tinygrad/tinygrad

.github/workflows/test.yml, test/mnist.py, tinygrad/utils.py
My boys smile more beautiful than the morning
https://github.com/geohot/tinygrad/issues/1
=> Run Tests in CI

README.md
Added Github action's status badge onto the readme
=> Test badge in readme

tinygrad/optim.py
While loop which rises t is meant till convergence so each optimiser step t=t+1
=> fixing adam

test/mnist.py, tinygrad/tensor.py
Maybe merge, idk? I don't like the dep and more code
=> use numba to double conv speed

test/test_tensor.py, tinygrad/gradcheck.py, tinygrad/utils.py
Hi there, my attempt for `gradcheck`. It is really simple: it computes the approx. of the Jacobian with Finite-Differences and checks if it is close to the one computed using `.backward()`. (It should also work with `Conv2d` when it will be ready...not sure though). 
Confidence: 70% :smile: it was funny.
=> tiny gradcheck

README.md, test/test_mnist.py, tinygrad/optim.py
Sorry for commenting out SGD, had to do the tests
=> added RMSprop optim

test/test_mnist.py, test/test_tensor.py, tinygrad/ops.py, tinygrad/tensor.py
My try at making the maxpool2d layer parametrizable.
It is implemented by adding all **kwargs that are passed as properties to the ctx object.
=> makes maxpool2d parameterizable

tinygrad/tensor.py
Please don't look at the other PR lol (closed).
Removed `logging`.
Moved `_ctx` back out of Class level.
=> Clean init function

tinygrad/gradcheck.py
the one loop in numerical_jacobian can be vectorized or not?
=> streamlined numerical_jacobian

test/test_ops.py, test/test_tensor.py, tinygrad/gradcheck.py, tinygrad/opsgpu.py, tinygrad/optim.py, tinygrad/tensor.py
Create PRs to this branch for GPU ops.
=> Add GPU Support! (do not merge yet)

test/test_ops.py, tinygrad/ops.py
@geohot this pr replaces the existing sigmoid with stable sigmoid.
This is a critical fix and this repo needs more attention like overflow and underflow,  e.g in div op.
=> Stable Sigmoid op

tinygrad/opsgpu.py
I'll work on backward, but might not get to it until later tonight. Feel free to do it yourself in the meantime if you want.
=> GPU {Avg,Max}Pool2D forward pass

test/test_ops.py, tinygrad/opsgpu.py
Thanks for the bugfix on the last one, btw.
=> Gpu AvgPool2D backward pass

examples/efficientnet.py
Reverts geohot/tinygrad#79
Hmm, I should have tested it. No window shows up on my Mac.
=> Revert "pygame is fine, cv2 can also do the trick"

test/test_ops.py, tinygrad/opsgpu.py, tinygrad/tensor.py
Just a draft. Anyone see the mistakes?
=> Conv2D backward on GPU

test/test_mnist.py, test/test_net_speed.py, test/test_ops.py, tinygrad/opsgpu.py, tinygrad/utils.py
We have a working GPU TinyConvNet now, and we're at 989.
=> GPU MaxPool2D.backward(); TinyConvNet train passes

test/test_ops.py
=> adds broadcasting test cases

test/test_ops.py, tinygrad/tensor.py
tanh non first class op 
using sigmoid
tanh = 2 * sigmoid(2 * x) - 1
=> :zap: tanh non first class op

test/test_ops.py, tinygrad/opsgpu.py
to reduce the number of lines (issue #112). pure python implementation for tuple to avoid additional constructor calls in forward.
=> refactoring of forward in reshape

tinygrad/tensor.py
backward 22.01 s
back_Conv2D :  81    19687.31 ms
back_Pow :  98     1137.16 ms
Conv2D :  81      986.24 ms
Sigmoid :  65      950.51 ms
Pow :  98      528.35 ms
back_Mul : 165      509.08 ms
Mul : 165      127.86 ms
back_AvgPool2D :  17      110.99 ms
back_Sigmoid :  65       96.07 ms
back_Sub :  49       81.16 ms
Add : 214       74.19 ms
back_Add : 140       59.01 ms
AvgPool2D :  17       50.21 ms
Pad2D :  17       33.29 ms
Sub :  49       28.01 ms
back_Dot :   1        2.00 ms
back_Reshape : 230        2.00 ms
Dot :   1        1.97 ms
Reshape : 230        0.00 ms
LogSoftmax :   1        0.00 ms
Sum :   1        0.00 ms
back_Sum :   1        0.00 ms
back_LogSoftmax :   1        0.00 ms
back_Pad2D :  17        0.00 ms
=> Fix train_efficientnet

tinygrad/tensor.py
These are a good example of what classmethods are generally used for; little wrappers around the constructor for alternative ways to init one.
The class is just passed into the method itself as the first param automatically, allowing for further abstraction if u ever start inheriting from classes using these ([further details](https://stackoverflow.com/a/12179752)).
=> use classmethods for Tensor helper funcs

tinygrad/tensor.py
- Formats the debug output to be nicely aligned
- Use f-strings for string interpolation
```
back_Conv2D : 856     6164.73 ms
Pow : 8783     4024.32 ms
back_Dot : 4231     2471.53 ms
Conv2D : 1228     1704.42 ms
MaxPool2D : 463     1406.54 ms
Dot : 4307     1002.26 ms
ReLU : 3326      773.55 ms
back_ReLU : 2881      708.28 ms
back_MaxPool2D : 436      653.26 ms
Mul : 19430      358.72 ms
LogSoftmax : 2305      142.64 ms
Sub : 8303      121.33 ms
Add : 7361      115.54 ms
back_Mul : 5319      103.48 ms
back_AvgPool2D :  42       70.24 ms
back_LogSoftmax : 2231       60.91 ms
AvgPool2D :  72       59.28 ms
Sum : 3025       46.34 ms
back_Sum : 3020       45.83 ms
back_Pow :  90       28.26 ms
Reshape : 434       12.65 ms
Sigmoid :  22        1.36 ms
back_Sub :  48        1.29 ms
back_Reshape …
```
=> Format debug output and use f-strings

test/test_ops.py, tinygrad/tensor.py
@marcelbischoff You know why this is broken?
=> Mean axis (doesn't work)

tinygrad/optim.py
=> :hammer: refactor optim

test/test_gc.py, tinygrad/tensor.py
...and sacrifice test speed.
We are getting too close to 1000 LOC, all lines matter!
=> Win more lines

setup.py
Install testing requirements:
```pip install -e ".[testing]"```
Install GPU requirements:
```pip install -e ".[gpu]"```
Not sure if these should be documented somewhere for ease?
=> Extra install requirements.

test/test_net_speed.py, tinygrad/ops_cpu.py, tinygrad/utils.py
- Removes some unused imports
- Avoids a few unnecessary calls to the range() function for the pooling ops
=> Minor clean up

tinygrad/tensor.py
Moving memory is slow, and therefor monitoring the time spent converting
and limiting the number of copy operations can improve performance.
GPU efficient net performs 500 copy operations to the GPU.
```GPU=1 DEBUG=1 python3 examples/efficientnet.py https://upload.wikimedia.org/wikipedia/commons/4/41/Chicken.jpg```
```
toGPU :    508     144.99 ms
Conv2D :     81      61.04 ms
Mul :    163      46.15 ms
Add :    140      36.60 ms
Pad2D :     17      28.51 ms
Pow :     98      20.30 ms
Sub :     49      15.66 ms
Reshape :    230      11.94 ms
Sigmoid :     65      11.09 ms
Dot :      1       5.74 ms
AvgPool2D :     17       5.63 ms
toCPU :      1       0.05 ms
```
=> Profile GPU and CPU copying.

examples/mnist_gan.py, tinygrad/tensor.py
An effort to generate mnist digits with tinygrad.
Added generator
added LeakyRelu.
added dropout.
=> :tada: effort to generate mnist data using GAN with tinygrad. [WIP]

examples/mnist_gan.py
=> tinygrad.utils to extra.utils fix in mnist_gan

tinygrad/ops_cpu.py, tinygrad/ops_gpu.py, tinygrad/tensor.py
Don't think this hurts readability all that much. 
From 1000 sloc, we are now down to 981.
=> Less lines

tinygrad/optim.py
More info [here](https://docs.python.org/3/library/functions.html#super).
=> super() without arguments

extra/efficientnet.py, extra/utils.py
hopefully this is what you meant with https://github.com/geohot/tinygrad/issues/193
I moved it to extra/utils.py since it's doing things
=> issue-193 - Move torch loader out of efficientnet code

test/test_mnist.py, test/test_ops.py, tinygrad/ops_cpu.py, tinygrad/ops_gpu.py
* backward pass now behaves like torch for ties on GPU
* implemented CPU max similar to GPU so it passes tests as well. Unfortunately, currently adds lines.
see #226
=> max to behave on ties like torch

tinygrad/ops_cpu.py, tinygrad/ops_gpu.py
This saves lines. And reduces redundant repetition.
=> Dynamically register ops to Tensor

.github/workflows/test.yml, extra/training.py, test/env.py, test/test_gc.py, test/test_mnist.py, test/test_net_speed.py, test/test_nn.py, test/test_ops.py, test/test_optim.py, test/test_tensor.py, tinygrad/tensor.py
=> Test split

examples/serious_mnist.py, examples/transformer.py, extra/training.py
Transformer gets them all correct (occasionally). Feel free to only add the `BS+1` in `training.py`.
* some parameters tweaked
* learning rate decay
* displaying what transformer gets wrong if accuracy is high
Sample Output:
```
loss 0.37 accuracy 0.87: 100%|██████████████████| 50/50 [00:05<00:00,  8.66it/s]
100%|███████████████████████████████████████████| 16/16 [00:00<00:00, 25.79it/s]
test set accuracy is 0.865583
reducing lr to 0.0025
loss 0.28 accuracy 0.89: 100%|██████████████████| 50/50 [00:05<00:00,  9.25it/s]
100%|███████████████████████████████████████████| 16/16 [00:00<00:00, 19.07it/s]
test set accuracy is 0.884583
reducing lr to 0.0021
loss 0.19 accuracy 0.92: 100%|██████████████████| 50/50 [00:05<00:00,  9.14it/s]
100%|███████████████████████████████████████████| 16/16 …
```
=> transformer >99.98% test accuracy in ~30s

extra/utils.py, tinygrad/ops_ane.py, tinygrad/ops_cpu.py, tinygrad/ops_gpu.py, tinygrad/tensor.py
=> :hammer: refactor register ops

test/test_ops.py, tinygrad/ops_cpu.py, tinygrad/tensor.py
mish (non first class) and softplus (first class) implementation.
if anyone can try to make softplus as second class please let me know.
#216
=> :zap: Added softplus and mish non stable

examples/serious_mnist.py, examples/yolo_nn.py, examples/yolov3.py, extra/augment.py, extra/kinne.py, extra/utils.py, tinygrad/ops_cpu.py, tinygrad/ops_gpu.py, tinygrad/tensor.py
isinstance is meant to be used inplace of type() here; more standard, faster and supports polymorphism.
also made some minor improvements, removed some unused imports & extra whitespace.
=> minor optimizations & cleaning

test/test_tensor.py, tinygrad/tensor.py
Create a tensor of shape (100,000,) and add a dropout with rate=0.01. We can then count the number of zeros in this tensor and expect it to be around 100,000 * 0.01 = 1000 with some tolerance.
=> Add dropout test

accel/ane/1_build/run.swift, tinygrad/ops_ane.py, tinygrad/tensor.py
1. python create model not match swift model in ane build folder.
2. fix ane lib path and add a dummy backward function for use_ane.py
can run in examples folder.
=> Fix ane bugs.

.github/workflows/test.yml
For #300. I added a -y flag to install OpenCL properly.
=> Fix OpenCL installation

examples/train_resnet.py, models/resnet.py
Can tranfer learn with arbitrary resnets in examples/train_resnet.py. Haven't figured out loading with fake_torch_load yet.
=> Transfer learning for ResNet

examples/yolo/yolo_nn.py
=> Fix yolo MaxPool2d param name

tinygrad/helpers.py, tinygrad/llops/ops_gpu.py, tinygrad/ops.py, tinygrad/shapetracker.py, tinygrad/tensor.py
=> batch from lazy branch

accel/lazy/ops_lazy.py, accel/opencl/conv.cl, accel/opencl/ops_opencl.py
=> opencl tests passed

.github/workflows/test.yml, setup.py
=> add mypy to ci testing

tinygrad/tensor.py
=> Make creation helpers use fp32 by default

README.md, extra/utils.py, test/test_gc.py, test/test_ops.py, test/test_tensor.py, tinygrad/nn/optim.py, tinygrad/tensor.py
=> set requires_grad to None

examples/serious_mnist.py, extra/augment.py
=> Reshape dataset from fetch_mnist

examples/stable_diffusion.py, tinygrad/shapetracker.py, tinygrad/tensor.py
remove explicit inherit from object.
=> remove redundant list comprehension from inside all.

test/test_ops.py
remove custom tolerances that don't appear to be needed.
=> enable tests in test_ops.py that are disabled but now work.

accel/llvm/ops_llvm.py, test/external_test_llvm.py, tinygrad/lazy.py, tinygrad/llops/ops_llvm.py, tinygrad/ops.py
=> LLVM Backend take 2

examples/serious_mnist.py, tinygrad/utils.py
Automatically release an updated version of tinygrad to PyPI by creating a release on github.
@geohot You will have to set repo secrets.
gotcha: The GitHub release version/tag does not effect the version uploaded to PyPI, this is based on `setup.py`. So this should be updated prior to creating the release.
=> Ci pypi release automation

tinygrad/mlops.py, tinygrad/tensor.py
Small changes that reduce line count without sacrificing readability.
=> Reduce line count

accel/llvm/ops_llvm.py
This change allows llvm to vectorize the max call
Speed after change on my intel Mac:
```
add                            1024x1024    1.01 ms in torch,    1.62 ms in tinygrad,    1.61x slower 234.40012 234.40012
add                            4096x4096   18.23 ms in torch,   22.03 ms in tinygrad,    1.21x slower 862.98096 862.98096
.add_sq                         4096x4096   52.45 ms in torch,   65.03 ms in tinygrad,    1.24x slower 2796576.5 2796576.5
.conv bs: 32 chans:  4 ->  32                2.94 ms in torch,    4.32 ms in tinygrad,    1.47x slower 72729.484 72729.48
conv bs: 32 chans: 16 ->  32                7.53 ms in torch,   69.81 ms in tinygrad,    9.27x slower -36285.277 -36285.273
conv bs: 32 chans: 64 ->  32               27.93 ms in torch,  283.47 ms in tinygrad,   10.15x …
```
=> Make max vectorize

accel/llvm/ops_llvm.py
A change to show the optimised IR under when running under DEBUG=4
=> Show optimised IR under debug 4

examples/stable_diffusion.py
confirmed with a bunch of print statements in the [official model](https://github.com/CompVis/stable-diffusion/blob/ce05de28194041e030ccfc70c635fe3707cdfc30/ldm/modules/diffusionmodules/openaimodel.py#L413)
=> confirmed UNetModel params

examples/stable_diffusion.py, test/test_nn.py, tinygrad/nn/__init__.py
=> Revert "Rename Normalize and move to nn"

.pre-commit-config.yaml, setup.py, tinygrad/ast.py, tinygrad/lazy.py, tinygrad/shape/__init__.py
=> Add commit hooks

accel/llvm/ops_llvm.py, tinygrad/ast.py
See https://github.com/geohot/tinygrad/pull/490#issuecomment-1407750705
=> Use force_create to allocate return buffer

tinygrad/helpers.py
=> Big make_pair changes

test/test_symbolic.py
=> Add symbolic tests for correctness

accel/ane/2_compile/hwx_parse.py, accel/cherry/tinygrad/cherry.py, examples/benchmark_train_efficientnet.py, examples/efficientnet.py, examples/mnist_gan.py, examples/serious_mnist.py, examples/train_efficientnet.py, examples/train_resnet.py, examples/transformer.py, examples/vit.py, examples/yolov3.py, extra/kernel_search.py, extra/onnx.py, extra/thneed.py, extra/training.py, extra/utils.py, openpilot/compile.py, test/external_test_gpu_ast.py, test/test_mnist.py, test/test_ops.py, test/test_speed_v_torch.py, test/test_train.py, tinygrad/graph.py, tinygrad/lazy.py, tinygrad/llops/ops_gpu.py, tinygrad/llops/ops_torch.py, tinygrad/ops.py, tinygrad/runtime/opencl.py, tinygrad/shape/__init__.py
=> Refactor getenv into helpers

accel/triton/ops_triton.py, extra/triton/test.py, setup.py, test/test_ops.py, tinygrad/llops/ops_triton.py
Works to add numbers, more soon.
@ptillet is there a way to not use torch for the buffers and instead use something like pycuda?
=> A Triton backend for tinygrad

examples/stable_diffusion.py, test/test_nn.py, tinygrad/nn/__init__.py
fixes https://github.com/geohot/tinygrad/pull/415 by splitting Normalize into GroupNorm and LayerNorm
>Comma AI's Kia EV6 arrives at Taco Bell
=> Rename Normalize and move to nn

README.md
installing tinygrad directly trough setup.py can cause issues as described in [this stackoverflow issue](https://stackoverflow.com/questions/19048732/python-setup-py-develop-vs-install)
=> adding more robust install method in readme

tinygrad/helpers.py, tinygrad/nn/optim.py, tinygrad/shape/symbolic.py
Using `isinstance` tuples.
These changes do not affect the functioning of the project. Just to make code tiny and more readable.
=> Tiny code improvements

examples/benchmark_train_efficientnet.py, examples/hlb_cifar10.py, extra/introspection.py, extra/kernel_search.py, extra/thneed.py, openpilot/compile.py, test/external_test_opt.py, tinygrad/llops/ops_gpu.py, tinygrad/ops.py, tinygrad/runtime/cuda.py, tinygrad/runtime/opencl.py
=> refactor to keep cl in the runtime

test/test_shapetracker.py, test/test_symbolic.py, tinygrad/llops/ops_gpu.py, tinygrad/shape/__init__.py, tinygrad/shape/symbolic.py
TODO: make this work for LLVM too
=> Symbolic render

examples/deep_deterministic_policy_gradient.py
Hi, I thought it would be nice to have a reinforcement learning example, so I implemented the Deep Deterministic Policy Gradient algorithm using Tinygrad. It seems to be slower compared to Pytorch and Tensorflow (I guess it's the forward propagations of the target networks in the learning step). Maybe someone has an idea how to speed it up.
=> Added reinforcement learning example

examples/hlb_cifar10.py, examples/serious_mnist.py, examples/yolov3.py, models/efficientnet.py, models/resnet.py, test/external_test_opt.py, test/graph_batchnorm.py, test/test_nn.py, tinygrad/nn/__init__.py
Replace BatchNorm2D with BatchNorm2d (matches PyTorch).
=> BatchNorm2D -> BatchNorm2d

examples/deep_deterministic_policy_gradient.py, examples/hlb_cifar10.py, examples/mnist_gan.py, examples/serious_mnist.py, examples/train_efficientnet.py, examples/train_resnet.py, examples/transformer.py, extra/training.py, extra/utils.py, test/graph_batchnorm.py, test/test_mnist.py, test/test_optim.py, test/test_train.py
get_parameters has been moved out of extra.utils, but is imported back to maintain compatibility. This PR replaces all imports from extra.utils to import from tinygrad.nn instead.
=> Import get_parameters from tinygrad.nn

examples/serious_mnist.py, models/transformer.py
with uniform, test accuracy is around 50%
but with scaled_uniform, we have >99.8%
=> Fix weight initialization

tinygrad/ast.py
Fixes #457
The problem is kernels like f(x) = x + x (1 in graph) and f(x, y) = x + y (2 in graph) have the same str(ast), but produce different kernels.
Topo sort fails, because cached kernel 1 is used for 2, but by including the bufs into the cache key(basically something like the function signature), there won't be a cache hit on 2, so everything works like expected.
Test is passing now:
=> Fix kernel cache key

extra/kernel_search.py, tinygrad/ast.py, tinygrad/llops/ops_gpu.py, tinygrad/runtime/cuda.py, tinygrad/runtime/metal.py, tinygrad/runtime/opencl.py
Despite the code being longer, openpilot model goes from 19.45 ms -> 19.35 ms
=> a sustainable approach to float4

.github/workflows/test.yml, README.md, test/external_test_opt.py, test/test_nn.py, test/test_ops.py, tinygrad/helpers.py, tinygrad/lazy.py, tinygrad/llops/ops_cpu.py, tinygrad/llops/ops_gpu.py, tinygrad/llops/ops_torch.py, tinygrad/mlops.py, tinygrad/ops.py, tinygrad/tensor.py
Too much of a hit to speed right now, but will be fixed and 100s of lines will be deleted :)
=> conv2d is an hlop

examples/compile_efficientnet.py, tinygrad/llops/ops_gpu.py, tinygrad/runtime/clang.py
as discussed on discord, results can roughly be seen in https://godbolt.org/z/Tb9jMxWfx (ideally this would be quantified with perf measurements at some point)
The efficientnet was tested with `-fsanitize=address,undefined` and it ran fine.
I added separate commits for minor changes which I can also remove if they are not wanted.
=> add restrict qualifier to inputs in c backend

setup.py, test/test_randomness.py
=> Add tests for randomness

examples/stable_diffusion.py
Just opens the rendered image in the default viewer after saving.
=> Opens image in default viewer after saving.

tinygrad/ops.py
=> Revert "less lines"

tinygrad/codegen/ast.py, tinygrad/codegen/gpu.py, tinygrad/codegen/llvm.py, tinygrad/graph.py, tinygrad/helpers.py, tinygrad/jit.py, tinygrad/lazy.py, tinygrad/nn/optim.py, tinygrad/ops.py, tinygrad/runtime/ops_clang.py, tinygrad/runtime/ops_cuda.py, tinygrad/runtime/ops_llvm.py, tinygrad/runtime/ops_metal.py, tinygrad/shape/__init__.py, tinygrad/shape/symbolic.py, tinygrad/tensor.py
Naively reduce number of lines (43 less lines), by using walrus operator, multi assignment, and removing new line for simple `if` and `for` statement
=> reduce number of lines

tinygrad/ops.py
=> One less line in consume_flops

examples/deep_deterministic_policy_gradient.py
=> Fixed DDPG example

examples/llama.py
=> Llama use pathlib

examples/llama.py
=> use pathlib over os.path

.gitignore, extra/gemm/metal_matmul.py, models/transformer.py, models/vit.py, test/test_ops.py, tinygrad/image.py, tinygrad/lazy.py, tinygrad/ops.py, tinygrad/runtime/ops_clang.py, tinygrad/runtime/ops_cuda.py, tinygrad/runtime/ops_gpu.py, tinygrad/runtime/ops_metal.py, tinygrad/tensor.py
memory tracking, better types.
=> good changes from llama branch

extra/onnx_ops.py, test/test_ops.py, tinygrad/tensor.py
=> Eq magic function support

.github/workflows/test.yml, .pre-commit-config.yaml, tinygrad/codegen/ast.py, tinygrad/codegen/gpu.py, tinygrad/codegen/llvm.py, tinygrad/graph.py, tinygrad/helpers.py, tinygrad/jit.py, tinygrad/lazy.py, tinygrad/nn/__init__.py, tinygrad/nn/optim.py, tinygrad/ops.py, tinygrad/runtime/ops_clang.py, tinygrad/runtime/ops_cpu.py, tinygrad/runtime/ops_gpu.py, tinygrad/runtime/ops_llvm.py, tinygrad/runtime/ops_metal.py, tinygrad/runtime/ops_torch.py, tinygrad/shape/shapetracker.py, tinygrad/shape/symbolic.py, tinygrad/tensor.py
Applied flake E203 rule: `var : type = value` becomes `var: type = value`
(sorry for the misunderstanding in the last PR)
=> apply flake8 E203 rule

examples/stable_diffusion.py, extra/utils.py
in `master` fails with
```python
TypeError: Dummy() takes no arguments
```
and after adding `__init__`
```python
UnpicklingError: state is not a dictionary
```
=> Add comments to SD

docs/abstractions.py
Fixed the import error for latest changes in master!
=> A fix for an import error in docs

examples/llama.py, extra/utils.py, test/extra/test_utils.py
Fixes exception mentioned in https://github.com/geohot/tinygrad/issues/687#issue-1620209645
now fails at
https://github.com/geohot/tinygrad/blob/cbc5a7222aca61f5378465e6b9e1bb678b4affa5/examples/llama.py#L254-L255
=> Fix llama 13B weights loading

test/test_optim.py, tinygrad/nn/optim.py
Added AdamW optimizer (3 lines).
I know that the challenge was to do it in only 2 lines, so no hard feelings if it doesn't get merged.
=> add AdamW optimizer

test/test_dtype.py, tinygrad/helpers.py, tinygrad/runtime/ops_cpu.py, tinygrad/runtime/ops_torch.py, tinygrad/tensor.py
for #694
- add support for cast in cpu and torch
- remove hack for Tensor.float
- implement Tensor.half
- more tests
=> casting: support all backends and implement half

test/test_ops.py, tinygrad/tensor.py
=> Added activation ops + tests

tinygrad/lazy.py
to avoid circular import when checking if backend is available in `_Device`'s `__init__` method
=> Device: move below LazyBuffer

test/external/external_test_opt.py, tinygrad/lazy.py, tinygrad/tensor.py
=> fix backward convs

test/external/fuzz_shapetracker.py, test/external/fuzz_symbolic.py, test/unit/test_shapetracker.py, test/unit/test_symbolic.py, tinygrad/codegen/cstyle.py, tinygrad/codegen/linearizer.py, tinygrad/lazy.py, tinygrad/shape/shapetracker.py, tinygrad/shape/symbolic.py, tinygrad/tensor.py
=> Remove Zeroview

test/test_randomness.py
To support #756 with the distribution test.
=> Statistics test: check if distributions match torch

tinygrad/codegen/cstyle.py, tinygrad/codegen/linearizer.py
=> Half4 load

extra/lr_scheduler.py, test/extra/test_lr_scheduler.py, test/test_lr_scheduler.py
Added three learning rate scheduler:
- MultiStepLR
- ReduceLROnPlateau
- CosineAnnealingLR
=> LR Schedulers

.gitignore, datasets/squad.py, examples/mlperf/helpers.py, examples/mlperf/metrics.py, examples/mlperf/model_eval.py, examples/mlperf/model_spec.py, models/bert.py
Language models are so much easier to write than RNN-T :sweat_smile:
=> Add mlperf bert model

count_tokens.py, sz.sh
Closes #743 
Token types are defined here : https://docs.python.org/3/library/token.html
To avoid inflating the token count with line breaks, comments, indents, only 4 types of tokens are counted : 
```python
TOKEN_WHITELIST = [
token.OP,
token.NAME,
token.NUMBER,
token.STRING
]
```
About `token.OP`:
> To simplify token stream handling, all [operator](https://docs.python.org/3/reference/lexical_analysis.html#operators) and [delimiter](https://docs.python.org/3/reference/lexical_analysis.html#delimiters) tokens and [Ellipsis](https://docs.python.org/3/library/constants.html#Ellipsis) are returned using the generic [OP](https://docs.python.org/3/library/token.html#token.OP) token type.
From https://docs.python.org/3/library/tokenize.html
Output:
```
File …
```
=> Count Python tokens

test/test_tensor.py, tinygrad/tensor.py
=> use tensor dtype for zeros_like()

extra/onnx_ops.py, tinygrad/tensor.py
Implemented the ONNX Conv1D as Conv2D, all the 8 Conv1D tests do pass. I detect, that it is a Conv1D, by the fact that the tensors are shape of length 3.
=> conv1d & conv3d onnx tests

.gitignore, extra/onnx_ops.py, test/external/external_test_onnx_backend.py, tinygrad/codegen/llvmir.py, tinygrad/helpers.py, tinygrad/runtime/lib.py, tinygrad/runtime/ops_clang.py, tinygrad/runtime/ops_torch.py
Added onnx And, Or, Xor, Not ops, also the bool dtype
Converted the previous casting on comparison ops from .numpy().astype to using Tensor.cast with the correct dtype  
Previous -  360 failed, 440 passed, 1692 skipped, 2 warnings in 32.11s
After       -  314 failed, 486 passed, 1692 skipped, 2 warnings in 33.58s
=> Onnx ops And, Or, Xor, Not

extra/onnx.py
Implements https://github.com/onnx/onnx/blob/main/docs/Operators.md#Shrink
Before: 330 failed, 496 passed, 1808 skipped, 2 warnings
After: 327 failed, 499 passed, 1808 skipped, 2 warnings
=> Add Onnx op Shrink

extra/onnx_ops.py
=> add onnx Binarizer op

test/test_ops.py, test/test_tensor.py, tinygrad/tensor.py
Added `Tensor.full` and `Tensor.full_like` and reused them in `zeros, ones, zeros_like, ones_like`
TODO
- need to improve the tests so we don't repeat code
=> add Tensor.full and Tensor.full_like and reuse them

extra/onnx.py
Before: `=== 329 failed, 497 passed, 1808 skipped, 2 warnings in 18.43s ===`
Now: `=== 315 failed, 511 passed, 1808 skipped, 2 warnings in 19.33s ===`
Might have the flaw that we now just assume that the type of the input is `float32`. How can we be sure?
=> Fix binary operation tests that have float as input

test/test_dtype.py, test/test_nn.py, tinygrad/codegen/cstyle.py, tinygrad/helpers.py, tinygrad/runtime/lib.py, tinygrad/runtime/ops_clang.py, tinygrad/runtime/ops_gpu.py, tinygrad/runtime/ops_metal.py
also added a helper function for checking if dtype is int and some dtype tests
=> support Int64 type in cstyle gen

test/test_dtype.py, tinygrad/codegen/llvmir.py, tinygrad/helpers.py
Added llvm int support
split the dtype tests so that int tests are now run for llvm runtime
=> Llvm int support

test/test_ops.py
=> added conv1d tests -> simple, padding, stride, asymmetric padding

extra/onnx.py, extra/onnx_ops.py
Before
=== 296 failed, 530 passed, 1808 skipped, 3 warnings in 21.67s ===
After
=== 294 failed, 532 passed, 1808 skipped, 3 warnings in 19.38s ===
=> ConstantOfShape ONNX test fixed.

extra/onnx_ops.py, tinygrad/tensor.py
Tests fixed:
- test_clip_default_inbounds_cpu 
- test_clip_default_max_cpu 
Before:
=== 294 failed, 532 passed, 1808 skipped, 2 warnings in 32.39s ====
After:
=== 292 failed, 534 passed, 1808 skipped, 2 warnings in 33.74s ====
=> Fixed test suite for Clip

docs/showcase.md
Followup to #900 with some additional fixes.
Gonna start documenting API after this.
Re stable diffusion: we should probably make sure that #834 isn't happening anymore.
=> quick doc fixups

test/test_ops.py, test/test_tensor.py, tinygrad/tensor.py
Extended the existing implementation to work with n-dimensional inputs with a specified axis. Also added relevant cumsum tests.
=> Add cumsum with n-dim inputs

test/test_ops.py, tinygrad/codegen/cstyle.py
We were appending f to NAN and INFINITY constatns, and now we don't!
Constants taken from https://www.gnu.org/software/libc/manual/html_node/Infinity-and-NaN.html
=> fix inf/nan codegen

extra/onnx_ops.py
=> Implement onnx MeanVarianceNormalization

tinygrad/tensor.py
made seed None by default, stable diffusion now generates a different image each time
=> made seed None by default -> numpy picks a random seed

examples/whisper.py
In response to a quote from latest stream (https://youtu.be/Mr0rWJhv9jU?t=13758)
=> Whisper: there is a better way to do that!

datasets/imagenet_download.py, docs/env_vars.md
hi, adding a python version of https://gist.github.com/antoinebrl/7d00d5cb6c95ef194c737392ef7e476a in a separate `imagenet_download.py`
=> imagenet download and prepare

.github/workflows/test.yml, extra/onnx.py, extra/onnx_ops.py
Fixed Prelu op to return correct value
Resolved negative values in slice bug breaking layernorm tests
Resolved Where op not casting to input tensor
Added: 
- OptionalHasElement
- OptionalGetElement
Removed tracing/warnings in CI to focus on failing tests and results
Now    - 227 failed, 597 passed, 1810 skipped, 2 warnings in 16.09s
=> fixes to Onnx ops LayerNormalization/Prelu and added OptionalHasElement/OptionalGetElement

tinygrad/codegen/assembly.py, tinygrad/codegen/assembly_ptx.py, tinygrad/codegen/cstyle.py, tinygrad/codegen/linearizer.py, tinygrad/helpers.py, tinygrad/ops.py, tinygrad/runtime/ops_cuda.py, tinygrad/shape/symbolic.py, tinygrad/tensor.py
A subset of RDNA assembly support, figured I'd merge this first.
We have to separate the notion of a "Runtime" and a "Compiler"
=> PTX assembly support

extra/onnx_ops.py, test/external/external_test_onnx_backend.py, test/test_ops.py, tinygrad/codegen/llvmir.py, tinygrad/runtime/ops_cpu.py, tinygrad/tensor.py
Adds floor/ceil ops to tensor and Onnx ops
Onnx ops after:
190 failed, 654 passed, 1790 skipped, 2 warnings in 15.17s 
Tested on:
- METAL
- CUDA
- GPU
- CPU
- TORCH
=> Adds floor/ceil

.github/workflows/test.yml
Marked as WIP, as I don't expect it work on the first try and github CI doesn't run on a fork for some reason.
=> cache gpuocelot build in cuda CI

.github/workflows/test.yml, test/Dockerfile
credits to [bdkiran](https://github.com/bdkiran)
changes made:
- enable docker test in CI
- run full set of tests in docker
- skip CLANG in multi-device test, I think we are missing dependencies
- copy current folder into docker container
- install python dependencies
=> Docker fix

examples/llama.py
No need to slice A and B twice in LLaMa complex multiplication
```
test/external/external_test_speed_llama.py::TestLLaMASpeed::test_llama_compile using <class 'tinygrad.runtime.ops_metal.MetalCodegen'>
testing llama python run time
built model
assigned empty tensors, doing warmup
codegen         mean runtime:  112.46ms, runs:   315.72,   82.73,   83.22,   84.40,   83.35,  121.45,   86.78,   90.19,   88.71,   88.05
methodcache     mean runtime:   88.56ms, runs:    75.47,  119.04,   81.63,   81.04,   79.23,   83.41,   82.42,   79.36,  122.67,   81.34
profile         mean runtime:  455.47ms, runs:   529.99,  515.67,  444.73,  426.64,  428.02,  471.64,  431.93,  435.21,  436.11,  434.71
```
```
test/external/external_test_speed_llama.py::TestLLaMASpeed::test_llama_compile using <class …
```
=> Optimization in llama.py

tinygrad/lazy.py, tinygrad/mlops.py, tinygrad/ops.py
=> movement ops aren't really ops

test/test_ops.py, test/unit/test_weak.py, tinygrad/helpers.py, tinygrad/lazy.py, tinygrad/nn/image.py, tinygrad/ops.py, tinygrad/tensor.py
=> realize hotspots

tinygrad/codegen/linearizer.py
Before:
```
#include <metal_stdlib>
using namespace metal;
kernel void E_32768_32_4(device float* data0, const device float* data1, uint3 gid [[threadgroup_position_in_grid]], uint3 lid [[thread_position_in_threadgroup]]) {
{ int gidx0 = gid.x;  /* 32768 */
{ int lidx1 = lid.x;  /* 32 */
float4 val1_0 = (float4)(((device float4*)data1)[((gidx0*32)+lidx1)]);
float val2_0 = 1.0f;
float alu0 = (val1_0.x+val2_0);
float alu1 = (val1_0.y+val2_0);
float alu2 = (val1_0.z+val2_0);
float alu3 = (val1_0.w+val2_0);
float4 alu4 = float4(alu0,alu1,alu2,alu3);
((device float4*)data0)[((gidx0*32)+lidx1)] = alu4;
}} /* global+local */
}
```
After:
```
#include <metal_stdlib>
using namespace metal;
kernel void E_32768_32_4(device float* data0, const device float* data1, uint3 gid …
```
=> Fix folding of float4 add/mul

tinygrad/codegen/linearizer.py
170 -> 135 ms / step on 7900XTX
=> cifar train speed

test/test_ops.py, tinygrad/tensor.py
for #1038 
Tests will fail for inf and nan, but it's likely caused by #942
=> Fix Tensor ceil and floor for whole numbers

.github/workflows/test.yml, docs/quickstart.md
* fix quickstart.md
* test quickstart in ci
=> Quickstart

examples/transformer.py
fixed a broken link to minGPT in the transformer example code
=> fix broken link

docs/quickstart.md, examples/benchmark_train_efficientnet.py, examples/deep_deterministic_policy_gradient.py, examples/hlb_cifar10.py, examples/mnist_gan.py, examples/serious_mnist.py, examples/train_efficientnet.py, examples/train_resnet.py, test/external/external_test_opt.py, test/external/graph_batchnorm.py, test/extra/test_lr_scheduler.py, test/models/test_end2end.py, test/models/test_mnist.py, test/models/test_train.py, tinygrad/nn/optim.py
Just a nice one-liner using list comprehension. Also fixes all tests that previously imported `get_parameters` from `tinygrad.nn.optim` or similar - removing that useless import at the end of `optim.py`.
=> Refactor nn.optim

tinygrad/nn/__init__.py, tinygrad/shape/shapetracker.py, tinygrad/tensor.py
Based on https://github.com/geohot/tinygrad/pull/1102
=> [perf] Replace more list comprehension with *

test/external/external_test_onnx_backend.py, test/test_dtype.py, test/test_tensor.py, tinygrad/codegen/assembly_rdna.py, tinygrad/codegen/cstyle.py, tinygrad/codegen/llvmir.py, tinygrad/helpers.py, tinygrad/runtime/lib.py, tinygrad/runtime/ops_gpu.py, tinygrad/runtime/ops_metal.py, tinygrad/runtime/ops_torch.py
Removes all `float64` instances along with all associated tests with them.
=> Remove float64

CONTRIBUTING.md
Meant to submit this when `CONTRIBUTING.md` was first written, but ended up forgetting about it :grimacing: 
Just some grammatical fixes/changes, makes it more readable. Also a small note about not sacrificing readability for speed.
=> CONTRIBUTING.md fixes

extra/training.py
add a return statement to the train function in order to provide access to the losses and accuracies lists
=> Add return statement to the train function

extra/gradcheck.py, test/test_tensor.py
`numerical_jacobian` is either bugged or not accurate enough, but this fixes the test for the `jacobian` function.
=> Fix: Jacobian tests [WIP]

tinygrad/runtime/ops_cuda.py
Also doing formatting as it's easier to compare ptx to cuda backend code.
orange - instruction or immediate value
purple - state space
blue - operand or identifier
green - type
white - modifier (be it infix or prefix)
=> add ptx formatter + syntax highlighter

test/test_tensor.py, tinygrad/tensor.py
manual_seed() has the wrong type None instead of int, this fails if we call it without argument: #1169
Added tests
=> fix Tensor.manual_seed() default to wrong type

examples/deep_deterministic_policy_gradient.py
float64 is not supported by tinygrad
=> Initialise numpy arrays as float32 in DDPG example

extra/datasets/coco.py, extra/datasets/imagenet.py, extra/datasets/imagenet_download.py, extra/datasets/kits19.py, extra/datasets/librispeech.py, extra/datasets/openimages.py, extra/datasets/squad.py
=> Update file paths in extra/datasets

tinygrad/tensor.py
=> remove superfluous parentheses

.github/workflows/test.yml, .pre-commit-config.yaml, test/test_ops.py, test/unit/test_shapetracker.py, tinygrad/codegen/cstyle.py, tinygrad/codegen/linearizer.py, tinygrad/helpers.py, tinygrad/runtime/ops_cuda.py, tinygrad/runtime/ops_gpu.py
So many hacks in cstyle, adding float2 is annoying.
=> Refactor load/store before tensor cores

tinygrad/tensor.py
See https://github.com/tinygrad/tinygrad/pull/1210#issuecomment-1627846455.
=> remove tuple from type annotation in Tensor.__init__

test/test_ops.py, tinygrad/tensor.py
Prerequisites for making things like cumsum fast.
=> remove contiguous on full

test/test_ops.py, tinygrad/tensor.py
[Fixes #1151](https://github.com/tinygrad/tinygrad/issues/1151).
=> Fix pow to work with negative tensors

docs/abstractions.py, test/test_tensor.py, tinygrad/tensor.py
=> Fix constant folding for Tensor([3])

.pylintrc, models/mask_rcnn.py, tinygrad/codegen/assembly.py, tinygrad/codegen/cstyle.py, tinygrad/codegen/linearizer.py, tinygrad/ops.py, tinygrad/runtime/ops_metal.py, tinygrad/shape/shapetracker.py, tinygrad/shape/symbolic.py, tinygrad/tensor.py
Some unnecessary of `else`/`elif` after returns. Could be a matter of taste.
I enabled the pylint option, that is optional,of course.
=> [READY] style: no-else-return

.github/workflows/test.yml, .gitignore, examples/compile_efficientnet.py, examples/webgpu/compile_webgpu.py, examples/webgpu/index.html, test/models/test_efficientnet.py, test/models/test_rnnt.py, test/models/test_train.py, test/test_dtype.py, test/test_nn.py, test/test_ops.py, test/test_specific_conv.py, test/test_webgpu.js, test/unit/test_disk_tensor.py, tinygrad/codegen/cstyle.py, tinygrad/codegen/linearizer.py, tinygrad/codegen/wgsl.py, tinygrad/jit.py, tinygrad/runtime/ops_webgpu.py, tinygrad/state.py
In collab with @[martinloretzzz](https://github.com/geohot/tinygrad/commits?author=martinloretzzz)
Closes #1030
=> Webgpu support

test/unit/test_symbolic.py, tinygrad/shape/symbolic.py
Simplify the logic, also fix an inconsistency that
`(a*6+b*6)//16 -> (((a*6)+(b*6))//16)` but `(a*6+b*6+16)//16 -> ((((a*3)+(b*3))//8)+1)`.
With the change now `(a*6+b*6)//16 -> (((a*3)+(b*3))//8)` too.
=> Simplify symbolic.SumNode.__floordiv__ logic

test/test_ops.py, tinygrad/tensor.py
The squeeze function pops the targeted dimension if its size is 1.
=> Added `tensor.squeeze` and support for testing exceptions

tinygrad/runtime/ops_cuda.py
nvcc --cubin error's when trying to compile PTX and can be skipped.
=> display sass for both cuda code and ptx

test/test_nn.py, tinygrad/nn/__init__.py
=> Added `nn.ConvTranspose1d`

examples/hlb_cifar10.py, extra/lr_scheduler.py, tinygrad/nn/optim.py
=> add contiguous to learning rate

extra/utils.py
`.mkdir` does not return the actual directory being created.
=> Moved mkdir in `utils.download_file` to diff line

test/test_speed_v_torch.py
@geohot 
Same as #1205 just reduced the tensor size to the 256 so that there wont be memory problem.
=> Re-open create cumsum speed test

extra/thneed.py, tinygrad/runtime/ops_gpu.py
initial part of #963
this also makes copyin actually async, using the same event tracking style that the metal backend is currently using.
=> cl fixes for multigpu

.github/workflows/test.yml, test/external/fuzz_shapetracker.py, test/external/fuzz_symbolic.py, test/unit/test_shapetracker.py, tinygrad/shape/symbolic.py
Modified the existing fuzz script and add to CI. It takes about 10 seconds each.
Want to get this in before making more changes in symbolics.
Tested locally that bad changes will reliably be caught.
Tested in CI that a bad changes will make CI fail.
=> Add Fuzz Test symbolic / shapetracker to CI.

test/external/external_test_opt.py, tinygrad/lazy.py
Reverts tinygrad/tinygrad#1187
=> Revert "Match Torch speed for sum reduction on M1"

tinygrad/runtime/ops_cuda.py
Replace path generated in f-string by os.path.join
=> fix CUDAProgram __init__ with DEBUG>=6 on Linux

test/test_ops.py, tinygrad/tensor.py
Added test_chunk and changed the implementation because previous one fails the tests. 
Test cases are bit mess right now as I tried to figure out how to test for mod != 0 and dimension tests.
I have changed the implementation (checks were failing).
=> Added test_chunk and fixed

.github/workflows/test.yml, examples/compile_efficientnet.py, examples/deep_deterministic_policy_gradient.py, examples/yolov8-onnx.py, examples/yolov8.py, extra/lr_scheduler.py, extra/onnx.py, extra/onnx_ops.py, extra/training.py, models/mask_rcnn.py, models/unet3d.py, test/test_conv.py
@geohot mentioned wanting this in the 7/20 daily voice call.  Added Pylint [trailing-whitespace / C0303](https://pylint.pycqa.org/en/latest/user_guide/messages/convention/trailing-whitespace.html) to CI linter job.
This causes the linter job to fail based on findings, if desired I can apply the suggested changes in this PR.
=> Add pylint trailing whitespace rule

test/test_dtype.py
Pretty straightforward DRY refactor of the test_dtypes.py file.
=> [GH-1305] Refactor test_dtypes.py to be cleaner

test/external/fuzz_symbolic.py, test/test_symbolic_shapetracker.py, tinygrad/shape/shapetracker.py, tinygrad/shape/symbolic.py
Part of #1259. Added type notations, some arithmetic support to make the stride work.
=> symbolic shapetracker part 1

test/test_ops.py, tinygrad/tensor.py
Reverts tinygrad/tinygrad#1298
=> Revert "Fix max nan"

examples/llama.py, test/external/external_test_speed_llama.py, test/models/test_real_world.py, tinygrad/state.py
Followup to https://github.com/tinygrad/tinygrad/pull/1275 which cleans up code reuse and introduces LLaMA-2 support.
=> Add LLaMA-2 support

test/test_ops.py, tinygrad/tensor.py
Fixes: #1251
It's kinda big and ugly, but it works, forwards and backwards.
=> Match torch on fractional negative base pow

test/test_tensor.py, tinygrad/helpers.py
Previous implementation of `argfix` had unreachable code at line 18 and the exception wasn't being caught at the right spot (`x[0]` used in line 16 but exception inside `if` block). 
Credit goes to Andriamanitra, but he wasn't planning on finishing his PR, so I did it instead.
https://github.com/tinygrad/tinygrad/pull/1226
=> Fix argfix and add tests

test/unit/test_shapetracker.py
fix the newly added EditorConfig Checker on CI
=> trim space

run_multibackend.sh
```console
$ ./run_multibackend.sh -c 'from tinygrad.lazy import Device; print(Device.DEFAULT)'
********* CPU *********
File "<string>", line 1
from
^
SyntaxError: invalid syntax
```
```console
$ ./run_multibackend.sh -c 'from tinygrad.lazy import Device; print(Device.DEFAULT)'
********* CPU *********
CPU
********* GPU *********
GPU
********* METAL *********
METAL
********* CLANG *********
CLANG
********* LLVM *********
LLVM
********* TORCH *********
TORCH
```
=> convert `$@` to `"$@"` in `run_multibackend.sh`

test/test_assign.py, test/test_conv.py, test/test_nn.py, test/test_ops.py, test/test_speed_v_torch.py, test/test_tensor.py, tinygrad/codegen/cstyle.py, tinygrad/codegen/linearizer.py, tinygrad/codegen/wgsl.py
Utilized hack from #1370 and made it generic to fit with any CStyleLanguage that contains a limit 
Closes #1313
=> Limit dims based on max size

tinygrad/runtime/ops_metal.py
Reverts tinygrad/tinygrad#1335
=> Revert "Improve Metal runtime command buffer handling"

.github/workflows/test.yml
use https://github.com/vegardit/fast-apt-mirror.sh to find a better apt mirror because the azure one behaves strangely at times and this should help it be more stable.
=> Make cuda CI a bit more consistent

examples/whisper.py, tinygrad/runtime/ops_gpu.py
First PR, just wanted to remove dependencies to torch, torch audio since librosa has all the same functionality already
=> Removed dep of torch, torchaudio, kept librosa only

test/test_helpers.py, tinygrad/helpers.py
Found a bug in my recent #1331 PR that was not present in the original code.
Added a test for this and fixed the bug.
=> fix: Context

test/test_ops.py, tinygrad/tensor.py
With this PR we can match with torch API, Also we can use this in the onnx as this will be compatible in constant mode
=> inf, -inf support for pad

examples/stable_diffusion.py, examples/vits.py, models/bert.py, test/external/external_test_opt.py
I was just browsing the code and found some misspelled words, thought i might correct them. Maybe kind of a dickhead move for a first commit but fuck it.
=> Corrected a few misspelled words

tinygrad/renderer/wgsl.py, tinygrad/runtime/ops_webgpu.py
Also added an assert in the call for max bufs so it doesnt go to rust and fail there
=> Moved global max and local max to LinearizerOptions for webgpu

tinygrad/shape/shapetracker.py
The function was created a year ago. Later code calls `View()` directly. Removing assert type check should be fine as long as mypy passed. Removed a manually passing `strides_for_shape(new_shape)` arg, which is re-computed anyway in `View()`.
Also replaced the last line of `strides_for_shape` with helper function `filter_strides`
=> remove view_from_shape

test/external/external_test_opt.py, test/models/test_real_world.py, tinygrad/lazy.py
Match Torch speed for sum reduction on M1
=> Match Torch speed for sum reduction on M1

test/external/external_test_speed_llama.py
=> use fake buffer for external_test_speed_llama.py

test/test_ops.py, tinygrad/renderer/llvmir.py
=> fix cast bool->float in llvmir

.github/workflows/test.yml
Two pytests with missing -n=auto.
=> [READY] ci: missing n=auto

examples/llama.py
`JIT=1` chat is broken now because user input has variable length. this is a quick patch. after inner attention became jittable, the correct separation will be `if Mask is None` for the whole transformer.
it's probably not worth it to jit when `Mask is not None` though given that it's called only once every chat loop, and the additional complexity is non-trivial (need arange a variable and slice with a variable)
=> patch JIT llama chat mode

examples/llama.py
eh my bad, i only tested for 2 convo and we don't use jit until the third call...
#1496
=> correct patch JIT llama chat

.github/workflows/benchmark.yml
From: https://github.com/orgs/community/discussions/26409#discussioncomment-3251822
=> don't try to run benchmark on forks

.github/workflows/benchmark.yml
- feat: don't try to run benchmark on forks
- fix: i hate yaml
- feat: am dumb
- feat: am dumb 2
=> dont run on fork

examples/stable_diffusion.py
Reverts tinygrad/tinygrad#1513
=> Revert "SD: Refactor AttnBlock, CrossAttention, CLIPAttention to share code"

examples/stable_diffusion.py
Sorry, I was running with -O so it didn't catch the error. This should be fixed now thanks to @terafo.
Results:
=> [New] SD: Refactor AttnBlock, CrossAttention, CLIPAttention to share code

models/bert.py, setup.py, test/models/test_bert.py
Changes made:
- compute attention with ```Tensor.scaled_dot_product_attention```
- add tests ```test/models/test_bert.py```
=> Bert: use Tensor.scaled_dot_product_attention

test/unit/test_shapetracker.py, tinygrad/shape/shapetracker.py
This reverts commit cf2bf1518d4bc60c0d1c671853613180c57eb4f3.
=> Revert "Better reshape (#1423)"

test/test_dtype.py, tinygrad/codegen/assembly_arm64.py, tinygrad/renderer/llvmir.py, tinygrad/runtime/ops_metal.py, tinygrad/runtime/ops_torch.py, tinygrad/runtime/ops_webgpu.py
Includes f64 tests and f64 support for 
- LLVM
- torch
- ARM Assembly
Included asserts for:
- METAL
- WEBGPU
=> Torch/LLVM/arm F64 support

test/test_uops.py, tinygrad/renderer/llvmir.py
* Adds int32 ops to LLVM 
* Need to do some more digging as to why mul_bool doesn't work
=> Fix uops int32 for llvm

extra/onnx.py, extra/onnx_ops.py, test/external/external_model_benchmark.py
**Bounty:** _onnx commavq model running and tested #1494_
TODO
```
VAL=1 python3 test/external/external_model_benchmark.py
```
=> Run onnx commavq model

test/test_symbolic_ops.py, tinygrad/runtime/ops_cuda.py
support CUDA for #1353 . I don't have a device to test, but the implementation is similar to other backend and CI passes
=> Support arg int for CUDA kernel

docs/quickstart.md, examples/serious_mnist.py, extra/training.py, test/test_nn.py, tinygrad/tensor.py
Updated `docs/quickstart.md`, `examples/serious_mnist.py`, `extra/training.py` accordingly after adding the function into `tensor.py`
~~Also, I deleted `examples/hlb_cifar10_torch.py` since its not going to be further updated.~~
=> sparse cat cross entropy

tinygrad/codegen/assembly.py, tinygrad/codegen/assembly_arm64.py, tinygrad/codegen/linearizer.py, tinygrad/codegen/optimizer.py, tinygrad/lazy.py, tinygrad/renderer/cstyle.py, tinygrad/renderer/wgsl.py, tinygrad/runtime/ops_gpu.py, tinygrad/shape/shapetracker.py, tinygrad/shape/symbolic.py, tinygrad/tensor.py
Check for existence, not `len`.
=> perf: no len if it is not needed

tinygrad/tensor.py
Before
```
Total time: 4.13324 s
File: /home/rvd/src/roelofvandijk/tinygrad/tinygrad/tensor.py
Function: _broadcasted at line 579
579                                             @profile
580                                             def _broadcasted(self, fxn:Type[Function], other:Union[Tensor, float], reverse:bool=False) -> Tensor:
581     42921     107249.3      2.5      2.6      dtype = self.dtype if self.dtype != dtypes.bool and self.dtype.__class__ is not ImageDType else dtypes.float32
582     42921       9421.7      0.2      0.2      x: Tensor = self
583     42921     172293.4      4.0      4.2      y: Tensor = Tensor(cast(float, other), device=self.device, …
```
=> perf: faster broadcasted

docs/quickstart.md, examples/hlb_cifar10.py, examples/llama.py, examples/mlperf/model_eval.py, examples/train_efficientnet.py, examples/whisper.py, extra/training.py, models/rnnt.py
There are more np.argmax than this PR. I have not touched them as i did not want to change the behaviour accidentally.
Only changed rather seemingly safe part.
Note: I did not test the models as I am unable to do so.
=> np.argmax to Tensor.argmax

tinygrad/tensor.py
Can be considered similar to #1440 
Made eye load from constant,
I believe cumsum is much more readable, repeat has kind of duplicate code, made chunk more readable 
I do not think this is considered code golf, if so please inform me which parts
=> Readability for unreadable functions

tinygrad/helpers.py
Moved over from https://github.com/tinygrad/tinygrad/pull/1605
=> [ready] perf: faster partition

docs/quickstart.md
=> Fix link to state.py in quickstart

examples/gpt2.py, test/external/external_test_embedding.py, tinygrad/codegen/linearizer.py, tinygrad/codegen/optimizer.py, tinygrad/nn/__init__.py
Getting ~10ms/tok
Record:
`ran model in 35.95 ms, 9.83 ms on GPU, 0.82 GOPS, 0.90 GB, 91.24 GB/s`
It's a tragic 491 kernels.
=> make embedding and GPT-2 fast

test/test_ops.py, tinygrad/tensor.py
=> do not replace divs with muls for non-floats

docs/quickstart.md
Upgrade the section "Training" in `docs/quickstart.md` to contain the newest implementation of `sparse_categorical_crossentropy`, which has not changed logically but is more concise than before.
Remove `indexing a tensor with another tensor` as an example of what tinygrad does not support, since this is no longer true (see [1]) and can also be a big disappointment for newcomers, since indexing a tensor with another tensor is quite useful and common.
[1]: https://github.com/tinygrad/tinygrad/pull/1399
=> Quickstart: Upgrade section "Training" to new code

.github/workflows/test.yml, openpilot/compile.py, test/external/external_model_benchmark.py, test/models/test_onnx.py
Should fix CI.
I am not very familiar with openpilot and onnx. Attempted to fix by checking errors and source https://github.com/commaai/openpilot/blob/57ad4f02f8e693639262aa3a982be8ed6c433ee0/selfdrive/modeld/modeld.py#L65.
=> update openpilot supercombo.onnx to 0.9.4

examples/hlb_cifar10.py
=> remove FAKEDATA in CIFAR

tinygrad/lazy.py
This is a surprisingly big one. Constant definition in while loop in for loop in busy function.
There are other place in the codebase that do something similar (define a const dict for a lookup every time anew).
Also uses `is` instead of `==` for singletons.
There is more to optimize here (use of tuples, doesn't need a `while`) but that's for another MR to keep this small.
```
Before
Total time: 1.51153 s
File: /home/rvd/src/roelofvandijk/tinygrad/tinygrad/lazy.py
Function: _push_movement_ops at line 306
306                                           @profile
307                                           def _push_movement_ops(srcs:Tuple[LazyBuffer, ...]) -> …
```
=> [ready] perf: constant in while in for in busy func

tinygrad/shape/shapetracker.py
Also part of https://github.com/tinygrad/tinygrad/pull/1605, but screwing up the diff there.
=> [ready] perf: avoid reshaping if not necessary

.github/workflows/benchmark.yml
* feat: specify shell
* feat: specify shell for mac
=> pipefail benchmark (#1709)

examples/stable_diffusion.py
This should fix the index problem in the stable diffusion
=> Fix: Stable Diffusion index

.github/workflows/test.yml, examples/llama.py, test/test_symbolic_jit.py, tinygrad/jit.py, tinygrad/runtime/ops_gpu.py, tinygrad/shape/shapetracker.py, tinygrad/shape/symbolic.py
python 3.11
master python runtime: ~8.1ms
remove JIT call in TransformerBlock: ~7.3ms
+ `-O`: ~7.0ms
=> llama JIT python runtime speedup

test/unit/test_symbolic.py, tinygrad/codegen/linearizer.py, tinygrad/shape/symbolic.py
Since refactoring the linearizer seems to be important right now, I wanted to get more familiar with it.
Found a TODO which I could easily do and thought it would be good to implement.
Removes many unnecessary isinstance calls, adds one line of code in total.
First time contributing - I hope I did everything correctly.
=> added visitor pattern

test/test_allocators.py, test/test_tensor.py, tinygrad/runtime/lib.py
=> allow zerosized tensors

tinygrad/codegen/kernel.py, tinygrad/codegen/optimizer.py, tinygrad/lazy.py, tinygrad/nn/image.py, tinygrad/runtime/ops_cpu.py, tinygrad/tensor.py
Use enumerate or direct iteration instead of `range(len(abc)`
=> [ready] refactor: enumerate

extra/hip_wrapper.py, tinygrad/runtime/ops_hip.py
We assume that all the devices are the same, but we kinda already do that for opencl.
=> hip multidevice

tinygrad/codegen/optimizer.py, tinygrad/codegen/search.py
A bit better search of shapes using dividers instead of consts + search for group_for_reduce dim.
=> search for grouped reduces

test/test_ops.py, tinygrad/tensor.py
cleean refactooooooooooooors only (maybe)
still potential lines to be reduced in fancy indexing.
wip
wip
wip
=> Make __getitem__ TINYer

.github/workflows/test.yml, test/models/test_real_world.py, tinygrad/codegen/search.py
Check kopt correctness comparing output after applied optimization and before.
=> test kopt correctness

test/models/test_real_world.py
KeyError fixed, now the test does not fail
=> KeyError fixed.

setup.py
https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#platform-specific-dependencies
used syntax from here :s
=> Metal stuff pip install on default when on Darwin

examples/stable_diffusion.py
useful for testing correctness of model runs
=> add seed option to stable_diffusion

tinygrad/tensor.py
Reverts tinygrad/tinygrad#1786
=> Revert "fix attn_mask None issue"

test/external/external_model_benchmark.py
Not too sure if this is a proper way of writing try, except :c
I haven't written many of these
It allows openpilot to be ran though.
also sry for missing this in the onnx PR :c
=> fix try except not catching fxn() in benchmark

examples/llama.py
=> convert llama `precompute_freqs_cis` into tinygrad

test/test_cache_collector.py, tinygrad/jit.py, tinygrad/ops.py, tinygrad/runtime/lib.py
=> fix jit buffer reuse when freed

extra/utils.py
print how the lazydata of a tensor is constructed
```python
from extra.utils import printtree, Tensor
printtree(Tensor.randn())
```
```
0 ━┳ MUL 
1  ┣━┳ SIN 
2  ┃ ┗━┳ SUB 
3  ┃   ┣━━ CONST 1.5707963267948966
4  ┃   ┗━┳ MUL 
5  ┃     ┣━┳ RESHAPE 
6  ┃     ┃ ┗━┳ SHRINK ((0, 1),)
7  ┃     ┃   ┗━━ RAND 1694128620
8  ┃     ┗━━ CONST 6.283185307179586
9  ┗━┳ SQRT 
10    ┗━┳ MUL 
11      ┣━┳ MUL 
12      ┃ ┣━┳ LOG2 
13      ┃ ┃ ┗━┳ SUB 
14      ┃ ┃   ┣━━ CONST 1
15      ┃ ┃   ┗━┳ RESHAPE 
16      ┃ ┃     ┗━┳ SHRINK ((1, 2),)
17      ┃ ┃       ┗━━ RAND 1694128620
18      ┃ ┗━━ CONST 0.6931471805599453
19      ┗━━ CONST -2
```
=> utils.printtree

examples/stable_diffusion.py, test/test_assign.py, tinygrad/tensor.py
=> patch to remove hack from stable_diffusion.py

test/test_speed_v_torch.py, tinygrad/codegen/linearizer.py, tinygrad/renderer/cstyle.py
also minor changes to test_speed_v_torch.py and size of UOps.SPECIAL
=> linearizer: support local and group_for_reduce dimensions together

test/models/test_real_world.py, test/test_linearizer.py, tinygrad/codegen/optimizer.py, tinygrad/codegen/search.py
Made kopt to work with local+grouped reduce and a bit change limits of kopt to make search space smaller.
Added test for local+grouped reduce and some other transformations
=> kopt works with local+grouped reduce and tests

extra/utils.py, test/extra/test_extra_helpers.py, test/test_symbolic_shapetracker.py, test/unit/test_shapetracker.py, tinygrad/codegen/kernel.py, tinygrad/codegen/optimizer.py, tinygrad/helpers.py, tinygrad/lazy.py, tinygrad/nn/state.py, tinygrad/shape/shapetracker.py, tinygrad/shape/view.py
I manually adjusted 2 apply rejects from imports. everything else is from the patch
btw we don't support symbolic shape toCPU so assert should be fine
=> apply view.py patch

.github/workflows/test.yml, setup.py
It runs the smallest model. The whole step took about 21 seconds, so I just appended it to KOPT test (renamed to Real World Test) to save github action workers.
=> run gpt2 in CI

.github/workflows/szdiff.yml, sz.py, tinygrad/tensor.py
Base on #895.
Add a diff mode to `sz.py` when it detects more than 2 arguments `source dir` and `target dir` which are specified in `szdiff.yml`. It's default action is still to show the total line count. Also set `skip_unchanged` and `ignore_empty` in CI to `true` to prevent the bot from spamming.
~~The output format and some test commits (line changes, same lines changes to skip, no changes ignore) that I did can be found in https://github.com/g1y5x3/tinygrad/pull/2~~
=> add line changes diff bot to CI

examples/gpt2.py
The same as in SD, helps for testing
=> add seed to gpt-2

.github/workflows/szdiff.yml
Since this PR branch is not the target the of pull request, the test won't be triggered here. Once it is merged to the master branch (or can be any other branches), other PRs targeting the master will trigger this test properly. 
Tested in the following scenarios:
1. created a pr within the fork but different branch using the same account - https://github.com/g1y5x3/tinygrad/pull/5#issuecomment-1722142188
2. created a pr from a different fork and branch but still using the same account - https://github.com/g1y5x3/tinygrad/pull/6#issuecomment-1722145324
3. created a pr from a different fork and branch using a difference account - https://github.com/g1y5x3/tinygrad/pull/7#issuecomment-1722147996
=> add comment bot to CI

extra/utils.py
shows Lazybuffer in tree. usefull for understanding codegen.
can now print any lazyop or buffer not just tensor
no new lines
=> polish print_tree

tinygrad/codegen/kernel.py, tinygrad/lazy.py, tinygrad/ops.py
filled the types of Any and replaced many `# type: ignore` with 2 asserts
=> lazy type annotation and cleanups

test/test_symbolic_jit.py, test/test_symbolic_ops.py
LLVM works after: https://github.com/tinygrad/tinygrad/pull/1652
Wanted to add HIP too but isn't in CI yet :(
=> Enable symbolic ops tests for LLVM

docs/abstractions.py, test/models/test_real_world.py, test/test_custom_function.py, test/test_linearizer.py, test/unit/test_flopcounter.py, tinygrad/codegen/kernel.py, tinygrad/codegen/linearizer.py, tinygrad/codegen/optimizer.py, tinygrad/codegen/search.py, tinygrad/lazy.py, tinygrad/ops.py, tinygrad/runtime/lib.py, tinygrad/runtime/ops_hip.py, tinygrad/runtime/ops_metal.py, tinygrad/shape/view.py
Reverts tinygrad/tinygrad#1905
=> Revert "All LazyOps in the Linearizer"

docs/abstractions.py, test/test_custom_function.py, test/test_symbolic_shapetracker.py, test/unit/test_flopcounter.py, test/unit/test_shapetracker.py, tinygrad/codegen/kernel.py, tinygrad/codegen/linearizer.py, tinygrad/codegen/optimizer.py, tinygrad/lazy.py, tinygrad/ops.py, tinygrad/shape/shapetracker.py
@roelofvandijk I know you've been pushing for this. I've come around on dataclass too.
=> Make ShapeTracker Immutable

tinygrad/runtime/ops_hip.py
=> fix hipgraph exec

docs/quickstart.md, examples/hlb_cifar10.py, examples/mlperf/model_train.py, examples/simple_conv_bn.py, examples/train_efficientnet.py, extra/datasets/__init__.py, extra/training.py, test/external/external_test_opt.py, test/external/graph_batchnorm.py, test/models/test_end2end.py, test/models/test_real_world.py, test/test_schedule.py, test/test_symbolic_ops.py, test/test_tensor.py, tinygrad/tensor.py
most of the line addition/removal are caused by the indentation when applying `with Tensor.train()`
=> with Tensor.train()

test/test_tensor.py, tinygrad/lazy.py
=> fix transfer to mapped buffers

extra/thneed.py, test/test_cache_collector.py, tinygrad/jit.py, tinygrad/runtime/lib.py
Cache collector is a bit simpler (i hope) and more performant.
- SD 6.54 -> 6.05 GB
- hlb_cifar 2.40 -> 2.04 GB
Others are the same or slightly better.
This is an intermediate step while I am looking on how to embed this into lazy, but this might help with unet training.
=> simplify CacheCollector

examples/train_efficientnet.py
- Adds a missing colon from previous commit (https://github.com/tinygrad/tinygrad/pull/1935)
- Fixes issues for cifar10 dataset
This also resolves https://github.com/tinygrad/tinygrad/issues/1573
=> Fix examples/train_efficientnet 

test/test_cache_collector.py, tinygrad/jit.py
This should fix jitted DIST=1 execution. I tested it on my intel mac (with integrated and discrete cards). Should be tested on a tinybox before merge.
=> fix jitted dist

.github/workflows/test.yml, test/test_custom_function.py, test/test_jit.py, test/test_lazybuffer.py, tinygrad/lazy.py, tinygrad/ops.py, tinygrad/realize.py
=> unrealized consts everywhere

docs/abstractions.py, examples/handcode_resnet50_opt.py, extra/kernel_search.py, test/models/test_real_world.py, test/test_linearizer.py, tinygrad/codegen/kernel.py, tinygrad/codegen/linearizer.py, tinygrad/codegen/optimizer.py, tinygrad/codegen/search.py
Is there a specific reason we have the process()? Seems redundant to me.
=> no process() in Linearizer

extra/gemm/metal_matvec.py, tinygrad/codegen/optimizer.py, tinygrad/renderer/cstyle.py, tinygrad/runtime/ops_gpu.py
Bringing this back with a fix for nvidia opencl shared memory alignment issues (the tests in `test/test_linearizer.py` already cover the issue, so I didn't add any).
=> optimizer: add matvec optimizations

examples/llama.py
the first shrunk freqs_cis was not used
=> simpler llama - don't shrink twice

tinygrad/codegen/optimizer.py
Reverts tinygrad/tinygrad#1996
=> Revert "allow local + grouped reduce in hand_coded"

extra/gemm/simple_matmul.py, tinygrad/codegen/linearizer.py, tinygrad/renderer/cstyle.py
also add cache defeat to extra/gemm/simple_matmul.py
This is now the prerequisite to #1882
=> wmma: clean up to make WMMA arg order consistent

setup.py
the features change broke using tinygrad as a package.
=> add `tinygrad.features` to setup.py

tinygrad/renderer/llvmir.py
Added a better description of what that piece of cryptic code does
=> Fix comment to describe code

examples/gpt2.py, examples/llama.py, test/test_custom_function.py, test/test_symbolic_jit.py, test/test_symbolic_ops.py, test/test_symbolic_shapetracker.py, tinygrad/codegen/linearizer.py, tinygrad/features/kopt.py, tinygrad/jit.py, tinygrad/lazy.py, tinygrad/ops.py, tinygrad/realize.py, tinygrad/shape/shapetracker.py, tinygrad/shape/symbolic.py, tinygrad/shape/view.py
update based on #1962 making a new draft. (1) added Variable.bind, (2) removed var_vals from LazyBuffer, (3) implemented ShapeTracker.unbind and used in jit check
=> Variable.bind newer

test/test_linearizer.py
must use apply_tensor_core instead of hand_coded_optimizations
=> test: fix test_linearizer.test_tensor_core test

.github/workflows/test.yml, test/external/external_test_opt.py, tinygrad/lazy.py
This reverts commit 63869c62fc1dc6b2371e01cab5e21968c113ce53.
=> Revert "openpilot kernel fix from 209 to 207 (#2006)"

examples/stable_diffusion.py
Expose `unconditional_guidance_scale` as a command line param. Would be nice to have it on the web stable diffusion demo site.
=> Stable diffusion: make guidance modifiable

.github/workflows/test.yml, openpilot/compile2.py, test/external/external_test_opt.py, tinygrad/features/image.py, tinygrad/lazy.py, tinygrad/realize.py
This reverts commit 924ecc4d6a05327814d9b373beafdef6383ddaf1.
=> Disable logging in early compile2 and lower kernel counts

test/unit/test_symbolic.py, tinygrad/shape/symbolic.py
Mathematically seems true also tests pass.
=> MulNode.__lt__ rule

examples/hlb_cifar10.py, extra/dist/__init__.py
```
❯ mypy examples/hlb_cifar10.py
Success: no issues found in 1 source file
```
=> fix: hlb cifar types

test/test_linearizer.py, tinygrad/codegen/optimizer.py, tinygrad/features/search.py, tinygrad/runtime/ops_llvm.py
Also added OptOps.UPCASTMID to constrain valid axes for opts with group_for_reduce.
=> optimizer: add test for correctness of opts

test/test_tensor.py
Issue: #1751
Original repro attempt: #2132
Fix: #2128
=> Test for #1751

tinygrad/runtime/ops_gpu.py
repro: #2134
old attempt: #2128
=> Fix for #1751

examples/handcode_resnet50_opt.py
`beam_search` supports cache now
=> remove shelve from handcode_resnet50_opt.py

examples/gpt2.py, examples/llama.py
they just crashed (dividing by 0), since timings are not available any more for debug=1.
=> fix debug=1 llama/gpt2 timings

extra/hip_wrapper.py, test/test_exec.py, tinygrad/ops.py, tinygrad/runtime/ops_hip.py
Refactor hipgraph to share "split into batches" logic with cudagraph.
Added test to check how batches are created.
Simplify hipgraph creation.
=> Refactor hipgraph

.github/workflows/test.yml, test/test_linearizer.py, tinygrad/codegen/kernel.py, tinygrad/codegen/linearizer.py, tinygrad/codegen/optimizer.py
This PR fixes HIP TC and preserves the TC=2 behavior.
=> wmma: refactor tensor cores using existing local dims

.github/workflows/test.yml
My changes got accepted into master so I'm switching tests to the main ocelot repo as promised
=> switch ocelot back to main repo

tinygrad/renderer/cuda.py, tinygrad/runtime/ops_cuda.py
split the cstyle parts into `renderer` like other backend and added the headers for using tensor cores that I am working on.
=> adding cuda TC headers

test/test_linearizer.py, tinygrad/codegen/optimizer.py, tinygrad/features/search.py
Reverts tinygrad/tinygrad#2162
=> Revert "optimizer: simplify GROUP and LOCAL to have one of each"

.github/workflows/test.yml, examples/compile_efficientnet.py, examples/index.html, extra/export_model.py, test/extra/test_export_model.py, test/test_webgpu.js, tinygrad/renderer/cuda.py
Support for models that typically return multiple tensors (eg, regression + confidences in SSD)
=> Enable Multi-Output Export

test/test_allocators.py, tinygrad/runtime/lib.py, tinygrad/runtime/ops_gpu.py
GPU=1 `copyout` allocates one more buffer on the gpu, so ensure that we have enough vram.
Fixes #1989
=> Fix cl map buffer

test/test_linearizer.py, tinygrad/codegen/kernel.py
i think `limit_dims_to_max` is wrong, this PR makes it less wrong by ensuring the iterator don't go out of bound. the goal is to unblock debugging #2209 
happy to refactor the whole thing, there's really no test for the intended behavior though
=> less broken limit_dims_to_max

extra/gemm/metal_matmul.py, extra/gemm/metal_matvec.py
Updated metal_matmul.py and metal_matvec.py. Both of these were not running since [03cf0af](https://github.com/tinygrad/tinygrad/commit/03cf0afa4f2ad477fb41c22b3dbecb6023b2966f).
=> update metal matmul and matvec for compile api

test/test_dtype.py, tinygrad/codegen/linearizer.py, tinygrad/renderer/cstyle.py, tinygrad/renderer/llvmir.py, tinygrad/renderer/triton.py
Reverts tinygrad/tinygrad#2046
=> Revert "Internal casting support"

examples/gpt2.py, examples/llama.py, tinygrad/tensor.py
=> pad None means (0,0)

examples/stable_diffusion.py
we really have 3 attention blocks in sd...
=> clean up attentions in stable diffusion

.github/workflows/test.yml, extra/helpers.py, mypy.ini, tinygrad/graph.py, tinygrad/lazy.py, tinygrad/renderer/llvmir.py, tinygrad/renderer/triton.py, tinygrad/runtime/lib.py, tinygrad/runtime/ops_cuda.py, tinygrad/runtime/ops_gpu.py, tinygrad/runtime/ops_llvm.py, tinygrad/runtime/ops_metal.py, tinygrad/runtime/ops_shm.py, tinygrad/runtime/ops_webgpu.py, tinygrad/tensor.py
* replace `axis.__class__ is int` with `isinstance(axis, int)` to make mypy happy
* add `--warn-unused-ignores` to mypy flag
refs #2240
=> refactor/ci: delete many `# type: ignore`

examples/llama.py, test/external/external_test_opt.py, test/external/external_test_speed_llama.py
part of #2283 
llama takes int as input and converts to Variable iff JIT
easier to use llama as a lib and fix llama for interpreted backends
=> llama take int and convert to Variable internally

test/test_symbolic_ops.py, tinygrad/ops.py, tinygrad/shape/symbolic.py
this interface should be jittable too, just swap the `var_vals` at jit time with the jit global one
=> support symbolic shape in Interpreted

extra/optimization/test_beam_search.py, tinygrad/features/search.py, tinygrad/ops.py
Allow beam search on kernels with var vals.
=> beam works with var vals

test/test_randomness.py, tinygrad/tensor.py
Only with replacement (for now)
=> Add Tensor.multinomial 

test/external/fuzz_linearizer.py
unified the exec call
next will see how to put it in ci, maybe something like > 90% pass rate
=> fuzz_linearizer same api for interpreted and compiled

.github/workflows/test.yml, setup.py, tinygrad/runtime/ops_webgpu.py
~~might need to update the cache too~~ setting the min dependency works
=> wgpu.utils._device -> wgpu.utils.device

.github/workflows/test.yml, test/test_jit.py
=> include WEBGPU in test_jit.py

extra/to_movement_ops.py, test/unit/test_symbolic.py, tinygrad/features/image.py, tinygrad/lazy.py, tinygrad/ops.py, tinygrad/shape/shapetracker.py, tinygrad/shape/symbolic.py, tinygrad/shape/view.py
eh more hash Node comparisons...
=> Node.vars() returns a set and properly dedup

test/test_webgpu.js
tried running the test for 20 times and all passed without needing to retry...
=> retry the flaky test_webgpu.js 3 times

tinygrad/codegen/kernel.py, tinygrad/helpers.py, tinygrad/shape/shapetracker.py
separated just the types from #2350
=> Just new types

test/test_randomness.py, tinygrad/tensor.py
p, cdf_normalized -> weight, cdf
symmetric unsqueeze / squeeze
test cases to check num_sample > 0 and ndim != 0
TODO: how do we want to handle 0/0 in general?
=> Pretty multinomial

extra/dist/world.py
don't know how i missed that one.
=> missed cleanup from cache_id removal

tinygrad/lazy.py, tinygrad/shape/shapetracker.py, tinygrad/shape/symbolic.py
I believe using set.union is more readable, appropriate and bit faster in my local setup.
Note: Set.union(*, set()) is for when argument is [] empty list
=> Readable and Faster Union of Vars

test/test_symbolic_jit.py, test/test_symbolic_ops.py, tinygrad/codegen/linearizer.py, tinygrad/ops.py, tinygrad/runtime/ops_metal.py
fix the variable order when we compile and when we call the compiled function
=> fix the variable arg order

.github/workflows/test.yml, examples/whisper.py
This is just a breakdown of #2366 to smaller PRs. This one starts with Whisper.
=> Update Whisper to use fetch helper

examples/vits.py
Continuation of #2366 that updates VITS example.
=> Update VITS to use fetch helper

examples/llama.py
=> Fix: missing n_kv_heads for smaller models from huggingface

docs/quickstart.md
@wozeparrot fyi. will leave it to you if you want to modify the text to say it's also implemented in the core lib
=> remove the commented import

.github/workflows/test.yml, test/test_copy_speed.py, test/test_linearizer_failures.py
=> metal ci tests everything

docs/abstractions.py, extra/optimization/helpers.py, tinygrad/codegen/linearizer.py, tinygrad/lazy.py, tinygrad/ops.py, tinygrad/runtime/ops_cpu.py, tinygrad/runtime/ops_disk.py, tinygrad/runtime/ops_torch.py
turned out to be pretty easy, CONTIGUOUS is just like RESHAPE
=> bye bye NOOP

ruff.toml
check trailing whitespace (W291) and blank lines contains whitespace (W293)
=> ruff check whitespaces

docs/quickstart.md
finally got some time for this.
should remove the confusion while still linking back to where the original implementation is.
=> reword loss fucntion comment in quickstart.md

tinygrad/features/graph/metal.py
Fixes metal icb running some jits with var_vals
Fixes missing var_vals buffers to resources and metal docs say that `useResources` should be called "before issuing any dispatch calls that may access the array of resources".
=> fix metal graph with var_vals

test/imported/test_indexing.py
added all internal helper functions needed for tests
I kept the original code/documentation in
'''
(torch impl)
'''
just so its easier to review (also to go back to in case I got something wrong)
will delete them at the end
=> helper functions for test_indexing.py

docs/README.md
why we got these doc prs maybe
=> no document prs

examples/gpt2.py
get back to CUDA 3.4ms with BEAM=12
=> gpt2 half for kvcache and output logits

examples/gpt2.py
rewrite embedding as a symbolic shrink of the embedding weight when we only need one row
CUDA HALF is broken now. with float, on 3080 with BEAM=12 it's 10% faster 4.7ms -> 4.2ms and two less kernels because the new embedding fused with something else
=> gpt-2 fast embedding for bs=1 and seqlen=1

test/unit/test_shapetracker.py
adding test to cover #2644 failure
=> adding test to cover #2644 failure

test/test_jit.py, tinygrad/jit.py
gpt-2 timings with CUDA:
new:
ran model in 1.79 ms
total 11.74 ms
old:
ran model in 1.67 ms
total 13.05 ms
=> split large jit into several graphs

examples/llama.py
add output validation before making it fast
=> validate llama output

tinygrad/codegen/kernel.py
=> combine GROUP and GROUPTOP to a single block

examples/mixtral.py
=> fix help message

test/test_dtype.py, tinygrad/tensor.py
commented out the int ones for now
=> some dtype creation spec test cases

test/test_dtype.py, tinygrad/helpers.py
`helpers.least_upper_dtype(dtypes)` to get the promoted type
=> dtype promotion helpers

tinygrad/helpers.py
Suggestion taken from here: https://realpython.com/primer-on-python-decorators/
=> add decorator to preserve info about original function

tinygrad/tensor.py
also moved the expand noop check to .expand.
=> refactor _broadcasted

tinygrad/tensor.py
input can be Tensor, float, int.
also updated scaled_dot_product_attention that might add a None to a Tensor
=> update type annotation of _broadcasted

test/test_dtype_alu.py
found in https://github.com/tinygrad/tinygrad/actions/runs/7202564474/job/19620928209
=> fix a typo in test_dtype_alu

tinygrad/codegen/linearizer.py
remove condition branches in cache check and the actual insertion
=> insert_before is None means insert at the end

extra/onnx_ops.py
read through it and clean some minor stuff
=> minor onnx_op cleanups to prep dtype changes

extra/onnx_ops.py
Reverts tinygrad/tinygrad#2758
=> Revert "minor onnx_op cleanups to prep dtype changes"

test/test_linearizer.py
I had broken matvec optimizations in #2727 but CI was green.
=> Test coverage for matvec

extra/triton/triton.py, test/test_dtype.py, test/test_uops.py, test/unit/test_disk_tensor.py, tinygrad/codegen/linearizer.py, tinygrad/helpers.py, tinygrad/renderer/cstyle.py, tinygrad/renderer/llvmir.py
in DEFINE_GLOBAL, PtrDtype(int32) is buffer and int32 is int
=> remove _arg_int32 internal type

test/helpers.py, test/test_linearizer.py, tinygrad/codegen/linearizer.py
Reverts tinygrad/tinygrad#2625
=> Revert "Use the reduceop dtype to define the acc in linearizer"

test/external/external_test_onnx_backend.py, test/test_dtype.py, tinygrad/tensor.py
interesting cases `f16 + 2 -> f16`. `i8 + 2 -> i8`
=> _broadcasted handles the python number types

tinygrad/codegen/linearizer.py
Reverts tinygrad/tinygrad#2792
=> Revert "Green Uop unary check"

test/test_randomness.py, tinygrad/tensor.py
Reverts tinygrad/tinygrad#2801
=> Revert "Tensor.randint is Tensor.uniform with dtypes.int32"

test/test_ops.py, tinygrad/tensor.py
output is the sorted alphabets if there's no "->"
=> support Tensor.einsum with no "->" in formula

test/test_tensor.py, test/unit/test_helpers.py, tinygrad/helpers.py, tinygrad/tensor.py
Reverts tinygrad/tinygrad#2793
=> Revert "Make Tensor creation allow multi-dim list of int and bool"

.github/workflows/benchmark.yml
easier to separate the issue between HALF and BEAM when it failed
=> run HALF GPT2 in nvidia benchmark in addition to HALF/BEAM

tinygrad/renderer/cstyle.py, tinygrad/runtime/ops_clang.py
also removed a questionable Any annotation
=> replace a defaultdict counting with Counter in cstyle

test/test_tensor.py, test/unit/test_helpers.py, tinygrad/helpers.py, tinygrad/tensor.py
Reverts tinygrad/tinygrad#2810
=> Revert "Revert "Make Tensor creation allow multi-dim list of int and bool""

test/test_randomness.py, tinygrad/tensor.py
Reverts tinygrad/tinygrad#2802
=> Revert "Revert "Tensor.randint is Tensor.uniform with dtypes.int32""

tinygrad/features/image.py
use transpose for transpose instead of permute, and use pad for pad instead of slice
=> minor cleanup of image

examples/hlb_cifar10.py, extra/onnx_ops.py, test/external/external_test_jit_on_models.py, test/models/test_real_world.py, test/test_dtype.py, test/test_hip_rdna3.py, test/test_tensor.py, tinygrad/helpers.py, tinygrad/tensor.py
`Tensor.default_type` became `dtypes.default_float` and added `dtypes.default_int`
=> dtypes.default_float and dtypes.default_int

test/test_tensor.py, tinygrad/helpers.py, tinygrad/tensor.py
also updated some tests to test against default dtypes
=> dtypes.from_py to convert py objects to dtypes

test/test_dtype.py
make is_dtype_supported a pure function and clean up long lines
=> clean up test_dtype.py

tinygrad/codegen/kernel.py
clean up some long lines and combined some short lines
=> minor clean up in kernels

tinygrad/codegen/linearizer.py
providers a general utility for linearizing ImageDType ASTs
=> UOps support for ImageDType

test/external/fuzz_shapetracker_math.py, test/unit/test_shapetracker.py, test/unit/test_shapetracker_math.py, tinygrad/shape/view.py
fuzzer found a bug, and it's not complete
=> disable reshape merging with masks

test/unit/test_shapetracker.py, tinygrad/shape/view.py
=> update one skipped pad_reshape test that was fine

examples/gpt2.py
also updated function name from greedy_until to generate, as it's not greedy nor until
=> make gpt2 decode output just once at the end

test/helpers.py, test/test_linearizer.py, tinygrad/codegen/linearizer.py
removes #noqa lines and makes the fusion more readable.
=> mulacc fusion cleanup

test/helpers.py, test/test_linearizer.py, tinygrad/codegen/linearizer.py
Reverts tinygrad/tinygrad#2871
=> Revert "mulacc fusion cleanup"

extra/onnx_ops.py, tinygrad/lazy.py, tinygrad/mlops.py, tinygrad/tensor.py
#2883 breaks commavq result in a weird way so i split elementwise from reduceop and will do lazy assert as follow up. also #2800 can rebase on this
=> move the op casting logic from mlops to tensor try 2

tinygrad/lazy.py, tinygrad/mlops.py, tinygrad/runtime/ops_cpu.py, tinygrad/runtime/ops_torch.py
=> assert for elementwise dtypes in lazy

extra/onnx.py, extra/onnx_ops.py
also removed a case in safe_numpy that always convert 0-dim array to 1-dim
=> onnx_ops formatting cleanup

tinygrad/graph.py
bringing #1817 to current code
looks like:
```
391    ┃ ┃ ┗━┳ XOR 
392    ┃ ┃   ┣━┳ ADD 
393    ┃ ┃   ┃ ┣━⬆︎ goto 367: ADD
394    ┃ ┃   ┃ ┗━┳ XOR 
395    ┃ ┃   ┃   ┣━⬆︎ goto 367: ADD
396    ┃ ┃   ┃   ┗━┳ ADD 
397    ┃ ┃   ┃     ┣━┳ MUL 
398    ┃ ┃   ┃     ┃ ┣━⬆︎ goto 369: ADD
399    ┃ ┃   ┃     ┃ ┗━━ CONST ConstBuffer(val=8192.0, dtype=dtypes.uint, st=ShapeTracker(views=(View(shape=(2,), strides=(0,), offset=0, mask=None, contiguous=False),)))
400    ┃ ┃   ┃     ┗━┳ DIV 
401    ┃ ┃   ┃       ┣━⬆︎ goto 369: ADD
402    ┃ ┃   ┃       ┗━━ CONST ConstBuffer(val=524288.0, dtype=dtypes.uint, st=ShapeTracker(views=(View(shape=(2,), strides=(0,), offset=0, mask=None, contiguous=False),)))
403    ┃ ┃   ┗━┳ ADD 
404    ┃ ┃     ┣━┳ MUL 
405    ┃ ┃     ┃ ┣━⬆︎ goto 394: XOR
406    ┃ ┃     ┃ ┗━━ CONST …
```
=> catch cycles in print_tree

test/external/external_model_benchmark.py, test/models/test_onnx.py
updated in https://github.com/onnx/models/pull/644
=> update onnx model links

test/test_dtype.py, tinygrad/tensor.py
=> don't use numpy to create Tensor(None)

docs/abstractions.py
removed some old terms and updated types and code pointers
=> less outdated abstraction.py

test/test_dtype_alu.py
wrapped long lines and lowered atol for METAL.sin to 2 since atol of two sins are bounded by 2
=> cleanup test_dtype_alu

tinygrad/mlops.py, tinygrad/tensor.py
use None for no-op slice and pad
=> tensor.py cleanup around Tensor.slice

extra/models/llama.py, test/test_dtype.py, tinygrad/codegen/linearizer.py, tinygrad/renderer/cstyle.py, tinygrad/renderer/llvmir.py, tinygrad/tensor.py
also implemented int MULACC for opencl and llvm in addition to the float one. added different default acc for ReduceOps.MAX based on dtype.
@Qazalin fyi
=> use at least int32 and uint32 for sum output

tinygrad/tensor.py
don't need contiguous between two casts, and don't need cast bool into float before mul
=> clean up manual cast dtypes in tensor.py

test/test_dtype.py, tinygrad/tensor.py
cumsum behaves like sum, and functions that return an index return in dtypes.default_int
=> test dtypes of return values of cumsum, argmax/min, multinomial

test/test_dtype.py, tinygrad/codegen/kernel.py, tinygrad/codegen/linearizer.py
less long line, spaces and colocate variables
=> minor cleanup in kernel and linearizer

tinygrad/codegen/kernel.py
=> hotfix float4 only supports float and half

examples/gpt2.py, extra/models/llama.py
not using argmax yet because there's a multinomial outside of function.
=> use max for gpt2 and llama logit output

tinygrad/runtime/ops_cuda.py
added for distros that default to /opt/ when installing cuda toolkit
=> add `/opt/cuda/include` directory

tinygrad/renderer/cstyle.py
we only need to override a few fields.
=> Share HIP cstyle with CUDA

tinygrad/renderer/cstyle.py
similar to code_for_op,
I don't think we need the loop because any dimension >3 won't compile anyways.
=> refactor workitem rendering in cstyle

tinygrad/shape/symbolic.py
delegate simplification to individual node
=> simpler SumNode.__mod__

tinygrad/codegen/kernel.py
and other minor apply_opt cleanups
=> merge apply_opt OptOps.LOCAL and OptOps.LASTLOCAL into one block

tinygrad/shape/symbolic.py
`gcd(self.b, b) == b` is equivalent to `self.b % b == 0`. use the same condition and format in __floordiv__ too.
=> simpler ModNode.__mod__ and ModNode.__floordiv__

tinygrad/features/search.py
instead of list of list then flatten
=> one list comprehension in search action

tinygrad/codegen/linearizer.py
=> out_tokens -> grouped in linearizer

test/test_lazybuffer.py, test/test_multitensor.py, tinygrad/lazy.py
fixed the multitensor +1 then sum bug
=> canonicalize device in LazyBuffer constructor

tinygrad/codegen/linearizer.py, tinygrad/shape/symbolic.py, tinygrad/shape/view.py
having NumNode in var_vals does not change the substitute output
=> use Variable instead of VariableOrNum for Node.substitute var_vals arg

tinygrad/codegen/kernel.py
remove noop isinstance check and fix long lines
=> minor cleanup of matvec in hand_coded_optimizations

test/test_ops.py
=> add test_softmax to test_ops

tinygrad/tensor.py
unify the type spec for Tensor creation functions and broadcasted elementwise ops that take python scalar
=> use Scalar = Union[float, int, bool] in tensor.py

test/test_ops.py, tinygrad/tensor.py
simplified cases when splitting a dim, or merge dims in predix
=> add Tensor.unflatten and Tensor.flatten(end_dim)

test/test_ops.py
not sure why it was skipped but works now in CI
=> enable argmax tests for METAL/WEBGPU in CI

examples/beautiful_cartpole.py
tested by getting 3 full scores in a row
=> move beautiful cartpole action sampling inside jit

test/test_ops.py
add cases for same low/high and both negative etc
=> add more Tensor.clip test cases

examples/llama.py, extra/optimization/helpers.py, extra/to_movement_ops.py, test/imported/test_indexing.py, test/test_linearizer.py, test/test_linearizer_failures.py, test/test_search.py, test/test_symbolic_shapetracker.py, test/unit/test_shapetracker.py, test/unit/test_shapetracker_math.py, tinygrad/codegen/kernel.py, tinygrad/codegen/linearizer.py, tinygrad/features/search.py, tinygrad/jit.py, tinygrad/lazy.py, tinygrad/ops.py, tinygrad/realize.py, tinygrad/shape/shapetracker.py, tinygrad/shape/symbolic.py
Reverts tinygrad/tinygrad#3026
=> Revert "track size in shapetracker"

.github/workflows/test.yml, extra/gemm/simple_matmul.py
accumate for half inputs is always in float
=> remove ACCUM_FP32 in simple_matmul.py

test/external/external_test_example.py, tinygrad/device.py, tinygrad/tensor.py
backend devices used to be called buffers
=> Device._buffers -> Device._devices

examples/gpt2.py, test/test_symbolic_ops.py
test cases taken from ll_transformer branch
=> fix gpt2 attention with start_pos = 0

test/test_multitensor.py
will do a clean up like test_ops to add a few more shapes variation after llama sharded 7B is upstreamed, next is the entire transformer block.
=> test scaled dot product attention

test/test_symbolic_shapetracker.py, tinygrad/jit.py, tinygrad/lazy.py, tinygrad/shape/shapetracker.py, tinygrad/shape/view.py
4% faster for llama compile time
=> unbind view or shapetracker also returns var_val

examples/transformer.py, extra/models/transformer.py
trained to 0.999 in < 6 seconds on M1 Max consistently
=> fix onehot and jit in examples/transformer

test/test_multitensor.py
these tests really can be used as documentation. Both demonstrate the intended use cases and show that it works. also help me to sort through the attention test pr.
=> better test demonstration

tinygrad/tensor.py
similar to how reshape is done. also updated shrink shortcut criteria to read similar to pad
=> Tensor.expand resolves the new_shape before shortcut return

test/test_multitensor.py
a bunch of the hlops are not tested for multigpu yet. I will be adding tests along with encountering them.
=> test multigpu cat

tinygrad/shape/view.py
no logic depends on state == 0 or state == 2
=> remove the third merging state in view._merge_dims

tinygrad/codegen/kernel.py, tinygrad/device.py, tinygrad/features/search.py, tinygrad/runtime/ops_clang.py, tinygrad/runtime/ops_cuda.py, tinygrad/runtime/ops_gpu.py, tinygrad/runtime/ops_hip.py, tinygrad/runtime/ops_llvm.py, tinygrad/runtime/ops_metal.py
removed all Device.DEFAULT in search.py
=> use device from LinearizerOptions in kernel search

extra/models/llama.py, test/test_multitensor.py, tinygrad/features/multi.py
add multigpu support for llama attention with tests
~~still need to fix the kv cache~~
need to make a small for loop to test kv cache more properly
=> add mutigpu support for llama attention

examples/gpt2.py, test/test_symbolic_ops.py
logits would be empty so need to replace that with ones before sampling, also cannot reshape with -1 when there's 0 in other axes
=> fix gpt2 with empty prompt

examples/gpt2.py, test/test_symbolic_ops.py
Reverts tinygrad/tinygrad#3100
=> Revert "fix gpt2 with empty prompt"

examples/gpt2.py, test/test_symbolic_ops.py
logits would be empty so need to replace that with ones before sampling, also cannot reshape with -1 when there's 0 in other axes
=> fix gpt2 with empty prompt take 2

extra/gemm/simple_matmul.py, test/test_linearizer.py, tinygrad/codegen/kernel.py, tinygrad/codegen/linearizer.py, tinygrad/features/image.py, tinygrad/renderer/cstyle.py, tinygrad/tensor.py
Also removed invalid HIP FP16->FP16 tensor core definition since it's not actually accumulating in FP16.
=> wmma: enable METAL half tensor cores and clean up cstyle

tinygrad/features/search.py
return inf if search encountered runtime errors.
=> catch runtime error in search._time_program

extra/onnx_ops.py, test/test_ops.py, tinygrad/tensor.py
also updated MeanVarianceNormalization and made test_ops test tensors of var and std smaller
=> add Tensor.var

examples/beautiful_mnist.py
also removed .realize() for jit functions since jit does it automatically now. a little more beautiful
=> move sample inside jit for beautiful_mnist

extra/datasets/__init__.py, tinygrad/runtime/ops_torch.py
updated mnist test to cast label to int8 and avoid hacking cast issue of torch uint8
=> remove numpy from ops_torch

test/test_dtype.py
Context: https://github.com/tinygrad/tinygrad/commit/96345061d3e3472f4593a6681d8280c23eeaf645#commitcomment-137045507
=> add tests to catch ptrdtype comparison bugs

tinygrad/dtype.py
* dynamically map dtypes to numpy
* np is no longer needed as attribute, so cleaner code
=> use fmt for numpy to dtype mapping

tinygrad/graph.py
=> s/lazydata/lazyop/ in print_tree

examples/mlperf/model_eval.py, test/test_multitensor.py, tinygrad/tensor.py
Works, but needs #3029 for the JIT
=> use shard api to eval resnet fast

examples/hlb_cifar10.py
still too slow to search on tinybox though
=> add LATEBEAM to hlb_cifar

.github/workflows/benchmark.yml
=> run full hlb_cifar training in tinybox ci

examples/hlb_cifar10.py
do more things in Tensor space instead of numpy, clean up dtypes and use more Tensor methods.
=> modernize hlb_cifar

examples/hlb_cifar10.py
89 -> 86 seconds, same eval acc
=> gelu -> quick_gelu in hlb_cifar

examples/mlperf/model_eval.py, test/test_custom_function.py, test/test_multitensor.py, test/test_uops.py, tinygrad/device.py, tinygrad/features/search.py, tinygrad/jit.py, tinygrad/runtime/graph/cuda.py, tinygrad/runtime/graph/hip.py
If I merge this, bounty goes to @ramenguy99. Just updating the APIs
=> multitensor jit

examples/hlb_cifar10.py
use GPUS to specify number of gpus. using the shard API is quite magical. first compilation on a tinybox takes forever though
=> hlb_cifar multi gpu training

test/test_hip_rdna3.py, tinygrad/runtime/ops_cuda.py, tinygrad/runtime/ops_gpu.py, tinygrad/runtime/ops_hip.py
=> compile cache for several devices

tinygrad/runtime/graph/cuda.py, tinygrad/runtime/graph/hip.py, tinygrad/runtime/ops_gpu.py
Cleanup all double exceptions when getting compilation/graph errors.
=> clean up exceptions in del everywhere

tinygrad/codegen/kernel.py
same questionable logic, but less lines now
=> smaller limit_dims_to_max

test/test_dtype.py, test/test_dtype_alu.py, test/test_hip_rdna3.py
=> hypothesis.st -> hypothesis.strat

test/test_dtype.py, test/test_multitensor.py, tinygrad/features/multi.py
uneven shards reduce is incorrect now
=> parameterize multitensor tests for reduce

tinygrad/features/search.py
=> reenable padto to search action

test/test_multitensor.py, test/test_ops.py, tinygrad/lazy.py, tinygrad/tensor.py
this fixed uneven shard reduce case if the uneven one has length 0
=> move reduce over 0 len axis logic to lazy.py

test/test_ops.py
- removed exact duplicated tests
- only kept one function if torch_fxn is the same as tinygrad_fxn
- used tensor method instead of class method style
- replaced unneeded `lambda f: f(x)` with just `f`
- re-enabled commented tests that work now
- removed some forward_only now 0 shape tensor can backward
=> cleanup test_ops.py

tinygrad/tensor.py
make expand dim=None as noop (in addition to -1). then slice, reshape, expand in _pool can share the same noop prefix
=> cleanup noop prefixes in _pool

test/test_tensor.py, tinygrad/tensor.py
it should have the same device as self
=> fix device of Tensor.arange inside Tensor.one_hot

examples/hlb_cifar10.py
it's no-op with multi gpu and less STEPS. also the patch was selected from the whole dataset, not from the same batch
=> comment out cutmix in hlb_cifar

examples/handcode_resnet50_opt.py
use this to study tensor cores on HIP
=> add HALF to handcode_resnet50_opt.py

examples/hlb_cifar10.py
experimenting with different setups, also would like to jit the data augmentation next
=> cifar flags for RANDOM_CROP, RANDOM_FLIP, and CUTMIX

examples/hlb_cifar10.py
removed some complicated looking stuff. no wall time difference
=> cleanup pad_reflect and make_square_mask in hlb_cifar

test/test_linearizer.py, test/unit/test_symbolic.py, tinygrad/codegen/linearizer.py, tinygrad/shape/symbolic.py
for cuda tc, we want to support same expand var in multiple buffer axes (also helps with multiple different expand vars in the same index position). more changes coming after this.
saves 2 lines, too.
=> name upcast variables

examples/hlb_cifar10.py
mostly cosmetic. LATEBEAM=4 single 7900xtx 59.2 seconds
=> minor hlb_cifar cleanups

examples/hlb_cifar10.py
save 1ms CPU time per batch. also only shuffle training set
=> cifar only shuffle data at epoch start

test/test_linearizer.py
also re-enable the test_tensor_core_opts
=> test: fix test_linearizer to use the correct tc_dims

examples/hlb_cifar10.py
=> cifar move GlobalCounters.reset() before shard

test/test_ops.py, tinygrad/tensor.py
The initial motivation for this is to unstuck #3207, but since this is needed anyway, I figured I could implement it in a separate PR, especially since the mentioned PR isn't valid anymore because of https://github.com/tinygrad/tinygrad/pull/3207#issuecomment-1907787274.
=> Implement Tensor.round

tinygrad/runtime/ops_cuda.py
=> fix cuda device var rewrite

test/test_ops.py
=> failed test cases for Tensor.round

extra/onnx_ops.py, test/test_ops.py, tinygrad/tensor.py
fixes `# TODO: implement round to even`
this is one mad lookin round tho
=> fix: big round even rounder round

.github/workflows/test.yml, extra/onnx_ops.py, test/external/external_test_onnx_backend.py
Einsum inner product and `...` are not supported
=> onnx Einsum, CumSum, DepthToSpace, SpaceToDepth

test/test_jit.py, tinygrad/dtype.py, tinygrad/features/multi.py, tinygrad/lazy.py, tinygrad/tensor.py
moved Scalar to dtype.py. assert in _broadcasted when y is a Scalar and fix some tests
=> const cleanup with dtype.Scalar

extra/hiprtc/hiprtc_runtime.h, setup.py, test/test_device_speed.py, tinygrad/renderer/cstyle.py, tinygrad/runtime/compiler/hip_comgr.py, tinygrad/runtime/ops_hip.py
Still needs freeing and probably some cleanup around the header, but this is a 10x speedup for (empty) HIP compilation.
=> use comgr to compile

test/test_dtype.py
* Tests for Tensor init data dtype matching resulting dtype.
=> tests for Tensor init data dtype and resulting dtype

test/test_winograd.py, tinygrad/lazy.py
I'm curious how this used to work...
Oh, probably before the shapetracker view fusion improvements!
=> winograd should be 4 kernels

.github/workflows/benchmark.yml
used HIP instead of GPU and disabled slow CLANG
=> HIP=1 NOCLANG=1 for tinybox external_model_benchmark

tinygrad/features/multi.py
similar to contraction, but this is one is for finding the mapped single axis
=> MultiLazyBuffer.reshape new_axis without real_strides

test/test_winograd.py, tinygrad/shape/shapetracker.py, tinygrad/shape/view.py
This makes Winograd twice as fast (to compile) on M3
=> take merge views from corsix branch

test/test_winograd.py, tinygrad/shape/shapetracker.py, tinygrad/shape/view.py
Reverts tinygrad/tinygrad#3273
=> Revert "take merge views from corsix branch"

extra/onnx_ops.py, test/external/external_test_onnx_backend.py, test/test_ops.py, tinygrad/tensor.py
support 0 in shape for Trilu and select_last_index for ArgMax
=> onnx update for trilu and argmax

test/test_ops.py
- removed noop a=0
- fixed integer div test
- added test for both python expression and Tensor method call
- reordered for consistency and added some spaces
=> minor cleanups to test_ops

.github/workflows/benchmark.yml, examples/hlb_cifar10.py, test/test_multitensor.py, tinygrad/features/multi.py
use onehot structure to store the real partition. goal is unsynced batchnorm2d that can be run on multigpu for training.
draft version in https://github.com/chenyuxyz/tinygrad/pull/109
=> shrink MLB on sharded axis

test/test_ops.py
some have numerical issues at large input similar to sigmoid
=> test_ops sinh/cosh/asinh/acosh/atanh

ruff.toml
select -> lint.select.
also added rule names for fully specified ones
=> update ruff.toml for v0.2.0

tinygrad/tensor.py
noop cleanup, the kernels remain the same
=> remove some contiguous and contiguous_backward from wino

test/external/fuzz_shapetracker_math.py, tinygrad/shape/view.py
empty list -> None. also added env SEED for fuzz_shapetracker_math
=> touchup canonicalize empty mask

test/unit/test_helpers.py, test/unit/test_shapetracker.py
also cleaned long lines in test_shapetracker and enabled the line length check
=> move TestGetContraction to test_helpers

test/unit/test_disk_tensor.py, tinygrad/nn/state.py
the correct keys are U32 and U64.
=> fix safetensor load uint32 and uint64

tinygrad/tensor.py
left ones in conv2d and wino, no E501 elsewhere in tensor. three functions need general readability improvement: getitem and gather, conv2d and wino, and pow
=> remove some noqa: E501 in tensor

test/test_ops.py
tried refactoring pow and found some bugs
=> add failed Tensor.pow test cases

.github/workflows/test.yml, test/test_ops.py, tinygrad/tensor.py
run on TORCH since it's the fastest one on CI.
caught a bug in multinomial, and update the behavior of fancy index and gather to move the indices Tensor to same device as self.
=> test intermediate tensors created by function have same device as input

.github/workflows/benchmark.yml, examples/hlb_cifar10.py
set to 93% to reduce flakiness for now
=> verify eval acc for hlb_cifar training

.github/workflows/test.yml, test/test_linearizer.py, test/test_ops.py, tinygrad/codegen/kernel.py, tinygrad/runtime/ops_hip.py, tinygrad/runtime/ops_metal.py, tinygrad/runtime/ops_python.py
Will be used for validating UOp behavior matches the spec. The spec is defined by this emulator.
=> Python uop emulator

extra/gemm/metal_matmul.py, extra/gemm/metal_matvec.py
I found bugs in ```metal_matmul.py``` and ```metal_matvec.py```, so I fixed them.
=> fix metal compile error in extra/gemm

tinygrad/renderer/cstyle.py
I'm doing HIP in a separate PR since we need to move the includes to `render_kernel` as well
=> dynamic Metal WMMA function prekernel

autogen_stubs.sh, tinygrad/device.py, tinygrad/realize.py, tinygrad/runtime/autogen/hsa.py, tinygrad/runtime/driver/hsa.py, tinygrad/runtime/ops_hip.py, tinygrad/runtime/ops_hsa.py, tinygrad/runtime/ops_metal.py
HSA patches in a series of:
1) HSA runtime
2) Simple HSA graph (like HIP rn)
3) One big HSA graph with transfers embedded
...
=> hsa runtime

.github/workflows/test.yml, test/test_ops.py, tinygrad/runtime/ops_python.py
Can I lock the bounty with this PR?
Notes:
- Right now only 6 tests are failing and most of them are due to only one error. So I figured I could push a PR to lock the bounty, and in the meanwhile, fix the remaining tests.
- I left a few comments on the code which I would appreciate an answer for.
**UPDATE**: There are only 3 remaining failing tests.
**UPDATE**: All tests pass now.
=> Make tests in `test/test_ops.py` pass for Python emulator

extra/onnx_ops.py, test/external/external_test_onnx_backend.py, test/test_dtype.py, test/test_ops.py, tinygrad/tensor.py
make #3195 great again
the test_dtype tests follows jax casting rules
=> correct division dtype casting

.pre-commit-config.yaml
it's silently using DEFAULT after removing TORCH
=> remove use of TORCH in pre-commit

extra/onnx_ops.py, test/external/external_test_onnx_backend.py, test/test_conv.py, test/test_tensor.py
the onnx tests were all skipped.
=> add back "CPU" in test_onnx_backend supports_device

tinygrad/codegen/kernel.py, tinygrad/features/jit.py, tinygrad/shape/shapetracker.py, tinygrad/shape/symbolic.py, tinygrad/shape/view.py
these are the only allowed nodes in a Tensor shape
=> limit sint to be Union[int, Variable, MulNode, SumNode]

tinygrad/runtime/graph/hip.py
Fix `RuntimeError: HIP Error 101, invalid device ordinal` from #3000
=> fix hip invalid ordinal

test/test_linearizer.py, tinygrad/shape/symbolic.py
handle Node collapsing into NumNode similar to OpNode
=> remove create_rednode

.pre-commit-config.yaml
=> add mypy --strict-equality to pre-commit

.github/workflows/test.yml
fixed by the store fix in ops_python
=> enable test IMAGE=2 PYTHON=1 python3 test/test_ops.py TestOps.test_simple_conv2d

test/test_multitensor.py, tinygrad/features/multi.py
=> support MLB reshaping on-axis for evenly sharded

tinygrad/features/jit.py
Rewrite jit grapher to simpler integrate multigraph support. I think it looks cleaner, the logic is the same.
For #3403
=> jit grapher simplified

test/test_uops.py, tinygrad/runtime/ops_python.py
fixes: https://github.com/tinygrad/tinygrad/pull/3480#issuecomment-1961521843
* sqrt(0) != nan
=> fix exec_alu(UnaryOps.SQRT, <...>, (0,)) + add test

test/test_dtype.py, tinygrad/renderer/cstyle.py
follow up of #3420, fixed #3304 on HIP
tested on tinybox. @Qazalin fyi enumerator does not support these
=> float64 function support for HIP

.github/workflows/test.yml, test/test_dtype.py
follow-up on #3492 fyi @chenyuxyz
=> run f64 increased precision tests on remu

test/unit/test_symbolic.py, tinygrad/shape/shapetracker.py, tinygrad/shape/symbolic.py, tinygrad/shape/view.py
Also made sure taking max twice can get int.
=> fix Node.max can be symbolic

tinygrad/helpers.py, tinygrad/runtime/ops_cuda.py
This should be cleaner and less lines
=> no cuda compile helper

test/test_lazybuffer.py
=> test for the split reduce kernel

tinygrad/lazy.py
removed useless assert now arg is axis and cleaned split logic
=> cleanup lazy reduce

tinygrad/runtime/graph/metal.py, tinygrad/runtime/ops_metal.py
Sometimes MTLCommandBuffer fails silently and just doesn't update output Buffer, which is quite bad. There's multiple issues that lead to metal flakiness, this is one of them.
Fixes https://discord.com/channels/1068976834382925865/1069001075828469790/1189831398975094804
=> Raise exception if MTLCommandBuffer fails

extra/optimization/test_beam_search.py, tinygrad/features/search.py, tinygrad/helpers.py, tinygrad/ops.py
=> use hash as key for beam

tinygrad/runtime/ops_hsa.py
Reverts tinygrad/tinygrad#3504
=> Revert "check buffers are accessible by other gpu before transfer"

tinygrad/lazy.py
Reverts tinygrad/tinygrad#3475
This made things slower.
=> Revert "move all reduces to the end in lazy"

test/unit/test_disk_tensor.py, tinygrad/runtime/ops_disk.py
=> fix disktensor offset issue

tinygrad/runtime/graph/hsa.py
=> fix addresses of dispatch packets

tinygrad/runtime/driver/hsa.py, tinygrad/runtime/graph/hsa.py, tinygrad/runtime/ops_hsa.py
A proper replacement for #3504
=> scan all gpu agents at launch

test/test_uops.py, tinygrad/codegen/linearizer.py, tinygrad/codegen/uops.py, tinygrad/renderer/cstyle.py, tinygrad/runtime/ops_python.py
Let's see if tests pass, I thought this was still needed.
=> add index to DEFINE_GLOBAL

extra/optimization/test_beam_search.py
might fail due to CL_OUT_OF_RESOURCES
=> disable flaky test_conv_beam in CI

test/test_multitensor.py, tinygrad/tensor.py
Reverts tinygrad/tinygrad#3483
=> Revert "don't allow MLB assigns with different axes"

tinygrad/nn/__init__.py
what is a good interface for picking an initializer?
=> allow overriding weight init for Linear

tinygrad/nn/__init__.py
Reverts tinygrad/tinygrad#3569
=> Revert "allow overriding weight init for Linear"

test/models/test_real_world.py, test/test_schedule.py, tinygrad/lazy.py
=> lazy.py: cache consts

tinygrad/runtime/graph/hsa.py
=> fix sync in hsa graph

test/test_search.py
Some basic sanity tests for `bufs_from_lin` as a start.
=> Tests for `bufs_from_lin`

tinygrad/runtime/driver/hsa.py, tinygrad/runtime/graph/hsa.py, tinygrad/runtime/ops_hsa.py
A bit refactor:
* flush hdp cache when kernargs are updated.
* use alloc() and alloc with options instead of code duplications
* readability + some line savings
=> hsa flush hdp

test/unit/test_symbolic.py, tinygrad/codegen/linearizer.py
updated one in linearizer if condition, and various symbolic tests
=> apply more create_lt_node

tinygrad/codegen/kernel.py, tinygrad/features/search.py, tinygrad/runtime/ops_hsa.py
I don't know if it's a the best way to fix beam calling to HIP device when using hsa backend...
=> hsa in lin opts

.github/workflows/test.yml, tinygrad/codegen/uops.py
using `is` to compare with enums, remove long lines and slightly more compact
also added a test entry with DEBUG=100 to cover some DEBUG path
=> cleanup uops

extra/models/bert.py
Init tensor as multilazybuffer, if needed.
=> Fix: BERT data parallel

test/test_tensor.py, tinygrad/helpers.py
it's possible to overlook setting keyword for kwargs and argfix silently truncates input
=> check the input length into argfix

.github/workflows/benchmark.yml
would merge if it's also ~1 minute. btw why is gpt2 beam not slower in the first beam run?
=> llama + beam to mac benchmark, full cifar to nvidia benchmark

test/test_dtype.py
Reverts tinygrad/tinygrad#3481
=> Revert "test: add failing bfloat16 test case for metal backend"

extra/models/efficientnet.py, test/test_dtype_alu.py, test/test_image_dtype.py, test/test_multitensor.py, test/test_tensor.py, test/unit/test_disk_tensor.py, tinygrad/tensor.py
=> ban __bool__ on Tensor

test/test_dtype_alu.py
revert this part of #3629. this is flaky
=> skip METAL sin test in test_dtype_alu

.github/workflows/test.yml, examples/mlperf/optimizers.py, ruff.toml, setup.py, test/external/external_test_optim.py, test/external/mlperf_resnet/lars_optimizer.py
tested against reference TF implementation
#3361
=> lars optimizer + tests

test/test_linearizer_failures.py, tinygrad/renderer/cstyle.py
fixed some bracket nesting level exceeded maximum of 256 errors
=> remove parentheses of GEP if it's from SSA

.github/workflows/test.yml, test/external/external_test_hip_compile.py, test/test_hip_compile.py, tinygrad/renderer/cstyle.py
we can avoid the compiler overheads of the include file for kernels that don't need bf16.
fyi @wozeparrot
=> make the bf16 include dynamic

examples/vits.py, extra/models/mask_rcnn.py
also removed `.cpu()` calls in mask_rcnn so `python3 examples/mlperf/model_spec.py` runs
=> fix example that calls Tensor.__bool__

tinygrad/runtime/ops_metal.py
This is the source of metal flakiness
=> Track transfers on metal

tinygrad/renderer/llvmir.py
```
_block -> block
builder._block.module -> builder.module
var_dtype -> dtype
```
=> clean up llvmir builder

tinygrad/shape/shapetracker.py, tinygrad/shape/view.py
verified the cases that used real_strides are redundant (https://github.com/chenyuxyz/tinygrad/pull/166)
=> View.__add__ to merge_view

tinygrad/codegen/uops.py, tinygrad/mlops.py, tinygrad/ops.py, tinygrad/renderer/assembly.py, tinygrad/renderer/cstyle.py, tinygrad/renderer/llvmir.py, tinygrad/tensor.py
Reverts tinygrad/tinygrad#3687
=> Revert "bring reciprocal back"

test/test_ops.py
=> use default_float.np to construct test data in test_ops

tinygrad/runtime/ops_hsa.py
Inactivating/destroying aql queues helps to solve some reproducible gpu hangs when exiting having work in aql queues
=> fix gpu hangs when exiting while aql queues are executing

examples/hlb_cifar10.py
prepared bfloat16 change. added float() and cast(default_float) in whiteing, explicitly set dtype in various places that convert between numpy and Tensor
=> explicit dtypes in hlb_cifar

examples/llama.py
=> fix llama shard convo mode

tinygrad/device.py
=> Call self.nbytes

examples/yolov8.py
replaced an `assign` with `replace`, and add '.png' for output if input URL does not contain an extention
=> fix yolov8.py

test/test_dtype.py, tinygrad/codegen/uops.py
Reverts tinygrad/tinygrad#3743
=> Revert "fix const bitcast should not be constant folded"

test/test_uops.py
and a expected failed bitcast fold test case. Will fix with UOps.BITCAST refactor
=> add test case for uop cast constant fold

test/test_dtype.py, test/test_uops.py, tinygrad/codegen/linearizer.py, tinygrad/codegen/uops.py, tinygrad/renderer/assembly.py, tinygrad/renderer/cstyle.py, tinygrad/renderer/llvmir.py, tinygrad/runtime/ops_python.py
implicitly fixed no const folding for bitcast
=> UOps.BITCAST

test/test_dtype.py
With bf16 creation and bf16 to numpy, we can test bf16 in test_dtype. Only support HIP now as it needs bf16 buffer support. Also the rtoal is slightly larger
=> bf16 tests in test_dtype.py

examples/mlperf/model_train.py
we might be able to have higher lr given smaller BS, but this is good.
Trained to 75.9%
https://wandb.ai/chenyuxyz/tinygrad-examples_mlperf/runs/xi2f48se/overview
=> update mlperf resnet default hparams

.github/workflows/test.yml, test/models/test_real_world.py
cleaned up a bit. Found an issue that `JIT` is used both in core tinygrad jit and example, so specifying `JIT=2` failed the test
=> Run test_real_world in METAL test

.github/workflows/test.yml, test/external/external_test_onnx_backend.py, test/helpers.py, test/models/test_real_world.py, test/models/test_whisper.py, test/test_dtype.py, test/test_dtype_alu.py, test/test_linearizer_failures.py, test/test_specific_conv.py, test/test_uops.py, test/unit/test_disk_tensor.py
updated all places that check if float16 is supported
=> move is_dtype_supported to test.helpers

tinygrad/realize.py
with this, multioutput will be really simple to add in, just change sorted_realizes to store a list of lists of bufs!
=> bfs scheduler, infra for multioutput

tinygrad/nn/optim.py
Just opening a PR to run CI lol
=> [experimenting] use contiguous instead of realize in optim

tinygrad/features/jit.py
Saves some enqueue time for big jit caches
llama 7b gpu6
```
enqueue in  39.35 ms
total  60.86 ms, 16.43 tok/sec
```
vs
```
enqueue in  52.92 ms
total  65.90 ms, 15.17 tok/sec
```
resnet beam=4
```
30  339.68 ms run,   36.58 ms python,  26.77 ms fetch data,  276.33 ms HSA * 6,  7.03 loss, 0.00 acc, 0.007821 LR, 94.53 GB used,  45560.44 GFLOPS
```
vs
```
30  369.88 ms run,   57.52 ms python,  24.03 ms fetch data,  288.33 ms HSA * 6,  7.03 loss, 0.00 acc, 0.007821 LR, 94.53 GB used,  41840.78 GFLOPS
```
=> increase jit batch size progressively

tinygrad/device.py, tinygrad/features/jit.py, tinygrad/features/search.py, tinygrad/runtime/graph/hsa.py
Reverts tinygrad/tinygrad#3781
NVIDIA benchmark failed
=> Revert "add outbufs info to CompiledASTRunner"

.github/workflows/test.yml, extra/optimization/test_beam_search.py, test/helpers.py, test/test_gc.py, test/test_jit.py, test/test_linearizer.py, test/test_randomness.py, test/test_schedule.py, test/test_tensor.py, test/unit/test_disk_tensor.py, tinygrad/features/search.py, tinygrad/helpers.py, tinygrad/tensor.py
Reverts tinygrad/tinygrad#2601
Broke benchmark CI
=> Revert "threefry_2x32"

examples/mixtral.py
=> remove mixtral weight to clang first

test/test_assign.py, tinygrad/lazy.py, tinygrad/realize.py
Reverts tinygrad/tinygrad#3796
=> Revert "add failing assign test"

tinygrad/device.py, tinygrad/features/jit.py, tinygrad/features/search.py, tinygrad/runtime/graph/hsa.py
the CUDA benchmark passed when we reran.
=> add outbufs back

test/test_linearizer.py, test/test_linearizer_failures.py, test/test_ops.py, tinygrad/codegen/uops.py
=> disable simplify_phi_loops

test/test_arange.py, tinygrad/tensor.py
revert to old cumsum opt while phi simplification is disabled.
added a flops complexity test for this
=> use old cumsum optimization for arange

.github/workflows/benchmark.yml
50% more hcopt perf with this one weird trick
=> use BS=128 and BS=768 for resent benchmark

test/test_linearizer.py, test/unit/test_symbolic.py, tinygrad/codegen/uops.py, tinygrad/shape/symbolic.py, tinygrad/tensor.py
See #3808, related to #3530
The division can't be factored, the param wasn't passed through when floordiv called itself. I see this caused a number of reverts, apologies.
=> Fix factoring bug (O(n) arange related)

tinygrad/runtime/driver/hsa.py, tinygrad/runtime/graph/hsa.py, tinygrad/runtime/ops_hsa.py
just a clean up of how we handle singnals
=> clean up hsa driver

test/unit/test_symbolic.py, tinygrad/shape/symbolic.py
might add more indexing ALU though
@chaosagent fyi
=> factor out partial in SumNode div int

tinygrad/realize.py
These two ideas help with a simpler multioutput implementation:
- We don't need to track LoadOps.CONST in the graph and in_degree, they are always generated.
- `seen` can update on the spot when the realize is sorted.
=> conceptual bfs simplification

examples/llama.py
@wozeparrot fyi in case the format change breaks the bot
=> show llama bandwith with timing

extra/optimization/helpers.py, test/external/fuzz_linearizer.py, test/external/verify_kernel.py, tinygrad/device.py
refactor fuzz_linearizer comparison to allow it to be used in for BEAM_VERIFY in device.py
Closes #3819
=> log optimized kernels and a script to compare with non-optimized ones

tinygrad/shape/view.py
=> fix View.pad arg type

test/test_ops.py, tinygrad/tensor.py
also added comment of the behavior if there are multple, and more tests
=> user _resolve_dim in argmax

tinygrad/runtime/graph/cuda.py
fix hlb_cifar nan loss on multigpus cuda
=> switch devices running cudagraph

.github/workflows/benchmark.yml
ran 30 runs and the lowest i see is 93.35. lowered to 93.3 for now.
maybe reenable ema later if it reduces variance
@uuuvn fyi i will test and merge ring allreduce if all looks good
=> lower hlb_cifar acc to 93.3

tinygrad/renderer/cstyle.py
Replaces [amd_hip_bfloat16](https://github.com/ROCm/clr/blob/develop/hipamd/include/hip/amd_detail/amd_hip_bfloat16.h) - something like this is a prereq for #3851
=> tiny version of amd_hip_bfloat16

tinygrad/realize.py, tinygrad/runtime/ops_cuda.py
=> cuda transfer + async copyin

test/helpers.py, test/test_dtype.py, tinygrad/renderer/assembly.py
added negative int for int case
TODO: test this on real GPU. test passed on tinybox
=> diverse test value in test_dtype DATA based on dtype

test/test_assign.py, tinygrad/nn/optim.py, tinygrad/realize.py
@Qazalin this is why I needed prerealize, maybe you have a better way?
=> fix assign

tinygrad/features/jit.py, tinygrad/runtime/graph/cuda.py, tinygrad/runtime/ops_cuda.py
graph is multidevice, quite not huge perf impact (test hlb, 2gpus). need to enqueue transfers as well to get the speed
=> init multidevice cuda graph

tinygrad/renderer/assembly.py
=> cheap less lines in ptx

tinygrad/tensor.py
=> touchup einsum

examples/mlperf/model_train.py
=> hotfix check ckpts before writing achieved model

test/external/fuzz_linearizer.py, test/helpers.py, test/test_linearizer_failures.py, tinygrad/renderer/cstyle.py
fixed some bf16 cast issue since it does not have `.name`. also more robust if there are lang specific type override
=> replace dtype.name str with render_dtype in cstyle

tinygrad/runtime/ops_cuda.py
Enables the new `--minimal` option added to NVRTC in CUDA 12.4, as mentioned in 
---
Test program:
```python
from time import perf_counter_ns as pc
z = Tensor.ones(1).relu()
st = pc()
z.realize()
et = pc()
print(f"Time taken: {et-st:>12,} ns")
print(z.numpy())
```
Before this PR with CUDA 12.4:
```bash
fluffy@mist in tinygrad :: CACHELEVEL=0 DISABLE_COMPILER_CACHE=1 python hello_tiny.py
Time taken:   21,606,017 ns
[1.]
```
With this PR and CUDA 12.4:
```bash
fluffy@mist in tinygrad :: CACHELEVEL=0 DISABLE_COMPILER_CACHE=1 python hello_tiny.py
Time taken:   17,667,016 ns
[1.]
```
=> add --minimal flag to nvrtc

.github/workflows/test.yml, test/test_dtype.py
except casting negative float to unsigned integer which is undefined
=> include negative float in test_dtype

tinygrad/runtime/ops_python.py
folded some lines. i just want to merge lars!
=> denser ops python

tinygrad/codegen/kernel.py, tinygrad/features/search.py
removed some `assert isinstance(dev, Compiled)` and lines
=> tiny search cleanup

.github/workflows/benchmark.yml, docs/env_vars.md, examples/hlb_cifar10.py, test/test_dtype.py, tinygrad/dtype.py
looking for standard names for these. we have FLOAT16 that does something to IMAGE and HALF to convert weights.
=> env var to change default float

.github/workflows/benchmark.yml, examples/beautiful_mnist.py
ran 100 times and the lowest was 97.57, and most are > 98. picked 97.5 for ci threshold
=> verify beautiful_mnist.py eval acc and put into benchmark ci

.github/workflows/benchmark.yml, tinygrad/renderer/cstyle.py
it runs if device gpu supports bfloat. updated ci benchmark too
=> bf16 support in metal

tinygrad/codegen/kernel.py
=> check only upcast int amount in upcasted_axis

tinygrad/dtype.py, tinygrad/features/multi.py, tinygrad/lazy.py, tinygrad/tensor.py
prereq cleanup to make const arg same python type as dtype
=> rename Scalar to ConstType and cast_scalar to as_const

test/test_assign.py, tinygrad/engine/schedule.py
This gives tinygrad specific asserts for unsupported assigns.
=> DAG cycle asserts

tinygrad/engine/schedule.py
We should account for all outputs when getting a MemBuffer's index.
This is a prereq for multioutput kernels.
```
__kernel void E2_n1(__global int* data0, __global int* data1, const __global int* data2, const __global int* data3) {
int val0 = data2[0];
int val1 = data3[0];
data0[0] = (val0+val1);
data1[0] = (val0*val1);
}
```
=> generic BufferOps.LOAD indexing

tinygrad/renderer/cstyle.py
=> for loop to generate hip math functions for different floats

tinygrad/engine/schedule.py
This is the last prereq for multioutput assign.
=> dynamic assign MemBuffer indexing

test/test_uops.py
=> update test_uops _equal to use assert_allclose

docs/abstractions2.py, extra/introspection.py, tinygrad/buffer.py, tinygrad/engine/realize.py, tinygrad/engine/schedule.py, tinygrad/lazy.py, tinygrad/tensor.py
All in service of putting the Buffers instead of the LazyBuffers in the ScheduleItem
=> create the buffer with the LazyBuffer

docs/abstractions2.py, tinygrad/engine/realize.py, tinygrad/lazy.py, tinygrad/tensor.py
TestMultiTensor.test_double_matmul_shard_W_0 fails
=> move assign logic into lazy.py

extra/gemm/amx.py
Update the AMX gemm to support the LLVM api
=> Update amx gemm

test/external/fuzz_linearizer.py, test/test_linearizer.py, tinygrad/codegen/kernel.py, tinygrad/codegen/linearizer.py, tinygrad/codegen/uops.py, tinygrad/engine/schedule.py, tinygrad/features/graph.py, tinygrad/lazy.py, tinygrad/ops.py, tinygrad/renderer/assembly.py, tinygrad/renderer/cstyle.py, tinygrad/renderer/llvmir.py, tinygrad/runtime/ops_disk.py
currently it's mixed between `==` and `is`, moved all to `is`
=> use is to compare with enum

examples/mlperf/model_train.py
it's annoying that BEAM with BENCHMARK does not run eval which has different kernels
=> beam search resnet eval too in BENCHMARK

examples/gpt2.py, examples/hlb_cifar10.py, examples/llama.py, examples/mlperf/model_eval.py, examples/stable_diffusion.py, extra/gemm/metal_matvec.py, extra/introspection.py, openpilot/compile2.py, test/external/external_benchmark_multitensor_allreduce.py, test/test_assign.py, test/test_speed_v_torch.py, tinygrad/__init__.py, tinygrad/buffer.py, tinygrad/device.py, tinygrad/engine/schedule.py, tinygrad/features/graph.py, tinygrad/helpers.py, tinygrad/nn/state.py, tinygrad/ops.py
break circular import between ops and buffer
=> move GlobalCounter to helpers

examples/mamba.py
make it read nicer and cleanup some movement methods and math simplification.
remaining issues:
790m, 1.4b, 2.8b model do not really run.
sampling is not implemented.
jit is incorrect.
some deadcode / wrong code path and copied from torch stuff.
=> cleanup mamba

extra/onnx_ops.py, test/test_const_folding.py, tinygrad/lazy.py, tinygrad/tensor.py
will do div and pow separately.
updated the test to use float Tensor as Tensor.ones defaults to use float
updated onnx ops because it was depend on tensor converting None to 0
=> move const folding of ADD/SUB/MUL from tensor to lazy

extra/gemm/simple_matvec.py
we can test with this or add it to CI for benchmarks
=> extra/gemm/simple_matvec: add simple_matvec.py

tinygrad/function.py, tinygrad/tensor.py
=> use *0+1 for Tensor.pow base case, remove function.Zero

test/test_const_folding.py, test/test_multitensor.py, tinygrad/features/multi.py
fixed multi const folding for sharded const.
=> don't call contiguous for unpadded const into multi tensor

tinygrad/codegen/uops.py, tinygrad/ops.py, tinygrad/runtime/ops_python.py
will use this for const folding in lazy too
=> move exec_alu from uops to ops

tinygrad/device.py
llvm has problems with fp16 and comparing with nan
=> use clang as default instead of llvm for cpu

tinygrad/renderer/assembly.py
Updated as promised. I left out `ptr_arm` as a separate function as it's quite complex and needs to be called for all LOAD/STORE not fitting that well with the pattern matcher
=> Refactor the use of pattern matcher in ptx

tinygrad/engine/schedule.py
The first output should _only_ be a unique key for a ScheduleItem. This diff refactors some parts of the scheduler that treat it as the only output.
=> Graph ScheduleItems

test/test_pattern_matcher.py, tinygrad/codegen/uops.py, tinygrad/renderer/assembly.py
Your last comment on the previous pr clarified what are the expectations for this - hope my question was not interpreted as stalling on this, just wanted to make sure about the direction
=> Add pattern matcher tests, move uop transforms from assembly to pattern

test/test_const_folding.py, test/test_ops.py, test/test_uops.py, tinygrad/lazy.py, tinygrad/tensor.py
changed the underlying arg directly
=> const fold cast unrealized_unpadded_const

tinygrad/features/multi.py, tinygrad/lazy.py, tinygrad/tensor.py
realized #3580 was doing the same thing. unmasked is more accurate
=> is_unrealized_unpadded_const -> is_unrealized_unmasked_const

test/test_pattern_matcher.py
something about the PTX rewrite is incorrect that it has duplicated rewritten uops
=> failed test in test_pattern_matcher

extra/onnx.py
taken from #3896 
currently half is still interpreted as float
=> onnx buffer_parse clean up

examples/mlperf/helpers.py, examples/mlperf/model_train.py, tinygrad/runtime/autogen/hsa.py
Where did the try/except go on ctypes.CDLL? We don't need the hsa library anymore.
=> support MOCKDATA=1 for resnet

test/test_assign.py
=> assign jit test case with other tensor as input

.github/workflows/benchmark.yml
this can catch multi tensor issue on mac.
=> metal CI run llama with 4 shards

test/test_multitensor.py
This test was broken from its introduction in #4032
=> Fix broken test

extra/models/llama.py
similar to optimization in gpt2. simpler code and ~2% speedup
=> use single tensor for llama kv chache

test/test_ops.py, tinygrad/tensor.py
As the title says. It has the same api as Torch
=> add lerp operation to tensor

tinygrad/renderer/assembly.py, tinygrad/renderer/cstyle.py
variable prefix is never optional (removed the default "t") and UOp can be optional (added the default None).
=> Update ssa input order and annotate types in cstyle and assembly

tinygrad/runtime/ops_kfd.py
Two small fixes as I'm getting tinygrad working with KFD.
=> Fixes for ops_kfd

test/models/test_mnist.py, test/models/test_real_world.py, test/test_fuzz_shape_ops.py
made sure the test is still covered by some other backends
=> skip a few clang test that took > 30 seconds in CI

tinygrad/runtime/graph/cuda.py, tinygrad/runtime/ops_cuda.py
=> cudagraph memcpy through host

tinygrad/engine/schedule.py
_recursive_lazyop already has all the outputs to offset the input idx - we don't need to store the same state twice.
=> refactor MemBuffer indexing

test/test_dtype.py, tinygrad/features/multi.py, tinygrad/function.py, tinygrad/lazy.py, tinygrad/tensor.py
note that this does not change `mean` behavior that intermediate sum is casted to half before div
=> move sum acc_dtype into lazy so it applies to backward

tinygrad/runtime/graph/cuda.py
=> hotfix: CUDA_P2P works

.github/workflows/benchmark.yml, test/external/verify_kernel.py, test/test_const_folding.py, tinygrad/lazy.py
testing perf, also this might have issue with assign?
=> remove CAST_BEFORE_VIEW

examples/mlperf/model_train.py
7.99 hours was rendered as 7h0m.
=> correct resnet estimate time

examples/mlperf/model_train.py
working on measuring compile time
=> TRAIN_BEAM and EVAL_BEAM for resnet

tinygrad/engine/schedule.py
This is because a set doesn't maintain insertion order.
for perf: Element lookup and iteration on realizes is still o(1) and o(n).
tested with:
- Running `DEBUG=2 python3 test/test_multitensor.py TestMultiTensor.test_simple_add_X` no longer has different order.
- Multi output fusion works without heavy sorting
=> keep order in realizes

.gitignore, tinygrad/features/search.py
not the highest possible performance, but adequate for most usage
TODO: will add testing to show performance before and after
=> search: BEAM_UOPS_MAX to prune candidates with too many uops

examples/mlperf/model_train.py
also run eval in benchmark mode if either one is positive
=> log resnet TRAIN_BEAM / EVAL_BEAM

test/external/verify_kernel.py, tinygrad/device.py
also add printing of ast and applied_opts during verify_kernel to more easily debug errors if they come up
=> logging: change LOGKERN to LOGKERNS to match LOGOPS
