- .github/workflows/test.yml
no need to append a colon for these events as we didn't specify any activity types or configuration
> clean up CI (triggered events)

- .github/workflows/test.yml
- requirements.txt
Getting rid of invalid GPU error by getting pytorch cpu-only version
> fix for invalid GPU error caused by (test/test_net_speed.py::TestConvSpeed::test_mnist) when testing in CI

- tinygrad/utils.py
This allows tinygrad to work on windows during first time run. (As Windows unable to understand /tmp path, caused it unable to load)
> Fix temp location for windows

- examples/efficientnet.py
- tinygrad/gradcheck.py
- tinygrad/ops.py
I don't really like two code options and not liking the `g` loop. I anyways leave it here. It is 10% slower on `efficientnet` but 5x faster `test_net_speed.py`. Probably needing to write own tensorop anyways.
> alternative to einsum which is slow in extreme cases

- examples/efficientnet.py
Reverts geohot/tinygrad#48
now stretches potrait pictures and adds unnecessary code.
> Revert "flip the aspect ratio, of the picture is in portrait"

- README.md
Since, tinygrad is in active development, shouldn't users use --upgrade flag for pip ?
> Use --upgrade since its in active dev

- tinygrad/tensor.py
Fixes TypeError: sequence item 0: expected str instance, int found
triggered by https://github.com/inducer/pyopencl/blob/v2020.2.2/pyopencl/__init__.py#L1500
in pyopencl v2020.2.2
e.g. when answers=[0,2] but only one GPU is available
> GPU Selection works when len(answers)>ngpus

- tinygrad/utils.py
#62 If requests.get fails during a download, the incomplete file is passed
without a size check. This causes errors during image/model loading.
> fetch() 'Ran out of input' fix

- tinygrad/utils.py
This was introduced by PR #65. os is imported in fetch and is not needed elsewhere. I mean line count matters, right?
> Delete unnecessary import in utils.py

- test/test_ops.py
Using relative error is generally better, except for special cases where absolute values are so small that relative error are naturally larger (small divisor gives larger relative error).
> tests should use rtol unless special case

- test/test_ops.py
Used `with self.subTestI(...):` in other tests that loop over parameter sets.
Also added strides test cases to `test_maxpool2d_strided_fwd()` which were forgotten in #81.
> label op subtests by params

- test/test_ops.py
- tinygrad/ops.py
Strided CPU Pooling was introduced but assumes small kernel size
(<=(10,10)), but efficientnet.py feeds kernel_size=(112,112).
This causes a huge array buffer allocation in stack_for_pool() that
hangs inference for a long time or until system OOM.
Revert CPU Pooling for now, and re-introduce #74 later with a new
global-average-pooling op that can be used instead of avgpool2d with
large kernel size for efficientnet inference.
#86
> revert b0c0c5d: Strided Pool funcs (#74)

- test/test_ops.py
- tinygrad/opsgpu.py
* Cleanup stride leftovers.
* Add test for Global Average Pooling via tensor.avg_pool2d.
Is avg_pool2d() really broken on GPU backward()? Current tests on GPU are passing for me, so if it is, tests should be added for the failure cases and I'll add the NotImplementedError back in.
> finish unsupporting strided pool, add global avg pool test

- test/test_ops.py
- tinygrad/opsgpu.py
Semantics of broadcasting that were implemented:
- dimensions of the same size can be broadcast together
- dimensions can be broadcast together as long as at least one of them has size 1
- if one of the two tensors to be broadcast has fewer dimensions, its shape will be padded with 1s (added onto the end)
To do this, I also refactored `buffer_zeros` by creating a function `buff` that creates a buffer from a numpy array.
> General broadcasting of binary operations

- requirements.txt
Seeing if tests pass with fixed pyopencl version. Not entirely sure how test suite works but guessing we're pip installing newest version
> fix pyopencl

- tinygrad/tensor.py
Otherwise `.cpu()` is broken if default is gpu
> .cpu() is broken if default is set to gpu

- tinygrad/tensor.py
In [`tensor.py`](https://github.com/geohot/tinygrad/blob/master/tinygrad/tensor.py#L14-L40) the `ProfileOp` class is defined twice for `DEBUG` and otherwise, I've defined it once by just `pass`ing it if it's not `DEBUG`.
I don't know if that's a good approach but defining it once seems nicer and [saves some lines yo](https://github.com/geohot/tinygrad/blob/master/tinygrad/tensor.py#L12) (https://github.com/geohot/tinygrad/issues/94).
```
================================= test session starts =================================
platform linux -- Python 3.8.6, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/mufeedvh/open-source/tinygrad
collected 58 items
test/test_mnist.py ......                                                       [ 10%]
test/test_net_speed.py . …
```
> Define `ProfileOp` class once

- README.md
Installing is done with pip3, but the tests are being run with python2 which may not work.
> Made the readme more consistent

- .github/workflows/test.yml
OpenCL was not actually being tested as pyopencl was not installed.
Before:
```
=================== 46 passed, 1 xfailed in 61.57s (0:01:01) ===================
```
After:
```
============ 83 passed, 2 skipped, 5 warnings in 190.54s (0:03:10) =============
``
> Add pyopencl to dependency installs

- examples/train_efficientnet.py
- test/test_tensor.py
Add a test mentioned in #165. Verified it fails if deepwalk returns duplicate nodes.
Also fix train_efficientnet example, it is referencing a removed field.
> Add diamond model test

- tinygrad/tensor.py
These lines make it so that require_init_gpu() function always selects available GPUs. In previous versions, require_init_gpu() could accidentally select CPU as device.
> require_init_gpu() function selects GPU as device and falls back to CPU if none are available

- .github/workflows/test.yml
Validating every Python code's indentation is 2 spaces.
```bash
if [[ $(pylint --jobs=0 --indent-string='  ' * | grep "Bad indentation") ]]; then exit 1; fi
```
This one-liner exits with error if there is any indentation size other than `2`.
- `--jobs=0` - Use multiple processes to speed up Pylint. Specifying 0 will auto-detect the number of processors available to use.
- `--indent-string='  '` - String used as indentation unit.
> Added indentation linter

- README.md
- extra/training.py
- requirements.txt
- setup.py
- test/config.py
- test/test_gc.py
- test/test_mnist.py
- test/test_net_speed.py
- test/test_nn.py
- test/test_ops.py
- test/test_optim.py
- test/test_tensor.py
- tinygrad/ops_gpu.py
- tinygrad/optim.py
- tinygrad/tensor.py
This PR aims to resolve 4 issues:
1. No tests for ANE
2. Device to device conversion
3. Failure to run GPU Tests
4. Failing GPU tests
__Sorry, but this will be long.__
Test calls have been added for the ANE device which will envoke ANE tensors when running tests. Same as GPU
``` python
@unittest.skipUnless(ANE, "Requires ANE")
class TestNNANE(TestNN):
device=DeviceTypes.ANE
```
To be able to support ANE in tests, it is required that ANE support the same conversion as CPU->GPU and GPU->CPU. 
I have created a universal any to any converter. This function accepts any of the accepted datatypes (GPUBuffer, ane.tensor and any np.ndarray compatible data) and returns the converted data.
``` python
@staticmethod
def data_to_device(data, device=DeviceTypes.CPU):
```
CI tests have not been run since …
> All devices are equal!

- ane/2_compile/compile.m
add a compile.m corresponding to compile.mm
build with
```clang compile.m -F /System/Library/PrivateFrameworks/ -framework ANECompiler -framework Foundation```
CoreFoundation framework is a C library.
Foundation is an Objective-C framework.
CF data structures in CoreFoundation usually have corresponding NS data structures in Foundation, e.g.,
NSDictionary is "toll-free bridged" with its Core Foundation counterpart, CFDictionary.
See [1].
[1] https://developer.apple.com/library/archive/documentation/General/Conceptual/CocoaEncyclopedia/Toll-FreeBridgin/Toll-FreeBridgin.html
> add an aneccompile example in Objective-C

- tinygrad/ops_ane.py
- tinygrad/ops_cpu.py
- tinygrad/ops_gpu.py
- tinygrad/tensor.py
For all ops, the `forward` and `backward` methods should be static.
So, given that all ops inherit from `Function`, the `__new__` method in `Function` replaces `forward` and `backward` with their static version. This saves about 50 LOC in ops_cpu.py, ops_gpu.py and ops_ane.py.
> saving 50 LOC with automatic @staticmethod for forward and backward

- examples/vgg7.py
- extra/kinne.py
- extra/waifu2x.py
(test image used here is a part of tinygrad's `logo.png`)
+ Importing of existing Waifu2x vgg7 JSON models (confirms that this works, used for above test image)
+ Training (not fully tested to completion, but it at least shows something this time)
+ Has a little "not quite a format" for storing parameters. (It's just flat binaries with a loader for convenience.)
+ Proper tiling/etc. for normal upscaling runs, but also able to invoke model directly (another debugging aid)
+ The 4x4 (overlapping in a 2x2 grid) deconvolution layers used by Upconv7. Upconv7 delivers 'acceptable' accuracy without significant implementation complexity, while vgg7 delivers 'um.' accuracy with almost no implementation complexity.
+ Adding GPU support to this (but I don't have OpenCL setup here)
> vgg7 (image upscaling) implementation - not the best, but it works

- .github/workflows/test.yml
This pull request fixes the OpenCL installation problem while running tests with Github actions.
> Fixed OpenCL installation while running tests

- tinygrad/ops_ane.py
This [commit ](https://github.com/geohot/tinygrad/commit/0eda3eb421458cae74b5ac75a24a9116ba192523) moved the `ane` folder into the `accel` folder.
I believe this brakes loading the `relu.hwx` file on `ops_ane.py`.
I'm Enjoying your streams very much!
> Fix loading `relu.hwx` from the wrong path on ops_ane.py

- tinygrad/llops/ops_cpu.py
We can replace += with = since we only change tmp once.
Now np.empty() can replace np.zeros() which might be slightly faster.
This saves a few milliseconds, best case ~60ms.
(However, most of the time in ops_cpu.processing_op() seems to be spend on np.reshape())
> unnecessary assign add in cpu processing_op

- extra/gemm/gemm.c
Aligning them to 64 bytes yielded a subtle performance increase (~5%).
Fixed the pointer width compiler warning.
> Align matrices to cacheline width

- tinygrad/tensor.py
No need for the `dispatch` method, this can be done by `functools.partialmethod`
> Use functools.partialmethod when registering Function to Tensor

- tinygrad/nn/__init__.py
When running the resnet training example, I saw that batch_invstd can become none since it was set to None when previously training. This should fix it.
> Fix batch_invstd none in BatchNorm2D

- .editorconfig
Almost every IDE or text editor supports [editorconfig](https://editorconfig.org/).
I've set it up to just enforce the 2 space python indentation for now.
> Basic editorconfig support

- accel/llvm/ops_llvm.py
partial does not take static methods in older python (my version Python 3.9.13)
```
set, clr = partial(nop_op_imm5, 17, 0), partial(nop_op_imm5, 17, 1)
TypeError: the first argument must be callable
```
This change fixes that.
> Make tinygrad work with older python version

- test/test_speed_v_torch.py
Maybe we should just write the ansi escape codes by hand?
> don't fail when termcolor is not installed

- README.md
I had some confusion while trying to set up the examples with Stable Diffusion, turned out you might need to put the weight into the `weights/` dir
> Add step for setting up Stable Diffusion

- README.md
This commit resolves issue https://github.com/geohot/tinygrad/issues/453
In the example code in the README.md, when it is run, it prints for Tiny Grad the tensors as:
<Tensor <LB (3, 3) op:MovementOps.RESHAPE> with grad None> <Tensor <LB (1, 3) op:MovementOps.RESHAPE> with grad None>
But to be equivalent to the output of the Torch example, we need to use numpy() to get it to show:
[[ 2.  2.  2.]
[ 0.  0.  0.]
[-2. -2. -2.]]
[[1. 1. 1.]]
> Print out the tensor using numpy().

- accel/triton/ops_triton.py
- test/test_ops.py
Fixes some bugs to pass all tests of test_ops.py:
Some notes:
Padding:
Triton doesn't support python's and operator (Unsupported node: BoolOp), the only way I got it working is by replacing "&&" with "\*1\*". Using only one "*" resulted in a error (LLVM ERROR: Cannot select: 0x5582df7a81a8: i1 = mul 0x5582df7a8070, 0x5582df7a8140)
Support more ops:
- Power: trition doesn't have a pow operation built-in, a workaround is to use tl.exp(tl.log(A)*B), see [link](https://github.com/openai/triton/issues/506), there are some problems with integers, but not float's, I've added some tests to verify the mentioned edge cases work.
- Sign: already implements GT0
Allocate return buffer:
test_ops originally failed, because the return buffer wasn't connected to bufs[0].
It's handled for the GPU at …
> Triton bugfixes & implementation of remaining ops

- accel/triton/ops_triton.py
- setup.py
This PR fixes 3 bugs:
- A memory leak, that was caused by kernel caching, where the buffers and gpu memory allocations weren't deleted, because they were referenced by the kernel cache.
- An illegal memory access in efficientnet and the openpilot tests. This was really hard to find. They only appeared in complex models, but after analyzing the kernels with compute-sanitizer I could figure out that every kernel with zero padding had many of these errors, but only in a few cases it resulted in the termination of the kernel. The root cause of the error is, that data of the zero padded area is requested, even though it is not used and the 
branch of the select statement shouldn't be executed. This results in reads outside of the buffer and if these reads are in another buffer, just wrong …
> Fix triton illegal memory accesses and memory leak

- accel/triton/ops_triton.py
Forgot to push this commit to the last PR https://github.com/geohot/tinygrad/pull/512
> Triton fix invalid kernel launches by flattening the grid

- setup.py
- test/test_ops.py
- our implementation of gelu is the tanh approximation, available in PyTorch
- note that [by default, PyTorch doesn't approxiate gelu](https://pytorch.org/docs/stable/generated/torch.nn.GELU.html#torch.nn.GELU), do we want to match it?
- `quick_gelu` hasn't been added to PyTorch, but we have the implementation [here](https://github.com/pytorch/pytorch/issues/39853#issuecomment-858211939)
> Add test for quick_gelu

- test/test_shapetracker.py
Hello!
This PR posits an improvement on the TestZeroViewShapeTracker test ([issue 476](https://github.com/geohot/tinygrad/issues/476)).
Previously, we were comparing the shape of the ST after the pad, without regards to the ZeroView attribute. 
I've added a simple ZeroView class which should be contained within the test shape tracker as a result of the .pad operation.
Thanks!
> TestZeroViewShapeTracker fix test

- test/test_tensor.py
- tinygrad/helpers.py
- tinygrad/tensor.py
This PR modifies the behavior of `Tensor.__getitem__` in several ways, with the goal of bringing tinygrad indexing more in line with the behavior of numpy and torch indexing. The changes in behavior are as follows:
- Indexing a tensor with a negative integer N now returns the Nth-to-last element instead of zeros.
- Slicing a tensor from a negative starting position N now slices from the Nth-to-last position instead of padding the tensor with zeros.
- Indexing a tensor with an integer not in the range [-size, size) now throws an IndexError instead of returning zeros.
- Slicing a tensor past its bounds is now equivalent to slicing with None, instead of padding the tensor with zeros.
- Indexing a tensor with None or np.newaxis along axis A now reshapes the tensor with an additional dimension …
> NumPy-like semantics for Tensor.__getitem__

- test/test_speed_v_torch.py
With the recent refactor, tinygrad is faster than PyTorch in most test. I've updated the test to show where tinygrad is faster, and use a different color for the ratio.
> Show where tinygrad is faster in speed test vs torch

- setup.py
to be able to install from zip archive.
Though `tinygrad/llops/ops_triton.py` symlink breaks `import tinygrad` if installed from zip, I just rm ops_triton.py post install
> Add missing packages to setup.py

- README.md
Makes it easier for people to find tinygrad.org.
> Add tinygrad.org reference in Readme (1 liner)

- examples/mnist_gan.py
from discord:
> examples/mnist_gan.py appears functionally broken; it only generates black images with a grey dotgrid
changes made:
- use scaled_uniform instead of uniform to avoid overflow
- remove legacy behavior (e.g. using .numpy() instead of .data)
- refactor and improve readability
final output:
> Fix mnist gan example

- test/test_graph.py
- tinygrad/graph.py
- tinygrad/ops.py
Originally wanted to include the PRUNEGRAPH into the creation step of the graph, but couldn't get that working(Needed something like the AST of a DeviceBuffer).
Removes a few lines, has a few readability improvements and adds the GRAPHPATH option to set the output location and name of the graph (I like to use ./net)
Produces the same graph for the test_efficientnet.py(except adding a prunable key to the nodes).
> Refactor graph

- tinygrad/runtime/metal.py
Moved the compute pipeline creation to init
Converted the copyin function to use numpys copy, removing realloc of MTLBuffer. 
tested on an intel mac
> small tweaks to the metal runtime

- examples/yolov3.py
Fixes the following error and warning for the yolov3 example:
```
File "tinygrad/examples/yolov3.py", line 12, in <module>
from extra.utils import fetch, get_parameters
ImportError: cannot import name 'get_parameters' from 'extra.utils' (tinygrad/extra/utils.py)
tinygrad/examples/yolov3.py:595: DeprecationWarning: The binary mode of fromstring is deprecated,
as it behaves surprisingly on unicode inputs. Use frombuffer instead
img = cv2.imdecode(np.fromstring(img_stream.read(), np.uint8), 1)
```
> Fix yolov3 example

- test/test_tensor.py
- tinygrad/tensor.py
Even though several examples try to be deterministic by setting `np.random.seed(1337)`, the resulting models are different for each run. Root cause is that `np.random.seed` doesn't affect random functions that use the default generator `np.random.default_rng()`
> Fix Tensor random functions determinism with same seed

- extra/onnx_ops.py
little hack to correct included padding in avgpool
the only still failing avgpool tests are the ones captured by the asserts: `auto_pad == "NOTSET"` and `ceil_mode == 0`
also fixes inception model
> fix: avgpool without counting padding and inception

- extra/onnx_ops.py
Passing all tests except for the ones that use the Cast opt
onnx expects the return to be layernorm, mean, invstddev
> layer norm support in onnx

- README.md
- extra/onnx_ops.py
- test/test_ops.py
- tinygrad/codegen/gpu.py
- tinygrad/codegen/llvm.py
- tinygrad/mlops.py
- tinygrad/ops.py
- tinygrad/runtime/ops_cpu.py
- tinygrad/runtime/ops_torch.py
- tinygrad/tensor.py
Opening as a draft to get feedback on a couple things
- onnx expects a bool tensor to be returned so I am using .numpy().astype(bool) - hacky for now until we add types?
- created mlops functions to take advantage of the broadcast helper function in tensor - but not sure if this makes sense or if there even is a backwards pass for these operators? 
----
added comparison functions in tensor class
used mlops to take advantage of the broadcast function
tested with the following runtimes
- CPU
- GPU
- CUDA
- LLVM
- TORCH
adds onnx ops Less, LessOrEqual, Greater, GreaterOrEqual, Equal, all tests passing except for the ones that require Or operator
> adding comparison operators 

- extra/utils.py
I get this error when I run on windows:
```
λ python examples\efficientnet.py https://media.istockphoto.com/photos/hen-picture-id831791190                                                                             
cuda backend not available No module named 'pycuda'                                                                                                                        
gpu backend not available No module named 'pyopencl'                                                                                                                       
llvm backend not available No module named 'llvmlite'                                                                                                                      
metal backend not available No module named 'Metal' …
```
> Fix windows file permission error

- README.md
- tinygrad/tensor.py
Fixes #637
I also added some notes to the readme testing section to help others, let me know if you want removed / changed.
Original Error:
```
test\models\test_train.py .Windows fatal exception: stack overflow
Thread 0x00002074 (most recent call first):
File "C:\Users\Patrick\AppData\Local\Programs\Python\Python39\lib\threading.py", line 316 in wait
File "C:\Users\Patrick\AppData\Local\Programs\Python\Python39\lib\threading.py", line 574 in wait
File "D:\COMMAI\tinygrad\venv\lib\site-packages\tqdm\_monitor.py", line 60 in run
File "C:\Users\Patrick\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950 in _bootstrap_inner
File "C:\Users\Patrick\AppData\Local\Programs\Python\Python39\lib\threading.py", line 908 in _bootstrap
Current thread 0x00002238 (most recent call first): …
```
> Expand the inline loop to prevent stack overflow from `_deepwalk`

- examples/efficientnet.py
for #701. This is more of a temporary fix. Once we have uint8 support we can probably remove it.
> Cast image to float32

- examples/transformer.py
- extra/training.py
- tinygrad/helpers.py
Without this, examples/transformer.py didn't run. With this change it runs successfully.
> add int64 as supported dtype from numpy

- examples/yolo/waifu2x.py
- examples/yolov3.py
Got an error while I was running yolov3. Looks like the implementation of transpose has been changed to match PyTorch now. So I've updated the parameters for transpose in the examples.
```
% GPU=1 python3 examples/yolov3.py                                                       [13/181]
Modules length: 107                                                                                                    
Loading weights file (237MB). This might take a while…                                                                 
running inference…                                                                                                     
Traceback (most recent call last):                                                                                     
File …
```
> Permute examples

- tinygrad/lazy.py
The `ImportError` does not catch some errors from `pyopencl`, e.g.:
`pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR`.
Thus it may be more appropriate to use a trivial `Exception`.
> Do not specify errors when trying to load devices.

- extra/onnx.py
- extra/onnx_ops.py
- tinygrad/helpers.py
Original goal was to add support for `Pad` operator of onnx.
tests for constant padding pass. overall test report: `436 failed, 297 passed` to `405 failed, 328 passed`.
i had to add int64 to dtypes, because onnx tests for constant padding directly call run_onnx with int64 ndarrays.
nd padding with non zero constants is now possible
> padding changes for onnx

- examples/train_resnet.py
- models/resnet.py
Changes made:
- use `scaled_uniform` instead of `uniform`
- use SGD instead of Adam for higher test accuracy
- increase the number of steps per iteration from 50 to 100
This gives us a test accuracy of around 95%
> Fix train_resnet example

- tinygrad/codegen/cstyle.py
- tinygrad/runtime/ops_cuda.py
Running `CUDA=1 python3 examples/llama.py --timing --prompt "Hello." --temperature=0 --tinyfake --count 1` gave errors:
```
kernel.cu(5): error: no suitable constructor exists to convert from "float" to "float4"
float4 acc0_0 = 0.0f;
```
and
```
AttributeError: 'RawCUDABuffer' object has no attribute '_cl'
```
I know you don't like extra lines, but these two changes fixed the issues.
> Fixed two errors when running LLaMA example with CUDA=1

- .gitignore
- test/test_ops.py
- tinygrad/tensor.py
This PR adds `Tensor.stack()` and `Tensor.repeat()`. They mirror the namesake PyTorch methods.
In order to make **einops** work with tinygrad tensors (which is what I’m originally trying to do) the logic of `stack()` and `repeat()` is needed to add tinygrad as a new einops backend. In particular, it’s needed here
and here
I can just simply add the code there, but I though it may be more useful/correct(?) if provided directly by tinygrad (and not just inside einops).
> Add Tensor.stack() and Tensor.repeat() (...trying to make einops work with tinygrad)

- test/unit/test_flopcounter.py
Ran all the tests, got a warning, checked stack overflow to see how to get rid of it :smile: 
Seems like pytest thought that `TestBuffer`  was supposed to be a test and was complaining about it, so setting that variable to False tells pytest to not treat it as a test. 
I get a few other warnings about overflows as well
> Fix PytestCollectionWarning when running tests

- .gitignore
- datasets/librispeech.py
- examples/mlperf/metrics.py
- examples/mlperf/model_eval.py
- examples/mlperf/model_spec.py
- models/rnnt.py
- test/models/test_rnnt.py
For now dataset has to be downloaded manually from https://www.openslr.org/12/. mlperf uses `dev-clean`.
Then all the flacs have to be converted to wav using something like:
```fish
for file in **/*.flac; ffmpeg -i $file -ar 16k "$(dirname $file)/$(basename $file .flac).wav"; end
```
Need this file as well https://github.com/mlcommons/inference/blob/master/speech_recognition/rnnt/dev-clean-wav.json.
I'm currently using `librosa` for the stft and audio file loading but it might be possible to rewrite them to not rely on librosa.
The RNN-T bench is also slightly different from the other ones as feature extraction is part of the benchmark, so I'm not quite sure where to put the feature extraction function.
Edit: this is also pretty slow rn
Edit again: not slow anymore
> Add mlperf RNN-T model

- README.md
For non-contributors sufficient to not clone the repo.
Works also with editable mode this way:
```bash
python3 -m pip install -e git+https://git@github.com/geohot/tinygrad.git#egg=tinygrad
```
> One liner pip installation

- tinygrad/runtime/ops_gpu.py
The motivation for this is that on certain devices with multiple different gpus like a laptop with a dedicated and intergrated gpu, it may be preferable to prevent tinygrad from using a specific gpu like the intergrated one.
Specifically for me with a gfx1032 and a gfx1035, the gfx1035 crashes the kernel driver when used.
To fix this we allow the exclusion of gpu devices by name with the environment variable `CL_EXCLUDE`.
> Ability to exclude cl devices from being used

- examples/llama.py
- models/rnnt.py
- test/external/external_test_opt.py
- test/test_nn.py
- tinygrad/nn/__init__.py
Embedding is used in a few models now (RNN-T and LLaMA) and will be used in BERT and other language models as well. So we should promote it to nn.
Rewrote it to no longer rely on numpy which means that this can now be JIT compiled.
Added a test to see if it matches torch.
> Promote Embedding to `nn`

- extra/utils.py
On Linux or maybe more POSIX systems `os.rename` will fail if the source and destination are on different filesystems.
~~For me this is the case as the `NamedTemporaryFile` would be put somewhere under `/run` which is mounted as a tmpfs.~~
~~`shutil.move` does not have this limitation.~~
Edit: This now puts the temporary file in the same directory as the destination which allows `os.rename` to work.
> Put temporary file in the same directory as the destination file

- test/test_ops.py
- tinygrad/tensor.py
The reshape should only be necessary when multiplying a vector with a matrix - this fixes batched matmul.
> Don't collapse dimensions during batched matmul (FIX #799)

- test/test_nn.py
- tinygrad/nn/__init__.py
fixed running_var of BatchNorm2d where a test did not match pytorch's running_var.
BatchNorm2d is now implemented in the same way as pytorch, using the biased variance estimator for training and the unbiased estimator for inference.
Note that technically it would be more ideal to use the unbiased estimator for both training and inference, as mentioned here by Andrej Karpathy: 
https://www.youtube.com/watch?v=q8SA3rM6ckI&t=3920s
> Batchnorm2d fixed running_var

- test/unit/test_symbolic.py
- tinygrad/shape/symbolic.py
This diff modifies the `symbolic.py` file mainly to not rely on calls to the expensive `isinstance` by leveraging inheritance to dispatch the correct routines instead.
Changelog:
1. Get rid of `create_opnode` because it had a massive if-else ladder of checking the class type, replace by computing minmax bounds at init time of `OpNode`
2. Move logic for `__mul__`, `__floordiv__`, and `__mod__` inside each opcode
3. Rewrite the `Variable.sum` simplification routine to avoid having to order the list of `MulNodes` before grouping them
Local test suite is passing. Wait for CI
`test_net_speed.py` benchmark:
```
test/test_net_speed.py::TestConvSpeed::test_mnist torch forward pass:  19.031 ms
torch backward pass: 19.433 ms
475052 function calls (464120 primitive calls) in 280.306 seconds
Ordered …
```
> Optimizations in `symbolic.py`

- test/test_custom_function.py
The following error was thrown while running the TestCustomFunction unit test, even adding an overloadable attribute didn't fix the problem, hence the PR.
```
E       pyopencl._cl.RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE
E       
E       Build on <pyopencl.Device 'NVIDIA GeForce RTX 3050 Ti Laptop GPU' on 'NVIDIA CUDA' at 0x55b9b98c2cc0>:
E       
E       <kernel>:2:19: error: overloaded function 'atan2' must have the 'overloadable' attribute
E           __kernel void atan2(global float *c, global float *a, global float *b) {
E                         ^
E       cl_kernel.h:1879:27: note: previous overload of function is here
E       double16 __OVERLOADABLE__ atan2(double16, …
```
> fixed TestCustomFunction

- test/external/external_test_onnx_backend.py
There are ONXX tests for regular ops with a unsupported data types, such as test_max_uint8_cpu (int16, unint8, uint16, uint64, float64, ...). They don't get excluded by the current regex expressions.
I changed the exclusion regex, to include all tests containing these datatypes in their name, although I could write out all the tests in the format of test_\<OP\>_\<TYPE\>*, for clarity as well.
PASSED count is same pre & after the change (doesn't exclude any passing tests), but SKIPPED goes 1862 -> 1885.
Is a small change, but the first thing I noticed for getting to 0 FAILED. If some of these data types should work, I could look into making the tests PASS too.
> ONNX tests: exclude all unsupported filetype tests

- test/external/external_test_optim.py
- tinygrad/nn/optim.py
This is the first in what will hopefully be a series of prs to get RNN-T training working.
This adds the [LAMB optimizer](https://arxiv.org/abs/1904.00962) based on the official tensorflow implementation [here](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/optimizers/lamb.py).
I'm not sure what the best way to test this is as pytorch doesn't have LAMB implemented and the implementations that I could find are either [CUDA specific](https://nvidia.github.io/apex/_modules/apex/optimizers/fused_lamb.html) or [broken](https://github.com/jettify/pytorch-optimizer/issues/226). So thats why this is draft for now.
I have tested this on training a small net on MNIST and it does work.
It should also be possible to rewrite AdamW and Adam as functions of LAMB if we wanted to save …
> Add LAMB optimizer

- datasets/openimages.py
- examples/mlperf/model_eval.py
- examples/mlperf/model_spec.py
- models/resnet.py
- models/retinanet.py
- adds resnext to support loading retinanet pretrained on openimages
- object detection post processing with numpy. Some parts could easily be written with tinygrad ops but im not sure how useful that would be. imo it should stay decoupled from forward until the whole postprocessing is part of the graph.
- Just like the reference implementation i used **fiftyone** to download the dataset and convert it to coco format (probably overkill). And **pycocotools** for mAP evaluation.
evaluation result:
```
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.375
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.524
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.405
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | …
```
> add retinanet with resnet backbone

- models/transformer.py
The reason for 0 dropout (at the pretraining/causal lm stage is that on limited hardware, you want the model to learn the dataset patterns quickly first, then use dropout at fine-tuning. Because dropout can slow down accuracy at the lm stage. So optional dropout may allow features to be quickly learned first.
> default transformer dropout to 0

- models/resnet.py
- tinygrad/lazy.py
After the fix, running `test_resnet` gives the following output:
```
cache: entering
cache: exiting with size 26 allowed 31
```
Before the current change, it was showing 29(instead of 26)
Please confirm if this is the correct fix.
> Fix ResNet Kernel Fusion (from bounty)

- tinygrad/nn/optim.py
Follow up to https://github.com/geohot/tinygrad/pull/821
I'm not sure if we actually want this, it does save quite a few lines but it kind of loses the actual adam implementation, and it "adds" a test for the `adam` flag.
LAMB is essentially just LARS applied to Adam so if we just set the trust ratio to `1.0` its just Adam.
I'm not quite sure whats going on with METAL tho.
> Rewrite Adam/W as functions of LAMB

- test/test_tensor.py
- tinygrad/tensor.py
Same behavior as in [pytorch](https://pytorch.org/docs/stable/generated/torch.zeros_like.html#torch.zeros_like), if `dtype` is specified when using `Tensor.zeros_like()` then create tensor with given `dtype`, otherwise create it with the tensor's `dtype`.
> zeros_like use dtype if specified else default to tensor’s dtype

- extra/onnx.py
ONNX version can be any version, any version above 10 should have the same behaviour as version 10.
Slice can be implemented not only by version 10.
Fixes:
```
OnnxBackendNodeModelTest::test_slice_end_out_of_bounds_cpu
OnnxBackendNodeModelTest::test_slice_neg_cpu
OnnxBackendNodeModelTest::test_slice_start_out_of_bounds_cpu
```
This PR, however, does not fix that the whole slice implementation is buggy.
> Fix ONNX slice tests for model version > 10

- extra/onnx.py
As specified in the documentation for onnx split:
https://github.com/onnx/onnx/blob/main/docs/Operators.md#attributes-98
Axis defaults to 0
---
Fixes two tests:
Before: `=== 329 failed, 497 passed, 1808 skipped, 2 warnings in 18.43s ===`
After: `=== 327 failed, 499 passed, 1808 skipped, 2 warnings in 19.11s ===`
> Set Split Axis Default to 0

- tinygrad/helpers.py
Supports
```python
from tinygrad.helpers import Context
from tinygrad.tensor import Tensor
a = Tensor.ones(1)
b = Tensor.ones(1)
with Context(DEBUG=4):
(a+b).numpy() # DEBUG=4
```
This should be compatible with the current way of handling these vars. `DEBUG(x)` still works.
Could be useful for Device.DEFAULT as well.
> stack based context manager for DEBUG and IMAGE

- extra/onnx_ops.py
Before:
=== 307 failed, 519 passed, 1808 skipped, 3 warnings in 17.53s ===
After:
=== 304 failed, 522 passed, 1808 skipped, 3 warnings in 17.22s ===
> InstanceNormalization ONNX test fixed.

- extra/onnx_ops.py
- test/test_tensor.py
- tinygrad/tensor.py
I had to change `Tensor._rng` from outside because the ONNX tests use `np.random.seed()` for the expected dropout mask, and using `default_rng(seed)` won't give the same results as when the same seed is used in `np.random.seed(seed)` (because the latter [uses](https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html) a [RandomState](https://numpy.org/doc/stable/reference/random/legacy.html#numpy.random.RandomState)).
> Fix ONNX dropout and unify the implementation

- extra/onnx_ops.py
- test/test_ops.py
- tinygrad/nn/__init__.py
- tinygrad/tensor.py
Works by adjusting the padding in the call to `conv2d`
Added some tests for asymmetric args/bias while debugging this, we also now pass some more of the onnx tests
> Support `output_padding` in transposed conv

- test/models/test_end2end.py
- test/test_ops.py
- test/test_tensor.py
- tinygrad/codegen/linearizer.py
- tinygrad/nn/image.py
- tinygrad/shape/shapetracker.py
- tinygrad/tensor.py
This PR adds the following features:
- Zero-dim support:
```python
>>> from tinygrad.tensor import Tensor
>>> b = Tensor(10)
>>> b.shape
()
>>> ones = Tensor.ones(2,2,2,2)
>>> ones.sum().shape
()
>>> (ones.sum() * b).numpy()
array(160., dtype=float32)
>>> (ones.sum() * b.reshape(1)).numpy()
array([160.], dtype=float32)
```
- varargs support for `Tensor.zeros()` and `.ones()`: not only `Tensor.zeros(45, 65)` works, but also `Tensor.zeros([45, 65])`.
- Why: Make them consistent with their torch counterparts: e.g., `Tensor.zeros([])` should return a 0dim tensor.
- A refactored `Tensor.__getitem__()`.
- ~5.8x faster slicing:
```python
d = torch.arange(64**3).reshape(64,64,64)
%timeit old_getitem(d, s[1:32, 32:64, 1:64], print_results=False)
%timeit new_getitem(d, s[1:32, 32:64, 1:64], …
```
> Zero dim Tensor support

- examples/train_efficientnet.py
make it work out of the box for new users.
the default configuration of train_efficientnet is to use the smaller cifar dataset. import datasets.imagenet tries to open imagenet_class_index.json and will fail, unless user has already downloaded it.
> train_efficientnet: only import datasets.imagenet when IMAGENET is set

- test/test_ops.py
Pytorch 1.13 is being an idiot, but this is an easy fix.
The trick is to add `dim=None` if we are using `keepdim=True`.
I tested, and this still works with torch=2.0.1.
Here is the full log - it has to do with the Python - C interface if I understand it correctly.
```
$ env CPU=1 EXCLUDE_DEVICES=GPU pytest test/test_ops.py 
========================================================================== test session starts ===========================================================================
platform linux -- Python 3.10.11, pytest-7.3.1, pluggy-1.0.0
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/xl0/work/projects/tinygrad/tinygrad
plugins: …
```
> Fix .std() tests on torch=1.13

- extra/onnx_ops.py
In the last merge, I introduced a bug that made one of the 3 tests fails, this fixes it. My bad, sorry for the trouble
Before:
=== 295 failed, 531 passed, 1808 skipped, 2 warnings in 31.32s ===
After:
=== 294 failed, 532 passed, 1808 skipped, 2 warnings in 28.58s ===
> Fixed all ConstantOfShape test suite

- test/external/external_test_onnx_backend.py
Excluded string type tests. 
The tests were causing the following error because tinygrad does not support strings/object types:
```
def from_np(x) -> DType: return asdict(dtypes())[np.dtype(x).name]
KeyError: 'object'
```
The excluded tests:
- test_equal_string_broadcast_cpu
- test_equal_string_cpu
> exclude string type from external_test_onnx_backend.py

- test/test_tensor.py
- tinygrad/lazy.py
- tinygrad/ops.py
- tinygrad/runtime/lib.py
- tinygrad/tensor.py
- new `LazyBuffer.fromCPU` method to create from `ndarray` + changing the `__init__` method to have optional `LazyOp`/`RawBuffer`
- Add `int32` support for `RawMallocBuffer`
> Eliminate LoadOps.FROMCPU

- .github/workflows/test.yml
- README.md
- docs/abstractions.py
- docs/adding_new_accelerators.md
After https://github.com/geohot/tinygrad/pull/920, the docs were broken, by still using the `FROMCPU` LoadOp, updated and added to ci
> Update broken `docs/abstractions.py` for changed ops, and add to CI

- extra/onnx.py
Fixes `test_softmax_default_axis_cpu` by correctly choosing the new Softmax implementation for onnx_model_version 13.
> Use correct onnx op version

- extra/onnx.py
Before
=== 286 failed, 538 passed, 1810 skipped, 2 warnings in 31.25s ====
After
=== 284 failed, 540 passed, 1810 skipped, 2 warnings in 31.56s ====
> fix test_pow_type - autocasting for Pow with inputs of diff type

- examples/stable_diffusion.py
- tinygrad/lazy.py
Disk tensor bug on windows, when parsing the device string the split does not limit to 1. Since window path includes a ":" this results in the disk tensor only getting the drive letter as the path. Limiting the split to 1 passes the full path to file to disk tensor.
Closes (#927)
> [bug fix] limit split to 1 due to windows path containing :

- docs/quickstart.md
Updating broken link in `docs/quickstart.md` from `/tests` to `/test`.
> Replaced broken link to /tests with /test

- extra/onnx.py
- extra/onnx_ops.py
- test/external/external_test_onnx_backend.py
- tinygrad/helpers.py
- tinygrad/tensor.py
Resolved some issues with Slice/Shape/Size that were causing some tests to fail.
Made some changes to onnx debugging to help track models that use multiple ops. 
Increased the priority of float in dtypes to match torch when adding float + int64
Before - 283 failed, 541 passed, 1810 skipped, 2 warnings in 14.55s
After - 258 failed, 566 passed, 1810 skipped, 2 warnings in 14.10s
> Onnx slice fixups 

- examples/llama.py
- examples/stable_diffusion.py
- extra/onnx_ops.py
- test/external/external_test_onnx_backend.py
- test/external/external_test_opt.py
- test/test_ops.py
- tinygrad/tensor.py
Adds support for 16 more onnx ops. Also replaced numpy.triu usage in llama and stable diffusion. 
Might conflict with #935, will update this pr if it gets merged first
Closes #929
> Adds tril & triu support 

- tinygrad/runtime/ops_torch.py
- tinygrad/tensor.py
Maintain input tensor dtypes on CMPEQ op for pytorch and in the tri functions
> maintain input tensor dtype

- tinygrad/shape/shapetracker.py
Using LLaMa for benchmark, `python3 -O` to disable asserts as some of them are expensive and we don't want to sacrifice readability by optimizing them
```
GPU=1 DEBUG=0 OPTLOCAL=2 python3 -O examples/llama.py --prompt "Hello." --count 10 --temperature 0 --timing --profile
```
Aggregating by time spent per file
Before:
```
lazy.py: 0.9459 seconds
shapetracker.py: 0.8728 seconds
tensor.py: 0.8376 seconds
ops.py: 0.2657 seconds
symbolic.py: 0.1064 seconds
```
After:
```
lazy.py: 0.9416 seconds
tensor.py: 0.8587 seconds
shapetracker.py: 0.4083 seconds
ops.py: 0.3439 seconds
symbolic.py: 0.1100 seconds
```
Saving 0.47s on `shapetracker.py`
> Shapetracker optimizations

- test/test_dtype.py
- tinygrad/codegen/cstyle.py
- tinygrad/codegen/llvmir.py
- tinygrad/helpers.py
- tinygrad/runtime/lib.py
- tinygrad/runtime/ops_gpu.py
- tinygrad/runtime/ops_metal.py
- tinygrad/runtime/ops_torch.py
- tinygrad/tensor.py
Adds float64 support to the different runtimes, also included an excluded field on dtypes for unsupported platforms
From my testing float64 is not supported on metal and OpenCL on M2 Mac. OpenCL float64 is fine on my windows machine although this is an optional feature and ideally should check the OpenCL extensions for it.
Also brings the onnx stat line to:
190 failed, 650 passed, 1794 skipped, 2 warnings in 14.73s
Tested on:
- CPU
- GPU
- CUDA
- LLVM
- CLANG
Closes #891
> F64 support

- extra/helpers.py
_early_exec_process is a local function that is defined whiting the scope of another function, should be global.
also :
* replaced while 1 by while True
* moved imports to top.
this is the error example when testing GPU Backend.
https://github.com/geohot/tinygrad/issues/980
> FIX: Can't pickle local object

- tinygrad/runtime/ops_clang.py
addressing #981 
- split clang cflags, dynlib extension, and function export decorator by platform
- removed clang-rt from msvc linker args based on comment, added msvc dllexport decorator for kernel function
- retained darwin cflags from the linux config as i am not setup to verify correctness (assuming clang rt worked as expected on darwin)
tested on: win10, arch
note: these cflags assume the clang in PATH is set to target the host machine by default, some additional configuration would allow cross compilation
> clang rt for msvc

- extra/gemm/tf_gemm.py
I was running into extremely poor performance training with TensorFlow on my AMD card, which led me to this repository.  I was curious how TF stacked up compared to tinygrad, and I figured this script might be useful to others as well.
It's modelled closely after the existing torch benchmark script but just adapted slightly for tensorflow.
Here are my results for `tf_gemm.py` on 7900 XTX with ROCm 5.5:
```
65536    107.37 us, would be    312.52 GFLOPS  256x 256x 256 matmul in <dtype: 'float16'>
262144    105.39 us, would be   2546.97 GFLOPS  512x 512x 512 matmul in <dtype: 'float16'>
1048576    171.60 us, would be  12514.40 GFLOPS 1024x1024x1024 matmul in <dtype: 'float16'>
4194304    316.75 us, would be  54237.60 GFLOPS 2048x2048x2048 matmul in <dtype: 'float16'>
16777216   1360.75 us, …
```
> Add tensorflow GEMM benchmark script

- extra/hip_wrapper.py
- tinygrad/jit.py
- tinygrad/lazy.py
- tinygrad/runtime/ops_hip.py
Reply on PyHIP, a thin python wrapper for libamdhip64.so, to access ROCm HIP runtime API.
[https://github.com/jatinx/PyHIP](https://github.com/jatinx/PyHIP)
PYTHONPATH=/path/to/PyHIP HIP=1 python3 examples/llama.py
Pytorch was running on CPU in this case.
Attempted running pytorch on GPU but failed due to this issue:
[https://discord.com/channels/1068976834382925865/1083520343169319042/1097708353536397372](https://discord.com/channels/1068976834382925865/1083520343169319042/1097708353536397372)
```
nanami@nanami-ai:~/tinygrad$ HIP=1 OPTLOCAL=1 JIT=1 python3.10 test/test_speed_v_torch.py
add                               1x   1    0.00 ms (    0.00 GFLOPS     0.00 GB/s) in torch,    0.17 ms (    0.00 GFLOPS     0.00 GB/s) in tinygrad,   44.55x slower    0.00 MOPS    0.00 MB
add …
```
> HIP backend

- examples/yolov8.py
Accessing `sys[1]` cause `TypeError: 'module' object is not subscriptable`.
> Fixed argument passing in example yolov8

- docs/env_vars.md
- tinygrad/runtime/ops_gpu.py
* Add some previously undocumented environment variables from `ops_gpu.py` to `env_vars.md`
* Update debug print for OpenCL to print the devices that will be used post-filtering with `CL_EXCLUDE`
* Print more detailed device info rather than raw Python objects with addresses etc.
* Remove a couple unused or superfluous variables and assignments
* Use `fromimport` shorthand to shave off a couple precious LOC
* Couple small whitespace changes to clean things up
The main motivation for this was to ease setup for users like me that have to filter out an iGPU from their OpenCL device list.  Trying to launch kernels on the iGPU causes the Python script to hang at best and my computer to blackscreen at worst.
I felt that printing out the _actual_ devices that are used post-filtering made more …
> Minor improvements + cleanup to `ops_gpu.py`

- .github/workflows/test.yml
- extra/utils.py
- test/extra/test_utils.py
- test/models/test_onnx.py
- test/test_nn.py
- test/unit/test_disk_tensor.py
- tinygrad/helpers.py
Main changes were converting uses of '/tmp' to using a helper function that creates os specific paths with temp directory. Only had to skip one test(test_conv_transpose2d) because it was running out of memory in the runner.
> Windows & Ubuntu CLANG CI support

- test/external/external_test_image.py
- tinygrad/codegen/assembly_rdna.py
* Adds support for casting from `bool` -> `float32`.  Seems like a very common operation that is required in many places.
* Fix bool register definition for vector operations
* Use `vcc_lo` instead of `vcc` which seems to be required since it's configured to use wavefront_size=32
* Add vector support for some places that were scalar only in register definition and comparison ops
* Fix some issues in what seems to be defunct `external_test_image.py`
* Some tests still don't pass for other reasons, but it at least runs now and one broken test is now fixed
* Refactor RDNA3 assembler register definition
* Unify multi-registor code between dtypes and combine with single-register allocation since they're all untyped registers at the end of the day
----
My main goal starting out today was to …
> Add RDNA3 assembler `UOps.CAST` partial support + other fixes/improvements

- tinygrad/ops.py
When a kernel takes a very short amount of time, calculating GFLOPS does a division by zero when DEBUG is greater than or equal to 2. This is fixed by checking when the estimated time is 0 and if it is, setting it to a very small number
> fixed division by zero for fast kernels

- .github/workflows/test.yml
- test/test_dtype.py
- tinygrad/runtime/ops_cuda.py
Opening a new pr, as I couldn't reopen the old one, sorry.
- pycuda.driver.Context - mocked
- cuda - mocked
- no mentions of CUDACPU in the implementation code
- focused on readability
- no pressure on tinygrad to maintain patches / interfaces. All is handled by ocelot now!
Edit:
also fixes tests on cuda due to `half_prekernel` being only includeed if fp16 is used in a kernel.
> cuda ci on cpu

- test/test_ops.py
- tinygrad/tensor.py
Reduced line counts for tensor.dot by 1 while also supporting 1d tensors as input (previously broken). 
Now should work in all the following cases: 
- 1d @ 1d
- 1d @ Nd
- Nd @ 1d
- Nd @ Nd
Also added the corresponding tests. 
Eventually we could reduce duplicated code like: 
```
def dot(self, w:Tensor) -> Tensor:
if (n1:=len(self.shape))*(n2:=len(w.shape)) == 0: raise RuntimeError(f"both arguments to matmul need to be at least 1D, but they are {n1}D and {n2}D")
x = self.reshape(*self.shape[0:-1], *(m1:=[1]*min(n1-1, n2-1, 1)), self.shape[-1])
w = w.reshape(*w.shape[0:-2], *m1, *w.shape[-(m2:=min(n2, 2)):]).transpose(-1, -m2)
return (x*w).sum(-1)
```
Let me know!
> Reduce tensor dot line count and fixed 1d tensor dot

- test/test_optim.py
- tinygrad/nn/optim.py
Passing the same tensor multiple times in the set of learnable params passed to optimizers can result in models completely failing to learn, but no errors are produced.  De-duping the passed tensors avoids the problem.
I ran into this when porting some of my TensorFlow code to work with Tinygrad.  Had a maddening few hours before I finally tracked down the issue.
I also noticed that the `Optimizer.realize()`'s `extra` arg doesn't seem to ever be set when calling it from within the tinygrad project.  Makes sense if it's meant to be a public API, or maybe I missed something, but if not it might be possible to remove that and get rid of some code.
> Dedup params in `Optimizer`

- test/external/external_test_speed_llama.py
Would changing the amount of runs to 10 be okay? I see quite some variation locally.
Changes output from this:
```
using <class 'tinygrad.runtime.ops_gpu.CLCodegen'>
testing llama python run time
built model
assigned empty tensors, doing warmup
codegen         runtime in ms: 301.48, 232.38, 226.40, 242.69, 227.07, 233.93, 263.47, 228.38, 221.30, 219.61
methodcache     runtime in ms: 211.98, 261.42, 216.48, 219.08, 214.98, 205.48, 214.63, 211.68, 267.02, 216.87
profile         runtime in ms: 1340.62, 1154.90, 1118.25, 1090.96, 1188.29, 1103.09, 1149.75, 1176.59, 1108.89, 1205.75
```
To this:
```
using <class 'tinygrad.runtime.ops_gpu.CLCodegen'>
testing llama python run time
built model
assigned empty tensors, doing warmup
codegen        runtime:  234.29ms , runs:   301.52,  212.94, …
```
> refactor: print formatting for llama timing

- test/test_ops.py
- tinygrad/tensor.py
I think there was a tinybug in Tensor.arange() when step != 1? 
```
Previously:
In [5]: torch.arange(5,10,3)
Out[5]: tensor([5, 8])
In [3]: Tensor.arange(10,5,3).numpy()
Out[3]: array([5.], dtype=float32)
after fix:
In [4]: Tensor.arange(10,5,3).numpy()
Out[4]: array([5., 8.], dtype=float32)
```
> Tensor.arange() bug fix

- tinygrad/codegen/assembly.py
Don't emit loop end code for global+local loop in assembly kernel, since this is handled by the GPU runtime.
A recent change broke PTX:
```
$ PTX=1 DEBUG=4 ENABLE_METHOD_CACHE=0 python ./test/test_nn.py TestNN.test_conv2d
***       0.00 GB    0.02 ms op: BinaryOps.MUL        out(float): (64, 16, 7, 7)                 in(2): [(64, 16, 7, 7)] 
*** exec  0.00 GB    0.01 ms op: BinaryOps.ADD        out(float): (64, 16, 7, 7)                 in(2): [(64, 16, 7, 7)] 
float4 merging axis : [(2, 2, 0, 4)]
0 buffer<50176, dtypes.float>                     [View((392, 32, 4), (128, 4, 1), 0, None)]
1 buffer<1, dtypes.float>                         [View((392, 32, 4), (0, 0, 0), 0, None)]
2 buffer<50176, dtypes.float>                     [View((392, 32, 4), (128, 4, 1), 0, None)]
3 buffer<1, …
```
> do not emit loop end code for global+local loops in assembly kernel

- tinygrad/tensor.py
It's more concise, idiomatic and faster:
```
In [8]: %timeit [1 for _ in range(100)]
2.12 µs ± 26.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
In [9]: %timeit [1] * 100
515 ns ± 5.23 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```
> [tensor][perf] Replace list comprehension with *.

- extra/onnx_ops.py
Fixes error: TypeError: Gemm() got an unexpected keyword argument 'broadcast', from external_test_onnx_backend. Clears 3 failing tests
Referred to http://www.xavierdupre.fr/app/mlprodict/helpsphinx/onnxops/onnx__Gemm.html#gemm-13 for detail on the use case of the attribute
> Handle broadcast flag on gemm

- docs/abstractions.py
Here's the error message we were getting on Windows when we tried to run abstractions.py: ![error message](https://cdn.discordapp.com/attachments/1068976834928193609/1125288178631319552/image.png)
We add the dll export in to fix this.
> Small fix to abstractions.py so it runs errorless on Windows

- .pylintrc
- extra/onnx.py
- models/retinanet.py
- tinygrad/codegen/linearizer.py
- tinygrad/helpers.py
- tinygrad/lazy.py
- tinygrad/shape/shapetracker.py
- tinygrad/shape/symbolic.py
- tinygrad/tensor.py
Small optimization for best/average case for `any` and `all` uses.  Be lazy when we can.
```shell
In [2]: %timeit any([x for x in range(int(1e6))])
18.9 ms ± 284 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
In [3]: %timeit any(x for x in range(int(1e6)))
296 ns ± 3.39 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
In [4]: %timeit all([False for _ in range(int(1e6))])
16.2 ms ± 354 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
In [5]: %timeit all(False for _ in range(int(1e6)))
279 ns ± 0.332 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```
> Use generators instead of lists in `any`s and `all`s

- datasets/coco.py
Fix issue when trying to eval mrcnn:
```
% METAL=1 MODEL=mrcnn python3 examples/mlperf/model_eval.py
eval mrcnn
File "/Users/dhipke/git/tinygrad/examples/mlperf/model_eval.py", line 244, in <module>
globals()[nm]()
File "/Users/dhipke/git/tinygrad/examples/mlperf/model_eval.py", line 201, in eval_mrcnn
from datasets.coco import BASEDIR, images, convert_prediction_to_coco_bbox, convert_prediction_to_coco_mask, accumulate_predictions_for_coco, evaluate_predictions_on_coco, iterate
File "/Users/dhipke/git/tinygrad/datasets/coco.py", line 22, in <module>
download_file('http://images.cocodataset.org/zips/val2017.zip',fn)
File "/Users/dhipke/git/tinygrad/extra/utils.py", line 42, in download_file
with tempfile.NamedTemporaryFile(dir=pathlib.Path(fp).parent, …
```
> Create COCO data directory if it doesn't exist.

- test/test_ops.py
- tinygrad/mlops.py
- tinygrad/tensor.py
Sigmoid backward is broken for most of negative numbers, and this also breaks 
tanh, gelu and quick_gelu 
for large negatives, in Exp backward, we get 
-0. in grad_output, inf in self.ret, MUL of which gives NaN as grad
Adding mlop for sigmoid solves the issue, but there is an oppurtunity for fusion here
> Broken Sigmoid backward: Add test and mlop for Sigmoid

- datasets/imagenet_download.py
- extra/helpers.py
- setup.py
- test/extra/test_helpers.py
Update `cross_process` to use `cloudpickle`, as it fails on Python 3.9+:
Example:
```
% METAL=1 MODEL=resnet python3 examples/mlperf/model_eval.py
eval resnet
File "/Users/dhipke/git/tinygrad/examples/mlperf/model_eval.py", line 244, in <module>
globals()[nm]()
File "/Users/dhipke/git/tinygrad/examples/mlperf/model_eval.py", line 35, in eval_resnet
x,ny = next(iterator)
File "/Users/dhipke/git/tinygrad/extra/helpers.py", line 45, in cross_process
p.start()
File "/opt/homebrew/anaconda3/lib/python3.10/multiprocessing/process.py", line 121, in start
self._popen = self._Popen(self)
File "/opt/homebrew/anaconda3/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
return _default_context.get_context().Process._Popen(process_obj)
File …
```
> Make cross_process use cloudpickle

- tinygrad/tensor.py
Speeds up operations that do not require gradients by a bit since it no longer saves parents, and also speeds up backward pass since there is a less expensive check for if backward should be run.
> Don't save parents unless needed

- test/external/external_test_opt.py
- tinygrad/lazy.py
New test case:
```
def test_fold_expand_reduce(self):
with CLCache(1):
a = Tensor.randn(16, 1)
a = a.expand((16, 16)).sum(-1)
a.realize()
assert len(GlobalCounters.cache) == 1, "optimizer didn't fold expand/reduce"
```
This generates two kernels on master, including a reduction kernel
```
***    0 E_4_4                         arg   2 sz []                 [4]          OPs      0M/   0.00G  mem  0.00 GB tm     14.71us/     0.01ms (    0.00 GFLOPS,    0.01 GB/s)
***    1 r_16_16                       arg   2 sz [16]               [16]         OPs      0M/   0.00G  mem  0.00 GB tm     10.75us/     0.03ms (    0.02 GFLOPS,    0.01 GB/s)
```
With these changes we have:
```
***    0 E_4_4                         arg   2 sz []                 [4]          OPs      0M/   0.00G  mem  0.00 GB tm …
```
> Fold expand preceding reduce if the reduction is on the same axis as the expansion

- examples/transformer.py
- tinygrad/runtime/ops_cuda.py
**Problem Statement**
Running `examples/transformer.py` using CUDA crashes at the evaluation stage, error:
```
loss 0.38 accuracy 0.86: 100%|████████████████████████████████████████████████████████████████| 50/50 [00:04<00:00, 11.68it/s]
0%|                                                                                                  | 0/16 [00:00<?, ?it/s]
File "/home/bdn/Desktop/Modules/tinygrad/examples/transformer.py", line 32, in <module>
acc, Y_test_preds = evaluate(model, X_test, Y_test, num_classes=10, return_predict=True)
File "/home/bdn/Desktop/Modules/tinygrad/extra/training.py", line 60, in evaluate
acc, Y_test_pred = numpy_eval(Y_test, num_classes)
File "/home/bdn/Desktop/Modules/tinygrad/extra/training.py", line 53, in numpy_eval
out = …
```
> Fix evaluation stage in examples/transformer.py when using CUDA

- tinygrad/runtime/ops_cuda.py
`DEBUG=6 CUDA=1 pytest -s -v -n=auto test/test_ops.py`
test/test_ops.py::TestOps::test_add_number nvdisasm fatal   : Object file /tmp/cubin is not readable
Also bring imports to a single line, same as in ops_clang
> ops_cuda: fix race condition on cubin file read when testing with -n>1

- extra/utils.py
- test/extra/test_utils.py
Did this because some examples that use `download_file` expect a weights dir, this way the user doesn't have to manually create it. 
- also removed duplicate import `os`
> Fix: auto create parent dir when downloading file

- test/test_lazybuffer.py
- tinygrad/lazy.py
The shape tracker in LazyBuffer.fromCPU is initialized with only the input array's shape, meaning it will always claim to be contiguous, including when the input array is not. This was the actual cause of the bug in #1150, as `x` already should already have been made contiguous [1].
This PR proposes a "fix" by simply making a copy of the array, which allocates a new contiguous buffer and thereby corrects the shape tracker mismatch. The downside is that it changes the previous behaviour of sharing/reusing the buffer.
If we wish to keep supporting buffer sharing, it should also be possible to construct a correct shape tracker by passing the array's shape, strides, and base.
[1]: Specifically the problem is that `_realize_contiguous` avoids emitting `UnaryOps.NOOP` (soon to be …
> Fix ShapeTracker mismatch in LazyBuffer.fromCPU

- .github/workflows/test.yml
Something is very wrong with CI right now, the queue is pretty much completely backed up.
This should help a bit by canceling older runs when there are new commits.
> Cancel previous workflow runs on new commits

- .github/workflows/test.yml
Reverts tinygrad/tinygrad#1184
Going to revert this, it's annoying to see the Xs when there's no bugs, like on #1193.
It makes debugging harder, and hopefully with the timeout it's fine.
> Revert "Cancel previous workflow runs on new commits"

- test/test_tensor.py
- tinygrad/tensor.py
Tensor.randn can return ±inf in the rare case of our RNG returning a 0. The cause is the log function in the Box-Muller transform we use for randn.
PyTorch also uses Box-Muller, but avoid this issue by mapping the RNG value from `[0, 1) -> (0, 1]`. This PR implements that fix. [[src]](https://github.com/pytorch/pytorch/blob/91dcc3b2726aa33ca9a30dfb8d165d8ec7b7bba3/aten/src/ATen/native/cpu/DistributionTemplates.h#L142)
---
Since zeros values are extremely rare, it's a bit of a pain to test. I mined a seed that would reproduce the bug on the current implementation, but I didn't add it because it seems too specific. Let me know if you want me to add it, or if you have a better test in mind.
```python
def test_randn_isnt_inf(self):
Tensor.manual_seed(195866)
a = Tensor.randn(128)
assert not …
```
> Fix bug where Tensor.randn returns inf

- tinygrad/codegen/linearizer.py
fixes: #1198 
remaining:
example:
```python
from tinygrad.tensor import Tensor
a, b = Tensor(2), Tensor(5)
((a+b) * (a+b)).realize()
```
codegen before change:
```c
void E_(float* restrict data0) {
float val1_0 = 2.0f;
float val2_0 = 5.0f;
float alu0 = (val1_0+val2_0);
float alu1 = (val1_0+val2_0);
float alu2 = (alu0*alu1);
data0[0] = alu2;
/* global+local */
}
```
after change:
```c
void E_(float* restrict data0) {
float val1_0 = 2.0f;
float val2_0 = 5.0f;
float alu0 = (val1_0+val2_0);
float alu1 = (alu0*alu0);
data0[0] = alu1;
/* global+local */
}
```
> implement common subexpression elimination

- tinygrad/shape/shapetracker.py
Makes `View` into `NamedTuple` s
Part 1 of https://github.com/geohot/tinygrad/pull/1044 that does not require to modify all the tests using ShapeTracker.
Pure refactor.
> [READY] perf: view as named tuples

- tinygrad/runtime/ops_cpu.py
local testing (test/test_net_speed.py) yields:
```
forward pass:  185.863 ms, 7.83x off baseline 23.746 ms
backward pass: 820.215 ms, 20.74x off baseline 39.543 ms
forward pass:  157.368 ms, 6.85x off baseline 22.983 ms
backward pass: 209.347 ms, 5.66x off baseline 36.967 ms
```
central tendency for `optimize=True` is around 8x and 20x. `optimize=False` is around 7.5x and 5.5x. I could compile an n=1000 analysis if that would be helpful in analyzing the change.
Reading:
-  https://numpy.org/doc/stable/reference/generated/numpy.einsum.html
-  https://stackoverflow.com/questions/49265044/numpy-einsum-path-differences-and-the-optimize-argument
> [perf] use optimize=True in np.einsum

- test/test_lazybuffer.py
- tinygrad/lazy.py
In addition to div, any ops that will generate non-zero outputs from zero inputs need to be guarded.
Closes #1221
> Fix LazyBuffer SHUFFLE_PAD_OPS to prevent invalid pad movement

- .github/workflows/test.yml
CI: don't install the recommended packages for the GPU test, saves a GB of installs and a bit more than a minute.
Before
Install dependencies: 2m 37s
```
Need to get 2054 MB of archives.
After this operation, 5981 MB of additional disk space will be used.
```
After
Install dependencies: 1m 12s
```
Need to get 1491 MB of archives.
After this operation, 4633 MB of additional disk space will be used.
```
> [READY] ci: don't install recommended packages for GPU

- test/test_nn.py
Not really sure if this is necessary since it's the same implementation as Conv2d, but still good to compare to torch I think.
> Added test for `nn.Conv1d`

- docs/abstractions.py
- docs/adding_new_accelerators.md
- test/test_ops.py
- tinygrad/codegen/assembly_ptx.py
- tinygrad/codegen/assembly_rdna.py
- tinygrad/codegen/cstyle.py
- tinygrad/codegen/linearizer.py
- tinygrad/codegen/llvmir.py
- tinygrad/codegen/wgsl.py
- tinygrad/graph.py
- tinygrad/lazy.py
- tinygrad/mlops.py
- tinygrad/ops.py
- tinygrad/runtime/ops_cpu.py
- tinygrad/runtime/ops_torch.py
- tinygrad/tensor.py
This addresses #1154 and fixes #942. I've only added the op to the tested backends, but adding it to other ones should be pretty straightforward.
Maybe it makes sense to automatically fall back to the current implementation of WHERE in cases where the backend doesn't support that op? I guess such a logic could be added in `ops.py`.
> Add WHERE ternary (or trinary?) op

- test/test_ops.py
- tinygrad/ops.py
Related #1263,
I have changed the assertion condition but not sure if it against the logic or just overlooked.
Transposing a tensor throws assertion if there is WHERE Ops in the LB.
> Fix: AssertionError Transpose/Permute when WHERE Op in LB

- test/test_ops.py
- tinygrad/tensor.py
Based on 
`# NOTE: using slice is discouraged and things should migrate to pad and shrink`
Just updated the "Tensor.eye()" function replacing slice with pad/shrink.
I do not know if I should continue cleanup code.
Maybe bit faster but not sure
> Slice migrated in Eye op

- test/external/external_test_opt.py
- tinygrad/lazy.py
This PR is for matching PyTorch speed on the sum reduction on Metal (https://github.com/tinygrad/tinygrad/issues/1167)
When tested on an M1 Max, we get the following results:
| test | Original | This PR |
| --- | --- | --- |
| sum 1024 x 1024 | 2.05x slower | 0.90x faster |
| sum 2048 x 2048 | 2.65x slower | 0.87x faster |
| sum 4096 x 4096 | 10.90x slower | 0.96x faster |
| sum 8192 x 8192 | 21.78x slower | 0.88x faster |
| sum 16384 x 16384 | 36.65x slower | 0.95x faster |
| cube_sum 256 x 256 x 256 | 11.62x slower | 0.91x faster |
| line_sum 4194304 | 2.85x slower | 0.98x faster |
| line_sum 16777216 | 10.29x slower | 0.96x faster |
| max 4096 x 4096 | 16.21x slower | 0.95x faster |
<details>
<summary>Raw Results</summary>
NEW RESULTS
```
sum                             1024x 1024 …
```
> Match Torch speed for sum reduction on M1

- examples/llama.py
Add back support for LLaMA 13B and add 30B and 65B.  Closes #1254.
Wasn't able to test 65B due to memory constraints but here are the results with 13B and 30B on a MBP16 M2 Max 96GB:
```
using METAL backend
using 13B model
ram used: 26.03 GB, freqs_cis                                         : 100%|█████████████████████████████████████████████████████████████████████████████████████████| 364/364 [00:06<00:00, 58.91it/s]
loaded weights in 6185.82 ms, 26.03 GB loaded at 4.21 GB/s
Hello.
ran model in 596.72 ms
sync in 31.25 ms
I
ran model in 154.41 ms
sync in 2.73 ms
am
ran model in 148.00 ms
sync in 2.73 ms
a
ran model in 140.58 ms
sync in 3.20 ms
ran model in 142.85 ms
sync in 2.65 ms
2
ran model in 149.57 ms
sync in 2.81 ms
0
ran model in 143.11 ms
sync in 2.68 ms
year
ran model in 142.81 …
```
> Fix llama.py to load and concatenate 13B, 30B, and 65B models

- docs/abstractions.py
- test/test_tensor.py
- tinygrad/tensor.py
Reverts tinygrad/tinygrad#1227
This change always make size 1 tensor a constant, which breaks #1273. Passing a size 1 tensor in JIT as input does not work because JIT only updates buffers.
I recommend reverting this now and find a better way to spec constant tensors.
> Revert "Fix constant folding for Tensor([3])"

- test/test_jit.py
Because the #1274 revert, this test passes now.
> Enable JIT test for size 1 tensor

- tinygrad/runtime/ops_cuda.py
adds a user defined function to convert float4 to half4 
Before
```bash
CUDA=1 python test/test_dtype.py TestHalfDtype
FAILED (failures=1, errors=9)
```
After 
```bash
CUDA=1 python test/test_dtype.py TestHalfDtype
FAILED (failures=1, errors=2)
```
> fixes cuda error when trying to convert float4 -> half4

- tinygrad/codegen/wgsl.py
Currently WGSL will fail to compile due to a shader error in the presence of NaN const (renders as "nanf").
For reference on this approach see: https://github.com/gpuweb/gpuweb/issues/3749
> Fix WSGL to render NaN and prevent shader compile error

- examples/webgpu/index.html
* demo somewhy doesn't work on my device and throws error "Error: GPUPipelineError: [Invalid ShaderModule] is invalid" inside setupNet func
* because of that, JS halts the execution of the rest of the code below and on the screen, we see "loading..." forever
* added try catch here to communicate about the error in a proper way
<details>
<summary>web page screenshot</summary>
</details>
> fix: prevent infinite "loading..." state at webgpu demo page

- examples/efficientnet.py
- extra/utils.py
- test/extra/test_utils.py
you cannot currently use relative file paths with fetch
This shows up in the yolov8 example:
```
desktop>python3 tinygrad/examples/yolov8.py ./TestImages/Abyssinian_1.jpg
No variant given, so choosing 'n' as the default. Yolov8 has different variants, you can choose from ['n', 's', 'm', 'l', 'x']
running inference for YOLO version n
File "tinygrad/examples/yolov8.py", line 405, in <module>
image_location = [np.frombuffer(io.BytesIO(fetch(img_path)).read(), np.uint8)]
File "/home/bigfoot/dev/tinyfork/tinygrad/extra/utils.py", line 22, in fetch
download_file(url, fp, skip_if_exists=not getenv("NOCACHE"))
File "/home/bigfoot/dev/tinyfork/tinygrad/extra/utils.py", line 39, in download_file
r = requests.get(url, stream=True)
File …
```
> change fetch to allow for local file selection

- examples/mnist_gan.py
I was looking at the mnist_gan example and noticed the output images lacked saturation, resulting in a subdued and low-contrast appearance. After a bit of investigation I think the primary cause of this is the lack of bias terms within the networks. I tried adding these for example:
```python
self.b1 = Tensor.zeros(256)
.
.
.
x = x.dot(self.L1).add(self.b1).leakyrelu(0.2)
```
This worked very well and produced the following final result:
I realise that bias terms are often left out of GAN architecture for simplicity, and on further investigation they all converged to 0, except for in the first layer of the discriminator. Therefore it was possible to simply add a hard coded const bias to the first discriminator layer.
The rationale for this change is that the generator is zero cantered, …
> Fix discriminator balancing in mnist_gan example

- tinygrad/runtime/ops_hip.py
Makes HIP pass all test_ops and test_speed_v_torch, also lets HIP train cifar which was the main point of this (gets *slightly* higher FLOPS than CL actually).
Really need HIP in CI, but #1048 seems somewhat stalled.
> HIP backend fixes

- examples/llama.py
- test/external/external_llama_eval.py
- tinygrad/state.py
Here's a summary of the memory and performance on METAL on my M2 Max with and without the `--quantize` option:
| Model Size | Loading Time | RAM | Fastest Ran Model Time |
| --- | --- | --- | --- | 
| 7B (fp16) | 1786.25 ms | 13.48GB | 105.30ms |
| 7B (int8) | 2608.36 ms | 6.87GB | 128.51 ms |
| 13B (fp16) | 6218.58 ms | 26.03 GB | 129.24 ms |
| 13B (int8) | 5576.42 ms | 13.19 GB | 169.25 ms |
| 30B (fp16) | 22970.66 ms | 65.06 GB | 1534.54 ms |
| 30B (int8) | 17363.83 ms | 32.75 GB | 258.79 ms | 
| 65B (fp16) | N/A | N/A | N/A |
| 65B (int8) | 40315.09 ms | 65.56 GB | 1551.57 ms | 
The performance of 30B (int8) is quite a bit better than 30B (fp16), perhaps due to memory bandwidth limitations.
> Add option in llama.py to quantize weights to int8 at runtime

- test/test_ops.py
- test/test_speed_v_torch.py
- tinygrad/tensor.py
Previous implementation uses Tensor.slice which uses pad + shrink. Previous implementation used slice instead of pad so I converted the slice to pad in new one. We do not need shrink in the cat operation.
Hope it is not Chesterton's Fence.
Just a little bit optimization effect on llama but speed is volatile so practically less function call.
This branch
```
using <class 'tinygrad.runtime.ops_metal.MetalCodegen'>
testing llama python run time
built model
assigned empty tensors, doing warmup
codegen         mean runtime:  147.83ms, runs:   162.49,  170.76,  143.67,  145.73,  141.18,  143.99,  141.86,  142.29,  143.80,  142.52
methodcache     mean runtime:  135.79ms, runs:   158.25,  132.46,  133.65,  134.84,  133.17,  133.09,  132.98,  133.04,  133.33,  133.12
profile         mean runtime: …
```
> Small Tensor.cat optimization and reformating

- tinygrad/runtime/ops_metal.py
This PR changes how we handle command buffers in the Metal runtime.
Previously, we waited for each command buffer to finish before queuing more work, which according to Apple's [Tuning Hints](https://developer.apple.com/documentation/metalperformanceshaders/tuning_hints) could introduce delays of up to 2.5ms. 
Now, we've implemented a dispatch group approach. We enter the group when we create a new command buffer and leave when it's done. 
This modification allows the `synchronize` method to wait on the group instead of individual buffers, which should enhance both the speed and stability of the Metal runtime.
> Improve Metal runtime command buffer handling

- .github/workflows/test.yml
Fix #1366. Root cause was that windows env was not set up correctly. It needs to be a powershell command writing to `$env.GITHUB_ENV` (https://stackoverflow.com/a/65110357). windows CI was using `CPU`. It was fine before #1252  because ubuntu was covering it. Also this test is the slowest now and it takes 8 minutes.
I changed the os to `ubuntu-latest` and added a guardrail check. Verified that guardrail works with windows [link](https://github.com/chenyuxyz/tinygrad/actions/runs/5695168286/job/15437766791), and the intentionally fail test indeed failed with clang+ubuntu [link](https://github.com/chenyuxyz/tinygrad/actions/runs/5695199334).
> use ubuntu for clang ci test

- test/unit/test_shapetracker.py
- tinygrad/shape/shapetracker.py
Noticed that the upper bound was off by one. Essentially the same code also appears on line 199, but there it does correctly include the -1.
> Fix off by one error in View.expr_node

- test/external/external_test_opt.py
- test/unit/test_shapetracker.py
- tinygrad/shape/shapetracker.py
can remove the `%` check and fold both `prod`s into one. I checked the initial refactor #650 that introduced these, and I believe it could have been this version.
Also added some unit tests to document the current 1s grouping behavior. Should be able to group them into single axis but when I tried, at some point I passed all tests except the openpilot one and I felt it's not as trivial.
> simplify get_contraction

- test/unit/test_shapetracker.py
- tinygrad/shape/shapetracker.py
to_shape_strides wasn't merging two dimensions if there was a dimension of size 1 in between them. 
For example: `ShapeTracker((10, 1, 10))` now corectly produces shape strides `((100, 1),)` instead of `((10, 10), (10, 1))`.
Also simplified the conditional in on line 17 and added the tests that caught this, expanding on #1363
> fix to_shape_strides

- .editorconfig
- .github/workflows/editorconfig.yml
- .github/workflows/test.yml
- examples/webgpu/compile_webgpu.py
- examples/webgpu/index.html
- extra/accel/ane/2_compile/compile.mm
- extra/accel/ane/3_run/h11ane.h
- extra/accel/ane/README.md
- extra/accel/ane/README.old
- extra/accel/ane/aneregs
- extra/accel/ane/lib/ane.py
- extra/datasets/coco.py
- extra/gemm/amx.py
- extra/gemm/gemm.c
- extra/gemm/gemm.py
- extra/intel/go.sh
- test/external/external_test_image.py
- test/external/external_test_opt.py
- test/external/external_test_yolov8.py
- test/external/graph_batchnorm.py
- test/extra/test_utils.py
- test/test_webgpu.js
- tinygrad/runtime/ops_metal.py
This PR enables more options in the editorconfig file:
- end of line = LF (unix)
- ~insert final newline = true~
- trim trailing whitespace = true
- charset = utf-8
I have not reformatted any existing files. The changes will be slowly applied by people editing the files with editors that support editorconfig.
Also there is no check (via editorconfig-checker) in the CI right now.
> update editorconfig, enforce via CI

- test/test_randomness.py
- test/test_tensor.py
- tinygrad/tensor.py
Could use this in #1371  to implement the contentvec from  https://github.com/auspicious3000/contentvec .
**Tensor::normal:** normal dist can be computed from standard dist by factoring in std and adding mean. See notes in: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html
**Tensor::kaiman_normal:** analog to Tensor::kaiman_uniform.
Includes tests.
Also any reason why Tensor::uniform default args are low=-1.0 and high=1.0 and torch::init::uniform are a=0 and b=1? (https://pytorch.org/docs/stable/nn.init.html#torch.nn.init.uniform_ )
> rng hlops: add normal and kaiming_normal

- extra/gemm/hip_matmul.py
Before:
```
(venv) chaos@tiny3:~/tinygrad$ KX=2 KY=2 N=2048 python extra/gemm/hip_matmul.py 
4194304    443.88 us, would be  38703.69 GFLOPS matmul, 113.39 GB/s
```
After:
```
(venv) chaos@tiny3:~/tinygrad$ KX=2 KY=2 N=2048 python extra/gemm/hip_matmul.py
4194304    289.60 us, would be  59322.55 GFLOPS matmul, 173.80 GB/s
```
XD
> syncthreads before wmma

- test/test_ops.py
- tinygrad/tensor.py
Const padding only supported in .pad and not .pad2d. As pad2d uses slice, implementation needed to be changed in either pad2d or slice. If not changed, it will be duplicate code.
Note: inf or -inf is not supported, I believe they require use of .where
> Re-open constant pad support to Tensor.pad

- test/test_symbolic_shapetracker.py
- tinygrad/shape/shapetracker.py
- tinygrad/shape/symbolic.py
Part of #1353 
reshape from int shape to shape with a variable writes the variable value to `Variable.val`. We don't need the value to generate the kernel code, but we need it to run the generated program.
> reshape to register variable value

- tinygrad/runtime/ops_gpu.py
splitting #963 into smaller prs.
Before:
```
gpu:0, 0.01195 s, 2.80894 GB/s, 2048x2048x2, 33554.43200 KB
gpu:0, 0.01724 s, 3.89176 GB/s, 2048x2048x4, 67108.86400 KB
gpu:0, 0.03089 s, 4.34465 GB/s, 2048x2048x8, 134217.72800 KB
gpu:0, 0.05452 s, 4.92342 GB/s, 2048x2048x16, 268435.45600 KB
gpu:0, 0.09634 s, 5.57272 GB/s, 2048x2048x32, 536870.91200 KB
```
After:
```
gpu:0, 0.00438 s, 7.65615 GB/s, 2048x2048x2, 33554.43200 KB
gpu:0, 0.00800 s, 8.38438 GB/s, 2048x2048x4, 67108.86400 KB
gpu:0, 0.01542 s, 8.70673 GB/s, 2048x2048x8, 134217.72800 KB
gpu:0, 0.03976 s, 6.75204 GB/s, 2048x2048x16, 268435.45600 KB
gpu:0, 0.08238 s, 6.51688 GB/s, 2048x2048x32, 536870.91200 KB
```
> use host ptr for speed on copyouts

- docs/env_vars.md
- docs/quickstart.md
- test/test_helpers.py
- tinygrad/helpers.py
The various updates to documentation and code outside `helper.py` is just some suggestions. I can remove all of them if wanted.
(I initially pitched this in #1331.)
> Timing and Context can now be used as decorators

- test/test_ops.py
- tinygrad/tensor.py
This PR, refactors pad2d and slice, eventually slice and pad2d does the same thing both can shrink and pad with zeros but they do it with different formatted input. So I have merged them into one in pad2d and used it in slice.
As a result of this PR, pad2d now supports const padding
To sum up, slice and pad2d does the same thing eventually
> Const pad support to pad2d and slice

- test/test_lazybuffer.py
- test/unit/test_symbolic.py
- tinygrad/lazy.py
- tinygrad/shape/shapetracker.py
- tinygrad/shape/symbolic.py
Part of #1353
`LazyBuffer.get_variable_buffers()` returns a map of {symbol: unrealized size 1 buffer of symbol value}. We will need the keys of this dict in codegen, and the values in exec.
Extend the original `Node.vars` to possibly return the `vars` from in `OpNode.b`. The only place that used `vars` was in `real_strides`. We need to keep the version that only returns the vars of `OpNode.a` because `real_strides` construct a set of variables and relies on the assumption that `OpNode.b` will always be `int`.
> LazyBuffer.get_variable_buffers()

- test/test_symbolic_shapetracker.py
- tinygrad/shape/shapetracker.py
- tinygrad/shape/symbolic.py
part of #1353 
Support expand into symbolic shape by doing the bound math for `LtNode(Node, Node)`, which folds it into a `NumNode` if it's always true or always false.
> support symbolic expand

- test/test_symbolic_shapetracker.py
- test/unit/test_symbolic.py
- tinygrad/shape/symbolic.py
Part of #1353, followup on symbolic expand
Add support to implicit expand in `_broadcasted` like `Tensor.rand(3,4).reshape(3, Variable) + 1` by adding `__bool__` to Node. Before this change
```
a = Variable("a", 1, 8)
max(a, 1) == min(a, 1) == a
```
with this change
```
a = Variable("a", 1, 8)
max(a, 1) == a
min(a, 1) == 1
```
so `_broadcasted` can do expand from `1` to `a` correctly.
`max(2, a)` still evaluates to `a`, but I don't think we need to support that for the movementops
> Support implicit expand to symbolic shape in _broadcasted

- examples/efficientnet.py
`out` is already converted to an ndarray before the matplotlib debug comment, which results in an AttributeError when .numpy() is called again.
> efficientnet: Fix output plot debug

- test/test_ops.py
- tinygrad/nn/image.py
- tinygrad/tensor.py
Currently Tensor.dot works even with wrong shapes: mxa @ bxn, when a != b but either one of a or b is 1 (see #1364). 
Added an assert on the shapes to have the same behavior as numpy/torch.
> Add assert for wrong matmul/dot shapes

- tinygrad/codegen/cstyle.py
The `NOUNROLL` option is currently broken. Does it make sense to add a test run of `test/test_ops.py` with `NOUNROLL` enabled to catch this in future?
Also I've noticed that the currently failing Metal tests do pass with `NOUNROLL` enabled. Should we maybe enable these tests and run them like that?
> Fix NOUNROLL

- test/test_lazybuffer.py
- tinygrad/lazy.py
Seems we count children wrong with lazycache. Because of this we got really bad kernels generated with #1387 when one (huge) reduce was merged several times into elementwise.
Measured on hlb_cifar10, efficientnet, sd, real_world_tests - no bad surprises happend, performance is the same.
> correct children count with lazycache

- tinygrad/runtime/ops_cuda.py
#1443 reintroduced #1224 due to:
```python
if self.opts.global_max and self.opts.local_max: self.limit_global_dims(3, self.opts.global_max, self.opts.local_max)
``` 
And the fact CUDA didn't have local_max set. This PR sets local_max for CUDA backend, CIFAR works again.
> CIFAR works again on CUDA

- tinygrad/codegen/linearizer.py
- tinygrad/runtime/ops_cuda.py
Quick fix to #1447, only committed in previous pr, but forgot to push, so only original commit of PR got merged. Added comment to linearizer that explains flip behavior. Also it actually doesn't have to be done for WGPU, since it doesn't flip local dims when kernel renders.
> Actually flip local_max in CUDA

- setup.py
Some backends like Metal, Clang and WebGPU needs tinygrad.renderer to be added to the packages.
> Add tinygrad.renderer to packages in setup.py

- test/test_jit.py
Closes #1503.
The test is the only one that compares gpu floats to numpy floats with assert_equal. The issue was reproducible on NVcards which use `-fmad=true` by default.
> use allclose instead of equals in test_jit

- examples/llama.py
- test/test_ops.py
- tinygrad/tensor.py
changes made (so far)
- implemented function
- support is_causal and attn_mask
- wrote test cases
- use function in LLaMA
> Tensor.scaled_dot_product_attention to match torch, used in LLaMA, and tested

- test/test_dtype.py
- test/test_ops.py
- tinygrad/renderer/llvmir.py
Whoops, I got a little lax with my llvmir issue... sry
Add to #1480 
it's not a `Tensor.where()` issue that was causing it, it was simply a dtype cast `Tensor([...], dtype.bool).float()` issue
and as such there's also a `Tensor([...], dtypes.float32).cast(dtypes.bool)` issue too.
I deleted the `test_where_bool` test in `test_op.py` and added `TestBoolDtype` in `test_dtype.py`
thanks nimlgen for helping with my issue though
I was just careless.
> llvmir support for bool <-> float casting

- examples/stable_diffusion.py
Changes made:
- compute attention with `Tensor.scaled_dot_product_attention`
- remove `self.scale` as they are no longer used
Results:
> a horse sized cat eating a bagel
> tinybox in a living room, vaporwave, volumetric light, octane render, hyperrealistic
> SD: Refactor AttnBlock, CrossAttention, CLIPAttention to share code

- tinygrad/runtime/ops_clang.py
attempt to fix file race condition described in https://github.com/tinygrad/tinygrad/issues/1258
> fix file race condition in ops_clang

- examples/benchmark_train_efficientnet.py
- Python 3.11.4
- numpy 1.24.2
Fixes issue:
```
loss_cpu = loss.detach().numpy()[0]
~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed
```
> examples: numpy() array returns only one value, not an array

- test/test_ops.py
- tinygrad/helpers.py
- tinygrad/ops.py
Closes #1495
This also makes our torch backend to match our GPU backends when working with non-float types:`torch.tensor([10], dtype=torch.int32).sqrt()` (expected to return `int32(3)`, was `float32(3.1623)`).
> fix casting behavior for interpreted buffers

- test/test_tensor.py
- tinygrad/tensor.py
_ctx is deleted after `backwalk()` [here](https://github.com/tinygrad/tinygrad/blob/master/tinygrad/tensor.py#L236), and crashes because we weren't doing the proper check for deleted attribute
```
ERROR: test_deepwalk_ctx_check (__main__.TestTinygrad)
----------------------------------------------------------------------
File "/Users/yiminghan/tinygrad/test/test_tensor.py", line 221, in test_ctx
x.dot(layer).mean().backward()
File "/Users/yiminghan/tinygrad/tinygrad/tensor.py", line 224, in backward
for t0 in reversed(self.deepwalk()):
File "/Users/yiminghan/tinygrad/tinygrad/tensor.py", line 215, in deepwalk
return _deepwalk(self, set(), [])
File "/Users/yiminghan/tinygrad/tinygrad/tensor.py", line 212, in _deepwalk
if i not in visited: _deepwalk(i, …
```
> fix deepwalk ctx check crash

- tinygrad/runtime/ops_clang.py
as suggested by @wozeparrot in https://github.com/tinygrad/tinygrad/pull/1458/files#r1292819054
> fix file race condition in ops_clang via pid in the filename

- test/test_lazybuffer.py
- test/test_symbolic_shapetracker.py
- test/unit/test_symbolic.py
- tinygrad/lazy.py
- tinygrad/shape/shapetracker.py
- tinygrad/shape/symbolic.py
part of #1353, move variable values from `Variable.val` to `ShapeTracker`
this effectively reverted #1391 and changed #1386 to what you have suggested previously
```
vi = Variable("i", 1, 10)
a = Tensor.rand(3, 4).reshape(vi, 2)
b = Tensor.rand(2, 4).reshape(vi, 2)
```
now stores `{vi:6}` in `a` and `{vi:4}` in `b`.
later in `ASTRunner` we will check if all `src` have compatible variable values and propagate the `var_vals` to output
> ShapeTracker.var_vals

- tinygrad/jit.py
Addressed the TODO in  [tinygrad/jit.py](https://github.com/tinygrad/tinygrad/blob/master/tinygrad/jit.py#L15)
`self.jit_cache: List[Tuple[Callable, Any]] = []  # TODO: Any should be List[RawBuffer], but this fails`
This should be `Tuple[Callable, List[Optional[RawBuffer]]]]` since elements can be None. The fix also requires `# type: ignore[no-redef]` on two lines since mypy fails to infer the correct type when `args` is redefined.
> Change Any to List[Optional[RawBuffer]] in JIT

- .github/workflows/test.yml
github updated their runner images, and fast-apt-mirror due to that.
just disable it for now, tracking upstream: https://github.com/vegardit/fast-apt-mirror.sh/issues/2
> hotfix for broken ci

- .github/workflows/test.yml
- test/test_helpers.py
- test/test_symbolic_ops.py
- test/test_symbolic_shapetracker.py
- test/unit/test_symbolic.py
- tinygrad/codegen/linearizer.py
- tinygrad/codegen/optimizer.py
- tinygrad/helpers.py
- tinygrad/ops.py
- tinygrad/renderer/cstyle.py
- tinygrad/renderer/wgsl.py
- tinygrad/runtime/ops_clang.py
- tinygrad/runtime/ops_gpu.py
- tinygrad/runtime/ops_metal.py
- tinygrad/shape/shapetracker.py
- tinygrad/shape/symbolic.py
part of #1353 , codegen and exec to implement `realize` for symbolic inputs.
The combined `var_vals` are passed into kernel function directly. I have implemented the backend for CLANG, GPU, METAL. `global_size`, `local_size` and `op_estimate ` are computed to int during exec. In addition to CI, I also tested with `DEBUG=4 python -m pytest -rA test/test_symbolic_ops.py` to make sure all debugging info renders with symbols.
Most of the hand coded optimization works, and I need to disable the upcast ones because we cannot upcast a symbolic axis.
Also added some test cases for 2 variables. Want to make it as general as possible.
These two examples show that we need to support symbolic for loop max and symbolic offset
kernel for matmul `(3, vi) @ (vi, 5)`
```
#include <metal_stdlib>
using …
```
> symbolic codegen and exec

- tinygrad/runtime/ops_gpu.py
move stuff that doesn't need to be in `post_init` into `__init__`.
this lets us get a total device count before the devices are actually initialized. Needed for #1529.
this also lets us get the device names before the devices are initialized. Needed for #1545.
> cleanup ops_gpu

- extra/hip_wrapper.py
`c_void_p` can't be hashed, but we can hash the underlying pointer value,
and `int` gets auto upcasted to `c_void_p` when passed to a ctypes function that takes `c_void_p`
> fix lru on hip

- test/test_symbolic_shapetracker.py
- test/unit/test_symbolic.py
- tinygrad/shape/symbolic.py
This was not needed for #1353 but makes the symbolic x symbolic more general. I dropped a `realize` during `llama.py` cleanup and ended up make these changes. We will have the `realize` back to llama but I think it's good to make these operation more future proof.
It's mostly about `NumNode` ops with other `Node`. `NumNode(1) * Node` was a `MulNode` and now simplified to a `Node`. Also support `NumNode // NumNode` etc.
Also now `Node.__mod__` and `Node.__floordiv__` use the same set of checks. Tests were updated to reflect that.
Lastly, `SumNode // SumNode` defers the remainder check to another `//`. Previously we only support the case that remainder is 0.
> more symbolic symbolic ops

- .github/workflows/test.yml
* Adds `--no-install-recommends` to intel installation
* Changes `apt-get` to `apt`
* Consolidates update and install step
> fix: apt-get to apt, no recommends, clean up

- test/test_dtype.py
- tinygrad/codegen/assembly_arm64.py
broadcasting using CI=1 ARM64=1 CLANG=1 was incorrect since the stored values were shifted depending on dtype. When the assembler copied the tensor into the broadcasted array it would do so incorrectly because of this shift. This error would only occur when the broadcasted array shape was a multiple of 4. By default int32 was shifting by #0 so I removed the shift condition and all the tests passing again.
these are the tests I ran below:
```
CI=1 ARM64=1 CLANG=1 python -m pytest -n=auto test/ -k 'not (test_nn.py and (test_conv_transpose2d or test_conv2d))' --ignore=test/models --ignore=test/test_speed_v_torch.py --ignore=test/test_net_speed.py --ignore=test/test_specific_conv.py  --ignore=test/unit/test_disk_tensor.py
```
> for issue #1555, int64 and int8 in CI=1 ARM64=1 CLANG=1

- tinygrad/codegen/assembly_arm64.py
Some int registers and fp registers were overwritten being caller-save. Made the generated asm to follow arm64 calling convention.
> fix usage of arm64 regs according to CC

- test/test_linearizer.py
- tinygrad/codegen/linearizer.py
Supports #1037. Depends on #1482, merge that to see a good diff.
Before, CSE was done by comparing AST subtrees. When upcasting, there may be common expressions within a single subtree (eg a.expand([2]) + b.expand([2]), see the tests). Additionally, doing CSE at a uop level gives us a place to add zero-folding, which is much easier to implement at a uop level.
Before (running the test, note two adds):
```
*** exec  0.00 GB    0.02 ms op: BinaryOps.ADD        out(float): (2,)                           in(2): [(2,)] 
UOps.DEFINE_GLOBAL  :                           []                               ('data0', dtypes.float)
UOps.DEFINE_GLOBAL  :                           []                               ('data1', dtypes.float)
UOps.DEFINE_GLOBAL  :                           [] …
```
> CSE at uop level

- test/test_ops.py
- tinygrad/tensor.py
Image tests fails when test size is (10,20,30) ("test/test_ops.py::TestOps::test_argmax - pyopencl._cl.LogicError: clCreateImage failed: INVALID_IMAGE_SIZE") not sure why but with (10,20) passes.
Note: Torch selects first index for duplicate max, this version selects last index. Cant find a way to select the first occurence
@wozeparrot If this passes you can update the argmax in cifar, I cant update it as I cant run cifar at the moment.
> Argmax/Argmin Feature

- tinygrad/lazy.py
One of my favourites.
Before
```
Total time: 0.813725 s
File: /home/rvd/src/roelofvandijk/tinygrad/tinygrad/lazy.py
Function: _push_movement_ops at line 300
300                                           @profile
301                                           def _push_movement_ops(srcs:Tuple[LazyBuffer, ...]) -> Tuple[LazyBuffer, ...]:
302     53865      17066.2      0.3      2.1    new_srcs = []
303     96942      25955.3      0.3      3.2    for x in srcs:
304     96942      19403.3      0.2      2.4      mops: List[Tuple[MovementOps, Any]] = []
305     96942      13880.5      0.1      1.7      bx = x
306                                               # backwalk …
```
> perf: if argument order (mops)

- tinygrad/helpers.py
- tinygrad/lazy.py
- tinygrad/runtime/lib.py
`namedtuple` are like Gondor, they need no key.
The intention is to use this as a key for the LazyCache, so it needs to be hashable. As `namedtuple`, `dtype` is already hashable.
If the `ShapeTracker` where a tuple of views, it would be hashable by itself as well.
`python3.11 -O test/external/external_test_speed_llama.py`
Before
```
codegen         mean runtime:  193.99ms, runs:   229.83,  246.88,  180.52,  176.26,  195.84,  178.55,  184.07,  187.23,  176.50,  184.28
methodcache     mean runtime:  175.20ms, runs:   209.10,  197.53,  162.70,  161.03,  162.69,  188.16,  163.63,  173.66,  167.63,  165.84
profile         mean runtime:  830.36ms, runs:   807.96,  892.16,  756.62,  899.99,  830.83,  803.15,  790.21,  789.10,  852.20,  881.34
```
After
```
codegen         mean runtime: …
```
> perf: namedtuples are hashable, don't need a key

- tinygrad/lazy.py
`CPU=1 kernprof -lv pytest -s test/unit`
before
```
Total time: 1.27732 s
File: /home/rvd/src/roelofvandijk/tinygrad/tinygrad/lazy.py
Function: toCPU at line 188
188                                             @profile
189                                             def toCPU(self):
190      2569       1848.9      0.7      0.1      assert self.dtype.np, f"{self.dtype} is not supported in toCPU"
191      2446    1012422.5    413.9     79.3      realized = self.cast((dtypes.from_np(self.dtype.np), False)).contiguous().realize().realized
192      2569     262520.3    102.2     20.6      ret = cast(RawBuffer, realized).toCPU().reshape(self.shape)
193      2569 …
```
> perf: no ret needed

- docs/quickstart.md
- examples/serious_mnist.py
- extra/training.py
- test/test_nn.py
- tinygrad/tensor.py
The flat training loss was due to missing the conversion to numpy in `accuracy = (cat == y).mean()`. Saw tests passed so didn't double check. Sorry.
```
loss 2.67 accuracy 0.03: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.38it/s]
loss 4.37 accuracy 0.22: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 96.55it/s]
loss 0.09 accuracy 0.98: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 84.68it/s]
100%|██████████████████████████████████████████████████████████████████ …
```
> sparse cat cross entropy

- examples/llama.py
- test/test_jit.py
- test/test_symbolic_jit.py
- test/test_symbolic_ops.py
- test/test_symbolic_shapetracker.py
- tinygrad/jit.py
- tinygrad/shape/symbolic.py
This jits the `freqs_cis` kernel using `shrink`, and updates the jit to check `ShapeTracker.views` against the cached input. Verified that the old llama failed if we removed contiguous with this check.
Will check for the 5ms thing and jit the new sample (that uses `Tensor.argmax`) in a separate PR.
Assigning variable using `freqs_cis.lazydata.st.var_vals[pos] = start_pos` works, but it feels weird as an API. Another use case that we don't support now is reshape a 2d matrix into (variable, variable) that commavq might want?
> support symbols in shrink and JIT freqs_cis in llama

- README.md
this PR adds links to the `tinygrad already supports numerous accelerators, including:` section of the readme
> add accelerator links to readme

- docs/quickstart.md
In the quickstart MNIST training example, only convert final accuracy tensor to numpy, to avoid mixed type comparison in `pred == labels`, which yields `True` everywhere and thus accuracy `1.0`.
> Quickstart: Use tensors to compute train accuracy

- tinygrad/runtime/ops_metal.py
This should fix the Metal blocking issue. From [doc](https://developer.apple.com/documentation/metal/mtlcommandqueue/3553957-makecommandbuffer)
"Each command queue has a fixed number of command buffers for its lifetime (see [makeCommandQueue(maxCommandBufferCount:)](https://developer.apple.com/documentation/metal/mtldevice/1433433-makecommandqueue)). This method blocks the calling CPU thread when the queue doesn’t have any free command buffers, and returns after the GPU finishes executing one."
The default `newCommandQueue` set the number to 64 [(doc)](https://developer.apple.com/documentation/metal/mtldevice/1433388-makecommandqueue). This PR increases it to 1024. I could not find a guidance on the limit of this number. A stackoverflow …
> Increase MaxCommandBufferCount in ops_metal to 1024

- examples/hlb_cifar10.py
```
999   86.53 ms run,    3.84 ms python,   82.68 ms CL,  491.54 loss, 0.000070 LR, 6.90 GB used,   7793.55 GFLOPS
eval 9404.0/10000 94.04%,    0.40 val_loss STEP=1000
```
1. move to device, cast to float, normalize, reshape, one-hot encode labels, and pad to 36x36 all technically need to be done only once, thus take them out of the `fetch_batch`.
2. The left pre-processing operations that need to be done while batching are random crop, random flip, and cutmix with random masks. They are currently applied on all 50,000 training data every 98 STEPS and are not **jitted**. This is also what [hlb_CIFAR10](https://github.com/tysam-code/hlb-CIFAR10/blob/ff53cac99dc71a66b1ada43d63d1307debd592a7/main.py#L460C22-L460C22) is doing.
3. There's still 3 places inside `fetch_batch` that makes a …
> fix CIFAR jit

- tinygrad/tensor.py
This `tuple(list` was unnecessary.
In general, using more tuples in other places might help (a bit) as well.
> refactor: tuples can be concatenated with +

- tinygrad/graph.py
- tinygrad/lazy.py
- tinygrad/ops.py
See [docs](https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING).
Note that `GRAPH=1` is not covered in the CI tests.
> [ready] avoid in-function graph imports in lazy.py

- .github/workflows/test.yml
Running no tests on Python 3.8 makes it very easy to add features that are incompatible with that version. I suggest running at least the linters in both 3.8 and 3.11. Technically, only 3.8 would probably suffice.
> [ready] ci: add py38 to linters

- tinygrad/ops.py
Pulled out the buffers init line from https://github.com/tinygrad/tinygrad/pull/1603
```
before
codegen         mean runtime:  286.26ms, runs:   269.69,  334.04,  290.90,  271.43,  274.94,  275.24,  279.90,  289.45,  284.85,  292.20
methodcache     mean runtime:  271.34ms, runs:   289.39,  279.17,  283.27,  266.64,  251.71,  253.12,  306.11,  263.08,  264.54,  256.33
profile         mean runtime: 1005.80ms, runs:   887.07, 1040.87, 1005.02,  979.29, 1043.24,  974.64, 1016.84, 1007.91, 1001.12, 1101.99
Total time: 1.02049 s
File: /home/rvd/src/roelofvandijk/tinygrad/tinygrad/ops.py
Function: __init__ at line 29
29                                             @profile …
```
> [ready] perf: faster lazyop init

- test/test_symbolic_jit.py
- test/test_symbolic_ops.py
- tinygrad/tensor.py
`scaled_dot_product_attention` in training mode always creates a dropout mask before, so symbolic tests will fail in training mode because we don't support `Tensor.rand` for symbolic shape. `test_nn.py` might set `Tensor.training` to true, and `test_symbolic_ops.py` fails if it's run after.
Fix by not creating a dropout mask if `dropout_p==0`, which is the default for `scaled_dot_product_attention`
> fix symbolic_ops tests with Tensor.training=True

- tinygrad/ops.py
`self.buffers` was empty on error, now it can be partially filled.
See https://github.com/tinygrad/tinygrad/pull/1673#pullrequestreview-1597103014
> [ready] fix: restore all-or-nothing for buffers

- tinygrad/ops.py
The cast was killing the performance of `LazyOp.__eq__`
```
from:
Total time: 0.13719 s
File: /home/rvd/src/roelofvandijk/tinygrad/tinygrad/ops.py
Function: __eq__ at line 35
35                                             @profile
36                                             def __eq__(self, __value: object) -> bool:
37     46378      14344.3      0.3     10.5      if __value.__class__ is not LazyOp: return False
38     46378      98018.8      2.1     71.4      __value = cast(LazyOp, __value)
39     46366      24826.8      0.5     18.1      return self.op == __value.op and self.src == __value.src and self.arg == __value.arg
to:
Total time: 0.0412131 s
File: …
```
> [ready] perf: faster lazyop eq

- tinygrad/codegen/linearizer.py
Don't check each time for  `=0`, just start at 1.
```
before
92     216255.2   2350.6     13.1          loaded_buffers.update({b:self.global_load(self.bufs.index(self.local_alias[i]) if i in self.local_alias else i, global_idxs+local_idxs+reduce_idxs+full_upcast_idxs) for i,b in enumerate(self.bufs) if b in self.earlybufs and i != 0})
after
92     170862.2   1857.2     11.1          loaded_buffers.update({b:self.global_load(self.bufs.index(self.local_alias[i]) if i in self.local_alias else i, global_idxs+local_idxs+reduce_idxs+full_upcast_idxs) for i,b in enumerate(self.bufs[1:]) if b in self.earlybufs})
```
> [ready] perf: start enumerate at 1 instead of checking all i

- tinygrad/lazy.py
- tinygrad/ops.py
The cast here was necessary because .__class__ was used instead of isinstance. Mypy only understands isinstance. Without either the cast or isinstance, mypy will complain about the attribute access of __value.
Together they are both slower and more complex than just using isinstance.
> perf: remove cast and revert back to isinstance

- tinygrad/tensor.py
Note the enormous fraction of time that `canonicalize` consumes... This can be avoided (https://github.com/tinygrad/tinygrad/pull/1680).
```
before
codegen         mean runtime:  266.70ms, runs:   412.61,  276.13,  244.64,  247.40,  247.41,  241.40,  249.70,  241.22,  249.48,  257.01
methodcache     mean runtime:  259.77ms, runs:   290.15,  280.88,  272.47,  238.81,  280.16,  292.18,  229.41,  224.18,  230.08,  259.41
profile         mean runtime: 1108.83ms, runs:  1011.89, 1157.24, 1211.69, 1231.71, 1039.94, 1129.84,  991.76, 1167.78, 1080.75, 1065.67
Total time: 1.01743 s
File: /home/rvd/src/roelofvandijk/tinygrad/tinygrad/tensor.py
Function: __init__ at line 41 …
```
> [ready] perf: simpler Tensor init

- test/test_helpers.py
A test case after the `dtypes.bool` bug that was a native python bool instead of `np.bool_`.
The bug originally was noticed and fixed here when building teenygrad https://github.com/tinygrad/tinygrad/pull/1589/files#diff-50df1fc0be73d15ad0f20907e19fbba15df16e785af95ea82f8f5910b22e707bL96
The test case here checks that all the fields in dtypes extend from a numpy type
> unit test dtypes to prevent bugs

- examples/llama.py
performance critical `realize` for the unjitted path
this PR
```
ran model in 161.57 ms
sync in 4.14 ms
2
ran model in 162.44 ms
sync in 3.56 ms
0
ran model in 162.07 ms
sync in 3.94 ms
year
ran model in 172.77 ms
sync in 3.67 ms
old
ran model in 162.81 ms
sync in 3.87 ms
male
```
master
```
ran model in 190.39 ms
sync in 6.33 ms
2
ran model in 234.34 ms
sync in 4.78 ms
0
ran model in 214.29 ms
sync in 4.13 ms
year
ran model in 227.56 ms
sync in 4.87 ms
old
ran model in 232.43 ms
sync in 5.71 ms
male
```
> critical realize for unjitted llama

- examples/llama.py
Top memory usage was about 2x since new weights were realized while original are still refed.
> remove memory peak for quantized llama

- examples/deep_deterministic_policy_gradient.py
- tinygrad/nn/optim.py
fixes #1667 
the bug for 1667 happens when the device.Default differs from that of DEVICE from 
deep_determinist_policy_gradient.py: 13
`DEVICE = "GPU" if getenv("GPU") else "CPU"`
> Changed DEVICE to Device.DEFAULT in deep_determinist_policy_gradient

- test/external/external_model_benchmark.py
All models from https://github.com/commaai/commavq have been moved to https://huggingface.co/commaai/commavq-gpt2m.
(https://github.com/commaai/commavq/commit/78a85e64b5acc92cbed0ba5b7517fd09057610e8)
> Reactivate commavq/gpt2m benchmark

- test/unit/test_symbolic.py
- tinygrad/shape/symbolic.py
similar to #1669, also added unit tests for `sym_infer`
should be faster in theory due to fewer `int` case check , but I could not measure a meaningful end to end difference. Also verified that GPU jitted llama still is < 5ms.
> visitor pattern for sym_infer and unit tests

- examples/gpt2.py
- test/models/test_real_world.py
Move symbolic reshape and shrink inside the jitted function and jit the whole `TransformerBlock.__call__` similar to #1633. It saved about 1.5 ms python time on M1 Max with METAL. `GPU=1` is currently broken with `ValueError: probabilities contain NaN` on mac on master.
Also added a gpt2 test in `test_real_world`.
with `METAL=1 JIT=1 python examples/gpt2.py --prompt="Hello." --count=10 --temperature=0 --timing`.
this PR
```
ran model in 11.31 ms
total 43.88 ms
ran model in 11.41 ms
total 43.93 ms
ran model in 11.34 ms
total 44.10 ms
Hello. I'm a little late to the party, but
```
master
```
ran model in 12.95 ms
total 44.02 ms
ran model in 13.20 ms
total 43.97 ms
ran model in 13.11 ms
total 44.24 ms
Hello. I'm a little late to the party, but
```
> faster gpt2 jit path and gpt2 in test_real_world

- tinygrad/lazy.py
The `ret` is not required that early, since the `.st` is just the `st` passed in. It can also not be realized yet.
```
before
codegen         mean runtime:  298.02ms, runs:   380.94,  292.23,  294.43,  285.56,  291.13,  279.13,  287.87,  295.79,  282.54,  290.57
methodcache     mean runtime:  271.31ms, runs:   306.46,  260.52,  258.55,  261.83,  261.36,  266.73,  258.98,  285.36,  291.98,  261.37
profile         mean runtime:  940.76ms, runs:   881.74,  936.80,  973.32,  924.76,  949.20,  924.44,  956.17,  944.20,  958.76,  958.20
Total time: 3.39387 s
File: /home/rvd/src/roelofvandijk/tinygrad/tinygrad/lazy.py
Function: shuffle_and_prune_movement_ops at line 222 …
```
> [ready] perf: create buffer only when needed

- docs/abstractions.py
In #1723, the Token class was removed.
> Remove Token from abstractions.py

- test/test_conv.py
- test/test_nn.py
- tinygrad/codegen/optimizer.py
- tinygrad/mlops.py
- tinygrad/shape/shapetracker.py
- tinygrad/tensor.py
New pr, old: #1037 . Tracking issue: #1618 . This is the minimal set of changes for fast winograd. Compilation time is slow with only this patch, that needs #1484 and some expr_idxs changes.
On rtx3090:
```
conv bs:  4 chans:128 -> 128 k:3              0.70 ms (86888.78 GFLOPS 126888.59 GB/s) in torch,    0.79 ms (77287.86 GFLOPS 112867.82 GB/s) in tinygrad,    1.12x slower   60806.07 MOPS 88798.54 MB
```
It can be 0.77ms with a slightly different hand coded optimization change, or it can be very good with KOPT.
We can merge once this part of the code is refined and the compile time is sufficiently low.
> 3x3 winograd convs

- .github/workflows/test.yml
- docs/env_vars.md
- setup.py
- test/models/test_real_world.py
- tinygrad/codegen/search.py
Add env variable `BUDGET` for search budget. Test in CI with `DEBUG=1` so we can check if it runs.
It surfaces 2 problems:
(1) llama generation is not fully covered in test, currently KOPT fails because of symbolic offset, but CI does not test it. I plan to fix this and update the test in a separate PR.
(2) cifar hangs with current KOPT. People reported it in discord. Skip in CI for now.
> Test KOPT in CI

- test/test_speed_v_torch.py
- tinygrad/codegen/linearizer.py
- tinygrad/codegen/optimizer.py
This PR enables tensor cores with 2D convolutions. Depending on the kernel size, this results in a speedup of up to 1.63 on my machine (M1 Max with 24 GPU cores).
master:
```
conv bs: 32 chans:128 -> 128 k:1              4.32 ms ( 3976.36 GFLOPS   124.28 GB/s) in torch,    3.21 ms ( 5355.60 GFLOPS   167.38 GB/s) in tinygrad,    0.74x faster   17179.87 MOPS   536.94 MB
conv bs:  4 chans:128 -> 128 k:3              2.68 ms ( 7210.13 GFLOPS    25.65 GB/s) in torch,    5.43 ms ( 3561.77 GFLOPS    12.67 GB/s) in tinygrad,    2.02x slower   19327.35 MOPS    68.76 MB
conv bs:  4 chans:128 -> 128 k:5             12.48 ms ( 4302.68 GFLOPS     5.68 GB/s) in torch,   14.29 ms ( 3756.84 GFLOPS     4.96 GB/s) in tinygrad,    1.15x slower   53687.09 MOPS    70.88 MB
conv bs:  4 chans:128 -> 128 k:7 …
```
> Metal conv tensor cores

- test/external/external_multi_gpu.py
introduced by fb1cc6bf4be9325a6161dbabcb35c393c7b50dee
> revert typo in external_multi_gpu.py

- tinygrad/renderer/cstyle.py
Some opencl compilers are not happy with:
```
<program source>:35:41: error: member reference base type 'float' is not a structure or union
acc0.x = (((float4)(0.0f,0.0f,0.0f,0.0f).x*val12.x)+acc0.x);
~~~~~~~~~~~~~~~~~~~~~^~
```
> fix gpu compilation of const GEP

- test/test_tensor.py
- tinygrad/tensor.py
Upon tryign to run codellama example with GPU=1 on M2 Macbook Air 16GB, I was getting following errors
```
AttributeError: 'E_12_4_8_16_2_4' was not found as a program info attribute or as a kernel name
pyopencl._cl.LogicError: clCreateKernel failed: INVALID_KERNEL
```
The kernel had was taking in a `double` parameter, e.g.
`__kernel void E_12_4_8_16_2_4(__global float* data0, const __global float* data1, const __global double* data2) {`
but was assigning to float value
`float val4 = data2[(gidx1*32)+(lidx3*2)+(gidx0*128)];`
and after some digging I realized Tensor was loading in ndarray with incorrect dtype
> Use correct dtype in Tensor when data is an ndarray

- tinygrad/shape/symbolic.py
subclassing `ABC` makes `isinstance` on nodes slow because it also calls the instance check in abc. We can make `Node` concrete by raising `RuntimeError`.
`STEPS=10 WINO=1 python examples/hlb_cifar10.py`
master
```
0 22255.78 ms run, 22255.38 ms python,    0.40 ms CL, 1187.24 loss, 0.001281 LR, 1.45 GB used,     21.33 GFLOPS
1 4982.98 ms run, 4982.46 ms python,    0.53 ms CL, 1187.59 loss, 0.002563 LR, 5.00 GB used,     93.98 GFLOPS
2  147.11 ms run,   19.96 ms python,  127.15 ms CL, 1903.47 loss, 0.002994 LR, 5.00 GB used,   3183.58 GFLOPS
3  142.42 ms run,    9.98 ms python,  132.44 ms CL, 2749.10 loss, 0.002577 LR, 5.00 GB used,   3288.29 GFLOPS
4  142.80 ms run,    8.58 ms python,  134.22 ms CL, 2304.10 loss, 0.002159 LR, 5.00 GB used,   3279.50 GFLOPS
5  142.65 ms run,    7.66 ms …
```
> Node does not need to subclass ABC

- examples/llama.py
`precompute_freqs_cis` was returning a numpy float64 (double) when all we need is float32 (and all mac can support)
This seems consistent now with meta's implementation:
```
def precompute_freqs_cis(dim: int, end: int, theta: float = 10000.0):
freqs = 1.0 / (theta ** (torch.arange(0, dim, 2)[: (dim // 2)].float() / dim))
t = torch.arange(end, device=freqs.device)  # type: ignore
freqs = torch.outer(t, freqs).float()  # type: ignore
freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
return freqs_cis
```
notably: the `.float()` for freqs after torch.outer.
---
now GPU=1, and also ofc METAL=1 work for llama example
> fix llama on apple silicon, keep freqs type consistent

- tinygrad/shape/symbolic.py
a huge portion of compile time is simplifying `valid`, naive short circuit AndNode 20s -> 17s. Saved about 50% of `AndNode.substitute` time and 25% calls to `isinstance`.
`STEPS=5 WINO=1 python examples/hlb_cifar10.py`
master
```
0 20196.11 ms run, 20195.73 ms python,    0.37 ms CL, 1187.24 loss, 0.002563 LR, 1.45 GB used,     23.51 GFLOPS
1 4702.02 ms run, 4701.55 ms python,    0.46 ms CL, 1187.59 loss, 0.002577 LR, 5.00 GB used,     99.60 GFLOPS
2  143.23 ms run,   19.05 ms python,  124.18 ms CL, 2754.43 loss, 0.001741 LR, 5.00 GB used,   3269.73 GFLOPS
3  143.49 ms run,   10.02 ms python,  133.47 ms CL, 2845.13 loss, 0.000906 LR, 5.00 GB used,   3263.80 GFLOPS
4  142.64 ms run,    7.69 ms python,  134.94 ms CL, 2122.40 loss, 0.000070 LR, 5.00 GB used,   3283.31 GFLOPS
```
this PR
```
0 …
```
> AndNode.substitute short circuit

- examples/gpt2.py
- examples/llama.py
- test/test_custom_function.py
- test/test_symbolic_jit.py
- test/test_symbolic_ops.py
- test/test_symbolic_shapetracker.py
- tinygrad/codegen/linearizer.py
- tinygrad/jit.py
- tinygrad/lazy.py
- tinygrad/ops.py
- tinygrad/shape/shapetracker.py
Make ShapeTracker stateless and cache friendly.
Need to make a behavior change that reshape from symbolic shape to an int shape not erasing the `var_vals`. This is needed in the llama jitted path because we are using symbolic offset.
> Move var_vals from ShapeTracker to LazyBuffer

- tinygrad/shape/symbolic.py
`Node.__lt__` is cleaner now
I did not modify any logic in this PR, the subtraction then factoring gcd out can be simpler. Will do the rewrite in a separate PR. Need to add a type ignore for the gcd part, mypy does not know that `__lt__` is only used for idx and not symbolic shape.
comes with a tiny perf improvement, 2% faster wino cifar and 5% less call to isinstance
master
```
PYTHONPATH=. STEPS=5 WINO=1 python -O examples/hlb_cifar10.py
0 16106.11 ms run, 16105.71 ms python,    0.40 ms CL, 1187.24 loss, 0.002563 LR, 1.45 GB used,     29.47 GFLOPS
1 4303.18 ms run, 4302.69 ms python,    0.49 ms CL, 1187.59 loss, 0.002577 LR, 5.00 GB used,    108.83 GFLOPS
2  142.45 ms run,   17.51 ms python,  124.94 ms CL, 2754.43 loss, 0.001741 LR, 5.00 GB used,   3287.59 GFLOPS
3  142.49 ms run, …
```
> move Node.__lt__ SumNode special case to SumNode.__lt__

- tinygrad/renderer/cstyle.py
We already did this for dtypes.sz > 1, but nvcc wants this for half->float casts.
Fixes compile problem with `FP16=1 JIT=1 CUDA=1 python3 examples/gpt2.py`:
```
kernel.cu(21): error: ambiguous "?" operation: second operand of type "const half" can be converted to third operand type "float", and vice versa
float val2 = (alu0)?(data3[gidx1+1024]):0.0f;
```
> cast types in render_load

- tinygrad/shape/symbolic.py
`DivNode.b` can only be `int`. It's asserted in `get_bounds` in L201
> Remove isinstance(self.b, int) check in DivNode.substitute

- tinygrad/codegen/optimizer.py
- tinygrad/shape/shapetracker.py
1. NamedTuple already supplies the (identical) `__repr__`
2. Use `View.create` everywhere
3. Correctly cache the instantiantion via `View.create`
4. `shape_strides` was only used once
Comes with a minor speedgain (4%), but this one is more correctness.
```
codegen         mean runtime:  203.41ms, runs:   246.02,  200.11,  178.07,  179.18,  182.85,  181.67,  193.41,  183.10,  185.06,  304.62
methodcache     mean runtime:  170.13ms, runs:   154.47,  173.37,  185.78,  177.96,  172.94,  164.38,  170.64,  168.89,  163.49,  169.36
profile         mean runtime:  789.72ms, runs:   774.23,  774.34,  851.13,  764.46,  776.03,  801.11,  780.29,  779.02,  805.98,  790.56
to
codegen         mean runtime:  195.06ms, runs:   255.96,  186.99,  182.53,  175.61,  180.32,  181.48,  178.95,  178.96,  181.35, …
```
> fix: clean up View

- test/test_tensor.py
Here is a minimal test case for producing the following error, which was fixed by #1839 
```
python test/test_tensor.py TestTinygrad.test_tensor_copy
File "/home/g1y5x3/tinygrad/test/test_tensor.py", line 240, in test_tensor_copy
copy.deepcopy(Tensor.ones((3,3,3)))
File "/usr/lib/python3.11/copy.py", line 172, in deepcopy
y = _reconstruct(x, memo, *rv)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/copy.py", line 271, in _reconstruct
state = deepcopy(state, memo)
^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/copy.py", line 146, in deepcopy
y = copier(x, memo)
^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/copy.py", line 211, in _deepcopy_tuple
y = [deepcopy(a, memo) for a in x]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/copy.py", line …
```
> add  test_tensor_copy

- .github/workflows/test.yml
- tinygrad/shape/view.py
reapply the fix in #1842, the patch had reverted the fix. Also downgrade CPU CI test to python 3.8 to catch this. It's about one minute slower in CI, but still faster than clang and cuda.
also test locally with `python3.8 test/external/external_model_benchmark.py`
> Fix view, CI cpu test with python 3.8

- test/unit/test_helpers.py
- tinygrad/helpers.py
- tinygrad/lazy.py
- tinygrad/nn/__init__.py
- tinygrad/tensor.py
added the minimal `all_int` asserts required by mypy
some notes:
- `_realize_rand` does not support symbolic shape either, but the check is deferred to numpy
- The ones followed by `Tensor.kaiming_uniform` is annoying but I don't see a simple way to annotate Tensor with int shape (similar to `LazyBuffer` with non-None `realized` requires explicit cast...).
- `mean` and `std` technically can support symbolic shape if we only average over int dims, but we are not using it now
> fix type of helpers.prod, add test cases

- sz.py
Separate the original #1863 into two PRs. It's basic functionality stays the same.
In order for the comment bot in CI to work securely, it should always copy the `sz.py` from the master branch instead of the PR branch. The diff mode has been thoroughly tested. Here is an example of having additional files, deleted files, as well as files with unchanged `Lines` but slightly different `Tokens/Line` to indicate the changes that has been made.
```
Name                              Lines    Diff    Tokens/Line    Diff
------------------------------  -------  ------  -------------  ------
tinygrad/tensor.py                  526     -14           22.9    +0.5
tinygrad/lazy.py                    290      -4           17.6    +0.1
tinygrad/shape/symbolic.py          284      -3           14.8 …
```
> add diff mode to sz.py

- tinygrad/lazy.py
- tinygrad/mlops.py
- tinygrad/shape/shapetracker.py
- tinygrad/shape/symbolic.py
- tinygrad/shape/view.py
Previously after symbolic shrink (e.g. `t[var:var+1]`), the resulted shape would be `NumNode(1)`, and every downstream shapes would have mixed `NumNode` and `int`. And we need `NumNode.__index__` because of that and need to explicitly convert the shape back to int in `toCPU()`.
This PR convert the `NumNode` shape into `int` in `__unsafe_resize`. We can simplify `toCPU` and remove `NumNode.__index__`. Also fixed the types and checks in `real_strides` and `real_offsets`, which previously would be `MulNode(NumNode, Variable)` and now `MulNode(Variable, int)`.
> No NumNode in shape after symbolic shrink

- tinygrad/runtime/ops_hip.py
Tested on gpt2, same output with the same seed:
```
nimlgen@tiny:~/tinygrad$ DEBUG=0 JIT=1 HIP=1 python3 examples/gpt2.py --seed 1 --timing
...
ran model in 17.38 ms
total 18.95 ms
What is the answer to life, the universe, and everything?
"The simple answer is to grow old and die." --Jared Diamond
I once encountered a fan who lived an over-deft life—and then he died of a brain hemorrhage. There is no cure for this, of course, but it is just an easy way to say "happily ever after," which here I would consider a good description of life. When you die, you leave behind everything you hold dear—your friends, your relationships, the chance
```
```
nimlgen@tiny:~/tinygrad$ DEBUG=0 JIT=0 HIP=1 python3 examples/gpt2.py --seed 1 --timing
...
ran model in 2822.14 ms
total 2825.04 ms
What is the …
```
> support symbolic jit in HIP

- .github/workflows/szdiff.yml
Add a branch up-to-date check before triggering the comment bot. It utilizes the `git rev-list --left-right --count  tinygrad/master...${{ github.event.pull_request.head.sha }}` to detect the exact amount of behind/ahead of current branch compare to the tinygrad master branch. Then just condition the comment bot action only on when branch is up-to-date (this is adjustable in `$count -gt 0`).
Here is a sample outout:
```
git rev-list --left-right --count  tinygrad/master...${{ github.event.pull_request.head.sha }} | awk '{print "Behind "$1" - Ahead "$2""}'
Behind 6 - Ahead 0
```
> add branch up-to-date check

- test/external/external_test_allocator_on_models.py
- test/test_allocators.py
- tinygrad/runtime/lib.py
This fixes import error when python is exiting: `ImportError: sys.meta_path is None, Python is likely shutting down` (from `extra/gemm/hip_matmul.py`).
> no import when Python is shutting down

- tinygrad/codegen/optimizer.py
- tinygrad/shape/symbolic.py
Avoids variable check with unexpected behaviour.
This gives better optimizations for gpt2 on my quadro T1000.
`DEBUG=1 JIT=1 python examples/gpt2.py --model_size gpt2 --timing`
Before:
```
ran model in 39.70 ms, 24.71 ms on GPU, 0.34 GOPS, 0.69 GB, 27.72 GB/s
total 41.13 ms
```
After:
```
ran model in 32.58 ms, 17.46 ms on GPU, 0.34 GOPS, 0.69 GB, 39.23 GB/s
total 34.07 ms
```
> Fix gpt optimization

- test/unit/test_symbolic.py
- tinygrad/shape/symbolic.py
- tinygrad/tensor.py
after #1871, there's no NumNode in shape. The only place that `NumNode.int()` is called is inside `LtNode.get_bound()` if the `LtNode` reduces to a `NumNode`. Explicitly expand the 3 possible cases similar to symbolic < symbolic, and we can remove `NumNode.int()`.
Found a bug in the old symbolic < symbolic case that it should be `self.a.min >= self.b.max` to result in `(0, 0)`, not `self.a.min > self.b.max`. Added a regression test and reworked the tests to make it read nicer.
> Remove NumNode.int()

- examples/hlb_cifar10.py
- tinygrad/jit.py
- tinygrad/lazy.py
```
999   64.98 ms run,    3.52 ms python,   61.46 ms CL,  497.12 loss, 0.000086 LR, 6.76 GB used,  10382.36 GFLOPS
eval     9404.0/10000 94.04%,    0.40 val_loss STEP=1000
eval ema 9413.0/10000 94.13%,    0.40 val_loss STEP=1000
```
The most of the speed gain was from changing the `heuristics` in `lazy.py` threshold to 0.1 so that the one giant reduce kernel becomes way faster. But in the mean time, there's also a bunch of incremental speed gain from various PRs @chaosagent and @chenyuxyz submitted.  
Added a ema net based on the [orignal repo](https://github.com/tysam-code/hlb-CIFAR10/blob/ff53cac99dc71a66b1ada43d63d1307debd592a7/main.py#L442-L458) which gives some additional accuracy improvement. However, I tried to tune the hyp-param a little bit more to get rid of fixed random seed …
> cifar step time 65ms while stay above 94%

- extra/hip_wrapper.py
- tinygrad/runtime/ops_hip.py
we still need a better way to handle this, probably just splitting the wrapper into a separate package.
this cleans up the hip wrapper quite a bit, and removes completely useless code that was in there.
this also makes it so that the hip wrapper can be imported without failing if it can't find the hip libraries.
> cleanup hip wrapper

- extra/accel/ane/lib/ane.py
- extra/datasets/__init__.py
- extra/datasets/coco.py
- extra/gemm/amx.py
- extra/gemm/gemm.py
- sz.py
- test/external/external_test_image.py
- test/extra/test_utils.py
this branch:
```
--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```
master:
```
************* Module extra.accel.ane.lib.ane
extra/accel/ane/2_compile/ane.py:217:25: C0303: Trailing whitespace (trailing-whitespace)
extra/accel/ane/lib/ane.py:217:25: C0303: Trailing whitespace (trailing-whitespace)
.... a few more
test/extra/test_utils.py:49:0: W0311: Bad indentation. Found 6 spaces, expected 4 (bad-indentation)
-------------------------------------------------------------------
Your code has been rated at 9.99/10 (previous run: 10.00/10, -0.01)
```
mainly because when running pylint locally it's hard to see which issues are from the change's diff or were just there.
I'm also checking why CI just …
> Fixing pylint errors

- examples/stable_diffusion.py
- While digging in tinygrad showcases, I found a variable defined but not used.
> chore: remove redundant noise in stable diffusion example

- tinygrad/shape/symbolic.py
not used, `AndNode.__mul__` doesn't even return
> Remove LtNode.__mul__ and AndNode.__mul__

- tinygrad/helpers.py
https://github.com/tinygrad/tinygrad/pull/1852 introduced typing_extensions as a runtime requirement, but the package is only noted as a requirement for linting. So trying to use `python -c 'from tinygrad.tensor import Tensor'` after `pip install -e .` on python 3.11 will fail.
It seems that this does not happens before 3.11 only because typing_extensions was a downstream dependency of pyopencl. Anyway this commit makes it clear that typing_extensions is only needed for linting, as written in setup.py.
> Do not import typing_extensions at runtime

- .github/workflows/szdiff.yml
The `header` tag allows you to manage comments independently so removing the tag makes it default to keep only one comment per PR.
Test done in my own [branch](https://github.com/g1y5x3/tinygrad/pull/17)
When branch is behind:
When branch is updated:
> keep only one comment from git action bot

- .github/workflows/test.yml
- extra/gemm/simple_matmul.py
- test/test_linearizer.py
- test/test_speed_v_torch.py
- tinygrad/codegen/kernel.py
As per @geohot 's suggestion, here are the test changes along with just the shapes and no logic changes.
We can see that running `METAL=1 python3 ./test/test_linearizer.py TestLinearizer.test_tensor_cores` passes, but running on a HIP with `HIP=1 python3 ./test/test_linearizer.py TestLinearizer.test_tensor_cores`, the tensor core is triggered but with numerical errors in the output:
```
======================================================================
FAIL: test_tensor_cores (__main__.TestLinearizer.test_tensor_cores)
----------------------------------------------------------------------
File "/home/flammit/tinygrad/./test/test_linearizer.py", line 112, in test_tensor_cores
np.testing.assert_allclose(np_c, r.numpy(), atol=5e-3, rtol=1e-4)
File …
```
> wmma: add test and tensor core shape

- test/test_linearizer.py
Maybe device output buffer allocation belongs in run_schedule instead of exec_ast?
> use schedule in more places in linearizer tests

- tinygrad/lazy.py
- tinygrad/renderer/llvmir.py
The `fast` flag implies both `nnan` and `ninf`. These 2 lead to different results when handling `inf`s/`nan`s. To remove this workaround from lazy, we need to drop these flags.
Closes #1937
> fix llvm nan/inf const

- tinygrad/tensor.py
Note that this could be `zip(m,t)`, but is not, to save expensive `__getitem__` calls on t if `mm==0`. 
Failing test jobs should be the intel keys issue.
> simplify line

- .github/workflows/test.yml
- test/test_dtype.py
- tinygrad/renderer/cstyle.py
- tinygrad/renderer/wgsl.py
I noticed an error when running `stable_diffusion` on `webgpu` (but it can affect any other model when running on `webgpu`):
The cast that is generated inside `render_load` is wrong, because `float` is not defined in wgsl, and because in wgsl this style of cast `(f32)(some_var)` is invalid. The correct syntax is `f32(some_var)`.
I added `render_cast` to wgsl and modified the cstyle version as well to solve this.
> Fix cast error in render_load in wgsl

- setup.py
closes #1990.
can confirm that installing from git with my fork stops pylance from complaining, solving the issue.
> chore: add `py.typed` marker.

- setup.py
This reverts commit 6d581e89113da02c031fdad82a4a8a9730ea91ca.
> Revert "chore: add `py.typed` marker. (#1991)"

- .github/workflows/test.yml
- .pre-commit-config.yaml
- mypy.ini
this allows for reproducible `python -m mypy` runs configured exactly as they would be in ci, without having to manually find and copy all the cli flags.
> ci: use `mypy.ini`

- tinygrad/codegen/optimizer.py
I tried to test it on all hw I have. gpt2 gets the most noticeable boost, while the other models remained relatively stable with no significant performance drop or gain.
| **Model**         | **Master** | **New**   | **Improvement (%)** |
|:-----------------:|:----------:|:---------:|:-------------------:|
| **GPT2 total**    | 10.75 ms   | 7.62 ms   | 29.2% ↑             |
| **LLAMA**         | N/A        | N/A       | N/A                 |
| **SD step**       | 367.60 ms  | 368.48 ms | 0.24% ↓             |
| **HLB CIFAR run** | 15.63 ms   | 15.48 ms  | 0.96% ↑             |
| **Model**         | **Master** | **New**   | **Improvement (%)** |
|:-----------------:|:----------:|:---------:|:-------------------:|
| **GPT2 total**    | 11.91 ms   | 10.83 ms  | 9.08% ↑             |
| …
> allow local + grouped reduce in hand_coded

- examples/llama.py
- test/models/test_real_world.py
Fixed the branching with empty prompt (just one BOS token, this is the current test case in test_real_world that breaks with non-CI). Also applied `all_jitted` test.
master
```
PYTHONPATH=. GPU=1 python3 examples/llama.py --prompt "" --count 20 --temperature 0
using GPU backend
using LLaMA-7B model
ram used: 13.48 GB, freqs_cis                                         : 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 292/292 [00:00<00:00, 2551.49it/s]
loaded weights in 123.70 ms, 13.48 GB loaded at 108.95 GB/s
File "/Users/chenyu/code/tinygrad/examples/llama.py", line 569, in <module>
probs = llama.model(Tensor([toks[start_pos:]]), start_pos, args.temperature).realize() …
```
> Fix llama with empty prompt

- examples/compile_efficientnet.py
- extra/export_model.py
- test/extra/test_export_model.py
Add support for exporting models that have `forward` or `__call__` with multiple Tensor inputs
> Allow multi-input model export

- extra/utils.py
Moves runtime imports to top of file and narrow down.
Should help (a bit) everywhere these functions are used.
After
```
time PYTHONPATH=. STEPS=2 WINO=0 kernprof -lv examples/hlb_cifar10.py
0 1425.81 ms run, 1425.59 ms python,    0.23 ms CL, 1199.34 loss, 0.002262 LR, 0.84 GB used,    473.17 GFLOPS
1  652.53 ms run,  652.34 ms python,    0.19 ms CL, 1196.44 loss, 0.000086 LR, 3.17 GB used,   1033.90 GFLOPS
Wrote profile results to hlb_cifar10.py.lprof
Timer unit: 1e-06 s
real    0m11.992s
user    0m10.608s
sys     0m2.488s
```
Before
```
time PYTHONPATH=. STEPS=2 WINO=0 kernprof -lv examples/hlb_cifar10.py
0 1395.06 ms run, 1394.83 ms python,    0.23 ms CL, 1199.34 loss, 0.002262 LR, 0.84 GB used,    483.60 GFLOPS
1  649.72 ms run,  649.49 ms python,    0.23 ms CL, 1196.44 loss, 0.000086 …
```
> dataset loading speed: Inline imports

- test/models/test_real_world.py
- tinygrad/codegen/search.py
Should pass any valid val_vars when kopting. For kernels like that, uninitialized start_pos causes mem error (cuda + hip suffer, gpu seems defaulting to 0, so it works in CI)
```
__global__ void E_8_32_4(float* data0, const float* data1, const float* data2, const int start_pos) {
int gidx0 = blockIdx.x; /* 8 */
int lidx1 = threadIdx.x; /* 32 */
float4 val0 = (float4)(*((float4*)(data1+(gidx0*128)+(lidx1*4))));
float val1 = data2[start_pos];
*((float4*)(data0+(gidx0*128)+(lidx1*4))) = (float4)make_float4((1.0f-(((val0).x<val1)+(val1<(val0).x))),(1.0f-(((val0).y<val1)+(val1<(val0).y))),(1.0f-(((val0).z<val1)+(val1<(val0).z))),(1.0f-(((val0).w<val1)+(val1<(val0).w))));
}
```
> add var_vals to kopt with symbolic

- examples/whisper.py
Without this cast, I am getting the following error when running whisper.py on METAL - please let me know if there's a better way to fix this (or if it's not broken for everyone else).
```
File "/Users/mmmkkaaayy/workspaces/tinygrad/examples/whisper.py", line 232, in <module>
dec = enc.decode(lst)
^^^^^^^^^^^^^^^
File "/opt/homebrew/lib/python3.11/site-packages/tiktoken/core.py", line 254, in decode
return self._core_bpe.decode_bytes(tokens).decode("utf-8", errors=errors)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument 'tokens': only integer scalar arrays can be converted to a scalar index
```
`print(lst)` before the fix yields `[50257, array(50361., dtype=float32)]`
> whisper: cast model output token to int32

- examples/llama.py
very fast 15 sec per token :)
```
CPU=1 python3 examples/llama.py --temperature=0 --count=10 --prompt="Hello." --timing
using CPU backend
using LLaMA-7B model
ram used: 13.48 GB, freqs_cis                                         : 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 292/292 [00:00<00:00, 8349.61it/s]
loaded weights in 43.22 ms, 13.48 GB loaded at 311.85 GB/s
Hello.
ran model in 17725.62 ms
total 17726.15 ms, 0.06 tok/sec
I
ran model in 16049.01 ms
total 16049.51 ms, 0.06 tok/sec
'
ran model in 14948.75 ms
total 14949.35 ms, 0.07 tok/sec
m
ran model in 15054.05 ms
total 15054.49 ms, 0.07 tok/sec
a
ran model in 14926.72 ms
total 14927.12 ms, 0.07 tok/sec
ran model in 15016.93 ms
total 15017.35 ms, 0.07 tok/sec
2
ran model …
```
> llama default to JIT only if device supports JIT

- tinygrad/codegen/linearizer.py
- tinygrad/renderer/cstyle.py
- tinygrad/renderer/llvmir.py
- tinygrad/renderer/wgsl.py
example output from `CLANG=1 DEBUG=4 python -m pytest -rA test/test_symbolic_ops.py -k test_add`
master
```
void E_s0(float* restrict data0, const float* restrict data1, const float* restrict data2, const int i) {
for (int ridx0 = 0; ridx0 <= ((i*3)+(-1)); ++ridx0) {
float val0 = data1[ridx0];
float val1 = data2[ridx0];
data0[ridx0] = (val0+val1);
}
}
void E_3(float* restrict data0, const float* restrict data1) {
for (int ridx0 = 0; ridx0 <= 2; ++ridx0) {
float val0 = data1[ridx0];
data0[ridx0] = val0;
}
}
```
this PR
```
void E_s0(float* restrict data0, const float* restrict data1, const float* restrict data2, const int i) {
for (int ridx0 = 0; ridx0 < (i*3); ++ridx0) {
float val0 = data1[ridx0];
float val1 = data2[ridx0];
data0[ridx0] = (val0+val1);
}
}
void E_3(float* restrict data0, …
```
> use "<" instead of "<=" in codegen for loop

- test/unit/test_disk_tensor.py
- tinygrad/tensor.py
This refactors existing disktensor movement ops tests and adds new ones for `reshape`
> Refactor and add more unit tests for disktensors

- examples/stable_diffusion.py
When running `examples/stable_diffusion.py` on `WEBGPU` an error is thrown because the output cannot be casted to `uint8`, since it is not supported on `WEBGPU`.
To solve this, I `numpy` cast if on webgpu, `Tensor` cast otherwise.
> Fix stable diffusion output error on WebGPU

- tinygrad/renderer/metal.py
- tinygrad/renderer/opencl.py
- tinygrad/runtime/ops_gpu.py
- tinygrad/runtime/ops_metal.py
the immediate use-case is for rendering the bitcast op. OpenCL and Metal have different utilities for doing bitcast safely. The raw C implementation doesn't work on their compiler safety checks:
```
program_source:8:32: error: address of vector element requested
*(data0+3) = (*((device int*)&((val0).w)));
```
_(even though we know it's safe when we upcast)_
Other C-based backends didn't have this issue.
> Refactor GPU and Metal langauges in their own separate renderers

- test/unit/test_symbolic.py
- tinygrad/shape/symbolic.py
I realized we have not covered this rule, also this removed some of the conditional loads in IMAGE=2 tests but did not effect openpilot. 
This rule is mostly triggered in IMAGE
> ModNode __mod__ rule

- tinygrad/runtime/ops_hip.py
Hip also warns like CUDA
```
/tmp/comgr-020f91/input/r_13_512_32_8_2_4:34:6: warning: 'shared' attribute ignored when parsing type [-Wignored-attributes]
*((__shared__ float2*)(temp+(lidx1*64)+(lidx2*2))) = (float2)acc0;
^~~~~~~~~~
/long_pathname_so_that_rpms_can_package_the_debug_info/src/out/ubuntu-22.04/22.04/build/hip-on-rocclr/hipamd/src/hiprtc/hip_rtc_gen/hipRTC_header.h:15:35: note: expanded from macro '__shared__'
#define __shared__ __attribute__((shared))
^~~~~~
/tmp/comgr-020f91/input/r_13_512_32_8_2_4:38:31: warning: 'shared' attribute ignored when parsing type [-Wignored-attributes]
float2 val5 = (float2)(*((__shared__ float2*)(temp+(lidx1*64)+(ridx1*2))));
^~~~~~~~~~
/long_pathname_so_that_rpms_can_package_the_debug_info/src/out/ubuntu-22.04/22.04/build/hip-on-rocclr/hipamd/sr …
```
> mute hip warnings

- extra/export_model.py
We're creating wrong sized `Float32Array`s during webgpu model export. We use the buffer size for the `Float32Array` size when reading the inference output, although we only need 1/4 of that size.
In the efficient net compilation example for 1000 output classes we had a 4000-sized f32 array:
Should be:
> Fix output size in WebGPU model export

- setup.py
- tinygrad/renderer/triton.py
This removed the ugly `tl.where(...)` from all scalar definitions
> Improve triton generated code quality

- .github/workflows/test.yml
- extra/optimization/test_beam_search.py
- tinygrad/ops.py
llama 20 tok/s -> 22 tok/s
should be able to do search with variable shape, will do separately
> exclude ast with variables from beam search

- test/test_randomness.py
- tinygrad/tensor.py
`scaled_uniform` feels similar to `glorot_uniform` and we use it for init some layers, so I keep the range to [-1, 1].
also refactored the unit tests to reuse the same `equal_distribution` for all tests
> Tensor.uniform set default to standard uniform

- tinygrad/runtime/ops_cuda.py
Support for cudagraph. CUDAGraph will run if PyCUDA has the CudaGraph API; otherwise, the regular BatchExecutor will be used
For now I decided to go [with fork](https://github.com/nimlgen/pycuda/tree/dev.cg2) if this is fine for merging, the API should not change a lot from what I have now. Will get it merge, it's just taking a lot of time on communication.
> init cudagraph

- examples/gpt2.py
- tinygrad/features/search.py
Made slight modifications to the search space, so Beam=12 gets kernels to achieve ~3ms execution time for gpt2. 
In theory, with CudaGraph we should get <5ms on 13900k+3090 (don't have any machine to check this). On the og tiny, I managed to achieve sub 5ms as well applying more CPU-related optimizations (caching sym_infer + asserts in jit.py). However, I'm sure about the cleanliness of these changes, so I focused on achieving the sub 5ms on the 13900k.
I would greatly appreciate it if you could run a test on the 13900k.
> beam=12 makes gpt2 gpu-time < 5ms on 3090

- examples/llama.py
When pointed at a .index.json file it tries to recurse with a pathlib.Path when it needs a str:
```
File "/home/spinlock/src/tinygrad/tinygrad/examples/llama.py", line 259, in <dictcomp>                                        
parts = {n: load(Path(fn).parent / Path(n).name) for n in set(weight_map.values())}                                         
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                            
File "/home/spinlock/src/tinygrad/tinygrad/examples/llama.py", line 257, in load                                              
if fn.endswith('.index.json'):                       
^^^^^^^^^^^                                                                                                              
AttributeError: 'PosixPath' …
```
> Fix llama .index.json loading

- test/test_linearizer.py
- tinygrad/codegen/optimizer.py
- tinygrad/features/search.py
Now that tensor cores only use LASTLOCAL, we can simplify to use only that op everywhere.
The only use of GROUP is in matvec hand-coded opts and it doesn't make a performance difference so switching to use only the top behavior.
Also adds additional asserts to prevent tensor core dims from being altered which causes bad kernels to be generated.
> optimizer: simplify GROUP and LOCAL to have one of each

- examples/llama.py
this contains the same `repeat_kv` fix in #2170, i have verified the fix works with 34B codellama models which use `n_kv_heads`. Also tested all 9 codellama models and fixed some param errors.
> fix codellama params and repeat_kv

- tinygrad/codegen/linearizer.py
It got removed [here](https://github.com/tinygrad/tinygrad/pull/1723/files), and I added back during the webgpu stable diffusion [port](https://github.com/tinygrad/tinygrad/pull/1370#discussion_r1362754621) only on webgpu, but it can be used anywhere else, so we're adding it back.
> Reenable limit_dims_to_max

- test/unit/test_disk_cache.py
there can be race with multiple workers modifying the same table, can have some errors locally with `GPU=1 python -m pytest -n=10 test/unit/test_disk_cache.py`
fixed by assigning unique table name for each test
> use unique table name for each disk_cache test

- test/test_dtype.py
- tinygrad/renderer/llvmir.py
This cast in master:
```py
Tensor([1,2,3,4], dtype=dtypes.int32, device="LLVM").cast(dtypes.bool) # or any other int
```
returns:
```
[ True False  True False]
```
this PR fixes it by using a compare instead of a cast.
The test case added here only supports the new line in llvmir.
I'm writing a more comprehensive test suite for casting in #2156. Ran these changes through every casting combination in that PR as well
> Fix llvm int->bool cast

- tinygrad/runtime/ops_hip.py
When 'C' is applied to the array, we might get a pointer to freed memory.
Numpy comment on `.data`:
```
Note that unlike ``data_as``, a reference will not be kept to the array:
code like ``ctypes.c_void_p((a + b).ctypes.data)`` will result in a
pointer to a deallocated array, and should be spelt
``(a + b).ctypes.data_as(ctypes.c_void_p)``
```
Segfault:
```
#0  __memmove_avx_unaligned () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:222
#1  0x00007fff42909a6e in ?? () from /opt/rocm-5.7.0/lib/libamdhip64.so
#2  0x00007fff4290be87 in ?? () from /opt/rocm-5.7.0/lib/libamdhip64.so
#3  0x00007fff4290c275 in ?? () from /opt/rocm-5.7.0/lib/libamdhip64.so
#4  0x00007fff428d5f45 in ?? () from /opt/rocm-5.7.0/lib/libamdhip64.so
#5  0x00007fff4289ede4 in ?? () from …
```
> fix hip segfault

- test/test_ops.py
- tinygrad/helpers.py
- tinygrad/ops.py
- tinygrad/renderer/cstyle.py
even with NOOPT, we need `required_optimizations` to set up shape for image dtypes
> fix IMAGE=2 failed with NOOPT=1

- test/test_jit.py
- tinygrad/runtime/lib.py
Fixes a problem when jit overwrites the same buffer for backends which use mmaped buffer. This now makes a copy when .toCPU() is called, so several different numpy buffers do not share the same memory.
> Fix mmaped in jit

- examples/hlb_cifar10.py
- extra/dist/collectives.py
- extra/dist/world.py
- test/external/dist/test_collectives.py
- test/external/dist/test_world.py
- tinygrad/runtime/ops_shm.py
Before HIP multigpu, this was used to make shm faster by caching the shared memory allocations. But really that shouldn't be an issue since JIT should be caching them anyways.
This really just became a terribly ugly hack that got everywhere with multigpu.
> remove cache_id

- tinygrad/helpers.py
Fixed #2229.
Trying the sample code from the front page:
```python
from tinygrad.tensor import Tensor
x = Tensor.eye(3, requires_grad=True)
y = Tensor([[2.0,0,-2.0]], requires_grad=True)
z = y.matmul(x).sum()
z.backward()
print(x.grad.numpy())  # dz/dx
print(y.grad.numpy())  # dz/dy
```
fails on Windows with this exception:
```python
File "hello.py", line 8, in <module>
File "tinygrad\tensor.py", line 126, in numpy
File "tinygrad\tensor.py", line 105, in realize
File "tinygrad\realize.py", line 27, in run_schedule
File "tinygrad\ops.py", line 292, in exec_ast
File "tinygrad\ops.py", line 289, in get_program
File "tinygrad\ops.py", line 239, in to_program
File "tinygrad\ops.py", line 193, in build
File "tinygrad\helpers.py", line 212, in wrapper
File …
```
> fix sqlite cache path on Windows

- README.md
this has been broken for a while and upstream wants to deprecate it anyways.
> remove tokei badge from readme

- test/test_dtype.py
- tinygrad/runtime/ops_torch.py
I had mistakenly used `size` instead of `itemsize` for upcasts, fixed here + asserts the upcast/downcast result dtype based on `priority` + one more test for same size ops
> fix ops tests in test_dtype

- test/external/fuzz_linearizer.py
- test/test_linearizer_failures.py
use fixed Linearizer and Opts in the `test_linearizer_failures` so we know the failed cases are fixed, not swapped with other opts due to a fuzzer change. running tests is faster too because it does not test all the fuzzed path
> explicit opts for test_linearizer_failures

- test/test_ops.py
- tinygrad/tensor.py
this +1 line but i think it's cleaner. the old way also created the second mlops.Pad for the value even if arg is no-op
> fix pad None will value

- extra/onnx_ops.py
- test/external/external_test_onnx_backend.py
the onnx documentation is confusing as 💩 for ConvTranspose
> fixed Onnx test: test_convtranspose_autopad_same_cpu 

- tinygrad/helpers.py
[883679b31e35969afc622a3f7922491fda18e8d8 ](https://github.com/tinygrad/tinygrad/pull/2306/commits/883679b31e35969afc622a3f7922491fda18e8d8) already did some of this, this PR expands on it.
I read through the JAX and numpy design docs to see how they do it.
The final changes make sure:
1. bool gets promoted to int8
2. bfloat16 and float16 have the same priority
The difference with numpy's is that they promote uint+int ops to an int one level higher to avoid data loss in negative numbers:
```
(np.uint16(1) + np.int16(1)).dtype # dtype('int32')
```
If we also wanna do this then it'd probably require some more logic than [`max(dtypes)` ](https://github.com/tinygrad/tinygrad/blob/master/tinygrad/lazy.py#L217)
> dtype promotion priorities

- tinygrad/runtime/ops_metal.py
according the [metal feature set table](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf) indirect command buffers are supported on selected apple devices. 
you only need to check the lowest family supporting ICBs along with `argumentBuffersSupport`
> Add Metal device check for ICB support

- extra/optimization/helpers.py
- extra/to_movement_ops.py
the old one always returns True when the len(views) are different. replaced with a symbolic check, only 2 sts need brute force check and the space is small.
> Simpler mops verify

- test/models/test_real_world.py
not really fixing the test, but running `python -m pytest -rA test/models/test_real_world.py` locally does not break now.
> fix test_real_world llama

- test/test_allocators.py
- tinygrad/runtime/lib.py
- tinygrad/runtime/ops_metal.py
- If the aging buffers queue is emptied, ensure_has_free_space() may return without ensuring space_to_free is available.
- [Metal buffers](https://developer.apple.com/documentation/metal/mtldevice/1433375-newbufferwithlength) have a max length and may return None on allocation failures. Error immediately if the max is exceeded or None is returned.
Not catching these can cause hard to track downstream issues.
> Assert for memory allocation failures

- tinygrad/runtime/ops_hip.py
* Free events.
* Speed up cputime when no hipgraph (19ms->12ms gpt2) + less lines. Creating structure types every call is really expansive.
> hip free event + a bit faster cpu time

- tinygrad/runtime/ops_disk.py
AttributeError: 'PosixPath' object has no attribute 'startswith'
> fix shm path test on macos

- examples/whisper.py
- test/models/test_whisper.py
- test/test_jit.py
@mmmkkaaayy can you verify if +1-1 is still needed? would like to remove this hack. i run the whisper locally and the tests also passed
i think the test case you put is bugged due to the optional input `cache_v`, and having jitted and non-jitted function to mutate the state based on different input. i also had some issues in llama chatbot mode. if i always put `cache_v` the issue disappear
btw the whisper code is pretty clean and good job getting symbolic kvcache jit worked!
> remove whisper +1-1 hack

- tinygrad/jit.py
#2288 broke hip multigpu, didn't notice till now, really need tests on hip multigpu but not really sure how to go about it.
This was in the original cachecollector and isn't in the new one, but its kinda needed because stuff that isn't an astrunner like the functions multigpu injects shouldn't have optimized buffers.
> don't optimize buffers when its not an astrunner

- extra/assembly/assembly.py
- extra/assembly/assembly_rdna.py
- test/test_linearizer.py
- tinygrad/codegen/linearizer.py
- tinygrad/helpers.py
- tinygrad/renderer/cstyle.py
This is a conceptual refactor of how vectorized and scalar dtypes work.
In the current way of dealing with vectorized dtypes:
- There's no clean way to relate `float4` and `float`
- Requires manual defining and duplicating the same priority and sizes
- Has led to duplicates in `render_cast`
This also helps with a cleaner implementation of non-fp32 math
> dtypes.float.vec(sz)

- extra/autopad.py
- extra/optimization/test_beam_search.py
- test/external/external_test_onnx_backend.py
- test/test_linearizer.py
- tinygrad/codegen/kernel.py
- tinygrad/codegen/linearizer.py
- tinygrad/features/search.py
- tinygrad/helpers.py
- tinygrad/ops.py
- tinygrad/renderer/cstyle.py
- tinygrad/renderer/llvmir.py
- tinygrad/renderer/triton.py
17^3 @ 17^3 now can be optimized, 3 PADTO then handcodeopt, 16s -> 0.6s
checked with fuzzer and both the loop pushing and applying PADTO look good
(1) MAX does not work with padding output shapetracker 0 as it needs -inf as the padding value
(2) if the network has an in-place assign, PADTO would break the assign
we also need a different search strategy, PADTO is good because we can follow up with a LOCAL or GROUP, but BEAM would not pick it because PADTO by itself is slower
> autopad shapetracker for BEAM

- README.md
I am not sure whether Triton should/will be removed all together after https://github.com/tinygrad/tinygrad/pull/2396, but till then fix link.
> Fix Triton README broken link

- tinygrad/codegen/linearizer.py
i think there was a scatter when the Tokens were around. with UOps it's just a linear pass so we can remove the index scatter and just build the ret list directly
> clean up ast_parse

- test/test_tensor.py
- tinygrad/tensor.py
The causal mask being generated in the `scaled_dot_product_attention` function in `tensor.py` was slightly wrong.
Running the following:
```python
x = Tensor.ones(1,1,4,4)
Tensor.scaled_dot_product_attention(x, x, x, is_causal=True)
```
With this line added after 783 in the function:
```python
if attn_mask is not None: print(attn_mask.numpy())
```
Would print the following:
```
[[  1. -inf -inf -inf]
[  1.   1. -inf -inf]
[  1.   1.   1. -inf]
[  1.   1.   1.   1.]]
```
Which is not correct, the following is what the mask should look like:
```
[[  0. -inf -inf -inf]
[  0.   0. -inf -inf]
[  0.   0.   0. -inf]
[  0.   0.   0.   0.]]
```
Since the mask addition is always following by a softmax, this "off by 1" is not that big of a deal
```python
>>> x = Tensor.randn(4,4)
>>> (x.softmax() - …
```
> fix causal mask in Tensor class

- .github/workflows/test.yml
- tinygrad/runtime/ops_gpu.py
My laptop has an Intel APU and during debugging with the "GPU" backend when I use `DEBUG >=5` I get the error
```python
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 17: invalid start byte
```
This is caused in ops_gpu.py in `CLProgram` by `print(prg.decode('utf-8'))`.
I added a basic test that causes this error on the CI. As a suggested fix this PR prints it only if the device name contains "NVIDIA".
> Fix UnicodeDecodeError when debugging on Intel APU

- test/test_linearizer_failures.py
clean this up to prepare for the debug bounty
not sure why CUDA CI timed out, works on real CUDA
> test_linearizer_failures to run on all backends

- tinygrad/tensor.py
Adds the '[override]' error code to the type ignores for '=' and '!='.  This means that mypy will only ignore that specific error code, so it can catch other type errors involving these operators.  
This also seems to be the best practice regarding overriding the return type for equality operators according to this thread: https://github.com/python/mypy/issues/2783
> Add [override] error code to type: ignore in tensor.py

- test/unit/test_symbolic.py
- tinygrad/shape/symbolic.py
SumNode.\_\_lt\_\_ currently has an ill-typed call to math.gcd, sending a (Node | int) to the function which requires an int.   This PR fixes this by checking to see if the argument is an int.  If it is an int, the behavior is the same.  If it is not an int, the gcd is set to 1, so which results in the code not performing an optional reduction of both sides of the inequality.  It also includes a test case which reproduces the error in the old code.
It might also be worth writing a gcd function in the Node class so that more reductions are possible.  This would also affect similar code in SumNode.\_\_floor\_div\_\_
> Add isinstance check before gcd call in SumNode.__lt__

- test/external/external_model_benchmark.py
If you run `python3 test/external/external_model_benchmark.py` vs `MODEL="openpilot" python3 test/external/external_model_benchmark.py` and print out what the `np_inputs` dict's data is, it's different because of how torch.randn behaves when it's called more than once.
I think it's better to have this be a reproducible output no matter how we run the benchmark test.
> Reproducible model benchmark output

- test/unit/test_symbolic.py
- tinygrad/shape/symbolic.py
Modding out a variable whose bounds are nodes can lead to nonsense values since inequalities involving nested nodes are not reliable.  This rules out one path for getting nonsense values.
> Add assertion to prevent nonsense mod values

- test/helpers.py
- test/test_jit.py
- test/test_symbolic_jit.py
- tinygrad/jit.py
* Assertions for `len(jit_cache) == 1` were trivially passing when using the graph executor
* Graph executor test cases were not asserting the len of `graph.prg.jit_cache`
* Using `getattr(Device[Device.DEFAULT], "graph", None)` was bypassing assertions for Metal CI where the `graph` attr exists but the JIT is not using the graph executor because of lack of indirect command buffer support.
> improve test assertions for jit cache len with graph executor

- test/unit/test_symbolic.py
- tinygrad/shape/symbolic.py
#2474 breaks BEAM search gpt2, non-simplifiable mod should return a ModNode instead of AssertionError
> non-simplifiable mod should result in ModNode

- examples/gpt2.py
on M1 Max 47ms -> 35ms per batch. with the same seed, the output is still coherent but different
generating the 100th batch with max size 1024 and beam=12
`JIT=1 PYTHONPATH=. MAX_CONTEXT=1024 BEAM=12 python examples/gpt2.py --count=100 --temperature=0.7 --batch_size=32 --timing --seed=0 --noshow`
`JIT=1 PYTHONPATH=. MAX_CONTEXT=1024 BEAM=12 HALF=1 python examples/gpt2.py --count=100 --temperature=0.7 --batch_size=32 --timing --seed=0 --noshow`
> fp16 in gpt2 attention

- .github/workflows/test.yml
- test/test_ops.py
Investigating `Get all passing Metal tests in CI` bounty.
Tried to repro failing tests by running in CI without skips and all tests passed.
After some investigation it appears that the main issue was failing tests `test_half_to_int8` which were changed in #1306.
As for `test_ops.py`, it is not clear as to why each was failing and I am unable to reproduce (in pipeline or on apple silicon mac). Perhaps the runners have moved to using intel to apple silicon, but I can only speculate here. Not sure if further investigation is needed here.
> Removing METAL Skips as CI works

- extra/onnx_ops.py
Directly casting is deprecated and will error in the future.
> Fix: Get item from ndarray before casting to int in onnx Range

- tinygrad/renderer/llvmir.py
We could get away with not casting DEFINE_ACC's arg because it was always a float. Now this renderer works like cstyle
https://github.com/tinygrad/tinygrad/blob/7fec966b5ec66efdc7dfcd4b0f0f3a99a866c503/tinygrad/renderer/cstyle.py#L55
> Refactor llvm const renders

- test/unit/test_shapetracker.py
- tinygrad/shape/shapetracker.py
also changed the behavior that leading 1s are always pushed to the latest possible index
> simpler get_contraction

- test/test_ops.py
- tinygrad/shape/shapetracker.py
- tinygrad/shape/view.py
An alternative to PR #2298 to fix all the issues mentioned in #2177 and #2194.
Explanation of the changes:
1. In `View.__unsafe_resize` I clip the nmask to be between 0 and the new_shape, because otherwise for example `Tensor([1,2]).pad(((3,0),))[0:2]` would have `mask=((3,2),)`, and then in `ShapeTracker.to_movement_ops` it would calculate a negative real_shape and also would want to pad by 3, but that is wrong since the final result has only 2 zeros.
2. In `ShapeTracker.to_movement_ops` I check if the real_shape contains zero and there is a mask, which would happen if we shrink to elements outside the base buffer (created by padding), so in this case I set the real_offset to be zero to not go outside the base buffer and get an error.
3. In `View.reshape` I return None if the new_shape …
> New fix accessing elements created by padding

- tinygrad/renderer/llvmir.py
This didn't break any tests because there's no ALU op done in ints right now. With non-fp32 ALUs, regressions pop up
> Int ops shouldn't have a fast math flag

- tinygrad/lazy.py
probably remove optype and all the double check of x.op.op next, then clean up the middle part logics. the root tracing and reordering stuff can be simpler
> minor lazy tweak before rewrite

- tinygrad/features/graph/metal.py
The 2nd useResource discards everything from the first. Visible in metal gputrace dependency graph + docs says the same:
> Calling this method again, or calling [useHeap:](https://developer.apple.com/documentation/metal/mtlcomputecommandencoder/2866530-useheap?language=objc), overwrites any previously specified usage options for future dispatch calls within the same compute command encoder.
> set useResources once in metal graph

- tinygrad/shape/view.py
Fix #2614
view=View(shape=(2, 1920, 32, 32), strides=(1310720, 1024, 32, 1), offset=0, mask=((0, 2), (0, 1280), (0, 32), (0, 32)), contiguous=False), new_shape=(2, 32, 240, 256)
returns None
> fix for false merge

- .github/workflows/test.yml
- test/test_ops.py
- tinygrad/renderer/cstyle.py
Tests were previously failing due to:
- `dtypes.int64` not supported on webgpu: `test_div`, `test_maximum` and `test_div_int` were failing, because the `vals` array's values were implicitly` int64`, I'm forcing `int32` now with `np.array`
- `bool` not HOST_SHAREABLE: bool cmp tests were failing, because bool storage buffers are not allowed in WebGPU (https://www.w3.org/TR/WGSL/#host-shareable-types)
- 8-buffer per kernel: this limit has already been bypassed by [this hack](https://github.com/tinygrad/tinygrad/blob/0978c24b8e2db85e5eddec1945934b5dd3d3334b/tinygrad/lazy.py#L254), so it's safe to remove the skip from the tests that were failing due to this
- `inf`: `test_pad` inf tests were failing, because the previous `inf` `(0x1.fffffep+127f`) didn't come back as `inf` to cpu, `(1.0/0.0)` …
> Get all WEBGPU test_ops passing

- examples/gpt2.py
- test/test_symbolic_shapetracker.py
- tinygrad/shape/shapetracker.py
- tinygrad/shape/view.py
2.86ms -> 2.65ms (on 3080). 518 kernels -> 470 kernels
found an issue with reshaping with a symbolic mask, will merge this once i have a regression test for it
> use one kvcache tensor in gpt2 instead of two separate caches

- examples/llama.py
- extra/models/llama.py
Transformer class has a jit param so we should use that in the caller
> move llama getenv("JIT") from models to examples

- setup.py
to repro, try installing tinygrad master and `import tinygrad.features.graph`
i think it was broken even before this https://github.com/tinygrad/tinygrad/commit/3128da832d5ad14ef2dd7aff48581fc966d7c8d9 because runtime.graph didnt exist in setup.py
> add tinygrad.features.graph to packages

- .github/workflows/test.yml
- test/test_linearizer.py
- test/test_linearizer_failures.py
- test/test_nn.py
- test/test_symbolic_ops.py
- test/test_uops.py
- tinygrad/renderer/cstyle.py
- tinygrad/runtime/ops_webgpu.py
- support `vals` using uniforms, test_symbolic passes
- brought back `render_store` because the explicit cast is needed in some cases (example: assigning a cmplt bool result to a i32 output buffer)
> support vals on WebGPU, run more tests

- test/imported/test_indexing.py
- test/test_ops.py
- tinygrad/tensor.py
This PR does mainly formatting
- 2 spaces
- translated torch code to tinygrad code (some torch functions are left as TODOs up top)
- annotated still disabled tests using TODO and triple quotation
- enabled easy to enable tests that don't require much review
- snuck 1 very simple `IndexError("slice() cannot be applied to a 0-dim tensor.")` test in
current total enabled tests: 24
-----
after this is merged, I'll start enabling more of these disabled tests
I already done some on other branches
> Formatted test_indexing

- extra/to_movement_ops.py
at the end of extra/to_movement_ops, go through all mops and remove the ones that are effectively noop (only shallow check that ShapeTracker remained exactly the same)
reduced average returned len(mops) from 8.44 to 4.41
> remove noop from extra/to_movement_ops

- extra/to_movement_ops.py
improved version of #2693, instead of checking one step no-op, keep all previously seen shapetracker and cut the solution short if a series of movements are effectively no-op. reduced average returned length 4.41->4.38
> slightly better extra/to_movement_ops dedups

- test/test_ops.py
- tinygrad/tensor.py
Closes #2665. Is this desired in core? Seems appropriate to me, but it doesn't take self, so if LOC is a problem, could be in extra.
> Implement einsum

- test/test_dtype.py
- tinygrad/helpers.py
- tinygrad/renderer/cstyle.py
1. dtypes.is_dtype should always check the scalar version
this caused a regression in rendering vectorized int constants. we should figure out why CI was green.
example kernel diff for `TestOps.test_simple_padding_conv2d`
```diff
__kernel void r_4_4_4_3(write_only image2d_t data0, read_only image2d_t data1, read_only image2d_t data2) {
const sampler_t smp = CLK_NORMALIZED_COORDS_FALSE | CLK_ADDRESS_CLAMP | CLK_FILTER_NEAREST;
int lidx0 = get_local_id(0); /* 4 */
float4 acc0 = (float4)(0.0f,0.0f,0.0f,0.0f);
float4 acc1 = (float4)(0.0f,0.0f,0.0f,0.0f);
float4 acc2 = (float4)(0.0f,0.0f,0.0f,0.0f);
float4 val0 = read_imagef(data1, smp, (int2)((lidx0+(-1)),0));
-   float4 val1 = read_imagef(data2, smp, (int2)(false,false));
+   float4 val1 = read_imagef(data2, smp, (int2)(0,0));
float4 val2 = …
```
> fix dtypes helpers for integers

- test/unit/test_disk_tensor.py
- tinygrad/nn/state.py
Saving tensors of certain types (e.g. doubles, bools, shorts) currently fails. I have added a unit test to show that they fail. Adding the missing dtypes to `safe_dtypes` enables the unit test to run successfully. 
Please note that there may be a very good reason that `safe_dtypes` did not already include the dtypes that I added. Please let me know if that is so. The unit test does assert that the saved and loaded tensors are the same, but maybe I am missing something else.
Please feel free to suggest any modifications.
> Extend available types for `safe_save`

- test/external/external_model_benchmark.py
onnx is remapping the models, old ones are in archive/
> update onnx benchmark urls

- test/test_dtype.py
- tinygrad/helpers.py
- tinygrad/mlops.py
do unary first and gradually adjust the type promotion. if any of the input type is a image, it returns that image similar to how current priority 100 works.
some unary function requires binary input type alignment so left for the next pr
> some unary functions cast int input into float

- test/test_ops.py
- test/test_schedule.py
- tinygrad/tensor.py
replaced `x ** Tensor(0)` with `mlops.Zero.apply(self)+1`
the resulted ast has one more layer of `CONST ConstBuffer(1) + CONST ConstBuffer(0)` because we do const folding at lower layer. the generated kernels are the same for `pow(Tensor(2))` and a lot simpler for `pow(Tensor(0))`
> simpler Tensor.pow to integer

- tinygrad/tensor.py
relevant kernel for `Tensor([1,2,3,4,5,6])[Tensor([1,2,3,4,-1,-2,-3], dtype=dtypes.int32)].numpy()`
master:
this pr:
@geohotstan fyi
> simplify fancy index with negative Tensor entries

- test/test_ops.py
broke something in advanced indexing when trying to convert `__lt__` and friends to return in dtypes.bool.
> more test cases in test_slice_fancy_indexing_with_idx

- tinygrad/device.py
This fixes annoying double exception on allocation failure or even sometimes on ^C:
```
[...]
File "/home/sobomax/projects/tinygrad/tinygrad/device.py", line 70, in __init__
self._buf = opaque if opaque is not None else self.allocator.alloc(dtype if isinstance(dtype, ImageDType) else size * dtype.itemsize)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[...]
File "/home/sobomax/projects/tinygrad/tinygrad/runtime/ops_cuda.py", line 18, in check
if status != 0: raise RuntimeError(f"CUDA Error {status}, {ctypes.string_at(init_c_var(ctypes.POINTER(ctypes.c_char)(), lambda x: cuda.cuGetErrorString(status, ctypes.byref(x)))).decode()}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```
> Fix double exception in __del__() when __init__() raises exception.

- tinygrad/renderer/cstyle.py
- tinygrad/runtime/ops_clang.py
it's the same `const int` for clang, opencl, cuda and hip. metal overwrites with `constant int&` and webgl has its own thing
> set default str for CStyleLanguage.arg_int_prefix

- examples/compile_tensorflow.py
Just cleaning up this example which has been broken for a while.
`export_model()` doesn't quite work for this example I didn't see a really clean way of merging the needs of compile_efficientnet.py vs compile_tensorflow.py.  There are two things I'm doing in response to the current version I feel are a little hacky.
1) run_onnx != model - I didn't see an example of using an onnx model as a first class Tinygrad model.  So I make a dumb little class TinyOnnx as a hack.
2) runtime model loading - One of the goals here is to be able to load weight at runtime, but the default is to embedded them into the sourcecode.  I just don't pass `bufs_to_save` to `export_model_clang()` which works for me.
I don't see any other users that would have similar needs so I think these hacks are probably okay. …
> updating to work with new internal apis

- test/test_hip_rdna3.py
> restore Tensor.default_type in test_hip_rdna3

- extra/assembly/assembly.py
- extra/triton/triton.py
- test/test_uops.py
- tinygrad/codegen/linearizer.py
- tinygrad/renderer/cstyle.py
- tinygrad/renderer/llvmir.py
now DEFINE_GLOBAL uop.arg[1] is always the same as uop.dtype, we can remove the one in arg and just use uop.dtype
> remove duplicated  dtype in DEFINE_GLOBAL args

- test/test_linearizer.py
cleans up the skips for running linearizer in compiled backends only
> test_linearizer cleanup

- test/test_dtype.py
- test/test_dtype_alu.py
- tinygrad/helpers.py
- tinygrad/lazy.py
- tinygrad/mlops.py
follow-up on #2740
these unary functions are supported for the half dtype, we shouldn't cast them to float.
here vs master:
```diff
kernel void E_2(device half* data0, const device half* data1, uint3 gid [[threadgroup_position_in_grid]], uint3 lid [[thread_position_in_threadgroup]]) {
int gidx0 = gid.x; /* 2 */
half val0 = *(data1+gidx0);
-   *(data0+gidx0) = (log2((float)(val0))*0.6931471805599453f*1.4426950408889634f);
+   *(data0+gidx0) = (log2(val0)*(half)(0.6931471805599453f)*(half)(1.4426950408889634f));
}
```
regression test: `3c6886c1cefe83e3db0af90bc496ae3887195b46`
cc @chenyuxyz
> don't auto-cast half to float in unary functions

- extra/optimization/helpers.py
- test/test_linearizer_failures.py
- test/test_ops.py
- test/test_uops.py
- tinygrad/codegen/linearizer.py
- tinygrad/mlops.py
- tinygrad/renderer/cstyle.py
- tinygrad/renderer/llvmir.py
asserting these in `uop`
`test_uops` now takes different dtypes for each input. removed several implicit cast in renderers. replaced the WEBGPU render hack to always render bool as f32 (we can remove this after broadcasted aligned the output types)
@Qazalin @wpmed92 fyi
> TernaryOps.WHERE has vin[0] as bool and BinaryOps.CMPLT always outputs bool

- test/test_dtype.py
- tinygrad/mlops.py
- tinygrad/ops.py
this is a pretty big change. in `mlops ADD / SUB / MUL / DIV / WHERE`, use `least_upper_dtype` to determine the output type and upcast / downcast the forward / backward pass accordingly. also updated many places that were using `max()` to determine the output type
llama is 20% slower, i think it's due to positional encoding or mask being hard coded in float so we need additional casting. gpt2 does not have this issue. will fix separately
> use least_upper_dtype mlops to upcast the output type in mlops

- test/test_dtype.py
- test/test_tensor.py
- tinygrad/helpers.py
- tinygrad/tensor.py
`Tensor([1,2,3])` now has default `dtype.int`. we can finally do this! @geohotstan fyi
> int / List[int] data -> dtypes.int32

- test/test_dtype.py
- tinygrad/tensor.py
(1/self) is incorrect for int tensor
> rsqrt is self.reciprocal().sqrt()

- tinygrad/runtime/ops_gpu.py
On Windows, the unsigned long type is 32-bit, which is not compatible with the required data size for event profiling.
I remember that Windows is not a first party platform so feel free to close.
Tinygrad blows up with gpu and debug > 1
File "C:\git\tinygrad\tinygrad\runtime\ops_gpu.py", line 54, in __call__
start = init_c_var(ctypes.c_ulong(), lambda x: check(cl.clGetEventProfilingInfo(event, cl.CL_PROFILING_COMMAND_START, ctypes.sizeof(x), ctypes.byref(x), None)))  # noqa: E501
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\git\tinygrad\tinygrad\helpers.py", line 300, in init_c_var
def init_c_var(ctypes_var, creat_cb): return (creat_cb(ctypes_var), ctypes_var)[1] …
> Update CLProgram to use unsigned long long for event profiling

- test/test_dtype.py
- tinygrad/renderer/llvmir.py
- tinygrad/runtime/ops_torch.py
This change add few missing bits and pieces into torch backend type conversion code:
o dtypes.bfloat16 <-> torch.bfloat16
o dtypes.ushort -> torch.int16
o dtypes.uint -> torch.int32
o np.uint32 -> np.int32
This makes coder and hlb_cifar10 working with TORCH=1 OOB.
```
WARNING: not loading freqs_cis
ram used: 14.58 GB, freqs_cis                                         : 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 292/292 [00:02<00:00, 128.03it/s]
loaded weights in 2281.31 ms, 4.54 GB loaded at 1.99 GB/s
weights -> model: 9970.24 ms
<|im_start|> system
You are Quentin. Quentin is a useful assistant who writes Python code to answer questions. He keeps the code as short as possible and …
```
> Make torch backend more usable, fix bfloat support in the llvm backend

- tinygrad/mlops.py
- tinygrad/runtime/ops_cpu.py
- tinygrad/runtime/ops_torch.py
input dtypes are aligned and casted in mlops, no need to match and upcast in interpreted backends
> remove match_type in ops_torch and ops_cpu 

- .github/workflows/test.yml
- extra/introspection.py
- pytest.ini
- test/extra/test_lr_scheduler.py
- test/imported/test_indexing.py
- test/models/test_mnist.py
- test/models/test_onnx.py
- test/models/test_train.py
- test/test_net_speed.py
- test/test_nn.py
- test/test_optim.py
- test/test_speed_v_torch.py
- test/test_zero_copy.py
pytest markers are bad because it's hard to notice tests being skipped without active looking. several tests were skipped in the CI, and one of them was broken.
this pr removed the use of marker. fixed the broken test and skipped some slow and repetitive / redundant ones manually to keep the CI time < 5 minutes.
> Remove pytest markers

- tinygrad/renderer/cstyle.py
input dtypes are aligned before uop level so we don't need functions that handle different input types
> remove cstyle hip functions that deals with different types of input

- test/external/fuzz_shapetracker.py
- test/unit/test_shapetracker_math.py
- tinygrad/shape/shapetracker.py
doesn't fix the reshape bug. there's a really long tail issue even if you disable line 66 in view.
`CNT=1000000000 FUZZ=invert PYTHONPATH="." python3 test/external/fuzz_shapetracker_math.py`
> shapetracker: minor improvements

- test/imported/test_indexing.py
- tinygrad/tensor.py
LLVM still runs and is a lot faster, would be curious to know why. also reworded some error messages and remove error message regex check
@geohotstan feel free to remove the regex check in test_indexing. also i like to write error message in a way that does not introduce new variables and use `{variable=}` if possible
> skip slow test_indexing on METAL

- test/test_symbolic_ops.py
- tinygrad/tensor.py
we can support jittable symbolic shape random with custom rand now, and we can formalize it in the test after threefry is ready
> remove the all_int(shape) check in Tensor._loadop

- test/unit/test_shapetracker.py
- tinygrad/shape/view.py
ad233d557f435 disabled part of `_reshape_mask`, due to the offset computation being wrong. I've removed the offset computation entirely, re-enabled the part, and addressed the offset computation in a different way at the caller of `_reshape_mask`.
> Fix reshape merging with masks

- tinygrad/lazy.py
- tinygrad/mlops.py
- tinygrad/ops.py
- tinygrad/tensor.py
The high-level problem is that we can't define globals with boolean buffers in webgpu. These hacks were first put in both lazy and mlops in #2888 and #2887 to cast the CMPLT output to float. This made it really hard to manage all the issues it caused with the UOps spec PR #2800.
these changes:
- ensure CMPLT is always a bool, we don't need the mlops bool cast
- remove the workaround in lazy asserts for webgpu, CMPLT _is_ still a bool in wgsl.
> Move the webgpu CMPLT hack to one place

- examples/stable_diffusion.py
saw a flaky CI failure with 1.1e-4, and 3e-4 is a good number
> increase stable diffusion validation threshold 1e-4 -> 3e-4

- tinygrad/tensor.py
`Tensor([1, 2, 3]).where(1.2, 2.3)` the first `[1, 2, 3]` can directly cast into bool without casting float (in broadcasted) first
> don't match dtype with first input in where

- test/external/external_model_benchmark.py
not sure what the issue was but seems to be fixed on master
> remove the different rtol / atol for openpilot CUDA in benchmark

- test/test_copy_speed.py
- tinygrad/runtime/ops_disk.py
1. We don't need `try: import _posixshmem` because tinygrad dropped support for windows in [v0.7.0](https://github.com/tinygrad/tinygrad/releases/tag/v0.7.0)
2. python >=3.10 mmap module exposes MAP_POPULATE [issue](https://github.com/python/cpython/issues/84791). After tinygrad switches its minimum version to 3.10 we can remove platform dependant check `0 if OSX else 0x008000`
3. MAP_LOCKED is still not exposed
4. MADV_HUGEPAGE is actually exposed in python >=3.8, so we can just check that attribute from mmap module
5. Leading slash is always prepended [shared_memory.py](https://github.com/python/cpython/blob/main/Lib/multiprocessing/shared_memory.py#L73)
> Disk shm refactor

- test/test_tensor.py
- tinygrad/tensor.py
it's possible for numel 1 tensor lazydata to be unbased and should call lazydata.base.realized
> bugfix Tensor.item when it's unbased

- test/test_randomness.py
- tinygrad/tensor.py
Fixed an issue where Tensor.randint((4,4)) was causing errors due to a missing asterisk (*) in the static method, a bug introduced a week ago. Additionally, updated several other tensor methods related to randomness to align more closely with PyTorch standards and other Tinygrad methods. Tests have been revised to include checks for both 2,3 and *(2,3) shape inputs.
- Added asterisk 
- Updated Randomness tests
Old Version 
```python
In [1]: from tinygrad.tensor import Tensor
In [2]: a = Tensor.randint((4,4))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 a = Tensor.randint((4,4))
File ~/tinygrad/tinygrad/tensor.py:197, in Tensor.randint(low, high, *shape, …
```
> Fixed Tensor.randint() not accepting tuple shapes

- extra/autopad.py
- extra/optimization/test_beam_search.py
- test/test_linearizer.py
- tinygrad/codegen/kernel.py
- tinygrad/features/search.py
the correct condition is that PADTO cannot be applied to reduce axis, not Reduce.MAX in ops. even for Reduce.SUM it's possible that the reduce axis had a div before, and the padded 0 became inf then sum over it is incorrect.
> fix PADTO optimization

- examples/beautiful_mnist.py
the compiler error was due to `error: call to 'max' is ambiguous` when we have max(int, float) in kernel. it was first fixed in 4380ccb1 the non fp32 math PR, and further solidified with dtype refactor
> remove obsolete TODO in beautiful_mnist

- extra/models/llama.py
- tinygrad/codegen/kernel.py
used ellipsis and other higher level tensor function. disabled the half @ half -> half tensor core as it fails uop dtype checks
> cleanup llama apply_rotary_emb and other helpers

- .github/workflows/test.yml
- tinygrad/codegen/kernel.py
- tinygrad/codegen/linearizer.py
correctly enabled TC=2 tensor core op test in CI which was not testing tensor core due to "arm64" check even with TC=2. fixed the broken test by not pushing uop out of loop scope if it has UOps.DEFINE_LOCAL in parents.
also removed some obsolete isinstance checks in tensor core now that LazyOp only has LazyOp in src.
> fix TC=2 tensor core op test

- tinygrad/tensor.py
`.where` does the dtype and shape conversions for 0, no need to use zeros_like
> cleanup Tensor.triu and Tensor.tril

- test/unit/test_helpers.py
- tinygrad/codegen/linearizer.py
- tinygrad/device.py
also matched MULACC criteria between interpreted and compiled (that probably need to be refactored somewhere else)
> remove type check for LazyOp.src now it's always LazyOp

- .github/workflows/benchmark.yml
- examples/hlb_cifar10.py
- test/models/test_real_world.py
when [`OneCycleLR`](https://github.com/tinygrad/tinygrad/blob/ad0d710ec442a34a4b0278f24b27d096d0d34d6b/extra/lr_scheduler.py#L69C65-L69C65) is initialized in fp16, `max_lr / div_factor` resulted a value `1.993e-17` that caused underflow and nan.
> adjsut div factor to avoid underflow for cifar in fp16

- test/unit/test_symbolic.py
- tinygrad/shape/symbolic.py
AndNode produces a Node that min/max is bounded by [0, 1] so `//` on top of that is almost always 0. we don't really use that either
> remove AndNode.__floordiv__ special case

- tinygrad/runtime/ops_disk.py
- tinygrad/runtime/ops_hip.py
Faster on M3 too!
```
diane@blak:~/tinygrad$ sudo purge; python3 examples/llama.py --prompt "Hello." --count 10 --temperature 0 --timing --gen 1
using METAL backend
using LLaMA-7B model
ram used: 13.48 GB, freqs_cis                                         : 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 292/292 [00:02<00:00, 134.56it/s]
loaded weights in 2177.77 ms, 13.48 GB loaded at 6.19 GB/s
```
> make disk simpler

- test/test_dtype.py
corrected dtypes for TORCH and float64 support
> correct (dtype, device) in test_dtype.is_dtype_supported

- test/test_linearizer.py
- tinygrad/codegen/linearizer.py
- tinygrad/device.py
- tinygrad/renderer/llvmir.py
- tinygrad/tensor.py
we previously only upcast uint and int, and half was using half for acc. change to acc in float for precision. but cast the result back to half to match torch/jax output dtype
> use float for acc dtype for half tensor sum

- extra/models/llama.py
without contiguous on keys and values, it runs but the update is incorrect
> hotfix llama conversation mode

- tinygrad/renderer/cstyle.py
earlier encountered this compilation error when loading llama 14B
```
RuntimeError: compile failed: /tmp/comgr-b82ca8/input/<null>:25:37: error: C-style cast from 'float' to '__bf16' is not allowed
__bf16 val0 = (alu1?*(data1+alu0):(__bf16)(0.0f));
```
ironically, I cannot find any header files in hip that defines `__bf16`.
> add bf16 type_map for both cuda and hip

- test/test_nn.py
used Tensor.train decorator, reordered to always tinygrad instances first, and removed redundant idx cast
> clean up test_nn.py

- tinygrad/nn/__init__.py
get rid of the unnecessary check of isinstance int
> use in_features directly in nn.Linear.__init__ bound check

- test/test_ops.py
- tinygrad/tensor.py
supported both 0 in cat axis (for a subset of input), or 0 in non-cat axis (all needs to be 0)
> Tensor.cat with 0 shape tensors

- tinygrad/device.py
- tinygrad/helpers.py
- tinygrad/jit.py
- tinygrad/realize.py
op_estimate can be symbolic, but mem_estimate is always int, thus we don't need to sym_infer it. fixed some long lines too. update_stats is a very big function
> mem_estimate is always int, not symbolic

- .github/workflows/benchmark.yml
BEAM=2 is faster and less search time. investigating why BEAM2+BEAM4 is slower than BEAM2 alone
> use BEAM=2 instead of BEAM=4 in cuda ci gpt2

- test/imported/test_indexing.py
- test/test_lazybuffer.py
- tinygrad/lazy.py
it might be coming from an expand, and resetting st results incorrect stride. caught by interpreted backend
fixes #3094
> bugfix do not reset shapetracker of 0 size lazybuffer

- test/imported/test_indexing.py
- test/test_ops.py
- tinygrad/tensor.py
should always expand into 0, not the other way around. fixed matmul with 0 in input shapes. for forwards for now though, backward is more involved and would need to change 0 size shortcuts
> fix broadcasted logic if there's 0 in shapes

- extra/models/transformer.py
I replaced it with new one_hot tensor op. The _examples/transformer.py_ trains to 0.999 accuracy and **test_transformer** in _test_train.py_ passes.
> one_hot in transformer.py

- test/unit/test_symbolic.py
- tinygrad/shape/symbolic.py
with this, `a:=NumNode(x) == b` implies `hash(a) == hash(b)`
> update NumNode.__hash__ to be hash(self.b)

- tinygrad/runtime/ops_cuda.py
- tinygrad/runtime/ops_hip.py
No exceptions in __del__ when module creation is failed in hip/cuda like in #3016
```
Exception ignored in: <function CUDAProgram.__del__ at 0x7fe3737caaf0>
File "/cache/home/nr620/tinygrad/tinygrad/runtime/ops_cuda.py", line 53, in __del__
if not CUDACPU: check(cuda.cuModuleUnload(self.module))
AttributeError: 'CUDAProgram' object has no attribute 'module'
```
> no exceptions in __del__ when module creation is failed in hip/cuda

- test/test_lazybuffer.py
- test/unit/test_disk_tensor.py
cast implicitly resets shapetracker and makes it contiguous (for disk tensor), which fails for Interpreted backend if inputs contain non-contiguous st.
> failed test case due to cast resets shapetracker

- tinygrad/dtype.py
* directly using `DType` object as keys creates issues while subclassing the dataclass, so used the `name` attribute as key instead.
* added support for `PtrDType` to `DType` comparison. (this was not needed for `NamedTuple`).
> make DType a dataclass

- test/external/external_model_benchmark.py
exceptions can be raised from either model conversion or individual backend failed. openpilot on torch mps works, but does not work with torch cpu. seperate the expcetion block so that the benchmark can inlcude torch mps for openpilot.
> separate try except blocks in onnx2torch in model benchmark

- test/external/fuzz_linearizer.py
- test/test_linearizer_failures.py
Fuzzer now generates random inputs to validate that output matches (before all rawbufs were 0s, so no matter what in most of cases output was 0 as well). Add some additional area for output rawbuf to check for oob writes.
> fuzzer validates outputs + (partially) oob accesses

- test/test_multitensor.py
so that the uneven case is not just with 0 length and can have other positve values
> fuzz length for multitensor reduce test case

- test/test_dtype_alu.py
those should pass now as we have broadcasted before passing to lt and eq. also updated the test skipping criteria to reuse test_dtype.is_dtype_supported
> add operator.lt and operator.eq to test_dtype_alu

- test/test_dtype_alu.py
3f56d1a5e8385b12526899abd120e811033bb313 added `operators.lt` and `operators.eq` to `binary_operations` in test_dtype_alu.py, except for llvm. This broke `METAL=1 python -m pytest -n=auto test/ --ignore=test/external --ignore=test/models --durations=20` on my machine, but for some reason not on CI. Maybe it has somehting to do with the fact that metal in CI is software-emulated.
This PR moves exclusion check earlier (before `integer_binary_operations = binary_operations + [(Tensor.xor, np.bitwise_xor)]`) and adds METAL to exclusion list.
> Fix metal tests broken by 3f56d1a

- test/test_tensor.py
- tinygrad/tensor.py
dtypes are inferred from underlying lazydata, requires_grad needs to be passed explicitly
> shard and to should preserve requires_grad

- extra/backends/ptx.py
- extra/backends/triton.py
- test/test_ops.py
- tinygrad/codegen/linearizer.py
- tinygrad/lazy.py
- tinygrad/renderer/cstyle.py
- tinygrad/renderer/llvmir.py
- tinygrad/runtime/ops_cpu.py
- tinygrad/runtime/ops_torch.py
- tinygrad/tensor.py
```
In [15]: jax.lax.neg(jnp.array(True))
TypeError: neg does not accept dtype bool. Accepted dtypes are subtypes of floating, complexfloating, integer.
In [7]: torch.neg(torch.tensor(True))                                                                                                                                                                                                                                                                       
RuntimeError: Negation, the `-` operator, on a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.   
```
it appears that bool tensors don't `neg`
but our `logical_not` depend on neg when Tensor is bool dtype
and when it's not bool dtype, it doesn't match jax or torch
```
In [10]: …
```
> fix neg logical_not inconsistencies

- extra/onnx_ops.py
The onnx round is a little more involved so it can't directly use the new Tensor.round
but I made the onnx round use the new ideas from Tensor.round
for onnx,
it sometimes considers the val of the breakpoint from rounding up or down
instead of 0.5, it could be 0.3
and it sometimes also considers whether it wants to round up or round down when it's equal to the breakpoint
so 1.5 may round to 2 or 1
There is also an option here to round to the nearest even integer, which is really weird...
> fix _round in onnx_ops to look more like new Tensor.round

- test/test_dtype.py
- test/test_ops.py
- tinygrad/lazy.py
- tinygrad/tensor.py
resolves #3186 
the problem for #3186 is a `where` scalar casting problem it appears
I cross checked jax's casting behavior for `where` and `maximum` with the tests I wrote in `test_dtype` and they do match.
but the changes in `tensor.py` to fix `where` is really ugly :s   
is there a better way to do it? :s  
I played with a few other ways like changing `_broadcast` to something like `_broadcastall(multiple_tensors)` but it just added even more unneeded complexity
> fix maximum/where Scalar casting

- extra/gemm/hip_matmul.py
`python3 extra/gemm/hip_matmul.py` produces the following error on current master:
` File "/home/wpmed/tinygrad/extra/gemm/hip_matmul.py", line 30, in <module>
a = hipallocator.alloc(N*N*4)
File "/home/wpmed/tinygrad/tinygrad/device.py", line 152, in alloc
try: return super().alloc(size, options)
File "/home/wpmed/tinygrad/tinygrad/device.py", line 140, in alloc
return self._alloc_with_options(size, options) if options is not None else self._alloc(size)
File "/home/wpmed/tinygrad/tinygrad/runtime/ops_hip.py", line 55, in _alloc
check(hip.hipSetDevice(self.device.device))
AttributeError: 'int' object has no attribute 'device'`
This is because in this example device is set to `0`, but `HIPAllocator` expects a `HIPDevice`. The `int` value of the device then can be accessed by `device.device` …
> Fix hip_matmul device error

- extra/gemm/simple_conv.py
- test/test_linearizer.py
- tinygrad/tensor.py
The goal is to easily test tensor core triggering situations, especially those with multiple TC axis choices.
> extra/gemm: add a simple_conv.py along with correctness check

- examples/mlperf/model_eval.py
This PR fixes an issue regarding `bbox` being passed in as an `ndarray` to `loadRes` function of `pycocotools` after running `MODEL=retinanet python3 examples/mlperf/model_eval.py`:
To fix the issue, each `bbox` is converted to a list using `tolist()`. With this fix and letting the evaluation script run, it completes it with the target metric:
> Fix RetinaNet model evaluation script

- test/test_linearizer.py
- tinygrad/codegen/linearizer.py
will correctly handle and permutation of optops after the TC one.
This is the first PR in a series to add tensor cores to the optimization space with no wrong actions.
> wmma: fix the upcasts after WMMA to be hcopt ordering invariant

- examples/hlb_cifar10.py
less compile time for eval due to cache. 500 was a slow uneven number for 6 GPU too. eval time 5.9s -> 3.4s
> cifar EVAL_BS set default value to BS

- test/unit/test_device.py
- tinygrad/device.py
fixes `UnboundLocalError: local variable 'lib' referenced before assignment` when running with `DISABLE_COMPILER_CACHE=1`
> fix UnboundLocalError when running Compiler with DISABLE_COMPILER_CACHE

- tinygrad/features/search.py
hipcc crashes for buffers that are too large
this allows beam with wino, which is not that slow after #3293
> limit group_for_reduce bufs to 32kb

- test/test_linearizer.py
- test/test_winograd.py
- tinygrad/tensor.py
Significantly reduces the number of shapetrackers. for now, there is a bug where the gfactors get unfused into 2 kernels instead of 1. but it's way faster.
the idea is as follows:
```
each column of wino transform matrix mat is multiplied by only one element of the input data vector v
before, we have:
Tensor.stack([sum([mat[i][j] * v[i]] for j in range(len(mat[0]))]) for i in range(len(mat))])
this accesses v[i] once for each element of mat, times the size of the output stack, due the pad and add implementation of stack. However, if we first stacked the consts:
sum( [Tensor.stack(mat[i][j] for i in range(len(mat[i]))) * v[j] for j in range(len(mat))])
we can save a factor of len(mat[0]) for each wino dim.
the core idea is: Tensor.stack(mat[i][j] * v[i] for j in range(...)) is slower than …
```
> faster wino compile by catting consts across data expand dim

- tinygrad/shape/view.py
Fixes the following trivial cases:
```
same but unequal
ShapeTracker(views=(View(shape=(7, 4, 3, 1, 5), strides=(54, 0, 1, 0, 12), offset=1, mask=((0, 7), (0, 4), (0, 3), (0, 1), (0, 5)), contiguous=False),))
ShapeTracker(views=(View(shape=(7, 4, 3, 1, 5), strides=(54, 0, 1, 0, 12), offset=1, mask=None, contiguous=False),))
same but unequal
ShapeTracker(views=(View(shape=(3,), strides=(-4,), offset=8, mask=((0, 3),), contiguous=False),))
ShapeTracker(views=(View(shape=(3,), strides=(-4,), offset=8, mask=None, contiguous=False),))
same but unequal
ShapeTracker(views=(View(shape=(2, 4, 10, 1), strides=(0, -20, 1, 0), offset=60, mask=((0, 2), (0, 4), (0, 10), (0, 1)), contiguous=False),))
ShapeTracker(views=(View(shape=(2, 4, 10, 1), strides=(0, -20, 1, 0), offset=60, mask=None, …
```
> canonicalize empty masks

- test/test_ops.py
- tinygrad/device.py
- tinygrad/runtime/ops_cpu.py
Trying to apply the `.dot` method on tensors that translate directly to buffer ops of type `CONST` will produce incorrect results. Example:
```py
a = Tensor.ones((2, 3))
b = Tensor.full((3, 4), 2.0)
x = a.dot(b)
print(x.numpy()) # should be matrix of 6s, but getting a matrix of 2s
```
This issue only applies to interpreted backends because of an optimization in the `_interpret_ast` function which rewrites ASTs containing `ReduceOps.SUM` followed by a `BinaryOps.MUL` into `TernaryOps.MULACC`.
In order for `MULACC` to execute correctly, it uses strides info of input arrays, which doesn't work on input arrays that came directly from a buffer op of type `CONST` and were broadcasted later, because `np.broadcast_to` keeps the strides info of input arrays for …
> Fix dot product on buffers with zero strides

- extra/onnx.py
This op has optional arguments which are stored as floats, but, unlike required params, are not being cast into ints, which causes some models crashing.
> Fix: Always cast ONNX Slice op arguments into ints

- test/test_ops.py
- test/test_tensor.py
- tinygrad/tensor.py
Using `Tensor.mean` to compute the mean for tensors with 0(s) in their shape should output `nan`s when selecting those zeros in `axis`. This complies with Pytorch's behavior and actually makes sense.
> Fix Tensor.mean to compute the mean correctly when 0-length axes are selected

- test/test_ops.py
- tinygrad/tensor.py
fix when correction is too big. it seems to only work when input size is 0 though. torch can output -inf in var when correction is too big, which does not make sense.
> fix Tensor.var with 0 in reduce dim.

- tinygrad/lazy.py
** this is a PoC, and probably not how this should eventually be implemented ** (i will need to read the rest of lazy.py...)
the matmul forwards is: `half(sum(float(mul(a,b))))`, so the backwards is `mul(half(expand(float(grad))),b)`. Expands always realize in the lazy graph, but half(expand(float)) is just expand, so the casts can be simplified out by swapping the half and expand. this saves membw, and also allows half/half tc to trigger.
this change just applies casts to smaller dtypes before any movementops, just to check perf, and it's quite good (7950x):
```
993   14.06 ms run,    0.86 ms python,   13.21 ms HIP,  496.00 loss, 0.000112 LR, 2.08 GB used, 250407.02 GFLOPS,   3521.88 GOPS
994   14.05 ms run,    0.85 ms python,   13.20 ms HIP,  493.25 loss, 0.000107 LR, 2.08 GB used, …
```
> PoC UnaryOps before expand

- test/test_dtype.py
half memoryview only in 3.12+. rest of the test_dtype (bounty) seems to be legit issue in ops_python.
> exclude half with PYTHON in test_dtype.is_dtype_supported

- test/external/external_test_onnx_backend.py
was debugging fast math and turned out it passed on CI now. more like a bug in CI
> update onnx tests that no longer fail on CI

- .github/workflows/test.yml
- test/test_linearizer.py
- tinygrad/runtime/ops_python.py
Can test with the HIP, but it must be on python 3.12 to have half memory:
```
PYTHONPATH=. DEBUG=2 EMULATE_HIP=1 FORWARD_ONLY=1 PYTHON=1 N=16 HALF=1 ACC_HALF=0 python3 ./extra/gemm/simple_matmul.py
PYTHONPATH=. DEBUG=2 EMULATE_HIP=1 FORWARD_ONLY=1 PYTHON=1 N=64 HALF=1 ACC_HALF=0 python3 ./extra/gemm/simple_matmul.py
PYTHONPATH=. DEBUG=2 EMULATE_HIP=1 FORWARD_ONLY=1 PYTHON=1 N=16 HALF=1 ACC_HALF=1 python3 ./extra/gemm/simple_matmul.py
PYTHONPATH=. DEBUG=2 EMULATE_HIP=1 FORWARD_ONLY=1 PYTHON=1 N=64 HALF=1 ACC_HALF=1 python3 ./extra/gemm/simple_matmul.py
```
You can also use the standard tensor core tests now:
```
EMULATE_METAL=1 FORWARD_ONLY=1 PYTHON=1 python3 ./test/test_linearizer.py TestLinearizer.test_tensor_cores 
EMULATE_HIP=1 FORWARD_ONLY=1 PYTHON=1 python3 ./test/test_linearizer.py …
```
> ops_python: add HIP tensor core mock and refactor METAL

- test/test_randomness.py
- tinygrad/tensor.py
I tried to create a Tensor.randint on another device:
```python
x = Tensor.randint([3,3],device="CLANG")
print(x)
```
Output shows it is created on "GPU" instead:
```python
<Tensor <LB GPU (3, 3) contig:True (<UnaryOps.CAST: 3>, None)> on GPU with grad None>
```
This PR fixes it by making Tensor.randint pass the kwargs on, only updating the dtype to int32. Also added a test that would fail without this PR.
> fix Tensor.randint ignoring kwargs

- test/test_linearizer.py
- tinygrad/codegen/kernel.py
- tinygrad/codegen/linearizer.py
Fully UNROLLing the first_reduce should not change the number of local_dims.
Fully UNROLLing a GROUP dim should reduce the number of group_for_reduces by one.
Also changed group_for_reduces to be a count as the axis number isn't used anywhere (they are always the first reduce dims).
For testing ran: `PYTHONPATH=. METAL=1 FUZZ_BEAM=1 FUZZ_N=64 DEPTH=2 python3 ./test/external/fuzz_linearizer.py` and no failures except for the expected compare failures with large half accs and GROUP.
> linearizer: fix up edge case bugs in UNROLL opt

- test/test_ops.py
removed the explicit set value if it's the same as default 1e-6, or higher but can be set to default.
> cleanup atol in test_ops

- test/external/external_test_onnx_backend.py
- tinygrad/runtime/ops_metal.py
disable test_MaxPool3d_stride_padding_cpu onnx test that would fail with fast math enabled. the test failed with `NOOPT=1 python -m pytest test/external/external_test_onnx_backend.py -k test_MaxPool3d_stride_padding_cpu` and passed with
`METAL_FAST_MATH=0 DISABLE_COMPILER_CACHE=1 NOOPT=1 python -m pytest test/external/external_test_onnx_backend.py -k test_MaxPool3d_stride_padding_cpu`
> add METAL_FAST_MATH env var to disable metal fast math

- test/unit/test_view.py
- tinygrad/shape/view.py
repro:
```python
from tinygrad.shape.view import View
a = View.create(shape=(2, 1, 2), strides=(30, 0, 2), offset=7, mask=None)
print(a)
print(a.minify())
b = View.create(shape=(1, 2, 2), strides=(0, 30, 2), offset=7, mask=None)
print(b)
print(b.minify())
```
before:
```
View(shape=(2, 1, 2), strides=(30, 0, 2), offset=7, mask=None, contiguous=False)
View(shape=(2, 2), strides=(30, 2), offset=7, mask=None, contiguous=False)
View(shape=(1, 2, 2), strides=(0, 30, 2), offset=7, mask=None, contiguous=False)
View(shape=(1, 2, 2), strides=(0, 30, 2), offset=7, mask=None, contiguous=False)
```
after:
```
View(shape=(2, 1, 2), strides=(30, 0, 2), offset=7, mask=None, contiguous=False)
View(shape=(2, 2), strides=(30, 2), offset=7, mask=None, contiguous=False)
View(shape=(1, 2, 2), strides=(0, 30, …
```
> fix merging condition in merge_dims

- tinygrad/shape/shapetracker.py
When `vm1` is contiguous and size of `vm1` and `vm2` match, then `merge_views(vm2, vm1)` must be `vm2` reshaped to `vm1` , if the reshape is possible.
benchmarks:
```python
SEED=6961 CNT=10000 CHECK_NEQ=1 FUZZ=plus PYTHONPATH="." python3 test/external/fuzz_shapetracker_math.py
```
with `SEED=6961`,
master:
same but unequal 5.54%
branch:
same but unequal 5.42%
with `SEED=5115`,
master:
same but unequal 6.05%
branch:
same but unequal 5.90%
> patch merge_views to handle missing case

- tinygrad/tensor.py
```
mat_in, mat_out = len(mat[0]), len(mat)
```
> verbose apply_matrix

- tinygrad/helpers.py
followup after #3370 disabled fast math on metal. This ensured that the benchmark does not used old compiled cache.
> bump db version to 11

- docs/abstractions.py
- test/external/external_test_example.py
- test/test_schedule.py
- tinygrad/codegen/kernel.py
- tinygrad/device.py
- tinygrad/features/jit.py
- tinygrad/features/search.py
- tinygrad/lazy.py
- tinygrad/runtime/ops_ext.py
- tinygrad/runtime/ops_python.py
- tinygrad/tensor.py
Interestingly, this seems to depend on the JIT only rerunning the dependent kernels. Without that, it tries to reallocate EXT buffers.
This is a good bug to investigate, because it was probably copying from uninit memory.
Repro with `MODEL=commavq METAL=1 python3 test/external/external_model_benchmark.py`
> ops_ext to replace cpu import

- test/test_lazybuffer.py
- test/test_linearizer.py
- tinygrad/codegen/linearizer.py
- tinygrad/dtype.py
- tinygrad/lazy.py
- tinygrad/realize.py
- tinygrad/tensor.py
in realize.py we force the ConstBuffer's arg to be float. I think this is wrong, it has lead to ASTs like this:
`Tensor([1,2,3]) + 2`
```
0 ━┳ STORE MemBuffer(idx=0, dtype=dtypes.int, st=ShapeTracker(views=(View(shape=(3,), strides=(1,), offset=0, mask=None, contiguous=True),)))
1  ┗━┳ ADD 
2    ┣━━ LOAD MemBuffer(idx=1, dtype=dtypes.int, st=ShapeTracker(views=(View(shape=(3,), strides=(1,), offset=0, mask=None, contiguous=True),)))
3    ┗━━ CONST ConstBuffer(val=2.0, dtype=dtypes.int, st=ShapeTracker(views=(View(shape=(3,), strides=(0,), offset=0, mask=None, contiguous=False),)))
```
when I removed that float cast, it uncovered issues upstream where we create these const buffers, eg. tensor.py's _broadcast and lazy.py's const could return bufs like this:
`ConstBuffer(val=1, …
> dtypes: delete the float cast in realize.py

- test/test_ops.py
A prereq to make `test/test_ops.py` run faster with the Python backend in #3384.
> Make tensors sizes smaller in maxpool2d tests

- test/test_linearizer.py
#3401 uncovered a [cache key conflict in linearizer's `load_cache`](https://github.com/tinygrad/tinygrad/pull/3401#discussion_r1490998933). The test before was an attempt to unit test this regression, but as @chenyuxyz [pointed out](https://github.com/tinygrad/tinygrad/pull/3401#issuecomment-1946122961) it tests the implementation.
This is an end-to-end test of the linearizer, it gives the linearizer the AST and asserts the uops.
> a better test for load_cache key conflicts

- tinygrad/shape/symbolic.py
- tinygrad/shape/view.py
this can greatly reduce the posiible output types of substitute
> limit symbolic substitute var_vals to have NumNode or Variable

- .github/workflows/test.yml
- tinygrad/runtime/ops_python.py
First cast to float or int depending on the output value. Then use struct to pack and then unpack to get the correct bits (esp. important for floats). Last edge case is integer casts where struct packing an out-of-bounds value will throw, so use the original dtype fmt to pack, and then unpack with the desired type.
> Cast correctly in python emulator (dtype tests pass)

- test/test_dtype.py
- tinygrad/runtime/ops_python.py
Followup to #3446. #3447 brought up some good test edge cases around uint/int out-of-bounds conversions differing from numpy. Roll our own overflow wraparound handling, which simplifies struct packing afterwards
> Fix python cast uint/int overflow

- test/unit/test_symbolic.py
- tinygrad/shape/symbolic.py
`(Variable("a", 1, 5) < Variable("a", 1, 5))` should eval to `NumNode(0)`
> fix LtNode simplification when lhs and rhs contain same variables

- .github/workflows/benchmark.yml
- tinygrad/lazy.py
it made gpt2 slower (2ms -> 2.5ms on 3090, 7ms -> 8ms on M1 Max with BEAM=2). disabled it in gpt2 benchmark before understanding the full issue
> gate the cast before movements in lazy

- test/test_ops.py
- tinygrad/tensor.py
matched torch to take axis \in [-1, 0] and used axis=None internally
> fix softmax and log_softmax for 0d tensor

- .github/workflows/benchmark.yml
Might be from renaming, but the old filename is never created and the new filename is never uploaded.
> Upload correct benchmark artifact

- tinygrad/features/jit.py
Forbid optimizations for everything but astrunners. For syncs this is incorrect. For copies (+transfers), optimizing may create a dependency chain that prevents parallel execution.
* SD mem usage is the same
* hlb_cifar 6 GPUs (with ring all reduce) `12.51 GB used` -> `12.55 GB used`
For #3403
> cache collector optimizations are allowed only for kernel operations

- test/test_dtype.py
should be able to run in CI with python 3.12
> properly exclude PYTHON backend and support of half

- test/external/fuzz_linearizer.py
this allows us to limit the size of the kernel and reduce running times by avoiding ones that take a long time
> test/external/fuzz_linearizer: add a FUZZ_MAX_SIZE option

- tinygrad/runtime/driver/hip_comgr.py
Hardcoded arch causes problems on non gfx1100 platforms.
> don't hardcode arch in comgr

- tinygrad/device.py
- tinygrad/features/jit.py
- tinygrad/runtime/driver/hsa.py
- tinygrad/runtime/graph/hsa.py
- tinygrad/runtime/ops_hsa.py
Graph is faster than hip both for a single device and multidevices. HSA still got limitation since the only way to access sdma queue is to call hsa functions. Ideally we want to access queue and push prebuilt packets into it (as it's now with aql queue). As of now, the only way to access it is to ask the kernel driver to map it. I will play with it to see what perf we can get ideally.
llama: `enqueue in   3.89 ms total  43.15 ms, 23.17 tok/sec` -> `enqueue in   2.43 ms, total  41.12 ms, 24.32 tok/sec`
gpt2: `ran model in   7.80 ms` -> `ran model in   7.32 ms`
cifar:
```
HSA=1 GPUS=6 HALF=1 LATEWINO=1 LATEBEAM=0 DEBUG=0 STEPS=350 BS=3072 TARGET_EVAL_ACC_PCT=93 python3 examples/hlb_cifar10.py
...
348   45.27 ms run,   10.43 ms prep batch,    3.45 ms jit,   31.40 ms HSA * 6,  493.00 loss, …
```
> hsa multigpu graph

- tinygrad/runtime/ops_hsa.py
Fixes the case where a device is initialized after the creation of a buffer, which is then used as a source in a transfer operation for the device. Check that all known devices have access to the buffer prior to initiating the transfer.
> check buffers are accessible by other gpu before transfer

- test/unit/test_disk_tensor.py
failed case for #3510, mark as expectedFailure for now
> failed test case for disk tensor assign into dtype int64

- test/test_fuzz_shape_ops.py
- tinygrad/tensor.py
This fixes `.split` where `self.shape[dim]` is not perfectly divisible by `sizes` - `.chunk` is always the wrong choice here:
`tensor((5,)).split(4)` should result in `(tensor((4,)), tensor((1,)))`, was `(tensor((3,)), tensor((2,)))`
This also fixes issues in `.split` and `.chunk` where tensors with `shape[dim] == 0` lead to empty tuples/lists when the tensor itself should have been returned instead.
All included tests are hypothesis fuzz-tests and written with the idea in mind that if torch rises an error then so should tinygrad - otherwise all outputs must match. Because of this tinygrad will now be strict regarding `sizes` having to sum up to passed dimension in `.split`, `num` having to be non-null for `.chunk` and only allowing valid dims in `.unsqueeze`.
---
I am not sure if the …
> fix: align .split, .chunk and .unsqueeze with torch, add fuzz tests

- extra/gemm/cuda_matmul.py
fix Import Error: cannot import name 'compile_cuda' from 'tinygrad.runtime.ops_cuda' error in extra/gemm/cuda_matmul.py
> fix error in extra/gemm/cuda_matmul.py

- test/unit/test_disk_cache.py
- tinygrad/helpers.py
Some devices create cache table names with non-alphanumerical characters, e.g. "compile_hip_gfx1010:xnack-_12".
This commit escapes the table name in single quotes s.t. sqlite works in these cases (see https://github.com/tinygrad/tinygrad/issues/3538).
The change does not influence database schema and should not require a version bump.
> Escape table name in diskcache queries.

- .github/workflows/benchmark.yml
- .github/workflows/test.yml
- tinygrad/codegen/kernel.py
- tinygrad/codegen/linearizer.py
- tinygrad/codegen/uops.py
- tinygrad/renderer/cstyle.py
- tinygrad/runtime/ops_cuda.py
- tinygrad/runtime/ops_python.py
A couple of changes from the previous attempt:
1) Changed `make_half4` and `make_half8` to explicitly construct a `half4` or `half8` instead of returning a struct directly: i.e. `{ half4 r={x, y, z, w}; return r; }` instead of `{ return {x, y, z, w}; }`.   This is to make older CUDA compilers (11.5) happy.
2) Changed the structure of the CUDA TC threads structure so that each dim of all the thread aliases is the correct size.  This fixes an issue with float4 grouping and tensor cores that is triggered in `test_speed_v_torch.py: test_large_conv_1x1` on CUDA.
> wmma: add CUDA tensor core and fix test_speed_v_torch failure

- tinygrad/codegen/kernel.py
- tinygrad/features/search.py
For `LATEWINO=1`, this patch Increases the number of tensor core-eligible kernels in hlb_cifar from 13 to 18 and reduces single GPU step time from 15.3ms down to 13.7ms with `time HIP=1 HALF=1 STEPS=1000 LATEWINO=1 LATEBEAM=16 BEAM_LOOSE_TC=1 BEAM_UPCAST_MAX=4096 BEAM_LOCAL_MAX=512 BEAM_MIN_PROGRESS=25 TARGET_EVAL_ACC_PCT=93 python3 examples/hlb_cifar10.py`:
```
995   13.64 ms run,    1.76 ms python,   11.88 ms HIP,  494.75 loss, 0.000102 LR, 2.08 GB used,  14496.43 GFLOPS,    197.78 GOPS
996   13.56 ms run,    1.76 ms python,   11.80 ms HIP,  499.75 loss, 0.000099 LR, 2.08 GB used,  14590.15 GFLOPS,    197.78 GOPS
997   13.55 ms run,    1.75 ms python,   11.80 ms HIP,  492.00 loss, 0.000094 LR, 2.08 GB used,  14593.94 GFLOPS,    197.78 GOPS
998   13.67 ms run,    1.77 ms python,   11.90 …
```
> search: add BEAM UPCAST/LOCAL params and loosen TC criteria during BEAM

- tinygrad/codegen/uops.py
2c19ab6561f4f70f7bc4cac002fa4f0fc8e81c4d broke sharded LLaMA with ring_allreduce (#3000).
Simple reproducer:
```python
DEVICE = "CLANG"   # NOTE: you can change this!
import struct
from tinygrad.dtype import dtypes
from tinygrad.device import Buffer, Device
from tinygrad.ops import LazyOp, BufferOps, MemBuffer, ConstBuffer, BinaryOps
from tinygrad.shape.shapetracker import ShapeTracker
out = Buffer(DEVICE, 1, dtypes.int32)
a = Buffer(DEVICE, 1, dtypes.int32).copyin(memoryview(bytearray(struct.pack("I", 2))))
b = Buffer(DEVICE, 1, dtypes.int32).copyin(memoryview(bytearray(struct.pack("I", 3))))
ld_1 = LazyOp(BufferOps.LOAD, (), MemBuffer(1, dtypes.int32, ShapeTracker.from_shape((1,))))
ld_2 = LazyOp(BufferOps.LOAD, (), MemBuffer(2, dtypes.int32, ShapeTracker.from_shape((1,))))
zero = …
```
> Don't touch UOps.DEFINE_GLOBAL

- tinygrad/nn/optim.py
Currently using functions that take an arbitary optimizer as a parameter is impossible with type hints
```py
def train_step(optimizer: nn.optim.Optimizer)
...
optimizer.step() # error - no member named step
...
```
> Improve type hints for optimizer

- test/test_linearizer.py
- tinygrad/codegen/uops.py
- tinygrad/renderer/cstyle.py
#3551
This optimization works with both:
1. PHI nodes `TestOps.test_gemm`
```
__kernel void r_2_16_8_16_4_4_4n2(__global float* data0, __global float* data1) {
// this branch
*((__global float4*)(data0+idx)) = acc0;
// master
*((__global float4*)(data0+idx)) = (float4)(float4)((acc0).x,(acc0).y,(acc0).z,(acc0).w);
}
```
2. float4 values `TestOps.test_avgpool2d`
```
__kernel void E_2_37_7_3_2_16_4n3(__global float* data0, __global float* data1) {
// this branch
*((__global float4*)(data0+idx)) = val0;
// master
*((__global float4*)(data0+idx)) = (float4)(float4)((val0).x,(val0).y,(val0).z,(val0).w);
}
```
I limited this to global stores only, because they're already childless.
Next is supporting local store and accurately updating its children in the UOpGraph.
> Directly store float4 nodes

- test/unit/test_symbolic.py
- tinygrad/shape/symbolic.py
`(7//-2)` = -4, not -3
also a[0-7]//-2 = `((((a*-1)+8)//2)+-4)`, if you plug in various values of a, the new formula is correct.
`a=0`, result is 0. `a=1`, result is -1.
> Fix symbolic negative floordiv

- test/test_tensor.py
- tinygrad/tensor.py
1. `Tensor.to` should return `self` if `device == self.device`. This was not the case if provided with non-canonical name of `self.device` (e.g. `HIP` and `HIP:0`).
2. `Tensor.to` result was missing graph (`_ctx`), even though `requires_grad` and `grad` were propagated .
Add corresponding tests.
~~As a bonus, missing return type for deepwalk~~ ←I think I get why it's missing now.
> Fix two bugs concerning `Tensor.to`.

- test/test_uops.py
- tinygrad/codegen/uops.py
In Python, `x//y` rounds towards negative infinity, but `(x/y)` integer ops in other languages rounds towards 0.
Example in Python:
```
>>> (-9//4)
-3
>>> int(-9/4)
-2
```
Same example in C:
```
#include <stdio.h>
int main()
{
printf("%d\n", -9/4);
return 0;
}
$ ./a.out
-2
```
> Python div alu behavior differs slightly from others

- test/test_uops.py
- tinygrad/codegen/linearizer.py
- tinygrad/renderer/cstyle.py
I think linearizer should explicitly define a buf is mutable in the UOp, this is a prereq for multioutput.
> decouple buffer mutability from cstyle

- docs/showcase.md
This PR addresses outdated URLs in
https://github.com/tinygrad/tinygrad/blob/8500265561dc7402a7773e9c8bd58713d49461b6/docs/showcase.md?plain=1#L11
by replacing them with valid image file paths in repo.
Your attention is appreciated, but I understand if this PR is disregarded.
Thank you,
> fix outdated URL in showcase docs

- test/test_multitensor.py
- tinygrad/tensor.py
Right now `.dropout()` can not be used with multigpu. `.rand()`, which is called under the hood, uses `Tensor._loadop()` which cannot handle multidevice strings.
> Fix Tensor.dropout() with multigpu

- test/test_dtype.py
clang and python ALU for sqrt/sin/exp2/log2 returns double for math, so even if in tinygrad dtypes those are all floats, the comparison might be float to double and can fail. There might also be an issue if we changed default float to half
> test case to show clang and python doing math in double

- test/test_linearizer_failures.py
- tinygrad/renderer/cstyle.py
fixed another bracket nesting level exceeded maximum of 256
need to remove SUB since it's possible to have (const - (const - const)) in test/test_ops.py::TestOps::test_cos, in which case cannot remove the parens of children
> remove parens of ALU if it has associative property

- test/test_linearizer_failures.py
- tinygrad/codegen/uops.py
In a kernel that stores expanded value, the vin of float4 can come from same source, and we only remove once in that case.
> fix direct store float4 with same vin

- test/test_linearizer.py
- test/test_linearizer_failures.py
- tinygrad/codegen/kernel.py
- tinygrad/features/search.py
be more specific about invalid kernel opt, used that in test_linearizer_failures.
make BEAM kernel search work even with assertion disabled.
`BEAM=2 python3 -O examples/llama.py  --temperature=0 --count=10 --prompt="Hello." --timing`
> use custom KernelOptError in kernel opt

- test/test_ops.py
- tinygrad/tensor.py
I can also just early return in `_cumsum` when the specified axis length is 0.
> Fix `Tensor.cumsum` when axis of length 0 is selected

- extra/datasets/openimages.py
```python
def download_image(bucket, image_id, data_dir):
try:
bucket.download_file(f"validation/{image_id}.jpg", f"{data_dir}/{image_id}.jpg")
except botocore.exceptions.ClientError as exception:
sys.exit(f"ERROR when downloading image `validation/{image_id}`: {str(exception)}")
```
Uses `sys` yet it wasn't imported.
> Adding the missing sys import

- test/test_tensor.py
- tinygrad/tensor.py
This PR fixes a small issue when checking for `self.grad` inside `__repr__` after the implementation of `__bool__`.
Here's a simple way to reproduce the issue:
Here's the case when the fix is applied:
> Fix Tensor's __repr__ for printing out grad

- extra/optimization/search.py
this will make it easier to reproduce some of the memory faults we're seeing on HSA.
Currently with both the stock `rocm-6.0.2` and the new `hipruntime-03072024`, I believe the following command will trigger a page fault in about 10 seconds:
```
PYTHONPATH=. HSA=1 DEBUG=2 BEAM=64 BEAM_UPCAST_MAX=16384 BEAM_LOCAL_MAX=512 BEAM_MIN_PROGRESS=5 python3 ./extra/optimization/search.py --ast "LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.SUM, src=(LazyOp(op=BinaryOps.MUL, src=(LazyOp(op=BufferOps.LOAD, src=(), arg=MemBuffer(idx=1, dtype=dtypes.half, st=ShapeTracker(views=(View(shape=(6, 6, 512, 1, 512, 256, 2, 2), strides=(786432, 131072, 0, 0, 256, 1, 0, 0), offset=0, mask=None, contiguous=False),)))), LazyOp(op=BufferOps.LOAD, src=(), arg=MemBuffer(idx=2, dtype=dtypes.half, …
```
> search: add a tool that beam searches one or more kernels

- tinygrad/features/search.py
- tinygrad/runtime/ops_hsa.py
- tinygrad/runtime/ops_metal.py
when compilation succeeds, but runtime fails due to thread limits on METAL, this allows a beam search to proceed, treating this the same way as a compile failure.
> search: catch RuntimeError when timing acted_lins

- test/test_ops.py
need to cast some torch output to int32 because torch default returns int64 for index related function
close #2797
> test output dtypes matche in test_ops

- test/test_dtype.py
- tinygrad/tensor.py
bf16 Tensor created from python list goes through numpy float buffer and cast to bfloat16 on device (did not change the cast logic so only a few are supported now). `numpy` of bfloat16 Tensor returns in numpy.float to prevent precision loss.
> bfloat16 tensor creation from list and numpy

- test/test_dtype.py
fixable with float const then cast to bf16. cast folding with bitcast is incorrectly skipped
> failed test cases for bf16 Tensor.full

- test/helpers.py
Since HSAGraph inherits from JITRunner the assert wasn't treating that JITItem as a Graph.
`HSA=1 python3 -m unittest test.test_jit.TestJit.test_jit_multiple_outputs` should pass after this.
> Fix JITItem count assert for HSAGraph

- test/test_linearizer.py
- tinygrad/codegen/kernel.py
ValueError if src.src[0] is not a LOAD. Replaced with returning None in _apply_tc_opt and test to make sure the net output is KernelOptError.
> fix buf_index not found case in _apply_tc_opt

- test/external/speed_beam_v_hcopt.py
the goal is that big enough beam should be faster than hcopt/tc
~~also this failed on tc opt
NUM=2 FILTER_REDUCE=1 TEST_N=20 BEAM=4 DEBUG=2 python test/external/speed_beam_v_hcopt.py~~ fixed
> script to benchmark beam v hcopt

- test/test_jit.py
- tinygrad/features/jit.py
Minor bug fix: Currently calling the same `JIT`ted function with different kwargs breaks because the `expected_name_sts_dtype_device` changes.
This fixes the issue, but if it feels hacky, I can add a test or find a better solve (imo `itertools.chain`-ing the args and kwargs together isn't the best way of doing this).
> Fix kwargs in JIT

- .github/workflows/test.yml
- test/test_randomness.py
- tinygrad/tensor.py
for numpy based random, generate one for float then cast for bfloat16.
close #3653 (for the devices that support bf16 buffer)
> bfloat16 Tensor.rand
