tinygrad/tinygrad

- extra/optimization/get_action_space.py
- test/external/fuzz_linearizer.py
- test/test_linearizer.py
- test/test_linearizer_failures.py
- tinygrad/codegen/kernel.py
- tinygrad/codegen/linearizer.py
- tinygrad/device.py
- tinygrad/features/search.py
since all outbufs are the same shape opts and dimensions are valid. UOping needs a small refactor.
I'm leaving out multioutput FLOPS and mem from this refactor, it can't yet be tested e2e.
I think we could still use the first lb for the cache key
> multioutput uoping infra

- examples/coder.py
This is how bf16 load is tested in test_bf16_disk_write_read now and it should fix #2775. I tested that it fixed loading coder using PYTHON backend.
Will separate this special bf16 load v.s. regular bf16 support
> use llvm as bridge to fix_bf16 loading

- examples/coder.py
- test/test_dtype.py
- test/unit/test_disk_tensor.py
- tinygrad/nn/state.py
- tinygrad/tensor.py
updated coder.py and test_bf16_disk_write_read. LLVM does not really have bf16 buffer support, so removed from test_dtype cast bf16 tests since it does not work without the hack.
> move bf16 cast hack to Tensor.llvm_bf16_cast

- examples/coder.py
- examples/llama.py
- extra/models/llama.py
did not realize the same logic was in llama too.
really fix #2775
Add SUPPORT_BF16=0 if the device does not support bf16 buffer. It's slower so default to 1 as tinybox supports bf16 buffer
> apply the same fix_bf16 in llama and coder

- .github/workflows/test.yml
- README.md
- test/test_linearizer_overflows.py
- tinygrad/codegen/kernel.py
- tinygrad/features/search.py
- tinygrad/lazy.py
- tinygrad/runtime/ops_python.py
ci test uses device RHIP and HSA compiler (LinearizerOpt), so fine to remove HIP from tc. Also updated README and EMULATE tc test flag.
also added standalone test enumlated CUDA tensor cores.
> remove HIP in core tinygrad

- test/test_linearizer_failures.py
found during a full fuzz test of all applied_opts combos to a depth of 3 on the gpt2 kernels
confirmed on METAL, GPU, HSA, CUDA
> test_linearizer_failure: add failure 26 from a gpt2 kernel

- test/test_linearizer_failures.py
found during a full fuzz test of applied_opts combos to a depth of 4 on the gpt2 kernels w/o GROUPTOP.
added additional examples to failure 26 that don't have GROUPTOP
Tested on METAL, GPU, HSA, CUDA.
> test_linearizer_failure: add failure 27 from a gpt2 kernel

- test/test_dtype.py
- tinygrad/tensor.py
behavior matches jax. It's fine to have a tensor greater than max int8 size even if we set default int to int8
> use dtypes.int32 as return dtype for functions that return indices

- test/test_dtype.py
- tinygrad/codegen/uops.py
indices are in int32 now and is separated from buffer dtype. fix #3823
> use int32 instead of default_int in simplify_phi_loops

- .github/workflows/test.yml
- extra/optimization/test_beam_search.py
converted the rand in test to float32. I don't think it needs to be float64 which does not run with metal
> use float32 for rand buffer in test_beam_search and test in metal

- test/external/fuzz_linearizer.py
if the kernel is an assign `a += 1`, the rawbufs[0] is updated twice and gives false compare_error. @flammit fyi
> alloc new output in fuzz_linearizer between baseline and real one

- examples/hlb_cifar10.py
- extra/gemm/simple_conv.py
- extra/gemm/simple_matmul.py
- tinygrad/features/search.py
also clean up some examples to use __main__ and not initialize resources outside of main
This limits the amount of memory leaked in the child processes.  For very large kernels, you might need to limit the tasks per child to even less by setting `BEAM_MAX_TASKS_PER_CHILD` to a lower number.
For this run `PYTHONPATH=. HSA=1 GPUS=6 LATEWINO=1 LATEBEAM=64 BEAM_UPCAST_MAX=16384 BEAM_LOCAL_MAX=512 BEAM_MIN_PROGRESS=5 BEAM_MAX_TASKS_PER_CHILD=32 STEPS=10 DEBUG=2 HALF=1 BS=1536 python3 ./examples/hlb_cifar10.py`, the parent process still leaked up to 30GB by the end of a 4.5hr run, but this is not addressed here.  The total memory usage peaked at 80GB during one late WINO kernel, so in hindsight, I should've run with lower max tasks.
Tested in HSA and CUDA.  Trying to do beam inside of the …
> search: change to use "spawn" and limit the number of tasks per child

- test/test_jit.py
- tinygrad/features/jit.py
I think JIT should use Tensor.corealize to let the scheduler fuse outputs, the user can .realize() to opt-out of the fusion.
will enable the tests once multioutput is merged.
> proposal: multioutput JIT spec

- .github/workflows/benchmark.yml
smaller first batch saves about 0.05 ms per token. 1.75ms / tok on local 3090
> use JIT_BATCH_SIZE=4 for GPT2 3090 benchmark

- extra/optimization/helpers.py
- extra/optimization/search.py
- extra/to_movement_ops.py
- test/external/fuzz_linearizer.py
also fix up ast_str_to_str to support the new tuple of LazyOps
This will make it easier to integrate specific fuzz'ing of models into CI (i.e. use LOGOPS=/tmp/gpt2-asts.txt while running gpt2.py), then pass this to `fuzz_linearizer.py --file /tmp/gpt2-asts.txt`
> fuzz_linearizer: add --ast and --file params to read kernels

- examples/llama.py
copy scale on all device for now. naive sharding does not work because scale needs expand to really save memory.
70B does not work due to HSA_STATUS_ERROR_OUT_OF_RESOURCES.
`python3 examples/llama.py --gen 2 --size 13B --shard 6 --prompt "Hello." --count 10 --temperature 0 --timing --quantize`
13B on 6 gpus uses 47 GB v.s. 34 GB quantized
> simple fix llama shard with quantize

- test/external/verify_kernel.py
- tinygrad/features/search.py
show uop count, compile and run times for each candidate in search
also add --timing to verify_kernel.py to make it easier to explore hand-crafted applied opts
You can see the long tail of compile times for some of the WINO kernel:
> debug: add optional detailed BEAM_LOG logging

- test/test_ops.py
- tinygrad/tensor.py
The previous einsum code was broken when some of the result indices where not in the alphabetical order.
> Fix the result permutation in einsum

- test/test_linearizer_failures.py
- tinygrad/codegen/kernel.py
previously it was incorrectly aliasing 16 into the size 8 upcast on the store alias.  now it splits it properly into 8 and the remaining 2 into the correct local stride
> wmma: fix the AMD TC threads to split the first 16 threads

- .github/workflows/benchmark.yml
- examples/hlb_cifar10.py
- tinygrad/renderer/cstyle.py
- tinygrad/tensor.py
memory usage is between float and half due to numpy calls on dataset preprocessing, which converts into float.
on 3090
```
997  138.80 ms run,    2.65 ms python,  136.15 ms CUDA,  497.82 loss, 0.000092 LR, 3.80 GB used,   4848.80 GFLOPS,    673.00 GOPS
998  140.51 ms run,    2.68 ms python,  137.83 ms CUDA,  494.18 loss, 0.000092 LR, 3.80 GB used,   4789.63 GFLOPS,    673.00 GOPS
999  136.89 ms run,    2.65 ms python,  134.24 ms CUDA,  490.94 loss, 0.000092 LR, 3.80 GB used,   4916.41 GFLOPS,    673.00 GOPS
shuffling test dataset in 51.44 ms (epoch=0)
eval     9572/10240 93.48%,    0.40 val_loss STEP=1000 (in 2030.23 ms)
PYTHONPATH=. CUDA=1 BF16=1 python examples/hlb_cifar10.py  145.91s user 14.68s system 101% cpu 2:37.79 total
```
> training cifar with BF16 on CUDA

- tinygrad/renderer/assembly.py
- removes childless uops
- checking for item size of 1 is not necessary in pointer arithmetics now that we have constant folding
> ptx cleanup

- tinygrad/renderer/assembly.py
- tinygrad/runtime/ops_cuda.py
The minimum PTX version that supports sm89 is 7.8 (same version also supports sm90); without this ptxas fails when running tinygrad with PTX=1 on RTX 4090.
> Fix sm89 PTX=1 compilation

- tinygrad/runtime/ops_clang.py
don't need to define int64 and uchar
> clean up clang src header

- test/test_uops.py
- tinygrad/renderer/assembly.py
Previously load/store could be incorrectly rendered into ld.global/st.global when the input was an ALU op that performed an address computation with DEFINE_LOCAL on one of the arguments.
This would result in a GPU crash (unfortunately ptxas would silently compile this into a SASS kernel but the address would be a shared memory address). These kernels would be created during beam search for llama example and as such PTX=1 run would crash.
> Fix issues with pointer provenance in load/store through ALU

- test/test_dtype.py
- test/test_ops.py
- tinygrad/renderer/cstyle.py
- tinygrad/runtime/ops_clang.py
it includes macros to make sure that the math function output types match input types
fixed softmax_argmax issue in #3552 for clang.
> #include <tgmath.h> in ops_clang

- examples/llama.py
Instead of assuming every parameter is 2 bytes, add up tensor sizes in bytes. There's still some accuracy issues with bandwidth measurement but this brings things closer to reality.
> examples: Fix parameter bandwidth accounting for quantized LLama

- test/helpers.py
running `GPU=1 python -m pytest -rA test/test_dtype.py::TestHalfDtype::test_casts_from` on mac would fail.
> opencl on OSX does not support fp16 extension

- tinygrad/runtime/ops_cuda.py
if beamed kernel fails, we would raise on `check`
> check on cuEventSynchronize

- tinygrad/tensor.py
always casting to float32 makes default half to be slow
> correctly handle Tensor.rand when default_float = bf16

- .github/workflows/test.yml
- test/external/fuzz_linearizer.py
- test/external/verify_kernel.py
* rename FUZZ_BEAM to FUZZ_ALL_ACTIONS (not choosing a subset)
* skip simple ASTs (easier to use with LOGOPS output)
* don't fuzz a previously seen AST
* add options to allow non-zero --expected-failures
makes it easier to directly to run a model and directly validate a model using fuzz without sort/uniq on LOGOPS:
```
PYTHONPATH=. JIT=1 HALF=1 LOGOPS=/tmp/gpt2_ops.txt python3 examples/gpt2.py --count 10 --temperature 0 --timing
PYTHONPATH=. FUZZ_ALL_ACTIONS=1 DEPTH=2 python3 ./test/external/fuzz_linearizer.py --file /tmp/gpt2_ops.txt
```
> fuzz_linearizer: reduce debug verbosity and make easier for CI usage

- tinygrad/device.py
Spent a lot of time trying to find an (non-existent) error in my "buffers with offset" code
Introduced in #3934
How on earth isn't this caught by tests?
> Freeing size instead of buffer

- test/test_uops.py
- tinygrad/codegen/linearizer.py
- tinygrad/codegen/uops.py
- tinygrad/lazy.py
- tinygrad/renderer/cstyle.py
- tinygrad/renderer/llvmir.py
- tinygrad/runtime/ops_python.py
added an assert in uops, removed the cast in renderer. also removed some ad hoc casts.
fixed #3722
> enforce UOps.CONST arg has python type based on dtype

- .github/workflows/benchmark.yml
- test/external/external_model_benchmark.py
Before both `METAL` and `CUDA` were validating with only the `CLANG` backend
Now CI validation runs for the intended specified backend.
Or if we remove `NOCLANG`, validation test runs for both specified backend and `CLANG`
> correct device for validation test in model benchmark CI

- examples/llama.py
causes HSA resources leakages in child compile processes
To repro and make a tinybox REAALLY angry, do the following on master vs here: `PYTHONPATH=. DEBUG=2 BEAM=2 BEAM_MAX_TASKS_PER_CHILD=1 python3 examples/llama.py --gen 1 --size '7B' --temperature 0 --count 10 --prompt "Hello." --timing`.
You'll need to `rocm-smi -d N --gpureset` after to sort of recover (even after reset the default GPU is at 25Mhz and not 0Mhz).
> llama: prevent device initialization outside of __main__

- test/imported/test_indexing.py
- tinygrad/tensor.py
assign is more stable now, can start to think about #3394
> assert `__setitem__` if used other than disk

- test/test_dtype.py
- test/test_ops.py
- test/test_uops.py
- tinygrad/codegen/uops.py
this fixed the softmax.argmax bug for ops_python as the float is truncated to float32
> use ctypes to truncate float64 and float32 in uops

- test/test_dtype.py
- test/unit/test_disk_tensor.py
- tinygrad/lazy.py
- tinygrad/nn/state.py
- tinygrad/runtime/ops_disk.py
- tinygrad/tensor.py
On master disk doesn't assert that a cast is bitcast and does it as a bitcast even if it's a normal cast.
This behaviour is a footgun at least and broken at most. Also this is required (kinda, not really but it would make things much cleaner) for my zero copy offset buffers
> Shape changing bitcast and assert bitcast in disk

- test/test_randomness.py
there's a hack to fix float16, need a generic solution that works with bf16 and threefry
> test case Tensor.randn should be finite

- test/test_randomness.py
- tinygrad/tensor.py
fixed bfloat16 randn to not have inf.
don't really care about float64. threefry is float32 based too.
no nan loss training resnet with bf16
this
```
training resnet
Training on ['CUDA:0']
training with batch size 128 for 41 epochs
0 64281.37 ms run, 64267.41 ms python,  12.40 ms fetch data,    1.56 ms CUDA * 1,  7.07 loss, 0.00 acc, 0.000011 LR, 0.17 GB used,     49.38 GFLOPS
1 9314.52 ms run, 9309.47 ms python,   3.79 ms fetch data,    1.26 ms CUDA * 1,  7.03 loss, 0.00 acc, 0.000021 LR, 12.52 GB used,    340.80 GFLOPS
2 1042.35 ms run,    5.93 ms python,   5.02 ms fetch data, 1031.39 ms CUDA * 1,  7.09 loss, 0.00 acc, 0.000032 LR, 12.52 GB used,   3045.39 GFLOPS
3 1044.67 ms run,    4.12 ms python,   4.99 ms fetch data, 1035.57 ms CUDA * 1,  7.00 loss, 0.00 acc, 0.000042 LR, 12.52 GB …
```
> always use f32 for rand source of randn 

- tinygrad/engine/schedule.py
st here should be the same, calling simplify.unbind generates a different st object and breaks unbind cache
> don't simplify st in _recursive_lazyop when unbind

- test/test_const_folding.py
- test/test_jit.py
- tinygrad/features/multi.py
- tinygrad/lazy.py
- tinygrad/tensor.py
is_unrealized_contiguous_const is too strict and almost never hits if const is expanded. suffice to check if there's no pad
this fixed the intended behavior for `_to_const_val` folding a tensor zeros or ones. will eventually move this case into lazy and remove `_to_const_val` entirely. const folding with literal 0 and 1 should be fine to keep at tensor
> fix _to_const_val and const folding around it

- tinygrad/runtime/ops_kfd.py
`self.max_private_segment_size=512` is updated to pass other tests, since some kernels need >256 private memory.
The test `KFD=1 python3 test/test_ops.py TestOps.test_dilated_conv_transpose2d ` is fixed as well
> kfd fix kernels with private memory

- test/test_jit.py
I should have written this test with `expectedFailure`; the behavior this test was documenting was fixed in #3745
> delete irrelevant JIT regression test

- test/test_const_folding.py
works with literal const operand now because it's copied to each shard and handled by lazy. does not work for sharded const
> test examples for multi tensor const folding

- test/test_linearizer_overflows.py
Discussed in the learning tinygrad channel, conclusion was this is probably an oversight from a previous PR.
Hit by running `CLANG=1 python3 -m pytest test/test_linearizer_overflows.py`
> re-enable has_local check for linearizer test

- test/test_const_folding.py
- tinygrad/codegen/uops.py
`bool < false` is false, `true < bool` is false
(`a == a` is true, `a != a` is false is not implemented in this pr due to issues with float and nan)
> uops const fold rules to prevent tautological compare warnings

- tinygrad/features/search.py
TC upcasts don't impact the size or complexity of the kernel code
Fixes it so default search params will properly explore upcasts after the TC (i.e. for `simple_matmul.py`), but will increase the search time on TC-eligible kernels.
> search: fix counting of upcasts to ignore TC upcasts

- test/test_const_folding.py
- test/test_linearizer.py
- test/test_optim.py
- test/test_schedule.py
- tinygrad/lazy.py
- tinygrad/nn/optim.py
- tinygrad/ops.py
fixed `1 ** Tensor` folding.
wip. `test_onecyclelr` became very slow and need to prep this with some update rules in uops optimization to avoid `tautological-compare` warnings in clang
> Use exec_alu for lazy const folding

- tinygrad/runtime/ops_clang.py
src header should be part of the rendered output, and DEBUG=4 includes the header this way
> prepend CLANG_PROGRAM_HEADER in ClangCompiler.render instead of compile

- test/imported/test_indexing.py
- test/test_const_folding.py
2 additional tests in `test_indexing` also enabled by #4047 
also some basic `const_folding` tests to test folding advanced indexing into basic indexing.
Will do the `test_const_tensor_index` TODO next.
> add and enable tests for indexing const folding

- test/test_pattern_matcher.py
This got added alongside mulacc but there were no pattern matcher tests at the time of creation - updating
> Test for pattern matcher dtype set match

- test/test_dtype_alu.py
- tinygrad/codegen/kernel.py
- tinygrad/codegen/linearizer.py
- tinygrad/ops.py
an inferred cached_property.
removed all cases that use get_lazyop_info just to get the dtype of an op. prereq to remove InterpretedFlopCounter
> add LazyOp.dtype

- .github/workflows/test.yml
- .pre-commit-config.yaml
- tinygrad/ops.py
the annoying thing to remove all FlopCounter is that for device that does not support local, matmul index alu is huge. we can remove the dtype first.
sneak in updating `ruff` command to `ruff check`
> remove dtype from FlopCounter

- .github/workflows/test.yml
get rid of warning `Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache@v3.`
> update github action to actions/cache@v4

- test/test_multitensor.py
- tinygrad/runtime/ops_metal.py
revert commandbuffer broke metal on real devices (but not on CI due to its metal being software emulated)
> Metal is broken again

- tinygrad/engine/schedule.py
Since one ScheduleItem can target multiple output LazyBuffers, we need to map each output to a ScheduleItem.
When fusing:
https://tiny-tools-client.vercel.app/?id=2583e42c8eb2428a92ccb56432accece
`E_16`'s in_degree becomes 1:
https://tiny-tools-client.vercel.app/?id=e8f63a800c9442b18e5ea97cd987d48c
> account for all outputs when creating the graph

- tinygrad/lazy.py
verify with `SPLIT_REDUCEOP=0 BIG=2 MPS=1 python3 -m pytest -rA test/test_speed_v_torch.py -k sum`. 10X slower on mac
> add SPLIT_REDUCEOP to disable reduce split

- tinygrad/runtime/graph/cuda.py
- tinygrad/runtime/graph/hsa.py
- tinygrad/runtime/graph/metal.py
CUDAGraph (and other graphs) keep references to the input buffers in jit_cache.rawbufs. This doesn't allow the buffers to be freed/reused. I added code to remove these references like in TinyJit. For example, the following code uses around twice the necessary memory with around half of it stuck after making the graph:
```python
from tinygrad import Tensor,Device,TinyJit
from tinygrad.helpers import Context
import os
@TinyJit
def kernel(w,x):
res = ((w+x).max(-1)).sum()
return res.realize()
def step():
data = Tensor.rand(1024*256,1024,device="cuda").realize()
with Context(DEBUG=1):
res = kernel(w,data).item()
return res
w = Tensor.rand(1024,device="cuda").realize()
for _ in range(4):
res = step()
os.system("echo 1 $(nvidia-smi --query-gpu=memory.used --format=csv,noheader)") …
```
> CUDAGraph release input buffer references

- extra/optimization/search.py
- tinygrad/device.py
- tinygrad/features/search.py
setting BEAM_COMPARE=0 will prevents additional memory allocation needed to do the timing tests, until the real buffers can be used
This is useful for llama2-70B as well as unet3d for doing offline beam-searches when memory utilization is tight to populate the caches using `extra/optimization/search.py` on the output of LOGOPS, then running it live with `BEAM_COMPARE=0 BEAM=N` ensuring that no extra memory will be allocated during the run.
> search: add a BEAM_COMPARE env to optionally not compare to hc/tc

- test/test_dtype.py
- tinygrad/tensor.py
the use of sum can auto-upcast the result. fixed by using the data dtype as the acc_dtype
> fix return dtype of getitem Tensor indexing

- test/external/external_test_speed_llama.py
- test/test_multitensor.py
- tinygrad/device.py
On master:
```
tiny@tiny14:~/tinygrad$ BS=1536 GPUS=6 python3 examples/hlb_cifar10.py
shuffling training dataset in 2196.98 ms (epoch=0)
0 24073.57 ms run, 24073.25 ms python,    0.31 ms CUDA * 6, 1182.99 loss, 0.000015 LR, 1.11 GB used,     83.79 GFLOPS,   2017.22 GOPS
1 8122.71 ms run, 8122.15 ms python,    0.56 ms CUDA * 6, 1181.49 loss, 0.000030 LR, 12.35 GB used,    248.21 GFLOPS,   2016.16 GOPS
2   62.91 ms run,   23.67 ms python,   39.24 ms CUDA * 6, 1179.67 loss, 0.000045 LR, 12.35 GB used,  32048.85 GFLOPS,   2016.16 GOPS
3   61.12 ms run,   20.80 ms python,   40.32 ms CUDA * 6, 1171.41 loss, 0.000060 LR, 12.35 GB used,  32984.38 GFLOPS,   2016.16 GOPS
4   61.12 ms run,   20.59 ms python,   40.52 ms CUDA * 6, 1165.13 loss, 0.000075 LR, 12.35 GB used,  32989.38 GFLOPS,   2016.16 …
```
> multitensor shouldn't recompile

- tinygrad/codegen/linearizer.py
A refactor of the linearlizer to help with fusing multiple reduceops into one kernel
It makes the process of rendering a reduction it's own function, so that when there are multiple reducops in one kernel, there is only one block of code responsible 
introduces a new function `render_reduceop()` which does the rendering and moves `render_loop()` out of the `linearize()` so that it can be accessed by `render_reduceop()`
> Multireduce Kernels - prereq refactor

- .github/workflows/benchmark.yml
- examples/mlperf/initializers.py
- test/external/external_benchmark_resnet.py
Helpful for BEAMING / inspecting only a portion of the run, with a simple optimizer. Can test individual layers, individual convolutions w or w/o batchnorm. Remember to set JITCNT=high if you are benchmarking and not inspecting!
```
$ BEAM=0 DEBUG=0 JITCNT=10 CNT=5 DEFAULT_FLOAT=HALF python test/external/external_benchmark_resnet.py
layer1 slice2 x(64, 256, 112, 112)        :  211.17 ms,  16.50 tflops
layer1 slice1 x(64, 64, 112, 112)         :  177.96 ms,  21.00 tflops
layer2 slice2 x(64, 512, 28, 28)          :  20.77 ms,  41.01 tflops
layer2 slice1 x(64, 256, 56, 56)          :  50.12 ms,  29.00 tflops
layer3 slice2 x(64, 1024, 14, 14)         :  18.51 ms,  45.73 tflops
layer3 slice1 x(64, 512, 28, 28)          :  30.78 ms,  46.95 tflops
layer4 slice2 x(64, 2048, 7, 7)           : …
```
> Benchmarks for individual resnet layers

- test/test_schedule.py
- tinygrad/engine/schedule.py
Store in fp16 if it is convenient to save some memory.
Before:
```
0 ━┳ STORE MemBuffer(idx=0, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(64, 1, 64, 112, 112, 1, 1, 1), strides=(802816, 0, 12544, 112, 1, 0, 0, 0), offset=0, mask=None, contiguous=True),)))
1  ┗━┳ CAST (dtypes.float, False)
2    ┗━┳ CAST (dtypes.half, False)
3      ┗━┳ SUM ((7, 6, 5), dtypes.float)
4        ┗━┳ CAST (dtypes.float, False)
5          ┗━┳ MUL 
6            ┣━━ LOAD MemBuffer(idx=1, dtype=dtypes.half, st=ShapeTracker(views=(View(shape=(1, 64, 1, 64, 4, 114, 4, 114), strides=(0, 802816, 0, 12544, 0, 112, 0, 1), offset=-113, mask=((0, 1), (0, 64), (0, 1), (0, 64), (0, 4), (1, 113), (0, 4), (1, 113)), contiguous=False), View(shape=(64, 1, 64, 112, 112, 64, 3, 3), strides=(13307904, 0, 0, 456, 1, …
```
> in forced_realize, unchase last op if it is upcast

- test/test_fusion_op.py
- test/test_tensor.py
- test/test_tensor_data.py
- tinygrad/tensor.py
I tried hacking around indexing the memoryview and reconstructing the list with the right shape for awhile, only to find out that `memoryview.tolist()` exists 😄 
is this method valid?
after casting the memoryview, it seems that tolist resolves to a multidimensional list
> tolist to return multidimensional list

- test/external/fuzz_schedule.py
- tinygrad/engine/schedule.py
- tinygrad/helpers.py
eg.
```py
a = Tensor.empty(32, 32)
Tensor.corealize([a.sum() + 2, a.sum() * 4])
```
Fuzzes MULTIOUTPUT=0,1
```
fuzzing 3 schedule permutations
*** METAL      1 empty       1024 dtypes.float          arg   1 mem  0.00 GB tm      0.00us/     0.00ms (    0.00 GFLOPS,    0.00 GB/s)
*** METAL      2 r_256_4                                arg   2 mem  0.00 GB tm      8.92us/     0.01ms (    0.23 GFLOPS,    0.46 GB/s)
*** METAL      3 r_256_4n1                              arg   2 mem  0.00 GB tm      9.71us/     0.02ms (    0.21 GFLOPS,    0.42 GB/s)
testing permutation 0 {'MULTIOUTPUT': 0}
*** METAL      4 empty       1024 dtypes.float          arg   1 mem  0.00 GB tm      0.00us/     0.02ms (    0.00 GFLOPS,    0.00 GB/s)
*** METAL      5 r_256_4n1                              arg   2 mem …
```
> fuzz schedule context vars

- test/external/external_benchmark_resnet.py
For full layers, there was double relu.
bn(conv(x)).grad and bn(conv(x)) are realized if you stack layers, use contiguous to match it
`SAVE_SCHEDULE=1 CNT=1 ASSIGN=0 SPLIT_REDUCEOP=0 CONV=1 BN=1 BS=256 DEFAULT_FLOAT=HALF python test/external/external_benchmark_resnet.py BenchmarkResnetTrain.test_layer1_1`
>  more realistic edge behavior for resnet benchmark 

- tinygrad/runtime/ops_cuda.py
This will hopefully help people troubleshoot their problem much more quickly.  This exception is the first thing I ran into when trying out TinyGrad, and the error gives no details to point to where I should start looking.  Now it tells me `CUDA_ERROR_UNSUPPORTED_PTX_VERSION` which is something I can search for.
I didn't add tests since the exact text of error messages isn't usually something that is tested, but I can write a regression test for this if that is desired.
> Improves error message when CUDA module fails to load.

- test/test_assign.py
The focus should be on where `contiguous` is called.
> unify diamond assign tests

- .github/workflows/benchmark.yml
- extra/gemm/fuzz_matmul.py
- test/test_linearizer.py
- tinygrad/codegen/kernel.py
- tinygrad/features/search.py
Currently works on METAL and CUDA after the latest linearizer fixes, but on HSA there are weird issues with random small odd sized matrix shapes.  The last row or few rows will have random number of elements not be correct and the amount will generally be the same between runs.
To test / repro use:
```sh
PYTHONPATH=. DEBUG=4 DEBUG_VALUES=1 M=16 N=9 K=31 HALF=1 TC_OPT=2 python3 ./extra/gemm/simple_matmul.py
```
Note that while `(16,9,31)` doesn't work, `(16,9,32)` and `(16,17,31)` are fine.  The kernel code looks fine so it seems like memory load or sync issues (however, inserting barriers everywhere didn't make a difference).
For a more complete search use:
```sh
PYTHONPATH=. HSA=1 M_START=12 M_STOP=20 M_STEP=1 N_START=12 N_STOP=20 N_STEP=1 K_START=28 K_STOP=36 K_STEP=1 HALF=1 TC_OPT=2 …
```
> wmma: widen TC usage in search by using PADTO on TC axes when possible

- tinygrad/features/search.py
- tinygrad/helpers.py
also bump the DB version after the padded TC merge
Here's some stats on resnet search on this branch:
This run took 24 minutes to search from a clean disk cache:
```
flam@tiny19:~/tinygrad$ time PYTHONPATH=. CUDA=1 DEFAULT_FLOAT=HALF SPLIT_REDUCEOP=0 BS=1536 GPUS=6 BENCHMARK=10 TRAIN_BEAM=2 BEAM_UOPS_MAX=1200 BEAM_UPCAST_MAX=128 BEAM_MIN_PROGRESS=50 MODEL=resnet python3 examples/mlperf/model_train.py
training resnet
Training on ['CUDA:0', 'CUDA:1', 'CUDA:2', 'CUDA:3', 'CUDA:4', 'CUDA:5']
training with batch size 1536 for 37 epochs
0 34841.15 ms run, 34704.29 ms python, 135.64 ms fetch data,    1.23 ms CUDA * 6,  7.03 loss, 0.00 acc, 0.004177 LR, 2.08 GB used,   1093.60 GFLOPS
1 12432.41 ms run, 12395.74 ms python,  35.16 ms fetch data,    1.51 ms CUDA * 6,  7.01 loss, 0.00 acc, 0.008354 …
```
> search: add additional 7 factors to the action space

- tinygrad/codegen/uops.py
- tinygrad/renderer/assembly.py
We add new uops in assembly renderer so this gives some speed improvements. Slightly winning over cuda (0.993 on speed compare script) after this one with 32 major kernels left to beat (checking only those with exec times bigger than 500 us - smaller are very noisy)
> Optimize ptx loops

- test/imported/test_indexing.py
- test/test_setitem.py
- tinygrad/tensor.py
don't think setitem returns anything ([jax reference](https://github.com/google/jax/blob/main/jax/_src/basearray.pyi#L51))
a little unsure if this affects any previous DISK tensor implementations
also before the assert for contiguous was always returning True while not actually doing anything.
might've been the problem Cameron on discord was running into (I also accidentally ran into this thinking it was scheduler problem)
> setitem no return value

- examples/mlperf/model_train.py
- tinygrad/engine/jit.py
we want to have different BEAM values for resnet train and eval. global JITBEAM cannot do this. added the flag to change beam behavior at cnt=0 (so it default behaves the same with or without TinyJit), and for cnt=1 it uses existing BEAM.value.
Also updated the context var BEAM in resnet to be outside of TinyJit. saves about 3 minutes compile time
> use IGNORE_JIT_FIRST_BEAM to not BEAM in jit cnt=0

- examples/mlperf/model_train.py
only do few eval steps to compile, and skip second epoch when doing beam + benchmark. save 2 minutes
> resnet benchmark return early in eval

- .github/workflows/benchmark.yml
- examples/mlperf/model_train.py
also update LR default to scaled based on 1536 (the BS we are submitting)
> resnet benchmarks use DEFAULT_FLOAT=HALF

- tinygrad/features/search.py
this looks suspiciously like a hack to work around beam worker processes allocating 300+MiB of vram :thinking:
Seems pretty useful for the average user though.
> allow specify number of beam workers

- test/external/external_benchmark_resnet.py
- I got some details wrong before
- the strides happen in conv2
- there is a maxpool2d with stride 2 just before layer1
- add time/tflops/GBs/kernel estimates based on weighted sum
- allow getting convs other than conv2
- improve the JIT benchmarking setup
LMK thoughts.
Still testing these changes, will use them for benchmarking ksrc, split reduce, other things.
```
(venv) chaos@tiny15:~/tinygrad$ JITCNT=20 PARALLEL=10 BEAM=4 BS=256 DEFAULT_FLOAT=HALF python test/external/external_benchmark_resnet.py
layer1 slice1 x(256, 64, 56, 56)          :     41.86 ms,    9.32 tflops,    4.43 GB used,     81 kernels
layer1 slice2 x(256, 256, 56, 56)         :     35.02 ms,   10.05 tflops,    5.66 GB used,     63 kernels
layer2 slice1 x(256, 256, 56, 56)         :     39.34 ms,   15.00 tflops,    4.85 …
```
> More improvements for resnet layer bench

- extra/lr_scheduler.py
- test/test_optim.py
- tinygrad/nn/optim.py
when doing mixed precision training (float32 weight, default_float=half), still use float32 to store lr. it would have been upcasted later in actual weight update, but would have lost precision. this improved resnet convergence significantly
<https://wandb.ai/chenyuxyz/tinygrad-examples_mlperf/runs/acsacuu2/overview?nw=nwuserchenyuxyz> trains to target on epoch 34. without this it does not hit target even at opoch 37.
although not intentional, it seems to drop kernel counts @Qazalin fyi
> use at least float32 for optim.lr

- test/test_assign.py
We have a similar version of this graph
in [beautiful_mnist](https://tiny-tools-client.vercel.app/?id=3fd076fc9c6644b9b60b63f69fa457ac):
where fusing the assign child causes a cycle.
> test crossing diamond assigns

- test/helpers.py
Currently bf16 is not supported in PTX
> disable bfloat16 from ptx tests

- tinygrad/codegen/kernel.py
The previous calculation included UNROLLs which don't get stored in temp shared_memory, which meant that GROUPs or UPCAST/UNROLLS when alreading GROUP'ing were being incorrectly pruned too early.
> kernel: fix calculation of smem size to ignore UNROLL

- test/external/external_benchmark_resnet.py
```
time PYTHONPATH=. DEBUG=0 PARALLEL=10 SPLIT_REDUCEOP=0 JITCNT=20 BEAM=3 BEAM_UOPS_MAX=1500 BEAM_UPCAST_MAX=128 BEAM_LOCAL_MAX=1024 BEAM_MIN_PROGRESS=50 DEFAULT_FLOAT=HALF BS=256 python test/external/external_benchmark_resnet.py
layer1 slice1 x(256, 64, 56, 56)      :     37.09 ms,  10.53 tflops,   669 GB/s,   4.43 GB used,    80 kernels
layer1 slice2 x(256, 256, 56, 56)     :     30.41 ms,  11.58 tflops,   610 GB/s,   5.66 GB used,    62 kernels
layer2 slice1 x(256, 256, 56, 56)     :     40.94 ms,  14.41 tflops,   443 GB/s,   4.85 GB used,    80 kernels
layer2 slice2 x(256, 512, 28, 28)     :     23.35 ms,  14.72 tflops,   398 GB/s,   2.84 GB used,    62 kernels
layer3 slice1 x(256, 512, 28, 28)     :     30.24 ms,  19.22 tflops,   302 GB/s,   2.45 GB used,    80 kernels
layer3 …
```
> add mem/s to external_benchmark_resnet

- tinygrad/engine/schedule.py
It's helpful to visualize cycles when I schedule something wrong:
> save schedule graph pre validation

- extra/onnx.py
fixes #4314 
few notes:
This only addresses the reshape error
The reason of the error is that there is a previous `slice op` that uses a large `Tensor(9223372036854775807, dtype=dtypes.long)` as the `end` value, so the `Tensor.ceil()` used sets it to 0
After this is fixed, this model also requires `Exception: op_type ScatterND not supported` to run. I remember trying to write a ScatterND but being stuck at some cases.
> Fixes onnx Slice unintentional cast behavior

- test/external/external_test_opt.py
- test/test_schedule.py
The main focus is on differentiating fusion in these 3 graph variants:
for expand, reduce, shrink and same size contiguous children.
> reduce children fusion tests

- test/test_ops.py
- test/unit/test_shapetracker.py
- tinygrad/shape/view.py
Addresses the issue in #4109.
The issue appears when `old_dim` has n instances of `next_stride` but with a remainder. This remainder will push the position of the mask and might cross the axis boundary.
> Fix in `_reshape_mask`

- test/external/fuzz_schedule.py
Similar to lazy.py, This is essential for catching wrong diamond assign schedules.
> override assign_target in fuzz_schedule

- tinygrad/runtime/ops_gpu.py
- remove redundant byref as ctypes automatically handles passing `type` as `POINTER(type)`
- use walrus operator instead of `init_c_var` when possible
- simpler access of c strings from `create_string_buffer`
> refactor ops_gpu ctypes

- test/test_dtype.py
- tinygrad/function.py
without downcast_half, sum output dtype can be different from input dtype. cast back to input dtype in function.py
> fix function.py sum backward without downcast_half

- test/test_linearizer.py
- tinygrad/features/search.py
Fixes `get_linearizer_actions` to fully test all possible TC actions.  thanks to @chaosagent for pointing this out in discord.
Doesn't seem to regress, only improve on prior performance:
for tiny red / `HSA=1`:
| branch  | settings | setup (m:ss) | step time (ms) | flops (TF) |
| --- | --- | --- | --- |  --- |
| tc_reduce_choice | `SPLIT_REDUCEOP=1` | 15:48 | 455ms | 83 TF |  
| this branch | `SPLIT_REDUCEOP=1` | 15:52 | 427ms | 89 TF |  
for tiny green / `CUDA=1`:
| branch  | settings | setup (m:ss) | step time (ms) | flops (TF) |
| --- | --- | --- | --- |  --- |
| tc_reduce_choice | `SPLIT_REDUCEOP=1` | 25:34 (OOM), 19:36 (OOM) | 305ms, 304ms | 125TF, 125TF |
| this branch | `SPLIT_REDUCEOP=1` | 20:43 | 300ms | 127TF |
> search: fix actions space checks to ignore TC axis and amt

- examples/mlperf/helpers.py
- examples/mlperf/model_train.py
- test/external/mlperf_bert/external_test_checkpoint_loading.py
I think a standalone test to check whether checkpoint loading functionality is correct, is quite helpful to catch regressions caused by incorrect weight mapping or mixed precision changes in the forward pass. MLperf recommends [this](https://github.com/mlcommons/training/blob/master/language_model/tensorflow/bert/README.md#stopping-criteria).
> BERT: Checkpoint loading tests

- test/external/external_test_opt.py
- test/test_schedule.py
`test_llama` remains in external_test_opt because `model.forward` calls realize internally.
> fusion tests from test_opt

- test/test_linearizer.py
- test/test_search.py
- tinygrad/codegen/kernel.py
- tinygrad/features/search.py
won't change correctness, but will save a little python time by properly deduplicating potential actions
> search: fix edge cases on screening potential ops

- tinygrad/features/search.py
Also:
* ensure the return the unoptimized kernel if no opts are valid
* refactor debugging to a single BEAM_DEBUG variable.
* added an early stop as well if the best kernel runs in under `min_progress` since the next iteration cannot improve by more than that.
for tiny red / `HSA=1`:
| branch  | settings | setup (m:ss) | step time (ms) | flops (TF) |
| --- | --- | --- | --- |  --- |
| master | default | 26:24 | 365ms | 104TF |
| search_speed_improvements  | default | 23:56 | 367ms | 103TF |
for tiny green / `CUDA=1`:
| branch  | settings | setup (m:ss) | step time (ms) | flops (TF) |
| --- | --- | --- | --- |  --- |
| master | default | 23:53 | 263ms | 144TF |
| search_speed_improvements | default | 19:53 | 263ms | 144TF |
> search: skip timing the unoptimized kernel

- test/test_schedule.py
Passing this spec is a prereq for r3 in Adam, we need to replace `forced_realize` with a clean way to partially fuse some children.
> partial fusion spec

- tinygrad/tensor.py
factor out the -1 * and / loss_mask.sum() for both smoothing and non-smoothing terms
saved like 1 minutes in resnet estimated for green
> refactor sparse_categorical_crossentropy

- examples/hlb_cifar10.py
- test/test_schedule.py
- tinygrad/nn/__init__.py
-1 kernel ez :sunglasses:
mnist 96 -> 93 kernels. need to test resnet.
tested with test/models/test_end2end.py. we don't have backward tests for UnsyncedBatchNorm though...
> batchnorm d(var)/d(mean) = 0

- test/unit/test_disk_cache.py
- tinygrad/helpers.py
drop all tables in diskcache. added a unit test but disabled it by default because it will drop all cache...
> helpers.diskcache_clear

- test/test_linearizer.py
- test/test_linearizer_failures.py
- tinygrad/codegen/kernel.py
fixed test_failure_31. PADTO upcasted is at best a no-op, and might fail at edge cases.
> disable PADTO on upcasted axis

- test/unit/test_flopcounter.py
cannot really catch a spec change error without testing the new spec explicitly, but we don't intended to change the lazy spec lightly
another possible way to catch reduce flopcounter shape would be type checking InterpretedFlopCounter and throw error if `in` results in `Never`
> test unary and more reduces in test_flopcounter

- test/test_linearizer.py
- tinygrad/codegen/kernel.py
- tinygrad/codegen/linearizer.py
no change to performance or behavior.  new LOCALS are added to the left side of the LOCALS block (to the left of the first_reduce).
> kernel: un-reverse the order of the local indices

- test/test_lazybuffer.py
- tinygrad/lazy.py
changed the condition from all 0 in masked dims to any 0 in masked. it's no-op because shapetracker rewrites whole mask to 0 if any dim has 0 as part of canonicalization
> test for LazyBuffer._view when mask out and degrade into const

- .github/workflows/benchmark.yml
- test/test_const_folding.py
- tinygrad/lazy.py
this brings most of the memory gain for resnet back.
effectively revert #4152
> revert the removal of CAST_BEFORE_VIEW

- docs/developer.md
- docs/quickstart.md
- docs/showcase.md
Updating links in `docs/` to point towards https://github.com/tinygrad/tinygrad/blob/master instead of https://tinygrad.github.io/, ie making them work :)
> Update links in new docs

- examples/mlperf/model_train.py
clear cache if INITMLPERF is set, or running run_and_time. dev_beam and dev_run do not clear cache
doing 5 back to back on this before merging, output should be eligible for submission (if at least 4 runs converge)
> real diskcache_clear in model_train resnet

- .github/workflows/benchmark.yml
from fuzzer it seems to be flaky due to numerical issue, not kernel bug. we used to have half in splitted reduce.
run this in M1 Max for 20 loops and it's fine
> re-enable gpt2 half/beam mac benchmark

- tinygrad/engine/schedule.py
Fusion can be two steps:
1. Gather elementwise ops that _could_ fuse
2. Check reduceop -> fused_child is a self-contained DAG
This diff focuses on step 1.
> refactor: dfs fusion

- test/test_linearizer.py
Refactors the helper to use AST and rawbufs, this allows for testing linearizer correctness independent of scheduling.
> infra for testing linearizer correctness

- test/test_linearizer.py
generalizes helper_linearizer_opt to be independent of scheduling with:
```py
def helper_linearizer_ast(ast:Tuple[LazyOp, ...], inputs:List[Tensor],
```
factorized out.
This allows us to bypass scheduling for testing AST -> codegen correctness.
> test_linearizer_correctness

- test/test_linearizer.py
@0xtimmy test_linearizer now has a helper for testing the UOps by running the prg (noopt, handcoded opts). Grabbed a few tests from your PR #4259. Can you update your PR with this test format and delete `expectedFailure` ones?
> multi reduce linearizer tests start

- tinygrad/engine/schedule.py
@geohot I think the scheduler should create the correct AST in the DAG transformation part.
> move copy kernel to out of schedule ordering

- examples/llama.py
`BEAM=2 PYTHONPATH=. JIT=1 python3 examples/llama.py --quantize=nf4 --gen=3 --temperature=0 --count=10 --prompt="Hello." --size 8B --timing` on M1 Max
this
```
enqueue in   5.65 ms
total 306.70 ms, 3.26 tok/s, 353.75 GB/s, param 16.43 GB/s
the
enqueue in   5.82 ms
total 306.67 ms, 3.26 tok/s, 353.79 GB/s, param 16.44 GB/s
forum
enqueue in   5.87 ms
total 306.58 ms, 3.26 tok/s, 353.90 GB/s, param 16.44 GB/s
and
enqueue in   5.65 ms
total 308.55 ms, 3.24 tok/s, 351.65 GB/s, param 16.34 GB/s
I
```
master
```
enqueue in   5.95 ms
total 342.78 ms, 2.92 tok/s, 360.30 GB/s, param 14.70 GB/s
the
enqueue in   5.97 ms
total 342.82 ms, 2.92 tok/s, 360.27 GB/s, param 14.70 GB/s
forum
enqueue in   6.00 ms
total 342.24 ms, 2.92 tok/s, 360.88 GB/s, param 14.73 GB/s
and
enqueue in   5.95 ms
total 342.33 …
```
> slightly faster nf4 llama

- test/test_assign.py
There are two possible RuntimeErrors in the scheduler for ASSIGN:
1. contiguous st for read/write bufs
https://github.com/tinygrad/tinygrad/blob/4e1135a0bcfb3d85b44ecb846275b2a9b7cfc563/tinygrad/engine/schedule.py#L72
2. cycle in some diamonds
https://github.com/tinygrad/tinygrad/blob/4e1135a0bcfb3d85b44ecb846275b2a9b7cfc563/tinygrad/engine/schedule.py#L312
Differentiating them is important for piecewise scheduler testing.
> assert error detail in test_assign

- tinygrad/engine/schedule.py
- not x.base.realized -> x.base.realized is None everywhere
- use generators if possible
- more consistent naming
> small scheduler refactor

- test/test_schedule.py
- tinygrad/engine/schedule.py
We don't have good piecewise testing for simple_pads - only `TestHandCodedOpts` covers this in unit tests.
+np.testing.assert_equal outs - kernel count isn't enough.
> pad fusion tests

- tinygrad/tensor.py
still need the div because backward could not flow through eq
> simpler abs and sign

- test/test_ops.py
- tinygrad/function.py
- tinygrad/tensor.py
moved Sign logic to function.py, and backward always returns 0 to match torch. rewrite abs as `self * self.sign()`, so its backward also matches torch.
> redo simpler abs and sign

- test/test_dtype.py
brought up in #4188
abs to unsigned or bool is no-op
use where for int because cstyle does not like relu for int (might have more issue with int in general)
keep double relu for float, would need to check perf before switching
RHIP crashed in CI @Qazalin fyi
> fix abs of diff of uint

- .github/workflows/benchmark.yml
- .github/workflows/test.yml
if it takes more than 10 usually setup fails anyway. also updated matmul_kfd -> matmul_amd in benchmark
> CI test timeout 20 min -> 10 min

- test/external/fuzz_uops.py
- tinygrad/codegen/uops.py
Since the fuzzer uses a different toposort than uops.py we add UOps.END* in fuzz_uops.py
> correctly insert UOps.END* in fuzz result

- test/test_linearizer.py
- tinygrad/codegen/uops.py
Layout of how toposorting loops_children should behave given:
1. `n` nested loops
2. outer uops (not children of loops) before PHI
3. outer uops after PHI
4. children position with dependance on _some_ loops
> UOps.RANGE toposort spec

- examples/conversation.py
it used to be true for int8, not it's a string for int8 or nf4
> fix conversation.py quantize

- tinygrad/engine/search.py
we used 1024 for mlperf submission and result steps time is 20% faster. the default should not be worse
> update BEAM_LOCAL_MAX to 1024

- .github/workflows/test.yml
- test/test_linearizer.py
found root cause for https://github.com/tinygrad/tinygrad/actions/runs/9145074079/job/25143631108?pr=4647 - It's a uop simplification issue.
I think the tests are more robust if they run against a real compiler.
> catch compile errors in uops pattern matcher

- test/test_linearizer.py
- tinygrad/codegen/uops.py
In master the uop simplifier folds a PHI-GEP-CAST even if PHI is half4 and CAST is float4:
```
half4 acc0 = half4(0.0,0.0,0.0,0.0);
{
acc0 = // ...
}
*((device float4*)(data0+alu0)) = float4(acc0.x,acc0.y,acc0.z,acc0.w);
becomes:
*((device float4*)(data0+alu0)) = acc0;
```
We should only fold CAST if the PHI and CAST dtypes match.
> keep UOps.CAST in PHI-GEP fold for unmatching dtypes

- test/test_linearizer.py
- tinygrad/codegen/uops.py
5f84cbb5dfef6a0ecdacd5e6d851f2cf6d7d62b5 isn't the right fix for llama BEAM=2 - Need to trace this back further.
> revert uops dtype in pattern matcher

- test/test_linearizer.py
@0xtimmy the assert_allclose fails in the linearizer branch.
You can see the single reduce example in `TestLinearizer.test_upcast_with_locals`
> correctness test for multireduce nested locals

- test/test_linearizer.py
The root cause for llama BEAM=2 failing https://github.com/tinygrad/tinygrad/actions/runs/9145074079/job/25143631108?pr=4647 is that uops.py places children of PHI outside the loop.
In tensor cores, `GRAPHUOPS=1 python3 test/test_linearizer.py TestLinearizer.test_tensor_cores_upcast_unroll_minimal`
UOps.PHI is parent to the next WMMA loop child.
The spec in this diff specifies that PHI should be the stopping point of loop children. following the flow: RANGE -> DEFINE_ACC -> PHI -> ENDRANGE
WMMA [doesn't follow this structure](https://github.com/tinygrad/tinygrad/blob/4753283221e9f32ffdc228ce7798d86eecb120f8/tinygrad/codegen/linearizer.py#L251-L254).
> proposal: PHI nodes in TC shouldn't have children inside the loop

- test/test_uop_graph.py
- tinygrad/codegen/uops.py
continue from #4700. PtrDType comparison can be cleaned up separately
NOTE: this was in the first uop refactor pr and later changed to using `is` https://github.com/tinygrad/tinygrad/pull/4560/files#diff-91ca5e2e75ef3ea1982c8ca6cc175ee88f20efa0d8e4b96f305b970dc6df71e7R233-R234
> fix UOps.CAST noop for vectorized dtypes

- test/test_dtype.py
Sometimes called Dtype sometimes DType - pain to call manually
> Unify test_dtype naming conventions

- docs/index.md
- docs/quickstart.md
- docs/showcase.md
replaced the "Index" from Home page with "tinygrad documentation"
> docs: update page headers

- tinygrad/codegen/kernel.py
- tinygrad/codegen/linearizer.py
In multireduce tensor core kernels, we need to:
1. Map tensor core bufs to reduceop
2. Map the alias of those bufs
Allowing reduce_reduceop access to the local aliases of its A and B.
verified correctness in the full linearizer diff: #4742
The assumption for now is to fuse reduces with exactly the same shape and strides.
> map tensor core bufs to reduceop

- tinygrad/codegen/kernel.py
Creates tc opts for all reduces and asserting they're exactly the same.
This needs two new options for `TensorCoreOptions`
Verified multireduce correctness with https://github.com/tinygrad/tinygrad/pull/4742
kernel.py expectations from the scheduler:
1. If one reduceop triggered tc but the other didn't
2. If all triggered tc but on different axes
Both are wrong scheduling.
> refactor tc_opt creation

- test/external/external_test_lm_head.py
133ms on tinybox red with BEAM=2
> isolate the 134ms kernel in train_gpt2.py

- test/test_arange.py
with hcopt, arange(2560) uses less ops than arange(256)
> apply NOOPT in test_arange complexity

- test/test_linearizer.py
- tinygrad/codegen/kernel.py
tests correctness of two fused matmuls in a single kernel based on their shapes, strides and pads.
> add fused tc opts tests

- test/test_symbolic_jit.py
- test/test_symbolic_ops.py
- test/test_symbolic_shapetracker.py
- tinygrad/lazy.py
currently not supporting const fold symbolic shape. I think it's possible with a refactor to `Tensor.from_node`.
also added some failed required tests for symbolic arange.
> fix lazy r const folding with variable shape

- .github/workflows/benchmark.yml
- tinygrad/codegen/linearizer.py
Triggers ASSERT_COMPILE=1 if your commit has `[run_process_replay]` in the message. Enabling this in benchmarks is a starting point and we wanna support:
1. All CI tests
2. BEAM=2 process replay
example of catching kernel change: https://github.com/tinygrad/tinygrad/actions/runs/9329767427/job/25682587397
example of untriggered process replay https://github.com/tinygrad/tinygrad/actions/runs/9329864104/job/25682791707
> process replay benchmarks

- tinygrad/codegen/linearizer.py
Tensor cores change the idxs in the middle of rendering a reduceop.
However, this change should happen only once per kernel no matter how many reduceops we wanna render.
With this diff, indexes into the local aliases are computed before rendering any reduceops.
The expected diff for two matmuls of exactly the same TensorCoreOptions on different `a` and `b` in one kernel is:
```diff
- extern "C" __global__ void test(half* data0, const half* data1, const half* data2) {
+ extern "C" __global__ void test(half* data0, const half* data1, const half* data2, const half* data3, const half* data4) {
int alu9 = (alu4+alu5+alu8+alu7+alu3);
+   // first reduce
half val0 = data1[alu9];
half val1 = data1[alu9+1];
half val2 = data1[alu9+8];
// ...
half val11 = data2[alu10+144];
float4 wmma0 = …
```
> compute aliased buffer idxs pre reduce

- .github/workflows/test.yml
When we squash and merge the commit history is in the message so `[run_process_replay]` still gets triggered. This skips process replay for squashed merges.
> skip process replay on master

- tinygrad/tensor.py
10% less kernel for `test/models/test_train.py::TestTrain::test_transformer`, should make llm.c faster
> layernorm backward is indepedent of its mean

- test/test_tensor.py
- tinygrad/shape/view.py
set strides to 0, offset to 0, mask to None, and contiguous to True with size 0 view. It matches numpy stride too.
> canonicalize 0 in shape in View.create

- tinygrad/engine/search.py
added a flag `BEAM_STRICT_MODE` to catch compile error or other exceptions on demand
> default skip all exception in beam

- test/test_pattern_matcher.py
Logic to recognize arg sets in the pattern matcher was added in #4728. It would correctly reject uops if the arg was not in the set, but it would also fail to match on uops with args in the set. This regression test demonstrates this.
https://github.com/tinygrad/tinygrad/pull/4821#issuecomment-2147112516
> Add arg set regression test for pattern matcher

- tinygrad/codegen/uops.py
Makes things consistent with arg, also this addresses most of the performance regression in #4791.
Average over 10 runs on an m1 macbook air:
master
```
forward 29.906 ms
schedule 9.563 ms
lower 1571.959 ms ​
```
this branch:
```
forward 29.568 ms
schedule 9.413 ms
lower 1479.284 ms ​
```
> Nest ifs for dtype and uop in pattern matcher

- test/test_linearizer.py
Disabled on AMD and NV but was enabled for PTX
```
289.44s call     test/test_linearizer.py::TestKernelOpts::test_padto_matmul
```
> Disable slow test_padto_matmul for PTX 

- tinygrad/runtime/ops_nv.py
Need to be sure that self.lib_gpu allocated from LRU cache of NVAllocator is not accessed any more
> nv sync program copies to other execution

- .github/workflows/test.yml
- test/external/replay_codegen.py
- test/test_fusion_op.py
- tinygrad/codegen/linearizer.py
This diff rewrites process replay to:
1. Save every instance of a Linearizer created in HEAD
2. Recreate that Linearizer in master with ast, applied_opts, opts
3. Assert Program.src is the same.
This allows process replay to take max 2 minutes instead of 16-19 minutes per backend.
The drawback of ASSERT_COMPILE=1 is that even if only the Linearizer.name changes it can fail, making it fragile and slow (tests can't run with -n=auto).
> faster codegen process replay

- tinygrad/runtime/ops_amd.py
hmm, this syscall was really slow. it caused this python time jumps.
```
61   53.93 ms run,   20.71 ms python,   33.22 ms AMD * 6,  761.67 loss, 0.000583 LR, 8.85 GB used,  37310.47 GFLOPS,   2012.20 GOPS
62   53.89 ms run,   20.83 ms python,   33.05 ms AMD * 6,  765.66 loss, 0.000521 LR, 8.85 GB used,  37340.07 GFLOPS,   2012.20 GOPS
63   53.85 ms run,   20.84 ms python,   33.01 ms AMD * 6,  763.53 loss, 0.000459 LR, 8.85 GB used,  37364.62 GFLOPS,   2012.20 GOPS
64   53.77 ms run,   20.62 ms python,   33.15 ms AMD * 6,  771.70 loss, 0.000397 LR, 8.85 GB used,  37420.01 GFLOPS,   2012.20 GOPS
65   53.93 ms run,   20.75 ms python,   33.18 ms AMD * 6,  756.53 loss, 0.000335 LR, 8.85 GB used,  37309.97 GFLOPS,   2012.20 GOPS
```
vs
```
61   61.96 ms run,   29.13 ms python,   32.83 ms AMD * …
```
> do not sleep immediately in amd's wait_signal

- tinygrad/codegen/linearizer.py
Because this variable is only defined in an assert, all commands ran with `-O` break on L426. @Qazalin
> fix: variable defined in assert breaks -O

- tinygrad/codegen/linearizer.py
- tinygrad/codegen/uops.py
This folder was missing an `__init__.py` file, so the contents were not linted. Same problem for the folders in `runtime`.
This PR adds the file and fixes the warnings. I am not happy with the ignore on the `g_valid` issue.
Here are the warnings after adding the `__init__.py` file:
```
pylint...................................................................Failed
- hook id: pylint
- exit code: 14
************* Module tinygrad.codegen.uops
tinygrad/codegen/uops.py:277:8: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
************* Module tinygrad.codegen.linearizer
tinygrad/codegen/linearizer.py:92:68: E0606: Possibly using variable 'g_valid' before assignment (possibly-used-before-assignment) …
```
> fix: pylint will not lint folders without __init__.py

- tinygrad/codegen/linearizer.py
- tinygrad/engine/schedule.py
- tinygrad/ops.py
Tensor variable break process replay because they create ASTs with bound Variables. https://github.com/tinygrad/tinygrad/issues/4860
This diff unbinds the Variable before LazyOping.
before: `test/test_symbolic_jit.py TestSymbolicJit.test_var`
```
0 ━┳ STORE MemBuffer(idx=0, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(1, 1), strides=(0, 0), offset=0, mask=None, contiguous=True),)))
1  ┗━┳ DIV 
2    ┣━┳ SUM (0, 1)
3    ┃ ┗━━ LOAD MemBuffer(idx=1, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(Variable('i', 1, 10), 3), strides=(3, 1), offset=0, mask=None, contiguous=True),)))
4    ┗━┳ CAST dtypes.float
5      ┗━┳ MUL 
6        ┣━━ CONST ConstBuffer(val=Variable('i', 1, 10).bind(1), dtype=dtypes.int, st=ShapeTracker(views=(View(shape=(1, 1), strides=(0, 0), offset=0, …
```
> unbind Variable pre LazyOp

- test/external/replay_codegen.py
#4873 fixes the nondeterminism in process replay.
> raise assert [run_process_replay]

- examples/yolov8.py
As per the "Key Changes" section of [this July 2023 PR](https://github.com/ultralytics/ultralytics/pull/3748), the YAML files have since been relocated (_previously [here](https://github.com/ultralytics/ultralytics/tree/2c6fc0a4443b9cf805ef17b1cfdd71a98693b4d4/ultralytics/models/v8)_).
As such, since the reference comment doesn't point to a fixed commit, the URL leads to a 404.
> docs: Update referenced yaml in `yolov8.py`

- tinygrad/tensor.py
taking some good stuff from the #4886. I think `from_, to` is more readble than `sh, s` too [run_process_replay]
> expand broadcast functions a bit

- tinygrad/codegen/kernel.py
- tinygrad/renderer/__init__.py
For process replay to work correctly, any Linearizer should be reproducible just from these there:
1. ast
2. applied_opts
3. opts
This diff moves the optimizations that get applied from env vars dynamically to a property on the Renderer.
> expose tensor core optimization options to Renderer

- tinygrad/lazy.py
removed pylint: disable=possibly-used-before-assignment [run_process_replay]
> cleanup lazy const fold for binary

- test/test_ops.py
backward failed when correction >= reducing n
> test case for Tensor.var reducing over size = 1 axis

- test/test_nn.py
- tinygrad/tensor.py
it's only correct in LayerNorm where input is the data, and not correct in GroupNorm and InstanceNorm that reused layernorm. Added backward tests for weights, bias and input for these norms.
> revert the .detach() in layernorm

- test/test_ops.py
default [low, high] changed from [-1.5, 1.5] to [-2, 2] (except tan). dropped several explicit atol if it's unnecessarily larger than default 1e-6. tested on mac, tinybox red / green
> widen test_ops [low, high] and more strict atol

- test/unit/test_uop_symbolic.py
- tinygrad/codegen/linearizer.py
- tinygrad/codegen/uops.py
This does make things slower due to the extra BFS on the UOps graph, but it isolates UOp construction from the graph and will allow speedups there.
The key victory is removing state from the Linearizer.
> don't use uops.add while constructing

- tinygrad/codegen/linearizer.py
there was a bug in render_block because of accs not being typed.
This diff also showed a lot of places in the code where idx are wrongly/incompletely typed. These should all be just a List[UOp]
> more typing in linearizer uoping utils

- test/test_ops.py
- tinygrad/tensor.py
it's fine if `self.shape[d] >= index.shape[d]` for all `d != dim`, not for all `d`
> fix Tensor.gather shape checking criteria

- test/test_fuzz_shape_ops.py
Fix for test `test/test_fuzz_shape_ops.py` to be able to run by python3.8
`python3 -m pytest test/test_fuzz_shape_ops.py` would others fail.
> fix typing for test to run in py38

- test/test_ops.py
- tinygrad/tensor.py
`where(self, 0)` incorrectly upcasted the output. `where(self, False)` is correct but looks unnatural, so added a cast at the end. Pattern matcher can fold the cast into where branches
> fix Tensor.triu / Tensor.triu with boolean input

- test/test_ops.py
- tinygrad/tensor.py
The bug before was when there were consecutive Nones paired with other advanced indexing...
This PR fetches the dimensions before taking out the Nones so that it's pinned (no longer need to calc it). 
Also added a few more test cases.
Still the code isn't pretty... at least it's correct now I think.
> Getitem pin None dimension

- tinygrad/runtime/graph/hcq.py
- tinygrad/runtime/ops_amd.py
- tinygrad/runtime/ops_nv.py
Add `memory_barrier` to HCQ API. Calling this function ensures that all preceding writes are visible to any agent (GPU or CPU). This allows controlling HDP flushes and removes the need to call it from every execution. For now, it is implemented only for AMD; will relax NV constraints later.
> hcq add memory_barrier

- tinygrad/codegen/linearizer.py
- tinygrad/codegen/uops.py
Linearizer uops are stateless now.
This is the first step to deleting ctx from `render_ops`
> delete Linearizer.const [run_process_replay]

- examples/openpilot/compile2.py
- extra/models/mask_rcnn.py
- extra/onnx.py
- test/external/external_test_opt.py
- test/external/fuzz_linearizer.py
- test/external/fuzz_schedule.py
- test/external/fuzz_uops.py
- test/external/speed_compare_cuda_nv.py
- test/helpers.py
- test/test_dtype.py
- test/test_dtype_alu.py
- test/test_linearizer.py
- test/test_ops.py
- test/test_tensor.py
- test/test_uops.py
- tinygrad/dtype.py
- tinygrad/tensor.py
replaced all dtype.np with _to_np_dtype defined in tensor.py.
after this, the only numpy usages are (1) Tensor(np.ndarray), (2) construct .numpy() output, (3) numpy random buffer
> remove numpy from dtype

- examples/llama3.py
- setup.py
- test/unit/test_helpers.py
- tinygrad/helpers.py
adds subdir support in the fetch download cache
flips `--api` to `--no_api` to have api enabled by default
> easier llama3 + fetch subdir

- tinygrad/codegen/uops.py
Tried to make rewrite fast but in the end it's not significantly faster than before.  
However I've achieved some line reduction that are nice to have, I guess.
In my local bench `PROFILE=0 python test/external/external_benchmark_schedule.py` lower was like ~30ms faster so has i said not significantly faster. But the new way to refresh cached property is [indeed faster](https://pastebin.com/xNKgyRg8).
The setdefault is exactly the same speed but it's nice for line reduction
> perf: graph_rewrite line reduction and make it a little bit faster

- tinygrad/tensor.py
it was using `Expands`, the same in torch doc, but we also have expand so it's confusing
> docs: update wording for unflatten

- tinygrad/runtime/graph/hcq.py
- tinygrad/runtime/ops_nv.py
`BEAM=2 NV=1 python3 examples/llama.py --temperature 0 --count 10 --prompt "Hello." --timing --shard 4`
```
enqueue in   4.48 ms
total   9.55 ms, 104.73 tok/s, 1466.57 GB/s, param 1412.44 GB/s
```
> hcq optimize enqueue time

- test/test_uops.py
- tinygrad/codegen/uops.py
x+-y -> x-y rule didn't cover -y+x which is the same because a + b = b + a and my nicer uops always does that, but because this rule didn't cover that case that it was probably supposed to cover process replay broke
Here's diff:
Old rule:  21)))+(-(((val
New rule: val21)))-(((val
etc
> Incomplete/buggy rule breaks process replay on #4976

- .github/workflows/benchmark.yml
The stable diffusion example generates non-deterministic kernels, so even if tinygrad has a noop change there is no cached version of that kernel.
https://github.com/tinygrad/tinygrad/actions/runs/9528414804/job/26266055472
> hotfix: don't use ASSERT_COMPILE for benchmarks process replay

- test/unit/test_disk_tensor.py
test takes about 9 seconds. more importantly this is the only unit test that covered reading off pkl format
> re-enable test that loads torch pkl format

- test/test_dtype.py
- tinygrad/tensor.py
more flexible to not automatically downcast, can fix bert mixed precision training with this
> matmul returns in acc_dtype if specified

- test/external/replay_codegen.py
- tinygrad/codegen/linearizer.py
- tinygrad/codegen/uops.py
The UPat compiler diff had this extra workaround for process replay.
https://github.com/tinygrad/tinygrad/actions/runs/9534387266/job/26278750344
fixes process replay to test the src returned from to_program instead of rerendering.
> check Program from HEAD [run_process_replay]

- test/test_schedule.py
- tinygrad/engine/schedule.py
Currently the scheduler only accounts for the last view, it should instead check all views in the ShapeTracker for masks and correctly unfuse unsafe pads:
`(View(shape=(2, 4), strides=(0, 1), offset=-1, mask=((0, 2), (1, 4)), contiguous=False), View(shape=(8,), strides=(1,), offset=0, mask=None, contiguous=True))`
Kernel diff with NOOPT=1
master:
```
kernel void E_8(device float* data0, const device float* data1, const device float* data2, uint3 gid [[threadgroup_position_in_grid]], uint3 lid [[thread_position_in_threadgroup]]) {
int gidx0 = gid.x; /* 8 */
int alu0 = (gidx0%4);
bool alu1 = (0<alu0);
float val0 = (alu1?*(data1+alu0+(-1)):0.0f);
float val1 = (alu1?*(data2+0):0.0f);
*(data0+gidx0) = (val0*(1/val1));
}
```
this branch:
```
kernel void E_3_3(device float* data0, const device …
```
> look for unsafe pad ops in multiview ShapeTrackers

- examples/yolov8.py
it was creating Tensor from a list of numpy arrays, which is not supported after moving creating from a list not using numpy.
with this pr
```
tinygrad git:(fix-yolov8) ✗ PYTHONPATH=. python3 examples/yolov8.py https://encrypted-tbn0.gstatic.com/images\?q\=tbn:ANd9GcQ4YOtOwhKH61_mrmCEIKBViQ3JEfwPlz2SEZClZqKDp4XkjdjV
No variant given, so choosing 'n' as the default. Yolov8 has different variants, you can choose from ['n', 's', 'm', 'l', 'x']
running inference for YOLO version n
ram used:  0.01 GB, head.cv2.2.2.bias                                 : 100%|████████████████████████████████████████████████████████| 355/355 [00:00<00:00, 12818.35it/s]
loaded weights in  28.26 ms, 0.01 GB loaded at 0.22 GB/s
did inference in 39ms
copying to CPU now for post processing
Image 1:
Objects detected:
- …
```
> fix yolov8 example

- test/test_ops.py
- tinygrad/tensor.py
Found this small bug on the einsum output string while implementing ellipsis support for einsum.
Bug occurs when there's no "->" in the formula (so empty rhs) and multiple input operands
In this case output string should be sorted and repeated characters should be summed over (removed)
> fix einsum output str

- test/test_ops.py
- tinygrad/ops.py
without special handling, it throws ValueError: math domain error
> python_alu sin(inf) is nan

- test/test_dtype.py
- test/test_tensor.py
- tinygrad/ops.py
- tinygrad/runtime/ops_python.py
- tinygrad/tensor.py
use `truncate` when constructing tensor from list to make sure all values are packable (might be slow, but should be correct). add truncate_fp16 to cast overflowed values to inf/-inf.
> handle float16 overflow in PYTHON

- .github/workflows/test.yml
- test/test_dtype.py
- test/test_dtype_alu.py
- test/test_tensor.py
- test/unit/test_disk_tensor.py
- tinygrad/ops.py
added test_dtype_alu for PYTHON backend, everything passed except a inf to int cast. Also skipped some uint tests that numpy changed behavior and threw errors in 2.0.
>  RECIP(-0.0) should be -inf

- tinygrad/runtime/graph/hcq.py
- tinygrad/runtime/ops_nv.py
NV llama now:
```
enqueue in   3.87 ms
total   8.53 ms, 117.21 tok/s, 1638.39 GB/s, param 1580.82 GB/s
male
```
Rework of #4916
> hcq signal scheduler

- test/test_ops.py
- tinygrad/tensor.py
raise RuntimeError to match torch. on master it throws weird errors from shapetracker
> check Tensor.reshape can have at most one -1

- examples/mlperf/model_train.py
For large BS, the current LR and total steps won't work. LR scaling is derived from the [reference](https://github.com/mlcommons/logging/blob/master/mlperf_logging/rcp_checker/training_4.0.0/rcps_bert.json):
> Better default hparams for large BS

- test/test_dtype.py
- test/test_tensor.py
- tinygrad/tensor.py
numpy 2.0 does not allow oob python const and recommends writing as `np.array(value).astype(dtype)`
> fix out of bound python list into numpy array

- tinygrad/runtime/ops_python.py
the two errors (cell-var-from-loop and arguments-out-of-order) does not apply as we use it as intended. fix #4877
> update pylint for ops_python

- tinygrad/tensor.py
used `math.sqrt(2 / math.pi)` instead of `0.7978845608`, and moved one mul self inside parentheses. this matched the paper and llm.c
> minor change to gelu

- tinygrad/codegen/linearizer.py
- tinygrad/codegen/uops.py
winning back lines from the has_valid diff #5052
- remove redundant/uneven whitespace
- remove dead code
- UOp.store should've never had a dtype arg
> UPat line savings [run_process_replay]

- test/test_uop_graph.py
- test/test_uops.py
- tinygrad/codegen/uops.py
This diff folds symbolic NumNode 0 and 1 and CONST literal True and False gates.
After the symbolic removal we should always render a literal boolean for valid and remove the `None` in UPat.
> generic gate folding

- test/test_linearizer.py
.empty is dangerous because it doesn't mean anything for correctness.
Also removed the `test_tensor_cores_upcast_unroll_minimal` test, it's tested in a much better way by `test_tensor_cores_unroll_phi` and `test_tensor_cores_unroll_casted_phi`
> don't use Tensor.empty in kernel opts tests

- test/test_ops.py
- tinygrad/tensor.py
previous error message with multiple `...`:
```
if index_type not in [None, int, slice, Tensor]: raise IndexError(f"{index_type=} not supported")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: index_type=<class 'ellipsis'> not supported
```
this pr:
```
if len(ellipsis_idx) > 1: raise IndexError("an index can only have a single ellipsis ('...')")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: an index can only have a single ellipsis ('...')
```
> explicitly check getitem indices can have at most one ellipsis

- extra/models/llama.py
following the original implementation, cast back to input dtype before multiplying weight. slightly faster https://github.com/meta-llama/llama/blob/main/llama/model.py
> update llama model RMSNorm casting

- test/test_dtype.py
- tinygrad/tensor.py
mid cast to default_float does not work as intended when default is float32 and qkv is in half
> fix attention to always return in the same dtype as input

- test/unit/test_tqdm.py
- tinygrad/helpers.py
per doc `https://tqdm.github.io/docs/tqdm/`, user does not need to put `: ` in desc, and `: ` is automatically removed after desc if the latter is empty.
updated test cases and added a test for set_description
> fix desc in tqdm

- tinygrad/device.py
- tinygrad/helpers.py
Use just one X-type event. almost 2x less trace size.
> tiny profiler cleanups

- test/test_multitensor.py
- tinygrad/multi.py
it's incorrect to assume all first (len(device)-1) shards would have the same size. e.g. size 2 shard 4 -> (1, 1, 0, 0)
> fix uneven shard with shrink and pad args on sharded axis

- .github/workflows/test.yml
- test/external/process_replay/process_replay.py
- tinygrad/codegen/linearizer.py
As long as we can recreate LazyOp, OptOps and Renderer, process replay should run correctly. Fixes #5143
> limit pickled objects [run_process_replay]

- examples/llama3.py
applying #5123 to llama3 as well
`JITBEAM=4` on red
shard 4: 36.94 -> 39.10 tok/s
shard 2: 48.26 -> 62.29 tok/s
> shard llama3 on 0 sometimes

- extra/models/resnet.py
Update shapes to work with unsynced batchnorm
Need to use unsynced instead of synced to get fp16 training working for retinanet, This is also a bug which I think has to do with lack of casting in synced batchnorm. I tried fixing, but it increased step times.
Repro:
```
import functools
from typing import List
from tinygrad import dtypes, Tensor, GlobalCounters
from tinygrad.helpers import getenv
from extra.models import resnet
from examples.mlperf.initializers import Conv2dHeNormal, Linear
from examples.hlb_cifar10 import UnsyncedBatchNorm
def _sum(x:List[Tensor]):
ans = x[0].mean()
for xx in x[1:]:
ans+=xx.mean()
return ans 
if getenv('BN', 1): resnet.BatchNorm = functools.partial(UnsyncedBatchNorm, num_devices=1)
resnet.Conv2d = Conv2dHeNormal
resnet.Linear = Linear
res = …
```
> Fix batchnorm shapes for resnet.load_pretrained

- .github/workflows/benchmark.yml
- tinygrad/engine/search.py
ignoring beam cache but using compile cache should be fine, saved some benchmark time.
also updated `beam_search` to check flag value before accessing diskcache
> CACHELEVEL=0 -> IGNORE_BEAM_CACHE=1 in benchmark

- examples/sdxl.py
- examples/stable_diffusion.py
Brings in SDXL 1.0 Base inference code for image generation.
The code currently still has all of my references, can take them out if that's wanted.
On my 4060ti 16 GB it takes ~8 seconds for the first step and ~4 seconds for each additional step at 1024x1024 resolution.
Custom image sizes is also supported:
Custom model weights can easily be used (Juggernaut XL in this case):
> Add SDXL Inference to Examples

- tinygrad/shape/view.py
it checks if `axis` is a valid permutation, which is the same as `sorted(axis) == list(range(len(self.shape)))`
> simplify View.permute arg check [run_process_replay]

- test/test_uop_graph.py
- tinygrad/codegen/linearizer.py
- tinygrad/codegen/uops.py
Prevents the Linearizer from rendering NumNode(0) and NumNode(1) for valids. Now all non-bool gates are asserted in the UOps type checker.
> test: valid is always bool [run_process_replay]

- test/test_dtype_alu.py
- test/test_ops.py
- test/test_uops.py
- tinygrad/function.py
- tinygrad/ops.py
- tinygrad/renderer/assembly.py
- tinygrad/renderer/cstyle.py
- tinygrad/renderer/llvmir.py
- tinygrad/tensor.py
This PR contains the changes for adding `BinaryOps.AND` and `BinaryOps.OR`, separated from https://github.com/tinygrad/tinygrad/pull/5173.
BinaryOps.AND/OR are used for approximating the SIN/LOG2/EXP2 functions. https://github.com/tinygrad/tinygrad/pull/5187
- Added new uops: `BinaryOps.AND`, `BinaryOps.OR` in `tinygrad/ops.py`
- Implemented `Tensor.bitwise_and`, `Tensor.bitwise_or` in `tinygrad/tensor.py`
- Introduced `BitwiseAnd` and `BitwiseOr` classes in `tinygrad/function.py`
- Added unit tests for the new methods `bitwise_and` and `bitwise_or`
> [Feature] Added BinaryOps.AND/BinaryOps.OR

- examples/sdxl.py
- examples/stable_diffusion.py
- extra/models/clip.py
- extra/models/unet.py
- test/external/external_test_jit_on_models.py
- test/models/test_real_world.py
The abstracted CLIP and UNet models got pulled into their own respective files in the `extra/models` folder.
`examples/stable_diffusion.py` and `examples/sdxl.py` both had their implementations of these models removed and reference the common model.
```sh
$ NV=1 python3 examples/stable_diffusion.py --seed 0 --noshow
output validated with distance=7.163018835854018e-07
```
```sh
$ NV=1 python3 examples/sdxl.py --seed 0 --noshow
output validated with distance=0.0012854303931817412
```
> Pulled CLIP and UNet into Seperate Files

- tinygrad/codegen/uops.py
This diff is a small redundancy removal, turns out to be faster too:
```
***** model forward in  54.62 ms
***** model schedule in  17.24 ms
***** model lower in 1658.15 ms
***** model forward in  54.59 ms
***** model schedule in  17.36 ms
***** model lower in 1641.64 ms
```
> iterate over scoped uops once [run_process_replay]

- tinygrad/codegen/uops.py
- tinygrad/renderer/assembly.py
- tinygrad/renderer/cstyle.py
- tinygrad/renderer/llvmir.py
The Linearizer upcasts stores in uop creation, for auto-barrier LOAD needs an extra check on the UOp before rendering it as a gate.
> refactor gated load rendering [run_process_replay]

- test/models/test_real_world.py
The `test_real_world.py` was not updated properly and was calling UNet with the wrong params, causing an exception when run.
```
$ python3.10 test/models/test_real_world.py
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
test_gpt2: used 0.84 GB and 4 kernels in 11.21 ms
.test_llama: used 14.02 GB and 5 kernels in 199.53 ms
.test_mini_sd: used 0.00 GB and 2 kernels in 0.12 ms
.test_sd: used 4.84 GB and 7 kernels in 441.92 ms
.train_cifar: used 2.57 GB and 3 kernels in 216.24 ms
..train_mnist: used 0.06 GB and 2 kernels in 4.05 ms
.
----------------------------------------------------------------------
Ran 7 tests in 81.659s
OK
```
> Fixed UNet Call Params

- tinygrad/device.py
- tinygrad/runtime/ops_amd.py
- tinygrad/runtime/ops_nv.py
While working on qcom allocator, spent some time to dive into the copyin, copyout, transfer and offset of HCQCompatAllocator to find out that they require allocated memory object to have "va_addr" and other stuff
So this change make allocator abstraction more transparent
_It adds 3 new lines of code btw, so if it is considered to be superfluous, I'm ok :)_
> add return type for HCQCompatAllocator _alloc

- test/test_verify_lazyop.py
- tinygrad/ops.py
Consolidates all the shape asserts to the implicit movement ops check.
The assert in l158 was incomplete for multi reduce, the shape equivalence assert already catches this too.
kernel.py needs shapetracker fixups to not reduce the extra axis:
```
__kernel void r_32_32_32(__global float* data0, const __global float* data1) {
for (int ridx0 = 0; ridx0 < 32; ridx0++) {
for (int ridx1 = 0; ridx1 < 32; ridx1++) {
for (int ridx2 = 0; ridx2 < 32; ridx2++) {
float val0 = data1[(ridx0*32)+ridx2];
acc0 = (val0+acc0);
}
}
}
float acc1 = 0.0f;
for (int ridx3 = 0; ridx3 < 32; ridx3++) {
for (int ridx4 = 0; ridx4 < 32; ridx4++) {
for (int ridx5 = 0; ridx5 < 32; ridx5++) {
float val1 = data1[(ridx3*32)+ridx5];
acc1 = (val1+acc0+acc1);
}
}
}
data0[0] = acc1;
}
```
> verify_lazyop with multi reduce

- tinygrad/multi.py
second contiguous guarantees lbs are contiguous going into MultiLazyBuffer, don't need the first contiguous
> remove first contiguous in multi from_sharded

- examples/sdv2.py
- examples/sdxl.py
- extra/models/clip.py
Brings in Stable Diffusion v2 (the version mlperf uses)
Only the `v` version of the model was coded and tested for (the variant mlperf uses)
```
python3.10 examples/sdv2.py --seed 0
```
Generation was also verified against `Stability-AI/generative-models` implementation via noise injection
> Stable Diffusion v2 Inference

- .github/workflows/test.yml
- README.md
the main README example wasn't setting Tensor.training = True nor using the context manager and was giving the following error:
```
python tinygrad_example.py                                                
Traceback (most recent call last):                                                                        
File "/home/snakeonex/fun/tiny-shakespear/tinygrad_example.py", line 18, in <module>                    
optim.step()                                                                                          
File "/home/snakeonex/tinygrad/tinygrad/nn/optim.py", line 34, in step                                  
Tensor.realize(*self.schedule_step())                                                                 
^^^^^^^^^^^^^^^^^^^^ …
```
> fix README example

- tinygrad/renderer/cstyle.py
kernel diff:
```diff
extern "C" __global__ void C_3_8_4(float* data0) {
int gidx0 = blockIdx.x; /* 3 */
int lidx1 = threadIdx.x; /* 8 */
-  *((float4*)(data0+(gidx0*32)+(lidx1*4))) = make_float4(4.0,4.0,4.0,4.0);
+  *((float4*)(data0+(gidx0*32)+(lidx1*4))) = make_float4(4.0f,4.0f,4.0f,4.0f);
}
```
> hotfix: use dtype.scalar() for cstyle render_cast [run_process_replay] [no_assert]

- test/test_uop_graph.py
- tinygrad/codegen/uops.py
`test_cast_alu_fold` is relevant once we fold valid in UPat. Adding extra coverage since deleting the UPat didn't fail in process replay #5289
> uop graph tests + type_verify cleanup

- test/external/fuzz_schedule.py
- tinygrad/engine/schedule.py
Schedule creation returns a tuple describing the AST and its parents.
This gets grouped into a ScheduleItem once the LazyOp asts are fused/rewritten.
> refactor schedule creation

- test/test_multitensor.py
- tinygrad/multi.py
`test_elementwise_dtype` https://github.com/tinygrad/tinygrad/pull/5299/commits/ea5f83b87f5fa3620c0fb0830f7f8447456cc7c9 gives:
```
AssertionError: all multilazybuffer needs same dtype, getting [dtypes.bool, dtypes.float, dtypes.float, dtypes.float]
```
Because `CMPLT = auto(); CMPNE = auto();` change the dtype.
unblocks #5187
> fix dtype mismatch for bool ops in multi

- tinygrad/renderer/llvmir.py
UOps.SPECIAL only applies if the renderer has_local.
> remove UOps.SPECIAL rendering from llvm

- test/test_linearizer.py
the old asserts were bad because they were too strict about UOp count (which the PatternMatcher can mutate).
these tests should only care about relative position rather than absolute measures.
> generalize the uops toposort spec to ptx

- tinygrad/codegen/uops.py
- tinygrad/renderer/cstyle.py
CI proves in cstyle backends a float4 load is already the correct dtype.
also, LOAD's buf_dtype always matches its output_dtype.scalar() (except for PTX where src[0].dtype is rewritten as u64).
```diff
-  float4 val0 = (float4)(*((float4*)(data1+alu0+460)));
+  float4 val0 = *((float4*)(data1+alu0+460));
```
> test: delete the extra cast in cstyle load [run_process_replay] [no_assert]

- examples/handcode_bert_opt.py
- examples/mlperf/helpers.py
- examples/mlperf/model_train.py
I mistakenly set the predicted tokens to 512, which can only be 76 at most. Sorry
Beyond that, I was getting a duplicate input error from the JIT with `INITMLPERF` on. The reason is that e.g. `input_ids`, `input_mask`, and `input_lm_weights` are the same shaped zeros tensors.
> Fix fake dataloader

- test/test_tensor.py
- tinygrad/engine/realize.py
- tinygrad/engine/schedule.py
- tinygrad/helpers.py
- tinygrad/lazy.py
- tinygrad/tensor.py
like #4225 and #4197 and #3302
`traceback` is really slow, just grabbing a frame is relatively fast.
DEBUG=2 output:
```
*** AMD      829 r_512_11_11_32_2_2                     arg   2 mem 12.94 GB tm     74.60us/   349.07ms (  106.30 GFLOPS,  531.49 GB/s) ['max_pool2d']
*** AMD      830 r_128_11_11_32_4_2_2                   arg   3 mem 12.94 GB tm    362.12us/   349.43ms (   87.59 GFLOPS,  131.39 GB/s) ['max_pool2d bw']
*** AMD      831 r_64_16_3_8_3_3_256_3_4_3_3            arg   4 mem 12.94 GB tm   3679.48us/   353.11ms ( 3325.44 GFLOPS,    6.32 GB/s) ['conv2d', 'relu']
*** AMD      832 r_2_8_7_7_8_16_512_4_4_3_3             arg   4 mem 12.95 GB tm   5374.20us/   358.48ms ( 2754.03 GFLOPS,    4.93 GB/s) ['conv2d', 'relu']
*** AMD      833 r_2_8_5_5_8_16_512_4_4_3_3n1           arg   5 …
```
> tensor metadata

- tinygrad/runtime/ops_nv.py
Closes #5334 
Now: `tinygrad.device.CompileError: NvJitLink Error 4, NVJITLINK_ERROR_PTX_COMPILE`
> nv correct error messages with ptx

- test/test_linearizer.py
- test/test_verify_lazyop.py
- tinygrad/codegen/linearizer.py
- tinygrad/ops.py
Also added some syntactic sugar for LazyOp to help with the tests.
Linearizer generates an extra loop dim for mean:
```
kernel void r_81_32_32(device float* data0, const device float* data1, uint3 gid [[threadgroup_position_in_grid]], uint3 lid [[thread_position_in_threadgroup]]) {
int gidx0 = gid.x; /* 81 */
int alu0 = (gidx0*32);
for (int ridx0 = 0; ridx0 < 32; ridx0++) {
float val0 = *(data1+alu0+ridx0);
for (int ridx1 = 0; ridx1 < 32; ridx1++) {
acc0 = (val0+acc0);
}
}
float acc1 = 0.0f;
for (int ridx2 = 0; ridx2 < 32; ridx2++) {
float val1 = *(data1+alu0+ridx2);
float alu1 = (val1+(-(acc0*0.03125f)));
for (int ridx3 = 0; ridx3 < 32; ridx3++) {
acc1 = ((alu1*alu1)+acc1);
}
}
*(data0+gidx0) = acc1;
}
```
This should go away at some point, OK for correctness.
> multi reduce Tensor.var passing verify_lazyop

- test/external/mlperf_bert/external_benchmark_bert.py
Copies `external_benchmark_resnet`
Example output on my 4080:
```
(tinygrad) elwa@atlas:~/repos/tinygrad$ BS=16 CNT=5 DISABLE_DROPOUT=1 DEBUG=0 BEAM=1 DEFAULT_FLOAT=half python3 test/external/mlperf_bert/external_benchmark_bert.py
attention_output-layer, Input: [(16, 512, 1024), (16, 512, 1)]        :      0.98 ms,  35.62 TFLOPS,   389 GB/s,   0.11 GB used,    33 kernels
attention_self-layer, Input: [(16, 512, 1024), (16, 1, 1, 512)]       :      8.56 ms,  18.51 TFLOPS,   493 GB/s,   0.78 GB used,    57 kernels
embedding-layer, Input: [(16, 512), (16, 512)]                        :     96.51 ms,  13.59 TFLOPS,    13 GB/s,   0.33 GB used,    42 kernels
intermediate-layer, Input: [(16, 512, 1024)]                          :      3.46 ms,  41.25 TFLOPS,   235 GB/s,   0.33 GB used,    18 …
```
> Add layerwise performance bench for bert

- tinygrad/shape/view.py
return the new mask if reshaping is possible and None if not, instead of a mask and a bool
> clean up view _reshape_mask [run_process_replay]

- tinygrad/shape/view.py
`Variable.val` asserts if it's None, so unbind does not need to check if `.val` is not None
> tiny View.unbind cleanup [run_process_replay]

- tinygrad/shape/view.py
2 changes @chenyuxyz:
* v.unbind() is atomic, can be called twice to remove the `var_unbound_var` variable
* a function `substitute` (can also be a lambda) reduces some complexity here
One could argue that the 4  `new_...` variables don't have to be created now, but it is more readable to keep them.
> mini refactor: simpler view.unbind

- tinygrad/codegen/uopgraph.py
DEFINE_ACC with no RANGE is rewritten to its base CONST.
> delete extra check in DEFINE_ACC [run_process_replay]

- tinygrad/codegen/uopgraph.py
still o(n-i) but better:
```
***** model forward in  57.86 ms
***** model schedule in  18.09 ms
***** model lower in 2498.97 ms
```
```
***** model forward in  57.45 ms
***** model schedule in  17.80 ms
***** model lower in 1797.98 ms
```
> hotfix: faster UOps.END* insert [run_process_replay]

- test/test_linearizer.py
Uses numpy as the ground turth for checking lowering correctness in https://github.com/tinygrad/tinygrad/pull/5389. Before, it was comparing against NOOPT=0, leading to a false positive.
> hotfix: compare test_var_multireduce against numpy

- test/test_arange.py
- tinygrad/codegen/uopgraph.py
- tinygrad/codegen/uops.py
- tinygrad/engine/graph.py
```
kernel void r_4_256_16384_16384(device float* data0, const device int* data1, const device float* data2, uint3 gid [[threadgroup_position_in_grid]], uint3 lid [[thread_position_in_threadgroup]]) {
int gidx0 = gid.x; /* 4 */
int gidx1 = gid.y; /* 256 */
int val0 = *(data1+gidx0);
for (int ridx0 = 0; ridx0 < 16384; ridx0++) {
float val1 = *(data2+gidx1+(ridx0*256));
acc0 = (acc0+((!(ridx0!=val0))?val1:0.0f));
}
*(data0+(gidx0*256)+gidx1) = acc0;
}
```
have to prevent the load of all 16384 of them.
> improve single kernel indexing

- examples/handcode_bert_opt.py
- examples/handcode_resnet50_opt.py
```
usage:
147.50 ms: ['conv2d bw'] (114 times)
126.90 ms: ['conv2d'] (53 times)
24.79 ms: ['relu bw', 'conv2d bw'] (16 times)
23.58 ms: ['relu bw', 'conv2d bw', '__add__'] (14 times)
17.34 ms: ['relu bw', 'batchnorm bw'] (26 times)
15.36 ms: ['__sub__', '__mul__ bw', '__add__', 'relu bw', 'batchnorm bw'] (17 times)
14.83 ms: ['__sub__', '__mul__ bw', '__add__', 'batchnorm bw'] (35 times)
14.40 ms: ['__sub__', 'batchnorm bw'] (35 times)
11.82 ms: ['__sub__', 'batchnorm', 'batchnorm bw'] (16 times)
11.72 ms: ['__sub__', 'relu bw', 'batchnorm bw'] (17 times)
```
> usage summary in handcode opt

- extra/onnx_ops.py
- test/test_ops.py
- tinygrad/tensor.py
input is n for nrows and optional m for ncols
> update Tensor.eye api to match torch

- test/external/external_benchmark_schedule.py
Run with `hyperfine`:
```bash
FORWARD_ONLY=1 PROFILE=0 hyperfine "python3 test/external/external_benchmark_schedule.py" --show-output --warmup 1
```
> allow benchmarking forward only

- test/test_transcendental.py
found something wrong with float64 sin reduction. @hikettei can you take a look?
```
from tinygrad import Tensor, dtypes
import numpy as np
print(Tensor([39800.0], dtype=dtypes.float64).sin().numpy())
print(Tensor([39800.0], dtype=dtypes.float32).sin().numpy())
print(Tensor([39800.0], dtype=dtypes.float16).sin().numpy())
print(np.sin(np.array([39800.0], dtype=np.float64)))
print(np.sin(np.array([39800.0], dtype=np.float32)))
print(np.sin(np.array([39800.0], dtype=np.float16)))
```
```
CLANG=1 python test.py
[0.92785633]
[0.7428573]
[-0.7705]
[0.74285722]
[0.7428572]
[-0.7705]
```
> fuzz test transcend math

- docs/env_vars.md
During the conversation here https://github.com/tinygrad/tinygrad/issues/5408 I realized that the JIT env var was not documented, so after a bit of digging in the codebase I added it. I hope I got value 2 right.
> docs: addded JIT description to dos/env_vars.md

- test/external/process_replay/process_replay.py
- test/external/process_replay/reset.py
- tinygrad/codegen/kernel.py
adding to repro this llama 3 8b failure: https://github.com/tinygrad/tinygrad/actions/runs/9920520242/job/27407496131#step:13:107
GITHUB_SHA isn't unique because runs can be manually retried.
> restore process replay runs by their id

- test/external/process_replay/process_replay.py
resolves https://github.com/tinygrad/tinygrad/actions/runs/9921751542/job/27410052371?pr=5455
It's ok if each process resolves this independently.
> hotfix: ASSERT_PROCESS_REPLAY sometimes doesn't exist

- tinygrad/codegen/uopgraph.py
- tinygrad/codegen/uops.py
~~adds UOp ability to express "all permutations of src",~~ rewrites more patterns in the new UOp style
First PR towards hopefully a bigger refactor. Making UOp equally expressive means they could pattern match without UPat at all. At the very least UPat could be refactored to a dataclass with cleaner types and one constructor (compile).
Patterns UOp can't express yet:
> new UOp style patterns [run_process_replay]

- test/test_hcq.py
- tinygrad/runtime/ops_nv.py
Signaling on the copy queue uses 32bit signal, so limit timeline signal to 32bits then wrap. Test now check wait/signals on both queues
> nv fix timeline signal rollover on copy queue

- test/test_linearizer.py
- tinygrad/codegen/lowerer.py
changed from
```
int gidx0 = gid.x; /* 4096 */
int lidx4 = lid.x; /* 8 */
int gidx1 = gid.y; /* 7 */
int lidx5 = lid.y; /* 8 */
int gidx2 = gid.z; /* 7 */
int lidx6 = lid.z; /* 2 */
```
to
```
int gidx0 = gid.x; /* 4096 */
int lidx0 = lid.x; /* 8 */
int gidx1 = gid.y; /* 7 */
int lidx1 = lid.y; /* 8 */
int gidx2 = gid.z; /* 7 */
int lidx2 = lid.z; /* 2 */
```
the existing one started from pre-limited global dims which skip number if there are more than 3 global dims
> render lidx starting with 0

- test/test_ops.py
- tinygrad/tensor.py
- Added a `padding` parameter to `avg_pool2d` and `max_pool2d` along with a `count_include_pad` parameter to the former to match pytorch
- Extracted padding parameter computation from `conv2d` to be commonly used amongst `conv2d`,  `avg_pool2d`, and `max_pool2d`
- Expanded regression tests against new parameters
> Add Pad to Pooling

- tinygrad/renderer/__init__.py
- tinygrad/renderer/assembly.py
- tinygrad/renderer/cstyle.py
With the new lowerer, thread_local_aliases are no longer used
num_upcasts aren't either
> Remove outdated thread_local_aliases

- test/external/speed_compare_cuda_nv.py
- test/external/speed_compare_cuda_ptx.py
- test/test_speed_v_torch.py
- tinygrad/helpers.py
Moved `colorize_float` (used in speed tests) to `helpers.py`.
as per
https://github.com/tinygrad/tinygrad/blob/e21910367768fe034e7b9876d10e694b4cc743f6/test/external/speed_compare_cuda_ptx.py#L9-L10
Let me know if I should make a seperate PR to update all references to it, or keep working in this one.
> move colorize_float to helpers.py

- .github/workflows/docs.yml
- .github/workflows/test.yml
Adds a mkdocs check on https://github.com/tinygrad/tinygrad/blob/master/.github/workflows/docs.yml to avoid errors like the one reported in https://github.com/tinygrad/tinygrad/issues/5496
I have added the check after `mkdocs gh-deploy --force` to make sure that the documentation is deployed anyway. If needed I can switch them of course.
Let me know if you would like me to proceed with this adjustment or if there are any other changes required.
> add strict mkdocs check

- test/test_ops.py
existing trunc test passes backward but its backward is incorrect in general. added tests that would fail
> add 0d tensor to trunc/floor/ceil/round tests

- extra/models/inception.py
Added the base Inception model and the FID variant required for Stable Diffusion mlperf.
Ran identical inputs through tinygrad and pytorch versions of FidInceptionV3 and compared outputs in the following ways:
| Computation | Value |
| :-: | :-: |
| `mean(abs(tiny - torch))` | 0.0004 |
| `mean(abs(tiny))` | 0.3080 |
| `mean(abs(torch))` | 0.3080
> FID Inception Model

- docs/abstractions2.py
restore known abstractions behaviour
```python
******** first, the runtime ***********
5
******** second, the Device ***********
0 UOps.DEFINE_GLOBAL  : PtrDType(dtypes.int)      []                               (0, True)
1 UOps.DEFINE_GLOBAL  : PtrDType(dtypes.int)      []                               (1, False)
2 UOps.DEFINE_GLOBAL  : PtrDType(dtypes.int)      []                               (2, False)
3 UOps.CONST          : dtypes.int                []                               0
4 UOps.LOAD           : dtypes.int                [1, '0']                         None
5 UOps.LOAD           : dtypes.int                [2, '0']                         None
6 UOps.ALU            : dtypes.int                [4, 5]                           BinaryOps.ADD
7 UOps.STORE          : …
```
> fix abstracions2 printout

- test/external/process_replay/process_replay.py
This is because https://github.com/tinygrad/tinygrad/actions/runs/9996754763/job/27631802686 ran exactly when master changed state. if [run_process_replay] is green pre merge it's ok.
> hotfix: don't assert process replay in master

- docs/runtime/overview.md
I was reading through the Runtime Overview docs section and came across some small typos.
> Fix typo in Runtime Overview docs

- tinygrad/codegen/uops.py
`dtypes.is_int` is not the same as `dtype == dtypes.int`
> correct IDIV dtype check error msg

- test/test_linearizer.py
`x.argmax(0, False)` raises AssertionError: repeated stores in uops
with handcoded opts:
```
Opt(op=OptOps.UNROLL, axis=1, amt=0), Opt(op=OptOps.LOCAL, axis=0, amt=4)
```
NOOPT=1 is green.
AST from fuse_index https://github.com/tinygrad/tinygrad/pull/5590
> test argmax multi reduce failure in uopgraph

- extra/mcts_search.py
MCTS 500 is competitive with BEAM=8 on resnet on M1 Max.
- increment trial times even with compiled error and runtime error.
- use best time of children as the node value.
> MCTS tweaks

- tinygrad/device.py
- tinygrad/runtime/ops_amd.py
- tinygrad/runtime/ops_nv.py
program call now uses only abstracted calls, like queue, so it's unique for all hcq devices
> hcq move out program call to base class

- test/test_linearizer_failures.py
took more than 2 minutes in ci metal, it's basically the same as test_failure_37 but 20X bigger
> skip test_failure_39 in CI

- tinygrad/codegen/uops.py
easier to handle cases like *-1 that flip the bounds
> UOp compute min and max in one call [run_process_replay]

- test/test_schedule.py
- tinygrad/engine/schedule.py
these go down one level deeper than the immediate children of r:
(no kernel count change yet)
> share fusion behavior for r3 kernels

- examples/beautiful_mnist.py
- test/test_schedule.py
- tinygrad/engine/schedule.py
(this is independent from savings in FUSE_CONV_BW=1 and indexing #5590)
this branch:
```
~/code/tinygrad> DEBUG=1 python3 examples/beautiful_mnist.py
memory reduced from 897.18 MB -> 781.91 MB, 52 -> 37 bufs
opened device CLANG from pid:26625
loss:   2.60 test_accuracy:   nan%:  33%|██████████████████████████████████████                                                                            | 1/3 [00:13<00:27,  0.07it/s]scheduled 85 kernels
memory reduced from 903.62 MB -> 781.58 MB, 41 -> 23 bufs
JIT captured 88 kernels with 0 inputs
loss:   1.20 test_accuracy:   nan%: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:41<00:00,  0.07it/s]
```
master:
```
~/code/tinygrad> DEBUG=1 python3 …
```
> beautiful_mnist -4.3% kernels

- test/unit/test_symbolic.py
- test/unit/test_uop_symbolic.py
- tinygrad/codegen/uopgraph.py
old: `x // c` can fold if `0 <= x.vmin <= x.vmax < c`
new: `x // c` can fold if `0 < c and x.vmin // c == x.vmax // c`
> UOp more generic div folding

- tinygrad/engine/jit.py
- tinygrad/runtime/graph/cuda.py
- tinygrad/runtime/graph/hcq.py
- tinygrad/runtime/graph/metal.py
llama 8b 6gpus:
```
enqueue in   2.01 ms
total   6.99 ms, 143.01 tok/s, 3084.66 GB/s, param 2299.00 GB/s
```
vs
```
enqueue in   4.65 ms
total   7.85 ms, 127.42 tok/s, 2748.32 GB/s, param 2048.32 GB/s
```
llama 8b 4gpus:
```
enqueue in   1.39 ms
total   7.28 ms, 137.34 tok/s, 2696.59 GB/s, param 2207.06 GB/s
```
vs
```
enqueue in   3.14 ms
total   7.30 ms, 136.99 tok/s, 2689.75 GB/s, param 2201.46 GB/s
```
> optimize symbolic-related updates in graphs

- tinygrad/shape/symbolic.py
was used in the old linearizer but no longer needed. still need substitute because some fuzz tests calls sym_infer on AndNode
> remove the optimization in AndNode.substitute

- test/test_tensor.py
- tinygrad/tensor.py
This allows the user to pass a `gradient` parameter to Tensor.backward. The API is similar to the one in PyTorch: if the tensor is not a scalar, then gradient must be passed. If it is scalar and it is not passed, it is assumed to be 1.0.
This means that backward can generalize to vector-jacobian products (can be seen as a 'generalization' of the gradient).
> feat: allow passing gradient to .backward() to compute vjp

- test/external/process_replay/process_replay.py
prints total runtime when you push to `update_benchmark`
```
comparing speed for 27923708886 against 28018946178
job                                            master    compare    diff
---------------------------------------------  --------  ---------  -------
Train MNIST                                    8.0s      7.0s       12.50%
Run 10 CIFAR training steps                    20.0s     20.0s      0.00%
Run 10 CIFAR training steps w HALF             18.0s     19.0s      -5.56%
Run 10 CIFAR training steps w BF16             20.0s     21.0s      -5.00%
Run 10 CIFAR training steps w winograd         39.0s     41.0s      -5.13%
Run full CIFAR training w 1 GPU                88.0s     90.0s      -2.27%
Run full CIFAR training steps w 6 GPUS         55.0s     55.0s      0.00%
Run MLPerf …
```
> high-level benchmark timing diff

- test/test_dtype.py
- tinygrad/renderer/cstyle.py
CLANG requires suffix ULL for unsigned long long literals. This pr adds that suffix and a test for this.
```python
print(Tensor(2**64 - 1, dtype=dtypes.uint64).numpy())
```
Main:
``` sh
<stdin>:2:30: error: integer literal is too large to be represented in a signed integer type, interpreting as unsigned [-Werror,-Wimplicitly-unsigned-literal]
data0[0] = (unsigned long)(18446744073709551615);
```
This PR:
```sh
18446744073709551615
> ull literal support and test

- test/test_ops.py
- tinygrad/ops.py
- tinygrad/renderer/cstyle.py
Currently python_alu uses int(x/y) for integer division. This does not work for very large integers as the float casting is not precise enough. This pr replaces that with x//y, along with the required logic to make it truncate towards 0.
```python
print(Tensor([18446744073709551612,], dtype=dtypes.uint64, device='PYTHON').div(Tensor([1,], dtype=dtypes.uint64, device='PYTHON'), upcast=False).numpy())
```
```sh
[0] #main
[18446744073709551612] #this pr
> remove float division from idiv in python_alu

- extra/datasets/kits19.py
- test/external/external_test_datasets.py
This PR cleans up how the preprocessed directory is passed in. Before, the root preprocessing directory is passed in and the function themselves determines if it is a training or validation dataset. Now, two preprocessed constants are now defined: `TRAIN_PREPROCESSED_DIR` & `VAL_PREPROCESSED_DIR` and callers of these functions will have to pass in one of these constants.
> UNet3D KiTS19 preprocessing dir cleanups

- examples/mlperf/dataloader.py
This PR shows how the cleanups made in #5813 are going to be used in the training loop for UNet3D once updated. In this one, `TRAIN_PREPROCESSED_DIR` or `VAL_PREPROCESSED_DIR` is used based on the env. variable value of `VAL`.
Here's a quick run when the `preprocessed` folder does not exist when running `PYTHONPATH=. MODEL=unet3d VAL=0 python3 examples/mlperf/dataloader.py`:
> Dataloader example cleanups

- examples/llama.py
- extra/models/llama.py
only for 8 % devices == 0! (wait for more uneven splits / reshard support)
> optional shard kvcache for llama

- test/test_linearizer_failures.py
This AST passes verify_lazyop and the NOOPT=1 kernel is ok.
hcopts tries to unroll these loops and it fails.
I'm trying to fuse 2 aranges (data3 and data5)
```
X = Tensor.randn(2, 3)
xt = X[Tensor([1]), Tensor([[0,0,0],[0,0,0]])]
kernel void r_6_2_3(device float* data0, const device float* data1, const device int* data2, const device int* data3, const device int* data4, const device int* data5, uint3 gid [[threadgroup_position_in_grid]], uint3 lid [[thread_position_in_threadgroup]]) {
int gidx0 = gid.x; /* 6 */
int val0 = *(data2+0);
int val1 = *(data4+gidx0);
for (int ridx0 = 0; ridx0 < 2; ridx0++) {
int val2 = *(data3+ridx0);
for (int ridx1 = 0; ridx1 < 3; ridx1++) {
float val3 = *(data1+(ridx0*3)+ridx1);
int val4 = *(data5+ridx1);
acc0 = …
```
> hcopts fail in fused arange kernel

- test/external/external_benchmark_multitensor_allreduce.py
- tinygrad/multi.py
This current threshold is fixed and tuned based on AMD(?). On NV llama is a bit faster setting `RING_ALLREDUCE_THRESHOLD=16000`
> add RING_ALLREDUCE_THRESHOLD

- test/test_linearizer_failures.py
- tinygrad/codegen/uops.py
root cause of resnet bug, the ALU bound is only correct for scalar, not vectorized
> fix UOp ALU bound

- test/test_linearizer_failures.py
failed arange example with UOP_IS_SYMBOLIC
> test lin fail 47 for UOP_IS_SYMBOLIC

- test/test_tensor.py
- tinygrad/runtime/ops_amd.py
As commented in https://github.com/tinygrad/tinygrad/pull/5701, the 'minimal' failing test case is a second order derivative. The main issue is that tinygrad does not keep computational graph for gradients, so gradients cannot be 'backpropagated' again. This means that, for Tinygrad, the gradient of W.grad wrt inputs(for example) is 'None'. Common uses for this includes directly computing second order derivatives or even what is mentioned in https://github.com/tinygrad/tinygrad/pull/5701.
> add failing test for second order derivatives

- test/test_multitensor.py
- tinygrad/multi.py
depends (stacks on top of) #5599 
cleaner impl of #5600 
saves a line
the relevant patch: https://github.com/tinygrad/tinygrad/pull/5804/commits/a97be07404bb3676117ba4307e134757b7f5d23f
> MLB support reshape for uneven shards

- .github/workflows/test.yml
- test/unit/test_uop_symbolic.py
- tinygrad/codegen/uopgraph.py
Reverts tinygrad/tinygrad#5865
the pattern is correct and test passes with int64 for alu, so we need more rules not less
> Revert "remove one more UOp mod pattern"

- test/external/fuzz_uops.py
- tinygrad/codegen/uopgraph.py
- tinygrad/engine/realize.py
FUZZ_UOPS=1 creates the fuzz paths at runtime instead of compile time. This is fine because `get_runner` is behind a cache.
> fuzz uops is simpler with List[UOp] [run_process_replay]

- examples/mlperf/dataloader.py
- examples/mlperf/model_train.py
- extra/datasets/wikipedia.py
- test/external/mlperf_bert/preprocessing/external_test_preprocessing_part.py
This PR enhances the dataloader by adding the equivalent of `tf.data.experimental.parallel_interleave`, improving convergence to [2.3M - 2.8M steps](https://wandb.ai/wahl/MLPerf-BERT/runs/9qqq1oa4?nw=nwuserwahl)(matching reference) and speeding up the dataloader from 20ms to ~3ms. Note, we now batch all samples of one topic to one file, so deleting the diskcache and regenerating the data is necessary. :/
Direct testing against the reference is not possible because:
1. The reference only sets the graph seed, not the operation seed for random transformations.
2. `sloppy=True` in parallel interleave causes nondeterministic behavior.
A test confirming that removing the `sloppy` flag and operation-based shuffle matches the reference was written but not pushed, as it required changes to both …
> New BERT dataloader

- test/helpers.py
- test/test_uop_graph.py
- test/unit/test_uop_symbolic.py
- tinygrad/codegen/uopgraph.py
this simplified enough to make `UOP_IS_SYMBOLIC=1` works for beautiful_mnist and stable_diffusion
still need div folding to make the speed comparable
> UOp add mod folding

- test/test_schedule.py
becomes 1 kernel. But this is slower, can we fold it?
> test fused precompute_freqs_cis

- tinygrad/helpers.py
Upstream pypy issue: https://github.com/pypy/pypy/issues/3183
Workaround by fetching the pragma
> fix: sqlite on pypy

- tinygrad/renderer/cstyle.py
Fix bug where vectorized dtypes would render differently
Now, self.render_dtype is in charge of rendering vectorized correctly
CLANG has the following type_map: `type_map = {dtypes.bool:"_Bool", dtypes.half:"__fp16"}`
for half4 render_cast and render_vectorized would render `half4`
``` python
def render_cast(self, x:str, var_dtype:DType, bitcast=False) -> str:
if bitcast: return f"(*(({self.buffer_prefix}{self.render_dtype(var_dtype)}*)&{x}))"
return f"({self.render_dtype(var_dtype)})({x})"
def render_vectorize(self, x:List[str], var_dtype:DType) -> str:
assert len(x) == var_dtype.count, f"cast is wrong size {len(x)} != {var_dtype.count}"
assert self.float4 is not None, "vectorized cast is not supported on this platform"
return f"{self.float4.replace('float4', …
```
> Fix vectorized dtype rendering bug in CLANG

- test/test_schedule.py
- tinygrad/engine/schedule.py
```
FUSE_ARANGE=1 JIT=0 python3 examples/llama.py --gen 1 --prompt "Hello." --count 10 --temperature 0 --timing
```
works now, asserts ASSIGN doesn't change shape, but if we're fusing it with a reduceop it can reshape to match the top reduce.
> override output shape in fused assign

- test/external/process_replay/diff_schedule.py
runs both versions as ExecItems:
> Diff arange timings

- test/test_schedule.py
- tinygrad/engine/schedule.py
```
~/code/tinygrad> SPLIT_REDUCEOP=0 FUSE_ARANGE=1 python3 examples/beautiful_mnist.py
loss:   0.10 test_accuracy: 98.30%: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 70/70 [00:07<00:00,  9.40it/s]
```
> fix the reduceops cache breaking beautiful_mnist

- examples/mlperf/dataloader.py
use tinygrad tqdm for dataset, and PIL Image is only needed for resnet
> clean up mlperf dataloader import

- test/external/fuzz_schedule.py
- test/external/process_replay/diff_schedule.py
- test/external/process_replay/test_diff_schedule.py
- tinygrad/engine/schedule.py
This simplifies the graph_schedule API and makes the toposort easier to reason about.
> graph LBScheduleItem [run_process_replay]

- tinygrad/renderer/cstyle.py
It's failing process_replay because it is no longer rendering the vectorization structs if there are not used. Before, if there was type half or bfloat present, the vectorization structs would render automatically.
**kernel failing process_replay**
```c
#define INFINITY (__int_as_float(0x7f800000))
#define NAN (__int_as_float(0x7fffffff))
#include <cuda_fp16.h>
extern "C" __global__ void __launch_bounds__(1) r_4096_32000_32000n1(half* data0, const int* data1, const half* data2) {
int gidx0 = blockIdx.x; /* 4096 */
int val0 = data1[0];
for (int ridx0 = 0; ridx0 < 32000; ridx0++) {
half val1 = data2[gidx0+(ridx0*4096)];
acc0 = (acc0+(float)(((half)((!(ridx0!=val0)))*val1)));
}
data0[gidx0] = (half)(acc0);
}
```
``` diff
#define INFINITY (__int_as_float(0x7f800000)) …
```
> Refactor render_kernel for NV [run_process_replay]

- tinygrad/codegen/uopgraph.py
x.op is always UOps.ALU, so removed that check. From #5828, it looks like this is the intent of the rule.
> simplify ALU vmin==vmax fold [run_process_replay]

- test/test_tensor.py
was red 1 out of 4 times on M2 with and without NOOPT=1
> hotfix: adjust test_backward_pass_diamond_model thresholds

- test/test_arange.py
- test/test_schedule.py
these were the slowest tests:
```
============================= slowest 20 durations =============================
39.69s call     test/test_arange.py::TestIndexing::test_llama_embedding
38.18s call     test/test_arange.py::TestIndexing::test_llama_embedding_opt
30.09s call     test/test_schedule.py::TestIndexing::test_mnist_val
```
> smaller test_llama_embedding + assert correctness

- test/unit/test_symbolic.py
- test/unit/test_uop_symbolic.py
this speculative div was handled by "divisor" in symbolic.
> more failed simplified UOp div test case

- .github/workflows/test.yml
- .gitignore
- test/external/process_replay/diff_schedule.py
- test/external/process_replay/process_replay.py
- test/external/process_replay/reset.py
- test/external/process_replay/test_diff_schedule.py
- test/external/process_replay/test_process_replay.sh
- test/external/process_replay/utils.py
- tinygrad/engine/schedule.py
After every create_schedule call, RUN_PROCESS_REPLAY=1 recreates the graph with the master version of schedule.py.
This is more debuggable because it's mapping LazyBuffer -> ScheduleItem (without pickling LazyBuffers).
Doesn't diff the toposort.
> diff LazyBuffer schedules in process replay

- test/external/process_replay/process_replay.py
- tinygrad/engine/schedule.py
RUN_PROCESS_REPLAY=1 needs PYTHONPATH="." because it's importing from tests/external.
> scheduler process replay with [compare_schedule]

- test/external/process_replay/diff_schedule.py
- test/external/process_replay/process_replay.py
- tinygrad/engine/schedule.py
kernel.py folds some already:
```
REF_COMMIT_HASH=b67d521a07d73f29e20200c124f4676285ac93d5 RUN_PROCESS_REPLAY=1 DEBUG=1 python3 test/test_schedule.py TestConvBW.test_fold_conv_relu_backward
```
some beautiful_mnist kernels didn't fold before:
```
REF_COMMIT_HASH=b67d521a07d73f29e20200c124f4676285ac93d5 RUN_PROCESS_REPLAY=1 FUSE_CONV_BW=1 python3 examples/beautiful_mnist.py
```
and some kernels trigger other optimizations:
```
REF_COMMIT_HASH=b67d521a07d73f29e20200c124f4676285ac93d5 RUN_PROCESS_REPLAY=1 GPU=1 python3 test/external/external_test_opt.py TestOpt.test_expand_reduce_is_folded_on_different_axes
```
> assert conv bw reduceops merge [compare_schedule]

- test/test_tensor.py
- tinygrad/device.py
> Ignore non-computational backends when overwriting the default

- tinygrad/renderer/cstyle.py
Simplifies cstyle `render_const` in the spirit of #5313. This change takes advantage of the fact that CONSTs are always scalar, and localizes the complexity of deciding when to apply casts and extra parentheses to CONSTs in ALUs, where CONSTs are used to construct expressions as opposed to being used for simple assignments (where type promotion is easy to reason about).
process_replay impact: less excessive casting and parens.
e.g.
> Cleanup cstlye render_const [run_process_replay]

- test/test_linearizer_failures.py
- tinygrad/codegen/kernel.py
also added `RAWAST` to print pre-modified AST in DEBUG=3
> test_failure_48 for wrong truncation in idx on NV

- tinygrad/engine/realize.py
- tinygrad/engine/schedule.py
- tinygrad/ops.py
`MetaOps.CUSTOM, MetaOps.COPY, MetaOps.EMPTY, MetaOps.VIEW` don't fit into any of our existing UOps.
MetaOps.KERNEL and MetaOps.EXT can be the two paths in realize.py.
after AST is UOp:
MetaOps.KERNEL -> UOps.SINK
MetaOps.EXT -> UOps.EXT
> proposal: MetaOps.EXT

- tinygrad/engine/graph.py
this is fine because lazy.py doesn't create BufferOps.
> remove BufferOps from log_lazybuffer

- tinygrad/codegen/uopgraph.py
- tinygrad/dtype.py
this is enough to fix the alu overflow issue and unblock UOP_IS_SYMBOLIC, will do a separate one to move it later (need to fix the dtypes in expand/reduce/float4 rules)
> rewrite pyint after first rewrite [run_process_replay]

- test/test_multitensor.py
- tinygrad/tensor.py
Calling `.interpolate()` on a Tensor across multiple devices throws an error:
```
AssertionError: all buffers must be MultiLazyBuffer (<MLB... >, <LB... >)
```
This is due to the `Tensor.arange` being created on the default device rather than matching the input. Relaying that device to the constructor fixes the issue.
A new `TestTensorOps` class was made in `test/test_multitensor.py` to unit test the running of tensor ops on both a single and multiple devices, checking for error-less running as well as discrepancies in the result.
> Interpolate Multi Fix

- tinygrad/codegen/uopgraph.py
- tinygrad/renderer/__init__.py
- tinygrad/renderer/assembly.py
- tinygrad/renderer/cstyle.py
- tinygrad/renderer/llvmir.py
Applies transcendental rewrite rules if a `Renderer` doesn't have code for the ops. I've rewritten it so that `TRANSCENDENTAL=1` has no effect anymore so I think `TRANSCENDENTAL` should only handle one value, but I'd like to be sure this is the right approach first.
> Apply transcendental rewrite rules only if required by backend

- .github/workflows/test.yml
I'll take ownership of putting this back.
https://github.com/tinygrad/tinygrad/commit/6e3eb50fd172d7599e9a0aaea88b772460bd3a15 took 1 minute https://github.com/tinygrad/tinygrad/actions/runs/10361803011/job/28682742416#step:18:21
https://github.com/tinygrad/tinygrad/commit/18192079a9f49de43d059157067f8b29fcec9db9 and everything after it times out https://github.com/tinygrad/tinygrad/actions/runs/10364239612/job/28706053434#step:18:1
METAL tests also went from taking 5 minutes to 8.
> temp: disable process replay on metal

- test/test_linearizer_dumb.py
- test/test_uops.py
#6066 reveals we need toposort rules for LOAD/STORE indexing ordering.
master outputs kernels like:
```
float2 val18 = *((device float2*)(data2+16));
float4 val19 = *((device float4*)(data2+0));
float4 val20 = *((device float4*)(data2+4));
float4 val21 = *((device float4*)(data2+8));
float4 val22 = *((device float4*)(data2+12));
```
> spec for in order LOAD/STORE indexing

- tinygrad/codegen/uopgraph.py
there's no div and 1/c is const folded
> remove redundant x/c pattern [run_process_replay]

- test/test_linearizer_failures.py
- test/test_uop_graph.py
- test/unit/test_uop_symbolic.py
- tinygrad/codegen/uopgraph.py
fixed running `tinyphysics.onnx`, which contains a getitem from a boolean tensor.
only can repro through BEAM_COMPARE, which i think is a different bug in test_linearizer_failure
> rewrite bool ADD to OR and MUL to AND

- ruff.toml
- test/test_gc.py
- test/unit/test_helpers.py
- test/unit/test_shapetracker.py
- tinygrad/codegen/kernel.py
- tinygrad/helpers.py
- tinygrad/renderer/assembly.py
requires space after keywords like `assert`, `not`, `return`, `else`
> add E275 missing-whitespace-after-keyword linting rule

- tinygrad/codegen/uopgraph.py
- tinygrad/ops.py
- tinygrad/shape/shapetracker.py
The reasoning is to let engine.schedule and codegen.uopgraph share this. (without inheriting the low-level uops constant_folder in engine)
> move graph rewrite to ops [run_proess_replay]

- test/test_tensor.py
- tinygrad/tensor.py
Prerequisite for https://github.com/tinygrad/tinygrad/issues/5858.
Simply allows not deleting the graph information when running backward (defaults to False). Most common usage is gradient accumulation or second order derivatives. Defaults to False as PyTorch.
Another important usage as I mentioned is gradient accumulation (you can look it up, it is a simple concept). See the test for the expected behaviour (to match pytorch). In order for it to be correct, the gradient accumulation needs to only be done on leaf tensors (hence the t0.grad = None in .backward(). In eager frameworks like PyTorch, this reduces memory usage significantly. It could also reduce it on Tinygrad for training (but I'm not 100% sure it will). It simply frees grads that will not be used).
> add support for retain_graph in backward

- test/test_rearrange_einops.py
- tinygrad/tensor.py
Missing "1" as alias for "()" in rearrange. This fixes and tests that.
Now we can do `img_0.rearrange("(bw bh) 1 c w h -> c (bw w) (bh h)", bw=4)`
Other numbers are not supported as I think they can only be used in reduce and repeat.
Also added an assert that no dimensions were given for axes that don't exist and a test for that.
Now `x.rearrange("a b -> a b", c=2)` errors out, as it would in einops.
> Missing features from rearrange

- extra/datasets/kits19.py
MLPerf made some recent changes (see [here](https://github.com/mlcommons/training/pull/756)) since UNet3D is a retired benchmark and they moved it inside of their `retired_benchmarks` subfolder. This PR updates it to that new location.
> Update evaluation_cases URL for kits19

- test/test_arange.py
non CI uses larger embedding, still same orders of magnitude
> update test_arange test_llama_embedding_opt

- tinygrad/engine/schedule.py
- tinygrad/lazy.py
Reverts tinygrad/tinygrad#6202
Appears to be the cause of openpilot regression
> Revert "delete arg from (LazyBuffer) cast [run_process_replay]"

- test/test_linearizer.py
#6209
ufix only works for low-level CONST uops, we need a way to bring the syntactic sugar of UOp to AST UOp too.
> test_multireduce const has a shape

- docs/tensor/ops.md
- extra/onnx_ops.py
- test/external/external_test_onnx_backend.py
- test/test_const_folding.py
- test/test_dtype.py
- test/test_ops.py
- tinygrad/codegen/lowerer.py
- tinygrad/function.py
- tinygrad/lazy.py
- tinygrad/nn/__init__.py
- tinygrad/ops.py
- tinygrad/tensor.py
a new reduce op! was reading someone using tinygrad and needed to call `functool.reduce(mul, tensors)` because of no prod support.
also added onnx op support. one day these can all be written with associative_scan
> Tensor.prod

- extra/ops.py
- tinygrad/codegen/kernel.py
- tinygrad/codegen/lowerer.py
- tinygrad/ops.py
Kernel creates UOps.WMMA with 2 srcs, this gets rewritten to 3 + the EXPAND.
I think I can factor out the CONST to kernel.py too.
> use UOps.WMMA everywhere

- test/test_linearizer.py
- tinygrad/codegen/kernel.py
BufferOps was present in a test tagged with `expectedFailure` and slipped through
> remove extra.ops and LazyOp support from Kernel

- extra/models/clip.py
Previous version only worked for batch_size=0 and had to call `.numpy()`
New version works with any batch size and doesn't rely on a `.numpy()` call
```
PYTHONPATH=. NV=1 python examples/sdxl.py --seed 0
output validated with distance=0.00289628142490983
```
> CLIP Batched Pooling

- test/test_ops.py
This PR implements tests which make sure that tinygrad's `einsum` implementation conforms to PyTorch's as specified in their docs (https://pytorch.org/docs/stable/generated/torch.einsum.html).
The code was extracted from #6258 (which also included an implementation for `einsum` in tinygrad) and is related to issue #4156.
> Add einsum ellipsis tests

- extra/models/clip.py
The clip score computation was originally built and tested against single batch inputs and provides wrong answers for batch sizes >1
This PR fixes this code and produces consistent results with variable batch sizes
Just image+caption 1: `score: [0.3593387]`
Just image+caption 2: `score: [0.39535367]`
Batched images+captions 1 & 2: `score: [0.35933858 0.39535385]`
> Batched CLIP Score

- test/external/external_benchmark_ast.py
- tinygrad/engine/schedule.py
- tinygrad/helpers.py
- tinygrad/ops.py
Some reduceop kerenls take far longer than others:
This diff has some infra to isolate ScheduleItems.
> start benchmarking ast graph rewrite

- tinygrad/ops.py
No major speed impact, but a bit simpler.
`JIT=0 kernprof -lv examples/llama.py --gen 1 --prompt "Hello." --count 10 --temperature 0 --timing`
```
Total time: 0.416079 s
File: /Users/rvd/src/rvd/tinygrad/tinygrad/ops.py
Function: key at line 77
77                                             @functools.cached_property
78                                             @profile
79                                             def key(self) -> bytes:
80    225149     416079.0      1.8    100.0      return hashlib.sha256(functools.reduce(lambda x,y: x+y, [s.key for s in self.src], str((self.op, self.dtype, self.arg)).encode())).digest()
```
```
Total time: 0.394044 s
File: …
```
> Ops.key: no need for functools here

- test/test_ops.py
- tinygrad/tensor.py
- add support and tests for `nearest` mode in interpolate, equivalent to torch
- add support and tests for `nearest-exact` mode in interpolate, equivalent to torch
- adapt uint8 linear interpolate, making it equivalent to torch
- adapting torch's [multiplication trick](https://github.com/pytorch/pytorch/blob/2bd02e0c82c6d76157244655256062bade5070ae/aten/src/ATen/native/cpu/UpSampleKernel.cpp#L944) for uint8 interpolation
- implemented in `lerp` with no cast to float (5757458f5b3b5f5feef5fa87f76cbabf95ec7096)
> add support and tests for nearest modes in interpolate, adapt uint8 bilinear to torch implementation

- test/external/process_replay/process_replay.py
- test/external/process_replay/test_process_replay.py
- tinygrad/codegen/kernel.py
This file was getting out of control. This should also be much easier to unit test.
It's 3 sections:
1. differs: These are single-threaded, independent functions and return a bool (`changed`)
2. diff runners: multi threaded, running differs across the entire process replay capture
3. main loop: Runs both diff runners, **only** raises their exceptions if `[run_process_replay]` is set.
> process replay rewrite

- tinygrad/ops.py
`type_verify` is full of asserts. These get removed with `-O`, but all the if statements are still be executed, which is more than 10% of the linearize.
Using the fact that `__debug__` is set to false with `-O` we can skip everything here. (The other option would be to use the `PYTHONOPTIMIZE` value.)
`PROFILE=0 python -O test/external/external_benchmark_schedule.py` best out of 5
Master
```
***** model tensor in     17.15 ms
***** model schedule in    7.27 ms
***** model opts(53) in   28.97 ms
***** model lower in       6.32 ms
***** model rewrite in   478.40 ms
***** model linearize in 121.98 ms <--
14964
```
Branch
```
***** model tensor in     17.75 ms
***** model schedule in    7.23 ms
***** model opts(53) in   28.43 ms
***** model lower in       6.16 ms
***** model rewrite in …
```
> perf: skip type verify with -O

- test/test_ops.py
Many passes now, `test_gemm_fp16` seems to lack precision. `test_nested_conv2d` and `test_padded_conv3d` return the same wrong output for both GPU(qcom)/QCOM (compiler related?)
> qcom remove some tests skips

- test/test_linearizer.py
- test/test_linearizer_dumb.py
- test/test_linearizer_failures.py
- test/test_uop_graph.py
- test/test_uops.py
- tinygrad/codegen/uopgraph.py
- tinygrad/ops.py
- tinygrad/renderer/assembly.py
- tinygrad/renderer/cstyle.py
- tinygrad/renderer/llvmir.py
PR for bounty: "gated store rewrite to UOps.IF, well tested. spec: https://github.com/tinygrad/tinygrad/pull/5652"
Changes include:
> gated store rewrite to UOps.IF

- test/test_nn.py
- test/test_ops.py
- test/test_schedule.py
- tinygrad/tensor.py
Relatively simple. `sparse_categorical_cross_entropy` is the only non-trivial case because
* it supports `ignore_index`, so computing the mean is not as simple as `Tensor.mean`
* it was already optimized assuming `reduction="mean"`.
The implementation of `sparse_categorical_cross_entropy` in this PR was written to:
1. Reduce amount of new code
2. Maintain performance of default (`"mean"`) case
A side effect of 1. is that `sparse_categorical_cross_entropy` now typically produces an extra kernel. However, my measurements show identical perf (on metal) to the previous implementation. I can push the perf testing code I added to test/test_speed_v_torch.py if you want.
If preserving the number of kernels is more important than the code being concise and clean, we could easily have an optimized …
> Support `reduction` parameter in all built-in loss functions

- test/test_ops.py
- tinygrad/tensor.py
- fixing spacing
- use get_args to get valid Literal values and raise ValueError to match, and a test for that
- use `Y` to be consistent
> tensor reduction touchup

- tinygrad/codegen/uopgraph.py
from `8269a721cd6f5c6030ce120e1139095d7ba117eb`
process replay:
> fold bitwise noops

- test/test_renderer_failures.py
- tinygrad/ops.py
- tinygrad/renderer/assembly.py
- tinygrad/renderer/cstyle.py
So PTX fails for these gated stores.
diff if we use an alu gate vs a UOps.IF
@ianpaul10 you're fixing this in #6405, can you open a PR with just the ptx diff including this test?
> test new style gated store rendering

- tinygrad/helpers.py
- tinygrad/ops.py
1. Add `HashEnum` which caches the `__hash__` result for enums
2. Remove the custom `__hash__` implementation on `UOp`: it is effectively equivalent to the builtin `object` one but is a lot slower
3. Use `eq=False` for `NOp` (like `UOp` does)
Combined, PR makes both rewrite and linearize about 10% faster on my machine.
Before (min of 5 samples):
```
PROFILE=0 python3 test/external/external_benchmark_schedule.py
***** model tensor in     24.80 ms
***** model schedule in   11.01 ms
***** model opts(53) in  119.97 ms
***** model lower in       8.42 ms
***** model rewrite in   654.21 ms
***** model linearize in 208.02 ms
14967
all 1031.90 ms
```
After (min of 5 samples):
```
PROFILE=0 python3 test/external/external_benchmark_schedule.py
***** model tensor in     24.38 ms
***** model schedule …
```
> Faster UOp hashing

- test/test_schedule.py
- tinygrad/ops.py
This is the new way I'm thinking about SWIZZLE, it will not only be used to push to the LOAD but also to the STORE.
Makes graph_rewrite in the scheduler much easier to reason about.
This form of SWIZZLE can guarantee all asts in the entire lifetime of graph_rewrite have a valid shape.
> UOp.st infra for the new SWIZZLE

- test/test_schedule.py
- tinygrad/engine/schedule.py
This generalizes the new SWIZZLE to multi reduce fusion.
eg. here:
The first reduce (arange) applies the expand SWIZZLE, then we wrap it around a new SWIZZLE, describing a reshape:
```
1  UOp(UOps.STORE, None, arg=None, src=(
2    UOp(UOps.DEFINE_GLOBAL, PtrDType(dtypes.int), arg=0, src=()),
3    UOp(UOps.SHAPETRACKER, None, arg=ShapeTracker(views=(View(shape=(1, 1), strides=(0, 0), offset=0, mask=None, contiguous=True),)), src=()),
4    UOp(UOps.REDUCE_AXIS, dtypes.int, arg=(BinaryOps.ADD, (0, 1)), src=(
5      UOp(UOps.SWIZZLE, None, arg=ShapeTracker(views=(View(shape=(32, 32), strides=(32, 1), offset=0, mask=None, contiguous=True),)), src=(
6        UOp(UOps.ALU, dtypes.int, arg=BinaryOps.ADD, src=(
7          UOp(UOps.REDUCE_AXIS, dtypes.int, arg=(BinaryOps.ADD, (2, 3)), src=(
8 …
```
> can push SWIZZLE through reduce both ways

- test/test_schedule.py
- tinygrad/engine/schedule.py
- tinygrad/helpers.py
milestones:
1. Merge single reduceop fusion #6248
2. Improve AST rewrite speed, what's the source of this ~2x?
```
~/code/tinygrad (master) > SCHEDULE_ONLY=1 AST_REWRITE=1 PROFILE=0 python3 test/external/external_benchmark_schedule.py
***** model tensor in     25.64 ms
***** model schedule in   18.52 ms
all  44.19 ms
~/code/tinygrad (master) > SCHEDULE_ONLY=1 AST_REWRITE=0 python3 test/external/external_benchmark_schedule.py
***** model tensor in     25.54 ms
***** model schedule in   10.13 ms
all  35.69 ms
```
After  #6433 and #6449 this is faster but still too slow:
```
~/code/tinygrad (master) > AST_REWRITE=0 python3 test/external/external_benchmark_schedule.py
***** model tensor in     22.94 ms
***** model schedule in    9.37 ms
all  32.34 ms
~/code/tinygrad (master) > AST_REWRITE=1 …
```
> enable graph rewrite in the scheduler

- tinygrad/ops.py
```
TRACK_MATCH_STATS=1 SCHEDULE_ONLY=1 AST_REWRITE=1 UPAT_FILE=schedule python3 test/external/external_benchmark_schedule.py
```
> allow selecting UPat files in TRACK_MATCH_STATS [run_process_replay]

- tinygrad/codegen/uopgraph.py
master renders things like:
I think no_pyint is a part of the contract between linearize_uop and full_graph_rewrite, kinda like no EXPAND.
> assert pyint in linearize_uop [run_process_replay]

- test/test_ops.py
- tinygrad/ops.py
- tinygrad/tensor.py
mostly passed `TYPED=1 python3 -m pytest -n=auto test/test_ops.py`.
one last test specifically set an invalid value to test the exception, and to ignore that we need to import typeguard. And to get a working version of typeguard, we would need to get rid of dependency on tensorflow_addons because it requires a very old version of typeguard
> fix typing for test_ops

- tinygrad/engine/schedule.py
these two SWIZZLEs:
are changing srcs with different shapes, (6, 1) vs  (1, 3, 2, 2), which is fine as long as they're the same size.
> refactor for SWIZZLE with different st dims [run_process_replay]

- tinygrad/ops.py
If `uop.arg is None`, we're currently checking all relevant patterns twice.
This change is only a 2-3% net speedup on the benchmark because this isn't a super common situation, but I still think this change is justified because it's more "correct". It could also be a bigger speedup with different kernels.
> Don't re-check patterns when uop.arg is None

- test/test_linearizer.py
- tinygrad/codegen/kernel.py
- tinygrad/renderer/cstyle.py
Fix AMX shape: (sz,sz,sz) -> (sz,sz,1)
AMX no longer has threads
I was wrong when I thought the abstraction only went so far, refactoring TC I realized AMX could be correctly represented with current TC abstraction. Flops counting is fixed now without needing any hack.
This fix was originally on #6456 but I moved all the AMX shape changes here.
> Fix amx shape [run_process_replay]

- .github/workflows/test.yml
- test/unit/test_image_valid.py
- tinygrad/codegen/uopgraph.py
455 -> 364 valids.
generalize `idx < image bound` to `idx < image bound + c` for some `c`
> generic valid match criteria of #6552

- .github/workflows/test.yml
- test/unit/test_image_valid.py
- tinygrad/codegen/uopgraph.py
removed valid in the form of `(A % m, A // m + k)` and reduced valid to 356. intentionally made more restrictive to make sure it's correct
> brute force VALIDHACK matching

- test/test_uops.py
- tinygrad/ops.py
- viz/serve.py
- viz/test_viz.py
VIZ=1 was wrong for some graphs because the rewrite was applied from the `replaces` cache instead of `TrakcedPatternMatcher().rewrite`.
> include cached replaces in VIZ=1

- .github/workflows/test.yml
- test/unit/test_image_valid.py
- tinygrad/codegen/uopgraph.py
use graph_rewrite to simplify the expression with narrowed variables, and check boundry conditions on monotonically increasing function to drop valid.
> more generic simplify_valid_image_load

- test/unit/test_verify_ast.py
- tinygrad/ops.py
I think any None in UOp is a lint error not just a spec mismatch.
> fixup non-void sinks in tests [run_process_replay]

- tinygrad/ops.py
`Tuple[ConstType, ...]` instead of `Tuple[ConstType]`
> const_like type fix

- test/unit/test_image_valid.py
- tinygrad/codegen/uopgraph.py
apply to kernels in op 0.9.7.
if a valid has a complicated expr, we cannot drop valid but it's possible to simplify idx given valid
> relax idx simplification given valid

- .github/workflows/benchmark.yml
This was causing PtrDType changes to hang process replay.
Won't happen in test.yml CI because the db cache is fully ignored.
There's an argument to be made that we should clear the db cache in benchmarks.yml globally.
> hotfix: reset benchmarks cache for process replay

- tinygrad/renderer/cstyle.py
`NOLOCALS=1 python -c "from tinygrad import Tensor; Tensor.randn((5, 5)).realize()"` works on green box with this fix #6687
> hotfix missed cast in cstyle code_for_workitem

- examples/mlperf/model_eval.py
The Bert model in extra/models downloads the vocab in extra/weights, but model_eval.py searches for the vocab in the top tinygrad directory. Trivial but noticed it, so.
> fix wrong directory access for bert vocab in mlperf/model_eval.py

- test/unit/test_uop_symbolic.py
- tinygrad/codegen/uopgraph.py
not really used, want it to keep as a var for valid simplification [run_process_replay]
> do not fold var with min==max

- examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_green/dev_beam.sh
- examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_green/dev_run.sh
- examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_green/run_and_time.sh
- examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_red/dev_beam.sh
- examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_red/dev_run.sh
- examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_red/run_and_time.sh
- extra/models/bert.py
- tinygrad/tensor.py
removed DISABLE_DROPOUT=1.
updated BS to 54 that works on tinyboxes with dropouts.
used bert's sparse_categorical_crossentropy that takes Tensor ignore_index in accuracy method
> update mlperf bert scripts

- examples/mlperf/model_eval.py
- extra/datasets/openimages.py
**Overview**
This PR adds support for an optional `BASE_DIR` env. variable to place the openimages dataset at a specific location. In addition, it performs basic checks to see if a specific dataset type is already available from the `BASE_DIR` location.
The download script usage is as follows:
```python
BASE_DIR=<path> python3 extra/datasets/openimages.py
```
By default, it will download __both__ training and validation sets.
**Remaining task(s)**
> [MLPerf] Prepare openimages dataset script

- test/test_uops.py
- tinygrad/ops.py
explicit `arg=None` should change the arg.
> match dataclass.replace in UOp.replace [run_process_replay]

- tinygrad/engine/schedule.py
- tinygrad/ops.py
- viz/serve.py
The big graph creates UOps.BUFFER, where arg is the index in the big graph.
The small graph rewrites UOps.BUFFER to UOps.DEFINE_GLOBAL, where arg is from 0-n.
This makes decoupling compute scheduling from data scheduling (https://github.com/tinygrad/tinygrad/issues/6784) possible.
> add UOps.BUFFER, delete Buffer in UOps.DEFINE_GLOBAL

- test/test_schedule.py
- tinygrad/engine/schedule.py
src has a SWIZZLE that reshapes the reduceop:
when it's pushed all the way up to the second REDUCE_AXIS:
it should reduce on the new dims:
```diff
-UOp(UOps.REDUCE_AXIS, dtypes.int, arg=(BinaryOps.ADD, (1,)), src=(
-  UOp(UOps.SWIZZLE, dtypes.int, arg=ShapeTracker(views=(View(shape=(1, 10), strides=(0, 1), offset=0, mask=None, contiguous=True),)), src=(
+UOp(UOps.SWIZZLE, dtypes.int, arg=ShapeTracker(views=(View(shape=(1, 1), strides=(0, 0), offset=0, mask=None, contiguous=True),)), src=(
+  UOp(UOps.REDUCE_AXIS, dtypes.int, arg=(BinaryOps.ADD, (0,)), src=(
UOp(UOps.ALU, dtypes.int, arg=BinaryOps.MUL, src=(
UOp(UOps.ALU, dtypes.int, arg=BinaryOps.ADD, src=(
x3:=UOp(UOps.ALU, dtypes.int, arg=BinaryOps.ADD, src=(
```
master rewrites this to:
```diff
-UOp(UOps.REDUCE_AXIS, dtypes.int, …
```
> push swizzle through dim change

- test/test_schedule.py
one source of reds in https://github.com/tinygrad/tinygrad/pull/6811 is that we're trying to realize non-contig consts of size 0.
> test current behavior of const schedule [run_process_replay]

- tinygrad/engine/schedule.py
idea from #6811 - this diff constructs the big graph of UOps.BUFFER early and shares the map between all small graphs.
So many more things to fix:
1. CONST can be UOped early too, it's a VALID in the big graph then SWIZZLE in the small graph, rewritten to just VALID. ([or no VALID!](https://github.com/tinygrad/tinygrad/pull/6811/files#diff-9676c3f2152843d69d2f646646a7ecf1916ac1f962afdbafe4564bc07be3a644R19))
2. `make things that can't be images not images` is terrible. Maybe graph_rewrite+get the Buffer from ctx and just hack it there.
> early uop UOps.BUFFER (only once) [run_process_replay]

- test/test_ocl.py
- tinygrad/runtime/ops_gpu.py
Solves #3482. We sliced a memory-mapped file that lead to an awkward alignment. OpenCL, the backend used when GPU=1, did not give any errors and instead zero-padded the front of the buffer. This lead to corruption after copying from the GPU back to the CPU, which lead to bad weights and tokens. To fix this, we can simply reallocate the buffer on the heap if it is unaligned.
The alternative is to instead assert the alignment and give the user an error. However, this makes things much harder for the user for the dubious benefit of 1 less buffer copy. 
Tested on an M3 Mac:
```
$ GPU=1 python examples/gpt2.py --model_size=gpt2         
using GPU backend
using gpt2
ram used:  0.50 GB, lm_head.weight                                    : 100%|██████| 149/149 [00:00<00:00, 884.87it/s]
loaded …
```
> Fix GPT2 with OpenCL backend.

- tinygrad/ops.py
- viz/serve.py
Fixes red in #6831 - This is part of a bigger problem with our types, graph_rewrite rhs expects a UOp but it shouldn't.
> viz don't include graph_rewrites that return a non-UOp

- README.md
- test/external/process_replay/README.md
- test/external/process_replay/process_replay.py
backwards compatible, [run_process_replay] will still work but [pr] is the new shorthand.
> add pr alias [pr]

- tinygrad/runtime/ops_metal.py
This method isn't run on CI so it wasn't caught, but running `METAL=1 pytest test/test_jit.py::TestJit::test_jitted_transfers`, or the following two examples, would cause the program to hang, because `copyFromBuffer:sourceOffset:toBuffer:destinationOffset:size:` expects NSUInteger (c_ulong) rather than NSInteger (the default c_int/c_long). Interestingly though other methods that expect NSUInteger didn't experience an error like this. 
- [A low level transfer example](https://gist.github.com/mesozoic-egg/530649deca9ef490eb7b0fbe3066d118)
Sharding example (intra device, just for demo):
```python
from tinygrad import Tensor, Device
import numpy as np
np.random.seed(0)
data = np.random.rand(10).astype(np.float32)
a = Tensor(data)
a = a.shard(['METAL:0', 'METAL:1'], axis=0)
a.realize()
```
> Construct c_ulong in blitCommandEncoder copy method

- viz/index.html
- viz/serve.py
- viz/spec.py
- viz/test_viz.py
prereq for moving VIZ into core.
wins:
1. The VIZ server has 40 less lines.
2. spec.py, documented typed jsonable API responses.
> viz rewrite part 1 [pr]

- examples/mlperf/model_train.py
- examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_green/dev_run.sh
- examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_green/run_and_time.sh
- examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_red/dev_run.sh
- examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_red/run_and_time.sh
4h32m with this https://wandb.ai/chenyuxyz/MLPerf-BERT/runs/q99frv1l/overview.
loss scaler 2**13->2**10. matched the closest submission, no nan for ~10 runs.
increased lr and total step a bit.
`PARALLEL=0` after setup, same as resnet.
> update bert hparams

- test/test_transcendental.py
Right now, CI has several warnings like: 
```
test/test_transcendental.py::TestTranscendentalMath::test_float16
/Users/runner/work/tinygrad/tinygrad/test/test_transcendental.py:41: RuntimeWarning: divide by zero encountered in log
op[1](np.array([x], dtype=_to_np_dtype(dtypes.float16))),
```
when testing transcendental functions. This is because these functions have relatively limited domains and our testing library sometimes generates wacky inputs, as it should. We still want to confirm we match numpy's behavior in these cases, so I think we should suppress these errors.
> Suppress warnings in transcendental tests.

- test/test_dtype.py
- tinygrad/tensor.py
matches torch. for mixed precision training, we would want to use float for softmax
> support dtype in softmax and log_softmax

- .github/workflows/test.yml
- tinygrad/ops.py
- viz/serve.py
- viz/test_viz.py
VIZ needs a temp stack to keep track of graph_rewrite calls while doing another graph_rewrite.
> new viz fuzz tests, track multiple contexts

- tinygrad/ops.py
- viz/serve.py
- viz/test_viz.py
removes Kernel dep for type_checking. I think Any is fine here because we also wanna track ScheduleItem graphs.
> viz prep refactor for tracked scope decorator [pr]

- docs/tensor/ops.md
- test/test_ops.py
- tinygrad/tensor.py
#6911 
- using the same numerical stability method as `logsumexp` since the only thing that differs is the cumsum, not the exps: exp(x1) + exp(x2) + ... = exp(m) (exp(x1-m) + exp(x2-m) + ...).
- pytorch requires `dim` by caller. i set the `axis=0` as default which matches some of the behavior i see from other ops
> implement logcumsumexp

- extra/models/clip.py
CLIP was creating a tensor internally without defining a device and then multiplying by weights, which caused issues when the CLIP model was on a non-default device.
Passing in the device of one of the weights fixes this.
Ran the code changes in a full SDXL mlperf run where the CLIP model was on `NV:2` instead of the default `NV`.
> Clip Device Fix

- tinygrad/tensor.py
the final contiguous in rand is annoying because dropout saves the rand tensor, not the bool tensor for backward. Make contiguous optional and call contiguous in dropout saves 6G mem in bert training. @wozeparrot thought on this direction?
> dropout contiguous after >= p

- test/test_ops.py
need cummax for numerical stability
> failed example for logcumsumexp

- tinygrad/engine/realize.py
- tinygrad/runtime/ops_disk.py
Right now, `self.fd` is sometimes in `DiskDevice`. This messes up mypy/pylint, because those tools work poorly with attributes that are added and removed dynamically. Hence, we make it an `Optional` field instead.
Necessary for my fix for #6294.
> Make self.fd Optional.

- tinygrad/runtime/ops_metal.py
Before it would return an integer that doesn't help much in debugging:
now there's a descriptive string
> Get readable error from wait_check in ops_metal

- test/unit/test_uop_symbolic.py
- tinygrad/ops.py
addressed #6935
the first few terms in fold_unrolled_divs might have been folded already, so the check should first try to add those terms back. there is a case that every but one term is folded which is not an add chain anymore, so just added as a failed test case for now
> improve fold_unrolled_divs

- tinygrad/runtime/ops_cuda.py
This is required to enable larger than 48kb shared memory usage on a per-kernel basis.
Initially to be used for a 3-stage FP16/FP16 GEMM example in #6926 (needs 72KB of SMEM which is doable in RTX4090), but eventually can do a deeper integration to allow architecture-specific increases in maximum SMEM allocation (when needed by the kernel opts).
> ops_cuda: add optional dynamic smem parameter

- test/test_schedule.py
- tinygrad/tensor.py
two less kernels per softmax backward. testing on bert seems to be 3% faster
209 -> 213 tflops
<https://wandb.ai/chenyuxyz/MLPerf-BERT/runs/ed4m45ph/overview>
> derivative of softmax is indepedent of max

- test/test_dtype.py
- test/test_dtype_alu.py
- tinygrad/renderer/cstyle.py
process replay won't pass as handwritten comparison operations are removed and comparison alus are casted to float now.
Pattern Matching Enhancements:
* [`tinygrad/renderer/cstyle.py`](diffhunk://#diff-9694d15708a36a57a7e1485db60b1b4b1d2fc1e7278bc87127a73efd0bfa7dc0L393-R396): Added a new pattern matcher for `UOps.ALU` with `dtypes.bool` and simplified the existing pattern matchers for `dtypes.bfloat16`.
Kernel Rendering Adjustments:
* [`tinygrad/renderer/cstyle.py`](diffhunk://#diff-9694d15708a36a57a7e1485db60b1b4b1d2fc1e7278bc87127a73efd0bfa7dc0L418-L419): Removed the inline device operators for `hip_bfloat16` comparison operations.
Testing Enhancements:
* Modified `universal_test` and `universal_test_unary` functions to handle `bfloat16` with different tolerances (`atol=1e-3`, …
> Refactor AMD pm rules to remove handwritten bf16 bool alus

- test/test_dtype.py
- test/test_dtype_alu.py
Re https://github.com/tinygrad/tinygrad/pull/7024#issuecomment-2421048032
`np.errstate(all='ignore')` was ignoring errors as well, which affected tests in CI.
This fix ensures that only warnings are ignored. Errors will be raised as usual (I tested this by deliberately changing tests locally).
Source for the fix: https://docs.pytest.org/en/stable/how-to/capture-warnings.html#pytest-mark-filterwarnings
> fix test warnings without affecting errors

- tinygrad/engine/search.py
it's missing if we rebuild all kernels, not just the first 2k.
```
PYTHONPATH="." GPU=1 python3 extra/optimization/get_action_space.py
29%|█████████████████████████████████████▋                                                                                            | 3682/12701 [01:42<04:11, 35.83it/s]Traceback (most recent call last):
File "/Users/chenyu/code/tinygrad/extra/optimization/get_action_space.py", line 27, in <module>
test_rebuild(lin)
File "/Users/chenyu/code/tinygrad/extra/optimization/get_action_space.py", line 11, in test_rebuild
assert o in actions, f"{o} is not in actions"
^^^^^^^^^^^^
AssertionError: Opt(op=OptOps.LOCAL, axis=6, amt=2) is not in actions
```
> Add Opt(op=OptOps.LOCAL, axis=6, amt=2) to actions

- test/test_dtype_alu.py
https://github.com/tinygrad/tinygrad/actions/runs/11429782600/job/31796546477?pr=7168#step:22:75
Can repro the failure on a real AMD machine.
> skip test_bfloat16_unary on AMD

- test/test_assign.py
- tinygrad/engine/lazy.py
- tinygrad/engine/schedule.py
This bug blocks big graph progress. Found this in #7170 - The resnet code hangs for a Buffer reuse post-assign in the optimizer step:
I think Tensor should always guarantee that once a lazybuffer is assigned to it can't get reassigned to that exact LazyBuffer.
> assert a schedule double realize

- test/unit/test_shapetracker.py
- test/unit/test_uop_symbolic.py
- tinygrad/ops.py
instead of checking gcd for all uop, check the gcd of the ones that have const_factor() > 1 and still can simplify if others are smallish
> more generic lt_folding

- examples/gpt2.py
- test/unit/test_disk_tensor.py
- tinygrad/nn/state.py
In reference to the last comments on #7046.
`ggml_data_to_tensor` does not return `None` if a type is not supported, it raises a `KeyError`. Mypy does not recognize this, which means that explicitly setting the return type to `Tensor` creates a mypy error.
Do we want to spend one line on an explicit error?
> GGUF cleanup

- tinygrad/engine/schedule.py
This diff unblocks DFS buffer append order, eg ScheduleItem bufs in a multi output kernel: [out1, *inputs_to_out1, out2, *inputs_to_out2].
> compute ScheduleItem writable bufs [pr]

- tinygrad/engine/schedule.py
- tinygrad/ops.py
This unblocks UOps.ASSIGN work for big graph #7044 milestones 2 and 3.
Given a big graph with two LOADs:
BUFFER 32 -> LOAD
BUFFER 32 -> ASSIGN -> STORE -> LOAD
The small graphs (ASTs) become:
BUFFER 32 -> PRELOAD
BUFFER 32 -> LOAD
The scheduler can differentiate pre and post ASSIGN Buffer read and toposort correctly.
> proposal: add UOps.PRELOAD

- extra/backends/hsa_graph.py
- test/test_graph.py
- tinygrad/engine/jit.py
- tinygrad/renderer/__init__.py
- tinygrad/runtime/graph/cuda.py
- tinygrad/runtime/graph/hcq.py
This diff removes the use of `outcount` to slice mutable bufs in runtime/*, which assumed writable bufs are always first (BFS order).
[Big graph appends bufs in DFS order,](https://github.com/tinygrad/tinygrad/pull/7224) so a kernel can look like:
STORE 0, LOAD 1, STORE 2, LOAD 3 - output mask: [0, 2].
> mask out writable bufs in runtime access_resources

- test/test_linearizer.py
- tinygrad/engine/schedule.py
This diff switches the append order for ScheduleItem Buffers from BFS to DFS order.
For example, a Multi-output kernel in this order will look like:
WRITE 0, READ 1, WRITE 2
vs BFS:
WRITE 0, WRITE 1, READ 2
eg: ScheduleItem.bufs for `test/test_linearizer.py TestKernelOpts.test_padto_where_multioutput`
```diff
- (<buf real:False device:CLANG size:289 dtype:dtypes.int offset:0>, <buf real:False device:CLANG size:289 dtype:dtypes.int offset:0>, <buf real:True device:CLANG size:83521 dtype:dtypes.float offset:0>)
+ (<buf real:False device:CLANG size:289 dtype:dtypes.int offset:0>, <buf real:True device:CLANG size:83521 dtype:dtypes.float offset:0>, <buf real:False device:CLANG size:289 dtype:dtypes.int offset:0>)
```
DFS order invalidates using `len(outputs)` to slice writable buffers. I …
> dfs append_bufs

- tinygrad/engine/schedule.py
PRELOAD makes this much easier to detect and give an actionable next step for that specific kernel.
VIZ of `TestAssign.test_assign_diamond_contiguous_cycle`
prev error message:
```
File "schedule.py", line 433, in create_schedule_with_vars
RuntimeError: cycle detected in graph, prescheduled 3 but only scheduled 0
```
this branch:
```
File "schedule.py", line 205, in _lower_lazybuffer
RuntimeError: cycle detected in kernel.
help: consider using .contiguous() to load the pre-assign version of <buf real:True device:METAL size:4 dtype:dtypes.float offset:0>.
```
I think with embedded metadata in UOp this can get better too.
> early assert cyclic read [pr]

- test/unit/test_uop_symbolic.py
- tinygrad/ops.py
incorrect if numerator is negative, also updated the tests when div by negative const
> limit idiv by neg bound to only if s0 is non-negative [pr]

- tinygrad/engine/fuse.py
- tinygrad/engine/schedule.py
splitting these 200 lines of fusion code to a different place, all the big graph stuff will still be in schedule.py.
I don't think fuse.py will exist in this way after lazy.py is removed though.
> split to fuse.py and schedule.py [pr]

- examples/llama3.py
- extra/models/llama.py
#7180 
Some kv_data from the file isn't used, namely the model params which are hardcoded and the tokens which are copied from 8B. (Maybe you want that changed for this example?)
> Llama 3.2 1B load from GGUF

- test/test_renderer_failures.py
- tinygrad/renderer/ptx.py
This fixes a bug in the PTX renderer where the correct branch condition was inverted. This is the second of three PRs for the "Gated Store Rewrite to UOps.IF" bounty as discussed here: https://github.com/tinygrad/tinygrad/pull/7006. 
If this (and the previous PR) are successfully merged to master, I'll quickly create the final PR which will perform the actual graph rewrite, as well as remove all logic for gated stores from renderers.
> fixing branch condition on UOps.IF in the ptx renderer

- test/external/process_replay/helpers.py
- test/external/process_replay/process_replay.py
- tinygrad/codegen/kernel.py
- tinygrad/engine/schedule.py
towards sharing process replay with schedule and kernel. Once it's a generic helper schedule.py can use the context dict.
> always run process replay with contextvars

- test/unit/test_uop_vmin_vmax.py
- tinygrad/ops.py
Fix calculation of vmin and vmax in multiplication when one src is negative and the other src has negative min and positive max.
Using render from `test_uop_symbolic`
```python
print(render(-2 * Variable("a", -2, 4)))
```
Outputs:
```
('(a*-2)', -2147483648, 2147483647)
```
Added a test as well
> Fix calculation of vmin and vmax in multiplication

- tinygrad/engine/schedule.py
so the idea here is that all UOp srcs in the schedule become LOAD of some buffer.
Then this allows the scheduler to decide which STORE/LOADs to fuse/fold.
This is the expression of lazy.py and multi output in graph_rewrite rules.
> everything is load

- tinygrad/helpers.py
- tinygrad/nn/__init__.py
- tinygrad/tensor.py
it's used more often as generic tuple, also removed the default 2.
> make_pair -> make_tuple [pr]

- tinygrad/viz/serve.py
It definitely shouldn't crash.
VIZ has two dependancies for rendering:
1. rendering the code
2. UOp repr
This should handle UOp repr errors too, like a generic "render error" message if any non-critical extra detail fails to render.
> pass viz render errors

- tinygrad/ops.py
`x.src[1].tuplize < x.src[0].tuplize` implies `x.src[0] is not x.src[1]`
also renamed cc -> op
> simpler commutative flipping condition

- examples/yolov8.py
Calling
python3 examples/yolov8.py ./test/models/efficientnet/Chicken.jpg
used to result in this error
ValueError: Calling nonzero on 0d arrays is not allowed.
Using np.atleast_1d makes sure we avoid a zero-dimension array.
> Fix ValueError in Yolo 8 example

- tinygrad/renderer/cstyle.py
To avoid conversion back and forth that requires routines from compiler-rt (long double = 128 bit double on most platforms)
For #7365
> Use double sqrt instead of long double sqrt for double on clang

- docs/quickstart.md
"We use with Tensor.train() set the internal flag" -> "We use with Tensor.train() *to* set the internal flag"
> fix small typo

- test/unit/test_transcendental_helpers.py
- tinygrad/codegen/transcendental.py
we can safely assume input is non-zero, also removed unneeded bitcast
> remove special 0 case in frexp

- tinygrad/codegen/uopgraph.py
- tinygrad/ops.py
- tinygrad/renderer/llvmir.py
- tinygrad/renderer/ptx.py
Saw chenyu pr on shl and shr refactor of transcendental and most of llvm tests failed due to the lack of support of those op in the backend. I don't know if it was removed or never added to the backend for some specific reason but I believe it is worth having support for them in llvm backend.
> Add shl and shr to llvmir

- tinygrad/ops.py
Update spec to cover llvm and ptx requirements
given `x >> y` or `x << y`:
[LLVM](https://llvm.org/docs/LangRef.html#shl-instruction): `x.dtype == y.dtype`
[PTX](https://docs.nvidia.com/cuda/parallel-thread-execution/#logic-and-shift-instructions-shl): `y.dtype == uint32`
> update shifts spec

- examples/sdxl.py
Implements the fix when calling a JIT function 2 separate times before using the result.
This PR relies on the merging of #7154 and will be converted from draft to PR once that is done.
Ran SDXL batched inference code and computed the CLIP score (higher is better).
Before
```
clip_score: 0.2597
```
After
```
clip_score: 0.3468
```
> Split SDXL Gen Fix

- test/test_ops.py
Currently trying to find a way to have `ceil_mode` fit nicely in code
spammed some tests (fuzzed?) for our pools and found a failure case that should pass
exact error is 
`AssertionError: invalid shrink ((0, 1), (0, 1), (0, 1), (0, 10), (0, 2), (0, 9)) for (1, 1, 1, 9, 2, 11)`
raised by the `shrink` from this in `_pool`
```
xup = xup.shrink(
tuple(noop_ + flatten(((0,k), (0,o*s)) for k,o,s in zip(k_, o_, s_)))).reshape(noop_ + flatten((k,o,s) for k,o,s in zip(k_, o_, s_)))
```
real output should be
```
In [48]: torch.nn.functional.avg_pool2d(x, kernel_size=(1,2), padding=(0,1), stride=(5,1), count_include_pad=False).shape
Out[48]: torch.Size([1, 1, 2, 9])
```
I'll think about this a bit more and see if there's a clever way to have both this fixed and ceil_mode added.
> failure test case for pool ops

- tinygrad/codegen/uopgraph.py
i think ths is better than `(p[0], cast(Callable, p[1]))`
> update get_transcendental_patterns [pr]

- tinygrad/ops.py
`ConstLike = ConstType|Variable|Tuple[ConstType, ...]`. fixed the wrong `Tuple[ConstType]`
> ConstLike type [pr]

- test/helpers.py
- test/test_transcendental.py
- tinygrad/renderer/llvmir.py
reassoc reorders compute and breaks transcendental
fix #7421
> remove reassoc from LLVM flags

- test/test_ops.py
- test/test_schedule.py
- tinygrad/tensor.py
wrote a fix for the pool edge case but hit problems in `test_schedule`
it turns out that the 3 tests in `test_schedule` was doing conv with input shape `[2,2]` and weight shape `[3,3]` and was passing. 
Torch raises error for this `RuntimeError: Calculated padded input size per channel: (2 x 2). Kernel size: (3 x 3). Kernel size can't be greater than actual input size`
so I changed the weight shape, and kernel count increased....
I'm not sure whats suppose to fuse and what's not suppose to fuse.
also not sure if decreasing the weight shape is even the right test...
> fix test_schedule conv2d bug

- test/test_schedule.py
it shoult test some other properties. flakying with time test https://github.com/chenyuxyz/tinygrad/actions/runs/11688403523/job/32548762512
> increase threshold test_strongly_connected_DAG

- test/test_symbolic_ops.py
- test/test_symbolic_shapetracker.py
I hit this while writing fusion UPats in big graph #7556.
No asserts pre symbolic deletion `518c022c29104d79c7a50ec41af5b7e6404da317g`.
> failing test for View.__add__ RecursionError

- test/test_symbolic_shapetracker.py
- tinygrad/shape/view.py
the issue is that the symbolic shape is not greedly simplified and canonicalized before reshape
> fix view add with symbolic shape

- test/test_schedule.py
Big graph fusion #7556 found some failing tests for multi reduce swizzle.
These are isolated in view_left+view_right pattern matchers so I can work on them independently to unblock merging big graph.
> swizzle tests from the delete_fuse branch [pr]

- test/test_schedule.py
- tinygrad/engine/schedule.py
This test has an interesting discovery, should big graph swizzle pre split?
whether or not swizzle is possible becomes the fusion criteria. No (or very few) new UPats needed.
> late fusion tests, early merge view GroupOp.Buffer [pr]

- test/test_multitensor.py
https://github.com/tinygrad/tinygrad/actions/runs/11724131309/job/32657333309?pr=7572#step:17:153
Failed on completely unrelated change. Is there a reason Tensor.manual_seed is not used?
> Increase test tolerance for flaky probabilistic test

- test/unit/test_simplify_valid_idx.py
- tinygrad/ops.py
in simplify_valid, we start with valids that are in others' parent so the others is more likely to be simplified
> different valid order

- tinygrad/nn/__init__.py
Since WebGPU doesn't have `long`, `num_batches_tracked` has to be an `int` on WebGPU. This is currently a `Device.DEFAULT == "WEBGPU"` hack in the [WebGPU PR](https://github.com/tinygrad/tinygrad/pull/7063/files), can be done now cleanly with `is_dtype_supported`
> num_batches_tracked long only if supported [pr]

- examples/openpilot/compile3.py
- test/external/external_benchmark_openpilot.py
Initializing the Tensors to input into the models takes a considerable amount of time (5ms on latest master?). This makes it much slower than the thneed version of the openpilot runner. The input casts need to be added to the benchmark for the comparison to be fair and this not to regress.
> openpilot benchmark: add cast from numpy to benchmark

- test/test_linearizer.py
- tinygrad/ops.py
`Ops.ALU` is not used anymore, which used to be arg, is now op.
There were two occurrences in tests that still referenced `Ops.ALU`, I replaced them with `GroupOp.ALU`
> Remove Ops.ALU

- test/unit/test_shapetracker.py
- tinygrad/shape/shapetracker.py
uop_given_valid does not guarantee output to be flat. fixed one last real_strides test.
> rewrite idx again in real_strides after uop_given_valid

- test/test_metal.py
- tinygrad/runtime/ops_metal.py
fixed BEAM if src is invalid on METAL. it currently only accept RuntimeError in `_time_program`
> METAL raise RuntimeError with no compiler and bad src

- test/test_schedule.py
- test/unit/test_verify_ast.py
- tinygrad/codegen/kernel.py
In master, kernel.py's error for leftover swizzle is incomprehensible. This assert makes it easier to write big graph swizzle UPats.
> early assert swizzle in kernel [pr]

- extra/mockgpu/mockgpu.py
- test/testextra/test_mockgpu.py
Python typing_extensions [assumes](https://github.com/python/typing_extensions/blob/9340ce7f4e5e89617e63ac30a00118934200a471/src/typing_extensions.py#L3428) builtin.memoryview is a class (3.11, couldn't reproduce on 3.12). When it isn't, everything [blows up](https://github.com/tinygrad/tinygrad/actions/runs/11763036338/job/32766560039#step:17:1755)
Submitting this as a separate PR because this was just triggered by #7615 and can probably be triggered by an unlucky import ordering as well
> Hook memoryview via class instead of a function

- tinygrad/engine/schedule.py
- tinygrad/ops.py
it's kind of like the `gep` simplify stuff.
UOp.view will continue to borrow logic from LazyBuffers's ._view as big graph progresses.
> calling view on graph edges is fine [pr]

- docs/env_vars.md
I asked in Nov 11 stream if VIZ should be added to env_vars.md and George agreed.
One thing I noticed is /tinygrad/viz/README isn't currently a .md extension. Not sure if that's intended.
> adding viz to env_vars docs

- .github/workflows/benchmark.yml
- test/test_speed_v_torch.py
"operation cache defeats" adds 1 to all arg, which were centered around 0. adding 1 makes big matmul and matvec go inf.
fixed by subtract 1 after and bumpped tolerance for half input
> fix HALF=1 in test_speed_v_torch

- test/test_multitensor.py
in single device or copied multi case, device is applied. but for sharded case the device is silently ignored now. maybe similar to rand we just don't allow tuple device in rand_like
> add rand_like test case with device specified

- docs/env_vars.md
existing one throws 404 because mkdocs does not allow traverse above doc root (i think?). so for now just stick the github link to it
> update env_vars doc on VIZ link

- tinygrad/renderer/cstyle.py
This PR is related to [WebGPU](https://github.com/tinygrad/tinygrad/pull/7063) simplification. It adds `render_cast` to be used in string rewrites that use cast (like `CONST` and `CAST`). Adds +1 line, but removes [4](https://github.com/tinygrad/tinygrad/blob/60e7ac6685916b86cebd837d1ab6b98fc2123703/tinygrad/renderer/wgsl.py#L58) from WebGPU, where the +/-inf, nan, and cast string rewrites have to be duplicated just because of different cast style. This approach makes it possible to not duplicate.
> Add render_cast

- test/test_schedule.py
VIZ=1 of test_schedules has duplicate kernels
> use the method_cache in test_schedule [pr]

- tinygrad/ops.py
incomprehensible error for an innocent looking diff. This should've been caught earlier.
https://github.com/tinygrad/tinygrad/actions/runs/11857319813/job/33045429560#step:15:328
> assert buffer VIEW is void [pr]

- tinygrad/engine/schedule.py
- tinygrad/ops.py
The src[2].src[2] is still a mess, #7695 fixes that!
I first called this forced_realize to mirror lazy, but I think `is_contiguous_base` is more comprehensive.
`(Ops.CONTIGUOUS, src=(load_store.view(...)))` already expresses the contiguous pre load option.
This flags:
1. `(Ops.CONTIGUOUS, src=(op.view(...))` just swizzles then realize immediately. (rewrites to `(Ops.CONTIGUOUS, src=(op,))`)
2. early `(Ops.CONTIGUOUS, src=(op,))` is also fine, it's a user controlled immediate realize.
> add property to flag contig buffer uop [pr]

- test/test_lazybuffer.py
- tinygrad/engine/schedule.py
keeping it as you _could_ call .contiguous on a metaop, like:
This can be an instant rule in UOp's metaop method.
> to_uop one path for all ops part 1

- test/test_multitensor.py
- tinygrad/tensor.py
similar to Tensor(LazyBuffer) as we don't cast implicitly
> fix Tensor(MultiLazyBuffer) with different dtype should fail

- tinygrad/runtime/ops_amd.py
The CWSR save area allocation has the wrong size, the kernel expects some debug memory to be available after the main save area.
Linux 6.12-rc1 and above [validate the size of this allocation](https://lore.kernel.org/all/20240715123502.7013-1-Philip.Yang@amd.com/), causing the queue creation ioctl to fail with `OSError: [Errno 22] Invalid argument`.
> Fix AMD queue CWSR memory size

- test/unit/test_tqdm.py
- tinygrad/helpers.py
This fixes an issue where a `tqdm` context manager style isn't supported. This causes an error when this file got migrated over to use tinygrad's `tqdm` and throws the following error:
This PR now adds support for context manager inside tinygrad's `tqdm`:
> Context manager support for tqdm

- tinygrad/engine/schedule.py
This is faster, I think more readable too, metadata shouldn't be its own iteration of sparents, that's expensive.
There's lines being wasted in dataclass field definitions (both ScheduleContext and ScheduleItemContext track this).
Deleting those in https://github.com/tinygrad/tinygrad/pull/7767.
> metadata appending to graph_rewrite

- tinygrad/engine/schedule.py
benchmarked on tiny18
```
~/code/tinygrad (master) > SCHEDULE_ONLY=1 python3 test/external/external_benchmark_schedule.py
***** model tensor in     61.82 ms
***** model schedule in  203.31 ms
all 265.20 ms
~/code/tinygrad (faster_assign_view_check) > SCHEDULE_ONLY=1 python3 test/external/external_benchmark_schedule.py
***** model tensor in     61.47 ms
***** model schedule in  198.27 ms
all 259.81 ms
```
> faster assign view check [pr]

- .github/workflows/test.yml
fixed `fatal: not a git repository (or any of the parent directories): .git` because $HOME is not $GITHUB_WORKSPACE
> fix CI beautiful_mnist dir

- test/test_nn.py
- tinygrad/nn/state.py
Raise an error if the size of your tensors in the loaded model don't match the input model.
Mentioned in [discord](https://discord.com/channels/1068976834382925865/1069001075828469790/1307730523820658810).
> Raise error when model architecture does not match state dict

- test/test_kernel_cache.py
Fixes a regression introduced in https://github.com/tinygrad/tinygrad/commit/c100f3d40618ff7f19ded78eee89d8a0dc253135.
```
self = <tinygrad.engine.realize.CompiledRunner object at 0xfffedac82a80>
p = Program(name='E_\x1b[34m4194304\x1b[0m\x1b[90m_\x1b[0m\x1b[33m4\x1b[0m\x1b[90m\x1b[0m', src='typedef float float4 __at...))], mem_estimate=134217728, global_size=None, local_size=None, vars=[], globals=[0, 1], outs=[0], _ran_post_init=True)
precompiled = None
def __init__(self, p:Program, precompiled:Optional[bytes]=None):
if DEBUG >= 4: print(p.src)
self.p:Program = p
>     self.lib:bytes = precompiled if precompiled is not None else Device[p.dname].compiler.compile_cached(p.src)
E     AttributeError: 'NoneType' object has no attribute 'compile_cached'
tinygrad/engine/realize.py:81: …
```
> test_kernel_cache_in_action: fix test

- test/test_setitem.py
- tinygrad/tensor.py
So it might look a bit complicated but essentially the mask reduce is done manually inside the loop instead of outside which requires the squeeze(). Before in y.where(y, x) 0 is treated as False and so it takes the value from x. Instead we use the mask of y so that in the case where the mask is True and the value is 0 it still takes from y.
Edit: fix for #7739
> fix advanced setitem overlap with 0

- tinygrad/dtype.py
- tinygrad/renderer/cstyle.py
"char" might be unisgned depends on platform.
fixed `python -m pytest test/test_ops.py::TestOpsUint8::test_interpolate_bilinear` on arm64 linux
> use "signed char" for int8

- test/test_setitem.py
- tinygrad/tensor.py
chenyu pointed out the issue where if shape contained a 1. This fixes that. This way it only removes the dims from the reduce axis instead of removing all dims with 1.
> fix advanced setitem with 1 in shape

- test/test_linearizer.py
- tinygrad/renderer/cstyle.py
I had to skip bf16 tensor core support for Metal since CI doesn’t support it, even though it worked perfectly in my local setup. The tests failed with the error message below.
I'm currently working on bf16 support using uop-casting to simulate bf16 when the target lacks native support. I’ve encountered this issue before, and it’s confusing that bf16 is used in some pr kernels, even though CI skips all bf16 tests for Metal. I’m not sure why bf16 appears in some pr kernels despite this. (Still working on this)
``` python
def is_dtype_supported(dtype: DType, device: str = Device.DEFAULT):
if dtype == dtypes.bfloat16:
return device in {"AMD"} or (device in {"CUDA", "NV"} and not CI and not getenv("PTX"))
```
```
FAILED test/test_linearizer.py::TestLinearizer::test_tensor_cores - …
```
> metal bf16 tc support [pr]

- test/test_schedule.py
- tinygrad/engine/schedule.py
first step to merging the delete_lazy diff. #7801
Need this late because UOp.const_like creates CONST nodes. These can later be rewritten in big graph to VALID.
NOTE: ofc these can rewrite to just CONST if they're maskless. Once REDUCE_AXIS expresses shape in the arg. re: #6998
> move CONST/BIND -> VALID to matchers

- tinygrad/engine/schedule.py
- tinygrad/ops.py
second diff building up to #7801.
Opens up an interesting thing, should schedule just not import Buffer?
it can. Schedule doesn't ever need Buffers, all the init can be deferred to when we actually need `self.buffer` in realize.py.
Buffer to big graph is just a number, size, device and dtype.
> derive device (dname) from UOp [pr]

- tinygrad/engine/schedule.py
- tinygrad/ops.py
at this point the only reason the scheduler imports Buffer is because ScheduleItem holds a list of Buffers.
When `LazyBuffer = UOp` there's a globally accessible map of UOps to their Buffers realize.py can directly access.
> get buffer size just from Ops.BUFFER [pr]

- test/test_lazybuffer.py
- test/test_schedule.py
Moving the tests from #4465 over to UOps. Aiming to move a lot of the const folding logic in lazy.py to the scheduler.
> assert view degrade to const tests post scheduler graph_rewrite [pr]

- tinygrad/engine/schedule.py
- tinygrad/ops.py
`python3 -m mypy --lineprecision-report /tmp/test ./tinygrad/engine/schedule.py`
master vs branch:
```
Name                      Lines  Precise  Imprecise  Any  Empty  Unanalyzed
---------------------------------------------------------------------------
tinygrad.engine.schedule    431      189         12  110    120           0
Name                      Lines  Precise  Imprecise  Any  Empty  Unanalyzed
---------------------------------------------------------------------------
tinygrad.engine.schedule    432      209         12   91    120           0
```
I took the useful ones from `python3 -m mypy --warn-unused-ignores --warn-unreachable --strict ./tinygrad/engine/schedule.py`. Some of them feel redundant, like if you don't type-check MathTrait methods always return `@Self` type, it'll …
> good suggestions from mypy lineprecision-report for schedule.py [pr]

- tinygrad/engine/schedule.py
cutting out another scheduling overhead by making PRELOAD special to assigned bufs.
```
~/code/tinygrad (master) > SCHEDULE_ONLY=1 python3 test/external/external_benchmark_schedule.py
***** model tensor in     62.26 ms
***** model schedule in  205.19 ms
all 267.53 ms
~/code/tinygrad (assign_adjacents) > SCHEDULE_ONLY=1 python3 test/external/external_benchmark_schedule.py
***** model tensor in     62.27 ms
***** model schedule in  195.73 ms
all 258.07 ms
```
> faster assign scheduling [pr]

- tinygrad/renderer/cstyle.py
Working on bf16 tc support for amd. 
Using typedef instead of struct fixes vectorization for bf16.
Won't open bf16 tc pull request until I can properly test in tiny10. Progress here (ignaciosica/tinygrad#84))
process_replay has the following diff
```diff
-struct hip_bfloat16 { unsigned short data; };
+typedef unsigned short hip_bfloat16;
```
> typedef bf16 amd

- .github/workflows/benchmark.yml
- test/external/speed_v_theoretical.py
JIT=2 for metal cifar with HALF, and lower tflops for nv test_gemm_4096. failures in https://github.com/tinygrad/tinygrad/actions/runs/11980239535/job/33404098428?pr=7830
> less flaky benchmarks

- test/unit/test_attention.py
- tinygrad/tensor.py
still upcast before softmax, but faster because intermediate buffer can be stored in half (as long as qk is within half range).
> move attention upcast

- tinygrad/renderer/ptx.py
Ops.DEFINE_ACC was created in `lower_reduce_axis`, which sets the dtype for DEFINE_ACC with that of Ops.REDUCE_AXIS. REDUCE_AXIS was created in `_reduce_op` in lazy.py, which sets its dtype as with that of the lazybuffer. Vectorized dtype in lazy buffer is not valid. 
Some additional testing I did was raising exception inside the vectorized define_acc render (not in this PR), and ran beautiful_mnist and handcoded_opt, saw no errors
> remove vectorized define_acc in ptx render [pr]

- examples/llama3.py
use "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF".
```
PYTHONPATH=. JITBEAM=2 python3 examples/llama3.py --download_model --size 70B --quantize int8 --benchmark
```
on M4 Max, 40 sec to load the model and
```
enqueue in 165.15 ms
total 328.54 ms, 3.04 tok/s, 247.46 GB/s, param 221.20 GB/s
enqueue in   5.31 ms
total 168.48 ms, 5.94 tok/s, 482.54 GB/s, param 431.34 GB/s
enqueue in   5.32 ms
total 168.77 ms, 5.93 tok/s, 481.71 GB/s, param 430.60 GB/s
enqueue in   5.69 ms
total 169.51 ms, 5.90 tok/s, 479.61 GB/s, param 428.72 GB/s
enqueue in   5.41 ms
total 168.60 ms, 5.93 tok/s, 482.20 GB/s, param 431.04 GB/s
enqueue in   5.18 ms
total 168.98 ms, 5.92 tok/s, 481.12 GB/s, param 430.08 GB/s
enqueue in   5.43 ms
total 168.82 ms, 5.92 tok/s, 481.59 GB/s, param 430.49 GB/s
enqueue in   5.27 ms …
```
> download llama3 70B

- test/test_dtype_alu.py
this really tripped me out while I was doing float -> uint casting
thought I was going insane for a bit
should we treat this cast?
-------
`t1 = Tensor([2147483646.0], dtype=dtypes.float32).cast(dtypes.int32) -> 2147483647`
```
UOp(Ops.SINK, dtypes.void, arg=KernelInfo(local_dims=0, upcasted=0, dont_use_locals=False), src=(
UOp(Ops.STORE, dtypes.void, arg=None, src=(
UOp(Ops.DEFINE_GLOBAL, dtypes.int.ptr(), arg=0, src=()),
x2:=UOp(Ops.VIEW, dtypes.void, arg=ShapeTracker(views=(View(shape=(), strides=(), offset=0, mask=None, contiguous=True),)), src=()),
UOp(Ops.CAST, dtypes.int, arg=None, src=(
UOp(Ops.LOAD, dtypes.float, arg=None, src=(
UOp(Ops.DEFINE_GLOBAL, dtypes.float.ptr(), arg=1, src=()),
x2,)),)),)),))
[]
void E_(int* restrict data0, float* restrict data1) {
float val0 = …
```
> add test for inconsistent behavior in float to int casting

- tinygrad/nn/__init__.py
reshape on self.weight is noop, and don't need special case for numel 0.
> cleanup Embedding call [pr]

- test/test_tensor_data.py
- tinygrad/tensor.py
Right now `memoryview` raises an error if `data` is called on a Tensor with `0 in Tensor.shape`. This is because `memoryview` does not allow casting to a shape that includes a 0.
```
TypeError: memoryview: cannot cast view with zeros in shape or strides
```
I have added a test for this and a fix for `Tensor.shape == (0,)`.
There still is a problem with `Tensor([]).reshape(0, 2).data()`. Since casting is not allowed I do not see how to make the shapes match in that case.
> [BUGFIX] Tensor([]).data()

- test/unit/test_uop_symbolic.py
- tinygrad/ops.py
This allows mod_folding to detect cases like:
(3+3x[0-3])%4 -> 3-x[0-3]
and
(9+9x[0-3]+9y[0-3])%10 -> 9-x[0-3]-y[0-3]
The next step is to add/combine this with div folding to detect the same pattern with floor division, there is a lot of similarity between the two functions now. That would also resolve #6935.
This time also passing fuzz_symbolic :)
fuzz_symbolic passed 130_000 iterations so far on my laptop
> Improved mod folding

- tinygrad/viz/serve.py
In `_replace_uop` in `viz/serve.py`, master assumes rewriting `base` requires only rewriting its `src`s, however this is not true with matches from `(UPat(Ops.SINK, name="root")` and similar.
Fixes visible EXPAND nodes after the final expander rewrite in `uopgraph.py`.
> Fix missing final rewrite in viz

- tinygrad/engine/lazy.py
- tinygrad/engine/schedule.py
This was done a while ago, reverted because of an openpilot regression.
After big graph schedule is independent of lazybuffer, so this is fine. test_schedule also has tests for this.
> delete cast arg 2 [pr]

- tinygrad/engine/schedule.py
It's more correct this way. The logic for fold/fuse is isolated in break_sched. In master it's scattered between lazy and break_sched.
```
~/code/tinygrad (metadata_try_2) > SCHEDULE_ONLY=1 python3 test/external/external_benchmark_schedule.py
***** model tensor in     24.25 ms
***** model schedule in   81.25 ms
all 105.54 ms
~/code/tinygrad (master) > SCHEDULE_ONLY=1 python3 test/external/external_benchmark_schedule.py
***** model tensor in     24.54 ms
***** model schedule in   83.12 ms
all 107.70 ms
```
> ops metadata map try 2, early fuse [pr]

- tinygrad/runtime/ops_metal.py
fix `Tensor.ones(1000, 1000, 1000).contiguous().realize()` on METAL
on master it raises error
```
File "/Users/chenyu/code/tinygrad/tinygrad/runtime/ops_metal.py", line 139, in _alloc
if ret.value is None: raise MemoryError(f"Metal OOM while allocating {size=}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError: Metal OOM while allocating size=4000000000
```
> hotfix ctypes.c_ulong(size) for metal _alloc

- test/unit/test_simplify_valid_idx.py
- test/unit/test_uop_symbolic.py
- tinygrad/ops.py
Biggest difference is probably actually that I forgot to check if gcd changed if nothing else changed
The #7925 todo was fixed by not using the const in the gcd, and then taking it out.
> Don't take const in gcd and change the "nothing_changed" condition

- test/test_schedule.py
- tinygrad/engine/schedule.py
but something like Tensor.zeros contiguous would still work in this style. (Ops.CONTIGUOUS is the child, re: #7938)
> allow sinking childless consts and fold them [pr]

- tinygrad/engine/schedule.py
these parts should be the easiest to read in schedule.py.
btw if you have suggestions on how to do "upat templates" lmk, that inheritance is kinda meh.
> big graph do_realize cleanup and renames [pr]

- tinygrad/engine/schedule.py
these ops need to be cleaned up after each create_schedule.
> don't lru_cache is_scheduled [pr]

- tinygrad/ops.py
prereq for attaching CONST to a shape and device. The Tensor API expects CONST to have a device. It's still a "meta op". It really should be a flat CONST.reshape(shape)._copy(device), on milestone 4's cleanup list.
> conceptual uop st cleanup [pr]

- test/test_schedule.py
- tinygrad/engine/schedule.py
- tinygrad/ops.py
this enables late const folding in the scheduler. If the entire schedule folds to nothing, it's a NOOP:
> schedule sink folding with graph_rewrite [pr]

- test/test_schedule.py
- tinygrad/engine/schedule.py
The NOOP big graph in try 1 [went through one graph_rewrite pass](https://github.com/tinygrad/tinygrad/pull/7963/files#diff-120c8f826d67db123ecd7a1de1d0af40b894be9c3c3a27655819b4cd2689c581L391), hence the increased python time in
```
FAILED test/external/speed_v_theoretical.py::TestKernelSpeed::test_gemv_16384_4096 - AssertionError: 384.9744496062492 not greater than 430
FAILED test/external/speed_v_theoretical.py::TestKernelSpeed::test_gemv_4096_16384 - AssertionError: 384.76483806932373 not greater than 430
```
> schedule sink folding try 2 [pr]

- tinygrad/engine/realize.py
- tinygrad/engine/search.py
realized this after spending half an hour counting kernels in #7940.
> unset TRACK_MATCH_STATS while initing beam buffers [pr]

- test/test_jit.py
rtol=1e-5 => rtol=5e-5
This test just failed on CI on master
https://github.com/ignaciosica/tinygrad/actions/runs/12097851268/job/33733678176#step:11:169
> increase tolerance on test_jitted_view [pr]

- examples/stable_diffusion.py
We already support `uint8`, so no need the prevent that cast. The .`astype(np.uint8)` thing was also introduced because of this, [here](https://github.com/tinygrad/tinygrad/pull/2032/files#diff-9cb47193472565612f6239ffc4a259fc61bd7eb906d263db9198a1a7944929ab), and is not needed.
> Remove webgpu specific checks from stable diffusion example

- setup.py
- tinygrad/runtime/ops_webgpu.py
Starting with  `wgpu v0.19.0 `, stable diffusion segfaults with:
>  File "/Users/ahmedharmouche/Documents/tinygrad/tinygrad/runtime/ops_webgpu.py", line 56, in _copyout
>     buffer_data = self.dev.queue.read_buffer(src, 0)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/ahmedharmouche/Documents/tinygrad/venv/lib/python3.12/site-packages/wgpu/backends/wgpu_native/_api.py", line 3427, in read_buffer
>     tmp_buffer._map("READ_NOSYNC").sync_wait()
>   File "/Users/ahmedharmouche/Documents/tinygrad/venv/lib/python3.12/site-packages/wgpu/backends/wgpu_native/_helpers.py", line 268, in sync_wait
>     return self.finish()
>            ^^^^^^^^^^^^^
>   File "/Users/ahmedharmouche/Documents/tinygrad/venv/lib/python3.12/site-packages/wgpu/backends/wgpu_native/_helpers.py" …
> Downgrade wgpu to prevent sd segfault
