extra/gemm/fuzz_matmul.py, extra/gemm/simple_matmul.py, test/external/verify_kernel.py
also show unoptimized shape in verify_kernel
=> test: add fuzz_matmul and better debugging for simple_matmul

examples/mlperf/helpers.py, extra/datasets/kits19.py
fixed unet3d model_eval, will add to CI after merging new dice loss
=> scipy.signal.gaussian -> scipy.signal.windows.gaussian

examples/mlperf/model_train.py
https://github.com/mlcommons/logging/blob/master/mlperf_logging/rcp_checker/training_4.0.0/rcps_resnet.json
=> update resnet hparams based on BS=1632 RCP

tinygrad/codegen/linearizer.py
This is a pre-req to the PADTO+TC feature branch which cleans up an internal issue with no visible side-effects in the current feature base (all acc's are currently valid when tensor cores are triggered).
The purpose of this PR is to move the calculation/recalculation of all indices before the acc global_load, otherwise acc elements maybe be made with an incorrect idx or as idx=0 if the TC reduce axis is padded.
There should be no behavioral or performance changes from this refactor.
=> linearizer: refactor to define accs with potentially TC-modified idxs

extra/models/bert.py
Required for bert layers with custom init that are going to come with subsequent PR.
=> Bert monkeypatch support

tinygrad/engine/schedule.py, tinygrad/helpers.py
This is a prereq for fuzzing across scheduler optimizations.
=> Tunable multi output fusion

test/external/fuzz_linearizer.py, tinygrad/device.py, tinygrad/engine/jit.py, tinygrad/engine/realize.py, tinygrad/engine/schedule.py, tinygrad/features/search.py, tinygrad/runtime/graph/cuda.py, tinygrad/runtime/graph/hsa.py, tinygrad/runtime/graph/metal.py, tinygrad/runtime/ops_disk.py, tinygrad/shape/symbolic.py, tinygrad/tensor.py
Easier to add metadata, remove 16 lines.
=> clean up update stats

tinygrad/engine/schedule.py, tinygrad/helpers.py
sometimes you want to isolate to a particular part of the graph, or at least not capture initialization
=> SAVE_SCHEDULE as contextvar

.github/workflows/test.yml, test/external/external_test_opt.py
no more OPT=2 or OPT=3, check strict number of kernels, enabled tests that fusion works now
=> cleanup external_test_opt

test/test_linearizer.py
tested on tinybox green. bf16 tc has larger rtol and different numpy buffer size
=> fix test_linearizer tc opt tests for bf16

examples/vits.py, tinygrad/tensor.py
it was passing a const numpy array into Tensor.arange
=> fix examples vits / conversation.py

examples/whisper.py
no longer needed, the commented test case was removed too
=> remove the assign hack in whisper

examples/stable_diffusion.py
=> remove TODO: remove explicit dtypes after broadcast fix in stable_diffusion

examples/mlperf/model_train.py
also added a flag to optionally disable reset jitted steps
=> resnet print epoch ops and mem in benchmark

docs-legacy/adding_new_accelerators.md
mlops -> function, and removed some old ops. fix #4254
=> update adding_new_accelerators doc

.github/workflows/benchmark.yml, tinygrad/features/search.py
benchmark gemm and default_parallel
=> few more KFD -> AMD

.github/workflows/benchmark.yml, tinygrad/renderer/assembly.py
Fixes the invalid ptx found by matmul fuzzer
=> Ptx store gate cast to bool

test/test_schedule.py
Sets up infra for generalizing reduceop fusion for E2_ kernels, more r2_ kernels and eventually multi reduce.
=> test all permutations of reduce graph

test/test_uops.py, tinygrad/renderer/assembly.py
The test uops importing ptr_arm is not cool but I have no idea how to make it clean atm
=> Ptx beam fix

.github/workflows/benchmark.yml
also double BS for resnet training benchmark to match submission target
=> JIT=2 for mac cifar benchmark

tinygrad/features/multi.py
in resnet, instead of chunking as [43691, 43691, 43691, 43691, 43690, 43690], chunk as [43712, 43712, 43680, 43680, 43680, 43680] and those can have 32 local.
more than 2X faster for the applicable kernels and overall 1% for resnet
=> make ring allreduce chunks a multiple of 2^n if possible

tinygrad/codegen/linearizer.py
fixing issue with: https://github.com/tinygrad/tinygrad/pull/4320#discussion_r1582198802
=> hotfix: remove double assign

test/test_dtype.py, tinygrad/features/multi.py, tinygrad/function.py, tinygrad/lazy.py, tinygrad/tensor.py
sum of half does acc in float32 already, add an arg to not downcast to half and use that in mean
=> fix mean of half tensor if sum is greater than half.max

extra/datasets/wikipedia.py
=> cap default dataset wikipedia max_workers to 32

test/test_const_folding.py, test/test_multitensor.py, tinygrad/features/multi.py, tinygrad/lazy.py
const folding sum should return in the same dtype as regular sum, which can be different from input dtype
=> fix dtype of const folded sum

test/test_schedule.py
Compilation of all the fusion opportunities in llm.c.
graph for NLAYER=1 https://tiny-tools-client.vercel.app/?id=7d65124627fb4876a2c33813c08bde66
highlights:
```
// test_softmax_fusion
r_3072_64
r_3072_64n1
E_3072_64
// test_layernorm_onelayer_fusion
r_100_100
r_100_100n1
E_100_100
// test_scaled_dot_product_attention_fusion
r_256_16_16_16
r_4096_16
r_4096_16n1
E_4096_16
r_256_16_16_16n1
// test_scaled_dot_product_attention_causal_fusion
r2_16_16
E_16_16
r_256_16_16_16
r_4096_16
r_4096_16n1
E_4096_16
r_256_16_16_16n1
// test_adam_step_fusion
r2_3072_768_256
E_2359296n1
r2_3072_256
E_3072n1
```
#4321 is a lower level version of this spec.
=> good llm.c scheduler tests

tinygrad/tensor.py
dtype of randint was hardcoded to int32
=> int dtypes to randint

.github/workflows/benchmark.yml
gpt2 beam failed with JIT=0, JIT=1, JI=2, so not a JIT issue. it might be kernel bug (test_linearizer_27)
=> disable flaky mac gpt2 beam benchmark and add back cifar mac with JIT=2

examples/mlperf/dataloader.py, examples/mlperf/model_eval.py
will update train separately if batchnorm works with padding
=> pad first batch of imagenet dataloader and update eval

test/test_dtype.py, tinygrad/features/multi.py, tinygrad/function.py, tinygrad/lazy.py, tinygrad/tensor.py
breaks boolean mean and other stuff
=> remove downcast_half in sum

.github/workflows/benchmark.yml
CLANG was disabled for tinybox red for speed @wozeparrot fyi
=> NOCLANG=1 for tinybox green ci.

examples/mlperf/model_train.py, test/test_dtype.py, test/test_tensor_variable.py, tinygrad/tensor.py
divide only the reduce factor. added unit test and non-nan assertion in resnet training. also added a failed test cast for symbolic shape var
=> fix mean underflow for half tensor

examples/mlperf/dataloader.py, examples/mlperf/model_train.py
asserted if eval sample count is different from total eval file count.
=> pad resnet eval data in model_train

test/external/fuzz_schedule.py, test/test_uops.py, tinygrad/codegen/linearizer.py, tinygrad/codegen/uops.py, tinygrad/device.py, tinygrad/engine/realize.py, tinygrad/features/search.py, tinygrad/renderer/assembly.py, tinygrad/renderer/cstyle.py, tinygrad/runtime/ops_python.py
Need to fix up read/write define global
=> fix define global

examples/mlperf/dataloader.py, examples/mlperf/model_train.py, examples/mlperf/training_submission_v4.0/tinycorp/benchmarks/resnet/implementations/tinybox_green/run_and_time.sh, examples/mlperf/training_submission_v4.0/tinycorp/benchmarks/resnet/implementations/tinybox_red/run_and_time.sh
also added random seed from system in scripts
=> resnet correct steps_in_val_epoch in logging

examples/mlperf/dataloader.py, examples/mlperf/model_train.py
update model_train resnet to pad both training and eval
started a run in https://wandb.ai/chenyuxyz/tinygrad-examples_mlperf/runs/hm5gm8ku?nw=nwuserchenyuxyz
=> pad resnet training data with training data mean

tinygrad/engine/schedule.py
I think this helps focus the code on L173's constraint.
=> refactor scheduler parents search

examples/mlperf/model_train.py
=> resnet trainer: keep old cookie around until next step has been queued

test/test_multitensor.py, test/test_pickle.py, test/test_subbuffer.py, test/unit/test_disk_tensor.py, tinygrad/buffer.py, tinygrad/device.py, tinygrad/engine/jit.py, tinygrad/engine/realize.py, tinygrad/engine/schedule.py, tinygrad/helpers.py, tinygrad/lazy.py, tinygrad/ops.py, tinygrad/runtime/graph/cuda.py, tinygrad/runtime/ops_cuda.py, tinygrad/runtime/ops_disk.py, tinygrad/runtime/ops_nv.py
So this subtlety breaks `STEPS=350 BS=1536 GPUS=6 python3 examples/hlb_cifar10.py` such that it only gets 88%...
It's fine if you don't use RING though with `RING=0`
=> subbuffer support

test/test_uop_graph.py, tinygrad/codegen/linearizer.py, tinygrad/codegen/uops.py
@0xtimmy I think with the preorder approach we no-longer need it.
=> Revert "Add `insert_before` to Linearizer Functions (#4320)"

.github/workflows/test.yml, examples/llm.c/export.py
llm.c needed `"#include <tgmath.h>", "#include <stdbool.h>"`.
I think it can share CI path with imagenet to C.
=> Fix llm.c/export.py

tinygrad/tensor.py
Reverts tinygrad/tinygrad#4406
testing...
=> Revert "refactor sparse_categorical_crossentropy"

tinygrad/codegen/linearizer.py
prereq refactor for having more than one reduce in Linearizer (parallel, series).
=> refactor: pass reduceop into global_load

examples/compile_efficientnet.py, extra/export_model.py, tinygrad/engine/jit.py, tinygrad/helpers.py, tinygrad/runtime/graph/clang.py, tinygrad/runtime/graph/metal.py, tinygrad/runtime/ops_clang.py, tinygrad/runtime/ops_metal.py
A good place to write multithreaded stuff too.
=> Clang graph

.github/workflows/test.yml
~12s time saved per PR on setting up a job
=> merge EfficientNet to C with clang job

tinygrad/device.py
=> hotfix: npy is also ok

test/external/external_test_amd.py, tinygrad/runtime/ops_amd.py
Vega10 and later uses 64-bit wptr and doorbell
=> amd doorbell size ids 64bits

test/external/fuzz_linearizer.py
useful for checking late opts after TC such as GROUP, etc.
=> fuzz_linearizer: add FUZZ_REQUIRE_TC option to require TC in opts

test/test_dtype.py, tinygrad/tensor.py
cast to sum_acc_type, sum, div, then cast back
=> fix half mean and its backward

tinygrad/codegen/uops.py
PTX code generation is kinda slow, this speed up rewriting the graph, mostly by not creating a new uop for every rewrite, reducing the need to iterate over all uops to change refs
=> Speed up graph rewrite

examples/mlperf/training_submission_v4.0/tinycorp/benchmarks/resnet/implementations/tinybox_red/setup.sh
=> resnet setup power cap red box gpu to 350W

examples/mlperf/model_train.py
don't include save final check point time in run time, and some cosmetic order changes
=> polish resnet mlperf logging

test/external/speed_compare_cuda_nv.py, tinygrad/runtime/ops_nv.py
`r_50257_256_4` 1378.53us -> 691.74us and many others now the same speed as cuda
=> nv tune shmem size

tinygrad/tensor.py
=> move 0d tensor reduce axis check to _reduce

test/test_ops.py, tinygrad/tensor.py
the subtract max part should share with safe softmax
=> Tensor.logsumexp

tinygrad/engine/schedule.py
- Should generalize to "group"
- Don't need ShapeTracker
=> refactor fused children

tinygrad/engine/schedule.py
This sets up the infra for deleting forced_realize. We need to gather all children then fuse.
=> refactor: move fusion out of child iteration

tinygrad/engine/schedule.py
divides up the scheduler into 3 parts.
DAG creation is the most complex part, its pieces are going through a rewrite + simplification:
#4491
#4463
=> scheduler comments 1

tinygrad/tensor.py
still hard to undetstand, at least it prints what it's trying to expand
=> verbose error message in getitem

test/test_symbolic_jit.py, test/test_symbolic_ops.py, tinygrad/engine/jit.py
2d symbolic mean in jit does not quite work, order of the variable inputs are not deterministic?
=> add symbolic mean test cases in test_symbolic_ops and test_symbolic_jit

examples/mlperf/helpers.py, examples/mlperf/model_train.py, test/external/mlperf_bert/external_test_checkpoint_loading.py
also hard coded bert model config instead of looking up a file
@Eliulm fyi
=> fix TRAIN_BEAM and Tensor.training for mlperf bert

examples/mlperf/model_train.py
small adjustments, remove duplicated training setting and stop the script once target is hit
=> touchup bert script

tinygrad/engine/schedule.py
- docstrings for functions
- fusion comments
=> scheduler docs 2

test/test_assign.py
spec for a planned behavior change in _recursive_lazyop's assign assert.
=> assign buffer read/write tests

tinygrad/tensor.py
infer only if dtype is not set explicitly
=> cleanup dtype of tensor creation from list

test/test_linearizer.py, tinygrad/tensor.py
=> feat: add acc_dtype to einsum

test/test_setitem.py, tinygrad/tensor.py
working on supporting this, first properly raises error
=> raise error if setitem tensors have requires_grad

test/imported/test_indexing.py, test/test_setitem.py, tinygrad/tensor.py
also raise error for advanced indexing for now cuz it silently fails for people using it in discord.
=> setitem in-place operator tests

test/external/speed_compare_cuda_ptx.py
It needs to try except cuda because of 
https://github.com/tinygrad/tinygrad/issues/4580
=> Fix speed compare script

examples/llm.c/export.py
Fixing the optimizer, device API and ADAM self.t, I use this for scheduler benchmarking.
=> update llmc export

extra/models/llama.py
otherwise arange has inf if either dim or context length exceeds half.max
=> move .half() llama freq_cis to the end of sin and cos

examples/llama.py, test/test_ops.py, tinygrad/tensor.py
it supports uint tensor and non-negative scalar operand. also updated the usage in threefry and NF4 llama
=> Tensor.lshift and Tensor.rshift

tinygrad/tensor.py
=> split arange threefry

test/test_assign.py
Continuing the work from #4568
=> test masked assign views

test/external/replay_schedule.py, tinygrad/engine/schedule.py
takes out the unrelated things from the double expand diff
=> _recurse_lb cleanup

tinygrad/tensor.py
bad string replacement when we changed `function.` to `F.`
=> fix comment for Tensor.swish

tinygrad/engine/schedule.py
I think views shouldn't exist in the graph.
=> test: allbufs are base

tinygrad/tensor.py
Reverts tinygrad/tinygrad#4606
=> Revert "simpler abs and sign"

test/test_dtype.py
start breaking after github CI image update
=> skip CLANG test casts between double and half for now

test/test_schedule.py
I think CAST_BEFORE_VIEW should also delete with this.
=> base change scheduling spec

test/test_schedule.py, tinygrad/engine/schedule.py
we need a spec for shrink+complex pads
=> check simple_pads in shrink

test/external/external_test_opt.py, test/test_schedule.py
Now external_test_opt only tests e2e runs.
=> pick scheduling tests out of external_test_opt

extra/mockgpu/amd/amdgpu.py, test/external/external_test_hcq.py, tinygrad/runtime/graph/hcq.py, tinygrad/runtime/ops_amd.py, tinygrad/runtime/ops_nv.py
HCQ speed ups:
1) do not create separate queues when kernel has updatable launch dims
2) do not wait for signals from the same queue
=> hcq update queue in place

docs/showcase.md
this should  render the image correctly
=> add blob and raw=true for image in docs showcase

extra/mockgpu/nv/nvgpu.py, test/test_linearizer.py, test/test_search.py, tinygrad/codegen/kernel.py, tinygrad/renderer/__init__.py, tinygrad/renderer/assembly.py, tinygrad/renderer/cstyle.py, tinygrad/runtime/ops_amd.py, tinygrad/runtime/ops_nv.py, tinygrad/runtime/ops_python.py
=> move tc to renderers

tinygrad/codegen/linearizer.py, tinygrad/codegen/uops.py
=> root cause fix for UOps.CONST bad args

test/external/fuzz_uops.py, tinygrad/codegen/uops.py, tinygrad/engine/realize.py
This sets up the infra for running different permutations of UOps.
```
FUZZ_UOPS=1 DEBUG=7 python3 test/test_ops.py TestOps.test_tiny_add
```
=> uops fuzzing infra

test/test_linearizer.py, tinygrad/codegen/linearizer.py, tinygrad/codegen/uops.py, tinygrad/engine/graph.py, tinygrad/renderer/assembly.py, tinygrad/renderer/cstyle.py, tinygrad/renderer/llvmir.py, tinygrad/runtime/ops_python.py
LOOP implies it's serial. It can totally be parallel, so I think RANGE is a better name
=> LOOP -> RANGE

test/external/fuzz_uops.py
```
FUZZ_UOPS=1 DEBUG=7 python3 test/test_linearizer.py TestLinearizer.test_load_removed
```
works now.
=> reorder DEFINE_GLOBAL in fuzz_uops

test/test_search.py
integration test that beaming 1 kernel increments kernel count by 1, and moved exiting test_kernel_count to TestTimeLinearizer
=> update test_search kernel count

test/external/external_test_hcq.py, tinygrad/runtime/graph/hcq.py, tinygrad/runtime/ops_nv.py
LLaMA 3 on NV enqueue time:
```
NV=1 python3 examples/llama.py --gen 3 --size 8B --shard 6 --prompt "Hello." --count 10 --temperature 0 --timing
enqueue in   9.02 ms
total  39.46 ms, 25.34 tok/s, 420.30 GB/s, param 407.35 GB/s
I
```
=> nv hcq bind api

test/test_linearizer.py
- Delete `TestLinearizerUOptimize` class, optimize doesn't exist anymore.
- Delete mentions of `Compiled`
=> consolidate uops tests

examples/llama3.py, extra/models/llama.py
set default sampling params to function call to 0, and top k in llama3 to 25.
=> update llama sample for mac 32 input buffer limit

README.md
=> remove link to old adding_new_accelerators.md

test/test_linearizer_failures.py
=> example kernel that triggers Memory access fault for resnet on red

tinygrad/engine/search.py
this handles hanging beam but resnet red still faults with TC issues
=> set timeout in search _try_compile_linearized_w_idx

extra/onnx_ops.py, tinygrad/tensor.py
=> prepend `_` to broadcast_shape and deepwalk

test/external/verify_kernel.py
should've been changed with the LOGKERN to LOGKERNS change
=> test/external/verify_kernel: fix LOGKERNS variable name in comments

.github/workflows/test.yml, test/external/fuzz_uops.py
We need to customize the backtracking for fuzz_uops a bit since a standard toposort isn't sufficient for creating correct paths.
=> fuzzer path search for DEFINE_ACC

tinygrad/tensor.py
change the arg from ax1, ax2 to dim0, dim1 too
=> docs for transpose

extra/onnx_ops.py, test/imported/test_indexing.py, test/test_dtype.py, test/test_ops.py, tinygrad/tensor.py
gather(self, dim, index) to match torch
=> update Torch.gather api

tinygrad/tensor.py
repeat can take separate args now to match torch
=> docs: gather, cat, stack, repeat, squeeze, unsqueeze

.github/workflows/benchmark.yml, examples/llama.py
import quantize layers from new example llama3
add to mac benchmark
=> fix llama example quantize

test/test_linearizer.py, tinygrad/codegen/linearizer.py
Testing with:
```PYTHONPATH=. FUZZ_ALL_ACTIONS=1 FUZZ_REQUIRE_TC=1 DEPTH=4 DEBUG=2 DEBUG_VALUES=1 python3 ./test/external/fuzz_linearizer.py --file ../fuzz_matmul.txt --rtol 0.05 --atol 0.02```
=> wmma: chain unrolled WMMAs and phi only at the end

tinygrad/runtime/ops_cuda.py
Looks like some leftovers after a refactor, not even valid code anymore
=> Remove deprecated code

tinygrad/tensor.py
use _broadcasted to convert 3 cases into 1. const simplification should be handled by const folding.
=> pow cleanup part 1

test/test_ops.py, tinygrad/tensor.py
=> pow cleanup part 2

tinygrad/tensor.py
fast pow for int or (int+0.5) const exponent. and more comments
=> pow cleanup part 3

extra/mockgpu/nv/nvgpu.py, tinygrad/runtime/graph/hcq.py, tinygrad/runtime/ops_amd.py, tinygrad/runtime/ops_nv.py
WFI(wait for idle) flag on signal_exec is slow, embed signaling into qmd + wait in hcq.
=> optimize nv sync

test/test_linearizer.py, test/test_uops.py
- test_simplify_uop is tested in a much better way in `TestUOpGraph.test_where_same_fold`
- `test_tensor_cores_upcast_unroll` is testing the same behavior as `test_tensor_cores_upcast_unroll_minimal`
=> delete duplicate tests in test_linearizer

tinygrad/nn/__init__.py, tinygrad/tensor.py
need to import nn at the start of the page. maybe there's a better way to move it on top?
=> docs: fix nn rendering

tinygrad/codegen/linearizer.py, tinygrad/codegen/uops.py
This diff removes the redundancies in UOping ALUs.
=> integrate ALU uoping

docs/index.md, mkdocs.yml
tensor / function / dtype / nn under API now
=> docs: change nav structure and add repo_url

docs/favicon.svg, mkdocs.yml
I do like this more, not sure about you @chenyuxyz
=> tweak docs style

docs/quickstart.md
update import, point to docs more, remove mention that assign to index not supported
=> docs: minor update to quickstart

test/test_randomness.py, tinygrad/tensor.py
raise TypeError if low, high, dtype are not ints
=> check arg types of Tensor.randint

test/test_linearizer.py, tinygrad/codegen/kernel.py, tinygrad/codegen/linearizer.py, tinygrad/codegen/uops.py
multireduce requires changes in all codegen layers, cleaning some things up before adding them.
=> pre multi reduce codegen/* cleanup

docs/showcase.md, examples/mnist_gan.py, examples/vits.py, extra/threefry.py
fixed both examples, and i think it's better to show conversation
=> docs: showcase remove mnist_gan and add conversation.py

tinygrad/codegen/kernel.py, tinygrad/codegen/linearizer.py
follow-up on https://github.com/tinygrad/tinygrad/pull/4763
we need this for multireduce to allow render_reduceop render its own local bufs.
Verified correctness with https://github.com/tinygrad/tinygrad/pull/4742
=> map local aliases to reduceop

test/external/fuzz_shapetracker_math.py, test/unit/test_view.py, tinygrad/shape/view.py
mask / offset / strides can change during canonicalization, and contiguous can be True at the end
=> check contiguous in View.create after canonicalizing mask and offset

examples/llm.c/train_gpt2.py
=> fix train_gpt2.py

test/test_pattern_matcher.py
Standalone PR to add simple tests for each of the important fields that gets matched on.
=> Add UOps pattern matcher regression tests

test/test_ops.py
=> failed test case for ellipsis in einsum

tinygrad/tensor.py
handled the case with 0 in shape output of _cumsum, and _cumsum returns the correct shape with _first_zero=True
previously _cumsum with _first_zero generates a reduce of size (input+1) that often cannot be further optimized
=> simplify _cumsum with _first_zero=True

test/test_linearizer.py, tinygrad/ops.py
=> CMPLT is safe to pad

examples/llama3.py
some webui's need model, and some need time, and some need some other thing, so just implement basically all of them
=> greater chat api endpoint compat

tinygrad/codegen/linearizer.py
We can share the reduce idxs because reduce fusion is limited to ops with exactly the same shape and axis.
This is a prereq for rendering correct back-to-back tensor cores.
=> define indexes pre reduce

tinygrad/codegen/uops.py
Refactors the `_match` function to use `UPat`s. I currently added a `from_dict` method on `UPat` so that this PR can do the main refactor without also including all the changes to rewrite the patterns from dicts to `UPat`s. If this looks good I'm happy to add those here or in a followup PR (and remove the `from_dict` method).
Speed benchmark (M1 macbook air):
```
***** model forward in  31.49 ms
***** model schedule in  10.47 ms
***** model lower in 2608.46 ms
***** model forward in  31.40 ms
***** model schedule in  10.41 ms
***** model lower in 1556.09 ms
```
=> Refactor UOps match logic to UPat instead of dicts

tinygrad/codegen/linearizer.py
This is a prep refactor diff for merging mean+std multi reduce.
=> cleanup render_reduceop

tinygrad/renderer/assembly.py
Currently it outputs 
```
@%pred_pred_0   bra $loop_0;
@!%pred_pred_0  bra $loop_0_exit;
$loop_0_exit:
```
the second bra is a noop, and doesn't need to be there
=> Clean ptx branches

tinygrad/engine/schedule.py
The "must be contiguous for assign" error message can be incomprehensible for a new user - I think this gives more context and an actionable way to resolve it. https://discord.com/channels/1068976834382925865/1070745817025106080/1246946660790173726
=> improve augmented assign error message

tinygrad/renderer/assembly.py
less lines + you can instantly see the name of a variable the label depends on it the output
=> Remove ssa label

test/test_ops.py
prepare to fix nan, it did not work with ge and le before either
=> test_ops test cmp with special floats

test/test_pattern_matcher.py, tinygrad/codegen/uops.py
Follow up on #4827. Not sure if this will actually pass CI all the way if there were things that need to change now that the new patterns will be recognized (edit: NVM!)
=> Fix arg set in pattern matcher

tinygrad/runtime/ops_nv.py
=> nv check cmdq overrun

examples/mlperf/helpers.py, examples/mlperf/model_train.py
=> Option to disable dropout

test/test_pattern_matcher.py, tinygrad/codegen/uops.py, tinygrad/renderer/assembly.py
Followup on #4791. While doing this, I took the chance to use positional arguments wherever it wasn't too hard, let me know if I should reverse these.
=> Construct UOps patterns using UPat

examples/mlperf/model_eval.py, extra/datasets/openimages.py
This PR adds the train subset of openimages for mlperf, required to train RetinateNet.
=> add mlperf train subset of openimages

test/test_symbolic_jit.py, test/test_symbolic_shapetracker.py, tinygrad/shape/view.py
pre-requisite for symbolic arange (make symbolic ones that can be folded).
=> support symbolic reshape with non-contiguous

tinygrad/runtime/ops_nv.py
=> nv fix round of allocation sizes

tinygrad/shape/view.py
cleaned up `ret[-1]` blah and added some comments.
=> minor cleanup of view _merge_dims

tinygrad/codegen/kernel.py
=> cleanup kernel simplify_merge_adjacent

tinygrad/shape/shapetracker.py
removed a type cast and it can early return now
=> expand ShapeTracker.invert a bit

tinygrad/codegen/uops.py
Similar to #4867 but improves speed.
=> [run_process_replay] faster and simpler match function

tinygrad/runtime/ops_amd.py, tinygrad/runtime/ops_cuda.py, tinygrad/runtime/ops_gpu.py, tinygrad/runtime/ops_hsa.py, tinygrad/runtime/ops_metal.py, tinygrad/runtime/ops_nv.py, tinygrad/runtime/ops_python.py
Fixes all but one of the `no-else-return` warnings on runtime, see https://github.com/tinygrad/tinygrad/issues/4877
I wanted to get the easy ones out of the way.
One seemed different: https://github.com/tinygrad/tinygrad/pull/4880
=> fix: else-return on runtime

tinygrad/runtime/ops_cuda.py
This is the only `_free` implementation that returns.
=> fix: _free should not return

examples/llama3.py, examples/tinychat/common.css, examples/tinychat/index.css, examples/tinychat/index.html, examples/tinychat/index.js
usage:
`python3 examples/llama3.py --model <path_to_model> --api --shard <shard_count:1> --port <port:7776>`
screenshots:
=> feat: tinychat

test/test_multitensor.py, tinygrad/tensor.py
Tested const remained const in ast. Removed the TODO in _to_const_val too
=> test cases for multitensor adds const

test/test_uops.py
Linearizer should only insert gated stores and UOpGraph automatically rewrites the gated store graph to UOps.IF -> store parents + store -> UOps.ENDIF.
I think this can be a graph rewrite rule similar to what we have in UPat.
=> UOps.IF* to graph spec

test/test_pattern_matcher.py, tinygrad/codegen/uops.py
minor cleanup before fixing two level match
=> cosmetic changes to uop _match

test/external/external_test_optim.py, test/test_multitensor.py, test/test_optim.py, test/testextra/test_lr_scheduler.py
tested some basic property, also minor formatting for a few Tensor.training setups
=> improve test_dropout_on_shard

.github/workflows/test.yml
I think only deleting rocm-llvm should work.
=> revert hsa autogen removal

test/external/fuzz_linearizer.py
resolve issues in #4887. dataset generated from ubuntu but metal does not support double
=> skip unsupported dtype in fuzz_linearizer

.github/workflows/test.yml
=> increase metal ci test timeout to 20 minutes

tinygrad/codegen/linearizer.py
This diff allocates one temp buffer per block and unblocks multi reduce.
LocalBuffer allocation needs to be more thought through https://github.com/tinygrad/tinygrad/issues/4923
=> allocate shared memory per block

tinygrad/tensor.py
`permarg[i]` is just `i`, and break the big return into two lines. [run_process_replay]
=> minor Tensor.gather cleanup

tinygrad/tensor.py
more consistent variable names and update comments before next minor cleanup that touches logic [run_process_replay]
=> minor minor Tensor.__getitem__ cleanup

examples/mlperf/model_train.py, extra/models/bert.py
Resolves small inconsistency. [Reference](https://github.com/mlcommons/training/blob/master/language_model/tensorflow/bert/run_pretraining.py#L315)
=> Residual in MLM loss + Change default steps

tinygrad/tensor.py
get rid of some confusing transpose and permute, and the if condition on dim. Saved a kernel for each dim != 0 case in test by removing the dangling transpose at the end
=> simpler Tensor.gather

extra/mockgpu/amd/amdgpu.py, test/test_search.py
Ahh, when I tested this the test just returned the cached results from the real amd gpu
=> amd mockgpu correct timer resolution

test/test_ops.py, tinygrad/tensor.py
i think all None handling can be unified and remove the calc_dim in advanced indexing
=> fix getitem with leading None

test/test_tensor.py, tinygrad/tensor.py
added a small fuzzer to test data with mixed tuple and list of numbers matched with numpy
=> support creating Tensor from python tuple

test/test_schedule.py, test/unit/test_helpers.py, tinygrad/dtype.py, tinygrad/helpers.py, tinygrad/tensor.py
no numpy. annoying that half memoryview is 3.12 feature...
=> construct Tensor from python list/tuple directly

tinygrad/tensor.py
and moved to constructor with np.ndarray
=> Tensor._fromcpu -> Tensor._fromnp

.github/workflows/test.yml, autogen_stubs.sh, tinygrad/runtime/autogen/comgr.py, tinygrad/runtime/autogen/hsa.py
tries a variety of paths including ctypes find_library before failing with a nicer error
=> autogen _try_dlopen

test/test_tensor.py, tinygrad/tensor.py
=> raise TypeError calling len() on a 0-d tensor

docs/tensor/creation.md, tinygrad/tensor.py
there was a docstring just not linked to the doc page. also updated the example to show re-seed instead of a internal variable
=> doc: manual_seed

tinygrad/engine/jit.py
found a non-deterministic bug in jit with multiple variables. but first cleanup some variable names. [run_process_replay]
=> minor cleanup in jit

tinygrad/codegen/uops.py, tinygrad/renderer/cstyle.py
A boring, not that powerful and not able to represent all possible UPats version of #4976 
Will probably be line-neutral or close once i convert a bunch of 4 lines garbage normal UPat into half a line this
=> Boring UOps to UPat compiler [run_process_replay]

test/test_symbolic_jit.py, tinygrad/codegen/uops.py, tinygrad/engine/jit.py, tinygrad/ops.py, tinygrad/runtime/graph/clang.py
fixed symbolic jit bugs with two variables.
=> sort vars in jit when building expected input args

.github/workflows/benchmark.yml
Also all three should test winograd CIFAR
=> add GPT2 half/half+beam to AMD

tinygrad/codegen/uops.py
@uuuvn fyi this cleans up that linter error
=> allow keyword args in UOp.store [run_process_replay]

tinygrad/runtime/ops_python.py
made it clear that it's only handing int now. need to handle float inf next
=> minor refactor overflow handing in  python backend

.pre-commit-config.yaml, test/external/fuzz_linearizer.py, test/external/fuzz_uops.py, test/test_linearizer.py, test/test_pattern_matcher.py, test/test_uop_graph.py, test/test_uops.py, tinygrad/codegen/uops.py, tinygrad/engine/graph.py, tinygrad/renderer/assembly.py, tinygrad/renderer/cstyle.py, tinygrad/renderer/llvmir.py, tinygrad/runtime/ops_python.py
not changing extra.
renaming UPat as well otherwise there are collisions
=> rename uop [run_process_replay] 

tinygrad/runtime/ops_amd.py, tinygrad/runtime/ops_cuda.py, tinygrad/runtime/ops_disk.py, tinygrad/runtime/ops_gpu.py, tinygrad/runtime/ops_metal.py, tinygrad/runtime/ops_npy.py, tinygrad/runtime/ops_nv.py, tinygrad/runtime/ops_python.py
as pointed out by #4877, need to add `__init__.py` to trigger pylint. fixed some errors except ops_python (will do in a separate pr, it has a lot of errors), and sub-folders in runtime
=> pylint runtime/ and shape/

.github/workflows/test.yml, test/external/replay_codegen.py, tinygrad/codegen/linearizer.py
process replay defaults to asserting no change happened, with `[no_assert]`, it can produce a full kernel diff for the branch.
We can build a tool on top of this to generate a diff for any merge commit.
=> use process replay as a diff creator

test/test_ops.py, tinygrad/function.py, tinygrad/tensor.py
raise RuntimeError if there are multiple
=> check arg to Tensor.flip can appear only once

test/test_ops.py, tinygrad/tensor.py
also added support of negative axes
=> check Tensor.permute input arg is a valid permutation

test/test_ops.py, tinygrad/tensor.py
moved None handle to be with argfix, and only resolve -1 if there's a -1
=> minor cleanup to reshape arg handling

extra/onnx_ops.py, test/test_ops.py, tinygrad/tensor.py
Tensor constructor supports creating from tuple now
=> don't cast tuple to list before creating Tensor

.github/workflows/test.yml, README.md, test/external/process_replay/README.md, test/external/process_replay/process_replay.py, test/external/process_replay/reset.py
Contains instructions for how to run process replay locally with an additional reset tool.
=> process replay contributor docs

test/test_ops.py, tinygrad/tensor.py
`x.sum(())` is fine, and `x.sum((1,))` should throw IndexError
=> fix reduce axis of 0d tensors

examples/llama3.py, extra/models/llama.py
updated scaled_dot_product_attention middle cast and removed hard-coded half in llama attention.
=> update llama attention casting

test/test_ops.py, tinygrad/tensor.py
renamed arg to `diagonal` that matches torch api, and added document and examples
=> update Tensor.triu and Tensor.tril

test/test_linearizer.py, test/test_search.py
+a few cleanups from the multi reduce tests
=> test_linearizer with multi output ASTs

tinygrad/codegen/linearizer.py
adapting some of the changes from Lowerer - Builds up on the UOp alu utils and graph_dedup.
=> simplify render_ops ctx [run_process_replay]

test/test_linearizer.py, tinygrad/codegen/linearizer.py
also fixes Variable max size to be correct and add docs for the off parameter
=> linearizer: change globals to merge into left axis/gridDims.x first

test/test_multitensor.py, tinygrad/multi.py
previously it always returns from the first device
=> multi copy_to_device return the copy on same device if possible

test/test_multitensor.py
renamed d_zero, d0, d1, d2, ... to d0, d1, d2, d3 and reused some multi device tuples
=> cleanup test_multitensor

test/test_const_folding.py, tinygrad/lazy.py
=> safely fold NEG in lazy.py

tinygrad/lazy.py
toward https://github.com/tinygrad/tinygrad/issues/5097
=> make buffer view optional with a flag

test/test_graph.py, tinygrad/device.py, tinygrad/runtime/graph/hcq.py
Fixes issue from #5050
Ideally I have to work on a fuzzer for hcq.
=> fix hcq sync

examples/stable_diffusion.py
changed default steps, forgot to update validation
=> validate stable_diffusion output

test/test_print_tree.py, tinygrad/engine/graph.py
print Upat and let const 0 uops be displayed correctly
=> print_tree UPat +fix

ruff.toml, test/external/external_benchmark_resnet.py, test/external/external_model_benchmark.py, test/external/external_test_onnx_backend.py, test/test_linearizer.py, test/test_multitensor.py, tinygrad/codegen/linearizer.py, tinygrad/helpers.py, tinygrad/multi.py, tinygrad/runtime/ops_nv.py, tinygrad/tensor.py
https://docs.astral.sh/ruff/rules/unnecessary-comprehension/
=> ruff: unnecessary-comprehension

ruff.toml, tinygrad/runtime/ops_amd.py, tinygrad/runtime/ops_python.py, tinygrad/tensor.py
https://docs.astral.sh/ruff/rules/superfluous-else-raise/
https://docs.astral.sh/ruff/rules/superfluous-else-return/
=> ruff: else-raise and else-return 

ruff.toml, test/external/external_test_opt.py, test/external/external_test_whisper_librispeech.py, test/test_nn.py, test/test_uops.py, test/testextra/test_export_model.py, test/unit/test_shapetracker.py
This can be bugprone.
https://docs.astral.sh/ruff/rules/builtin-variable-shadowing/
https://docs.astral.sh/ruff/rules/builtin-argument-shadowing/
https://docs.astral.sh/ruff/rules/builtin-attribute-shadowing/
=> ruff: names shadowing builtins

.github/workflows/test.yml
fixing https://discord.com/channels/1068976834382925865/1069001075828469790/1254192658725736638
=> safely parse quoted titles [run_process_replay]

ruff.toml, tinygrad/engine/graph.py, tinygrad/runtime/ops_nv.py
This is ruff SIM105
https://docs.astral.sh/ruff/rules/suppressible-exception/
Did not enable the rule.
=> ruff: suppressible-exception

test/test_jit.py, tinygrad/engine/realize.py, tinygrad/engine/search.py, tinygrad/helpers.py
fixed first time BEAM slowness
=> CACHECOLLECTING -> CAPTURING and don't capture clear_l2

.github/workflows/benchmark.yml
=> benchmark use JITBEAM for llama and gpt2

tinygrad/engine/realize.py, tinygrad/engine/schedule.py
These file handles are not closed.
SIM115 tripped on them.
https://docs.astral.sh/ruff/rules/open-file-with-context-handler/
=> ruff: close file handle

.github/workflows/benchmark.yml
=> remove JIT_BATCH_SIZE=4 from gpt2 NV benchmark

tinygrad/runtime/ops_nv.py
nvrtc <=12.3 does not issue buffer4 but relocs.
=> nv do reloc

test/test_jit.py, tinygrad/engine/jit.py
it's possible to support TinyJit inside TinyJit, but there are edge cases like two TinyJit functions shared another TinyJit function. so just give a more precise error for now
#5184
=> better error msg for TinyJit inside TinyJit

examples/sdxl.py
removed a few unneeded realize and contiguous too
=> fix seed = 0 in sdxl

tinygrad/renderer/cstyle.py
Makes cifar faster running bf16 on AMD and HIP
`5  522.57 ms run,    5.33 ms python,  517.24 ms HIP, 1719.33 loss, 0.001823 LR, 2.63 GB used,   1287.84 GFLOPS,    672.99 GOPS`
`5  460.25 ms run,    4.25 ms python,  456.00 ms HIP, 1719.33 loss, 0.001823 LR, 2.63 GB used,   1462.21 GFLOPS,    672.99 GOPS`
=> amd inline bf16 funcs

.github/workflows/benchmark.yml, autogen_stubs.sh, tinygrad/renderer/assembly.py, tinygrad/runtime/autogen/cuda.py, tinygrad/runtime/autogen/nvrtc.py, tinygrad/runtime/ops_cuda.py, tinygrad/runtime/ops_nv.py
Sad that nvrtc does not support ptx -> cubin, so added a nvJitLink which cuda uses.
=> nv supports PTX=1

test/unit/test_tqdm.py, tinygrad/helpers.py
can do more, but many cases are not tested
=> simpler tqdm

test/unit/test_tqdm.py, tinygrad/helpers.py
previously it only supports MM:SS.
more chars to unitscales, strip trailing "." and " " in formatting, and more tests
=> fix tqdm unit_scale and support hours in time

tinygrad/helpers.py
=> tqdm minor cleanup

test/unit/test_tqdm.py, tinygrad/helpers.py
=> simplify tqdm scale math

test/unit/test_tqdm.py, tinygrad/helpers.py
enabled progress bar match in test, it matched perfectly now
=> tqdm supports fractional blocks

test/unit/test_tqdm.py, tinygrad/helpers.py
it should be treated as total = 0 (just show iteration count). also removed duplicated ": " in fetch and fixed unit scale with total = 0
=> fix tqdm with generator without `__len__`

examples/openelm.py, extra/models/llama.py, test/test_ops.py, tinygrad/runtime/ops_disk.py, tinygrad/tensor.py
Doesn't work yet, but repeat_interleave is good.
=> OpenELM + repeat_interleave

.github/workflows/test.yml, extra/mockgpu/amd/amdgpu.py, test/test_hcq.py, tinygrad/device.py, tinygrad/helpers.py, tinygrad/runtime/ops_amd.py
Rework hcq tests. Will be a good test that runtime supports all features of hcq (graph, profiler, etc)
=> hcq spec test

tinygrad/codegen/linearizer.py
cleanup diff for the BARRIER removal. In the new way of BARRIER insertion UOps.STORE is lowered as the barrier.
=> refactor UOps.LOAD barrier [run_process_replay]

tinygrad/codegen/uops.py, tinygrad/renderer/cstyle.py
workaround if user encountered UNMUL error
=> add a flag DISABLE_LOOP_COLLAPSE

test/models/test_real_world.py
unet is parameterized now so can test a smaller one is ci
=> test stable diffusion unet in ci

docs/nn.md, examples/mamba.py, examples/openelm.py, extra/models/llama.py, test/test_multitensor.py, test/test_nn.py, tinygrad/nn/__init__.py
the norm itself has no significant value to add to Tensor method, but we would want Tensor.normalize
=> nn.RMSNorm

test/test_jit.py, tinygrad/engine/jit.py
suggested in https://github.com/tinygrad/tinygrad/commit/73395b998b6bb5c7a5c4cabde72b29a81ab51ead#commitcomment-143660402
=> simpler TinyJit inside TinyJit detection

test/test_linearizer.py, test/test_uops.py, tinygrad/codegen/uops.py
for ALU, use self.arg instead of self.op to compare
=> fix UOp.cmp_tuple for ALU

test/external/external_test_onnx_backend.py, test/test_dtype_alu.py, tinygrad/renderer/llvmir.py
fixed isnan for llvm (still have issue with < nan)
=> remove "no-nans-fp-math"="true" for LLVM

tinygrad/tensor.py
`any(x==0 for x in y)` is `0 in y`.
also `get_args(ConstType)` instead of hard coded `float, int, bool`
=> minor _broadcast cleanup

examples/handcode_bert_opt.py, examples/mlperf/helpers.py
similar to handcode_resnet50_opt.py, one file to check bert kernels without dataset.
=> handcode_bert_opt.py

tinygrad/engine/schedule.py
https://github.com/tinygrad/tinygrad/pull/5187#issuecomment-2211709211
=> track seen graphs in recursive group

tinygrad/engine/schedule.py
For now this unblocks https://github.com/tinygrad/tinygrad/pull/5187
possible to rewrite fusion with dfs and put it behind an lru. Though all of this code will be deleted with graph rewrite based fusion.
=> hotfix: cache seen graphs in fusion

tinygrad/multi.py
only need to check real once, also added type annotation
=> touchup multi dtype in elementwise

tinygrad/multi.py
add type, move around and some newlines
=> minor multi cleanup

tinygrad/tensor.py
document rounding half to even and update examples to show
=> update Tensor.round doc and example

test/test_ops.py, tinygrad/tensor.py
passing None for no upper bound or no lower bound
=> support passing None to Tensor.clip

docs/tensor/ops.md, test/test_ops.py, tinygrad/lazy.py, tinygrad/tensor.py
does not work in ptx yet due to how boolean tensor is handled
=> Tensor.any and Tensor.all

tinygrad/shape/shapetracker.py, tinygrad/shape/view.py
In the spirit of https://github.com/tinygrad/tinygrad/issues/3662 (still relevant?), this should be a method on a view.
Can be cached with a lru_cache like the other view methods, miniscule speed improvement (like 1% on llama). `idxs` needs to become a tuple for that. Did not do that here to keep the refactor clean.
=> refactor: expr_view from ShapeTracker to View

test/test_ops.py, tinygrad/renderer/assembly.py
supported boolean acc and boolean phi. and rewrite boolean max to uint8 max
=> fix Tensor.all and Tensor.any for PTX

tinygrad/renderer/assembly.py
uop.cast syntatic sugar and some newline/space cleanup
=> minor PTX matcher cleanup [run_process_replay]

test/test_linearizer.py, test/test_uops.py
fix broken PTX tests in test_linearizer and test_uops. there are tests that were skipped and broken because it runs only with CUDA=1 and we run PTX with NV=1 now
=> fix some PTX tests

test/test_linearizer.py, tinygrad/renderer/assembly.py
making sure boolean reduce with gates are handled correctly
=> fix PTX match rule for gated LOAD

.github/workflows/test.yml, docs/abstractions3.py
closes #5342
Apologies if I broke any of the contribution guidelines. This is my first PR to this repo.
Was going through the onboarding docs and noticed this small bug when trying to run `python docs/abstractions3.py`.
Error output in the linked issue above. New (error free) output below.
```
The schedule contains 28 items.
ScheduleItem(ast=(LazyOp(op=LoadOps.COPY, src=(), arg=47040000),), bufs=(<buf re
ScheduleItem(ast=(LazyOp(op=LoadOps.CUSTOM, src=(), arg=<function custom_random 
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.ADD, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.ADD, src=(
ScheduleItem(ast=(LazyOp(op=LoadOps.COPY, src=(), arg=60000),), bufs=(<buf real:
ScheduleItem(ast=(LazyOp(op=LoadOps.COPY, src=(), arg=4),), …
```
=> Simple abstractions3.py fix

test/external/fuzz_schedule.py, test/external/fuzz_uops.py, tinygrad/codegen/uops.py, tinygrad/engine/realize.py
Completes #4644.
searching through 200 toposorts:
```
DEBUG=5 FUZZ_UOPS=1 FUZZ_SCHEDULE_MAX_PATHS=200 python3 test/test_ops.py TestOps.test_bias_conv_transpose2d
```
=> fuzz uop schedules

test/test_pattern_matcher.py, tinygrad/codegen/uops.py
since the test uses list for src the UPat should match in commutative fashion.
=> [bug fix] nested commutative pattern _match [run_process_replay] [no_assert]

tinygrad/nn/state.py
=> remove the realize in _rebuild_tensor_v2

test/test_hcq.py, test/test_multitensor.py, tinygrad/runtime/graph/hcq.py, tinygrad/runtime/ops_amd.py, tinygrad/runtime/ops_nv.py
=> add update_copy to hcq spec

.github/workflows/benchmark.yml, examples/gpt2.py, examples/llama.py, test/models/test_real_world.py
replaced getenv("JIT"), effectively made gpt2 default jit
=> use helpers.JIT in llama and gpt2 examples

tinygrad/shape/view.py
_reshape_mask is only determined by mask, old_shape, new_shape. it does not need to input the whole view
=> minimize view _reshape_mask API [run_process_replay]

examples/llama.py
fixes the assert, but it's not stopping for some reason at [EOS]
Fixes: #5200
=> fix llama.py chat mode assert

.github/workflows/test.yml, test/test_ops.py
test large input to trig functions that hit different reduction algo, and test TRANSCENDENTAL=2 for all backend
=> more transcend math tests in ci

.github/workflows/test.yml, test/test_const_folding.py, tinygrad/codegen/transcendental.py
fix test name, less # noqa: E501 and removed the cast
=> more transcend cleanup [run_process_replay]

tinygrad/codegen/kernel.py, tinygrad/codegen/lowerer.py
follow-up on https://github.com/tinygrad/tinygrad/pull/5372.
=> Lowerer cleanup 2 [run_process_replay]

tinygrad/codegen/kernel.py, tinygrad/helpers.py, tinygrad/renderer/__init__.py
prereq for https://github.com/tinygrad/tinygrad/pull/5378
=> use TC options as ContextVars [run_process_replay]

tinygrad/runtime/ops_nv.py
It's a bit faster than `ctypes.addressof(from_mv())`
=> nv use mv_address

.github/workflows/test.yml
defaults to generating a diff for every new PR.
=> make [run_process_replay] [no_assert] the default

test/external/process_replay/process_replay.py
https://github.com/tinygrad/tinygrad/pull/5389#issuecomment-2224080456
=> pass lowering errors if not asserting process replay

tinygrad/engine/graph.py
=> metadata in graph

tinygrad/codegen/uopgraph.py
Check: Are PRs like this that condense the logic welcome?
=> refactor: consolidate replace [run_process_replay]

test/test_linearizer.py, tinygrad/codegen/lowerer.py
next need to support max size per dim, splitting and correct way to do reverse or arbitrary permute global dims
btw sint collapse just works now
=> make some grouped_dim test work

.github/workflows/benchmark.yml, .github/workflows/test.yml
remove the noisy `Note: switching to 'origin/master'.
You are in 'detached HEAD' state. You can look around, make experimental changes...` in log
=> add `-c advice.detachedHead=false` to process replay git checkout

test/test_linearizer.py, tinygrad/codegen/lowerer.py
=> pass Renderer.global_max / local_max into get_grouped_dims

tinygrad/codegen/kernel.py
=> smaller reshape_and_permute arg in shift_to

docs/abstractions2.py, examples/openpilot/compile2.py, test/test_schedule.py, tinygrad/lazy.py, tinygrad/tensor.py
=> clean up rest of the loadop [run_process_replay]

test/test_dtype_alu.py, tinygrad/codegen/transcendental.py
@chenyuxyz fyi
Patch for this PR https://github.com/tinygrad/tinygrad/pull/5383.
- xlog2 can now accurately compute very small inputs down to DBL_MIN. (confirmed passed all the tests in this PR https://github.com/tinygrad/tinygrad/pull/5383)
=> [Patch] Fixed an invaild value of fp64 xlog(DBL_MIN)

test/test_transcendental.py
need this to pass locally on mac
=> relax fuzz transend math threshold a bit

tinygrad/codegen/transcendental.py, tinygrad/codegen/uops.py
there are some (x - x) in dfadd2_f2_f2_f2, dfmul2_f2_f2_f2, dfdiv2_f2_f2_f2 that were removed by pattern matcher
=> simplify transcend math [run_process_replay]

tinygrad/runtime/ops_amd.py
=> amd better allocation error messages

tinygrad/runtime/ops_nv.py
No need to copy into queue (to make command) to copy data into device. Use mapped vram instead as it's done in HCQgraph
=> nv remove copy_from_cpu command

test/test_tensor.py, tinygrad/engine/jit.py
=> use is to compare types

examples/beautiful_mnist.py, test/test_nn.py, tinygrad/nn/__init__.py
=> make BatchNorm work for 2D and 3D

test/test_dtype.py
compared with np.iinfo for integer dtype
=> test dtype.min and dtype.max

test/test_ops.py, tinygrad/tensor.py
Fixes a bug where dim was being resolved after an assert that expected it to be resolved.
Also added regression tests.
=> Gather Negative Dim fix

tinygrad/codegen/lowerer.py
=> len(full_shape)-ki.upcasted -> first_upcasted

test/test_linearizer.py
changes from the multireduce fusion work.
=> reshape rawbufs in test_linearizer

tinygrad/nn/__init__.py
Increases average beautiful_mnist run eval by a little bit
=> uniform init to match torch

test/test_linearizer.py
make sure local grouped dim is correct
=> test kernel opts case for 4 local and 4 groups

tinygrad/codegen/kernel.py, tinygrad/codegen/lowerer.py
=> remove Kernel.lazyops [run_process_replay]

extra/optimization/helpers.py, test/external/fuzz_linearizer.py, test/external/verify_kernel.py, test/test_linearizer_failures.py
also add beautiful_mnist failures
=> test/external/fuzz_linearizer: fix for new AST changes

examples/handcode_opt.py
=> fix handcode_opt.py with DEBUG=2

test/external/process_replay/process_replay.py
=> option to [skip_process_replay]

test/test_linearizer_failures.py
this one is from a DEPTH=2 fuzz_linearizer search
=> test/test_linearizer_failures: add a new beautiful_mnist one

tinygrad/codegen/kernel.py
the only use case now can be further simplified
=> remove Kernel.shape_offsets [run_process_replay]

test/test_arange.py, tinygrad/codegen/uopgraph.py
=> indexing fold with casted bool

tinygrad/codegen/uopgraph.py
I don't understand how this matches. STORE should never have a dtype.
=> fix broken store rule [run_process_replay]

tinygrad/codegen/kernel.py
hc path resnet on green 10% faster
=> swap global for size 3 too

test/test_linearizer.py, tinygrad/codegen/lowerer.py, tinygrad/ops.py
only supports merging dims in a way that does not surpass limit, no splitting yet
=> some limit_dims to limit global merging

test/test_linearizer.py, tinygrad/codegen/uopgraph.py, tinygrad/codegen/uops.py
Reverts tinygrad/tinygrad#5581
=> Revert "push contract through cast to fix test_float2_acc"

extra/models/clip.py
Adds the Vision component of CLIP as well as the OpenClipEncoder model which enables the computing of a clip score between an image-text pair.
Ran identical inputs through tinygrad and pytorch implementations:
| Model | Score |
| :-: | :-: |
| tinygrad | 0.2082 |
| pytorch | 0.2088 |
| delta | 0.0006 |
Verified `stable_diffusion.py` and `sdxl.py` produce identical results before and after.
=> CLIP Vision

test/test_pattern_matcher.py, test/test_uop_graph.py, tinygrad/codegen/uopgraph.py, tinygrad/codegen/uops.py, tinygrad/renderer/assembly.py
towards instant UOps rewrite on UOp.alu
=> move UPat and PatternMatcher from uopgraph.py to uops.py

tinygrad/codegen/uops.py
dtype is always the dtype of the caller
=> move ufix inside UOp [run_process_replay]

tinygrad/runtime/ops_amd.py
lead to silently not being called
=> typo in ops_amd invalidate_caches

test/test_linearizer_dumb.py, test/unit/test_symbolic.py, test/unit/test_uop_symbolic.py
this might just get fix once basic mod simplification is done
=> dumb linearizer example that max is not simplified

tinygrad/codegen/uopgraph.py, tinygrad/codegen/uops.py, tinygrad/shape/shapetracker.py, tinygrad/shape/symbolic.py
also simplified a few set.union
=> reuse UOp.sparents in UOps.vars [run_process_replay]

test/external/process_replay/process_replay.py
currently this is a tool to help me build https://github.com/tinygrad/tinygrad/pull/5590 and other scheduler changes. Next step is running in CI.
=> start scheduler process replay

test/unit/test_uop_symbolic.py, tinygrad/codegen/uopgraph.py, tinygrad/codegen/uops.py
works if lhs is a DEFINE_VAR.
folds trivial x < -math.inf now, need to change SPECIAL to use DEFINE_VAR to fold more
=> simple UOp lt/ge folding

tinygrad/renderer/assembly.py, tinygrad/renderer/cstyle.py, tinygrad/runtime/ops_python.py
prep rewrite SPECIAL using DEFINE_VAR
=> reorder UOps.DEFINE_VAR in runtime [run_process_replay]

test/test_linearizer.py, test/test_uop_graph.py, test/test_uops.py, tinygrad/codegen/kernel.py, tinygrad/codegen/lowerer.py, tinygrad/codegen/uopgraph.py, tinygrad/codegen/uops.py, tinygrad/renderer/assembly.py, tinygrad/renderer/cstyle.py, tinygrad/runtime/ops_python.py
from `(0, "gid0", 4)` to just `("gid0", 4)`. closer to a Variable
=> update UOp.SPECIAL arg spec [run_process_replay]

tinygrad/renderer/assembly.py
gdim is not used, gid and lid do not need to be attributes
=> remove ptx PTXRenderer.gdim gid lid [run_process_replay]

tinygrad/codegen/uopgraph.py, tinygrad/codegen/uops.py
covered by the generic lt fold pattern
=> remove UOps lt pattern of booleans

tinygrad/engine/schedule.py
the end result looks something like https://github.com/tinygrad/tinygrad/compare/master...scheduler-4,  -20% beautiful_mnist
=> scheduling infra for isolated dags

test/unit/test_symbolic.py, test/unit/test_uop_symbolic.py, tinygrad/codegen/uopgraph.py, tinygrad/codegen/uops.py
#5689, with just div folding and new test cases
=> UOps div folding

tinygrad/engine/schedule.py
https://github.com/tinygrad/tinygrad/pull/5681/files#r1690087335
=> bring unbind back in Varaible const

test/external/process_replay/process_replay.py
diffing LazyBuffer schedules is slower than just lowering an AST so this is behind [compare_schedule] for now.
=> more scheduler process replay tooling

tinygrad/engine/schedule.py
this is much better infra for fusion because it's giving context if the child can group.
=> map groupable children

.github/workflows/test.yml
the test time has increased to 3 minutes, given the issue it have caught i think 24 is good enough
=> halve kernel counts in metal Fuzz Test linearizer

tinygrad/device.py, tinygrad/runtime/ops_amd.py, tinygrad/runtime/ops_nv.py
update hcq spec to alloc updating only global/local dim. prereq for a faster launch dim update
=> hcq update_exec with optional params

tinygrad/runtime/graph/hcq.py
A bit faster (`0.10ms`) enqueue
=> hcq do not update the same signal

test/test_schedule.py, tinygrad/engine/schedule.py
I'll put this back in once
- SDXL loading is fast https://github.com/tinygrad/tinygrad/actions/runs/10098735231/job/27926390206 - tracking https://github.com/tinygrad/tinygrad/tree/sdxl
- Find a way to unit test the hash time for https://github.com/tinygrad/tinygrad/pull/5717
=> revert isolated dags scheduling

test/test_uop_graph.py, tinygrad/codegen/uopgraph.py, tinygrad/codegen/uops.py
https://github.com/tinygrad/tinygrad/pull/5444#issuecomment-2227150287
=> named UOp class "NOP" [run_process_replay]

test/unit/test_uop_symbolic.py, tinygrad/codegen/uopgraph.py, tinygrad/codegen/uops.py
made UOp.divides return the Optional[quotient] and used it for simple div folding
=> UOp simple div folding

extra/backends/hsa_graph.py, tinygrad/engine/jit.py, tinygrad/helpers.py, tinygrad/runtime/graph/clang.py, tinygrad/runtime/graph/cuda.py, tinygrad/runtime/graph/metal.py
same place where GraphRunner is defined
=> move GraphException to jit.py

.github/workflows/benchmark.yml
Seems like the bugs are fixed. AMD problem might be the compiler?
=> reenable LLaMA-3 8B BEAM on NV

tinygrad/codegen/uopgraph.py, tinygrad/codegen/uops.py
remove the need to name stuff "store_allow_any_len" in order to set allow_any_len in UOp 
building on top of #5742
=> NOp clean up any_len passing [run_process_replay]

tinygrad/codegen/uopgraph.py
all covered by generic max folding
=> remove redundant UOps max folding [run_process_replay]

test/unit/test_uop_symbolic.py
=> update test_uop_symbolic to test UOp min and max

test/external/process_replay/process_replay.py, test/external/process_replay/reset.py, tinygrad/codegen/kernel.py
`GITHUB_RUN_ID` https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
> This number does not change if you re-run the workflow run.
=> make process replay unique in retries [run_process_replay]

test/unit/test_symbolic.py, test/unit/test_uop_symbolic.py, tinygrad/codegen/uopgraph.py, tinygrad/codegen/uops.py
~~also one more distribute_mul rule~~
=> UOps.MUL bound when one is negative

.github/workflows/test.yml, tinygrad/codegen/kernel.py, tinygrad/codegen/lowerer.py, tinygrad/renderer/cstyle.py, tinygrad/shape/shapetracker.py
If I add locals, I can support the fix_st too.
=> TC=2 still sets tensor cores (and TC=3 support for locals)

.github/workflows/test.yml, extra/mockgpu/driver.py, tinygrad/multi.py, tinygrad/runtime/graph/hcq.py, tinygrad/runtime/ops_hip.py, tinygrad/runtime/ops_nv.py
mypy has stricter partial and api arg checks now
@nimlgen fyi
=> fix mypy errors in latest mypy

.github/workflows/test.yml
when cache is clear it takes time to populate cache
=> hotfix increase ci timeout to 20 mintues

.github/workflows/benchmark.yml, test/external/process_replay/restore.py, test/test_linearizer_failures.py
https://github.com/tinygrad/tinygrad/actions/runs/9995277064/job/27627040270
=> add llama3 8b BEAM=2 failures to test_linearizer_failures

tinygrad/codegen/kernel.py
=> s/self.shape_len - self.upcasted/self.first_upcast

test/test_ops.py, tinygrad/shape/view.py, tinygrad/tensor.py
fixes: #5774
Is it okay to check at a view level?
~~Regression tests pending~~
=> Add check for negative dimension in view

test/test_ops.py, tinygrad/shape/view.py, tinygrad/tensor.py
=> unify negative shape creation to raise ValueError

test/test_linearizer_failures.py, tinygrad/codegen/uopgraph.py, tinygrad/codegen/uops.py
This is [more correct](https://github.com/tinygrad/tinygrad/actions/runs/10166804663/job/28117790767?pr=5812#step:24:94), no material performance diff:
master:
```
~/code/tinygrad> PROFILE=0 python3 test/external/external_benchmark_schedule.py
***** model forward in  58.11 ms
***** model schedule in  20.10 ms
***** model uops in 118.36 ms
***** model linearize in 1565.30 ms
```
this branch:
```
~/code/tinygrad> PROFILE=0 python3 test/external/external_benchmark_schedule.py
***** model forward in  58.09 ms
***** model schedule in  19.80 ms
***** model uops in 119.52 ms
***** model linearize in 1547.35 ms
```
=> UOps.IF with rewrite rules

tinygrad/codegen/uops.py
s0,s1 instead of self.src[0] and self.src[1]
=> simpler src variables in UOp._min_max [run_process_replay]

tinygrad/codegen/uops.py
WHERE is annoying because of nan
=> UOp bounds for max

extra/qcom_gpu_driver/opencl_ioctl.py
- remove unused code
- add CP_REG_TO_MEM opcode
- fixed parse_cmd_buf for more than 1 command object by correcting an offset
- fixed memory mappings for cases when memory was allocated with KGSL_MEMFLAGS_USE_CPU_MAP.
KGSL_MEMFLAGS_USE_CPU_MAP: If set on call and return, the returned GPU address will be 0. Calling mmap() will set the GPU address. So there are no IOCTL_KGSL_GPUOBJ_INFO ioctls for that type of memory and it resulted to crash right after get_mem.
=> fix opencl_ioctl on comma

tinygrad/codegen/kernel.py, tinygrad/codegen/uopgraph.py
=> remove redundant mod 1 pattern [run_process_replay]

tinygrad/codegen/uopgraph.py, tinygrad/codegen/uops.py
and remove the redundant lt folding rule
=> add UOp bound for BinaryOps.CMPLT

test/unit/test_symbolic.py, test/unit/test_uop_symbolic.py, tinygrad/codegen/uops.py
assumes rounding towards zero like cstyles
=> UOp bound for div negative number

test/unit/test_symbolic.py, test/unit/test_uop_symbolic.py, tinygrad/codegen/uopgraph.py
don't think we are hitting it because the stride construction, still it's wrong and not needed
=> remove the wrong mod UOp pattern

test/test_pickle.py, tinygrad/engine/jit.py
Add methods to clear all intermediate buffers. This will be the new storage format for thneed.
=> CapturedJit is fun to pickle [run_process_replay]

tinygrad/codegen/uopgraph.py
group lt / div / mod together and minor cleanups
=> move UOp patterns around [run_process_replay]

tinygrad/engine/schedule.py
This is useful for fusing two different views of an arange, eg data3 here:
```
<LB METAL (4, 1) int (<ReduceOps.SUM: 1>, None)> ShapeTracker(views=(View(shape=(2, 4, 4, 1), strides=(0, 1, 0, 0), offset=0, mask=None, contiguous=False),))
<LB METAL (4, 1) int (<ReduceOps.SUM: 1>, None)> ShapeTracker(views=(View(shape=(2, 4, 4, 1), strides=(0, 0, 1, 0), offset=0, mask=None, contiguous=False),))
```
```
__kernel void r_2_4_4(__global int* data0, const __global int* data1, const __global int* data2, const __global int* data3, const __global int* data4) {
int gidx0 = get_group_id(0); /* 2 */
int val0 = data2[gidx0];
int val1 = data4[gidx0];
int acc0 = 0;
for (int ridx0 = 0; ridx0 < 4; ridx0++) {
int val2 = data3[ridx0];
for (int ridx1 = 0; ridx1 < 4; ridx1++) {
int val3 = …
```
=> infra for multi view reduce_info [run_process_replay]

.github/workflows/test.yml, test/unit/test_uop_symbolic.py, tinygrad/codegen/uops.py
breaks conv with UOP_IS_SYMBOLIC, added some conv tests in CI
=> revert some UOp IDIV bound

.github/workflows/test.yml, test/unit/test_uop_symbolic.py, tinygrad/codegen/uopgraph.py
fixed UOP_IS_SYMBOLIC=1 linearizer failure 47
=> revert a mod pattern

.github/workflows/test.yml, test/unit/test_uop_symbolic.py, tinygrad/codegen/uopgraph.py
fixed UOP_IS_SYMBOLIC=1 test_failure_40
=> remove one more UOp mod pattern

test/test_ops.py
made it pass with NOOPT which has larger accumulated error
=> increase atol and rtol test_gemm_fp16

.github/workflows/test.yml, test/unit/test_uop_symbolic.py, tinygrad/codegen/uopgraph.py
Reverts tinygrad/tinygrad#5864
=> Revert "revert a mod pattern"

.github/workflows/test.yml, test/unit/test_uop_symbolic.py, tinygrad/codegen/uops.py
Reverts tinygrad/tinygrad#5863
=> Revert "revert some UOp IDIV bound"

test/test_hcq.py, tinygrad/device.py, tinygrad/helpers.py, tinygrad/runtime/graph/hcq.py
=> hcq profiler shows dependencies

test/unit/test_symbolic.py, test/unit/test_uop_symbolic.py, tinygrad/codegen/uopgraph.py
prepare generic mod folding, also some test changes from mod folding pr
=> update UOp mod reduction patterns

tinygrad/codegen/uopgraph.py
move patterns around and update comments
=> UOp mod folding cleanup

test/test_arange.py, test/test_schedule.py, tinygrad/engine/schedule.py, tinygrad/helpers.py
```
DEBUG=1 DEBUG_ARANGE=1 FUSE_ARANGE=1 python3 examples/beautiful_mnist.py
```
after fixing all the `expectedFailures` in this diff it's ready to be the default.
=> indexing fusion 2

examples/mlperf/model_train.py
Required for 2,4-2,5M sample runs
=> Better hyperparameters for BERT training

tinygrad/codegen/uopgraph.py
=> minor cleanup to UOp mod folding [run_process_replay]

test/test_dtype.py, tinygrad/dtype.py, tinygrad/lazy.py, tinygrad/tensor.py
in Tensor creation and args into `cast` and `bitcast`, and acc_dtype
=> support using str to specify dtype

extra/onnx_ops.py, tinygrad/nn/__init__.py
=> pow(2) -> square in RMSNorm [run_process_replay]

test/helpers.py, test/test_dtype.py, test/test_dtype_alu.py, test/test_ops.py, test/test_speed_v_torch.py, test/test_subbuffer.py, test/test_transcendental.py
=> remove CUDACPU flag in tests [run_process_replay]

.github/workflows/benchmark.yml
=> enable llama 2 70B in tinybox green CI

tinygrad/renderer/cstyle.py
There's an opportunity to refactor these hardcoded strings to render_dtype too.
=> hotfix: TC renders nv_bfloat16

extra/hip_gpu_driver/hip_ioctl.py, extra/hip_gpu_driver/kfd_ioctl.h
- **feat: allow specifying processor as envvar**
- **feat: vendor kfd_ioctl.h**
=> hip_ioctl changes

test/test_arange.py, test/test_schedule.py, tinygrad/codegen/uopgraph.py, tinygrad/helpers.py, tinygrad/lazy.py
`SPLIT_REDUCEOP=0 DEBUG=2 NOOPT=1 FUSE_ARANGE=1 python3 examples/beautiful_mnist.py`
=> fast mnist indexing

extra/mockgpu/amd/amdgpu.py, extra/mockgpu/mockgpu.py
- **feat: implement same ioctl processor change**
- **feat: look for remu in different locations**
- allows overriding location with standard linux features of `LD_LIBRARY_PATH`
=> mockgpu remu changes

test/external/process_replay/diff_schedule.py, tinygrad/engine/schedule.py
```
ARANGE_DIFF=1 python3 examples/beautiful_mnist.py
```
=> diff fused arange schedules with ARANGE_DIFF=1

examples/mlperf/model_train.py, examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_green/README.md, examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_green/dev_beam.sh, examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_green/dev_run.sh, examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_green/run_and_time.sh, examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_red/README.md, examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_red/dev_beam.sh, examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_red/dev_run.sh, examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_red/run_and_time.sh, examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_red/setup.sh
FYI, [bert_green_08051012_20093.log](https://github.com/user-attachments/files/16509025/bert_green_08051012_20093.log) ran in 4:15min. 
Log is compliant with the checker: 
```
eliulm@tiny14:~$ python -m mlperf_logging.compliance_checker --usage training --ruleset 4.0.0 ./tinygrad/bert_green_08051012_20093.log 
INFO - Running compliance on file: ./tinygrad/bert_green_08051012_20093.log
INFO -  Compliance checks: training_4.0.0/common.yaml
INFO -  Compliance checks: training_4.0.0/closed_common.yaml
INFO -  Compliance checks: training_4.0.0/closed_bert.yaml
** Logging output also at compliance_checker.log
INFO - SUCCESS
```
=> MLPERF BERT submission scripts

test/helpers.py, test/test_uop_graph.py, tinygrad/codegen/uopgraph.py, tinygrad/codegen/uops.py
=> UOp.const_factor [run_process_replay]

tinygrad/engine/schedule.py
this sets up the infra for @lb_cache
=> start all cached scheduler functions with buf, st [run_process_replay]

test/unit/test_uop_symbolic.py, tinygrad/codegen/uopgraph.py
`(6x+6y)//16 -> (3x+3y)//8` etc
simpler version
=> divide by gcd in UOp div folding

test/unit/test_uop_symbolic.py, tinygrad/codegen/uopgraph.py, tinygrad/codegen/uops.py
matched symbolic and fixed UOP_IS_SYMBOLIC=1 arange folding
=> Use `(-self).lt(-x+1)` for `UOp.ge`

test/unit/test_uop_symbolic.py, tinygrad/codegen/uopgraph.py
combine and cancel the remaining const based on gcd of other terms like SumNode.
=> fancier UOp div gcd folding

test/test_schedule.py
This one is a hard case to make green with the current abstractions in the scheduler.
=> test pushing through different expands in 1 kernel

tinygrad/helpers.py
=> fix sqlite3 locks

tinygrad/runtime/ops_amd.py
=> amd raise when not supported arch

examples/mlperf/helpers.py, examples/mlperf/model_train.py
=> No checkpoint load in INITMLPERF

test/unit/test_symbolic.py, test/unit/test_uop_symbolic.py, tinygrad/codegen/uopgraph.py
simplify `(4*x+4*y+7)//16` to `(x+y+1)//4`.
fixed `GPU=1 UOP_IS_SYMBOLIC=1 IMAGE=2 python -m pytest test/test_ops.py -k conv`
=> trim const in UOp div_folding

tinygrad/codegen/uopgraph.py
=> UOp int alu patterns match all int

test/unit/test_symbolic.py, test/unit/test_uop_symbolic.py
=> add failed simplified UOp div test case

test/test_schedule.py, tinygrad/engine/schedule.py
prep for the reduceop merging diff.
=> assert test_conv_bw correctness

test/unit/test_uop_symbolic.py, tinygrad/codegen/uopgraph.py
remove an unnecessary gcd and swap the quo rem order, minimize diff for divisor pr
=> minor change to UOp div_fold

test/unit/test_uop_symbolic.py, tinygrad/codegen/uopgraph.py
in addition to try gcd of all terms, also try least common divisor of all MULs
=> divisor in UOp div_folding

tinygrad/device.py
=> simpler device_from_env [run_process_replay]

.github/workflows/test.yml, .pylintrc, extra/datasets/wikipedia_download.py, extra/mockgpu/amd/amdgpu.py, extra/mockgpu/driver.py, extra/mockgpu/mockgpu.py, extra/mockgpu/nv/nvdriver.py, extra/mockgpu/nv/nvgpu.py, extra/models/bert.py, extra/models/clip.py, extra/nv_gpu_driver/nv_ioctl.py, extra/optimization/search.py, test/imported/test_indexing.py, test/unit/test_symbolic.py, test/unit/test_uop_symbolic.py
also fixed many errors. it was not checking nested dirs. exclude autogen for now.
can we use ruff for this?
=> update pylint path to check indent/space for all

test/test_schedule.py
flaky https://github.com/tinygrad/tinygrad/actions/runs/10333939631/job/28606831006?pr=6023
=> relax rtol for test_arange_fuse_grouped_children

docs/developer/hcq.md, docs/developer/runtime.md, docs/index.md, mkdocs.yml, tinygrad/tensor.py
broken links would only show as INFO and not an error.
=> docs: fix broken links and update is_floating_point

test/test_schedule.py
one more https://github.com/chenyuxyz/tinygrad/actions/runs/10334072657/job/28607120462
=> more relax rtol for test_arange_fuse_grouped_children

tinygrad/renderer/cstyle.py
manually verified the fstring to make sure i didn't screw it up again. my bad
=> string -> fstring [run_process_replay]

tinygrad/codegen/uops.py
The UOp as AST diff requires deterministic order.
=> use dict for UOp parents

test/helpers.py, tinygrad/codegen/lowerer.py, tinygrad/codegen/uopgraph.py, tinygrad/dtype.py
it's a python int. priority should be  higher than bool, but we are not using it in type promo now.
=> bigint -> pyint [run_process_replay]

test/test_linearizer.py
Split tensor core tests for testing AMX tensor core that does not have locals
=> Split tensor core tests

tinygrad/engine/schedule.py
more lines, less dense.
also prep for UOp as AST.
=> refactor ast arg and op [compare_schedule]

test/unit/test_uop_symbolic.py, tinygrad/codegen/uopgraph.py
pretty cool that this is very easy to write now
=> UOps pattern (x%c)+(x//c)*c = x

test/helpers.py, test/test_pattern_matcher.py, test/test_uop_graph.py, test/test_uops.py, tinygrad/codegen/uops.py
This is important for the method_cache in ast as UOp.
it's the LazyOp `__eq__`+ dtype compare.
=> test: uop and lazyop have the same compare

test/test_ocl.py, tinygrad/runtime/ops_gpu.py
=> touchup cl_errors

test/test_linearizer_failures.py
with UOP_IS_SYMBOLIC=1, on METAL it breaks store fusion and have A+B and B+A being two different UOp
=> test linearizer failure 49

tinygrad/codegen/uopgraph.py
covered by generic div_folding
=> remove redundant div gcd patterns [run_process_replay]

test/test_fusion_op.py
flaky https://github.com/chenyuxyz/tinygrad/actions/runs/10392144818/job/28776666700
=> increase test_recursive_add time from 1s to 2s

test/external/process_replay/process_replay.py
=> fix qcom process_replay for kernel diff

docs/nn.md, test/test_nn.py, tinygrad/nn/__init__.py
It's used in RNNT and deltairis, good enough to move into nn
=> add LSTMCell to nn

setup.py
Makes mypy work in tiny dreamer
=> add a single py.typed

test/test_uop_graph.py, tinygrad/codegen/uopgraph.py
=> move % inside UOp mod_folding and remove deprecated tests

tinygrad/engine/search.py
I had some deep bugs in #6030 this could've caught in the linter.
=> add more types to search [run_process_replay]

tinygrad/helpers.py
more precise names and don't repeat set_description
=> tqdm touchup

test/unit/test_shapetracker.py, tinygrad/ops.py, tinygrad/shape/shapetracker.py
Reverts tinygrad/tinygrad#6120
=> Revert "use vmax for real_size [run_process_replay]"

test/unit/test_tqdm.py, tinygrad/helpers.py
~~don't default iterable to None~~, and more text cleanups
=> more tqdm touchup

test/test_dtype.py, test/test_hcq.py, test/test_randomness.py, tinygrad/dtype.py, tinygrad/tensor.py
- **feat: finfo**
- **feat: support half in threefry**
=> threefry half

test/test_randomness.py, test/test_symbolic_ops.py, tinygrad/dtype.py, tinygrad/tensor.py
also why is test_gc testing _rng_counter is allocated??
=> threefry touchup [run_process_replay]

test/test_transcendental.py
139216373.71875 failed
https://github.com/tinygrad/tinygrad/actions/runs/10446960642/job/28925156240
=> lower float64 sin fuzzer threshold

ruff.toml, test/external/external_test_amd.py, test/external/external_test_hcq.py, test/external/external_test_nv.py, test/test_assign.py, test/test_hcq.py, test/test_linearizer.py, tinygrad/codegen/uopgraph.py, tinygrad/device.py, tinygrad/helpers.py, tinygrad/lazy.py, tinygrad/ops.py, tinygrad/tensor.py
assertion should not have side effect or `-O` breaks.
initially just wanted to fix the one in rearrange, but it also made some long lines less long
=> RUF018 assignment-in-assert [run_process_replay]

test/unit/test_shapetracker.py, tinygrad/ops.py, tinygrad/shape/shapetracker.py
change MOD range to take any positive UOp
=> re:6125 switch real_size to use uops [run_process_replay]

tinygrad/function.py, tinygrad/tensor.py
float div is equivalent to mul a reciprocal
=> function.Div -> function.IDiv [run_process_replay]

test/unit/test_disk_tensor.py, tinygrad/nn/state.py, tinygrad/tensor.py
This implements the `tar_extract` functionality from #6146 and dedicated tests.
The tests are inside `test_disk_tensor.py` as this is the module I found most fitting, please let me know if there's a better one.
=> Write tar_extract

tinygrad/function.py
instead of `(1-(x!=max))`, use `(x!=max)!=True`.
prep to remove Unary.NEG, also this can be instruction fused later more easily
=> update function.Max backward

tinygrad/runtime/ops_amd.py, tinygrad/runtime/ops_nv.py
Switch all _gpu_alloc to allocator in user code
=> _gpu_alloc -> allocator.alloc

tinygrad/function.py, tinygrad/tensor.py
=> remove UnaryOps.NEG from function.py

test/test_uops.py
fixed the output_dtype for CMPNE and match the tests for CMPLT
=> add CMPNE tests in test_uops

test/test_nn.py, test/test_schedule.py, tinygrad/nn/__init__.py
-`test_batchnorm2d_no_running_stats` and `test_batchnorm3d_no_running_stats` catch the regression. Added two other tests for completeness.
=> Fix track_running_stats in batchnorm

extra/gemm/triton_nv_matmul.py
=> extra/gemm/triton_nv_matmul: fix Program arguments

tinygrad/ops.py
1. ops
2. UOp and KernelInfo
3. pattern matcher
4. ops in python
5. uop type spec
6. uop helpers
=> reorder uops.py [run_process_replay]

test/unit/test_symbolic.py, test/unit/test_uop_symbolic.py, tinygrad/codegen/uopgraph.py
now there's no NEG, with this it covers all kinds of a*x+b*x
=> UOp pattern x + x -> x * 2

test/test_uops.py, tinygrad/ops.py
cannot make all to use `repr` because ALU arg is enum
=> fix UOp repr with Variable in arg

tinygrad/tensor.py
=> minor bitcast touchup

tinygrad/engine/schedule.py, tinygrad/multi.py, tinygrad/ops.py
I think these mappings should have a single source of truth.
=> share REDUCE_ALU in multi and schedule [run_process_replay]

test/test_linearizer.py
=> fixup neg tests [run_process_replay]

tinygrad/engine/schedule.py
first part for arange / conv bw fusion with graph rewrite #6249
=> refactor reduceop swizzling (prep for UOps.SWIZZLE) [compare_schedule]

tinygrad/codegen/uopgraph.py, tinygrad/lazy.py, tinygrad/ops.py
helper for the number reduce acc is inited to (0 for ADD, 1 for MUL and -inf for MAX)
=> identity element of binary ops

test/test_schedule.py, tinygrad/engine/schedule.py
prereq for UOps.SWIZZLE #6271.
=> generic st_fixup in scheduler graph rewrite [compare_schedule]

tinygrad/engine/schedule.py
prereq refactor for complete single arange fusion.
having uops with invalid shape is fine in scheduler rewrite because it's responsible for st fixups. We assert this post rewrite.
=> uop output_st is Optional [run_process_replay]

tinygrad/engine/schedule.py
trains beautiful_mnist with graph rewrite fusion:
```
FUSE_ARANGE=1 AST_REWRITE=1 python3 examples/beautiful_mnist.py
```
=> single arange fusion with graph rewrite

examples/sdxl.py, extra/models/clip.py
1. Fixes the current issues stopping SDXL from running batched inference
2. Fixes issues related to methods using global variables that caused issues when running those classes in another file
3. Fixes the type hinting of components touched in this PR
```
$ PYTHONPATH=. NV=1 python examples/sdxl.py --seed 0
saving /tmp/rendered.png
output validated with distance=0.00289628142490983
```
```
$ PYTHONPATH=. NV=1 python examples/sdv2.py --seed 0
saving /tmp/rendered.png
```
```
$ PYTHONPATH=. NV=1 python examples/stable_diffusion.py --seed 0
saving /tmp/rendered.png
output validated with distance=9.23173956834944e-07
```
I also made a custom delta of `examples/sdxl.py` with hard-coded batching code to validate these changes worked
```
$ PYTHONPATH=. NV=1 python examples/sdxl.py --seed 0 …
```
=> SDXL Batched Inference Fixes

tinygrad/engine/jit.py, tinygrad/runtime/graph/metal.py, tinygrad/runtime/ops_metal.py
=> fix for metal ICB issue on M1/M2 [run_process_replay]

test/helpers.py, test/test_schedule.py
spec to iterate on making this curve linear.
=> graph_rewrite complexity tests [run_process_replay]

test/test_arange.py
Closes https://github.com/tinygrad/tinygrad/issues/6321
=> bump limit for test_llama_embedding_opt

test/helpers.py, test/test_fusion_op.py, test/test_pattern_matcher.py, test/test_pickle.py, test/test_schedule.py, test/test_uop_graph.py, test/test_uops.py
=> cleanup uop eq asserts for swizzle [run_process_replay]

test/unit/test_symbolic.py, test/unit/test_uop_symbolic.py, tinygrad/codegen/uopgraph.py
=> distribute MUL const into ADD for int

test/test_profiler.py
flaky, bumpped to 16000 for CI
=> increase test_profile_multidev_transfer threshold

test/test_uop_graph.py, tinygrad/codegen/uopgraph.py
This makes sure IF has a single spec across the entire graph_rewrite lifecycle.
Minimal change, I think we can delete a few more lines now that it's simpler.
=> late gate creation for STORE [run_process_replay]

test/test_linearizer.py, test/test_linearizer_dumb.py, test/test_linearizer_failures.py, test/test_uop_graph.py, test/test_uops.py, tinygrad/codegen/uopgraph.py, tinygrad/ops.py, tinygrad/renderer/assembly.py, tinygrad/renderer/cstyle.py, tinygrad/renderer/llvmir.py
Broke `BEAM=4 NV=1 HALF=1 IGNORE_BEAM_CACHE=1 DEBUG=2 python3 extra/gemm/simple_matmul.py`
=> Revert beam failure

tinygrad/helpers.py
fixed bar overflow
```
python examples/beautiful_mnist.py
```
```
https://storage.googleapis.com/cvdf-datasets/mnist/train-images-idx3-ubyte.gz: 47.0MB [00:00, 136MB/s]]
https://storage.googleapis.com/cvdf-datasets/mnist/train-labels-idx1-ubyte.gz: 60.0kB [00:00, 8.66MB/s]
https://storage.googleapis.com/cvdf-datasets/mnist/t10k-images-idx3-ubyte.gz: 7.84MB [00:00, 97.5MB/s]
https://storage.googleapis.com/cvdf-datasets/mnist/t10k-labels-idx1-ubyte.gz: 10.0kB [00:00, 8.90MB/s]
```
=> set tqdm total to None in fetch gunzip

test/test_dtype.py, tinygrad/ops.py
make sure the non-inf path returns the truncated value
=> fix output of truncate_fp16

test/test_uop_graph.py, test/unit/test_uop_symbolic.py, tinygrad/ops.py, tinygrad/renderer/__init__.py, tinygrad/renderer/assembly.py, tinygrad/renderer/cstyle.py, tinygrad/shape/shapetracker.py
new arg is (Variable, min as CONST, max as CONST). not exactly sure why some PTX kernels became simpler...
=> move DEFINE_VAR min/max from src to arg

test/test_uop_graph.py, test/unit/test_uop_symbolic.py, tinygrad/ops.py, tinygrad/renderer/__init__.py, tinygrad/renderer/assembly.py, tinygrad/renderer/cstyle.py, tinygrad/shape/shapetracker.py
now it's just arg = (expr as str, min as UOp.const, max as UOp.const)
=> remove Variable from UOp.DEFINE_VAR

tinygrad/tensor.py
simplified a bit.
it might be able to write it with only movements, but the backward would contain a reduce.
=> Tensor.roll touchup

tinygrad/ops.py
=> use uop vars for ast DEFINE_VAR [run_process_replay]

docs/index.md
thanks for the boost on [Twitter](https://x.com/obadakhalili/status/1821587868562940179)! is it enough?
=> tinygrad Tensor Puzzles

test/test_symbolic_shapetracker.py
these would have failed in #6365
=> tests of real_stride of symbolic shape

extra/optimization/extract_dataset.py, extra/optimization/generate_dataset.sh, test/external/process_replay/diff_schedule.py, test/external/process_replay/process_replay.py
Reverts tinygrad/tinygrad#6429
=> Revert "cleanup process_replay/* namings [run_process_replay]"

tinygrad/ops.py
Reverts tinygrad/tinygrad#6428
=> Revert "RewriteContext [run_process_replay]"

extra/optimization/extract_dataset.py, extra/optimization/generate_dataset.sh, test/external/process_replay/diff_schedule.py, test/external/process_replay/process_replay.py
Reverts tinygrad/tinygrad#6437
=> Revert "Revert "cleanup process_replay/* namings [run_process_replay]""

tinygrad/ops.py
Reverts tinygrad/tinygrad#6438
=> Revert "Revert "RewriteContext [run_process_replay]""

test/test_uops.py, tinygrad/ops.py
=> fix Variable init from the DEFINE_VAR refactor

test/test_schedule.py
first to fix AST_REWRITE=1, then to implement the same fusion for dtypes.half.
thanks chenyu for the test_ops ref!
=> conv bw schedule and correctness tests to iterate on

test/test_schedule.py, tinygrad/engine/schedule.py
P2 of #6464
trains beautiful_mnist with equivalent kernls as no graph rewrite.
=> green conv bw AST_REWRITE=1

tinygrad/codegen/uopgraph.py
Reverts tinygrad/tinygrad#6472
=> Revert "fold lt"

tinygrad/dtype.py
This dtypes.void doesn't yet do anything but we need it to exist in master to run process_replay.
=> init changes from the dtypes_void branch [run_process_replay]

tinygrad/engine/schedule.py, tinygrad/ops.py
I think this ltr chaining reads better.
=> add uop.swizzle(st)

tinygrad/engine/schedule.py
I don't think anyone uses this and there's no tests for it.
=> delete USE_COPY_KERNEL from the scheduler [run_process_replay]

tinygrad/codegen/kernel.py, tinygrad/dtype.py, tinygrad/ops.py
Each commit is independent and small. If any are deemed not worth the style or line count, they're easy to revert.
Combined, this is about a 20% speedup on my machine.
cc @roelofvandijk for the tip on the listcomp overhead
=> Misc rewrite perf improvements

tinygrad/runtime/ops_clang.py
=> clang compiler args

test/external/fuzz_schedule.py, test/external/process_replay/diff_schedule.py, test/external/process_replay/test_diff_schedule.py, tinygrad/engine/schedule.py
merging var_vals pre toposort.
=> var_vals prereq for deleting LBScheduleItem [run_process_replay]

tinygrad/engine/realize.py, tinygrad/engine/schedule.py
another prereq for deleting LBScheduleItem.
=> make ScheduleItem hashable [run_process_replay]

viz/index.html
LTR graph, wrapping rewrites, cleaner RHS.
=> viz minor stuff

tinygrad/codegen/uopgraph.py, viz/index.html, viz/serve.py
shows this SWIZZLE moving through the schedule graph
https://github.com/user-attachments/assets/1a6b3a1a-787d-4fe7-85be-708b9234a65b
```
VIZ=1 python3 test/test_schedule.py TestIndexing.test_simple_indexing
```
=> viz more work

tinygrad/codegen/uopgraph.py, tinygrad/shape/shapetracker.py
need MUL for valid [run_process_replay]
=> _get_add_chain(x) -> _get_chain(x, BinaryOps.ADD)

test/test_linearizer.py, tinygrad/codegen/uopgraph.py
Does this make any kernels faster? It's a reg alloc issue
=> remove logic to vectorize reduces

.github/workflows/test.yml, test/unit/test_image_valid.py, tinygrad/codegen/uopgraph.py
started unit test, 530 -> 473 valids
=> simple drop image valid case

.github/workflows/test.yml, test/unit/test_image_valid.py, tinygrad/codegen/uopgraph.py
x*(-1)<0 can be generalized to x*(-1)<c, 473 -> 462 valids
=> more generic version of #6548

.github/workflows/test.yml, test/unit/test_image_valid.py, tinygrad/codegen/uopgraph.py
=> other side of simple out of bound valid case

tinygrad/engine/schedule.py
`Any` arg for ShapeTracker is harder to develop for.
=> add swizzle_st [run_process_replay]

test/unit/test_uop_symbolic.py, tinygrad/codegen/uopgraph.py
it makes valid pattern more annoying
=> don't fold mul mod for common factor

extra/optimization/helpers.py, test/test_viz.py, tinygrad/ops.py, viz/serve.py
This was causing test_gemm to show extra rewrites.
=> viz more work [run_process_replay]

tinygrad/lazy.py, tinygrad/renderer/cstyle.py, tinygrad/runtime/ops_dsp.py
=> dsp offset buffer

.github/workflows/test.yml, test/unit/test_image_valid.py, tinygrad/codegen/uopgraph.py
=> remove LOAD where valid is an empty set

test/unit/test_image_valid.py
can save 2ms once this is fixed
=> failed test case for openpilot validhack conv

test/unit/test_uop_symbolic.py, test/unit/test_uop_vmin_vmax.py, tinygrad/ops.py
prereq to gated load simplification
=> _min_max for WHERE on dtypes int

test/test_uops.py, tinygrad/ops.py
=> fix upat .location for the type verifier

test/unit/test_image_valid.py
Sepcial and Variable to setup UOp
=> tiny cleanup of test_image_valid

viz/index.html, viz/serve.py
=> refactor viz to parse_qs

tinygrad/engine/schedule.py, tinygrad/ops.py
prereq for getting kernel name of a scheduler sink in VIZ=1.
=> move scheduler rewrites into full_ast_rewrite [run_process_replay]

.github/workflows/test.yml, test/unit/test_image_valid.py, tinygrad/codegen/uopgraph.py
also relaxed the bound check to check vmin/vmax instead just const. valids 482 -> 283
=> validhack use the new style ge for upper bound valid

.github/workflows/test.yml, examples/openpilot/compile2.py, test/unit/test_image_valid.py, tinygrad/codegen/uopgraph.py
=> UOps.RANGE is_increasing

.github/workflows/test.yml, test/unit/test_image_valid.py, test/unit/test_uop_symbolic.py, tinygrad/codegen/uopgraph.py
=> x//a<b -> x <a*b for positive a

test/external/external_test_valid_remove.py
=> add an example that idx is const and valid cannot be removed

tinygrad/ops.py, viz/test_viz.py
=> limit ctx tracking in TrackedPatternMatcher [run_process_replay]

tinygrad/codegen/uopgraph.py
valid might a const if gate folding is disabled
=> validhack explicity check valid has CMPLT [run_process_replay]

tinygrad/ops.py, tinygrad/renderer/__init__.py
=> remove UOp from DEFINE_VAR arg [run_process_replay]

viz/index.html, viz/serve.py, viz/test_viz.py
prep for a graph ranking view:
```
- schedule
-- kernel
--- uop
```
=> second iteration on viz/serve.py

tinygrad/ops.py, viz/serve.py, viz/test_viz.py
shows how each shapetracker gets rewritten to alu:
=> viz lowerer and graph_rewrite dedup try 2

test/external/external_benchmark_schedule.py, viz/index.html, viz/serve.py
Enter key toggles if it shows the kernel tree and up and down change kernels
+ capture ctx in external_benchmark_schedule.
=> viz more kernel view work

test/test_randomness.py
- **feat: this test should pass now**
- **feat: only passes with threefry**
=> check bfloat16 range with threefry

.github/workflows/test.yml, test/unit/test_image_valid.py, test/unit/test_uop_symbolic.py, tinygrad/codegen/uopgraph.py
(X := a0*x0 + a1*x1 + ...) > 0 is equivalent to x0 + x1 + ... > 0 if xi >= 0 and ai > 0 for ints
=> canonicalize simplex lt

tinygrad/codegen/uopgraph.py
=> validhack is_irreducible helper

viz/index.html, viz/serve.py, viz/test_viz.py
=> viz highlight new nodes

.github/workflows/test.yml, test/unit/test_shapetracker.py, tinygrad/codegen/uopgraph.py
=> don't use div_folding in lt_folding

viz/index.html
=> viz bugfix click in middle of UOps

examples/openpilot/compile2.py, examples/openpilot/compile3.py, tinygrad/renderer/cstyle.py
Reverts tinygrad/tinygrad#6683
=> Revert "gated native math in OpenCL"

viz/index.html
=> VIZ syntax highlighting and new colors

viz/index.html, viz/serve.py, viz/test_viz.py
=> viz fold const nodes and UOp/float4 syntax highlight

tinygrad/codegen/uopgraph.py
express valid into things to check when rewriting idx. it's the same for single clause or a simplex [run_process_replay]
=> simpler idx rewrite structure in simplify_valid_image_load

tinygrad/codegen/uopgraph.py
preparation for the brute force attempt for some valids
=> construct candidate set to attempt valid idx rewrite

tinygrad/engine/schedule.py
prereq for DEFINE_GLOBAL numbering with graph_rewrite.
=> refactor DEFINE_GLOBAL inputs to list [run_process_replay]

test/external/fuzz_schedule.py
=> give FUZZ_SCHEDULE views a base

tinygrad/codegen/uopgraph.py
will be using the simplify idx for non-image buffer [run_process_replay]
=> split validhack into simplify idx and drop valids

test/unit/test_simplify_valid_idx.py
restructure the tests, will use the same file for non-image tests
=> test_image_valid.py -> test_simplify_valid_idx.py

test/unit/test_simplify_valid_idx.py
moved UOps.VECTORIZE of idx into the helper
=> more test_simplify_valid_idx cleanup

tinygrad/ops.py, viz/index.html, viz/serve.py, viz/test_viz.py
=> viz more info for rewrite location

test/unit/test_simplify_valid_idx.py
the backward idx is pretty ugly now
=> conv backward tests in test_simplify_valid_idx

tinygrad/codegen/uopgraph.py
easier to see the diff in replacement
=> use UOp.replace and UOp.define_var in validhack

test/external/process_replay/diff_schedule.py, test/external/process_replay/process_replay.py, test/external/process_replay/reset.py, test/external/process_replay/test_process_replay.py
git commit style ```[changed] [insertions] [deletion]```.
=> process replay diff stats

examples/mlperf/model_train.py
only WANDB and RUNMLPERF order. BENCHMARK and BEAM will be done differently
=> smaller bert script change

examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_green/dev_run.sh, examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_red/dev_run.sh
already set in run_and_time.sh, need RUNMLPERF=1 for it to load real data
=> add RUNMLPERF=1 to bert dev_run.sh

tinygrad/codegen/kernel.py, viz/index.html, viz/serve.py
=> viz table view

examples/handcode_opt.py
using 54 for 6 gpus now, and 2 is not a good default
=> default BS=9 in handcode_opt bert

tinygrad/device.py, tinygrad/ops.py, viz/index.html, viz/serve.py
* run VIZ on a different process
* better layout for kernels, resizer and default expand
* logging
=> better VIZ

tinygrad/device.py, tinygrad/engine/schedule.py, tinygrad/ops.py
prereq for deleting Buffer from DEFINE_GLOBAL.
=> add UOp.define_global [run_process_replay]

tinygrad/tensor.py
should save memory since we only store mask in bool instead of the upcasted used in mul
=> use where in dropout

examples/mlperf/model_train.py, examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_green/dev_beam.sh, examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_green/dev_run.sh, examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_green/run_and_time.sh
fits BS=60 which is 2% faster than 54. also fixed wandb logging params
=> bert script delete eval data after eval

examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_green/dev_beam.sh, examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_green/dev_run.sh, examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_green/run_and_time.sh
=> bert BS back to 54

tinygrad/engine/schedule.py
prereq for deleting Buffer arg from DEFINE_GLOBAL.
=> refactor schedule edges to buf list [run_process_replay]

viz/serve.py
helpful for FUSE_ARANGE=1 dev.
=> VIZ show rendering errors

test/test_linearizer.py
prereq for moving SWIZZLE to kernel.
=> refactor test_linearizer correctness asserts

examples/mlperf/model_train.py
=> add RESET_STEP in bert to control reset

extra/models/inception.py
Implements the code for computing a FID score from a batch of Inception activations.
=> Compute FID Score

examples/mlperf/model_train.py
=> bert default CKPT to 0

tinygrad/dtype.py, tinygrad/engine/schedule.py, tinygrad/ops.py
prereq for UOps.BUFFER <-> Buffer interop.
=> add dtype.ptr() [pr]

tinygrad/engine/schedule.py
This makes interop between UOps.BUFFER and Buffer __init__ work, BUFFER is also ptr now.
=> Buffer arg from big graph [pr]

tinygrad/runtime/ops_python.py
=> CLANG fixed ops python [run_process_replay]

tinygrad/ops.py
Restores most of the perf loss from #6863
=> Restore fast path for matching new_src in rewrite [run_process_replay]

tinygrad/runtime/ops_nv.py
this should not have any impact on 4090, but remove limit on bigger gpus
=> nv set localmem sm count to max

test/unit/test_simplify_valid_idx.py, test/unit/test_uop_symbolic.py, tinygrad/renderer/cstyle.py
Refactoring `code_for_op` into pm, first pr
=> Static access for code_for_op [run_process_replay]

test/unit/test_uop_symbolic.py
no more test_symbolic for reference, so force expected output to be exact instead of a set
=> cleanup test_uop_symbolic.py

tinygrad/engine/lazy.py, tinygrad/tensor.py
=> remove DTypeLike from lazy

tinygrad/helpers.py, tinygrad/tensor.py
also cleaned up places where round_up was potentially called on symbolic
=> type annotation to round_up

examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_red/dev_beam.sh, examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_red/dev_run.sh, examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_red/run_and_time.sh
BEAM=4 slightly exceeded 30 minutes setup
=> use BEAM=3 for red box bert runs

examples/mlperf/model_train.py
getting 2 NaN for this, revert back to 2**10
=> back to 2**10 for bert loss scaler

test/test_nn.py, tinygrad/nn/__init__.py
https://github.com/tinygrad/tinygrad/issues/6910
output shape should be input_shape + (embed_dim,) and the sum reduction should be in the vocab dimension
=> fix embedding shape

examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_green/dev_beam.sh, examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_green/dev_run.sh, examples/mlperf/training_submission_v4.1/tinycorp/benchmarks/bert/implementations/tinybox_green/run_and_time.sh
=> limit beam param for bert on green

examples/mlperf/model_train.py
got two very close run, adding more steps for buffer
=> 10% more TRAIN_STEPS for bert

test/test_viz.py, tinygrad/ops.py
=> track viz context even if rewrite errors [pr]

.github/workflows/test.yml, examples/beautiful_cifar.py, examples/beautiful_mnist_multigpu.py
Fixed types for `mypy examples/beautiful_*.py`
=> Fix mypy examples/beautiful_*.py

tinygrad/engine/schedule.py
[baseline](https://github.com/tinygrad/tinygrad/actions/runs/11277079847/job/31362393426#step:11): 860 ms
[master](https://github.com/tinygrad/tinygrad/actions/runs/11277278851/job/31363062866#step:11): 2280 ms
[this branch](https://github.com/tinygrad/tinygrad/actions/runs/11277622878/job/31364205640#step:11): ~860 ms
blocker: [flaky with multiprocessing](https://github.com/tinygrad/tinygrad/actions/runs/11277622878/job/31364205640#step:12:24)
=> reduce scheduler process replay overhead [pr]

.github/workflows/benchmark.yml, tinygrad/runtime/ops_qcom.py
=> correct kernargs alignment

tinygrad/engine/schedule.py
prep refactor for deleting the LazyBuffer dep in getting buffer idxs, needed for multi output ASSIGN still.
=> start changes from big graph

tinygrad/renderer/cstyle.py
process_replay has diff as casting is no longer fixed and is now a uop
=> refactor _make_hip_code_for_op into pm rules

tinygrad/engine/schedule.py
src_st is the first thing that'll go away.
=> prep uoping diff for big graph [pr]

test/test_ops.py, tinygrad/function.py
=> remove bitcast backward in function.py

test/test_linearizer_failures.py, tinygrad/ops.py
adds the wrongly simplified kernel in test_linearizer_failures #7019
=> remove arbitrary multiplication case

tinygrad/codegen/kernel.py
that assert for intermediate uops is handled in a much better way with `spec` and renderers being `PatternMatchers`.
=> verify_ast changes from lazy_pm [pr]

test/test_dtype.py, tinygrad/renderer/cstyle.py
=> rewrite max to use cmplt + where

tinygrad/engine/schedule.py
=> small st_fixup changes [pr]

.github/workflows/test.yml, test/external/fuzz_linearizer.py
and applied smaller FUZZ_MAX_SIZE. this is getting quite slow in CI
=> add timing to fuzz_linearizer

test/unit/test_uop_symbolic.py
enable more tests and remove dead tests
=> clean up test_uop_symbolic.py

test/unit/test_simplify_valid_idx.py, tinygrad/codegen/uopgraph.py
saved a whopping one mod in the conv backward kernel...
=> use validhack logic to rewrite buffer idx

.github/workflows/test.yml
ubuntu-latest points to 24.04 now, maybe it's this?
=> use ubuntu-22.04 in CI

extra/nv_gpu_driver/nv_ioctl.py, test/external/fuzz_linearizer.py
`VALIDATE_HCQ=1` flag when running with `NV=1`.
=> fuzz nv vs cuda

tinygrad/engine/schedule.py
then rsrc should just be VIEW.
=> cleanup view on reduce [pr]

tinygrad/ops.py, tinygrad/viz/serve.py
I think there's potential here to do some heatmap visualization with the end times, instead of a flat number list.
=> track et in viz [pr]

tinygrad/viz/index.html, tinygrad/viz/serve.py
=> viz print the sink tree as it's rewritten [pr]

tinygrad/dtype.py, tinygrad/helpers.py, tinygrad/runtime/ops_disk.py
No process replay because types aren't equal
=> beautiful mnist works on windows

test/external/fuzz_linearizer.py, tinygrad/engine/search.py
Need to clean up, but allows to run the same beam kernels on any platform validating hcq devs.
=> beam capture and replay in fuzz

tinygrad/codegen/uopgraph.py
will reuse this to simplify valid independent of idx
=> idx_given_valid -> uop_given_valid [pr]

tinygrad/codegen/kernel.py
legacy stuff from when eq and is on UOp were different.
=> get membufs with dedup [pr]

test/unit/test_uop_symbolic.py
already worked so just fixed the test
=> enable test_resnet_half

.github/workflows/test.yml, tinygrad/engine/schedule.py, tinygrad/tensor.py
it's annoying to maintain this while making progress on big graph.
we need to rethink what we wanna actually fuzz here too.
=> delete fuzz_schedule [pr]

test/external/fuzz_linearizer.py
already broken on master and needs fix. don't throw to not block other pr
=> don't throw in fuzz_linearizer

test/helpers.py, test/test_dtype.py, test/test_linearizer_failures.py, tinygrad/codegen/lowerer.py, tinygrad/codegen/uopgraph.py, tinygrad/dtype.py, tinygrad/ops.py, tinygrad/shape/view.py
fixed test_failure_52 and resnet. need to understand this better
=> bring back pyint

tinygrad/runtime/ops_cuda.py
=> cuda correct pointer type

tinygrad/runtime/ops_python.py, tinygrad/tensor.py
=> fix import of truncate

test/helpers.py, test/test_dtype.py, test/test_linearizer_failures.py, test/test_uops.py, tinygrad/codegen/lowerer.py, tinygrad/codegen/uopgraph.py, tinygrad/dtype.py, tinygrad/ops.py, tinygrad/shape/view.py
also remove truncate in const folding
=> No pyint again

test/test_schedule.py, test/test_viz.py, tinygrad/codegen/kernel.py, tinygrad/engine/schedule.py, tinygrad/ops.py, tinygrad/viz/serve.py
groups calls to a single create_schedule:
very useful for big graph.
=> track_rewrites by function call [pr]

tinygrad/runtime/ops_nv.py
=> nv min regs count is 16

tinygrad/engine/schedule.py
big graph needs this to append the bufs.
=> keep srcs in all ops

tinygrad/engine/schedule.py
process replayable part of #7149 - prescheduled will be beautiful once this is done.
=> group stores by buffer uops [pr]

test/unit/test_disk_tensor.py, tinygrad/nn/state.py
=> GGUF Cleanup - raise if type is not supported

tinygrad/nn/state.py
tiny reordering and variable name changes
=> ggml_data_to_tensor touchups

docs/tensor/creation.md, tinygrad/nn/datasets.py, tinygrad/tensor.py
Closes #7182 
Optional for now, should remove fetch from `__init__.py`
=> Tensor.from_url API [pr]

tinygrad/engine/lazy.py, tinygrad/helpers.py
prereq for starting the schedule_cache spec. https://github.com/tinygrad/tinygrad/issues/6784
=> LAZYCACHE to context var [pr]

test/unit/test_shapetracker.py
currently real_strides returns all None, possible to get these with improved real_strides
=> failed test cases for 3+ views shapetracker strides

tinygrad/shape/shapetracker.py
only graph_rewrite once on idx (sholuld be idempotent), and always rewrite valid. will co-rewrite idx and valid next
=> minor tweak to real_strides [pr]

tinygrad/engine/schedule.py
This is where big graph starts, then it can move up fuse and group with graph_rewrite.
=> split to get_realizes [pr]

extra/nv_gpu_driver/nv_ioctl.py, tinygrad/runtime/ops_nv.py
=> nv fix shared_memory_size

tinygrad/engine/schedule.py
I'll keep BFS in milestone 2, maybe we'll move to DFS in milestone 3 or 5 depending on the speed diff.
=> bfs refactors from the big graph branch [pr]

test/test_tiny.py
A test suite to run with 0 deps
=> add some tiny tests that should pass everywhere [pr]

tinygrad/ops.py
This reverts commit b56fab54ea7514c4e4719aa103d7c19c44575d70.
=> Revert "some rules to simplify max (#7258)"

.github/workflows/benchmark.yml
also added a 15 minutes total timeout, this cannot grow indefinitely
=> RUN_PROCESS_REPLAY=0 on llama 70B and resnet training

.github/workflows/benchmark.yml
having llama3 4gpu and 6gpu should be good enough
=> disable llama 1 4gpu and 6gpu benchmark

test/test_uop_graph.py, tinygrad/ops.py
=> instant uop rules [pr]

tinygrad/engine/schedule.py
This reverts commit b805711f868565eb21e6f120a6324e79eb27fbc6.
=> Revert "move anything that isn't bfs [pr] (#7273)"

tinygrad/codegen/transcendental.py
simplified polyN and some redundant line cleanups
=> transcendental cleanups

test/unit/test_simplify_valid_idx.py
=> remove custom render in test_simplify_valid_idx

tinygrad/codegen/transcendental.py
from https://en.wikipedia.org/wiki/Exponent_bias, 15, 127, 1023 are bias
=> update exponent_bias in transcendental

test/test_linearizer_failures.py, test/unit/test_simplify_valid_idx.py, tinygrad/codegen/uopgraph.py
fixed test_failure_55. will reenable it later after fixing the bug
=> disable simplify_valid

test/unit/test_simplify_valid_idx.py, tinygrad/codegen/uopgraph.py, tinygrad/ops.py
the simplex should compare with valid bound, not its vmin
=> fix simplify_valid

test/test_device_behavior.py, test/test_setitem.py
A simple test for #7161 
~~Interestingly it fails LLVM and not CLANG in CI (in constrast to running it locally).~~ It also fails on LLVM locally.
=> Failing test: different behavior on different devices

examples/llama3.py
false positive if download_model and model are not provided
=> fix llama3 download_model assert

tinygrad/codegen/kernel.py
similar to function name, print rendered str instead of raw UOp
=> use UOp.render in colored_shape

tinygrad/engine/fuse.py, tinygrad/engine/schedule.py
gives everything a BUFFER, part one of #7293.
=> late buffer uops [pr]

test/unit/test_transcendental_helpers.py, tinygrad/codegen/transcendental.py
added a test to run UOps with const inputs. seems to have issue with both payne_hanek_reduction and cody_waite_reduction
=> unit test transcendental helpers

test/test_ops.py, tinygrad/codegen/transcendental.py
also added test for exp and log of nan and inf
=> tiny cleanup to transcendental xexp2

docs/abstractions2.py, docs/abstractions3.py
fix typing and use tinygrad tqdm
=> touchup abstraction docs

tinygrad/viz/index.html
Makes it somewhat look like this: https://github.com/tinygrad/tinygrad/pull/7089#issuecomment-2423774823
https://github.com/user-attachments/assets/930e7d57-b84e-49db-8334-d5e6a1683306
Working on reducing more lines of code!
=> VIZ UI improvement: resizable and collapsible sidebars

tinygrad/engine/schedule.py
part one of #7293, towards schedule_cache.
=> split preschedule from ast rewrite [pr]

tinygrad/ops.py
does this impact anything? some inf is incorrect now
=> limit UOps.ALU min/max to non-float only

test/test_ops.py, tinygrad/codegen/transcendental.py
=> clean up nan handling in transcendental

tinygrad/tensor.py
=> clean up get_shape [pr]

tinygrad/viz/index.html
Makes it look somewhat like https://github.com/tinygrad/tinygrad/pull/7089#issuecomment-2415759841
https://github.com/user-attachments/assets/9f51271c-140a-47ac-8f6d-f0138897b2fe
=> VIZ UI improvement: autoscroll kernel list when using arrow buttons

test/test_tensor.py, tinygrad/engine/schedule.py
=> global UOp to Metadata mapping + inverse DEBUG=2 metadata order [pr]

tinygrad/nn/__init__.py, tinygrad/tensor.py
`self.padding: Union[int, List[int]]` was wrong
=> fix typing in Conv2d

tinygrad/helpers.py, tinygrad/tensor.py
=> clean up Tensor._reduce

test/unit/test_transcendental_helpers.py, tinygrad/codegen/transcendental.py, tinygrad/dtype.py
also added some unit tests for frexp
=> clean up transcendental frexp [pr]

tinygrad/codegen/transcendental.py
similar speed, less alu (151 v.s. 154 per sine) and simpler, the power of 2 thing should probably be done in polyN if needed
=> reuse polyN in trig_poly float64

test/test_dtype.py, tinygrad/dtype.py, tinygrad/ops.py, tinygrad/renderer/cstyle.py, tinygrad/viz/serve.py
CI passes but benchmark fails!
=> Restore vcount [pr]

test/test_dtype.py, tinygrad/dtype.py, tinygrad/ops.py, tinygrad/renderer/cstyle.py, tinygrad/viz/serve.py
Reverts tinygrad/tinygrad#7390
=> Revert "Restore vcount [pr]"

test/test_dtype.py, test/test_hcq.py, tinygrad/dtype.py, tinygrad/ops.py, tinygrad/renderer/cstyle.py, tinygrad/viz/serve.py
Reverts tinygrad/tinygrad#7392
=> vcount + cleanups

tinygrad/engine/schedule.py
=> finally big graph

test/helpers.py, test/unit/test_helpers.py, test/unit/test_transcendental_helpers.py, tinygrad/codegen/transcendental.py, tinygrad/helpers.py
also move `eval_uop` to `test.helpers`
=> move `polyN` to helper [pr]

test/test_uop_graph.py, tinygrad/codegen/uopgraph.py, tinygrad/ops.py
Reverts tinygrad/tinygrad#7403
=> Revert "move up migrate + new gated fold"

.github/workflows/test.yml, test/test_uop_graph.py, tinygrad/codegen/uopgraph.py, tinygrad/ops.py
This reverts commit ea5654a9bca9f94cc90d5ac2bf1e483185735a06.
=> Revert "Revert "move up migrate + new gated fold (#7403)" (#7406)"

tinygrad/engine/schedule.py
I don't want schedule_cache miss because metadata is different.
=> delete metadata from schedule ctx [pr]

docs/tensor/elementwise.md, extra/models/bert.py, extra/onnx_ops.py, test/test_ops.py, tinygrad/tensor.py
the same one used in onnx and the one in bert.
test training bert in https://wandb.ai/chenyuxyz/MLPerf-BERT/runs/v4370gnc/overview
=> Tensor.erf

test/unit/test_transcendental_helpers.py, tinygrad/codegen/transcendental.py
added unit tests and updated the comment. it's rounding away from 0 for negatives
=> clean up transcendental.rintk [pr]
