tinygrad/tinygrad

test/test_viz.py, tinygrad/codegen/uopgraph.py, tinygrad/engine/schedule.py, tinygrad/ops.py, tinygrad/renderer/cstyle.py
It allows mixing and matching of ctx rules and non ctx rules
=> enforce ctx is called ctx [pr]

test/test_uop_graph.py, tinygrad/codegen/uopgraph.py, tinygrad/renderer/ptx.py
Reverts tinygrad/tinygrad#7431
=> Revert "improve full_graph_rewrite matchers for speed"

tinygrad/codegen/transcendental.py
denormal_map still looks wrong but a lot cleaner
=> cleanup xlog2 and remove unneeded functions

test/test_dtype_alu.py, tinygrad/codegen/transcendental.py
formula has 2X error with denormal floats
=> cast to float32 for float16 xlog2

tinygrad/codegen/transcendental.py
following the notations in the paper closer
=> more xlog2 cleanups

test/unit/test_transcendental_helpers.py, tinygrad/codegen/transcendental.py
=> update payne_hanek_reduction [pr]

tinygrad/engine/jit.py
removed an unnecessary cast and reordered a bit
=> clean up _prepare_jit_inputs [pr]

tinygrad/device.py
use is_allocated helper in Buffer
=> s/hasattr(self, '_buf')/self.is_allocated() [pr]

tinygrad/engine/fuse.py, tinygrad/engine/schedule.py
lines moving from fuse.py to UPats.
=> realize meta ops from graph_rewrite [pr]

tinygrad/codegen/kernel.py
probably will rewrite it later as reshape and permute function on Kernel, but for now it's shorter with better types
=> clean up reshape_and_permute

test/test_setitem.py
it was flaky, not broken broken
=> disable test_setitem_inplace_operator again

tinygrad/engine/fuse.py
These will move to graph_rewrite last. Until then it needs to at least cleanup the graph rewrite.
=> clean schedule ctx after fusing arange/conv_bw [pr]

test/unit/test_tqdm.py
time.sleep masked two issues:
(1) iters_per_sec might have unitscale in it, and calling `float` on it fails (2) default rate is too low to ensure the output matches, it might skip updating
=> fix tqdm tests

test/unit/test_tqdm.py, tinygrad/helpers.py
reduce parentheses and fuzz more tests now there's no sleep
=> tweak tqdm

extra/mcts_search.py
fixed
```
File "numpy/random/mtrand.pyx", line 971, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN
```
when all ucb_explored_children are big negative numbers result in all NaN probabilities
=> safe softmax trick in MCTS ucb_explored_children

test/test_pickle.py, test/test_uop_graph.py, test/test_uops.py, test/test_viz.py, test/unit/test_pattern_matcher.py, tinygrad/codegen/lowerer.py, tinygrad/codegen/uopgraph.py, tinygrad/engine/schedule.py, tinygrad/ops.py, tinygrad/renderer/cstyle.py, tinygrad/renderer/ptx.py, tinygrad/viz/serve.py
This reverts commit 400011a8c17c296459ee8b5391485c789a992dbb.
=> Revert "s/UPat/Pat (#7506)" [pr]

test/helpers.py, test/test_renderer_failures.py, test/test_uop_graph.py, test/test_uops.py, test/unit/test_simplify_valid_idx.py, test/unit/test_uop_symbolic.py, tinygrad/codegen/lowerer.py, tinygrad/codegen/uopgraph.py
Can someone finish fixing up the tests for this?
=> idx_load_store in lowerer [pr]

tinygrad/codegen/uopgraph.py, tinygrad/ops.py
Simpler, and a couple percent faster.
=> only match with op, not arg [pr]

tinygrad/viz/serve.py
hard to find STORE in the middle of a bunch of VIEWs
REDUCE_AXIS was hard to spot.
=> fix viz colors

extra/optimization/helpers.py
it has > 12000 rows now, but it depends on the backend that generates these so setting a lower but meaningful threshold
=> check `datasets/sops.gz` size to be > 5000

test/test_jit.py, test/test_schedule.py
=> skip test_jit_batch_split if JIT >= 2

.github/workflows/test.yml, extra/optimization/helpers.py, extra/optimization/test_helpers.py
filter based on "DEFINE_VAR" instead of "Variable". also added a unit test to make sure dataset includes image and variable kernels
=> fix load_worlds filter_novariable

tinygrad/engine/fuse.py, tinygrad/engine/schedule.py
I'm creating a Kernel.linearize like API for schedule with 3 functions: A "lowerer", a full graph_rewrite and a "linearize / toposort".
Cleaning up the ScheduleContext is a prereq for this.
=> create realizes later [pr]

test/unit/test_shapetracker.py, tinygrad/shape/shapetracker.py
simplified idx allows deriving more strides
=> uop_given_valid in real_strides

tinygrad/helpers.py
reclaims the db space after DROP TABLE
=> call VACUUM in diskcache_clear

test/unit/test_shapetracker.py, tinygrad/shape/shapetracker.py
improved one more real_strides. after finishing the last one will think about always applying these in to_indexed_uops
=> simplify_valid in real_strides

test/external/external_benchmark_hcopt.py
intersting that on m1 max hcopt wins BEAM 2 about 20% of the time
=> script to compare kernel opt with BEAM

test/test_linearizer.py, tinygrad/ops.py, tinygrad/renderer/llvmir.py, tinygrad/runtime/ops_llvm.py
Have to remove the alloca thing
=> replace llvm with new llvm

test/test_schedule.py, tinygrad/engine/schedule.py
can it push past this point with swizzle?
=> test swizzle post permute

test/test_schedule.py, tinygrad/ops.py
so satisfying
https://github.com/user-attachments/assets/8ee2855f-a0f2-4a8b-a77c-721887ee6c43
starting point for https://github.com/tinygrad/tinygrad/pull/7625
=> recursive swizzle with just graph_rewrite

tinygrad/engine/schedule.py, tinygrad/ops.py
I think this is a few UPats away from just relying on merge_views. st_fixup is terrible.
=> swizzle parents with graph rewrite

.github/workflows/benchmark.yml, test/external/speed_v_theoretical.py
draft to test on tinybox too, also need to figure out why subsequent runs became slower.
=> beam benchmark tests

.github/workflows/benchmark.yml
runs v4.1 bert setup.
```
rocm-smi --setprofile compute
rocm-smi --setmclk 3
rocm-smi --setperflevel high
```
=> setup perflevel in red CI

test/external/speed_v_theoretical.py
better amd after set compute profile
=> update speed_v_theoretical numbers

docs/tensor/creation.md, test/test_ops.py, tinygrad/tensor.py
was debating whether or not to add this since there is no actual linspace op in onnx but maybe onnx.AffineGrid can use it?
but then I saw https://x.com/spikedoanz/status/1855017414909739073/photo/1
=> add Tensor.linspace

test/test_ops.py, test/test_randomness.py, tinygrad/tensor.py
also fixed an assert when passing str dtype to randint
=> Tensor.linspace raises for dtype.bool

test/external/speed_v_theoretical.py
getting ~300GB/s if we just count the memory of inputs and output
=> add gemv to speed_v_theoretical

test/external/speed_v_theoretical.py
this made green gemv 20% faster... but why?
=> use randn in speed_v_theoretical instead of rand

tinygrad/renderer/cstyle.py
Just a reorder of the items for cleaner look
=> cleaner code_for_op order [pr]

tinygrad/tensor.py
=> more readable rand [pr]

examples/flux1.py
in addition to default downloading through fetch, add an arg to pass model path directly
=> flux set model path in args

extra/optimization/helpers.py, test/external/external_benchmark_multitensor_allreduce.py, test/test_multitensor.py, test/test_uops.py, test/unit/test_pattern_matcher.py, test/unit/test_verify_ast.py, tinygrad/engine/fuse.py, tinygrad/engine/lazy.py, tinygrad/engine/schedule.py, tinygrad/function.py, tinygrad/multi.py, tinygrad/ops.py
spec:
https://github.com/tinygrad/tinygrad/blob/4c7554ac081accb1fbb5dffa49227139727e452a/tinygrad/ops.py#L802
=> proposal: delete ReduceOps, only use REDUCE_AXIS

test/test_ops.py
Added two (currently failing) tests as discussed from Discord.
=> Add: failing tests for uint8 `min()`

test/test_multitensor.py, tinygrad/tensor.py
raise RuntimeError instead of dropping it silently
=> assert specifying device to rand_like a multi tensor

test/test_ops.py, tinygrad/tensor.py
Uses the flip idea from discord to fix the min function for unsigned ints
=> fix: Tensor min function for unsigned ints

test/test_ops.py, tinygrad/tensor.py
implemented with xor in tensor for now to not add another op. also used it in Tensor.min to fix dtype int on -2**31
=> Tensor.bitwise_not

test/test_linearizer_failures.py
from https://github.com/tinygrad/tinygrad/actions/runs/11821181386/job/32935299100#step:15:298
=> add test_failure_56 and test_failure_57

tinygrad/tensor.py
=> Tensor.shrink arg cleanup

tinygrad/engine/lazy.py
I know lazy.py is just awaiting removal but it's a minor nit nonetheless
=> Minor cleanup in lazy.py (Union[Ops,Ops] -> Ops) [pr]

test/test_compile_failures.py, test/test_const_folding.py, test/unit/test_shapetracker_math.py
should mark the ones that are expected to work with expectedFailure, and delete and ones that are not expected to work
=> enable a few tests that work now

extra/debug_sd_speed.py
run with `PYTHONPATH=. JIT=1 PARALLEL=0 BEAM=2 python extra/debug_sd_speed.py`
commit `4444e6d` (23ms)
master (29ms)
=> example script to show BasicTransformerBlock speed regression

test/test_ops.py, tinygrad/tensor.py
padding inf messed output dtype
=> fix max_pool2d for int tensor with padding

test/test_ops.py, tinygrad/tensor.py
more docs (similar to numpy) and removed many confusing  `-min(n2, 2)`
=> clean up Tensor.dot

tinygrad/tensor.py
flatten instead of double for loop comprehension
=> Tensor.repeat cleanup

tinygrad/tensor.py
=> _resolve_dim cleanup

tinygrad/engine/schedule.py
=> reverse map buf_uops [pr]

tinygrad/tensor.py
dim range checking is already done in `_resolve_dim`, existing tests cover these pretty well
=> simpler Tensor._reduce

test/test_ops.py, tinygrad/tensor.py
=> fix passing acc_dtype="" to Tensor.prod should fail

tinygrad/tensor.py
=> consmetic change to Tensor._pool

tinygrad/tensor.py
removed some dead conditions and add types. still reads more complicated than needed
=> minor Tensor.einsum cleanup

tinygrad/tensor.py
and reordered check lazy devices part
=> reorder `Tensor.__init__` to match type

tinygrad/engine/schedule.py
includes some https://github.com/tinygrad/tinygrad/pull/7764 prereqs.
=> delete buffer tracking from ScheduleContext [pr]

test/test_nn.py
current behavior is weird... when model is sharded and state_dict is not, load shards the state_dict and model shard axis does not change. but if model and state_dict are sharded differently, model shard axis becomes the state_dict axis after load.
it should either always use model shard axis or always use state_dict shard
=> load_state_dict test cases when model and data shard differently

test/external/process_replay/process_replay.py, tinygrad/engine/schedule.py
reverts #7782's change, very dumb on my part sorry.
=> hotfix: ctx doesn't impact process replay [pr]

test/test_setitem.py
minimal failure test case for 
#7739
=> add failure test for setitem bug

test/external/speed_v_theoretical.py
=> lower vs_theoretical conv tflops threshold for nv

tinygrad/engine/schedule.py
doing this in the toposort feels way too late, all the buffers are DEFINE_GLOBAL ptrs already at that point.
=> early mark uops as realized [pr]

test/test_schedule.py, tinygrad/engine/schedule.py, tinygrad/ops.py
process replayable refactor part of #7826's diff.
=> add UOp.const_with_shape [pr]

.github/workflows/benchmark.yml
and keep the non-fp16 one in mac
=> default run stable diffusion benchmark with fp16

tinygrad/engine/schedule.py
new axis are the permuted to end ones
=> simpler swizzle_r new_axis [pr]

tinygrad/codegen/lowerer.py, tinygrad/shape/view.py
=> variable_to_uop -> sint_to_uop [pr]

tinygrad/codegen/lowerer.py, tinygrad/ops.py, tinygrad/shape/view.py
both sint and uop are in ops.py
=> move sint_to_uop from view.py to ops.py [pr]

tinygrad/codegen/lowerer.py
=> simplify group_for_reduces in get_index [pr]

docs/tensor/ops.md, extra/models/llama.py, test/test_arange.py, test/test_ops.py, tinygrad/ops.py, tinygrad/tensor.py
generalized the existing cumsum and take Ops.MAX in addition to Ops.ADD
=> Tensor.cummax

tinygrad/multi.py, tinygrad/nn/__init__.py, tinygrad/nn/state.py
Contains the least controversial changes from #7846.
=> prepare mypy==1.13.0 bump

tinygrad/engine/schedule.py
another diff to help with diffing big graph between master and #7801.
=> don't change lazy state in schedule [pr]

.github/workflows/benchmark.yml
simple tests that run on real CUDA and HIP
=> test_tiny on real NV/CUDA/AMD/HIP

examples/llama.py
mac benchmark already runs quantize, this adds output validation
=> validate llama quantize output

tinygrad/codegen/kernel.py
@ignaciosica is this ever wrong? Like all WMMA srcs should lead to a LOAD.
=> always swizzle load st in wmma [pr]

.github/workflows/test.yml
=> webgpu -n=auto

test/unit/test_uop_symbolic.py, tinygrad/ops.py
Curious if this will be faster/better, I just want to see the process replay on this
In theory this should lead to smaller intermediate calculations and it makes it more likely for the mod to be a power of 2
=> Factoring gcd out of mod

tinygrad/tensor.py
same example from torch, i think it's much more useful
=> update Tensor.scatter doc examples

test/unit/test_uop_symbolic.py
same alu count but better bounds
=> add TODO case to test_mod_congruence

examples/mlperf/model_train.py
issue in benchmark dashboard logging, revert back to tqdm tqdm for now
=> use tqdm tqdm in mlperf training

extra/models/llama.py
do the cast based on input in first forward call instead
=> remove dtype from llama precompute_freqs_cis

test/test_linearizer.py, test/test_uops.py, tinygrad/ops.py, tinygrad/viz/serve.py
Reverts tinygrad/tinygrad#7931
=> Revert "add block uops and modify tests (without IF/RANGE flip)"

tinygrad/ops.py
=> BLOCK ops in Ops

tinygrad/ops.py, tinygrad/viz/serve.py
this is the rest of #7919 prereqs for new block lin
=> flip IF and RANGE order

tinygrad/codegen/kernel.py
Unifying view merge
I can't believe how small the diff ended up. The st needs to start contiguous so that the view addition doesn't get messed up. 
I believe it is still worth removing expanded_shape and cleaning up other things from tc as well (going to keep working on those).
=> true tc swizzle [pr]

test/unit/test_uop_symbolic.py
Added some test cases for div mod folding which are currently not simplifying
=> Div mod recombine test for issue

test/models/test_real_world.py
the test was useless because it was looking at the jit graph counts. wrap with JIT=2 for now.
if it's stable we could consider making kernel count strict, which helps change like #7940
=> update kernel counts in test_real_world

test/test_schedule.py, tinygrad/engine/schedule.py, tinygrad/ops.py
somehow test_speed_v_theoretical is red.
=> Revert "schedule sink folding with graph_rewrite [pr] (#7963)"

tinygrad/engine/lazy.py, tinygrad/engine/schedule.py
Optional[ShapeTracker] is a much easier type to work with than a tuple.
=> make ASSIGN arg optional

tinygrad/engine/schedule.py, tinygrad/ops.py
fine to swizzle store within kernel boundaries, you're right @ignaciosica ASSIGN is already kinda doing it.
=> swizzle store [pr]

tinygrad/helpers.py
reordered a bit to minimize the stuff in the with blocks
test manually with TestFetch and `DISABLE_HTTP_CACHE=1` on some examples
=> fetch cleanup

tinygrad/engine/lazy.py, tinygrad/engine/schedule.py
this but upats https://github.com/tinygrad/tinygrad/pull/2556.
eg. test_zero_size rewrites to Ops.NOOP
=> late folding size 0 ops

tinygrad/helpers.py
less lines for ceildiv and partition, and removed one # noqa: E501
=> small helpers cleanups

test/test_uop_graph.py, test/test_uops.py, tinygrad/codegen/uopgraph.py, tinygrad/renderer/cstyle.py, tinygrad/renderer/llvmir.py, tinygrad/renderer/ptx.py
work in progress, It seems like most of the work are already done, maybe just require some cleaning up and more tests
=> Remove gated store, put rewrite to uopgraph [pr]

tinygrad/runtime/ops_amd.py
was incorrect before. rdna 2, from my testing, fully works with this
=> fix: private segment sgpr on gfx103x

docs/tensor/elementwise.md, extra/onnx_ops.py, test/test_ops.py, tinygrad/tensor.py
was prepping an onnx_ops clean up and found a missed op from onnx_ops
=> add SELU to Tensor

test/external/external_debug_metal_sd_conv.py
this and other similar `conv2d + add` kernels contributed to most of the speed regression
=> script to run regressed sd conv on metal

test/external/fuzz_uops.py, test/test_uops.py, tinygrad/codegen/kernel.py, tinygrad/ops.py
757 ms -> 710 ms
```
light@blak:~/tinygrad$ python3 test/external/external_benchmark_schedule.py
***** model tensor in     19.95 ms
***** model schedule in   59.47 ms
***** model opts(31) in  144.02 ms
***** model lower in      12.10 ms
***** model rewrite in   358.41 ms
***** model linearize in 120.16 ms
19675
all 715.89 ms
light@blak:~/tinygrad$ python3 test/external/external_benchmark_schedule.py
***** model tensor in     19.11 ms
***** model schedule in   57.05 ms
***** model opts(31) in  142.60 ms
***** model lower in      11.98 ms
***** model rewrite in   357.81 ms
***** model linearize in 119.30 ms
19675
all 709.55 ms
light@blak:~/tinygrad$ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
light@blak:~/tinygrad$ python3 …
```
=> minor uop speedups [pr]

tinygrad/renderer/wgsl.py
use more UPat syntatic sugar and remove unneeded rules
=> clean up wgsl_matcher [pr]

tinygrad/renderer/ptx.py
always compare with dtypes instead of name string
=> minor tweak in ptx asm_for_op [pr]

tinygrad/nn/__init__.py
=> minor nn cleanups

tinygrad/ops.py
=> silent bug in op.st [pr]

test/test_uop_graph.py, test/test_uops.py, test/unit/test_graph_rewrite.py, test/unit/test_simplify_valid_idx.py, test/unit/test_uop_symbolic.py, test/unit/test_uop_vmin_vmax.py, tinygrad/codegen/transcendental.py, tinygrad/codegen/uopgraph.py, tinygrad/renderer/ptx.py, tinygrad/shape/view.py
just use dunder methods, eventually will remove those from ops
=> update uop and tests to not use lt/gt/le/ge [pr]

tinygrad/function.py
pr does not test this, but it's the same
=> update function to not use gt/lt [pr]

tinygrad/ops.py, tinygrad/tensor.py
=> remove lt/gt/le/ge from SimpleMathTrait [pr]

tinygrad/codegen/linearize.py, tinygrad/ops.py
NOTE: can also merge blockfork siblings
=> clean up rewrite logic + merge siblings

tinygrad/engine/schedule.py, tinygrad/ops.py
uval is still not well thought through and needs to be fixed pre big graph.
=> simple contiguous_while_contiguous prereqs [pr]

test/external/speed_v_theoretical.py
tiny7 is still slower https://github.com/tinygrad/tinygrad/actions/runs/12166149038/job/33931736130#step:8:209
=> lower v_theoretical gemv on red

test/unit/test_uop_symbolic.py, tinygrad/ops.py
Fold (x//c+a)//d -> (x+a*c)//(c*d)
Fix the point from #7996
=> Fold nested div with const

tinygrad/engine/schedule.py
walrus, and if x are the same, prod(x) must be the same
=> minor push_swizzle_down_through_elementwise cleanup [pr]

tinygrad/ops.py
that's the only use case, so no need for indirection
=> hook_overflow -> safe_exp2 [pr]

extra/onnx_ops.py, tinygrad/tensor.py
my scatter got heat from twitter
😔😔😔😔😔😔😔😔😔😔😔😔😔😔😔
does adding a `_arange_select` function help readability?
=> add _one_hot_along_dim helper for Tensor.arange masking

tinygrad/ops.py
start/end should not be float or bool
=> fix typing of UOp.range [pr]

tinygrad/shape/view.py
don't need canonicalize_st because we always merge 1 in `_merge_dims`
=> reshape mask cleanups [pr]

tinygrad/shape/view.py, tinygrad/tensor.py
same condition (check if old == new or old == 1) in tensor and view. also renamed _pad_left to _align_left because it's not really a pad
=> unify expand conditions [pr]

test/test_tensor.py, tinygrad/shape/view.py
removed a resolve, and remove special case for 0 size assert since it's covered by generic size check
=> clean up reshape size check [pr]

extra/onnx.py, test/external/external_test_onnx_backend.py
Reverts tinygrad/tinygrad#8069
=> Revert "combine get inputs and type_parse function in onnx"

test/external/external_test_onnx_backend.py, test/test_ops.py, tinygrad/tensor.py
int to power of int should return int etc, it hints that we would like to have Ops.POW
=> fix return type of Tensor.pow

extra/onnx_ops.py, test/external/external_test_onnx_backend.py
=> onnx Bitwise ops

.github/workflows/test.yml
mostly for speed, this is just making sure the script runs
=> don't FUZZ_ALL_ACTIONS in fuzz_linearizer.py

tinygrad/runtime/ops_amd.py, tinygrad/runtime/ops_nv.py, tinygrad/runtime/ops_qcom.py, tinygrad/runtime/support/hcq.py
=> hcq buffer is a class

test/test_ops.py
running test_ops with global NOOPT=1 should stay green.
=> set NOOPT in test_avg_pool3d_failure

test/test_ops.py, tinygrad/tensor.py
similar to `min`, use `~` instead of `-` so it won't go out of bound for signed int
=> fix argmin on int32 min

test/test_ops.py, tinygrad/engine/lazy.py, tinygrad/engine/schedule.py, tinygrad/ops.py
These are the correctness essential upats for the delete_lazy branch.
=> scheduler ops_folding from delete_lazy

test/test_ops.py, tinygrad/tensor.py
=> fix pow of int to negative const int

test/imported/test_indexing.py, test/test_lazybuffer.py, tinygrad/engine/lazy.py
last one on the delete_lazy refactors. The rest of the diff should be all signal and no noise.
=> small changes to refine the delete_lazy diff

tinygrad/engine/lazy.py, tinygrad/engine/realize.py
from toonygrad, none of the abstractions above realize need to know this arg so it can happen late.
new big graph
=> derive COPY nbytes late in realize [pr]

test/test_ops.py, tinygrad/tensor.py
use invert instead of just neg. consolidate min, argmin, and minimum
also update maximum to not apply the mid point for int
=> fix Tensor.minimum for int

test/external/speed_v_theoretical.py
getting 119 sometimes, so lowered to 115
=> lower test_gemm_4096 expectation on green

.github/workflows/benchmark.yml
more representative as it hits tensor cores on tinyboxes
=> use HALF in cifar wino benchmarks

tinygrad/engine/schedule.py
=> late scheduler context builder [pr]

tinygrad/codegen/kernel.py
=> remove bufs_for_tensor_cores [pr]

examples/webgpu/stable_diffusion/index.html
support sending prompt while focused on the input via Enter
also showing visually that model is running via rendering different title text
<details>
<summary>before/after demo</summary>
https://github.com/user-attachments/assets/5c9b12ee-2b88-4c51-b4ab-fe6613e908c8
</details>
=> stable diffusion UI - convenient send via Enter

test/unit/test_uop_symbolic.py
=> clean up test_uop_symbolic [pr]

.github/workflows/test.yml, examples/openpilot/compile3.py
added as exact number check now as it's not clear if more/less than allowed is any better
=> add ALLOWED_READ_IMAGE=2131 to openpilot

tinygrad/engine/search.py
=> delete CAPTURE_BEAM, this should use PR or VIZ infrastructure instead [pr]

tinygrad/nn/state.py
=> tiny gguf_load cleanup [pr]

tinygrad/engine/realize.py, tinygrad/tensor.py
=> remove duplicated UOp in Tensor init types [pr]

setup.py, tinygrad/runtime/ops_webgpu.py
The timeout issue has been resolved in `0.19.3`.
=> Bump back wgpu to latest [pr]

test/unit/test_view.py, tinygrad/shape/view.py
looking for better ways to write this. first adding some tests
=> unit test merge_dim [pr]

tinygrad/ops.py
=> flatten buffer args, delete dtype [pr]

tinygrad/engine/schedule.py
this+#8206 and there's no more "lazy" in schedule.
=> s/lazybufs/tensor_uops [pr]

.github/workflows/benchmark.yml
Can someone trigger benchmark job?
=> add real AMX tests to benchmark

test/unit/test_view.py, tinygrad/shape/view.py
something feels wrong... contructing a counter example next
=> reorder and comments to reshape [pr]

test/imported/test_indexing.py, test/test_schedule.py, tinygrad/engine/schedule.py, tinygrad/ops.py, tinygrad/shape/shapetracker.py
Reverts tinygrad/tinygrad#8222
=> Revert "use movement ops [pr]"

test/external/speed_v_theoretical.py
=> lower test_conv_3x3_256_32_32_256_256

test/imported/test_indexing.py, test/test_schedule.py, tinygrad/engine/schedule.py, tinygrad/ops.py, tinygrad/shape/shapetracker.py
Reverts tinygrad/tinygrad#8224
=> retry: use movement ops [pr]

test/unit/test_view.py, tinygrad/shape/view.py
the third return value is only used in reshape
=> move some ifs from merge_dims to reshape [pr]

docs/abstractions3.py, docs/tensor/properties.md, examples/beautiful_mnist.py, test/unit/test_gradient.py, tinygrad/gradient.py, tinygrad/nn/optim.py, tinygrad/tensor.py
Reverts tinygrad/tinygrad#8231
=> Revert "switch beautiful_mnist to use new optimizer [pr]"

test/test_ops.py, tinygrad/codegen/uopgraph.py
quite brittle... the problem is it has 3 terms and mul might have bad order
=> fix some sigmoid extreme

test/test_ops.py
it should also work if implemented differently
=> failed test case for stable sigmoid

tinygrad/shape/view.py
not needed, likely a hack to work around pre-resolve?
=> remove an if in reshape [pr]

.github/workflows/test.yml
need this make CI green and merge the debufferization diffs.
=> hotfix: use ubuntu-22.04 ci from 8249

tinygrad/engine/schedule.py, tinygrad/ops.py
towards deleting early bufferize.
=> unwrap existing buffer from assign src [pr]

docs/abstractions2.py, test/test_tensor.py, tinygrad/engine/schedule.py, tinygrad/ops.py, tinygrad/tensor.py
=> replace lazy srcs with the new uop api [pr]

tinygrad/engine/schedule.py
how much of a 1:1 map can this be?
37% of to_uop is filler already, the existence of another path for meta ops is unjustified after delete_lazy.
With some better spec choices in meta ops we can get it to 1:1 match.
=> simplify to_uop more, toward deleting early bufferize [pr]

tinygrad/engine/schedule.py
then, `if len(stores:=...)` is unjustified, this should be handeled better. Same problems as `TestRealizeMeansRealize` #8235.
what happens if the tensor_uop in the edges folds to just a CONST?
pre-delete_lazy lazy and current master both defer CONST realizing until it's forced to realize.
eg. TestOps.test_abs `[()]`
fold in the first schedule
realize in the second schedule, "just in time".
=> schedule_uop api refactor [pr]

test/unit/test_view.py
these have masks in self and masks in the merged views
=> more test examples to merge views [pr]

tinygrad/shape/view.py
naming / style / comments before logic change
=> minor changes to views add [pr]

test/unit/test_tensor_uop_representation.py
Reverts tinygrad/tinygrad#8288
=> Revert "TIP 3 as unittests [pr]"

test/test_hcq.py, test/test_profiler.py, test/test_viz.py, tinygrad/device.py, tinygrad/helpers.py, tinygrad/ops.py, tinygrad/runtime/graph/hcq.py, tinygrad/runtime/support/hcq.py, tinygrad/viz/index.html, tinygrad/viz/perfetto.html, tinygrad/viz/serve.py
=> viz profiler

tinygrad/shape/view.py
also more comments and type annotation
=> remove duplicated canonicalize mask in __unsafe_resize [pr]

tinygrad/shape/view.py
code path does not hit this, and we might want to assert if it ever hits
=> unused case where View adds invalid masked view [pr]

tinygrad/shape/view.py
=> redundant shape simplify in __unsafe_resize [pr]

test/unit/test_view.py
=> add failing tests for merge views

tinygrad/codegen/lowerer.py
Resolves `TODO: check has_valid in UPat, not here`
=> [pr] move has_valid into pm_lowerer

tinygrad/shape/view.py
removed usused mask check, and combined if blocks
=> minor cleanup to _reshape_mask [pr]

tinygrad/shape/view.py
formatting before logic change
=> minor change to _reshape_mask [pr]

tinygrad/shape/view.py
the only possible mask for it is either (0, 0) or (0, 1). so the logic is no-op
=> remove a leading 1 check in _reshape_mask [pr]

extra/onnx_ops.py, test/external/external_test_onnx_backend.py, test/test_ops.py, tinygrad/tensor.py
need to still ~verify correctness~ (wait still wrong) and check if there's a better implementation.
=> add GatherND and ScatterND to onnx ops

test/test_symbolic_shapetracker.py, tinygrad/shape/view.py
the view was not created through View.create, updated the test to show the expected behavior
=> update test_merge_view_recursion_err2 [pr]

tinygrad/tensor.py
Related to #8280
Maybe this should be a decorator? requires_grad should be injected at the end of any Tensor construction, not early.
=> fix (some) requires_grad [pr]

test/external/external_test_train_gpt2.py, test/external/fuzz_linearizer.py
also fixed run_linearizer with var_vals=None
=> isolate train_gpt2 slow kernels [pr]

tinygrad/codegen/kernel.py, tinygrad/codegen/uopgraph.py, tinygrad/helpers.py, tinygrad/multi.py, tinygrad/nn/__init__.py, tinygrad/renderer/cstyle.py, tinygrad/runtime/ops_python.py
Dict and DefaultDict and some imports
=> import and type cleanups [pr]

test/test_schedule.py, test/unit/test_tensor_uop_representation.py, tinygrad/engine/schedule.py, tinygrad/ops.py
Reverts tinygrad/tinygrad#8365
=> Revert "CONST(VIEW(DEVICE)) [pr]"

tinygrad/ops.py, tinygrad/shape/view.py, tinygrad/tensor.py
ran with `coverage` on test. not sure about if we still want max_var_const so just commented it out
=> remove untriggered/untested code [pr]

test/external/fuzz_linearizer.py, test/external/fuzz_shapetracker_math.py, test/unit/test_shapetracker_math.py, test/unit/test_simplify_valid_idx.py, test/unit/test_uop_symbolic.py, tinygrad/dtype.py, tinygrad/engine/realize.py, tinygrad/engine/search.py, tinygrad/ops.py
=> more typing cleanups [pr]

test/test_ops.py
was only tested in onnx, added to test_ops for completeness
=> add test for Tensor silu and swish

test/unit/test_view.py
these cases view the padded area of first view
=> test case view the padded area of a view

test/test_ops.py, tinygrad/ops.py, tinygrad/tensor.py
test more cases when either numerator and denominator is negative and has remainder or not
=> update idiv doc and test cases

examples/self_tokenize.py
can paste the whole tinygrad in gemini this way
=> optionally output to file in self_tokenize.py

tinygrad/codegen/kernel.py, tinygrad/codegen/linearize.py, tinygrad/device.py, tinygrad/dtype.py, tinygrad/renderer/llvmir.py, tinygrad/runtime/ops_amd.py, tinygrad/runtime/ops_nv.py, tinygrad/runtime/ops_qcom.py, tinygrad/runtime/support/hcq.py, tinygrad/tensor.py
many false positve... maybe due to tokenizer
=> typos found by gemini [pr]

test/test_schedule.py
This spec highlights the two failures blocking #8392. The fixes are unrelated to that diff.
I'll work on fixing the expectedFailures, then we can observe 8392 is green.
=> tensor uops symbolic folding spec [pr]

examples/self_tokenize.py
use comment for file name and join with newline instead of null byte when export to file
=> make self_tokenize output more like a python file

test/test_hcq.py, test/test_uops.py, tinygrad/ops.py, tinygrad/runtime/ops_amd.py
The case statement here in this diff is nice because we can just add BUFFER to the cases for contiguous ShapeTracker construction.
=> UOp shape spec and requirements from TIP 4

tinygrad/engine/realize.py
Refactoring this to a pattern matcher is a prereq for using existing UOps to compose "meta ops".
Then instead of `UPat(Ops.EMPTY)` we can have `VIEW(BUFFER(DEVICE)): EmptyOp` etc.
btw, I'm not happy that Runners need literal Buffers to construct, but this predates `Ops.DEVICE`, I can clean this up next.
Ideally, we want `si_lowerer` to take an AST (UOp), no context, and return a single Runner instance. The Runner abstraction does not need to know about Device Buffers, ExecItem can handle that.
=> refactor lower_schedule_item to pattern matchers [pr]

.github/workflows/test.yml, docs/abstractions2.py, docs/developer/runtime.md, setup.py, tinygrad/helpers.py, tinygrad/runtime/ops_clang.py, tinygrad/runtime/support/elf.py
Reverts tinygrad/tinygrad#8312
@uuuvn See benchmark failure
=> Revert "Clang JIT"

docs/tensor/movement.md, tinygrad/tensor.py
fixes small typo in rearrange docs https://github.com/tinygrad/tinygrad/blob/master/tinygrad/tensor.py#L1921 + add the method in the documentation
=> fix rearrange docs

docs/tensor/movement.md, tinygrad/tensor.py
also moved rearrange in tensor.py to high level movement
=> add Tensor.roll and Tensor.rearrange to doc

docs/tensor/elementwise.md, extra/onnx.py, test/external/external_test_onnx_backend.py, test/test_ops.py, test/unit/test_uop_vmin_vmax.py, tinygrad/function.py, tinygrad/ops.py, tinygrad/tensor.py
it's a python style mod. possibily can be cleaner with a floor div
relaxed the vmin for MOD slightly for cstyle negatives mod, it's more correct and might fix other bugs
=> Tensor.mod

test/unit/test_uop_vmin_vmax.py, tinygrad/ops.py
=> type annotation of resolve [pr]

tinygrad/tensor.py, tinygrad/viz/index.html
- fix annoying console logs
https://github.com/highlightjs/highlight.js/wiki/security#unescaped-html
`hljs.highlightElement` must target `<code/>` not `<pre/>`
=> [VIZ] fix hljs.highlightElement to correctly target <code/>

extra/onnx_ops.py, test/external/external_test_onnx_backend.py
Reverts tinygrad/tinygrad#8471
=> Revert "onnx pool ops clean up"

tinygrad/engine/schedule.py, tinygrad/ops.py
The arg on COPY doesn't need to exist now that we have Ops.DEVICE.
Had to change the UPat for "no double copy" because it was using the old COPY pattern. Now COPY.device actually returns the destination device.
before and after VIZ:
=> give copy a device: COPY(device, copyin)

docs/abstractions2.py, test/test_schedule.py, tinygrad/engine/schedule.py, tinygrad/ops.py, tinygrad/tensor.py
=> return becomes_map from the scheduler

tinygrad/runtime/ops_amd.py, tinygrad/runtime/support/am/amdev.py
* AM now also uses TRAP on sdma as (kernel and AMD) does that for fences.
=> am: minor missing parts

tinygrad/runtime/support/am/ip.py
AM PR: Ran 1 test in 3.769s
AM Master: Ran 1 test in 5.444s
=> am: tune all sleep timings to match kernel

.github/workflows/benchmark.yml, test/external/external_benchmark_multitensor_allreduce.py
because i didn't know how to use it...
=> fix create_schedule_with_vars usage in allreduce benchmark [pr]

test/external/external_benchmark_multitensor_allreduce.py
make `run` to able to run with ring only
=> update and clean up allreduce script [pr]

test/external/external_benchmark_multitensor_allreduce.py
time everything on tensor level and get time from GlobalCounters.time_sum_s
similar result to old script
```
Ring:
0.093871 seconds/iter
93.25 GFLOP/s
10.66 GB/s
Naive:
0.553733 seconds/iter
13.55 GFLOP/s
1.81 GB/s
```
=> simpler allreduce script [pr]

test/test_multitensor.py, tinygrad/tensor.py
=> remove custom splits in Tensor.shard [pr]

tinygrad/multi.py, tinygrad/tensor.py
without a custom bound, the bound is uniquely determined by shape and axis
=> remove bounds from MultiLazyBuffer.from_sharded [pr]

.github/workflows/benchmark.yml
gonna try small delay, can't repro this, but looks like that's the issue
=> ci: sleep a bit to let the driver unload the prev pid

tinygrad/runtime/ops_python.py
=> Rename `i` and `j` into `k` and `row`/`col` [pr]

test/external/external_test_datasets.py
Reverts tinygrad/tinygrad#8591
=> Revert "Faster KiTS19 dataset tests"

tinygrad/multi.py
determined by lbs shapes and axis
=> make MultiLazyBuffer.bounds a property [pr]

test/test_multitensor.py, tinygrad/multi.py, tinygrad/tensor.py
it's eqivalent to taking the lazydata from Tensor.split, then copy to devices
=> remove MultiLazyBuffer.from_sharded [pr]

.github/workflows/benchmark.yml
=> JITBEAM=2 for LLaMA-3 8B on 4 GPUs [pr]

tinygrad/engine/schedule.py, tinygrad/gradient.py, tinygrad/ops.py
Reverts tinygrad/tinygrad#8639
=> Revert "move subbuffer to a rewrite rule in the scheduler "

.github/workflows/benchmark.yml, .github/workflows/test.yml, docs/env_vars.md, test/test_linearizer.py, tinygrad/renderer/cstyle.py, tinygrad/renderer/ptx.py, tinygrad/runtime/ops_python.py
Walkthrough on tf32 tc (#8426)
Added tf32 flag only to correctness tests in benchmark (tensor core tests), I don't know if you want to add it to some real benchmarks as well
=> tf32 tc for nv and ptx

test/test_ops.py, test/test_schedule.py, tinygrad/tensor.py
matches torch, also fixed incorrect usage in tests
=> raise if attn_mask is set when is_causal=True in sdpa [pr]

test/test_schedule.py, tinygrad/tensor.py
built is_causal mask with ones_like and start with boolean, and reversed the mask -inf order
=> update mask in scaled_dot_product_attention

tinygrad/renderer/ptx.py
=> minor space alignment hotfix in ptx

test/test_schedule.py, test/unit/test_tensor_uop_representation.py, tinygrad/engine/schedule.py
=> Tensor UOps can become a buffer or const after scheduling

examples/mlperf/model_train.py
=> bert log global_norm in training step [pr]

examples/mlperf/helpers.py
=> envvar BERT_LAYERS [pr]

tinygrad/engine/schedule.py
This is zero folded with sym already.
https://github.com/tinygrad/tinygrad/blob/2dae467b75fa8dc74746adeca2050c09b6afb45c/tinygrad/engine/schedule.py#L365-L368
=> remove buffer size check in schedule item [pr]

examples/llama3.py
6.7tok/s with int8 JITBEAM=2 on m4 max
=> update llama3 70B to use R1

test/test_multitensor.py
new multi broke multi device dropout
=> failed test case for multi rand_like [pr]

.github/workflows/benchmark.yml
with `DISABLE_DROPOUT=1 BERT_LAYERS=2` for now
=> add bert to bechmark ci

test/test_multitensor.py, tinygrad/multi.py, tinygrad/ops.py
tuple is immutable. also updated test_rand_like_from_alu test
=> make UOp.multi real a tuple instead of list [pr]

tinygrad/runtime/ops_amd.py
Noticed that bind leads to hangs on resnet (bert looked fine when tested). Disabling it for now during investigation.
=> am disable bind

test/test_multitensor.py, tinygrad/multi.py, tinygrad/ops.py
chenyu, i still don't fully understand what real is? i need this to fix gradient
=> fix multi with no real srcs

tinygrad/runtime/support/am/amdev.py, tinygrad/runtime/support/am/ip.py
=> am: unset high clocks for sleep

tinygrad/runtime/support/am/amdev.py
Repro:
```
#!/usr/bin/env bash
while true; do
AM_RESET=1 AMD=1 python3 test/test_tiny.py TestTiny.test_plus
status=$?
if [ $status -ne 0 ]; then
exit 1
fi
AMD=1 python3 test/test_tiny.py TestTiny.test_plus
status=$?
if [ $status -ne 0 ]; then
exit 1
fi
done
```
=> am: fix hang

extra/models/llama.py, test/unit/test_disk_tensor.py, tinygrad/codegen/rewriter.py, tinygrad/renderer/llvmir.py, tinygrad/tensor.py
Reverts tinygrad/tinygrad#8720
=> Revert "move llvm_bf16_cast to renderer for CLANG and LLVM [pr]"

.github/workflows/test.yml
re-run the ci should hit the cache
=> fix windows ci cache

tinygrad/viz/index.html, tinygrad/viz/serve.py
```
VIZ=1 python3 examples/beautiful_mnist.py
```
can now return a response within a reasonable amount of time.
This diff enables work on the new (fast) graph renderer.
=> add pagination to viz [pr]

tinygrad/helpers.py
=> bump db version

tinygrad/engine/schedule.py
This UPat.any does not need to exist after #8811
=> simpler remove_movement_ops [pr]

test/external/speed_v_theoretical.py
=> lower green test_gemm_8192 tflops to 125 [pr]

test/test_nn.py, test/test_tensor.py, tinygrad/tensor.py
not used. gradient accumulation works directly
=> remove retain_graph in Tensor.backward [pr]

tinygrad/runtime/ops_amd.py
ugh, should have tested on amd
Reverts tinygrad/tinygrad#8836
=> Revert "am: queues allocated on gpus"

test/external/external_test_onnx_backend.py, test/test_ops.py, tinygrad/tensor.py
current implementation is not precise and blocking other simplification change
=> raise RuntimeError for int base pow

test/external/external_fuzz_hcq_signals.py
it looks fine now. will double check that queues built the way that each agent sees prev signal value before setting a new one.
=> hcq pci signal fuzzer

tinygrad/engine/schedule.py
This ScheduleContext can't stay as a global dict passed around everywhere. This diff removes its need for the becomes_map update.
There is a path to removing this global context completely with a few more refactors.
=> start simplifying the schedule context [pr]

test/test_const_folding.py, tinygrad/tensor.py
use %2 instead of cos to detect even numbers
=> simplify pow to not call cos

tinygrad/engine/multi.py
ALU/REDUCE_AXIS/RESHAPE/PERMUTE can change axis. prereq to move this logic to ops.py
=> factor out get_axis in multi [pr]

test/test_multitensor.py, tinygrad/engine/multi.py, tinygrad/ops.py
also updated tests so that axis is known prior to realize
=> move multi axis to property

tinygrad/codegen/rewriter.py, tinygrad/renderer/wgsl.py, tinygrad/spec.py
The unified diff is nice for this one, less tokens per line
https://github.com/tinygrad/tinygrad/pull/8887/files?diff=unified&w=0
=> replace UPat(name="x") with UPat.var("x") [pr]

tinygrad/tensor.py
=> pow cleanups

test/test_const_folding.py, test/test_multitensor.py, tinygrad/engine/schedule.py, tinygrad/ops.py
can use this to test the pr schedule diff thing, also would like to investigate where in multi is calling that contiguous
=> copy is already contiguous

tinygrad/engine/search.py
I think some benchmarks might have worsen based on this bug
=> hotfix bug in `get_kernel_actions` after `TC_SEARCH_OVER_SHAPE` was introduced

tinygrad/engine/schedule.py
This diff makes the PRELOAD deletion easier. Also, I am planning to move this to kernel.py, it's not a scheduler concern.
=> move assign ShapeTracker check to pattern matcher [pr]

test/test_search.py
adds regression test for #8904
=> add regression test: `test_get_kernel_actions_preserves_actions_state`

tinygrad/runtime/support/am/amdev.py
=> am: load fw based on versions

test/test_const_folding.py, test/test_schedule.py, tinygrad/ops.py, tinygrad/tensor.py
=> move more pow const to rewrite

test/unit/test_elf.py, tinygrad/runtime/support/elf.py
Please trigger benchmarks before merging to make sure there aren't any problems on non-mockgpu amd or nv.
=> Better errors when relocating against undefined symbol

tinygrad/dtype.py, tinygrad/renderer/llvmir.py
=> add float4 support to LLVM

test/external/external_benchmark_kernel_launch.py, test/test_speed_v_torch.py, tinygrad/engine/jit.py, tinygrad/ops.py, tinygrad/runtime/ops_metal.py, tinygrad/shape/shapetracker.py
Speed from 60 us to 10 us in LLVM
=> benchmark single kernel launch

test/external/external_benchmark_kernel_launch.py, tinygrad/engine/jit.py, tinygrad/runtime/graph/metal.py, tinygrad/runtime/ops_metal.py
Reverts tinygrad/tinygrad#8922
=> Revert "objc fast msg"

tinygrad/runtime/ops_metal.py
CPython doesn't make any guarantees about order in which globals like `msg` or `libobjc` are destroyed when the interpreter shuts down
https://github.com/tinygrad/tinygrad/pull/8949 triggered the unlucky ordering which lead to a bunch of errors at exit
There is also a bunch of other places where similar problems exist
=> Fix incorrect __del__

test/test_const_folding.py, test/test_schedule.py
not really belongs to test_const_folding
=> move pow folding tests to test_schedule [pr]

tinygrad/runtime/ops_metal.py
Moved loading MTLCompiler (and trying to load normal llvm before it) to MetalCompiler, like in CPUProgram with helper
=> Late MTLCompiler load

tinygrad/codegen/rewriter.py
does not need to be in late_rewrite and can be simplified further
=> move xpow to sym instead of late_rewrite

tinygrad/helpers.py
os.getlogin() is broken on WSL.
getpass.getuser() is also recommended in the [python docs](https://docs.python.org/3/library/os.html#os.getlogin) and it handles the env vars internally.
=> Use getpass.getuser() instead of os.getlogin()

tinygrad/shape/view.py
Also removed `TODO: this resolve shouldn't be needed`, same diff as: #8067
=> raise ValueError in view reshape for negative dims [pr]

tinygrad/codegen/rewriter.py, tinygrad/renderer/cstyle.py, tinygrad/runtime/ops_dsp.py, tinygrad/spec.py
=> dsp float4 fold + revectorize [pr]

test/test_ops.py
still one correction=0 case is broken
=> enable backward tests in test_std_one_in_axis [pr]

.github/actions/setup-tinygrad/action.yml
=> update gpuocelot commit

.github/workflows/test.yml, test/test_fuzz_shape_ops.py, test/test_renderer_failures.py
remove the exclusion in yaml and exclude on the test directly
=> adjust cuda ci test targets

README.md
Just reading through Readme and saw two typos. 
Feel free to not merge this and fix it yourself, just wanted to tell.
=> Minor typo in Readme

tinygrad/tensor.py
it returns single value for const tensor
=> update doc of Tensor.tolist

test/mockgpu/nv/nvgpu.py, tinygrad/runtime/ops_nv.py
we don't generate gridDim/blockDim in out code for now, but let's follow the spec.
=> nv: fill grid/block sizes

test/test_ops.py
=> failed test cases for rsqrt at 0 and similar ones

test/test_linearizer.py, test/test_linearizer_failures.py, tinygrad/codegen/kernel.py, tinygrad/ops.py, tinygrad/renderer/__init__.py, tinygrad/spec.py
updated the comments and doc except extra
=> UOps. -> Ops. [pr]

test/test_subbuffer.py
=> remove contiguous in test_subbuffer_used [pr]

examples/handcode_opt.py, extra/optimization/helpers.py, extra/optimization/rl.py, extra/optimization/search.py, extra/optimization/test_net.py, extra/optimization/test_time_linearizer.py, test/external/external_benchmark_hcopt.py, test/external/speed_beam_v_hcopt.py, test/external/verify_kernel.py, test/test_linearizer_overflows.py, test/test_search.py, tinygrad/engine/search.py
=> move time_linearizer to extra.optimization.helpers [pr]

tinygrad/codegen/rewriter.py
I can add a regression test later today.
=> mulacc_unrolled should happen even with no DEVECTORIZE

test/test_nn.py, tinygrad/nn/__init__.py
Reverts tinygrad/tinygrad#6799
=> Revert "match torch rmsnorm implementation"

test/test_speed_v_torch.py
working on getting rid of llvm sqrt hack
=> add test_sqrt to test_speed_v_torch

test/imported/test_indexing.py, test/test_nn.py, test/test_ops.py, tinygrad/codegen/rewriter.py, tinygrad/renderer/llvmir.py
replaced with xpow 0.5 in transcendental. fixed sqrt(0) backward
=> remove SQRT hack in llvm

examples/mlperf/model_train.py
=> bert eval at the end of training

test/test_ops.py, tinygrad/tensor.py
=> swap order in rsqrt

tinygrad/engine/schedule.py
scheduling shouldn't access this value. It also doesn't belong to the becomes_map stage.
=> move buffer refcount increment to the toposort [pr]

tinygrad/engine/schedule.py
=> keep CONST/BUFFER uops in tensor_map [pr]

test/test_dtype.py, tinygrad/dtype.py
context: https://github.com/tinygrad/tinygrad/pull/8846
=> add truncate_bf16

tinygrad/renderer/llvmir.py, tinygrad/runtime/ops_llvm.py
=> refactor LLVMRenderer

examples/mlperf/model_train.py
had one run that converged better https://wandb.ai/chenyuxyz/MLPerf-BERT/runs/u66tv2hh/overview
=> increase lr for bert

test/test_ops.py, tinygrad/tensor.py
Fixes https://github.com/tinygrad/tinygrad/issues/6937
=> Make logcumsumexp numerically stable

tinygrad/engine/schedule.py
This needs a generic VIEW -> movement ops backtracking diff next to enable reorder expand.
It is possible for `becomes_map = tensor_map`, we just need to map views in a way that substitute in the end resolves to the correct UOp.
=> new order to prepare for becomes_map = tensor_map [pr]

test/test_ops.py, tinygrad/tensor.py
raise RuntimeError that matches torch instead of an implcitly cast
=> raise in scatter if self and src have different dtype [pr]

test/test_ops.py, tinygrad/codegen/transcendental.py
also added more pow with const test cases
=> minor tweak to transcendental pow

tinygrad/viz/serve.py
reordering some things and structuring server.py better. Also removed FUZZ_VIZ as it's unused.
=> viz/server cleanups [pr]

tinygrad/viz/index.html, tinygrad/viz/serve.py
```
VIZ=1 PYTHONPATH=. python test/test_linearizer.py TestKernelOpts.test_color_shapes_with_local
```
=>  add kernel axis colors to viz [pr]

examples/mlperf/helpers.py, examples/mlperf/model_train.py
reuse the same get_data_bert path in setup and real run
=> clean up bert fake data iterator [pr]

test/test_renderer_failures.py, test/test_uops.py, tinygrad/codegen/kernel.py, tinygrad/renderer/__init__.py
Reverts tinygrad/tinygrad#9151
Breaks colors in DEBUG=2
=> Revert "name from uops [pr]"

tinygrad/engine/schedule.py
forgot to include this in kernel_map2.
=> hotfix: remove extra matcher for copy/buffer_view [pr]

tinygrad/engine/schedule.py
Previously this was done in the realization/grouping stage, but this kind of behavior should be as close to when it is actually needed as possible.
BUFFER UOps do not create a real Device Buffer until ScheduleItem is constructed, same should be true for BUFFER_VIEW.
=> create subbuffer immediately before constructing ScheduleItem [pr]

tinygrad/ops.py
There is no more VIEW(BUF, UOp) after the map_tensors refactor #9165.
=> remove support for VIEW with two sources in ops [pr]

tinygrad/engine/schedule.py
This is the new assign graph:
Need to refactor this such that KERNEL is always the flat shape and VIEW is applied after ASSIGN.
=> hotfix: add output buffer back to kernel parents + comment [pr]

tinygrad/device.py, tinygrad/ops.py
Also fix wrong ctypes, rename ptr to self.mem
=> fix win32 CPUProgram missing cache flush

tinygrad/viz/serve.py
The matches we record in a bottom_up_rewrite order keep the existing graph, so it's the same order as substitute order.
Otherwise top_down_rewrite overrides the SINK after every match from sources.
New final VIZ of beautiful_mnist create_kernels:
=> correctly step through bottom_up_rewrites in viz [pr]

examples/mlperf/helpers.py
set with BERT_SIZE=tiny. easier to study embedding and fusion
=> add bert tiny config

extra/models/transformer.py, extra/onnx.py, tinygrad/tensor.py
indexing and onehot compare with arange, and non-int dtype is likely a bug
will check onnx failure tomorrow.
=> _one_hot_along_dim input needs to be int

setup.py, test/unit/test_gradient.py
used torch.autograd.grad, but not sure if it can be a template like jax
=> use torch in test_gradient

.github/workflows/test.yml, setup.py, test/unit/test_helpers.py
skipped a few for now due to file permission errors
--ignore=test/unit/test_disk_tensor.py --ignore=test/unit/test_elf.py --ignore=test/unit/test_tar.py
=> run unit test on windows ci

tinygrad/runtime/ops_metal.py
=> metal: choose compile spec based on macos

test/test_ops.py, tinygrad/tensor.py
semi revert some pow logic back to tensor. added direct gradient check because the backward in test_ops passed by luck
=> fix gradient of pow(t, int)

extra/torch_backend/backend.py, extra/torch_backend/backend2.py, tinygrad/dtype.py, tinygrad/tensor.py
Should do a second PR to move these to methods on dtype at some point
=> torch and numpy dtype interop [pr]

examples/mlperf/model_train.py, examples/mlperf/training_submission_v5.0/tinycorp/benchmarks/bert/implementations/tinybox_green/dev_beam.sh, examples/mlperf/training_submission_v5.0/tinycorp/benchmarks/bert/implementations/tinybox_green/run_and_time.sh, examples/mlperf/training_submission_v5.0/tinycorp/benchmarks/bert/implementations/tinybox_red/dev_beam.sh, examples/mlperf/training_submission_v5.0/tinycorp/benchmarks/bert/implementations/tinybox_red/run_and_time.sh
running dev_beam migh OOM without it but runs fine in real run.
=> RESET_STEP in bert setup and beam

tinygrad/viz/index.html, tinygrad/viz/lib/worker.js
No white bar on firefox + fixed different behavior for `isIntersecting` on firefox when the bounding box area is 0.
=> viz ui fixes [pr]

test/external/speed_v_theoretical.py
=> lower test_gemm_8192 amd to 70

extra/torch_backend/backend.py
=> fix aten.normal_ arg

extra/torch_backend/backend.py
=> fix aten.reflection_pad2d

extra/torch_backend/backend.py
=> torch backend fix manual seed warning

test/test_ops.py
a few detach().numpy() -> detach().cpu().numpy() taken from #9302
=> update test_ops for tensors from torch

extra/onnx.py, test/external/external_test_onnx_backend.py, test/external/external_test_onnx_ops.py
~so it appears qlinearop is round away from zero while quantize linear is round to even~
I think it's all round to even...
=> Test Onnx quantization behavior

extra/torch_backend/backend.py, tinygrad/tensor.py
`72 failed` -> `67 failed, 111 passed` on Metal
=> aten leaky_relu, div.out_mode, clamp_max, clamp_min, copysign

test/test_arange.py, test/test_linearizer.py, test/unit/test_simplify_valid_idx.py, test/unit/test_uop_symbolic.py, tinygrad/ops.py
The failing tests are commutative add stuff.
=> reorder binops

test/test_linearizer.py
Doesn't work for all tests, but fine for things that don't check numpy
=> use empty for test instead of rand

test/test_schedule.py, tinygrad/engine/schedule.py, tinygrad/ops.py
`merge_views` to VIEW/MovementOps is like `symbolic_simple` to ALU Ops.
=> merge merge_views and remove_movement_ops [pr]

extra/torch_backend/backend.py, test/test_ops.py
=> Tiny backend test_ops fix part1

.github/workflows/test.yml, extra/torch_backend/backend.py
=> ruff torch backend

.github/workflows/test.yml
=> CI ubuntu-20.04 -> ubuntu-22.04

extra/torch_backend/backend.py
Related to #9302
101 --> 75 failures
=> Fix test_ops for tiny backend part 2

tinygrad/runtime/ops_amd.py
=> gfx10 correct ctl stack size

tinygrad/runtime/ops_amd.py
=> amd: support relocatable elf

tinygrad/engine/schedule.py
This setup makes it easy to write the new grouper. Currently if a UOp is not a contiguous/copy/assign, it checks the context to see if the grouper realizes it.
The new grouper should simply insert a contiguous whenever there is a UOp we want to realize.
=> always create kernels for assign/contiguous/copy [pr]

examples/llama3.py, examples/mlperf/initializers.py, extra/gemm/fuzz_matmul.py, extra/gemm/simple_conv.py, extra/gemm/simple_matmul.py, extra/gemm/simple_matvec.py, extra/torch_backend/backend.py, test/test_dtype.py, test/test_linearizer.py, test/test_ops.py, test/test_quantize_onnx.py, test/test_renderer_failures.py, test/test_search.py, tinygrad/nn/__init__.py, tinygrad/tensor.py
=> acc_dtype -> dtype

.github/workflows/test.yml, autogen_stubs.sh, extra/sqtt/README.md, extra/sqtt/rgptool.py, extra/sqtt/sqtt.h, tinygrad/device.py, tinygrad/runtime/autogen/sqtt.py, tinygrad/runtime/ops_amd.py, tinygrad/runtime/support/hcq.py
It currently runs on AMD (non-AM) but sometimes hangs, no idea why quite yet.
The stuff that deals with .rgp file format is in extra/, the stuff that deals with gpu sqtt is in ops_amd.py
extra/sqtt/rgptool.py is a nice tool to quickly see what's inside those .rgp files and modify them for testing (currently via python repl only)
=> SQTT profiling

tinygrad/engine/schedule.py
childless CONST/VIEW do not have a kernel, it's very annoying to write the new grouper when these ops are still around in the graph. becomes_map is good enough now that we don't need them anymore.
=> no const/view in schedule sink after sym [pr]

.github/workflows/test.yml, extra/torch_backend/backend.py, extra/torch_backend/test_multigpu.py, extra/torch_backend/wrapped_tensor.cpp
For #9317 add just the device support. Currently pulls available device count from GPUS environment variable.
=> torch backend multigpu - add devices and tests

test/test_arange.py
it does not grow quadratically, but it's not 0 ops now
=> add GROUP and GROUPTOP to test_arange

tinygrad/renderer/cstyle.py, tinygrad/runtime/ops_amd.py, tinygrad/runtime/ops_hip.py
standalone change from #9417
re: removed process replay flag as it failed due to pickle
=> Add arch to `AMDRenderer` and `HIPRenderer`

tinygrad/engine/schedule.py
It shouldn't be two stages, the swizzles are gonna move to the big_sink.
Will change that (var_vals, bufs) back to just ctx=bufs once the swizzles are moved.
=> ast_fixup in one graph_rewrite pass [pr]

extra/gemm/simple_matmul.py
broke mac benchmark
Reverts tinygrad/tinygrad#9438
=> Revert "`simple_matmul.py` uses np to generate random"

extra/gemm/simple_matmul.py
numpy does not support bfloat16
=> redo simple_matmul change

examples/mlperf/model_train.py
closer to the other submission with BS=240. converged with 10% less epochs
=> bert lower learning rate and total steps

test/test_schedule.py, tinygrad/engine/schedule.py, tinygrad/ops.py
Fix for #9474 + prereq for the grouper refactor. It shouldn't create VALID while also doing swizzles.
=> merge_views for buffer ops + create valids last

examples/mlperf/model_train.py
slightly better. first sub 3hr run https://wandb.ai/chenyuxyz/MLPerf-BERT/runs/0or96ink/overview
=> lower bert learning rate

extra/torch_backend/backend.py, test/test_ops.py
Related to #9302
72 --> 24 failures
=> Tiny backend test_ops fix part 3

examples/olmoe.py
GlobalCounters.reset() and only validate if temperature is 0
=> olmoe touchups

test/test_arange.py, test/test_linearizer.py, test/test_multitensor.py, test/test_nn.py, test/test_ops.py, test/test_sample.py, test/test_transcendental.py
OSX has larger buffer number limit, and it supports fp16 now
=> enable more webgpu tests

test/unit/test_tqdm.py, tinygrad/helpers.py
fixed `AssertionError: ' 1.00/10.0  1000it/s]' != ' 1.00/10.0  1.00kit/s]'`
=> add rounding to tqdm unit scale

tinygrad/runtime/support/am/amdev.py
allow allocs of smaller size than huge page size passed in.
=> am: fix allocs

.github/workflows/test.yml, test/test_amd_llvm.py, tinygrad/runtime/support/compiler_amd.py
=> add amd llvm compiler (no_comgr prereq)

examples/mlperf/losses.py, test/external/external_test_losses.py, test/external/mlperf_retinanet/focal_loss.py
This PR adds both sigmoid focal and L1 losses that is used for RetinaNet model training.
=> RetinaNet losses

tinygrad/codegen/kernel.py
rest of the code assumes self.ast is defined anyway
=> assert Kernel ast.op to be Ops.SINK [pr]

tinygrad/runtime/support/llvm.py, tinygrad/runtime/support/webgpu.py
also mypy recognizes `sys.platform == 'win32'` but does not recognizes it if wrapped inside a helper...
=> minor WEBGPU_PATH cleanup [pr]

tinygrad/tensor.py
also `requires_grad_` to save a line
=> remove MOCKGPU workaround in rand

test/test_jit.py, tinygrad/codegen/symbolic.py
currently adding jit produced different rand values
=> add a failed test case for jit/nojit rand [pr]

tinygrad/viz/index.html
It was a bunch of useless lines/duplicates, also fixed the resizer creating a lot of extra divs on ever render.
=> prep viz UI cleanup for grid scales

tinygrad/viz/index.html, tinygrad/viz/lib/graph.js
It was creating extra <def> on every render
=> statically define viz arrow heads

tinygrad/viz/index.html
The old one was just reseting zoom, this recenters the entire graph and scales things correctly.
=> rescale to fit viz graph [pr]

test/test_tensor.py
This is a test I wrote for issue #9597.
=> Added a test for a problem when finding the gradients between two constants

tinygrad/viz/index.html
Reverts tinygrad/tinygrad#9605
I barely even want copy to be a custom widget.
=> Revert "add copy button in VIZ code-block"

tinygrad/runtime/support/am/amdev.py, tinygrad/runtime/support/amd.py
https://github.com/tinygrad/tinygrad/pull/9428#discussion_r2018500132
=> am: module import in common

tinygrad/ops.py
Python is holding on to the contents of `cache` after it exits a UOp.toposort scope.
```
PYTHONPATH=. IMAGE=0 python examples/openpilot/compile3.py https://github.com/commaai/openpilot/raw/v0.9.7/selfdrive/modeld/models/dmonitoring_model.onnx dmonitoring_model_tinygrad.pklthub.com/commaai/openpilot/raw/v0.9.7/selfdrive
```
From this branch:
```
146351
146453
146453
```
vs master with memory leak:
```
146400
146526
146550
```
=> do not block gc in UOp.toposort

autogen_stubs.sh
=> Fix generate_am

tinygrad/viz/index.html
Every iteration of the viz refactor I implemented some form of this, I think it's a standalone win as this re rendering is written in so many places.
=> refactor viz state updates

tinygrad/viz/index.html
These should have never been so many lines,
The rest of line gains in viz is gonna come from carefully sharing logic between the different parts.
=> hotfix: less lines for viz helpers

tinygrad/ops.py
Reverts tinygrad/tinygrad#9624
=> Revert "Revert "do not block gc in UOp.toposort (#9623)""

tinygrad/viz/index.html
ripping out Object.assigns in viz one at a time, it makes the code unreadable.
=> viz kernel list cleanup

test/test_linearizer.py
Came up on #9606
Related to #9647
=> Uppercase K for dimension and lowercase k for kernel

tinygrad/engine/realize.py, tinygrad/runtime/ops_cuda.py
DEBUG >= 6 will output linearized uops
=> bump assembly debug >= 7

tinygrad/runtime/ops_null.py
DEBUG=2 and checking if things are allocated does not require a value on _buf.
Empty Compiler still needs src from Renderer though.
=> hotfix: NULL=1 Buffer does not have _buf

test/unit/test_uop_symbolic.py, tinygrad/codegen/symbolic.py
can be wrong in C div since it truncates towards zero
=> don't div_and_mod_folding for negative numerator with remainder

test/test_multitensor.py
=> skip CI CPU test_data_parallel_resnet_train_step

docs/env_vars.md
I think this is useful for newcomers. I remember checking this doc repeatedly when I first started diving into tinygrad. 
The drawback is that it will need to be maintained. But I think it might be worth it
=> Debug env var breakdown

.github/actions/setup-tinygrad/action.yml
`-DCMAKE_POLICY_VERSION_MINIMUM=3.5`
=> update install gpuocelot

extra/onnx.py, test/external/external_test_onnx_ops.py
Attributes `detect_negative` and `detect_positive` are 1 and 0 only.
Separated from #9471
=> fix ONNX IsInf unintended dtype promotion

.github/workflows/benchmark.yml
Reverts tinygrad/tinygrad#9690
=> Revert "disable CI red llama 3 4 gpu beam"

tinygrad/codegen/devectorizer.py
=> only check once for divisible fold lengths

tinygrad/runtime/ops_amd.py
linux amdgpu_discovery.c:amdgpu_discovery_set_ip_blocks is a ton of switch cases with sometimes weird choices like replacing nbio 3.X with 2.3 while nbio 2.5 is somehow nbio 7.0. `import_module` currently just tries to replace revision and minor with zeroes if there is no exact match, but that's not enough to cover all that weirdness
=> Fix RDNA2 support

test/external/external_benchmark_bert_matmuls.py
2 main matmuls in the bert layers. getting these to be fast makes bert fast
=> benchmark script for matmuls in bert

tinygrad/viz/js/profiler.js, tinygrad/viz/profiler.html, tinygrad/viz/serve.py
should be in the main viz tab - selection without button preferred (select from the list)
left sidebar will keep the kernels list + "Profiler list item"
center graph renders the timeline
right sidebar has the info about kernels (hover, select, etc)
=> viz profiler ui

test/external/external_benchmark_bert_matmuls.py
include the linear to get qkv, and permute so that stride matches with the real run
=> weighted linear in external_benchmark_bert_matmuls

tinygrad/tensor.py
easier to see if it's permuted to or permuted from
=> update doc for permute to 3d tensor

examples/mlperf/training_submission_v5.0/tinycorp/benchmarks/bert/implementations/tinybox_green/run_and_time.sh, examples/mlperf/training_submission_v5.0/tinycorp/benchmarks/bert/implementations/tinybox_red/run_and_time.sh
save 5 minut scheduling in setup so we can fit more search
=> use BERT_LAYERS=2 in bert init

examples/mlperf/training_submission_v5.0/tinycorp/benchmarks/bert/implementations/tinybox_8xMI300X/run_and_time.sh
=> full script for bert mi300x

test/test_softmax_fusion.py
getting RecursionError with DONT_GROUP_REDUCES=1
=> failed test for single softmax backward

.github/workflows/benchmark.yml, extra/gemm/simple_matmul.py, tinygrad/renderer/cstyle.py
also add `SHOULD_USE_TC=1` to verify TC is applied in simple_matmul
=> fix TF32 tensor core dropped in tc_sm89

.github/workflows/benchmark.yml, extra/gemm/simple_matmul.py
also zero centered the random input and update atol for tf32
=> add SHOULD_USE_TC=1 check to simple_matmul

.github/workflows/test.yml
=> higher ATOL for half input TC test

.github/workflows/test.yml
it's a function of N so only updated in the test command
=> more relaxed ATOL for HALF=1 simple_matmul test

test/test_softmax_fusion.py
that passed but adding fuse to Embedding still breaks gpt2
=> add test_embedding to test_softmax_fusion

test/unit/test_device.py, tinygrad/device.py
=> canonicalize Device.DEFAULT

examples/handcode_opt.py, extra/gemm/tvm_gemm.py, extra/optimization/get_action_space.py, extra/optimization/test_net.py, extra/replay_pkl.py, test/external/external_benchmark_hcopt.py, test/external/external_benchmark_schedule.py, test/external/speed_beam_v_hcopt.py, test/external/speed_compare_cuda_nv.py, test/external/speed_compare_cuda_ptx.py, test/test_linearizer.py, test/test_winograd.py, tinygrad/codegen/heuristic.py, tinygrad/codegen/kernel.py, tinygrad/engine/realize.py
=> move hand_coded_optimizations to heuristic.py [pr]

test/external/external_test_example.py
It fails at least on NV/CUDA
Closes #9814
=> Skip CLOUD in external_test_example

docs/env_vars.md, tinygrad/runtime/support/compiler_cuda.py
=> Use $CUDA_PATH/include for CUDA headers

examples/mlperf/model_train.py
This PR adds the `EVAL_FREQ` flag that controls how often the evaluation is run. By default, it is set to 1 as per MLPerf requirement.
=> RetinaNet eval frequency flag

test/test_dtype.py, tinygrad/device.py, tinygrad/dtype.py, tinygrad/tensor.py
=> FP8s part 1

examples/gpt2.py
Variable upper bound is inclusive
=> Off by one error in start_pos

tinygrad/runtime/ops_cloud.py
Not-quite-required but makes cloud graph a *lot* cleaner because unlike raw compiled programs `GraphRunner` takes `Buffer`s like other runners.
Otherwise either of: adding a new option to not free on `__del__`, (ab)using `external_ptr` to prevent free, or making something like a `FakeBuffer` is required.
=> Use Buffer in cloud server instead of opaques

tinygrad/viz/js/index.js, tinygrad/viz/js/worker.js
It will look like this:
Tested on https://github.com/tinygrad/tinygrad/pull/9885/commits/78ea6d08744d43cab0da563a5f3a85a3264bbd7c with test_9_gemm.
=> add counter for incoming edges in viz

extra/gemm/amd_matmul.py, extra/gemm/max_matmul.py, extra/gemm/tinygrad_nv_matmul.py, extra/optimization/extract_sa_pairs.py, extra/optimization/helpers.py, test/external/external_debug_metal_sd_conv.py, test/external/external_test_hcq_fuzz_failures.py, test/external/external_test_nv.py, test/external/external_test_train_gpt2.py, test/external/external_test_valid_remove.py, test/external/process_replay/process_replay.py, test/external/verify_kernel.py, test/test_linearizer.py, test/test_linearizer_dumb.py, test/test_linearizer_failures.py, test/test_linearizer_overflows.py, test/test_quantize_onnx.py, tinygrad/codegen/kernel.py
updated all `for opt in`. also updated a few test_linearizer tests to not implicitly depend on hand_coded_optimization
=> Kernel.apply_opts [pr]

setup.py
6.131.1 seems to cause timeout in CI
=> pin hypothesis version to 6.131.0

examples/handcode_opt.py, extra/optimization/get_action_space.py, extra/optimization/test_net.py, extra/replay_pkl.py, test/external/external_benchmark_hcopt.py, test/external/external_benchmark_schedule.py, test/external/speed_beam_v_hcopt.py, test/external/speed_compare_amd_am.py, test/external/speed_compare_cuda_nv.py, test/external/speed_compare_cuda_ptx.py, test/test_linearizer.py, test/test_winograd.py, tinygrad/codegen/heuristic.py, tinygrad/engine/realize.py
new api looks like `k.apply_opts(hand_coded_optimizations(k))`
=> hand_coded_optimizations returns list[Opt] [pr]

examples/mlperf/model_train.py
This PR contains a few small cleanups that I have found after the initial RetinaNet training script got merged.
=> RetinaNet training script cleanups

examples/mlperf/model_train.py, examples/mlperf/training_submission_v5.0/tinycorp/benchmarks/retinanet/tinybox_red/dev_beam.sh, examples/mlperf/training_submission_v5.0/tinycorp/benchmarks/retinanet/tinybox_red/dev_run.sh
also BASE_DIR -> BASEDIR for consistency, and move wandb up a bit for more accurate timing
=> dev scripts for retinanet

tinygrad/codegen/kernel.py
First pr of the refactor `use_tensor_cores` into `tc_mode`
This pr focuses on correctly checking for `k.opts.tensor_cores`. Before, it was still possible to trigger `OptOps.TC` without having tensor cores by using `TC=2`. This was wrong, as there is no way of applying tensor core shape if there is no tensor core.
This refactor is relevant as right now `use_tensor_cores` value from `apply_tensor_cores` is not propagated correctly. It uses the value passed only within the function but when applying the opt in `apply_opt` it fetches the value from the context var `USE_TC`.
=> `use_tensor_cores` bugfix [pr]

examples/mlperf/model_train.py, examples/mlperf/training_submission_v5.0/tinycorp/benchmarks/retinanet/tinybox_green/dev_beam.sh, examples/mlperf/training_submission_v5.0/tinycorp/benchmarks/retinanet/tinybox_green/dev_run.sh
also removed realize in data_get and used empty for fake data. slightly bigger lr. https://wandb.ai/chenyuxyz/MLPerf-RetinaNet/runs/8skid0e8?nw=nwuserchenyuxyz
=> retinanet green scripts

examples/mlperf/model_eval.py
`BS=96 BASEDIR="/raid/datasets/openimages" MODEL=retinanet python examples/mlperf/model_eval.py`
```
...
loaded dataset             @  8.64s
loaded initial data        @ 12.57s
******  619.97 ms to enqueue, 46042.13 ms to realize ( 116.22 ms fetching, 45399.58 ms postprocess_detections).     0.09 examples/sec.  0.83 TFLOPS  @ 59.23s
******  147.49 ms to enqueue, 37362.16 ms to realize ( 146.96 ms fetching, 36618.84 ms postprocess_detections).     0.11 examples/sec.  1.03 TFLOPS  @ 96.74s
******  152.85 ms to enqueue, 37244.08 ms to realize ( 120.67 ms fetching, 36235.19 ms postprocess_detections).     0.11 examples/sec.  1.04 TFLOPS  @ 134.14s
******  146.39 ms to enqueue, 37279.85 ms to realize (  65.07 ms fetching, 36233.56 ms postprocess_detections).     0.11 examples/sec.  1.04 TFLOPS …
```
=> print postprocess_detections time in retinanet eval

test/test_linearizer.py
`bf16` is not supported for `PYTHON` so no need to check for each `EMULATED_x` individually
=> use `is_dtype_supported` to check dtype support in tc tests

test/test_linearizer.py, tinygrad/device.py
=> hotfix `amd` bf16 is supported case

extra/remu/src/thread.rs
`DS_STORE_B16_D16_HI` and VOP3 f16 mul.
@ignaciosica If you're not in a rush I'll add a unit test and merge this separately. Otherwise feel free to cherrypick the commit.
=> remu new instructions

tinygrad/runtime/ops_amd.py
from fuzz:
```
[Sat Apr 26 08:55:45 2025] python3[516551]: segfault at 7f003f78f000 ip 0000576509a949c6 sp 00007ffc9a383ea0 error 6 in python3.10[576509a0b000+2b5000] likely on CPU 39 (core 13, socket 0)
[Sat Apr 26 08:55:45 2025] Code: c7 e8 9e 56 1e 00 49 83 6d 00 01 49 89 c6 74 23 49 83 fe ff 74 d4 f6 43 28 01 75 21 4c 8b 63 18 41 8b 44 24 10 83 e0 01 75 13 <4c> 89 75 00 e9 11 97 1e 00 4c 89 ef e8 e9 d3 05 00 eb d3 48 8d 05
```
or
```
...
File "/home/nimlgen/tinygrad/tinygrad/device.py", line 190, in alloc
return self._alloc(size, options if options is not None else BufferSpec())
File "/home/nimlgen/tinygrad/tinygrad/runtime/ops_amd.py", line 462, in _alloc
return self.dev.dev_iface.alloc(size, host=options.host, uncached=options.uncached, cpu_access=options.cpu_access)
File …
```
=> am: fix mmap failures

examples/coder.py, examples/llama.py, examples/llama3.py, examples/olmoe.py, examples/qwq.py, extra/models/llama.py
=> don't pass model in convert_from_huggingface and convert_from_gguf

test/unit/test_viz.py, tinygrad/ops.py, tinygrad/viz/js/index.js, tinygrad/viz/serve.py
space can be 0-n depending on the depth:
=> display viz rewrites with tabbing if they are subrewrites

extra/models/llama.py
=> remove TransformerBlock contiguous in llama

extra/models/llama.py, test/test_symbolic_jit.py, test/test_symbolic_ops.py, tinygrad/tensor.py
support slice that has step None and stop > start
=> simple symbolic slice in llama [pr]

test/unit/test_tensor_uop_representation.py, tinygrad/engine/grouper.py, tinygrad/engine/multi.py, tinygrad/ops.py, tinygrad/spec.py
Reverts tinygrad/tinygrad#10120
=> Revert "flip Ops.COPY order [pr]"

tinygrad/runtime/support/allocator.py, tinygrad/runtime/support/am/amdev.py, tinygrad/runtime/support/am/ip.py
10.61ms -> 7.11ms
but need to revisit allocator
=> Am faster alloc

test/unit/test_uop_symbolic.py, tinygrad/codegen/symbolic.py
Pattern is not correct currently if  `x.vmax` is not the same sign as `x.vmin`
=> Sign check in div const div pattern

test/mockgpu/usb.py, tinygrad/runtime/support/usb.py
=> usbgpu: send pci write in batches

test/unit/test_uop_symbolic.py, tinygrad/codegen/symbolic.py
A nice property about c div is you can take out the sign
=> Take neg out of idiv

test/helpers.py, test/test_image_dtype.py, test/test_jit.py, tinygrad/engine/jit.py, tinygrad/engine/realize.py, tinygrad/runtime/graph/remote.py, tinygrad/runtime/ops_remote.py
bert step:
cloud master - 1880.25 ms
cloud this - 1232.38 ms
master - 1094.61 ms
llama:
cloud master - 4.55 tok/s
cloud this - 9.20 tok/s
master - 17.63 tok/s
=> Cloud graph

test/test_schedule.py, tinygrad/engine/grouper.py, tinygrad/ops.py, tinygrad/spec.py
I'd really like to remove clone altogether..
=> all COPY can be clone

tinygrad/codegen/symbolic.py
I waay overthought this when I wrote it. Im just doing some refactoring because making changes to div_and_mod_folding before  #10174
=> Cleanup in `div_and_mod_folding` [pr]

.gitignore, tinygrad/engine/grouper.py, tinygrad/viz/js/index.js
Order of unique and device changed in BUFFER, also the parents substitute should not be hidden in viz.
=> minor grouper + viz fixup [pr]

test/unit/test_uop_symbolic.py, test/unit/test_uop_vmin_vmax.py
clean up TODOs and update tests
=> update uop symbolic tests [pr]

test/unit/test_uop_symbolic.py, tinygrad/codegen/symbolic.py, tinygrad/ops.py
the simplification was wrong with negative const_factor
=> fix test_div_numerator_negative

tinygrad/codegen/symbolic.py
remove type ignore and one walrus
=> minor div_and_mod_folding cleanup [pr]

test/models/test_real_world.py
added a working bert tiny test, and a failed bert FUSE_ARANGE test
=> train bert tests

tinygrad/runtime/ops_remote.py
bert step
cloud master: 1200.77 ms
cloud this: 1110.79 ms
native: 1114.81 ms
8% slower => within the margin of error
resnet step
cloud master: 13401.95 ms
cloud this: 3077.48 ms
native: 2131.50 ms
(530% slower => 44% slower, prob because a ton of stuff is being copied)
llama
cloud master: 10.44 tok/s
cloud this: 21.30 tok/s
native: 23.01 tok/s
(120% slower => 8% slower)
It also fixes the [weird ci thing](https://discord.com/channels/1068976834382925865/1294150613738983445/1370223404355162225) @chenyuxyz found.
master:
this:
4 minutes => 25 seconds total time
And it's capable of handling more than one connection (python http server just doesn't accept new connections before the old one is closed) which will allow multiple clients to connect at the same time and infiniband discovery server …
=> Faster remote server

test/helpers.py
Useful for testing remote multi stuff
=> Metal multi in ci is fine actually

tinygrad/runtime/support/amd.py
it's cheap now, so we can rescan it every run to eliminate chances of compatibility issues
=> usbgpu: rescan pci bus every run

.github/workflows/test.yml, test/helpers.py, tinygrad/runtime/ops_remote.py
Simplest thing to be able to use remote with multiple gpus, very slow because no transfers (copyin copyout for cross-device copies)
=> Remote multi (basic)

tinygrad/runtime/ops_remote.py
(stacked on top of #10269)
Should be a small speed improvement but the main reason this is needed is to have a defined ordering of RemoteRequests within one host so that transfers won't required doing something like:
```python
src_dev.batch_submit()
dest_dev.q(Transfer(dest, src_dev.session, src))
dest_dev.batch_submit()
```
for correctness.
=> Factor out remote connection and cache it

tinygrad/runtime/ops_remote.py
=> Remote multi (transfer)

test/test_schedule.py
new FUSE_ARANGE fixed the contiguous override issue, we don't need to skip those tests.
Moving forward I'll use assertRaisesRegex instead, skip makes behavior changes silent.
=> remove some skips in test_schedule + use assertRaisesRegex [pr]

extra/amdpci/am_smi.py, tinygrad/runtime/ops_amd.py, tinygrad/runtime/support/am/amdev.py, tinygrad/runtime/support/am/ip.py
```
sudo -E AMD=1 AM_RESET=1 AMD_IFACE=USB DEBUG=2 PYTHONPATH=. time python3 test/test_tiny.py TestTiny.test_plus
opened device PYTHON from pid:17579
am usb:0: mode1 reset
am usb:0: AM_SOC initialized
am usb:0: AM_GMC initialized
am usb:0: AM_IH initialized
am usb:0: loading sos component: PSP_FW_TYPE_PSP_KDB
am usb:0: loading sos component: PSP_FW_TYPE_PSP_KDB
am usb:0: loading sos component: PSP_FW_TYPE_PSP_SYS_DRV
am usb:0: loading sos component: PSP_FW_TYPE_PSP_SOS
am usb:0: loading fw: GFX_FW_TYPE_SMU
am usb:0: loading fw: GFX_FW_TYPE_SDMA_UCODE_TH1
am usb:0: loading fw: GFX_FW_TYPE_SDMA_UCODE_TH0
am usb:0: loading fw: GFX_FW_TYPE_RS64_MEC
am usb:0: loading fw: GFX_FW_TYPE_RS64_MEC_P0_STACK
am usb:0: loading fw: GFX_FW_TYPE_IMU_I
am usb:0: loading fw: GFX_FW_TYPE_IMU_D
am usb:0: …
```
=> usbgpu: fast cold boot

examples/minrf.py
tested that it trains to similar loss
=> randn_like in minrf

tinygrad/engine/jit.py
https://github.com/tinygrad/tinygrad/pull/9923#discussion_r2051406448
=> All MultiGraphRunners can graph transfers

setup.py
might be fine now? lots of perf improvements for the constants feature in 6.131.1 in the newer versions
=> feat: unpin hypothesis

test/test_dtype_alu.py
probably need this to avoid hitting it
=> hotfix: filter_too_much

examples/mlperf/dataloader.py
Hmm, this isn't the right fix...
=> resnet dataloader osx

tinygrad/runtime/ops_remote.py
Seems a bit cleaner than doing `.batch_request()` after `.q(...)` for requests with return value.
=> Remote `.q(..., wait=True)`

tinygrad/runtime/ops_remote.py
=> Remote finalize

test/test_symbolic_ops.py
=> Add conv2d ceildiv edge case

test/test_nn.py
With NOOPT=0, arange stays as a for loop:
NOOPT=1 seems to correctly fold the arange though:
```
VIZ=1 PYTHONPATH=. python test/test_nn.py -k 'test_embedding_one_kernel'
```
=> Failing test for slow embedding kernel with FUSE_ARANGE=1 [pr]

tinygrad/device.py
for regular buffers it's always 0. and helps to analyze which buffers are subbuffers
=> print offset only for subbuf

tinygrad/runtime/ops_remote.py
For memory savings from memory planner. Also for some reason it makes hlb cifar on mac noticeably faster.
master:
```
3  210.12 ms run,    4.34 ms python,  205.78 ms REMOTE, 2075.90 loss, 0.002698 LR, 2.07 GB used,   1558.41 GFLOPS,    327.45 GOPS
4  210.40 ms run,    4.33 ms python,  206.07 ms REMOTE, 2481.94 loss, 0.002262 LR, 2.07 GB used,   1556.34 GFLOPS,    327.45 GOPS
5  188.08 ms run,    4.41 ms python,  183.67 ms REMOTE, 1967.49 loss, 0.001827 LR, 2.07 GB used,   1741.00 GFLOPS,    327.45 GOPS
6  211.19 ms run,    4.26 ms python,  206.93 ms REMOTE, 1511.62 loss, 0.001392 LR, 2.07 GB used,   1550.51 GFLOPS,    327.45 GOPS
```
this:
```
3  189.05 ms run,    4.50 ms python,  184.55 ms REMOTE, 2075.90 loss, 0.002698 LR, 1.60 GB used,   1732.08 GFLOPS,    327.45 GOPS
4  187.81 ms run, …
```
=> Remote offset

test/mockgpu/cuda/cuda.py
=> fix: mockgpu cuda timing

.github/actions/setup-tinygrad/action.yml
example https://github.com/tinygrad/tinygrad/actions/runs/15057000247
=> brew --quiet to suppress already installed warnings

extra/remu/src/work_group.rs
=> simpler barrier match in remu

tinygrad/renderer/cstyle.py, tinygrad/runtime/ops_remote.py
Just overriding device in renderer seems to work fine, ~~currently running bert to check, will mark ready for review if works fine.~~ Bert ran successfully, but ci failed because cstylerenderer checks .device for renderer-specific things instead of having separate properties for them, #10361 should fix it
=> Remote beam

test/test_multitensor.py, tinygrad/runtime/graph/hcq.py
=> add hcq fixedvars support [pr]

tinygrad/runtime/graph/metal.py
=> metal: do not require icb fix on m3+

.github/workflows/mlperf.yml
will add proper daily cron instead of hourly and run full stuff if manual trigger looks good
=> test cron job to run resnet

tinygrad/engine/search.py
TODO: someone should track what triggers this down and add a test
=> fix beam none if buf is optimized out

.github/workflows/test.yml, test/test_schedule.py, tinygrad/codegen/kernel.py, tinygrad/engine/grouper.py, tinygrad/ops.py
The edges dict has to go too, it should only gate on Ops.CONTIGUOUS.
=> simpler can_pad

extra/remu/src/helpers.rs, extra/remu/src/thread.rs, extra/remu/test/hwtest.py
=> add v_rcp_f32_e64 to remu

.github/workflows/test.yml, test/mockgpu/amd/amddriver.py, test/mockgpu/amd/amdgpu.py
For testing remote graph stuff (prompted by #10371) in ci
=> amd mockgpu multigraph support

tinygrad/runtime/ops_remote.py
bytes concat is slow, don't do it if data is already present in self._h
also don't cast memoryview into bytes (copy, +100ms) before it's needed
this mitigates shard copying before shrink
master:
```
*** REMOTE     6 copy 1073.74M,  REMOTE <- METAL           arg  2 mem  2.15 GB tm    806.84ms/   829.61ms (     0.00 GFLOPS    1.3|1.3     GB/s)
*** REMOTE:    7 copy 1073.74M, REMOTE: <- METAL           arg  2 mem  3.22 GB tm    797.41ms/  1627.02ms (     0.00 GFLOPS    1.3|1.3     GB/s)
*** REMOTE:    8 copy 1073.74M, REMOTE: <- METAL           arg  2 mem  4.29 GB tm    677.89ms/  2304.91ms (     0.00 GFLOPS    1.6|1.6     GB/s)
*** REMOTE:    9 copy 1073.74M, REMOTE: <- METAL           arg  2 mem  5.37 GB tm    659.81ms/  2964.72ms (     0.00 GFLOPS    1.6|1.6     GB/s)
*** REMOTE:   10 …
```
=> Slightly less slow remote copyin

sz.py
Sadly there's no tokenizer builtin for javascript. Ignoring comments and empty lines only.
=> count viz javascript in lines

test/test_multitensor.py, tinygrad/engine/grouper.py, tinygrad/engine/multi.py, tinygrad/tensor.py, tinygrad/uop/spec.py
Resolves https://github.com/tinygrad/tinygrad/issues/10397.
Only need to change becomes_map for SINK(...MULTI). - Also I don't think `TestMultiTensor.test_mlb_assign_change_axis` tests anything right now. It's failing a spec check in master, not the assign_multi assert.
=> move multi_map to grouper rewrite pass

.github/workflows/mlperf.yml
also made push to `update_mlperf` branch trigger
=> run mlperf resnet on red box

tinygrad/runtime/ops_amd.py
this is hf to make ci always green, I will test d3->d0 state better
=> am: disable idle d3

test/test_const_folding.py, test/test_dtype_alu.py, test/test_edgecases.py, test/test_ops.py, test/test_quantize_onnx.py, test/test_schedule.py, test/unit/test_simplify_valid_idx.py, tinygrad/codegen/symbolic.py, tinygrad/tensor.py, tinygrad/uop/ops.py
#10321 
passed fuzzer for integer mod.
some regression in const folding can wait for a different pr as this is more correct.
need to fix quantize DSP though
=> fix tensor int floor div

tinygrad/renderer/cstyle.py, tinygrad/renderer/ptx.py
independent pre req from #9771
in the future we might want dynamic sized alignment, but this is a safe place to start from
=> align 16 shared buffs in ptx, metal, cuda and amd

tinygrad/runtime/support/amd.py
additionally nbio 2.3.0 is nbio_2_3_offset.h in the kernel
=> fix: apply ip version fixes during AMDIP creation

tinygrad/uop/ops.py
=> graph_rewrite_map in the other order [pr]

.github/workflows/mlperf.yml
Runs at 08:05 UTC (12:05 AM Pacific Time)
=> run mlperf resnet daily

extra/onnx.py, test/external/external_test_onnx_ops.py
=> Add ONNX training op tests for large update count

.github/workflows/test.yml
fix ci in https://github.com/tinygrad/tinygrad/pull/10253
ci success with this (AMD_LLVM=1): https://github.com/b1tg/tinygrad/actions/runs/15235587306
=> ci: setup llvm for amdremote

examples/mlperf/training_submission_v5.0/tinycorp/systems/tinybox_8xMI300X.json, examples/mlperf/training_submission_v5.0/tinycorp/systems/tinybox_green.json, examples/mlperf/training_submission_v5.0/tinycorp/systems/tinybox_red.json
standardized processor and accelerator names
=> mlperf system updates

docs/tensor/ops.md, tinygrad/tensor.py
like #10542 but with the typo fixed
=> Docs for masked_fill

test/test_renderer_failures.py, tinygrad/renderer/cstyle.py
=> cstyle strips paren for AND and OR

tinygrad/engine/grouper.py
Enabled by the LOAD refactor: https://github.com/tinygrad/tinygrad/pull/10541, this can merge with the same generic rewrite rule ALU ops use.
=> remove custom merge_views rewrite rule for buffer ops [pr]

.github/workflows/mlperf.yml, examples/mlperf/training_submission_v5.1/tinycorp/benchmarks/bert/implementations/tinybox_8xMI300X/run_and_time.sh, examples/mlperf/training_submission_v5.1/tinycorp/benchmarks/bert/implementations/tinybox_green/run_and_time.sh, examples/mlperf/training_submission_v5.1/tinycorp/benchmarks/bert/implementations/tinybox_red/run_and_time.sh, examples/mlperf/training_submission_v5.1/tinycorp/benchmarks/resnet/implementations/tinybox_green/run_and_time.sh, examples/mlperf/training_submission_v5.1/tinycorp/benchmarks/resnet/implementations/tinybox_red/run_and_time.sh, examples/mlperf/training_submission_v5.1/tinycorp/benchmarks/retinanet/implementations/tinybox_green/run_and_time.sh
also run the 5.1 script in ci cron job
=> `set -o pipefail` for mlperf run_and_time

tinygrad/engine/grouper.py
defaultdict has footguns, plain list is enough because the grouper just uses LIFO
=> use plain dict and list in grouper [pr]

tinygrad/renderer/wgsl.py
=> remove a MUL rewrite rule for wgsl

tinygrad/runtime/support/am/amdev.py, tinygrad/runtime/support/am/ip.py
print more pf info + issue a full reset after a pf
=> am: more info on PFs

test/external/external_model_benchmark.py
=> remove metal buffer limit in external_model_benchmark [pr]

tinygrad/renderer/llvmir.py
model_train.py should work after this
=> AMD_LLVM: support mfma for mi300x

test/test_ops.py, tinygrad/tensor.py
was incorrectly casted into int
=> fix const float pow to int tensor

tinygrad/tensor.py
also added many `s` for consistency
=> update doc example for multinomial

extra/models/llama.py, test/test_multitensor.py
fixed `IGNORE_OOB=0 python3 examples/llama3.py --size 1B --benchmark --temperature 0`
=> hotfix llama start_pos vmax is max_context-1

test/unit/test_search.py, tinygrad/engine/search.py
factor might not be a integer if input global_size has an odd number in it
=> fix odd number in get_test_global_size

examples/whisper.py, test/models/test_whisper.py
Im not sure exactly what the `+5` in 
```python
self.max_self_attn_cache_len = self.max_tokens_to_sample * 2 + 5  # roughly prompt + start toks + max_tokens_to_sample
``` 
Is supposed to be, but  I think it was maybe a workaround for Variable being off by one
=> Fix whisper OOB

examples/vits.py
google drive points to a warning page that does not work
=> update vits vctk model to use download from huggingface

extra/huggingface_onnx/run_models.py
Fixes the bug chenyu is hitting in #10435 
I was mostly using debug after downloading the models initially so I never hit this bug D:
=> fix run huggingface onnx debug

tinygrad/viz/index.html, tinygrad/viz/js/index.js, tinygrad/viz/js/worker.js, tinygrad/viz/serve.py
https://github.com/user-attachments/assets/99fc98d8-84a7-41c9-9e30-a95c503a9de1
=> viz: clicking a KERNEL node can open codegen rewrite

.github/workflows/benchmark.yml
this crashed for me on onnx parser pr but seems fine for the author. see if ci mac is fine
=> add one huggingface_onnx test to mac benchmark ci

.github/workflows/test.yml, examples/sdxl.py, test/unit/test_kernelize.py, tinygrad/engine/grouper.py
We have to fix the recursion depth issue in graph_rewrite before merging this.
=> move view left to the outer graph prereqs + testing

tinygrad/runtime/graph/cpu.py, tinygrad/runtime/ops_cpu.py, tinygrad/runtime/ops_llvm.py, tinygrad/runtime/ops_remote.py
Reverts tinygrad/tinygrad#10743
Ugh, the DSP needs it. There's 0 tests in CI for this, and there should be
=> Revert "remove cpu graph, it's different from the others"

extra/amdpci/am_smi.py
helps for stucked processes during beam + retries
=> am_smi: kill process group

tinygrad/tensor.py, tinygrad/uop/mathtraits.py
similar to https://github.com/tinygrad/tinygrad/pull/10741
=> move idiv to MathTraits [pr]

tinygrad/runtime/ops_amd.py
=> default AMD_LLVM=1

.github/workflows/mlperf.yml
similar pf on llvm19 and fine on 20
=> AMD_LLVM=0 for resnet cron

extra/onnx.py
introduces a noop change to add function `ensure_supported_dtype` to notify user when a fallback dtype happens
=> Add fallback dtype to ONNX

tinygrad/codegen/__init__.py, tinygrad/codegen/expander.py, tinygrad/codegen/lowerer.py, tinygrad/uop/__init__.py, tinygrad/viz/serve.py
Was used for DSP, tons of rewrites...
Just process replay failing, should give these a quick look. Not worth keeping, can always bring it back but I think it'll be cleaner in testgrad.
=> remove IGNORE stuff

.github/workflows/test.yml, test/test_remote.py, tinygrad/helpers.py, tinygrad/runtime/graph/remote.py, tinygrad/runtime/ops_remote.py
to test locally:
`PYTHONPATH=. PORT=6667 DEBUG=1 python tinygrad/runtime/ops_remote.py`
`PYTHONPATH=. PORT=6668 DEBUG=1 python tinygrad/runtime/ops_remote.py`
`PYTHONPATH=. REMOTE=1 HOST=127.0.0.1:6667*4,127.0.0.1:6668*4 GPUS=8 python examples/beautiful_mnist_multigpu.py`
=> Remote multihost (basic)

examples/mlperf/model_train.py
training with half BS and GRADIENT_ACC_STEPS=4 https://wandb.ai/chenyuxyz/MLPerf-BERT/runs/kh4fijkx/overview
=> bert grad accumulation

tinygrad/runtime/graph/remote.py, tinygrad/runtime/ops_remote.py
https://github.com/tinygrad/tinygrad/pull/10601#issuecomment-2985624147
I personally don't see how that is a good standalone pr, but whatever
=> Remote transfer on src

examples/so_vits_svc.py
i added os as it was missing and replaced download file with fetch from helpers
=> small fix replacing download_file with fetch

tinygrad/tensor.py
clarify and remove some flatten and squeeze/unsqueeze
=> simplify logcumsumexp

test/unit/test_viz.py, tinygrad/engine/realize.py, tinygrad/uop/ops.py, tinygrad/viz/serve.py
ProgramSpec is a drop-in replacement for all the VIZ features.
=> viz: remove Kernel check [pr]

tinygrad/nn/optim.py
one more flag
testing training bert on mi300x and red box with OPTIM_DTYPE=half
=> OPTIM_DTYPE to specify dtype for optim params

tinygrad/viz/index.html, tinygrad/viz/js/index.js
Sharing infra with the click handler. Looks like this:
=> viz: show time taken on hover

test/unit/test_tensor_uop_representation.py
These comments can update to match new tinygrad.
=> update test_tensor_uop_representation comments [pr]

docs/tensor/elementwise.md, extra/torch_backend/backend.py, test/test_ops.py, tinygrad/tensor.py
~~also updated sigmoid to use exp directly~~
=> Tensor.logsigmoid

tinygrad/viz/js/index.js
https://github.com/microsoft/vscode-docs/blob/main/docs/configure/command-line.md#opening-vs-code-with-urls
=> fix viz vscode link on windows

examples/mlperf/lr_schedulers.py, test/external/external_test_optim.py
@wozeparrot can you help me review this too? i could not find the exact reference on if first one lr should be 0 or not, but i don't like waste one epoch so it starts with non-zero lr.
=> CosineAnnealingLRWithWarmup

test/test_ops.py, tinygrad/tensor.py
separate when Y is prob vs indices and check shapes for indices. also fix higher dim cases
=> improve Tensor.cross_entropy

extra/torch_backend/backend.py, test/test_ops.py
build target and weight tensors outside so it tests backward too.
=> improve test_nll_loss

examples/mlperf/model_train.py
work in progress. now it can overfit small examples and vram roughly matches
=> llama3 mlperf train

examples/mlperf/model_train.py
=> bert grad clipping start with const 0

tinygrad/kernelize/kernelize.py, tinygrad/viz/index.html, tinygrad/viz/js/index.js
replaced with per device Buffer viz https://github.com/tinygrad/tinygrad/pull/10960
=> viz: remove per schedule renderMemoryGraph

extra/onnx.py, test/unit/test_helpers.py, tinygrad/helpers.py, tinygrad/tensor.py
=> is_numpy_ndarray helper [pr]

.github/workflows/test.yml, extra/optimization/generate_dataset.sh
it generates a downloadable zip. and there's no way to make it not a zip https://github.com/actions/upload-artifact/issues/426
=> generate kernel dataset and upload artifact

test/unit/test_uop_symbolic.py, tinygrad/uop/symbolic.py
Also raise an error when dividing by zero
=> Fix infinite rewrite on division by zero 

tinygrad/shape/view.py
Reverts tinygrad/tinygrad#11075
Hmm, SYM=1 gives the wrong answer with this, going to revert until there's a test.
=> Revert "Fix division by zero in add views"

test/test_nn.py, test/test_ops.py
=> move sparse_categorical_crossentropy to test_ops

docs/tensor/movement.md, test/test_ops.py, tinygrad/tensor.py
also updated Tensor.eye to use it
=> Tensor.diag

extra/torch_backend/backend.py, test/test_ops.py
#10509 
and found a bug in svd @kevvz fyi
=> pipe linalg svd to torch

test/test_ops.py, tinygrad/tensor.py
only implemented main diagonal for 2-D tensors. with diagonal and qr, we can get determinant
=> Tensor.diagonal

tinygrad/kernelize/grouper.py, tinygrad/kernelize/kernelize.py, tinygrad/uop/ops.py, tinygrad/viz/serve.py
I've decided to try smaller and less ambitious refactor bounty first.
=> [pr] Unify CONTIGUOUS and GBARRIER

test/external/external_test_onnx_backend.py
these failed on master with latest onnx
=> skip some new onnx tests

test/unit/test_uop_vmin_vmax.py, tinygrad/uop/ops.py
fix #11146 
when you root caused a bug and found the TODO...
=> don't narrow range of CAST on bool/unsigned

README.md
don't call rand and numpy to show that it's indeed one kernel
=> update the README matmul example

tinygrad/viz/js/index.js
Linearly scaling the height based on the max across all devices:
beautiful_mnist:
`VIZ=1 PYTHONPATH=. python test/test_multitensor.py TestMultiTensor.test_allreduce_naive`
`VIZ=1 PYTHONPATH=. python test/test_multitensor.py TestMultiTensor.test_allreduce_ring`
=> viz: absolute scaling of memory graph

tinygrad/opt/heuristic.py
IMAGE=2 test/test_ops.py works now
=> remove a TODO prod(k.full_shape[k.first_upcast:])

tinygrad/opt/heuristic.py
removed one condition that's always true
=> clean up hcopt [pr]

tinygrad/opt/heuristic.py
don't need all upcast candidates to be upcast-able, only check the actual one
looks like it's mostly no-op
=> update float4 condition in hcopt

tinygrad/opt/heuristic.py
start to use AxisType for conditions
=> shave more hcopt [pr]

test/test_linearizer.py, tinygrad/opt/heuristic.py, tinygrad/opt/kernel.py
decomp to shape_len and first_upcast to get the last upcast-able dim
=> remove Kernel.full_unupcasted_shape [pr]

.github/workflows/test.yml, examples/openpilot/compile3.py, tinygrad/opt/heuristic.py
keep the only perf relevant conditions and the rest is handled by try except
=> simpler grouptop in hcopt

tinygrad/opt/heuristic.py
GLOBAL+LOCAL for upcast
GROUP_REDUCE+REDUCE for unroll
=> clean up image upcast in hcopt [pr]

tinygrad/engine/jit.py, tinygrad/helpers.py
For easier override in tests for #9746
=> JIT_BATCH_SIZE is a ContextVar

test/external/external_test_simple_tokenizer.py
=> testing SimpleTokenizer against OASST1

tinygrad/opt/kernel.py
=> remove hasattr(self, 'axis_types') checks in dims property [pr]

tinygrad/opt/heuristic.py, tinygrad/opt/kernel.py
=> Kernel.axes_of helper [pr]

tinygrad/opt/kernel.py, tinygrad/opt/search.py
LOCAL goes to the last of (GLOBAL+LOCAL)+1
GROUP goes to right before first REDUCE
=> remove first_reduce used for locate real_axis [pr]

tinygrad/runtime/support/nv/ip.py
=> nv: print rpc msg with DEBUG>=3

extra/backends/rdna.py, test/test_linearizer.py, tinygrad/opt/kernel.py
=> insert_before -> insert_at [pr]

tinygrad/opt/kernel.py
ensure output of real_axis is always valid
=> move check axis < shape_len to real_axis [pr]

tinygrad/runtime/support/nv/ip.py, tinygrad/runtime/support/nv/nvdev.py
=> nv: graceful shutdown to cold state

test/test_linearizer.py, tinygrad/opt/kernel.py
=> remove Kernel.local_dims [pr]

docs/developer/hcq.md, test/test_hcq.py, tinygrad/runtime/graph/hcq.py, tinygrad/runtime/ops_amd.py, tinygrad/runtime/ops_nv.py, tinygrad/runtime/ops_qcom.py, tinygrad/runtime/support/hcq.py
Refactor goals:
* add peer_groups for devices. For now logic is the same as it was
=> hcq: refactor into peer_groups

test/test_linearizer.py, test/test_quantize_onnx.py, tinygrad/opt/kernel.py
upcast goes to end of global+local+upcast
infinite loop in codegen rewrite...
=> move upcast before reduce

tinygrad/viz/serve.py
Gonna use this for the GPU counters too
=> viz: factorize event stream

tinygrad/runtime/support/am/amdev.py
#11326 changes might not be compatible for warm boots, so bump
=> am: bump version after mm changes

.github/workflows/test.yml
seems to be the one crashing, also remove -n=auto for that
=> isolate test/external/external_test_am.py

tinygrad/uop/ops.py
=> use next instead of full list in UOp._device [pr]

extra/onnx.py
removed a type ignore and one error code skip
=> minor onnx Gather cleanup

tinygrad/viz/index.html, tinygrad/viz/js/index.js, tinygrad/viz/serve.py
prep for GPU counter tracer,
current view with PROFILE=2:
=> viz: tabulate runtime stats

tinygrad/schedule/kernelize.py, tinygrad/uop/ops.py
=> remove UOp.valid method [pr]

test/test_search.py, tinygrad/opt/search.py
it should check against pre real_axis axis in actions, not real_axis.
=> fix search dedup

tinygrad/viz/js/index.js
Can also start using some of the chromatic scales for the assembly view UI
https://d3js.org/d3-scale-chromatic/sequential#interpolateTurbo
=> viz: refactor to color scheme

tinygrad/viz/index.html, tinygrad/viz/js/index.js, tinygrad/viz/serve.py
I propose sharing this with DEBUG=2 using a method in Estimates. `def format(dur:float, var_vals:dict|None=None) -> str`
=> viz: add flops / mem bw to device programs

tinygrad/dtype.py, tinygrad/uop/symbolic.py
b.cast(a).cast(b) -> b if a preserves all values in b
=> generic double cast folding

tinygrad/nn/__init__.py, tinygrad/nn/optim.py, tinygrad/tensor.py
=> remove broken paperswithcode links in doc

test/test_tensor.py, tinygrad/codegen/__init__.py, tinygrad/engine/realize.py, tinygrad/opt/__init__.py, tinygrad/uop/ops.py
Reverts tinygrad/tinygrad#11516
=> Revert "optimize in rewrite"

test/test_schedule.py, test/test_softmax_fusion.py, test/unit/test_uop_spec.py, tinygrad/opt/kernel.py, tinygrad/uop/spec.py
Reverts tinygrad/tinygrad#11547
=> Revert "fix mismatch reduce"

tinygrad/viz/index.html
=> viz: align-center checkbox

test/test_ops.py, tinygrad/tensor.py
=> support threshold in Tensor.softplus

.github/workflows/benchmark.yml
=> skip AM ResNet50 benchmark

.github/workflows/benchmark.yml
not sure what to do with the 0.9.7 ones with IMAGE=2 and validate
=> benchmark openpilot 0.9.9

tinygrad/viz/js/index.js, tinygrad/viz/serve.py
Mainly to make the UI more generic, also simplified the llvm-mca loop a bit.
=> simpler disassembly table spec

tinygrad/viz/js/index.js
When area for memory graph is 0 it doesn't have any more work to do.
=> viz: factor out memory graph render

examples/beautiful_mnist.py
gather is fast now. there's a conv/bw kernel that only gets fast with BEAM, but whole thing runs < 5 seconds now regardless
=> small beautiful_mnist update

test/test_ops.py, test/test_schedule.py, tinygrad/tensor.py
list index does not need to be normalized in tensor
=> list indexing can normalize in python

test/test_ops.py, tinygrad/tensor.py
=> support int Tensor pow to const non-negative int

test/test_edgecases.py, tinygrad/tensor.py
=> assign should broadcast input tensor

test/unit/test_uop_symbolic.py, tinygrad/uop/symbolic.py
Can drop sign of divisor in cmod
=> Take sign out of mod

extra/onnx.py
we can drop the double where and abs since we know which ranges the inputs map into
=> simplify onnx cubic

examples/mlperf/model_train.py
prevents memory spike on device 0
=> llama MP realize weight after shard

tinygrad/viz/js/index.js
from #11639, it's really just a height.
Timeline events have a fixed height, data with a y axis (eg. memory) scales by the global peak y. So visually the memory graph with range 0-100MB is smaller than 0-1GB.
=> viz: s/area/height

tinygrad/renderer/llvmir.py
Reverts tinygrad/tinygrad#11715
So the BEAM issue was probably the reduce change, will put this back. It's not exactly the fix, but it's better
=> Revert "Revert "fix the misused cast in amd llvm tc""

tinygrad/tensor.py
=> minor Tensor.triu cleanup

test/test_dtype_alu.py
remove the check that looks into schedule, only test if output matches
=> clean up test_dtype_alu

tinygrad/codegen/gpudims.py, tinygrad/codegen/lowerer.py
Reverts tinygrad/tinygrad#11809
=> Revert "remove KernelInfo from gpudims"

test/unit/test_uop_symbolic.py, tinygrad/uop/symbolic.py
Reverts tinygrad/tinygrad#11811
=> Revert "Better div nesting"

test/unit/test_viz.py, tinygrad/viz/js/index.js, tinygrad/viz/serve.py
The server only sends the raw `alloc` and `free` events. This makes the total payload size 10-20% smaller:
|                   | All events | Master payload | Branch payload 
|---------------------------|-------------|---------------------|----
| beautiful_mnist   | ~16K      | 750 kB           | 664.4 kB    
| examples/olmoe.py         | ~54K      | 1.48 MB           | 1.34MB   
| llama 1B model_train   | ~24M  | 679.5 MB           | 518.26 MB
=> viz: memory layout in client side

tinygrad/viz/index.html, tinygrad/viz/js/index.js, tinygrad/viz/js/worker.js
This way it's easy to dynamically toggle styles for UOp nodes.
=> viz: move rect styles to classes

tinygrad/viz/js/index.js
It's  O(|E|)! https://github.com/dagrejs/graphlib/blob/0675d26bd5b4f5cae60303c08841797728f16d70/index.d.ts#L211
We have something similar in server for .toposort().
=> viz: g.edges() once

tinygrad/viz/index.html, tinygrad/viz/js/index.js, tinygrad/viz/js/worker.js, tinygrad/viz/serve.py
This looks like a successor to the edge count tags in master.
=> viz: add UOp ports to edges

test/unit/test_dtype_spec.py, tinygrad/dtype.py
use scalar itemsize, this was giving very high min/max
=> fix vec dtype _min_max

test/test_arange.py
=> remove skip PTX in test_arange

test/test_dtype_alu.py
=> add Tensor.maximum in test_dtype_alu

test/test_dtype_alu.py
=> lower universal_test_unary cos domain

tinygrad/codegen/opt/heuristic.py, tinygrad/codegen/opt/postrange.py
hmm, this should be a NOOP, but it isn't
=> only run hcopts once

tinygrad/tensor.py
Mypy type narrowing seems bugged
=> add type: ignore in tensor.py

test/test_tiny.py
=> enable IMAGE for test_mnist and test_mnist_backward

tinygrad/codegen/opt/search.py
seems incorrect, disable by default now
=> default BEAM_PADTO to 0

test/unit/test_shapetracker.py, tinygrad/uop/symbolic.py
Reverts tinygrad/tinygrad#12104
=> Revert "Simplify valid in symbolic"

tinygrad/viz/index.html, tinygrad/viz/js/index.js
=> viz: light up children

extra/to_movement_ops.py, extra/torch_backend/backend.py, setup.py, test/test_ops.py
support _reshape_alias. something is wrong with one case of unfold
=> update torch 2.8

test/unit/test_device.py
=> increase test_module_runs

examples/mamba.py
This change adds Top-K sampling, resolving the # TODO: topk comment.
A new --top_k argument can be used with --sample flag, it constrains the token selection to the k most probable candidates.
The new behaviors with `k=5` and `k=50`:
First-time contributor here. Thanks for the guidance in advance!
=> Implement Top-K sampling in Mamba example

test/unit/test_device.py
=> bump test_module_runs to 30 seconds

.github/workflows/test.yml
=> split RANGEIFY ci

tinygrad/renderer/llvmir.py
Reverts tinygrad/tinygrad#12194
=> Revert "Revert "more llvm intrinsics""

.github/workflows/test.yml, test/test_arange.py
simple test case to catch wrong reduce const folding. also clean up the old arange complexity test
=> add arange cat arange test

tinygrad/uop/symbolic.py
casued by 
`0 // uint_with_vmin_of_zero`
=> fix 0//0 infinite rewrite in rangeify onnx

.github/workflows/test.yml
all except test_resize_upsample_scales_cubic_align_corners_cpu runs
=> test CL=1 RANGEIFY=1 onnx

.github/workflows/test.yml, test/test_ops.py
=> test case to sum twice in different order

.github/workflows/test.yml, test/unit/test_winograd.py
=> RANGEIFY winograd test

.github/workflows/test.yml, test/test_schedule.py, tinygrad/schedule/rangeify.py
Reverts tinygrad/tinygrad#12308
=> Revert "Bufferize early, fix "children not making progress" on big graphs"

.github/workflows/test.yml, tinygrad/schedule/rangeify.py
Reverts tinygrad/tinygrad#12344
broke stable diffusion
```
File "/Users/chenyu/code/tinygrad/tinygrad/codegen/late/linearize.py", line 240, in finalize
lst = sorted(dedup(sink.src), key=lambda x: x.tuplize) + list(sink.arg.lst)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'InvalidType' and 'float'
```
=> Revert "rangeify reduce const folding"

.github/workflows/test.yml
=> don't skip rangeify test_instancenorm_3d

.github/workflows/test.yml, tinygrad/renderer/cstyle.py
vector_size don't support boolean element
=> rangeify: fix test_scatter_reduce

test/unit/test_conv.py
=> atol in test_two_binops_no_rerun

test/unit/test_device.py
=> increase timeout in test_module_runs

.github/workflows/test.yml
fails with RANGEIFY `RuntimeError: children not making progress`
=> add null bert training test in ci

test/test_ops.py
- **feat: skip test_masked_select**
- **feat: reason**
=> skip webgpu tests

tinygrad/apps/llm.py
fixed numerical issue in `CPU=1 RANGEIFY=1 python3 -m tinygrad.apps.llm`
=> use float for softmax in llm.py

test/external/external_test_opt.py, test/test_uop_graph.py, tinygrad/helpers.py, tinygrad/uop/spec.py
z3 can get very slow with RANGEIFY, also update some kernel numbers to what it is
=> default IGNORE_OOB=1

test/helpers.py, test/test_multitensor.py, test/test_schedule.py
triggers `children not making progress` with RANGEIFY
=> multi test case for sharded ring allreduce

.github/workflows/benchmark.yml, .github/workflows/test.yml, pytest.ini
padded tc is already slow, rest are slow with rangeify (correct if run locally)
=> skip slow benchmarks

.github/workflows/test.yml
=> smaller LLAMA_LAYER in Test llama 3 training
