tinygrad/tinygrad

test/unit/test_uop_symbolic.py
tinygrad/ops.py

only do if at least one branch is const, so total alu won't increase

alu(c?t0:f0, c?t1:f1) -> c?alu(t0,t1):alu(f0,f1)

---

tinygrad/engine/lazy.py
tinygrad/engine/schedule.py

Nothing above schedule, (eg. tensor/multi) should use/mutate these refs, right?

test: late buffer ref (only if it's scheduled)

---

tinygrad/ops.py

prereq for delete_lazy, there won't be any DEVICECONST. 
CONST starts as a VIEW of a BUFFER. (lazy/uop creates it, tensor uses it)
VIEW(BUFFER, CONST) gets rewritten to VALID (schedule creates it, codegen uses it)
once it's indexed it collapses to a CONST. (codegen unchanged.)

const_like can return a valid [pr]

---

test/unit/test_uop_symbolic.py
tinygrad/ops.py

Combined div and mod folding, this now also performs the same optimizations as #7887 for div folding.
This fixes  #6935 and also some cases of #7958
With `split_rem=True` this would fix #7958 fully as it makes the treatment of the remainder more consitent between mod and idiv. I added it as a flag to make it easier to play around with and see the difference. 
Im just fuzzing this a little a little longer before Ill mark as ready

Improved div folding

---

tinygrad/engine/lazy.py
tinygrad/engine/schedule.py

ASSIGN is wrong: `test/test_symbolic_ops.py TestSymbolicOps.test_attention_pos_0_sz_0`
uop actually has this assert in the spec. The fix is unrelated to delete_lazy. Failing there:
We used to have something asserting ASSIGN src[0] is base, but I don't think it actually matters. This might be the more principled way. It also lets us delete that arg on ASSIGN.

lazy srcs shape mistmatch assert + fix ASSIGN [pr]

---

.github/workflows/test.yml
test/test_dtype_alu.py
test/test_ops.py

On Ubuntu WebGPU uses Vulkan. Some nan/inf behavior differs from Metal, I skipped as narrowly as possible. Because of an X-display issues the efficientnet e2e test have been moved to the Metal runner, it increases the metal test runtime by about 10%.

Move WebGPU tests to Ubuntu runner

---

test/test_const_folding.py

test_const_folding.py is pretty good already, this adds some additional ones for the edge cases I ran into for #7979.
`test_bool_zero_max` exists for asserting correctness of UPat orders.
`test_zero_size_ops` for zero folding for non-const source, that only had coverage for SUM.
Though neither torch nor numpy give MAX an identity element.

reduce folding simple tests [pr]

---

.github/workflows/test.yml
extra/export_model.py
test/testextra/test_export_model.py

We always exported inputs/outputs as `Float32Array`s regardless of model input/output dtypes. This PR fixes it, and adds a test for this export behavior.

Proper dtypes for input/output of exported WebGPU model

---

test/unit/test_uop_symbolic.py
tinygrad/ops.py

pattern needed for "fix divmod folding" bounty
The other test case is still failing because a uop like `(y + (x//c)*c) + x%c` doesn't match. Maybe needs some thinking about how add chains should be matched.

bounty: Add pattern for div mod recombine with gcd

---

test/unit/test_uop_symbolic.py
tinygrad/ops.py

for the cases that the we don't know the exact bounds, we might still know the sign. with this, can remove some resolve for symbolic shapetracker

improve idiv _min_max

---

extra/export_model.py
test/testextra/test_export_model.py

Although there is no dtype for `u8`, `u16`, etc. in `wgsl` (we map`u8` to `u32`, `i8` to `i32`, etc.), the corresponding buffer exists in JavaScript. So, when exporting a model, we can construct a perfectly matching `TypedArray`.
`u8 -> Uint8Array, i8 -> Int8Array`

Use matching JS TypedArray when handling exported buffer

---

examples/webgpu/stable_diffusion/compile.py
tinygrad/renderer/wgsl.py

While working on SD compile simplification I found that it errors out at decode step in chrome:
It was because when casting the output to `uint8`, atomics are generated in webgpu. In `wgpu` lib we got away with loading atomic types normally, but as-per spec we should use `atomicLoad` builtin.
I'll setup a chrome test suite to catch these kind of errors. Eventually we should just switch to dawn. `wgpu` is not mature enough yet.

Use atomicLoad builtin when loading atomic type

---

test/test_schedule.py
test/test_subbuffer.py
tinygrad/device.py
tinygrad/engine/lazy.py

this can't stay in lazy because ops.py needs to import it.

move view_supported_devices to device [pr]

---

examples/webgpu/efficientnet/index.html
test/web/test_webgpu.js

efficientnet `index.html` was in root examples, should be in its folder, as the other two webgpu examples

Move efficientnet webgpu example

---

tinygrad/codegen/kernel.py

it's actually the same post order DFS as the toposort implementation

remove ordered parents, seems like dead code [pr]

---

test/unit/test_verify_ast.py
tinygrad/codegen/kernel.py

prereq for removing that const_like not returning CONST. blocking #8068.

maskless const can lower without valid, p1 [pr]

---

test/test_ops.py

torch defaults to int64 but we care more about int32 anyway. remove skipped tests due to int64 not supported

default tensors to int32 in test_ops

---

tinygrad/nn/state.py

`pickle`, `zipfile`, `tarfile` all support usage with IO instead of filename.
Tested by `test/unit/test_disk_tensor.py:TestTorchLoad`.

torch_load with Tensors

---

test/test_linearizer.py

It should've indexed gidx0, I think the lowerer expects CONST folding?
This started failing in delete_lazy, but right now because lazy folds these ops it's a hidden bug.

failing test for const folding breaking indexing [pr]

---

test/test_ops.py

was spamming some avg pool 3D tests and found a failure edge case
This goes down the `sum` code path for avg pool and is only encountered with 3D.
apparently this hits this assert in linearizer:
`assert all(len(x.src) == 0 and x.op not in {Ops.BLOCK, Ops.BLOCKSTART, Ops.BLOCKEND, Ops.BLOCKFORK} for x in _uops)`
with `print([x.op for x  in _uops])` -> `[<Ops.BLOCKFORK: 9>, <Ops.BLOCKEND: 10>, <Ops.DEFINE_GLOBAL: 14>, <Ops.CONST: 62>, <Ops.CONST: 62>, <Ops.CONST: 62>, <Ops.CONST: 62>, <Ops.CONST: 62>, <Ops.CONST: 62>, <Ops.CONST: 62>, <Ops.CONST: 62>, <Ops.CONST: 62>, <Ops.CONST: 62>, <Ops.CONST: 62>, <Ops.CONST: 62>, <Ops.CONST: 62>, <Ops.CONST: 62>, <Ops.CONST: 62>]`
with `NOOPT=1` it passes

add avg pool 3d failure test

---

test/test_schedule.py
test/unit/test_verify_ast.py
tinygrad/engine/schedule.py

This should be in the big_graph ops_folding rewrite to actually add value after the lazy deletion.
Also lowerer indexing breaks without const folding https://github.com/tinygrad/tinygrad/pull/8103.

revert VALID early folding for now

---

test/unit/test_uop_vmin_vmax.py
tinygrad/ops.py

This caused incorrect int64 indexing conversion when a var is an arg of a special.

fix var vmax when arg in special

---

test/test_ops.py
tinygrad/tensor.py

-1 is correct because 2**32-1 is not within int32 range, so in some case clang casts the whole thing into uint32
fixed #8108

fix bitwise_not for signed int

---

test/test_pickle.py

asserts no kernels run after realized unpickle. Also it should free the buffers pre unpickle.
not yet green in delete_lazy:

test_pickle_realized_tensor actually tests pickle [pr]

---

examples/webgpu/stable_diffusion/compile.py
examples/webgpu/stable_diffusion/index.html

Remove dependency on `f16-to-f32-gpu` custom WebGPU kernel based JavaScript lib, and use tinygrad generated decompression function instead.
Decreasing decode chunk size to prevent hitting max global size (see: https://github.com/tinygrad/tinygrad/issues/8043) -> doesn't affect decompression performance

Remove f16 decompression lib from SD compile.py

---

test/test_ops.py

also updated test_ops so that non-float compares with `assert_equal`. removed `test_multinomial` which is tested better in test_randomness

failed test case for int pow

---

test/test_ops.py
tinygrad/ops.py

on master it raises because it cannot truncate inf to int, which crashes valid expression like `(t > 0).where(1//t, t)`.

make //0 return 0 in python_alu

---

test/imported/test_indexing.py

If you delete 
the correctness asserts should still pass.

split scalar getitem tests into correctness and optimization [pr]

---

.github/workflows/test.yml
tinygrad/renderer/wgsl.py

Because of missing `allow_any_len=True` `cstyle` stores were generated, instead of `wgsl` style stores, such as:
`*data0[lidx0] = select(((i32(alu1))*val3),((i32(alu0))*val4),alu0);` 
This pointer syntax is not allowed in wgsl.

Fix setitem on webgpu

---

.github/workflows/test.yml

To avoid peer dependency issues when installing puppeteer, start with a clean npm cache.

Fix puppeteer install

---

.github/workflows/test.yml
test/imported/test_indexing.py
test/test_linearizer_dumb.py
test/test_multitensor.py
test/test_schedule.py
test/test_tensor.py

Runs 2x as many tests as before. Changed to blacklist style test declarations. Skipped some tests that were failing due to dtype things. (There is one skip that's because of a valid error)
Passing locally on Metal, testing if they also pass on Vulkan.

Run more WebGPU tests

---

test/test_ops.py

test beta and extreme inputs.
to pass big input, it needs to support `threshold`, which needs fix on backward that we punt until new gradient api

update test for Tensor.softplus

---

test/test_const_folding.py
test/test_lazybuffer.py
test/test_schedule.py

to keep the delete_lazy diff more minimal. The asserts mean the same thing.

assert the same things without mutating or accessing internal ops state [pr]

---

.github/workflows/test.yml
test/test_linearizer.py
tinygrad/renderer/wgsl.py

Run linearizer tests on webgpu.
Almost all passed without changes, there were 3 types of failing test cases that had to be fixed:
- missing `allow_any_len=True` on store pattern that caused `TestKernelOpts.test_padto_sum_ok` to fail
- `dtype` skips for `half`/`bfloat` tests
- exceeded `global_max` (to be handled separately, see: https://github.com/tinygrad/tinygrad/issues/8043)

Test linearizer on webgpu

---

test/test_multitensor.py

tested manual_seed and device order behavior. i initially thought the mockgpu hack would break, but it's fine because it's effectively using one device to simulate multiple devices

test multi device rand with manual_seed

---

tinygrad/helpers.py
tinygrad/runtime/ops_metal.py

instead of having sqlite / http download / metal compile to add "tinygrad" separately. also make it non-private since it's used in metal

add "tinygrad" to be part of cache_dir [pr]

---

test/unit/test_device.py
tinygrad/device.py

replace is wrong because it does not check if `:0` is at the end. use re.sub instead

fix device canonicalize for `:0` in middle [pr]

---

tinygrad/renderer/wgsl.py

- Removed `unpack_map`: All packed buffer types are now `u32`, no reason for `unpack_map`. Packed types divert to `u32`/`i32` only after loaded (sign_extension).
- `render_buf_dt` and `buf_map` are merged to one `buf_map`
No [pr] because rendered types now change for packed types.

No unpack_map in wgsl

---

examples/webgpu/efficientnet/index.html
examples/webgpu/yolov8/compile.py
examples/webgpu/yolov8/index.html
extra/export_model.py

This is a pre-req for SD compile, and in general, "multi-part" model export simplification. 
This change allows embedding multiple nets on a page. Allows both ES6-style usage (`import`), and usage on a plain `index.html` site.
Removed `getSaveTensorBuffer`s from example since that's handled inside the `net.js`. 
Weight path can now be passed in to `model.load`

encapsulate the exported WebGPU model

---

extra/onnx.py

apparently names of tensor values in a graph all have unique names
so there's no need for the many dictionaries
see: https://github.com/onnx/onnx/blob/main/docs/IR.md#names-within-a-graph

use shared model_tensor to track tensors in an onnx model 

---

test/test_gc.py

> That [UOp.toposort] cache should only be in scope for the function.
https://github.com/tinygrad/tinygrad/pull/8247#issuecomment-2543353016
However, the closure in toposort keeps a reference to the BUFFER uop [around](https://docs.python.org/3/c-api/cell.html) forever.

minimal failing test for UOp.toposort gc [pr]

---

test/test_dtype.py
tinygrad/renderer/cstyle.py

This is a less generic version of #8262 with only one of two cases of external linkage fixed and tests assuming that there is no `__truncdfhf2` in global link-map list (might not be true if something else loads an object with RTLD_GLOBAL that has it). 80% of the value for 20% of the lines
The second one (math functions like sqrtf) are harder to test for on a tight line budged because they are present in libc/libm. See the aforementioned #8262  for the simplest way i've found to do that

Fix double => half cast on clang

---

test/external/speed_v_theoretical.py

infinite loop with manual DEBUG set `DEBUG=2 python test/external/speed_v_theoretical.py -k conv`
```
File "/Users/chenyu/code/tinygrad/tinygrad/helpers.py", line 95, in __ge__
def __ge__(self, x): return self.value >= x
^^^^^^^^^^^^^^^
[Previous line repeated 4984 more times]
RecursionError: maximum recursion depth exceeded in comparison
```

hotfix DEBUG in speed_v_theoretical.py conv

---

tinygrad/runtime/support/hcq.py

Now we check signal value before raising, to solve `RuntimeError: Wait timeout: 30000 ms! (the signal is not set to 724, but 724)`.
Updates #8242

hcq better timeout handling

---

tinygrad/ops.py

The replaced rules can be applied to all associative ops including `Ops.XOR` and `Ops.MAX` as well. I have left them out to make sure there are no changes to the graph.
Can submit this separately or include in this PR, if you want this at all.

[pr] GroupOp.Associative

---

test/test_viz.py

This diff specifies a previously untested behavior of @track_rewrites.
If graph_rewrite is called outside of any @track_rewrites context, VIZ doesn't track the matches in VIZ. (This broke after i merged 8285)
But if there's an inner graph_rewrite call inside a decroated function, all of its rewrites must be tracked.

regression test viz failure when there's no tracked context

---

test/test_assign.py

This was red when I added type_verify to the scheduler. The target and new value of ASSIGN must have the same dtype.

bugfix: dtype mismatch in TestAssign.test_double_assign_alt [pr]

---

test/test_assign.py
test/test_schedule.py

This is an updated and more complete spec, replacing test_double_assign_alt.
It also isolates the current behavior of Ops.CONTIGUOUS that is the root cause of https://github.com/tinygrad/tinygrad/issues/4562.

scheduler deduping spec and asserts [pr]

---

test/test_symbolic_shapetracker.py
tinygrad/shape/view.py

something is still wrong with symbolic shape shrink, but it should not recurse forever

temp fix for symbolic shape view add [pr]

---

tinygrad/engine/schedule.py
tinygrad/ops.py
tinygrad/tensor.py

This diff splits BIND into its own concept in tensor and ops.
This enables independent progress on `CONST(VIEW(DEVICE))` and focuses that diff on natural UPat.cvar folding in the scheduler.
BIND can go from `VIEW(DEVICE, BIND)` to a new spec in a different diff, focusing on ASTs like:
and answering questions like how do we attach a DEVICE to this BIND?
```
vv = UOp.variable("a", 0, 10).bind(1)
a = Tensor(vv)
```

asserts to prepare for Tensor BIND proposal [pr]

---

test/test_schedule.py
test/test_uops.py
tinygrad/engine/schedule.py

more work towards splitting BIND from CONST, also updates fragile tests to use stable Tensor / UOp APIs.

BIND in tensor_uop_spec + cleanups [pr]

---

test/test_uops.py
tinygrad/ops.py
tinygrad/viz/serve.py

repro:
```
VIZ=1 python3 test/test_setitem.py TestSetitem.test_jit_setitem_variable_offset
```
kernel `http://localhost:8000/kernels?kernel=9&idx=0`
printing DEVICE arg was wrong too.
also, can we fix the Ops repr? that hack for REDUCE_AXIS is fragile.

hotfix: string repr of arg in viz and print [pr]

---

test/test_schedule.py
test/unit/test_tensor_uop_representation.py
tinygrad/engine/schedule.py
tinygrad/ops.py

This net loss of lines is just from refactoring of the existing scheduler and ops logic.
It also enables deleting all the elementwise CONST folding rules next.

CONST(VIEW(DEVICE)) [pr]

---

tinygrad/runtime/ops_disk.py
tinygrad/runtime/ops_hip.py
tinygrad/runtime/ops_llvm.py
tinygrad/runtime/ops_metal.py

it's not needed if we move the Device before Program and Allocator, which need Device.
not updating hcq because it has a lot more stuff, and CLDevice requires CLDevice

remove from __future__ import annotations from runtimes [pr]

---

tinygrad/codegen/uopgraph.py

can just import. 3 TYPE_CHECKING left. 2 are about python 3.12 and format str and those are fine. the last one is ops <-> device and shapetracker

unneeded TYPE_CHECKING in uopgraph.py [pr]

---

extra/models/mask_rcnn.py

**Overview**
This PR fixes a small issue I found when I was testing the MaskRCNN MLPerf eval script as I was working on the RetinaNet training script. On `master`, MaskRCNN is not explicitly checking if `x` is not `None` which results to the following error:
```bash
File "/home/flata/tinygrad/examples/mlperf/model_eval.py", line 252, in <module>
globals()[nm]()
File "/home/flata/tinygrad/examples/mlperf/model_eval.py", line 229, in eval_mrcnn
batch_result = compute_prediction_batched(batch_imgs, mdl)
File "/home/flata/tinygrad/examples/mask_rcnn.py", line 197, in compute_prediction_batched
predictions = model(image)
File "/home/flata/tinygrad/extra/models/mask_rcnn.py", line 1264, in __call__
x, result, _ = self.roi_heads(features, proposals)
File …
```

Explicit tensor check on MaskRCNN

---

test/unit/test_view.py

currently it behaves differently depends on first view somehow

test case view from an empty view

---

test/test_const_folding.py
test/test_schedule.py
test/unit/test_tensor_uop_representation.py
tinygrad/engine/schedule.py
tinygrad/ops.py

This is easy after #8353.
First step towards making it possible to reason about every UOp representation in Tensor purely from its parents.
UPat.cvar() matches this! Next is deleting all the symbolic custom rules, see how [simple](https://github.com/tinygrad/tinygrad/pull/8389/files#diff-5736814df0b2c07a42d5c1bfef6b5aa5635ce18043f4aa030e21768694259ca3L460-R464) `is_unrealized_const` is now.

fully local tensor const representation: CONST(VIEW(DEVICE)) [pr]

---

test/test_schedule.py
tinygrad/engine/schedule.py
tinygrad/ops.py

sadly we can't part ways with `is_unrealized_unmasked_const` yet, tensor.py and multi use it and *GroupOp.Movement can exist on top of a CONST, we only remove_movement_ops in the scheduler.

delete is_unrealized_const, it's just CONST [pr]

---

tinygrad/engine/schedule.py
tinygrad/ops.py

`simplify_reduceop` stays even after `symbolic+ops_folding` since it's folding shape changing ops.
`const_arg` is simple, self is either GroupOp.Movement(CONST) or CONST(). No more VIEW with len(src) == 2 having a different meaning.

a few more UPat.var -> UPat.cvar in the scheduler [pr]

---

test/test_ops.py

vals default loads as int32 now in test_ops

remove explicit np.array and np.int32 in test_div_int [pr]

---

test/mockgpu/driver.py

pre-commit started failing after #8396:
```
ruff.....................................................................Failed
- hook id: ruff
- exit code: 1
test/mockgpu/driver.py:80:13: RUF018 Avoid assignment expressions in `assert` statements
|
78 |                   st_blksize=4096, st_blocks=0, st_atime=0, st_mtime=0, st_ctime=0):
79 |     fmt_string = 'QQQIIIQQiQqqq'
80 |     assert (ssz:=struct.calcsize(fmt_string)) == 96, f"{ssz} != 96"
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ RUF018
81 |     return struct.pack(fmt_string, st_dev, st_ino, st_nlink, st_mode, st_uid, st_gid,
82 |                        st_rdev, st_size, st_blksize, st_blocks, st_atime, st_mtime, st_ctime)
|
```

fix pre-commit ruff error [pr]

---

.github/workflows/test.yml
test/test_image_dtype.py
test/test_schedule.py
tinygrad/engine/schedule.py
tinygrad/ops.py

symbolic_simple replaces all the existing elementwise ops folding rules in the scheduler.
It also allows for collapsing `float32 -> CAST(imagef) -> STORE` to the same Buffer.
The new behavior requires `.contiguous()` if the user actually wants to create the image Buffer right after cast:
`float32 -> CAST(imagef) -> STORE` does not allocate memory.
`float32 -> CAST(imagef) -> CONTIGUOUS -> STORE`, allocates a new Buffer.
The master implementation for `image_conv2d` [does this internally](https://github.com/tinygrad/tinygrad/blob/6bb54eb53238b70d0db219fdb4e94af35f7e87b6/tinygrad/tensor.py#L3818-L3820).

add symbolic_simple to the scheduler [pr]

---

examples/conversation.py
examples/vits.py
tinygrad/ops.py

Fixes 2 issues when trying to run conversation example for the first time:
1. `NotImplementedError: mode=1 is not supported` from a signature change to Tensor.pad
2. `AttributeError: 'Tensor' object has no attribute '_slice'` which looks to be removed in preference of Tensor.pad and shrink

Fix examples/conversation.py 

---

test/unit/test_helpers.py
tinygrad/helpers.py

raise RuntimeError instead of assert, and update all the skipped test cases

update TestContextVars for recreation [pr]

---

test/unit/test_helpers.py
tinygrad/helpers.py

instead of having a class var for whole stack, store the old context in each Context.
also updated a test that ContextVar created in Context is not being cleared after the Context block

simpler helpers.Context [pr]

---

test/test_viz.py
tinygrad/viz/serve.py

const can have some rewrites (eg. unmasked VIEW(CONST(VIEW)) -> CONST(VIEW+VIEW)) but because it's nodeless, VIZ shouldn't try to highlight anything in the graph.
Currently in master there's this extra square:
There shouldn't be anything:

viz early serialize to json + don't viz rewrites on const [pr]

---

test/test_const_folding.py
test/test_multitensor.py
test/test_schedule.py
tinygrad/multi.py
tinygrad/ops.py

The hack in copy_to_device can't stay. It doesn't belong in ops.
This diff includes the spec for rewriting `COPY(CONST) -> CONST`, as it exists in ops_folding.
The extra check for "is const" in ops only exists for multi. Sadly multi calls `contiguous` on all shards:
```
return MultiLazyBuffer([lb if lb.is_unrealized_unmasked_const() else lb.contiguous(allow_buffer_view=False) for lb in sharded_lbs], axis)
```
The scheduler respects contiguous and will dutifully store the thing you call contiguous on.
See how if we delete "early const folding" in copy_to_device, this contiguous prevents further folding:
vs if it was just `return MultiLazyBuffer(sharded_lbs, axis)` all MUL 0s would fold until we end up with a NOOP:

const copy folding spec + multi.py behavior [pr]

---

tinygrad/codegen/kernel.py
tinygrad/engine/search.py
tinygrad/renderer/__init__.py
tinygrad/renderer/cstyle.py

**New approach** 
Avoids having to swizzle output as the correct swizzle for the output is constructed through kernel opts.
**Overview**
The refactor focuses primarily on the **implementation** side of tensor cores (`TC`) rather than over their abstraction, as George mentioned. While an abstraction refactor could align with the kernel OptOps refactor into pattern-matching (`PM`) rules, this current work keeps tensor cores clean. It addresses:
1. Complex thread access patterns required for specific backends.
2. Simplifying support for new TC shapes.
3. Constructing output swizzles through kernel opts.
4. Use the swizzle from the docs.
> By `thread access pattern` I mean the elements of the tensor core each collaborating thread is in charge of loading (from `A` and `B`) and storing …

Ordered tc kernel opts

---

test/test_schedule.py
tinygrad/engine/schedule.py

Ideally all scheduler side-effects should be done as close to when we return the `list[ScheduleItem]`.
also, EMPTY needs a ShapeTracker in sources at the very least.

scheduler refactors and renames from the buffer_shape branch [pr]

---

docs/abstractions2.py
examples/handcode_opt.py
examples/llm.c/export.py
extra/gemm/tvm_gemm.py
extra/hip_gpu_driver/test_pm4.py
test/external/external_test_hcq.py
test/external/external_test_nv.py
test/external/fuzz_graph.py
test/test_conv_shapetracker.py
test/test_dtype_alu.py
test/test_fusion_op.py
test/test_graph.py
test/test_hcq.py
test/test_lazybuffer.py
test/test_linearizer.py
test/test_multitensor.py
test/test_pickle.py
test/test_schedule.py
test/test_search.py
test/test_tensor.py
test/test_uops.py
test/test_uops_stats.py
test/test_winograd.py

I think this API is cleaner for tensors, also they need to get cleaned up from the context once UOp mutability is gone.

create_schedule([x.lazydata]) -> x.schedule() in tests

---

extra/onnx.py
extra/onnx_ops.py
test/external/external_test_onnx_backend.py

tested this on on #8429 with 
`ORT=1 PYTHONPATH="." python3 examples/benchmark_onnx.py https://huggingface.co/qualcomm/MobileNet-v2-Quantized/resolve/main/MobileNet-v2-Quantized.onnx`
and ran into numerical stability issues.
```
Mismatched elements: 264 / 1000 (26.4%)
Max absolute difference among violations: 1
Max relative difference among violations: 0.02702703
ACTUAL: array([[ 43,  65,  57,  67,  71,  66,  62,  61,  55,  45,  49,  49,  47,
56,  50,  61,  42,  46,  68,  43,  56,  46,  59,  57,  52,  58,
47,  62,  62,  62,  51,  68,  52,  61,  76,  43,  56,  49,  61,...
DESIRED: array([[ 43,  65,  56,  67,  71,  66,  61,  61,  55,  45,  50,  49,  47,
56,  51,  62,  42,  46,  68,  43,  55,  46,  59,  57,  52,  58,
48,  63,  62,  62,  51,  68,  52,  61,  76,  43,  56,  49,  60,...
```
with …

add onnx DequantizeLinear

---

test/test_uops.py
tinygrad/ops.py

```python
from tinygrad import *
x = Tensor.rand(1, 32, 64, 128)
w = Tensor.rand(16,32,1,1)
o = x.conv2d(w).elu()
o.realize()
```
This bug was introduced in https://github.com/tinygrad/tinygrad/pull/8428
In process of rewriting `Ops.EXP2` transcendental calls `bitcast` which calls `can_view` which accesses `.st` which fails because it assumes that all `Ops.REDUCE_AXIS | Ops.WMMA` have at least one src with shapetracker

Fix uop.st for CLANG+AMX

---

extra/onnx_ops.py
test/external/external_test_onnx_backend.py

was `efficientnet`
`1: op "Conv" input shapes [(1, 3, 224, 224), (32, 3, 3, 3), (32,)] opt {'dilations': (1, 1), 'strides': (2, 2), 'kernel_shape': (3, 3), 'pads': (0, 0, 1, 1)}`
`(padding_top, padding_left, ..., padding_bottom, padding_right, ...)`
BUT! our conv supports asymmetrical pads!!!
I remembered this while laying in bed just now. Got up, pushed a fix, and saw the PR was merged and reverted 🫠.
--------
Note to self: `NOCLANG=1 PYTHONPATH=. python test/external/external_model_benchmark.py` before every PR
maybe run it as a pre-commit lmao

[fixed] onnx pool cleanup 

---

test/external/process_replay/helpers.py
test/external/process_replay/process_replay.py
test/test_pickle.py
tinygrad/engine/schedule.py

I remember when I tried to do this before it raised errors, now the context can actually be pickled.

pickle ContextVars in process replay [pr]

---

.github/workflows/test.yml
docs/abstractions2.py
docs/developer/runtime.md
setup.py
tinygrad/helpers.py
tinygrad/renderer/cstyle.py
tinygrad/runtime/ops_clang.py
tinygrad/runtime/support/elf.py

Diff with #8312:
- Mark AMX's wmma function static + comment about why
- R_AARCH64_CALL26 to call wmma function in AMX
- removed unnecessary i2u usage in R_AARCH64_ADR_PREL_PG_HI21 because getbits already sign-extends negative numbers correctly
- ClangCompiler is back because it is used by ops_dsp.py. Not sure whether i should leave it there or just create a separate DSPCompiler.
- using new python match instead of a bunch of ifs
Tested on: macos 15.2 arm64 (+amx), macos 14.7.2 arm64, ubuntu 24.04 arm64, fedora 41 arm64

Clang JIT again

---

test/test_ops.py
tinygrad/tensor.py

from #8109 
basically `_padding2d -> _resolve_pool_pads` and use it for all pool functions.
This also acts as an extra layer of protection over pool padding.
There were times where x.avg_pool(..., padding=[0,1,0,1]) was running and accidentally passing tests in onnx when asymmetric pads wasn't even supported. (e.g. [0,1,0,1] was zip-ed as [0,1] in calculations) 
so _resolve_pool_pads must run at the start of a pool op to ensure padding correctness.
`conv_transpose2d` can use this function when we actually support asymmetric padding.

Share a _resolve_pool_pads function for pool ops in Tensor

---

tinygrad/runtime/ops_metal.py

`-fno-caret-diagnostics` is what clang-tidy uses when user passes --quiet

Suppress 'X warnings generated.' in MTLCompiler

---

tinygrad/renderer/llvmir.py
tinygrad/tensor.py

`def llvm_bf16_cast` can be deleted from tensor.py after this. Is there any reason not to put this in all renderers?
This is currently blocking https://github.com/tinygrad/tinygrad/pull/8473.

move llvm_bf16_cast to the renderer [pr]

---

tinygrad/runtime/support/elf.py

First iteration of the AMX fix was using symbol lookup + trampoline approach which required this, however later i replaced it by marking amx function `static` and assumed that relocation was still used when callee wasn't inlined, however this turned out not to be the case because the callee can't be moved around by linker at link-time and can't be overloaded by other symbols (`static` means priority + local visibility)
Example of this behaviour if my explanation isn't good:
```c
int something;
static __attribute__((noinline)) int callee() {
return something;
}
int caller() {
return callee() * 2;
}
```
See how bl is already with offset but adrp+ldr don't have offsets yet because linker can move `int something` but can't `static int callee()`
```
test.o:	file format elf64-littleaarch64 …
```

Remove unused R_AARCH64_CALL26 relocation

---

test/test_schedule.py
tinygrad/ops.py

The COPY op a DEVICE source and the copyin source after https://github.com/tinygrad/tinygrad/pull/8482. This structure holds all the context we need to schedule this op.
Previously COPY was given a new_buffer on every construction, this would create two copies of exactly the same BUFFER on the same device.
This diff enables buffer allocation of COPY to happen in the scheduler, allowing for deduping of copies at the Tensor level.

dedup Ops.COPY [pr]

---

test/test_dtype.py
test/test_schedule.py
tinygrad/ops.py

This is a prereq for the delete BUFFER_VIEW from ops diff in #8473.
The PTX failure is a bug in the renderer, this is what CUDA generates vs ptx renderer:
```
python3 test/test_dtype.py TestInt8DType.test_bitcast_alt
```

do not use subbuffer for bitcast

---

docs/abstractions3.py
test/test_schedule.py

1. Kernel count tests should count CompiledRunners. `si_lowerer` can rewrite ASTs to any ExecItem that makes sense (eg. `STORE(LOAD)` -> `ViewOp`)
2. abstractions3 should use the ExecItem passed from lower_schedule_item. Buffers used in ExecItem can be different from the ScheduleItem, this is an existing behavior: `TestLinearizer.test_load_removed`.

test fixup prereqs for delete_buffer_view [pr]

---

test/test_schedule.py
tinygrad/engine/schedule.py
tinygrad/ops.py

This completes the proposed spec change from TIP 6: #8366.
Symbolic add AST diff: (a+3 from `TestTensorVariable.test_add_tvar`)
Now BIND contains its full meaning locally: device, shape, var, val.

add VIEW(DEVICE) to tensor variable [pr]

---

tinygrad/engine/schedule.py
tinygrad/ops.py

Now BUFFER_VIEW does not have a ShapeTracker in the sources, instead, we compute the ShapeTracker from sources as the st cached_property.
This allows for deleting BUFFER_VIEW and moving everything back to bitcast and contiguous. Realize can decide if it wants to use a subbuffer for a `STORE(LOAD)` or `STORE(BITCAST(LOAD))` kernel.

refactor buffer_view op structure [pr]

---

tinygrad/ops.py

TRACK_MATCH_STATS=2 is still used for printing the timings

hotfix: TRACK_MATCH_STATS=2 should not launch viz [pr]

---

test/test_schedule.py

This is gonna replace all the hardcoded ASTs in the swizzler tests. In general it's a good stress test for swizzle to put everything in one kernel.
With a few refactors, the `load_buffers` pattern matcher will move to core.

start tests for putting the tensor graph in a single kernel [pr]

---

test/test_lazybuffer.py
test/test_schedule.py
tinygrad/engine/jit.py
tinygrad/engine/realize.py
tinygrad/engine/schedule.py
tinygrad/ops.py

Ops.EMPTY is simply `ensure_allocated` on the source Buffer. `ExecItem` already does this for all buffers in a ScheduleItem, we don't need an extra op/runner.
`print(Tensor.empty(1).lazydata)` this branch vs master:
```diff
UOp(Ops.VIEW, dtypes.float, arg=ShapeTracker(views=(View(shape=(1,), strides=(0,), offset=0, mask=None, contiguous=True),)), src=(
UOp(Ops.BUFFER, dtypes.float, arg=(0, 1), src=(
-     UOp(Ops.DEVICE, dtypes.void, arg='METAL', src=()),)),
+     UOp(Ops.DEVICE, dtypes.void, arg='METAL', src=()),)),))
- UOp(Ops.EMPTY, dtypes.float, arg=None, src=()),))
```

delete empty op

---

extra/onnx_ops.py
test/external/external_test_onnx_backend.py

required to run `python3 examples/benchmark_onnx.py https://github.com/xamcat/mobcat-samples/raw/refs/heads/master/onnx_runtime/InferencingSample/InferencingSample/mobilenetv2-7-quantized.onnx`
also tested that with the huggingface branch and ORT verify passes
(there is also numerical inaccuracy here too. Gonna try to see if I can dampen it first)
qmatmul and qconv does op in int32
qadd and qavgpool does it in float
https://github.com/apache/tvm/blob/main/python/tvm/relay/frontend/onnx.py#L5373 it seems that a lot of these QLinear ops for ORT are also doing float math.

Add QLinearConv, QLinearMatMul, QLinearAdd, QLinearGlobalAveragePool to onnx

---

tinygrad/runtime/ops_disk.py

`assert self.device.mem is not None` did not assert because `.mem` triggers AttributeError first

fix checking DiskBuffer is opened [pr]

---

tinygrad/ops.py

Thinking in adding `elements_per_threads` as arg to wmma to simplify `ops_python`, George said he was okay in retrieving simple attributes from tc class like `dimensions`, `threads` and `elements_per_threads`
Is there any value in spec checking every wmma arg, or is it enough with checking the length?
```python
wmma_arg = (name, dims, dtype_in, dtype_out, device, threads, upcast_axes, reduce_axes)
```

minor arg spec check on wmma [pr]

---

test/test_schedule.py
tinygrad/engine/schedule.py
tinygrad/ops.py

I think this is the correct way to express the ops.py UOp and device.py Buffer connection. The meaning of Ops.BUFFER is that a device Buffer (can be unallocated) exists for that UOp.
A contiguous `VIEW(src=(BUFFER,))` representation should mean the same thing as "is_realized"
`is_realized`, in the current way that we express it, simply means that a Buffer instance exists.
This does not promise allocation (until execution time).
The Buffer currently exists in the buffers dict, it should be an arg to BUFFER UOp.

always give BUFFER uops Buffers [pr]

---

test/test_assign.py
tinygrad/renderer/cstyle.py

half on qcom and gpu isn't well tested because the CI runner does not support it.
Can we use PYTHON to emulate half? so that there's some test coverage in CI.
Running `python3 test/test_assign.py TestAssign.test_setitem_half` fails to compile on comma device.
[similar benchmark error](https://github.com/tinygrad/tinygrad/actions/runs/12732396403/job/35487536897#step:5:66).

fix half4 on qcom and gpu

---

test/test_uops_stats.py
tinygrad/engine/realize.py

A bug originally introduced in #8434. DEBUG=2 should output the nbytes not the size.

fix DEBUG=2 output for copy runners [pr]

---

.github/workflows/test.yml

thanks to nimlgen we can do this now #8575.
Seems fast enough:
master:
branch:

remove PYTHONPATH=. from mypy CI [pr]

---

examples/mlperf/dataloader.py

don't think that buffer is really beneficial. 5% faster data_time and 1ms faster per step. https://wandb.ai/chenyuxyz/MLPerf-BERT/runs/69c9lx8y/overview

simpler batch_load_train_bert [pr]

---

test/test_pickle.py
test/test_schedule.py

fixups from #8580.
hardcoded asts are bad because they'll get out of date. We can use the tensor API to test swizzle now (see run_tensor_ast).
This is currently in two kernels because of how the scheduler fuses things, but swizzling rewrite is capable of rewriting to a single kernel.

better test for reduce swizzle + don't use double dtype [pr]

---

test/external/external_model_benchmark.py
test/test_linearizer.py
test/test_schedule.py
tinygrad/engine/schedule.py

The scheduler does not yet do this splitting at schedule time. This diff just moves these asserts to the CompileError that the device compiler already does.
Once it's implemented we can remove the expectedFailures, but the scheduler itself does not need to assert this.

assert kernel buffer limit at compile time [pr]

---

test/test_tensor_uop.py

BUFFER_VIEW cannot be correct if the parent operation late folds to a CONST. There is fundamentally no BUFFER on a CONST, so this throws an error.
discovered this when deleting forced_realize:
mul*0 becomes just a CONST. What does BUFFER_VIEW(CONST) mean at that point? Should we rewrite it to a CONTIGUOUS(CONST)?

isolate simple failing test for subbuffer on CONST [pr]

---

tinygrad/device.py
tinygrad/helpers.py
tinygrad/runtime/ops_clang.py
tinygrad/runtime/support/elf.py

This commit moves jit loading, disassembling and CPUProgram logic from `ops_clang.py` to `elf.py`, `helpers.py` and `device.py` respectively
I don't quite like the `helpers.py` destination for capstone_flatdump but this is where cpu_objdump is so presumably this is how it's supposed to be

LLVM JIT prereqs

---

tinygrad/engine/schedule.py
tinygrad/gradient.py
tinygrad/ops.py

This has been a dream for me ever since delete_lazy, so much time wasted trying to work around it.
Now it's once and for all in an isolated rewrite rule you can reason about. Tensor and UOp should not ever care if something became a subbuffer.
I first thought it was realize.py's decision but I was wrong, the scheduler decides how BUFFERs get created, realize just allocates/frees(?) them.

move subbuffer to a rewrite rule in the scheduler 

---

tinygrad/device.py

Number after .so is abi version, it is always 1 for libgcc_s. Most linux systems set default library versions via symlinks that are simply followed to get actual elf, however conda does it via linker scripts which ctypes doesn't follow (below contents of libgcc_s.so):
```
/* GNU ld script
Use the shared library, but some functions are only in
the static library.  */
GROUP ( libgcc_s.so.1 -lgcc )
```
ctypes.util.find_library thinks that this is the actual elf and ctypes.CDLL just loads this text file as a shared library. The result is:
```
File "/home/me/src/tinygrad/tinygrad/device.py", line 223, in CPUProgram
helper_handle = ctypes.CDLL(ctypes.util.find_library('System' if OSX else 'gcc_s'))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```

Use full soname for libgcc_s in CPUProgram

---

tinygrad/helpers.py

Apple/AMD driver bug makes it so JIT is slower than without using JIT. Should default to setting JIT=2 for Intel MBPs
Issue: https://github.com/tinygrad/tinygrad/issues/8648

Disable graphs by default if using an intel macbook

---

test/test_multitensor.py
test/test_schedule.py
test/unit/test_disk_tensor.py
tinygrad/engine/schedule.py
tinygrad/multi.py
tinygrad/ops.py
tinygrad/tensor.py

function.py already handles calling the right UOp function, no bitcast:bool arg.
Multi does not implement bitcast, do we want it?
In general we should keep asserts/ifs in UOp methods to a minimum, these get called a lot in codegen.
In this case, the shape/dtype assert belongs to Tensor, it's a user error.
The cast behavior on DISK should be the same as any other ALU op on DISK device, NotImplemented at runtime.
It is not a parsing error.

delete unused cast/bitcast lines from ops.py [pr]

---

extra/gemm/simple_matmul.py

`simple_matmul` was broken for ints as `Tensor.rand` does not accept `int` as `dtype`

Fix simple_matmul for `int` plus minor cleanup

---

tinygrad/engine/schedule.py

This makes ops_folding a generic symbolic folder that can apply to Tensor UOps directly.
Keeps the tensor_map branch diff focused on the new contiguous rules. Nice to see this in VIZ already.

init folding changes from the tensor_map branch [pr]

---

tinygrad/engine/schedule.py

The found_contiguous UPat uses this context to track contiguous roots. re: #8666

hotfix: add ctx

---

test/test_linearizer.py
test/test_schedule.py

The simple_tensor_map diff changes the schedule for `(a*b)/b`,
Because it applies symbolic on the raw tensor uops that div folding can happen in the scheduler, no additional kernels needed.
Right now this happens late in the lowerer.

add tests for mul/div buffer collapsing in the scheduler [pr]

---

test/test_ops.py
tinygrad/ops.py

x < c -> X <= c-1 only works for int

fix parse_valid for float uop

---

test/test_schedule.py
tinygrad/engine/schedule.py

This is a prereq for the forced_realize deletion from #8580. Because ops.py's contiguous will simply return a new UOp whenever contiguous is called (no extra logic), we need to do perform this folding later in the scheduler graph_rewrite.

fold double contiguous [pr]

---

test/test_schedule.py
tinygrad/tensor.py

max can always be done in the same dtype without any numerical loss, so this is better when explicitly upcasting in softmax

move softmax upcast to after subtracting max

---

test/test_image_dtype.py

tensor_map_simple #8580 changed the kernel count here because it is correctly realizing the final CAST to float to a new BUFFER.
Right now this is incorrectly folding that gradient with the imagef CAST parent.

add failing assert for gradient realization [pr]

---

test/test_schedule.py
tinygrad/engine/schedule.py

- The extra logic in `uval` existed because of forced_realize.
- scheduler symbolic folding does not need the UPatScheduled style pattern matcher anymore
- Contiguous tests can use Tensor methods now that forced_realize is gone.

more high level contiguous tests + scheduler deletions [pr]

---

test/test_schedule.py
tinygrad/engine/schedule.py

A tensor const with symbolic shape has a stride 1. Currently this is blocking #8698 as we can add movement ops after the reshape is done.
The tensor const.reshape(bind) becomes:
```
UOp(Ops.CONST, dtypes.float, arg=1.0, src=(
UOp(Ops.VIEW, dtypes.void, arg=ShapeTracker(views=(View(shape=(4,), strides=(0,), offset=0, mask=None, contiguous=False), View(shape=(UOp(Ops.BIND, dtypes.int, arg=None, src=(
UOp(Ops.DEFINE_VAR, dtypes.int, arg=('i', 1, 10), src=()),
UOp(Ops.CONST, dtypes.int, arg=4, src=()),)),), strides=(1,), offset=0, mask=None, contiguous=True))), src=(
UOp(Ops.DEVICE, dtypes.void, arg='METAL', src=()),)),))
```
Unlike normal CONST is has two views and a stride=(1,).
We can still keep the unmasked check. I think this is the only thing a CONST with int shape and UOp shape have in …

allow symbolic shape in tensor const parents [pr]

---

test/test_schedule.py
tinygrad/ops.py

This already has a UPat and tensor map folds it correctly.
https://github.com/tinygrad/tinygrad/blob/3628f899292e311e01dead74e666929c9d0fbfd9/tinygrad/engine/schedule.py#L378-L380

remove the "no copy" line from copy_to_device

---

test/test_tensor.py
tinygrad/ops.py

err, tests shouldn't depend on any Tensor/ops methods doing folding before scheduling.
UOp functions always return a new UOp, the equivalence/folding is done after graph_rewrite.

fix using clone with shrink [pr]

---

test/unit/test_viz.py
tinygrad/ops.py
tinygrad/viz/index.html
tinygrad/viz/serve.py

replaced dataclass with TypedDict, no more asdict perf workarounds here.
This diff changes internal return types a bit, the UI is exactly the same as before.
eg. `GraphRewriteMetadata` is more compact, moved the detailed fields to the `GraphRewriteDetails` when we need the data in the UI.

viz cleanups 2 [pr]

---

test/test_schedule.py
tinygrad/engine/schedule.py

The scheduling flow has become something like:
1. Simplify tensors big graph to the most compressed version
2. Map the remaining tensors to BUFFER/CONST UOps
Step 2 may or may not require ScheduleItems. This diff splits the concerns between the `becomes_map` update and ScheduleItem creation.

tensor_map cleanups [pr]

---

tinygrad/engine/schedule.py
tinygrad/ops.py

The scheduler does not require VALID for the merge_views/sym graph_rewrite in big sink anymore,
so masked VIEWs can stay as VIEW(CONST) until we create the ScheduleItem AST.
To completely remove VALIDs with unmasked ShapeTrackers we need to restore indexing behavior for CONST in kernel/lowerer next.

move VALID creation after merging the views

---

tinygrad/engine/schedule.py
tinygrad/ops.py

With this diff no valids get created in the big sink, before and after of:
```
PYTHONPATH=. VIZ=1 python3 test/test_symbolic_jit.py TestSymbolicJit.test_mean
```
old, with the extra VALID:
new, no VALID:

share merge_views/valid creation for CONST/DEFINE_VAR

---

test/test_schedule.py
tinygrad/engine/schedule.py
tinygrad/nn/optim.py

FAILED test/models/test_end2end.py::TestEnd2End::test_bn_linear - RuntimeError: self operand of augmented assign must be contiguous.
FAILED test/models/test_real_world.py::TestRealWorld::test_train_cifar - RuntimeError: self operand of augmented assign must be contiguous.

contiguous is no longer needed in SGD [pr]

---

test/unit/test_verify_ast.py
tinygrad/codegen/lowerer.py

Prereq change for #8759.
Lowerer asserts this in master because the ShapeTracker does not get removed.
```
python3 test/unit/test_verify_ast.py TestVerifyAST.test_const_view_always_valid
```
Generates the correct kernel in this branch:

support lowering CONST(VIEW) in lowerer

---

tinygrad/engine/schedule.py
tinygrad/ops.py

After the unmasked VALID removal we need to keep this ShapeTracker in the DEFINE_VAR sources. eg, this is the new symbolic mean:
This spec already exists in the Tensor UOps spec, this diff extends it to ScheduleItem/Kernel ASTs.

allow VIEW source in DEFINE_VAR spec [pr]

---

.github/workflows/test.yml
tinygrad/device.py

The allocator does not enforce memory alignment, and this can cause issues when the block is used by certain instructions. 
For example, the following is a kernel generated by `test_maximum` in `test_ops.py`. The third instruction uses [`vmovapd`](https://www.felixcloutier.com/x86/movapd) which will trigger an exception if the address in `rdx` is not aligned to 16 bytes.
```asm
0x000000: push  rbp
0x000001: mov   rbp, rsp
0x000004: vmovapd       xmm0, xmmword ptr [rdx]
0x000008: vmovss        xmm3, dword ptr [rdx + 4]
0x00000d: vmovss        xmm1, dword ptr [rip + 0xa7]
0x000015: vucomiss      xmm1, xmm3
0x000019: vmovaps       xmm2, xmm1
0x00001d: ja    0x33
0x00001f: vucomiss      xmm3, dword ptr [rip + 0x95]
0x000027: vmovaps       xmm2, xmm3
0x00002b: jne   0x33
0x00002d: jp    0x33 …
```

Fix allocator memory alignment

---

.github/workflows/test.yml

DEBUG=5 prints a lot of info that's slow, and is not visible if test passed on CI. also skip two tests that took 3 minutes in python backend

remove DEBUG=5 in windows ci test [pr]

---

test/test_ops.py
tinygrad/codegen/rewriter.py
tinygrad/ops.py

Uses `1/(x*x) -> 1/x * 1/x`  together with `x/(1+x) -> 1-1/(1+x)` to rewrite sigmoid instead of `x/((x+1)(x+1)) -> 1/(x+1)*(1-1/(x+1))`
The last rule is what fixes `test_sigmoid_alt_extreme`, would not be needed if float multiplication distributed over addition

Better stable sigmoid

---

docs/abstractions2.py
test/test_schedule.py
tinygrad/ops.py

only abstractions2 needs updating, the rest of tinygrad follows this structure already. This works now because given any VIEW(BUFFER) UOp, `.base` is _always_ the buffer.

Realized only exists on base

---

docs/abstractions2.py
tinygrad/ops.py
tinygrad/tensor.py

Tensor.empty just creates a tensor with UOp(VIEW(BUFFER)). We do not need this extra construction.

remove r.lazydata.buf_uop_view [pr]

---

test/test_renderer_failures.py
tinygrad/renderer/ptx.py

I don't know why there that special case for `half` and `boolean`
pr has minor diff, before, in that cases, it was allocating two registers and only using one.
fixes issue on #8680 
---
**Before fix**
```python
minimal repro:
from tinygrad.helpers import Context
with Context(DEBUG=0):
a = Tensor.randn(33, 33, dtype="half").realize()
b = Tensor.randn(37, 33, dtype="half").realize()
c = a.pad((2,2)).matmul(b, acc_dtype="half").realize()
print(c.numpy())
------------------------------
.reg            .u64 %dat_u64_<3>;
.reg            .s32 %const_s32_<5>;
.reg            .f16 %const_f16_<5>;
.reg            .pred %const_pred_<1>;
.reg            .u32 %const_u32_<4>;
.reg            .s32 %alu_s32_<9>;
.reg            .f16 %acc_f16_<4>;
.reg            .s32 …
```

fix for define_acc rendering bug for ptx + regression test

---

test/test_schedule.py
tinygrad/engine/schedule.py

limiting FUSE_ARANGE scope to unblock progress on the context/KERNEL refactor.
We need to add a correct FUSE_ARANGE back that does this contiguous check without needing to lookup tensor uops.

remove support for checking tensor uops in FUSE_ARANGE [pr]

---

tinygrad/runtime/ops_amd.py

add env variable for am (`AMD_ALLOC_QUEUE_DEV_MEM`) to control where queues are allocated. and return them back to gpu by default.

am: queues allocated on gpus

---

test/unit/test_disk_tensor.py

While working on https://github.com/tinygrad/tinygrad/pull/8646 I found this failing test:
> FAILED test/unit/test_disk_tensor.py::TestTorchLoad::test_load_resnet - RuntimeError: Cannot use ``weights_only=True`` with files saved in the legacy .tar format. In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
This was because in that PR I modified setup.py (I removed the `wgpu-py` dependency). By doing so, the actions cache key for linting packages (see: `linting-packages-${{ hashFiles('**/setup.py') }}-3.10`) in `Linters+fuzz+unit Tests` changed, …

weights_only=False to prepare for pytorch 2.6 in unit tests

---

test/unit/test_uop_symbolic.py
tinygrad/codegen/rewriter.py

with `NOOPT=1`
```
Tensor([1, 2, 3]).pad(((1, 1),), value=4).realize()
```
this
```
#include <metal_stdlib>
using namespace metal;
kernel void E_5(device int* data0, device int* data1, uint3 gid [[threadgroup_position_in_grid]], uint3 lid [[thread_position_in_threadgroup]]) {
int gidx0 = gid.x; /* 5 */
bool alu0 = ((gidx0<4)&((gidx0<1)!=1));
int val0 = (alu0?*(data1+(gidx0+-1)):0);
*(data0+gidx0) = (val0+(alu0?0:4));
}
```
master
```
#include <metal_stdlib>
using namespace metal;
kernel void E_5(device int* data0, device int* data1, uint3 gid [[threadgroup_position_in_grid]], uint3 lid [[thread_position_in_threadgroup]]) {
int gidx0 = gid.x; /* 5 */
bool alu0 = ((gidx0<4)&((gidx0<1)!=1));
int val0 = (alu0?*(data1+(gidx0+-1)):0);
*(data0+gidx0) = …
```

push cast to branches in UOp where

---

test/test_assign.py
tinygrad/tensor.py

Before this change, `test_disk_assignment` would fail with: `AssertionError: can't copyin to unallocated buffer`. The disk buffer was not allocated because the scheduler would fold the entire `SINK(CONTIGUOUS(VIEW(BUFFER(DEVICE))))` tree to an isolated `SINK` node, meaning the buffer would not end up in schedule item to be allocated eventually.
~~Not entirely sure if this is the right fix, but `Tensor.data()` will do something similar.~~

Fix disk tensor assignment

---

tinygrad/engine/schedule.py

Simplification and grouping started as the same rewrite stage, after tensor_map these are distinctly different.
schedule.py should reflect this.
This diff loses the git blame but I think it's required for KERNEL Op.

reorder simplifier and grouper logic in scheduler [pr]

---

tinygrad/runtime/ops_llvm.py

@uuuvn See this for how to improve code quality.
I found an issue with the LLVM stuff, run `LLVM=1 pytest -n=auto test/` on Mac. Tons of segfaults!
```
collecting: 19/20 workers......F.....................................s....Fatal Python error: Segmentation fault                                                
Thread 0x0000000170d07000 (most recent call first):                                                                                                             
File "/opt/homebrew/lib/python3.11/site-packages/execnet/gateway_base.py", line 534 in read                                                                   
File "/opt/homebrew/lib/python3.11/site-packages/execnet/gateway_base.py", line 567 in from_io
File "/opt/homebrew/lib/python3.11/site-packages/execnet/gateway_base.py …
```

llvm cleanups [pr]

---

tinygrad/codegen/kernel.py

1. The only thing breaking process replay is PTX that uses the argument directly, like this PR diff:
```diff
<tinygrad.renderer.ptx.PTXRenderer object at 0x7d979c6c87c0>
[Opt(op=OptOps.GROUPTOP, axis=0, arg=16)]
r_256_16_256
@@ -28,8 +28,8 @@
ld.param.u64    %dat_u64_0, [data0+0];
ld.param.u64    %dat_u64_1, [data1+0];
ld.param.u64    %dat_u64_2, [data2+0];
-       .shared         .align 4 .b8 temp1[64];
-       mov.u64         %local_u64_0, temp1[0];
+       .shared         .align 4 .b8 temp0[64];
+       mov.u64         %local_u64_0, temp0[0];
mov.u32         %gidx0, %ctaid.x;
mov.u32         %lidx0, %tid.x;
mov.b32         %const_s32_0, 0;
```
2. Beautiful result of merging this pr:
3. Why was it temp1 in the first place? looking at #6030, it originates from:
```python
def …
```

make DEFINE_LOCAL variable names argument start from temp0 instead of temp1

---

test/external/process_replay/process_replay.py
tinygrad/engine/schedule.py

This is possible now after the Tensor UOp refactors.
In comes the `big_sink`, out goes a list Kernel AST. This will help clearly see if any scheduler changes impact created kernels or the order of the schedule.
I'm gonna start by just printing the diffs, once a few runs build confidence that this is stable I'll bring the `pr` assert back.

process replay from tensor uops to kernel ast

---

tinygrad/engine/schedule.py

This try block is required because there isn't a way to check if a ShapeTracker is already unbound.
Currently calling unbind on an already unbound View will throw error,
The scheduler works around this by maintaining a set of already unbound ShapeTrackers, is there a way to do this without maintaining external state?

unbind ShapeTrackers without maintaining a cache [pr]

---

test/external/process_replay/process_replay.py

The print of big_sink over this line limit almost become unreadable and doesn't really add value.
Maybe the process replay capture needs to be exported as an artifact?
New diff print for a `big_sink` with over 15K lines:

truncate process replay logs [pr]

---

examples/benchmark_onnx.py
examples/test_onnx_imagenet.py
examples/yolov8-onnx.py
extra/onnx_helpers.py

Should we try to have 1 place to store helper functions around onnx usage?
kind of a prereq to 100 huggingface, but I can make do without this too. 
`get_example_inputs` will get crazy with 100 huggingface
made the changes minimal for now so I don't accidentally write regressions for geohot's quantize stuff lolol.
onnx_helpers isn't used in many places yet. 
Ideally all the onnx related tests and external_model_benchmark can reuse stuff in here but that's gonna take some work.

add onnx_helpers to extra and add ort validate to benchmark_onnx

---

tinygrad/device.py

I encountered the same issue as #8642 and discovered that #8761 had reverted it, which seems unintentional.

cherry-pick reverted "Use full soname for libgcc_s in CPUProgram (#8642)"

---

test/external/process_replay/process_replay.py
tinygrad/engine/schedule.py

The scheduler creates KERNEL UOps and update the becomes_map in the same loop.
Then, it'll give the sched_sink to the schedule linearizer.

rename to KernelContext and move the linearize_sched comment [pr]

---

tinygrad/engine/schedule.py

This diff moves the BUFFER_VIEW op rewrite to the tensor_map stage:
also, COPY.src[1] is always the base, so that UPat.any is not needed.

simpler subbuffer construction + copyin is always base

---

tinygrad/engine/schedule.py

currently all the STOREs are in the SINK parents. Next after this is making the adding the append_to_kernels loop to this rewrite stage that accumulates the UOps directly instead.
Had to add var_vals back to the context, I don't like adding more state but we do need some way to merge the dicts here.
Maybe var_vals should exist on the Kernel arg instead? In the end we can merge all the KERNEL UOp var_vals args.

construct the sched_sink with graph_rewrite [pr]

---

tinygrad/runtime/support/hcq.py

check to `int` is not the best way, since we can get `floats` (when nolocals). just directly check that variable is variable

hcq: better var check

---

tinygrad/codegen/rewriter.py
tinygrad/codegen/transcendental.py
tinygrad/gradient.py
tinygrad/ops.py
tinygrad/tensor.py

UOp level negative int mod behaves differently on different backend, thus the `exponent.cast(dtypes.int32).cast(dtypes.uint32)%2).eq(1)` hack for now

Ops.POW and transcendental

---

test/test_ops.py

backward works now. 0**x still does not work because it's a special case fixed in transcendental

enable backward test for pow(neg const ** x)

---

tinygrad/runtime/ops_llvm.py

This gets `test_gemm_fp16` to pass on Windows on certain hardware. It would fail because the generated machine code would call compiler-rt functions to perform truncating. This also probably improves performance and is essentially `-march=native`.
Unless this was intentionally left as is to be re-implemented fully in LLVM IR or something.
Before
```asm
0x000000: push  r15
0x000002: push  r14
0x000004: push  rsi
0x000005: push  rdi
0x000006: push  rbx
0x000007: sub   rsp, 0xe0
0x00000e: movaps        xmmword ptr [rsp + 0xd0], xmm15
0x000017: movaps        xmmword ptr [rsp + 0xc0], xmm14
0x000020: movaps        xmmword ptr [rsp + 0xb0], xmm13
0x000029: movaps        xmmword ptr [rsp + 0xa0], xmm12
0x000032: movaps        xmmword ptr [rsp + 0x90], xmm11
0x00003b: movaps        xmmword ptr …
```

Pass host CPU features to LLVM target

---

test/imported/test_indexing.py
test/test_const_folding.py
tinygrad/tensor.py

added a TODO for advance indexing on const, which was the last place that checks const in Tensor

remove Tensor._to_const_val

---

test/test_tensor.py
tinygrad/tensor.py

Hello,
I'm new to tinygrad so I've been screwing around with it in the Python repl, and I found a bug. If I supply invalid arguments to `reshape()`, then a `ValueError` is thrown as expected. However, after that happens, I'm no longer able to `realize()` or `numpy()` any new tensors within that execution context, as an `AttributeError` is thrown:
```
>>> from tinygrad import Tensor
>>> print(Tensor.arange(16).reshape(1, 1, 4, 4).numpy())
[[[[ 0  1  2  3]
[ 4  5  6  7]
[ 8  9 10 11]
[12 13 14 15]]]]
>>> print(Tensor.arange(16).reshape(1, 4, 4, 4).numpy())
File "<stdin>", line 1, in <module>
File "/home/joalmo/coding/tinygrad/tinygrad/tensor.py", line 3946, in _wrapper
ret = fn(*args, **kwargs)
File "/home/joalmo/coding/tinygrad/tinygrad/tensor.py", line …
```

Fix AttributeError occurring after ValueError in _apply_uop

---

tinygrad/engine/schedule.py

```
CAPTURE_PROCESS_REPLAY=1 JITBEAM=2 IGNORE_BEAM_CACHE=1 python3 examples/llama3.py --size 8B --model weights/LLaMA-3/8B --benchmark --temperature 0 | tee llama3_beam.txt
```
~50tok/s here vs master 45toks/s on tinybox red.

prepickle scheduler process replay [pr]

---

tinygrad/runtime/graph/metal.py
tinygrad/runtime/ops_metal.py

Didn't test the stupid ICB fix, try 2.
```
light@blak:~/tinygrad$ git checkout master && python test/external/external_benchmark_kernel_launch.py
Already on 'master'
Your branch is up to date with 'origin/master'.
0: 29.56 ms
1:  0.86 ms
2:  0.46 ms
3:  0.29 ms
4:  0.95 ms
nosync  0: 53.71 us
nosync  1: 71.33 us
nosync  2: 54.17 us
nosync  3: 48.25 us
nosync  4: 71.08 us
precise 0: 200.62 us
precise 1: 288.37 us
precise 2: 210.58 us
precise 3: 217.04 us
precise 4: 374.04 us
*** METAL     19 E_                                        arg  3 mem  0.00 GB tm      6.88us/     0.01ms (     0.00 GFLOPS    0.0|0.0     GB/s) 
kernel 0.01 ms / full 0.21 ms -- 31.06 x
n:       1  tm:   0.01ms  tot:   0.11ms jit.py:244:__call__                                
n:       1  tm:   0.00ms  tot:   0.07ms …
```

objc fast msg, try 2 [pr]

---

tinygrad/ops.py

After BUFFER got a ShapeTracker of shape=(N,), the only UOp that can have a VIEW child and no ShapeTracker is a DEVICE, in CONST(VIEW(DEVICE)), maybe even that shouldn't be allowed. Like `.base` should always itself have some ShapeTracker. What is the shape of a device? `()`?

little better VIEW simplifier pattern [pr]

---

.github/actions/process-replay/action.yml

On pull_request creation, this need to check the pull_request.head.sha since HEAD points to the automatic merge commit.
Tested on pull_request, push and workflow_dispatch events.

fix "fatal bad object" log in process replay [pr]

---

tinygrad/viz/index.html
tinygrad/viz/serve.py

VIZ=1  was rendering the wrong final graph for `python test/models/test_mnist.py TestMNIST.test_adam_threestep
` because it was starting from the offset while building the replaces dict. It should start from the first match.
Is there a good way to cache UOp.substitute globally? That would speed this up.

fix viz paginate + cleanups

---

.github/workflows/benchmark.yml

Noticed some timeout errors, will investigate and fuzz. Going to revert to not make ci reds from time to time.  
This reverts commit 107e616857ecb6ed9c203f677670d962b1b4ee95.

Revert "use am in training benchmarks (#8965)"

---

test/test_schedule.py

This will be fixed by backtracking from a VIEW to the movement ops that resulted in that VIEW, and instead of the BUFFER, apply those movement ops.
First, there is a chain of movement ops:
These movement ops make a single VIEW:
Then the ADD and MUL tensors both become VIEW(BUFFER), we should have a way to replace that VIEW with the chain of movement ops that created it.

minimal failing test for #8975 [pr]

---

.github/workflows/test.yml
test/test_tensor_uop.py
test/test_uops.py
tinygrad/engine/schedule.py
tinygrad/ops.py

This is type checked in spec.py already before reaching the simplifier.
I'm happy tensor doesn't access UOp args anymore, `_to_const_val` wasn't good.

remove const_arg

---

tinygrad/engine/schedule.py
tinygrad/ops.py

Will probably add some of these back after replacing ScheduleItem with the KERNEL UOp, we don't need these yet.

kernel op cleanups + use ScheduleItem [pr]

---

extra/models/llama.py

for unknown reasons, without this, when trying to execute "Llama 3.2 1B", I get the error below. Fwiw I do not know the performance impact for this change. I can't even get exo running, but this change allows me to /get further/ (before running into a separate issue with vram allocation? story for another day i suppose)
error: 
```
Failed to fetch completions: Error processing prompt (see logs with DEBUG>=2): Nvrtc Error 6, NVRTC_ERROR_COMPILATION <null>(18): error: more than one user-defined conversion from "nv_bfloat16" to "half" applies:
function "__half::__half(float)" (declared at line 214 of /usr/include/cuda_fp16.hpp)
function "__half::__half(short)" (declared at line 227 of /usr/include/cuda_fp16.hpp)
function "__half::__half(unsigned short)" (declared at line 228 of …
```

workaround f16 cast ambiguity

---

test/test_assign.py
test/test_uops.py
tinygrad/engine/schedule.py
tinygrad/ops.py
tinygrad/spec.py
tinygrad/viz/serve.py

Current:
```
light@blak:~/tinygrad$ python3 test/external/external_benchmark_schedule.py
***** model tensor in     25.82 ms
***** model schedule in  238.27 ms
***** model opts(32) in  126.48 ms
***** model lower in      56.57 ms
***** model rewrite in   442.46 ms
***** model linearize in 166.69 ms
20200
all 1057.31 ms
```
With revert
```
light@blak:~/tinygrad$ python3 test/external/external_benchmark_schedule.py 
***** model tensor in     25.90 ms
***** model schedule in   77.48 ms
***** model opts(32) in  130.81 ms
***** model lower in      57.11 ms
***** model rewrite in   439.47 ms
***** model linearize in 166.56 ms
20200
all 898.34 ms
```
10% slowdown is fine, but 4x isn't

revert scheduler change

---

tinygrad/helpers.py

change capstone behavior so that it doesn't stop after encountering broken instruction
fixes capstone assembly output; no longer stops at amx instructions #8957 
>By default, Capstone stops disassembling when it encounters a broken instruction. Most of the time, the reason is that this is data mixed inside the input, and it is understandable that Capstone does not understand this “weird” code.
>
>Typically, you are recommended to determine yourself where the next code is, and then continue disassembling from that place. However, in some cases you just want to let Capstone automatically skip some data until it finds a legitimate instruction, then just carries on from there. Hence, the SKIPDATA mode is introduced for this purpose.
>
>In general, this solution is suboptimal because Capstone …

enable capstone skipdata [pr]

---

tinygrad/spec.py

VIEW is no longer a valid tensor UOp. This is possible after #8994 and #8984 reconstruct movement ops on top of the buffer + Tensor.empty constructs with RESHAPE: #8987.

disallow VIEW(BUFFER) in tensor uops [pr]

---

.github/workflows/test.yml

- Ensure that the set backend environment variable is persisted to the next step via $GITHUB_ENV
- It doesn't actually persist for Windows unless shell is explicitly set to bash.
- Add the assertion to ensure the selected backend is actually used.

Ensure Windows CI correctly tests the specified backends 

---

test/test_schedule.py
tinygrad/engine/schedule.py

We already support stacking movement ops on top of realized buffers in becomes_map.
To make #9051 work we need to extend this to newly created buffers.
This is tricky because VIEW is not a valid Tensor UOp, so it has to lookup the tensor_map to reconstruct movement ops, similar to #8984.

simple failing case for reorder expand + keep views in tensor_map [pr]

---

examples/mlperf/helpers.py
examples/mlperf/model_train.py

`DEFAULT_FLOAT=HALF BENCHMARK=10 BS=66 EVAL_BS=6 GPUS=6 MODEL=bert python3 examples/mlperf/model_train.py` no longer oom. I think the buffer of random init weights caused the oom.

zero out the weight in bert init run

---

tinygrad/runtime/ops_webgpu.py

`test_speed_v_torch` showed suspicious results (showed better results then METAL=1)
After synchronize:

Synchronize webgpu [pr]

---

extra/optimization/helpers.py

only test that used it was skipped in CI due to being slow

fix import time_linearizer [pr]

---

tinygrad/tensor.py
tinygrad/viz/index.html
tinygrad/viz/serve.py

Time to `big_sink` graph render for `VIZ=1 python ./examples/beautiful_mnist.py`:
This branch: `35s`
Master: `360s`
I think the first (input) sink and the output sink add value individually, we need to always display these first.
Iterating through all the matches is expensive, especially for larger graphs, but we shouldn't block VIZ because of it. This diff loads matches incrementally.
The extra "progress" element won't actually be needed, I wanna just update the right sidebar's rewrite number style based on if the graph is fetched or not. The `ul` already has styling for "active"/"non-active" states.

always viz the first graph + non blocking matches fetch [pr]

---

tinygrad/device.py
tinygrad/runtime/ops_amd.py
tinygrad/runtime/support/am/amdev.py

ops_amd.py registres device finalization via atexit.register after finalize_profile is registred in device.py leading to AM device being closed before finalizing profile leading to hang.
(atexit.register is LIFO: https://docs.python.org/3.12/library/atexit.html#atexit.register)
This pr moves registring device finalization to device.py before registring profile finalization

am: profiling working

---

tinygrad/viz/index.html
tinygrad/viz/serve.py

Time to fully load `VIZ=1 python ./examples/beautiful_mnist.py` tensor_map rewrite (1,209 rewrites):
master: [300s](https://github.com/user-attachments/assets/505bd970-dfb3-45b2-9ed0-a80999ffac14)
branch: 48s
The client streams rewrites so they become instantly available.
We incrementally load the matches, and the graph stays responsive:
https://github.com/user-attachments/assets/6725e543-26be-4ad8-87f8-6ae1f274e958
The final performance optimization left is D3 render itself.
Currently, renderGraph uses the main thread. This blocks the rest of the UI when you select a new match in the large graph.

faster viz data fetching with streaming [pr]

---

tinygrad/runtime/ops_webgpu.py

Async function calls have a common pattern that I factored out into a function.
We always have the:
-  `result` array: where we store the callback params
- `callback`
- `callbackinfo`
- the `async` function that we want to call with its `parameters`
- status enum values: needed for error messages
- 2 indices: one for the (optional) result object, and one for the (optional) error message
An example before after:
Before (7 lines):
```Python
pipeline_result: List[Any] = []
def cb(status, compute_pipeline_impl, msg, u1, u2): pipeline_result[:] = status, compute_pipeline_impl, from_wgpu_str(msg)
cb_info = create_cb_info(webgpu.WGPUCreateComputePipelineAsyncCallbackInfo2,  webgpu.WGPUCreateComputePipelineAsyncCallback2, cb)
webgpu.wgpuDevicePushErrorScope(self.dev, …
```

Refactor async functions in webgpu [pr]

---

.github/workflows/test.yml
test/test_dtype.py
test/test_linearizer.py
test/test_specific_conv.py
tinygrad/codegen/lowerer.py

This closes https://github.com/tinygrad/tinygrad/issues/8043
Our `_limit_dims` in `lowerer` only handles contraction, i.e. cases such as:
`dim=(2,3,4,5)`  `max=(16,16,16)`, so when` len(dim) > len(max)`
But with WebGPU we hit cases not handled by `_limit_dims`, when some element in `dim` is larger than the corresponding element in `max`, resulting in this error:
This can come in various forms, such as:
- `dim=(64,3,4)`, `max=(16,16,16)`
- `dim=(128,)`, `max=(16,16,256)`
The algo tries to find a divisor for the current `dim` if it's larger than `max`, and divides it until it's `<= max`. While dividing, it multiplies the next dim by the same amount so the product of the shape doesn't change.
- I removed all skips which were skipped because of this issue.
- I also removed ignore of …

Solve get_grouped_dims does not split issue

---

test/test_uop_graph.py

Right now const folding arithmetic uses arbitrary precision int and does not match backends behavior.
This means that you can get wildly different results depending on what part of UOp graph was evaluated at compile time. One example of this is failure in `test_payne_hanek_reduction` in "Add and test constant folding for bitcast" bounty.
I've tried to make a quick fix in #9073 but it obviously requires more work (and it was out of scope of the initial bounty).
This PR adds tests showing some problematic cases. Setting `truncate_output=True` in `exec_alu` fixes some of them but this is far from being a complete solution. At the very least you need a much better test suite.

Test broken const folding wraparound behavior

---

tinygrad/viz/serve.py

new `VIZ=1 python test/test_ops.py TestOps.test_add`
The graph is actually so clean now, void doesn't add that much value to the node.

don't display void dtype in viz nodes [pr]

---

test/test_assign.py
tinygrad/engine/schedule.py
tinygrad/ops.py
tinygrad/spec.py
tinygrad/viz/serve.py

on my M1:
```
~/code/tinygrad (kernel_map2) > python ./test/external/external_benchmark_schedule.py 
***** model tensor in     35.02 ms
***** model schedule in  135.67 ms
~/code/tinygrad (master) > python ./test/external/external_benchmark_schedule.py 
***** model tensor in     34.75 ms
***** model schedule in  122.88 ms
```
This diff constructs a sched_sink with KERNEL, ASSIGN and BUFFER such that the toposort is always valid, removing the need for a special PRELOAD and additional complexity in BFS. `sched_sink.toposort` is always correct.
This is not O(n^2) anymore because KERNEL replaces `break_sched` completely.
Thus, it requires a bigger diff than [try 2
](https://github.com/tinygrad/tinygrad/pull/8925)
In a future iteration I want KERNEL to replace the `realize_map` construction as …

KERNEL op try 3

---

test/unit/test_helpers.py
tinygrad/engine/realize.py
tinygrad/engine/search.py
tinygrad/helpers.py

**Before:**
```
0.00s:                 from   1 ->   1 actions 1024 1024 1024
18.37s:    409654.60 us from   6 ->   6 actions 1024  256 1024    4
29.96s:    125520.07 us from  12 ->  11 actions  256  256 1024    4    4
35.11s:     86910.17 us from  12 ->  12 actions  128  256 1024    4    4    2
40.31s:     86910.17 us from  12 ->  12 actions  128  256 1024    4    4    2
*** LLVM      10 r_128_256_1024_4_4_2                      arg  3 mem  0.01 GB tm     81.16ms/    93.54ms (    26.46 GFLOPS    0.2|19.9    GB/s) ['matmul']
```
**After:**
```
0.00s:                from   1 ->   1 actions 1024 1024 1024
22.33s:       423.46ms from   6 ->   6 actions 1024  256 1024    4
34.47s:       132.41ms from  12 ->  11 actions  256  256 1024    4    4
39.71s:        90.93ms from  12 ->  12 actions …
```

Use proper units when printing beam time

---

tinygrad/engine/schedule.py

The KERNEL/ASSIGN graph expresses this already. This is a prep for removing ScheduleItem and just using UOps from sched_sink.

change writable buffers refcount from the kernel graph [pr]

---

examples/mlperf/dataloader.py
examples/mlperf/helpers.py
examples/mlperf/model_train.py

python time 45ms -> 9ms, it was spending time to schedule the shard
also init bert data on CLANG since it's from numpy, so we don't create the tensor on default device then shard into GPUS
https://wandb.ai/chenyuxyz/MLPerf-BERT/runs/owclcozb/overview 8% faster per step

put bert data shard inside jit

---

tinygrad/viz/index.html

It used to say "no rewrites", match_count is different from graphs length!

hotfix: viz should show if there's a rewrite [pr]

---

tinygrad/engine/schedule.py

This makes #9165's more cleaner, we need this because "make things that can't be images not images" is a UPat in that branch. But on its own, this is a NOOP change, `sym` always also merges the views.

match image cast folding on the cast itself [pr]

---

tinygrad/engine/schedule.py
tinygrad/ops.py
tinygrad/viz/index.html

This refactor completely removes the need for an extra "bufferization" stage.
The Tensor UOps from tensor_map are directly used in the grouping logic. Only once a KERNEL UOp is created, we initialize BUFFER UOps.
We can do this by mapping the simplified Tensor UOps to `KERNEL` UOps (see `kernel_map`). So even though the original tensor UOps are rewritten, we have a link from the BUFFER to the Tensor UOp.
benchmarks:
```
~/code/tinygrad (map_tensors) > PYTHONPATH=. python3 test/external/external_benchmark_schedule.py
***** model tensor in     27.98 ms
***** model schedule in  120.38 ms
~/code/tinygrad (master) > PYTHONPATH=. python3 test/external/external_benchmark_schedule.py
***** model tensor in     28.32 ms
***** model schedule in  123.40 ms
```
There are some more deletions this …

do not create buffers we never realize in scheduler

---

.github/workflows/test.yml
docs/env_vars.md
tinygrad/runtime/ops_webgpu.py

`WEBGPU_BACKEND="WGPUBackendType_*"` now allows to force a backend. Some systems might allow multiple backends (OpenGL, Vulkan), and we sometimes want to select something other than the default. If the `env` is omitted, Dawn will select a default one.

Force WebGPU backend type [pr]

---

tinygrad/engine/schedule.py

If the DEBUG=2 for image fixup adds value I'm open to adding it back, I think since we have VIZ it's not needed anymore.
The new cycle assert makes it easier to find the KERNEL in VIZ:
```
RuntimeError: cycle detected in graph, kernel for UOp(Ops.BUFFER, dtypes.float, arg=4, src=(
UOp(Ops.DEVICE, dtypes.void, arg='METAL', src=()),
UOp(Ops.UNIQUE, dtypes.void, arg=2, src=()),)) must either depend on ASSIGN or BUFFER
```

scheduler cleanups + better cycle assert [pr]

---

examples/mlperf/dataloader.py
examples/mlperf/helpers.py
extra/models/bert.py

original data was int32 for these. float might have caused precision issues
4 runs converged fine

bert use int32 for input ids

---

.github/workflows/test.yml
setup.py

VIZ did not run at all after pip install because the package was not included in the tinygrad installation. This was also reported in #9158.
Now tinygrad includes the VIZ server and client assets in the package installation:
```
~> ls -l /opt/homebrew/lib/python3.11/site-packages/tinygrad/viz/
total 80
drwxr-xr-x  6 qazal  admin    192 Feb 20 14:59 assets
-rw-r--r--  1 qazal  admin  18544 Feb 20 14:59 index.html
-rw-r--r--  1 qazal  admin   4458 Feb 20 14:59 perfetto.html
-rw-r--r--  1 qazal  admin  11395 Feb 20 14:59 serve.py
```

Fix running VIZ=1 after package installation + test

---

test/test_conv_shapetracker.py
test/test_image_dtype.py
test/test_linearizer.py
test/test_multitensor.py
test/test_schedule.py
test/test_search.py
tinygrad/engine/schedule.py

These are expressed in the Kernel graph now. Schedule linearization no longer relies on ScheduleItem for the toposort, as the toposort of `sched_sink` is always correct.
The memory_planner currently accesses Buffer objects directly, could it just use the BUFFER UOp?
In master the progression of Tensor.schedule rewrites is:
1. const folding + movement_ops->view
2. break into KERNEL
3. linearize the sched_sink
3. convert Kernel UOp to ScheduleItem (this creates Buffer)
4. memory_planner
5. lower_schedule_item

remove inputs+outputs attributes from ScheduleItem [pr]

---

tinygrad/engine/schedule.py
tinygrad/spec.py

When schedule is called on a childless const/var/bind sched_sink just becomes a SINK with 0 kernels:
Prep for #9201.

no early return + allow childless const/bind/var in kernel graph [pr]

---

.github/workflows/test.yml

was failing with `line 1: pytest: command not found`

really run test_ops with TINY_BACKEND in ci

---

examples/llama3.py
tinygrad/helpers.py
tinygrad/viz/serve.py

Encountered `IndexError: list index out of range` when calling `memsize_to_str()` with inputs <= 1. This PR fixes the issue:
```py
from tinygrad.helpers import memsize_to_str
print(memsize_to_str(0))  # error -> 0.00 B
print(memsize_to_str(1))  # error -> 1.00 B
print(memsize_to_str(1000))  # 1000.00 B -> 1.00 KB
print(memsize_to_str(1234))  # same
```
Since there are no existing tests for `memsize_to_str()`, I haven't added any new ones. Let me know if you'd like tests to be included.

remove unused memsize_to_str and minor cleanups [pr]

---

tinygrad/engine/schedule.py
tinygrad/ops.py

```
VIZ=1 python test/test_schedule.py TestSchedule.test_preserve_multistage_reduce
```
The last reduceop becomes two KERNEL UOps:
And the output tensor UOp realizes to the reshape of BUFFER 8:
```
UOp(Ops.RESHAPE, dtypes.float, arg=(), src=(
UOp(Ops.BUFFER, dtypes.float, arg=1, src=(
UOp(Ops.DEVICE, dtypes.void, arg='METAL', src=()),
UOp(Ops.UNIQUE, dtypes.void, arg=8, src=()),)),))
```
This diff can go before the generic movement op reverser, I'm working on the generic becomes_map in #9210, that will allow for more ways of realizing Tensor UOps into any view of a buffer.

move split_reduceop to scheduler + enable it for multi

---

test/test_pickle.py
tinygrad/ops.py

After KERNEL UOp we don't allow for STORE(BUFFER)/LOAD(BUFFER), these are always created with DEFINE_GLOBAL.

simpler buf_uop [pr]

---

tinygrad/shape/shapetracker.py

The split_reduceop UPat calls this in the scheduler simplifier, so we end up with noise in the scheduler VIZ.

set TRACK_MATCH_STATS=0 for real_strides [pr]

---

test/models/test_real_world.py
test/test_schedule.py
test/unit/test_gradient.py
test/unit/test_tensor_uop_representation.py
tinygrad/engine/schedule.py
tinygrad/nn/optim.py
tinygrad/ops.py
tinygrad/spec.py

This diff enables the scheduler to simplify Tensor UOps to any VIEW of a BUFFER. Previously, this was limited to just RESHAPE(BUFFER), thus things like reorder_expand would not be possible.
Allowing non-contiguous VIEW(BUFFER) realizes revealed a bug in the SGD ASSIGN, where `self.b[i]` becomes a permuted VIEW. We do not allow for `t.assign(t.permute(...))`. I'm working on the diff to automatically insert contiguous in the graph when permuted ASSIGN is detected https://github.com/tinygrad/tinygrad/pull/9220.

allow VIEW(BUFFER) in Tensor UOps [pr]

---

tinygrad/ops.py

This should always be handled by the symbolic pattern matcher.

delete cast early folding from ops [pr]

---

test/unit/test_attention.py
tinygrad/tensor.py

saved some memory because exp (which is used for backward) are done in half. training bert seems fine and can fit BS=78 now (from 66)

move cast to before softmax in attention

---

tinygrad/engine/schedule.py
tinygrad/ops.py
tinygrad/spec.py
tinygrad/viz/serve.py

BUFFER_VIEW used to have a VIEW source, now it has a BUFFER source and a (size, offset) arg.
Example of shape-changing bitcast rewriting to a BUFFER_VIEW:
```
VIZ=1 python test/unit/test_disk_tensor.py TestDiskTensor.test_simple_read_bitcast_alt
```
This diff also changes the shape of BUFFER_VIEW to be flat, thus, in the rewrite of BITCAST to BUFFER_VIEW there may be a downstream reshape.
We multiply offset **from the ShapeTracker** with the base itemsize to create the device subbuffer: 
This is still done in the scheduler, I am following up with a diff to support BUFFER_VIEW as a kernel graph edge. Mapping a BUFFER_VIEW to a device.py subbuffer should be done in ops.

implement the new subbuffer spec for DISK [pr]

---

examples/mlperf/model_train.py

`LLVM=1 BERT_SIZE="tiny" DEFAULT_FLOAT=HALF BENCHMARK=5 MODEL="bert" python3 examples/mlperf/model_train.py` runs for me with this. it should not failed with single device shard though

hotfix bert no shard with only one device

---

test/test_const_folding.py
test/test_image_dtype.py
test/test_schedule.py
test/unit/test_tensor_uop_representation.py
tinygrad/ops.py
tinygrad/spec.py
tinygrad/tensor.py

Previously "is_realized" and a Tensor mapping to a BUFFER (even if it is unallocated) meant the same thing.
This diff separates scheduling/becomes_map from realization further by making is_realized only apply if the Buffer is allocated on device.
This also fixes the [issue reported on discord](https://discord.com/channels/1068976834382925865/1069001075828469790/1343587073164050578) regarding using Tensor.empty as a JIT input_rawbuffer.
test_const_folding and test_schedule only call create_schedule and do not execute any kernels, I changed the tests to check the BUFFER op instead of the `is_realized` property.

is_realized only if buffer is allocated

---

tinygrad/engine/schedule.py
tinygrad/ops.py

Working on #9242+setitem revealed this refactor,
a Tensor UOp ASSIGN is the same as ASSIGN in kernel graph, with src[1] substituted with KERNEL + an (optional) swizzle of the STORE ShapeTracker. This diff is a refactor toward p1,
following up with deleting ASSIGN from the KERNEL AST-while preserving the swizzle-

substitute assign source for KERNEL + comments [pr]

---

test/test_ops.py

instead of `(out+1).square().mean().backward()`, use forward.sum().gradient to get closer to the gradients

update test_ops backward tests

---

docs/quickstart.md
docs/tensor/elementwise.md
examples/mnist_gan.py
examples/so_vits_svc.py
examples/vgg7_helpers/waifu2x.py
examples/vits.py
examples/yolov3.py
extra/onnx.py
extra/torch_backend/backend.py
test/test_ops.py
tinygrad/tensor.py

This PR renames `leakyrelu` to `leaky_relu` to match `torch`'s naming. This addresses one of the issues in #9262.

Rename leakyrelu to leaky_relu

---

tinygrad/tensor.py

rendered as `*(data0+alu0) = ((val0<0.0f)?(0.01f*val0):val0);` instead of two wheres.
possible to update rewrite rules too

simpler leaky_relu

---

tinygrad/runtime/ops_nv.py

remove hardcoded cbuf0 size (for Blackwell & hopper)

nv: parse elf attrs

---

.github/workflows/test.yml
extra/torch_backend/backend.py
extra/torch_backend/test.py

It runs but with some performance and accuracy issues.
Few notes:
- Had to workaround thrown errors regarding events and streams in the DeviceGuardImplInterface and made them no-ops. Unsure if this is right.
- Patched pytorch Optimizer class to realize weight and optimizer state tensors on step. Otherwise computation graph blew up.
- Edited test file to delay float conversion as the kernel is gather samples is already really slow and 2x worse with float. Matches behavior of other beautiful_mnist example,

(bounty) Make mnist training run with torch backend

---

test/test_schedule.py
tinygrad/engine/schedule.py

bert has many elementwise kernels that just store a half:
```
VIZ=1 GPU=1 BERT_SIZE="tiny" DEFAULT_FLOAT=HALF BENCHMARK=5 MODEL="bert" python examples/mlperf/model_train.py
```
from the 84th scheduler call:
`CAST_AFTER_EXPAND=1` decreases number of ScheduleItems from 100 -> 59 for eval and  550 to 505 for the training step.
However, this is slower in benchmarks because it's using less flops:

test: recompute expanded CAST

---

tinygrad/engine/schedule.py
tinygrad/ops.py

This is a refactor of the BFS + kernel creation toward #9242, adding COPY as a node to the kernel graph, and returning becomes_map from the schedule.
All of these are requiring generic refactors to the flow of rewrites after `tensor_map`.

substitute ast from kernel op [pr]

---

examples/mlperf/dataloader.py
tinygrad/engine/jit.py
tinygrad/engine/realize.py
tinygrad/engine/schedule.py
tinygrad/ops.py
tinygrad/spec.py

We can treat subbuffers like normal BUFFERs for downstream KERNEL ops. Instead of loading a Buffer, the child kernel loads a subbuffer.
This enables deleting ViewOp Runner because BUFFER_VIEW has the complete information to construct the subbuffer when the KERNEL/COPY child runs:
The difference is that a childless subbuffer will not be allocated, I updated the mlperf data loader to use buffer and call ensure_allocated. We should just move these to the scheduler.

BUFFER_VIEW is a node in the kernel graph + delete ViewOp

---

extra/models/bert.py
test/test_dtype.py
tinygrad/dtype.py

en route for div rounding mode. dtype of true int division would change from int32 to default_float, which matches torch too.

least_upper_float is at least default_float

---

examples/mlperf/dataloader.py
tinygrad/engine/jit.py
tinygrad/engine/realize.py
tinygrad/engine/schedule.py
tinygrad/ops.py
tinygrad/spec.py

This made bert scheduling time twice slower, though I don't see a huge change in external_benchmark_schedule.py
```
~/code/tinygrad (revert_view_op) > python test/external/external_benchmark_schedule.py
***** model tensor in     35.44 ms
***** model schedule in  142.11 ms
***** model opts(32) in  200.02 ms
***** model lower in     171.37 ms
***** model rewrite in   457.14 ms
***** model linearize in 236.08 ms
20232
all 1243.71 ms
~/code/tinygrad (master) > python test/external/external_benchmark_schedule.py
***** model tensor in     34.98 ms
***** model schedule in  141.65 ms
***** model opts(32) in  190.24 ms
***** model lower in     172.29 ms
***** model rewrite in   462.35 ms
***** model linearize in 237.73 ms
20232
all 1240.78 ms
```

revert buffer_view change

---

extra/torch_backend/backend.py
extra/torch_backend/test.py

Fix copy to cast as that is the expected behavior [here](https://github.com/pytorch/pytorch/blob/af720cd5a7edafbf3ee791ce4aaa52a5da2049f6/torch/csrc/lazy/ts_backend/tensor_aten_ops.cpp#L56).
After this commit, the image AE models from https://github.com/madebyollin/taesd should work. Tested in ComfyUI, quite simple to patch in tinygrad. Tried an actual SDXL VAE and it runs but produces incorrect results.

torch fix casting and add ops for sd vae(s)

---

tinygrad/runtime/ops_amd.py

```python
self.pkt3(amd_gpu.PACKET3_SET_SH_REG, gfxreg(amd_gpu.regCOMPUTE_RESTART_X), 0, 0, 0, 0)
```
Will write zero to regCOMPUTE_RESTART_{X,Y,Z} and regCOMPUTE_THREAD_TRACE_ENABLE because of:
```python
regCOMPUTE_RESTART_X = 0x1bbb
regCOMPUTE_RESTART_Y = 0x1bbc
regCOMPUTE_RESTART_Z = 0x1bbd
regCOMPUTE_THREAD_TRACE_ENABLE = 0x1bbe
```
There is also a similar "oob"-write to regCOMPUTE_PIPELINESTAT_ENABLE and regCOMPUTE_PERFCOUNT_ENABLE in:
```python
self.pkt3(amd_gpu.PACKET3_SET_SH_REG, gfxreg(amd_gpu.regCOMPUTE_START_X), 0, 0, 0, *local_size, 0, 0)
```
But it doesn't seem to be strictly required for SQTT, so i left it alone

Do not "oob"-write zero to regCOMPUTE_THREAD_TRACE_ENABLE every exec

---

test/test_multitensor.py

In multi, when the result of an operation is needed on another device, we copy it on the destination device after the operation. this is fine for most cases, and is handled well in scheduling. 
However, in case of a binary op that expands its inputs, 
There's no rule in scheduler that moves copy before binary op. 
and really it doesn't make sense as a rule in scheduler. I think it should be a rule in get_multi_map. because there we expect this type of copy between devices, and moving copies to the beginning (after buffer) makes sense (it's basically all_gather).
I visualize what I mean,
Executing this code
```python
a = Tensor.empty(16, 1).shard_(devices_2, axis=0)
b = Tensor.empty(16, 16).to_(devices_2)
c = Tensor.empty(16, 16).shard_(devices_2, axis=1)
d = a+b
(d*c).realize()
```
This …

Failing test for not realizing intermediate expand in multi-GPU

---

tinygrad/codegen/symbolic.py

Since floats are not being flipped anymore this should help with const folding for floats

Make const moving not depend on the order

---

extra/torch_backend/backend.py
extra/torch_backend/test.py

Should keep context classes alive for manual __enter__.
Issue appeared when calling str() on a cpu tensor after backend is imported. Torch tensor str() interacts with list of TorchDispatchMode objects and hence segfault on bad ref.

fix TORCH_DEBUG=1 sigsegv

---

.github/workflows/test.yml
test/unit/test_disk_tensor.py
tinygrad/runtime/ops_disk.py

This PR fixes a bug where on macOS, with disk buffers > 2 GiB, not all data was copied, when copying from disk device to CPU device.
Reproducer: (second assertion fails on macOS before this diff):
```
import os
from tinygrad import Tensor, dtypes, Device
from tinygrad.helpers import fetch
model_path = str(fetch("https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-f16.gguf", "Llama-3.2-1B-Instruct-f16.gguf", subdir="llama3-1b-instruct"))
Device.DEFAULT="CPU"
start = 2425053024
x = Tensor.empty(os.stat(model_path).st_size, dtype=dtypes.uint8, device=f"disk:{model_path}")
assert not all(i==0 for i in x[start:].tolist())
y = Tensor.empty(os.stat(model_path).st_size, dtype=dtypes.uint8, device=f"disk:{model_path}").to(Device.DEFAULT)
assert not …
```

hotfix: load >2 GiB from disk on macOS

---

test/test_schedule.py
tinygrad/engine/schedule.py
tinygrad/ops.py

There are two advantages to adding buffer ops last:
1. Smaller graph while we're swizzling views to the edges (view_left+view_right)
2. No need for things like https://github.com/tinygrad/tinygrad/pull/9377 if we already know the VIEW(CONST) is the last and final representation (pre opts)

prep refactor for adding buffer ops last [pr]

---

tinygrad/engine/schedule.py
tinygrad/ops.py
tinygrad/spec.py

New graph of the bert kernels:
Instead of using a VIEW, in a partial ASSIGN we substitute the source for an offset buffer.
This is about 2-3% slower than master because instead of preserving the output shape in the ASSIGN node, we need to recurse to find the output shape of an ASSIGN(BUFFER, KERNEL) parent, as these nodes only define a size. This needs to happen in all downstream children in big_sink.

remove views from the kernel graph minimum diff

---

tinygrad/runtime/ops_amd.py

#9365 broke amd driver on non gfx1030
it should instead be capped to `0x7000` following https://github.com/torvalds/linux/blob/21e4543a2e2f8538373d1d19264c4bae6f13e798/drivers/gpu/drm/amd/amdkfd/kfd_queue.c#L441-L447

fix: correct gfx10 ctl stack size

---

.github/workflows/test.yml
extra/torch_backend/backend.py
extra/torch_backend/test_inplace.py

Torch in-place operations on views aren't common but they do happen.
This spawned off from #9317 since DistributedDataParallel internally uses views for its gradients and in-place updates.
TODOs:

torch: support in-place operations on views

---

extra/torch_backend/backend.py

Realize all tensors on optimizer step.
Things like running stats from batch norm aren't captured in optimizer state or parameters. One would need to hook the model (isn't an easy way to get at it from the optimizer) and/or the specific layers. This is more foolproof, maybe sub-optimal.

fix torch backend memory leak

---

.gitignore

When running
```
examples/mlperf/training_submission_v5.0/tinycorp/benchmarks/bert/implementations/tinybox_green/run_and_time.sh
```
the logfiles are in root and `git add .` tries to add them.
Also removing master_schedule.py as this is no longer a thing with the new process_replay.py

hotfix:  gitignore *.log [pr]

---

tinygrad/runtime/support/am/ip.py

`unord_disp=1` is a workaround for a deadlock running compute and graphics. we do not run graphics, we do not need this.

am: turn off unord dispatch

---

extra/gemm/simple_matmul.py

As requested by George on discord
Using generator for ints but not for floats due to the following benchmarks
```
np.random.randint   : 2.6765651249997973
rng.integers        : 1.0878237079996325
np.random.rand      : 1.4534849159999794
rng.random          : 1.8805371250000462
```

`simple_matmul.py` uses np to generate random

---

extra/onnx.py
extra/replay_pkl.py
tinygrad/codegen/devectorizer.py
tinygrad/codegen/kernel.py
tinygrad/renderer/cstyle.py
tinygrad/runtime/ops_dsp.py

`export PATH=/opt/homebrew/Cellar/llvm/19.1.7_1/bin:$PATH`
`DEBUG=2 CNT=4 DEVECTORIZE=0 CPU=1 DONT_REALIZE_EXPAND=1 QUANT=1 python3 examples/test_onnx_imagenet.py https://github.com/xamcat/mobcat-samples/raw/refs/heads/master/onnx_runtime/InferencingSample/InferencingSample/mobilenetv2-7.onnx`
`DEBUG=2 CNT=4 DEVECTORIZE=0 CPU=1 DONT_REALIZE_EXPAND=1 python3 examples/test_onnx_imagenet.py /tmp/model.quant.onnx`
`ALIGNED=0 QUANTIZE=1 DEBUG=2 DEVECTORIZE=0 python3 extra/replay_pkl.py /tmp/im.pkl`

Fast DSP for MobileNetV2 (try 2)

---

test/test_dtype.py

The global size is very large (781250 gidx) and the emulated version takes more than 1 minute to execute the kernel.

hotfix: skip test_mean_half_precision_underflow on amd ci

---

test/test_schedule.py

Since alu2 already depends on alu1 we don't need the extra `alu2?alu1:0`:
```diff
kernel void E_4_511(device float* data0, device float* data1, uint3 gid [[threadgroup_position_in_grid]], uint3 lid [[thread_position_in_threadgroup]]) {
int gidx0 = gid.x; /* 511 */
int gidx1 = gid.y; /* 4 */
int alu0 = (gidx0+(gidx1<<8));
bool alu1 = ((gidx0<255)!=1);
bool alu2 = (alu1&((alu0<257)!=1));
float val0 = (alu2?*(data1+(alu0+-257)):0.0f);
- *(data0+(gidx0+(gidx1*511))) = (val0+((alu2?alu1:0)?0.0f:(alu1?((float)(-INFINITY)):0.0f))+(alu1?0.0f:((float)(-INFINITY))));
+ *(data0+(gidx0+(gidx1*511))) = (val0+(alu2?0.0f:(alu1?((float)(-INFINITY)):0.0f))+(alu1?0.0f:((float)(-INFINITY))));
}
```

simple failing test for extra ops in VALID [pr]

---

test/test_schedule.py
tinygrad/engine/schedule.py
tinygrad/ops.py

This was creating nan in the new_grouper branch because it pushed the padded view through the recip:
Currently the existing grouper handles this by recursing the graph locally (at the MUL), the new grouper will push the VIEW left, past the mul, and when we reach the unsafe op, insert a contiguous.

fix view_left for unsafe pad ops [pr]

---

test/test_randomness.py
tinygrad/tensor.py

not sure if it's always like this, but increment before _threefry_random_bits is incorrect. the counts should start with random numbers generated so far.
use jax to generate 20 + 20 + 10 random numbers, the first 20 + 20 matches and the last 10 are different. just moving increment after _threefry_random_bits matches the number but jit test fails

failed test case for threefry

---

test/test_rewrite_tracked_childen.py

```
File "/Users/qazal/code/tinygrad/test/test_rewrite_tracked_childen.py", line 53, in print_children
print(ctx.children[r])
~~~~~~~~~~~~^^^
KeyError: UOp(Ops.REDUCE_AXIS, dtypes.float, arg=(Ops.ADD, (0, 1)), src=(
UOp(Ops.VIEW, dtypes.float, arg=ShapeTracker(views=(View(shape=(3, 3), strides=(3, 1), offset=0, mask=None, contiguous=True),)), src=(
UOp(Ops.BUFFER, dtypes.float, arg=9, src=(
UOp(Ops.DEVICE, dtypes.void, arg='METAL', src=()),
UOp(Ops.UNIQUE, dtypes.void, arg=0, src=()),)),)),))
```
After (a+0).sum() becomes a.sum()

simple failing test for graph_rewrite children [pr]

---

tinygrad/ops.py

Threefry wasn't fusing correctly in the new_grouper branch because this VIEW(ASSIGN) pushed to the left:
we always realize ASSIGN so it shouldn't swizzle, it's free to just VIEW the buffer

do not view_left assign + elementwise sources always have a shape [pr]

---

test/test_schedule.py

This needs to check the `n` dimensions before putting the reduces in a single kernel.
ideally we'd want to fuse the ADD and one of the reduces, and LOAD the other one.

simple failing test for scheduling parallel reduce [pr]

---

.github/actions/setup-tinygrad/action.yml

llvm 19 is the stable branch according to https://apt.llvm.org

use libllvm19 in ci (no_comgr prereq)

---

test/mockgpu/amd/amdgpu.py

the follow mapped ranges cause `assert prg_sz > 0` fails
```txt
st             st+sz           prg_addr
0x7370607f7000 0x7370607f8000 0x7370607f7000
0x7370607f6000 0x7370607f7000 0x7370607f7000
```

fix prg size calculation when there are adjacent mapped ranges(no_comgr prereq)

---

test/test_renderer_failures.py
test/test_uops.py
test/unit/test_simplify_valid_idx.py
tinygrad/codegen/devectorizer.py
tinygrad/ops.py
tinygrad/renderer/cstyle.py
tinygrad/renderer/llvmir.py
tinygrad/renderer/ptx.py
tinygrad/renderer/wgsl.py
tinygrad/runtime/ops_python.py
tinygrad/spec.py

To check if INDEX is out of bounds, we need three things:
1. buffer size
2. min/max of alu
3. mask
The devectorizer in master removes this mask before renderer. This diff refactors the renderers to keep the mask in INDEX.
PTX does not directly render INDEX, so we still move the mask to LOAD/STORE before doing the pointer arithmetic. This move is safe because in the final linearization of PTX UOps, INDEX doesn't exist.

remove move_mask from the devectorizer

---

tinygrad/engine/schedule.py

The DSP E kernel removal comes down to writing the matcher that reorders the VIEW after elementwise ops to the downcast:
We have this rule in a bunch of places now. It's a more generic case of the CAST_BEFORE_VIEW and reorder EXPAND rule.

add reorder_view matcher to scheduler [pr]

---

examples/mlperf/losses.py
test/external/external_test_datasets.py

This PR contains some cleanups for both the loss and dataset files. I saw them while I rebased #8385.
This should've been cleaned up in their respective PRs. I'll double check these types of changes in my future PRs.

RetinaNet loss and test cleanups

---

.github/actions/setup-tinygrad/action.yml
.github/workflows/test.yml
test/test_transcendental.py
tinygrad/runtime/ops_dsp.py

Fix for bounty: "Add sqrt support to transcendentals, fixing DSP=1 python test/test_tiny.py TestTiny.test_mnist_model with test"
Fixes log2, exp2, pow and sqrt.
sin is not working right now (will be address by #9541).

Fix DSP transcendentals

---

docs/developer/hcq.md
tinygrad/runtime/graph/hcq.py
tinygrad/runtime/ops_amd.py
tinygrad/runtime/ops_nv.py
tinygrad/runtime/support/hcq.py

`AMDComputeQueue.__del__` frees `hw_page` which is safe because `AMDAllocator._free` does `self.dev.synchronize()` which is supposed to wait for execution of IB to finish, however that doesn't happen if AMDComputeQueue is dropped right after submit before timeline signal is incremented, which it is in most places leading to a race if .bind() is also used (required for multi-xcc because bug in mec fw treats all PACKET3_PRED_EXECs outside IBs as if they had EXEC_COUNT of zero).

HCQ: Increment timeline signal before submitting

---

tinygrad/engine/schedule.py
tinygrad/viz/index.html
tinygrad/viz/lib/graph.js

This all needs to be integrated with the main kernel graph and have hover/click support.
You can see a start in "View Memory Graph" under the schedule viz
I think the d3 implementation and the data structures will stay, most of the iterations from here is gonna be in improving how we get these traces+metadata about the buffers.

start viz of memory usage

---

tinygrad/viz/lib/graph.js

```
VIZ=1 python ./examples/beautiful_mnist.py
```
shows if it's a weight buffer + some more info:
and highlights all the steps:
The children map can also help with looking up the KERNEL of a buffer.

show buffer info in memory viz

---

test/test_gc.py

This also fails in nimlgen's new memory planner https://github.com/tinygrad/tinygrad/pull/9526#issuecomment-2748480115.
The GC behaves correctly on the real Buffer and the UOp.
The JIT and memory planner still use a custom lb_refcount attribute.
It expects to count alive BUFFER UOps referring to a device.py Buffer, `TestGC.test_buffer_refcount` describes this spec, but higher-level tests are very dependent on the implementation of memory_planner and JIT.

failing test for UOp buffer ref count

---

tinygrad/viz/README

VIZ has already replaced it so the link doesn't exist anymore.

hotfix: replace link in viz/readme

---

test/test_gc.py
tinygrad/engine/schedule.py
tinygrad/ops.py

`lb_refcount` needs to count alive BUFFER UOps referencing the device.py Buffer.
But schedule only increments references for the new intermediate buffers it creates, or buffers it assigns to.
The new memory planner fails for Tensor.empty https://github.com/tinygrad/tinygrad/pull/9526#issuecomment-2748480115 since there's no ScheduleItem for it, might be more correct to put this when we create a Buffer.

move Buffer refcount increment outside of schedule.py

---

tinygrad/viz/lib/graph.js

eg this is for bert training with BATCH_SIZE=11
```
VIZ=1 GPU=1 BERT_SIZE="tiny" DEFAULT_FLOAT=HALF BENCHMARK=5 MODEL="bert" python examples/mlperf/model_train.py
```
The children are in UOp toposort order, so the first one is the STORE and other ones are LOAD.

display kernel metadata in memory viz

---

tinygrad/viz/lib/graph.js

For `VIZ=1 python ./examples/beautiful_mnist.py`
This nicely shows the peak memory usage is from a conv that stores a 655MB Tensor. in DEBUG=2 we go from 0.15GB to 0.81GB mem_used:

better yaxis formatting in viz memory graph

---

examples/other_mnist/beautiful_mnist_torch.py

Now it shouldn't crash when running on a tinybox.
```
~/code/tinygrad (torch_select_device) > time DEBUG=1 python ./examples/other_mnist/beautiful_mnist_torch.py 
opened device NV from pid:1634738
using torch backend cuda
opened device DISK:/raid/downloads/e8e6ed0857e9bb000985bfea8283b0b3.gunzip from pid:1634738
opened device CPU from pid:1634738
opened device DISK:/raid/downloads/684fe191a76d9107981692e6f0d3842f.gunzip from pid:1634738
opened device DISK:/raid/downloads/40a9ec2164c7887e8a5f1225de927907.gunzip from pid:1634738
opened device DISK:/raid/downloads/7b1e157ab43d54d0946f76d1bb6df574.gunzip from pid:1634738
loss:   0.07 test_accuracy: 98.26%: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 70/70 …
```

select torch device in examples/beautiful_mnist_torch.py

---

examples/other_mnist/beautiful_mnist_torch.py

The purple is from relu forward
```
??:0:at::_ops::relu::call(at::Tensor const&)
python_torch_functions_2.cpp:0:torch::autograd::THPVariable_relu(_object*, _object*, _object*)
/home/qazal/.local/lib/python3.10/site-packages/torch/nn/functional.py:1704:relu
/home/qazal/code/tinygrad/./examples/other_mnist/beautiful_mnist_torch.py:20:forward
??:0:PyMethod_New
/home/qazal/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:1750:_call_impl
??:0:PyMethod_New
/home/qazal/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:1739:_wrapped_call_impl
??:0:PyInit__datetime
/home/qazal/code/tinygrad/./examples/other_mnist/beautiful_mnist_torch.py:60:<module>
```

add TORCHVIZ=1 to beautiful_mnist_torch

---

tinygrad/viz/lib/graph.js
tinygrad/viz/lib/worker.js

It shouldn't have to go to the server for every graph. Before and after server logs:

cache viz worker at launch

---

tinygrad/viz/serve.py

If `track_rewrites` resolves in linearize the self.uops attribute exists,
If the linearizer fails we don't have a render for that Kernel.
It should not have to re-linearize every captured kernel.
VIZ=1 of beautiful_mnist startup time 671.35ms vs master 4648.38ms.

hotfix: use captured uops in viz render [pr]

---

tinygrad/ops.py

This reverts commit f1a35bbb5438955c2dac624aef912ff80bc748eb.
Bert segfaulted in master. Did not happen in update_benchmark https://github.com/tinygrad/tinygrad/compare/593cba8a70c68060806cafd9453aa272e2e8706d...d9d82c9081d63c863c1f347a905202ad34951409.

Revert "do not block gc in UOp.toposort (#9623)"

---

examples/mlperf/model_train.py

fix when only run eval `TRAIN=0 BERT_SIZE=tiny examples/mlperf/training_submission_v5.0/tinycorp/benchmarks/bert/implementations/tinybox_green/dev_beam.sh`

fix bert free_intermediates

---

extra/torch_backend/backend.py
extra/torch_backend/test.py
extra/torch_backend/wrapped_tensor.cpp

Report correct strides and offset to torch. The offset is necessary as part of some of the backwards as_strided calculations that torch does (like in [CopySlices](https://github.com/pytorch/pytorch/blob/c97632154108f27a84ae843844b3f7fd15994c65/torch/csrc/autograd/functions/tensor.cpp#L199)).
Fix to repeat not being a view.
Fix to behavior of as_strided. The operation should perform on the base "storage" and doesn't stack. Added test.
Some TODOs added where we need to be respecting requested strides.
Mostly as a result of investigation into `TINY_BACKEND=1 python test/test_ops.py TestOps.test_pad_circular_mode` failure.
The test now passes, but others are still failing. Looking to see results on #9302
This also fixed test_cat but broke two einsum tests, taking a look at those next.

torch backend: partial fix for strided related test fails

---

tinygrad/spec.py

in some cases (if there's a where in idx) the vmin/vmax might not be tight

print idx when OUT OF BOUNDS ACCESS

---

test/test_linearizer.py

Came up on #9606 
In the tests `helper_tc_allclose` and `helper_tc_ensure_uops_and_opts_count` `k` is first used as value for `K` dimension and then is reused for kernel `k = Kernel(realized_ast)`.
This standalone pr only changes syntax for the other dimensions.

Uppercase `N` and `M`

---

tinygrad/engine/schedule.py

eg fusing this arange with the merged conv bw is fine, the assert does not really belong in this pattern.
Deciding if two reduces should group is a separate concern in the grouper.

merge_double_reduce without asserts [pr]

---

tinygrad/renderer/cstyle.py

Fixes [CI in #9596](https://github.com/tinygrad/tinygrad/actions/runs/14171158999/job/39695067545?pr=9596#step:8:214)
TC=3 was broken for AMD with the same problem

remove `smem_prefix_for_cast` for AMD

---

tinygrad/engine/schedule.py
tinygrad/ops.py

Still useful for scheduling ops that don't use CompiledRunner.

bring GroupOp.Meta back

---

tinygrad/viz/index.html
tinygrad/viz/lib/graph.js

The first step in a rewrite is a new sink passed into graph_rewrite, each of these sinks are different sizes so it makes sense to recenter at the first step.
I've found the kernel graphs go outside the view port a lot when navigating from Tensor graph to smaller AST graphs.

always fit fresh viz graph into view [pr]

---

tinygrad/codegen/kernel.py

I think it is still convenient to have ast printed independently. `VIZ` is great for many things, but for very simple stuff I think the overhead is not worth launching it, that is why I think `DEBUG=5` printing only the `ast` / `modified_ast` is useful.

move uops print to debug >= 6

---

tinygrad/engine/realize.py

`ast` is already printed in `kernel` -> `linearize`, it was being logged twice
https://github.com/tinygrad/tinygrad/blob/a1ee4d587fcd74a01e73236511d1ede3048238cf/tinygrad/codegen/kernel.py#L670
https://github.com/tinygrad/tinygrad/blob/a1ee4d587fcd74a01e73236511d1ede3048238cf/tinygrad/codegen/kernel.py#L675
`applied_opts` are printed on `DEBUG >= 3`
https://github.com/tinygrad/tinygrad/blob/a1ee4d587fcd74a01e73236511d1ede3048238cf/tinygrad/codegen/kernel.py#L674

remove duplicated ast print

---

tinygrad/codegen/symbolic.py
tinygrad/ops.py

it's not wrong because the dtype is never used, but `x.const_like` is more readable

minor div_and_mod_folding cleanup [pr]

---

test/external/process_replay/process_replay.py
tinygrad/codegen/kernel.py

Capturing with RECORD_TRACEBACKS=1 will also include the location of the kernel if process replay fails to generate the diff:
`traceback.extract_stack` is very slow though. If we wanna make this the default process_replay path maybe it should manually recurse sys._getframe.

add RECORD_TRACEBACKS=1 option to process replay

---

tinygrad/runtime/ops_amd.py

Introduced in #9585, probably when i incorrectly resolved merge conflict while rebasing an old, mi300x-only branch. Seems to be the source of multi gpu beam llama hangs

Fix double SDMA_OP_FENCE

---

.github/workflows/test.yml
test/test_renderer_failures.py
tinygrad/runtime/ops_python.py

There was a bug for python backend and gated store, see [CI run](https://github.com/tinygrad/tinygrad/actions/runs/14218735982/job/39841347570#step:5:89) for reference. 
The problem was that the default gate was added where it was not expected. The index zipped the gate with the memory and offset, but the STORE was expecting for the gate to be in the input after the val. I think it's related to the move from the old style load/store to the new one.

fix gated store with index in python backend 

---

test/test_renderer_failures.py

test was failing due to tolerance

Increase `TestPTXFailures::test_gated_define_acc_with_half_dtype` atol and rtol

---

test/test_dtype.py
tinygrad/dtype.py

use torch bfloat16 for groundtruth in test. also a TODO for discrepancy

cleanup truncate_bf16 [pr]

---

extra/models/bert.py

sum of bool by default uses default_float for acc. So without float, it might overflow with a large BS and default_float=HALF.
fixed clsf_accuracy to not be inf in mi300x bert

insert float() in bert acc

---

extra/onnx.py
extra/onnx_helpers.py
test/external/external_test_onnx_backend.py
test/external/external_test_onnx_ops.py

Also removed sequence type support for now because it was barely tested and there was no `sequence_type` usage in top 100 huggingface models. Can add back later with good testing coverage.
Currently we don't have output dtype check yet, but for `test/external/external_test_onnx_ops.py`, ORT does runtime checks on shape and dtype for inputs and outputs.

ONNX add output shape validation

---

tinygrad/codegen/kernel.py

Test with logging locations: https://github.com/tinygrad/tinygrad/actions/runs/14242039304/job/39913970095#step:7:251
traceback.extract_stack is pretty slow https://stackoverflow.com/questions/52073977/why-is-traceback-extract-stack-in-python-so-slow - This is similar to the UPat location stuff that we can stop recursing once the unittest is found.

record unittest location in process replay [pr]

---

test/unit/test_uop_symbolic.py
tinygrad/codegen/symbolic.py

a.where(b.where(c, d), d) -> (a & b).where(c, d). a pattern in optimizer
process replay diff looks surprisingly smart... trying to figure out why

symbolic fold double where

---

test/test_jit.py
tinygrad/engine/jit.py

`optimize_weights` was a poor name from the beginning. `replan_buffers_memory_layout` should better describe what's happening in the function

jit: rename optimize_weights -> replan_buffers_memory_layout

---

examples/mlperf/helpers.py
extra/models/mask_rcnn.py

This PR moves the `BoxCoder` class from `extra/models/mask_rcnn.py` to `examples/mlperf/helpers.py`.
Also, I added a new parameter called `apply_to_remove` to `BoxCoder` since RetinaNet doesn't use it, while `MaskRCNN` uses it.
Lastly, I've updated the `encode` function to support the batch dimension as well for RetinaNet training.

Move BoxCoder to MLPerf helpers

---

examples/mlperf/training_submission_v5.0/tinycorp/benchmarks/bert/implementations/tinybox_red/run_and_time.sh

we should commit to use AM. it's 7ms slower python time now

use AM driver in bert mlperf

---

test/test_ops.py

so get_available_devices is not called when running other tests

move TestOpsFp8s skipTest

---

test/unit/test_rewrite_map.py
tinygrad/engine/grouper.py
tinygrad/ops.py

The scheduler already implements this for mapping Tensors to intermediate buffers, it can be shared infrastructure for the softmax/flash attention fusion rewrites.

multi stage graph_rewrite_map

---

.github/workflows/test.yml
autogen_stubs.sh

Had to autogen newer uapi headers for #9746 (dmabuf export ioctl missing), submitting just the fix without updating to newer headers as they are only needed for infiniband stuff

Fix kfd autogen and verify it in ci

---

extra/datasets/openimages.py

This PR cleans up the old `iterate` dataloader from `openimages` after the recent addition of #9442.

Clean up openimages old dataloader

---

extra/models/retinanet.py

This PR brings in all of the type annotations and loss functions needed for training RetinaNet (#8385). Running `BASE_DIR=/raid/datasets/openimages/ PYTHONPATH=. MODEL=retinanet python3 examples/mlperf/model_eval.py` works as expected.

RetinaNet model type annotations and loss functions

---

test/external/external_benchmark_bert_matmuls.py
test/external/external_benchmark_bert_softmax.py

BS=16, ACC_DTYPE=half for tinybox, BS=128, ACC_DTYPE=float for mi300x

update benchmark bert scripts with BS and ACC_DTYPE

---

examples/mlperf/initializers.py

for some reason with random dropout it creates different ast on each device. And search embedding is slow. This workaround saved 6 minutes setup time on mi300x (25->19) and resulted in similar speed

add contiguous to EmbeddingBert output

---

tinygrad/ops.py
tinygrad/tensor.py

This clearly shows which of the intermediates map to a Buffer in the end:
`VIZ=1 python test/test_tiny.py TestTiny.test_tiny_add`
Between "Multi Map" and "Schedule Map" there's gonna be a "Kernelize Map" here.

give _apply_map_to_tensors substitutes name [pr]

---

test/unit/test_allreduce.py

there's a world that sharding contiguous empty does not create copy kernels, but it does now

use CPU for test_schedule_ring

---

tinygrad/engine/grouper.py
tinygrad/engine/schedule.py

Grouper has nothing to do with var_vals, it's a ScheduleItem concern,
This enables Tensor.kernelize to just rewrite the Tensors graph instead of having to also return a var_vals dictionary.
The unbinding happens later when we actually want to run the ASTs.
eg BIND in Tensor -> DEFINE_VAR in ScheduleItem + mapping `{a:4}`.

unbind variables when creating ScheduleItems [pr]

---

tinygrad/runtime/ops_cpu.py

This section gets included in the finanl image, and we get a lot of garbage with DEBUG=7

clang should not emit the .comment section

---

examples/transformer.py

The y labels are expected to be of type int however the original supplied type is float. i have cast the original numpy arrays to int32 to fix the bug.
Steps to reproduce bug>
```python examples/transformer.py```

fixing bug in transformer training example

---

extra/onnx.py
extra/onnx_helpers.py
test/external/external_test_onnx_backend.py
test/external/external_test_onnx_ops.py

This reverts commit ac713e04db4e7989740674ab52e00dbc745793fe.
This broke model from `HuggingFaceTB/SmolLM-135M/onnx/model.onnx` from #9785
That model has symbolic dim for output but has a different value than the symbolic value specified at input. (result is validated to ORT to be correct however)
I think moving on we try to do little hand written validation. Just let the model run with flexibility.

Revert "ONNX add output shape validation (#9720)"

---

tinygrad/viz/index.html
tinygrad/viz/js/index.js

Rendering in DOM insertion order.
The labels would go below the edge paths once D3 re-rendered the edges: (eg, if you step forward, then walk back the rewrites)
Now it's always in a separate group above the edges:

ensure edge labels are always on top

---

test/external/process_replay/process_replay.py
test/test_schedule.py
tinygrad/engine/grouper.py
tinygrad/engine/schedule.py

It used to need a map from the tensor sink to the fixed up sched_sink with the extra edges for diamond assign.
It should instead be local to the Tensor UOp. ASSIGN(3) it always before ASSIGN(0), figuring out where to put the edge isn't local - we have to check the full graph - but expressing the edge is local to the ASSIGN UOp.

fix diamond assigns before mapping tensors to assigns

---

test/test_setitem.py
test/unit/test_disk_tensor.py

subtle bug in inplace setitem, `t[:3] *= 10` creates two ASSIGNs in the graph, when it's really one assign

setitem tests (some failing) from kernelize

---

test/test_schedule.py
tinygrad/engine/grouper.py
tinygrad/spec.py

Kernelize can be called multiple times on a Tensor. Once a Tensor maps to an ASSIGN(BUFFER, KERNEL), all its children will treat it as it was a normal BUFFER.
This requires allowing for KERNEL and ASSIGN (with the extra edges) in the tensor_uop_spec.
As these UOps directly flow from the grouper's `sched_sink`, the spec is shared.
The only difference is that `sched_sink` strictly, only allows for buffers, assigns and kernels. The Tensor graph can have a mix of kernels with other UOps within tensor_uop_spec.

Kernelize can be called multiple times on a Tensor

---

tinygrad/tensor.py

We don't need to apply the mask, it's a leftover from the previous implementation where the mask wasn't manually reduced.

rm mul from _masked_setitem

---

extra/export_model.py

Error if you tried to export using METAL before:
`AssertionError: only WEBGPU, CPU, CUDA, GPU, METAL are supported`
after:
`AssertionError: only WEBGPU, CPU, CUDA, GPU are supported`

fix assertion message for supported device in export_model

---

tinygrad/runtime/ops_cloud.py

The set name before starting part used to be required for #9935 when CLOUDDEV was a global variable, now just readability improvement

Less verbose cloud multiprocessing start

---

test/test_schedule.py
tinygrad/spec.py

Prereq for the gradient diff https://github.com/tinygrad/tinygrad/pull/9953
The Tensor UOp spec asserts views mid graph because we have not yet defined the gradient of a VIEW.
Since gradients do not flow through ASSIGNs, having a VIEW(ASSIGN) in the graph is fine, similar to a VIEW(BUFFER).

fix kernelize with VIEW children

---

examples/mlperf/model_train.py
extra/datasets/openimages.py

As pointed out in #9950, the estimated training time is incorrect. The core issue was that with `INITMLPERF=1`, both `steps_in_train_epoch` and `steps_in_val_epoch` are set to `BS` and `EVAL_BS`, respectively.
Since this is not representative of the actual dataset count, the estimations are going to be incorrect. This PR now looks through the actual number of images and uses that as the dataset count, regardless of the value of `INITMLPERF`.
Here's an actual run of the following command: 
```bash
INITMLPERF=1 BENCHMARK=10 MODEL=retinanet BASE_DIR=/raid/datasets/openimages/ BS=48 GPUS=6 python3 examples/mlperf/model_train.py
```
For comparison, here's the same run without `INITMLPERF`:
```bash
BENCHMARK=10 MODEL=retinanet BASE_DIR=/raid/datasets/openimages/ BS=48 GPUS=6 python3 …
```

RetinaNet time estimation fix

---

autogen_stubs.sh

Any operations on Steam Deck with `AMD=1` were giving the following error regarding NBIO 7.2.0 not being found, the fix is expands the RDNA2 fix (#9700) to handle Steam Deck as well.
```
['f644a68c-7d33-48df-8588-9652319edbef(WiFi (wlo1))', '6dcccf8a-84a7-4f7e-b897-9c21a77b4ef5(Ethernet (eno1))']})
Task exception was never retrieved
future: <Task finished name='Task-217' coro=<TinygradDynamicShardInferenceEngine.ensure_shard() done, defined at /nix/store/yqs9w5kkzd7rlj6a3agbgxc729s5d9qm-exo-0.0.16-intelarc/lib/python3.12/site-packages/exo/inference/tinygrad/inference.py:143> exception=ImportError('Failed
to load autogen module for NBIO 7.2.0')>
File "/nix/store/yqs9w5kkzd7rlj6a3agbgxc729s5d9qm-exo-0.0.16-intelarc/lib/python3.12/site-packages/exo/inference …
```

Fix NBIO 7.2.0 error on Steam Deck

---

test/test_schedule.py
tinygrad/gradient.py
tinygrad/spec.py

ASSIGNs are treated like DETACH in the graph, gradients do not flow through ASSIGN.
Currently the logic for picking if a Tensor uses replace or constructs ASSIGN(BUFFER, value) is in tensor.py. Any UOp children for an ASSIGN simply loads the BUFFER value, so it's behavior is similar to a BUFFER UOp.

fix kernelize usage with pm_gradient

---

examples/mlperf/model_train.py

eval 35 sec -> 20 sec. it was spending 13 seconds assembling output tensor on CPU backend. GPUS[0] seems to have enough memory, otherwise we can lower EVAL_BS

retinanet eval combine output on GPUS[0]

---

test/test_schedule.py
tinygrad/engine/schedule.py

It's looking closer to linearize.py. Eventually these can be shared. The toposort needs to look at the KERNEL ops instead of ASSIGN for multi output to toposort correctly.

refactor schedule linearize to defaultdict [pr]

---

test/test_schedule.py
tinygrad/engine/schedule.py

The linearizer used to put ASSIGN in the queue, this did not work with multi output because multiple ASSIGNs can share a KERNEL. 
`VIZ=1 python test/test_schedule.py TestSchedule.test_multioutput_ast`:

new schedule linearizer enqueues KERNEL UOps [pr]

---

examples/mlperf/model_train.py
examples/mlperf/training_submission_v5.0/tinycorp/benchmarks/retinanet/tinybox_green/dev_beam.sh
examples/mlperf/training_submission_v5.0/tinycorp/benchmarks/retinanet/tinybox_red/dev_beam.sh

it only controls logging, loading real data or not is solely controlled by RUNMLPERF

remove retinanet INITMLPERF from beam script

---

examples/mlperf/model_train.py

during setup only need to compile `_eval_step().numpy()`

retinanet only call postprocess_detections with RUNMLPERF

---

extra/torch_backend/backend.py
extra/torch_backend/test.py
test/test_tensor.py
tinygrad/tensor.py

- add randperm function in tensor.py
- create tests for randperm for pytorch backend and tinygrad frontend
@geohot  I read your general PR advice and thought about it for #9918 .
So, I made this PR only handle `randperm`, and will submit a separate PR for `torch.Generator` support in `torch_backend` after this PR is accepted.

Move randperm_generator off of cpu in torch_backend

---

tinygrad/runtime/ops_cloud.py

Refactor `/renderer` into a field of `/properties`. This is needed for most of my other cloud prs that add various fields to properties

Cloud properties

---

tinygrad/runtime/ops_cloud.py

(the first commit of this pr is #10021)
This is kind of a bug because currently with DEBUG>=1 it will say that
remote has device and then an array of renderer props instead of a real
device name which doesn't make sense:
```
127.0.0.1 - - [24/Apr/2025 16:50:44] "GET /properties HTTP/1.1" 200 -
remote has device ['tinygrad.renderer.cstyle', 'MetalRenderer', []]
opened device CLOUD from pid:20210
```
Now it will actually print the name of device behind cloud:
```
127.0.0.1 - - [24/Apr/2025 16:56:29] "GET /properties HTTP/1.1" 200 -
remote has device METAL
opened device CLOUD from pid:20315
```

Print real device behind cloud instead of an array of renderer properties

---

.github/workflows/test.yml

A lot more work is required to enable all of them and move into osxtests matrix, for now i created a separate runner for them (copied from WebGPU)
~~Will add test/test_graph.py to those tests in #9876~~
Hm, `@unittest.skipIf(CI and Device.DEFAULT=="METAL", "no ICB in CI, creation of graph fails")` on graph tests, looks like i'll have to use another device for cloud graph tests.

Add macos CLOUD tests 

---

.github/workflows/test.yml
test/test_linearizer.py

Set specific test for `AMD` padded `TC` to be expectedFailure to correctly track progress on the issue as that particular test is not broken due to a bug in the compiler, but instead due to an internal bug.
The bug related to the compiler can be suppressed by changing the compiler flag to `O1`. If we ran the fuzz test, we see that only fails when `N=17` (tinygrad issue). But if we ran with the flag set to `O3`, it fails on other cases two and it eventually hangs.
min repro for compiler bug: `DISABLE_COMPILER_CACHE=1 DEBUG=5 N=14 M=16 K=35 TC_OPT=2 HALF=1 python extra/gemm/simple_matmul.py` works with `O1` but fails with `O3`
this example also fails with `AMD_LLVM=1`
need to skip until #9606 is merged as right now `helper_tc_allclose` is not properly triggering padded tc and the test pass …

set `test_tensor_cores_padded_amd` to expectedFailure

---

tinygrad/runtime/support/compiler_amd.py

`DEBUG=7 MOCKGPU=1 AMD=1  PYTHONPATH=. python test/test_tiny.py TestTiny.test_plus` does not work on mac with error: `FileNotFoundError: [Errno 2] No such file or directory: '/opt/rocm/llvm/bin/llvm-objdump'`.
It shouldn't need rocm to run the disassembler on newer LLVM versions. I tested this on the red boxes and llvm@14 still requires the rocm path.

fix amdgpu_disassemble on mac [pr]

---

tinygrad/runtime/ops_nv.py

Kernels from the test has no input args, so init const_buffer0 size to 0.
closes #10051

nv: fix program init for no-args kernels

---

test/external/process_replay/process_replay.py
test/test_linearizer.py
test/unit/test_verify_ast.py
tinygrad/spec.py

This dedup already checks for sizes too, if you store a (3, 5) and a (4, 5) in the same kernel it is invalid.

don't sort dims in verify_sink_dims [pr]

---

test/unit/test_uop_symbolic.py
tinygrad/codegen/symbolic.py

with this, `bug_in_div_range` does not produce wrong answers without commenting out div_and_mod folding

don't simplify if div folding resulted in negative numerator

---

examples/webgpu/yolov8/compile.py
examples/webgpu/yolov8/index.html

640 is somehow slightly faster than 416 on my iPhone and similar on my computer
https://roryclear.github.io/yolo-webgpu/index_640.html
https://roryclear.github.io/yolo-webgpu/index.html

Change yolo webgpu res from 416x416 to 640x640

---

extra/remu/src/thread.rs
extra/remu/test/hwtest.py

[page 24](https://m7ymdt1k0usrgkaw.public.blob.vercel-storage.com/ref-jRgBvTGLG866V3AJ3U0BmVkIefoNuU.pdf#page=24) states that VALUs are "Not skipped if the instruction writes SGPRs/VCC". V_CMP ops do write to SGPR/EXEC or VCC, so remu didn't skip them regardless of the EXEC mask value.
Though when I tested against real hardware, V_CMP ops in VOP3 do not alter the exec mask on inactive threads.
This makes the [uninitialized VGPR usage](https://discord.com/channels/1068976834382925865/1134866270320328824/1366049909773701150) issue irrelevant, because the output of the comparison does not impact EXEC.

remu: only write v_cmp result if exec is set

---

tinygrad/runtime/graph/cpu.py

Makes #10014 more robust.
While working on LLVM graph (#10029) I found two tests (one was test_jit_multiple_random_regen in test_jit.py) where LLVM did not inlined functions with just linkage modifier (most likely because of the size).
I think there is a good chance that this can happen with clang backend too so it's better to force function inlining.

Make sure clang always inline batched functions

---

extra/torch_backend/test.py
test/test_arange.py
test/unit/test_uop_symbolic.py
tinygrad/codegen/devectorizer.py
tinygrad/codegen/symbolic.py

`(UPat.var("x", dtypes.sints) // UPat.var("y"), lambda x,y: div_and_mod_folding(x,y,Ops.IDIV)),` is causing issues
If you uncomment it, `DEBUG=4 python3 test/test_arange.py TestArange.test_complexity_w_unroll2` will get the wrong answer.

don't modify the ranges on reduce rewrite

---

examples/llama.py

The "Make sure buffers are GCed on CPU and with VIZ, with good tests" bounty should actually fix the root cause of this. Viewing the VIZ for model forward is still useful for kernelize and FUSE_ARANGE development.

hack for VIZ=1 with examples/llama

---

extra/models/llama.py

Reverts tinygrad/tinygrad#10104, it's different for multi and caused BEAM to hang

Revert "remove TransformerBlock contiguous in llama"

---

test/test_ops.py
tinygrad/runtime/ops_python.py

CAST only needs truncate and does not require dtype fmt. added bfloat16 tests can run locally

split CAST and BITCAST in PYTHON [pr]

---

tinygrad/runtime/ops_amd.py

this allows to move AM into sleep mode in case of some device failures (like pf).

amd: finalize device in case of failures

---

test/test_linearizer.py

test was failing locally on tiny green

fix `test_tensor_cores_codegen` for `PTX` renderer

---

tinygrad/runtime/support/am/amdev.py

do not rely on callers, this field should be aligned

am: do not expect aligned size in valloc

---

extra/remu/src/rdna3.rs
extra/remu/src/thread.rs

Fixes _RuntimeError: remu does not support the new instruction introduced in this kernel_ for https://github.com/tinygrad/tinygrad/pull/9771
Walkthrough docs are pending
Whenever you have time, feedback is much appreciated @Qazalin

add support for `ds_load_u8` in remu

---

tinygrad/runtime/support/amd.py

do not see linux's `pci_scan_bridge_extend` does anything special. it never resets bus (my controllers work without reset). spec also requires to write buses as dword.

usbgpu: tiny changes in setup pci bars to match spec

---

.github/workflows/test.yml
test/test_graph.py
test/test_jit.py
test/test_multitensor.py
tinygrad/runtime/ops_metal.py

GitHub CI macOS runners use paravirtualized metal which is broken with graph (some comments say that ICB in particular is broken but in my testing it was fine sometimes, but other times hitting an assert inside metal's code related to resouces, so not sure).
> Assertion failed: (resource != nil), function -[IOGPUMetalResource initWithResource:], file IOGPUMetalResource.m, line 458.
This can be reproduced locally with any virtualization software (like utm) that can create macOS VMs with apple's own virtualization framework.

Less messy broken graph on paravirtualized metal workaround

---

test/test_schedule.py
tinygrad/engine/grouper.py

In the master version of grouper.py https://github.com/tinygrad/tinygrad/pull/10186/commits/f05a508fd8a9ef7c5b4ada2737a36d75e6fdc45e, `VIZ=1 python test/test_schedule.py TestUOpBecome.test_reorder_expand_alt` creates two kernels.
It is not worth it to push the EXPAND after a UnaryOp if it costs an extra memory roundtrip. This is why generating quantized ONNX in #9682 required DONT_REALIZE_EXPAND =1.
Now just `DEBUG=2 QUANT=1 python3 examples/test_onnx_imagenet.py https://github.com/xamcat/mobcat-samples/raw/refs/heads/master/onnx_runtime/InferencingSample/InferencingSample/mobilenetv2-7.onnx` is enough to create the faster schedule.

only reorder expand if it can fuse with input

---

tinygrad/viz/serve.py

Now it shows AST and opts if codegen fails:
Because VIZ does not re-linearize kernels, viewing traceback details requires manually looking at logs. Adding more error details can be a future improvement to VIZ.

better error message for linearizer failures in viz [pr]

---

test/unit/test_uop_symbolic.py
tinygrad/codegen/symbolic.py

#10178 fails on process replay I think because there is a 'fake' variable with vmin==vmax=1 which happens to only get folded if its in an alu with a const. 
Just seeing what happens

Fold constant variable

---

test/test_subbuffer.py
tinygrad/ops.py

Currently it's only used in test_subbuffer. Once we add subbuffers for CONTIGUOUS and BITCAST in grouper, this needs to check a device attribute (without opening devices), it shouldn't be duplicated between ops and runtime.

remove view_supported_devices, check allocator instead [pr]

---

test/test_schedule.py
tinygrad/engine/grouper.py

Kernelize in master goes through:
1. merge_views+fuse: Reorder views and finalize the shape of UOps
2. group_realizes: Put UOps that will go to memory to a dict
3. create_kernels+append_to_kernels: Based on the realizes dict, create the kernel graph
4. fixup assign dependancies
5. create_asts: Create the local graph per kernel.
This diff is toward merging step 2 and first half of step 3. Then step 5 and second half of 3 can merge:
1. Same merge_views+fuse
2. insert_kernels: Insert KERNEL UOps immediately after ops that should realize
3. finalize_kernels: Either fuse KERNEL sources or load from global memory.
4. fixup ASSIGN edges

split kernel graph into insert and finalize stages [pr]

---

test/test_schedule.py
tinygrad/engine/grouper.py

Reverts tinygrad/tinygrad#10222
SDXL benchmark failed in master with "RecursionError: maximum recursion depth exceeded in comparison" http://github.com/tinygrad/tinygrad/actions/runs/14918155343/job/41908224946#step:9:3013.
We lack proper tests for this codepath in normal CI. Will add tests and redo this diff.

Revert "split kernel graph into insert and finalize stages [pr]"

---

extra/torch_backend/backend.py
extra/torch_backend/test.py

- Updated `aten.uniform_` and `aten.normal_` to include dtype parameter in backend.py
- Added unit tests for uniform and normal tensor generation with specific dtypes in test.py

Enhance tensor random functions with dtype support

---

test/unit/test_uop_symbolic.py
tinygrad/codegen/symbolic.py

This used to work but 
```
if (x.vmin < 0 or rem.vmin < 0)
```
disabled it.
If we include the const factor in the gcd then we can still remove it since trunc div == floor div  if the numerator is a multiple of the divisor

take gcd out of trunc div

---

tinygrad/viz/js/index.js

The spacing inside of the VIZ=1 nodes seem to be a few pixels too much on the top and left side. I changed x to 0 and set the first line's dy to 12, and the rest to 14. The change is especially noticeable in the SINK node shown below, it looks centered now.
Before:
After:

even spacing in viz nodes

---

extra/remu/src/thread.rs
extra/remu/test/hwtest.py

Used in https://github.com/tinygrad/tinygrad/pull/10246

add v_fmac_f16 vop3 instruction to remu

---

tinygrad/renderer/llvmir.py

FP16 matmul TFLOPS on 7900xtx (tiny13)
|matrix    |AMD|AMD_LLVM|
|----------|---|-------|
|8192x8192 |56|71|
|6144x6144 |81|81|

AMD LLVM speed: add nsw flag

---

tinygrad/runtime/graph/remote.py
tinygrad/runtime/ops_remote.py

This is a prereq refactor for cloud multi which will make it possible to use multiple devices from cloud host instead of just one.
I will do that via changing a session to be a `tuple[token, dev_idx]`
Previously the session was in cookies, this is a problem because a single http request can contain many RemoteRequests with potentially different devices.
The alternatives are either:
\- sending commands for different devices in separate http requests (slow)
\- only adding an idx in RemoteRequest in basically the same way i added session here, keeping session a cookie and concat in server. This is how i've done it previously and it looks just strictly worse than having it all be in the same place.

Move session to RemoteRequest

---

extra/onnx.py
test/external/external_test_onnx_backend.py
test/external/external_test_onnx_ops.py

split from #9609 
- added missing test to cover Squeeze op when axes is None
- resolved PRelu to match ORT
- added test coverage for tests in `test/external/external_test_onnx_ops.py` where both we and ORT fails at but we match ORT behavior

ONNX add tests against ORT

---

.github/workflows/test.yml
test/helpers.py
tinygrad/runtime/ops_remote.py

Not strictly required for anything but soon there will be like 4 new properties and having it be a huge json just seems like a bad taste.
It also seems right to not have a separate endpoint for this, just `GetProperties` request that returns a repr of this similar to how requests are sent in `BatchRequest`.
This will also make a switch to anything other than http much simpler if it will be required for any reason, like just a tcp stream of `BatchRequest`s

Remote properties is a dataclass

---

test/external/external_test_speed_llama.py
test/helpers.py
tinygrad/device.py
tinygrad/runtime/ops_cuda.py
tinygrad/runtime/ops_dsp.py
tinygrad/runtime/ops_gpu.py
tinygrad/runtime/ops_hip.py
tinygrad/runtime/ops_metal.py
tinygrad/runtime/ops_npy.py
tinygrad/runtime/ops_null.py
tinygrad/runtime/ops_python.py
tinygrad/runtime/ops_remote.py
tinygrad/runtime/ops_webgpu.py
tinygrad/runtime/support/hcq.py

(this is a prereq refactor for #10285)
At least `BufferXfer.copy` accesses it assuming it's always present, currently most devices just add this property on their own repeating the same code over and over again.
This is also a bit footguny, see `RemoteAllocator` that named this property `device` instead of `dev`, i could obviously just change that in one place but doing it globally seems like a better solution (and it reduces code duplication too).
`MallocAllocator` is a bit special, but passing `None` works just fine.

Make `dev` a property of `Allocator`

---

test/external/process_replay/process_replay.py

To correctly replicate scheduling we also need to start the UNIQUE counter at number of total "known" buffers in that capture.
Process replay in scheduling asserted with "Cycle detected in graph" because it did not account for known ASSIGN targets in the schedule graph. If the BUFFER counter counts up to n (from a 0 base), and there is also an ASSIGN to BUFFER n captured, the replayed graph can have a cycle.
If we base the counter at max(N) of the local UNIQUEs, all new buffers enumerate correctly independent of which process replay threads get to replay first.
One other way to solve this is to rebase all BUFFER numbers to 0 before scheduling.

enable process replay assert for schedule [pr]

---

test/test_multitensor.py
tinygrad/engine/multi.py
tinygrad/ops.py

@chenyuxyz is there a problem with doing it like this? Instead of using real, I just copy that piece to all devices, and change the shard axis to None. Hoping the optimizer can fix it later, but even if it can't it should be pretty rare?
This is a prereq for O(1) multi, or I need to find a different way to handle in that PR.

multi: instead of real, just copy

---

tinygrad/runtime/graph/remote.py
tinygrad/runtime/ops_remote.py

```
3 1183.79 ms run,   26.31 ms python,   0.47 ms fetch data, 1157.01 ms AMD * 6,  0.69 loss, 0.000175 LR, 134.22 GB used,  92125.82 GFLOPS
4 1179.94 ms run,   23.27 ms python,   0.44 ms fetch data, 1156.23 ms AMD * 6,  0.69 loss, 0.000175 LR, 134.22 GB used,  92426.82 GFLOPS
5 1181.35 ms run,   23.33 ms python,   0.46 ms fetch data, 1157.56 ms AMD * 6,  0.69 loss, 0.000175 LR, 134.22 GB used,  92316.49 GFLOPS
6 1176.95 ms run,   23.15 ms python,   0.45 ms fetch data, 1153.34 ms AMD * 6,  0.69 loss, 0.000175 LR, 134.22 GB used,  92661.54 GFLOPS
```
```
3 1180.47 ms run,    5.21 ms python,   0.33 ms fetch data, 1174.92 ms REMOTE * 6,  0.69 loss, 0.000175 LR, 137.38 GB used,  92385.46 GFLOPS
4 1191.75 ms run,    8.59 ms python,   0.54 ms fetch data, 1182.62 ms REMOTE * 6,  0.69 loss, …
```

Remote multi (graph)

---

test/test_dtype_alu.py

when testing alu for bfloat16, it should cast inputs to bfloat16 first, otherwise numpy has both errors from input and errors from alu which is more inaccurate

test_dtype_alu should cast bf16 input

---

test/test_schedule.py
tinygrad/engine/grouper.py

This was the root cause of `FUSE_ARANGE=1 python test/test_ops.py TestOps.test_avg_pool2d_ceil_mode` failing in master. Push pad before recip results in a division by zero in codegen:

grouper: check for unsafe PAD in FUSE

---

tinygrad/engine/grouper.py

New FUSE_ARANGE does not fuse E_ kernels with arange if there is an expand. This is because rangeless arange folding doesn't work in a lot of cases and ends up generating large for loops in the kernel.
Confirmed with `VIZ=1 GPU=1 FUSE_ARANGE=1 PYTHONPATH=. GPUS=1 BERT_SIZE="tiny" DEFAULT_FLOAT=HALF BENCHMARK=5 MODEL="bert" python examples/mlperf/model_train.py` arange and rand stay split:

remove FUSE_ARANGE_UINT [pr]

---

extra/remu/src/thread.rs
extra/remu/test/hwtest.py

Used by https://github.com/tinygrad/tinygrad/pull/10327.

add s_abs_i32 instruction to remu

---

extra/remu/src/thread.rs

both instructions are required by `test_mid_dim_multireduce`

add `ds_load_b96` and `ds_store_b96` instructions to remu

---

.github/workflows/benchmark.yml

example of benchmark job [silently failing](https://github.com/tinygrad/tinygrad/actions/runs/14975260718/job/42065838943#step:18:13)
same benchmark job after this change [failing](https://github.com/tinygrad/tinygrad/actions/runs/14975260718/job/42065838943#step:18:13)
exit codes and error action preference [(reference)](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference)

set fail-fast behavior

---

test/test_multitensor.py

@nimlgen `AMD=1 MOCKGPU=1 PYTHONPATH="." python3 test/test_multitensor.py TestMultiTensor.test_multitensor_jit_input` doesn't work on mac (works on real device)
```
light@blak:~/tinygrad$ AMD=1 MOCKGPU=1 PYTHONPATH="." python3 test/test_multitensor.py TestMultiTensor.test_multitensor_jit_input
F
======================================================================
FAIL: test_multitensor_jit_input (__main__.TestMultiTensor.test_multitensor_jit_input)
----------------------------------------------------------------------
File "/Users/light/tinygrad/test/test_multitensor.py", line 218, in test_multitensor_jit_input
out = f(tt)
^^^^^
File "/Users/light/tinygrad/tinygrad/engine/jit.py", line 328, in __call__
ret = self.captured(input_buffers, var_vals) …
```

add test_multitensor_jit_input [pr]

---

tinygrad/device.py

If multiple devices are requested with env args, the behavior undefined,  and it will select the first device in the iterator. Specifying multiple devices is almost certainly unintentional,  and should not be allowed. This PR prevents confusing bugs where the wrong device is used due to environment variables hanging around or hidden somewhere in the imports.

Prevent undefined device selection with env args

---

extra/torch_backend/backend.py
extra/torch_backend/test.py

- Implemented a new function `equal` in the torch backend to compare two tensors for equality.
- Added unit tests for the `equal` function to verify its correctness with different tensor inputs.

Add equal function impl and corresponding test

---

tinygrad/runtime/ops_remote.py

sometimes a minute is not enough, 5 minutes should be but if it isn't for some huge workload it can be overridden

Remote higher timeout and overridable via `REMOTE_TIMEOUT`

---

docs/index.md

- update the docs to use `sparse_categorical_crossentropy`
- `python3 -m ruff check docs/index.md` *(fails due to treating Markdown as Python)*
- `pre-commit run --files docs/index.md` *(fails: pre-commit not installed and network blocked)*
- `python3 -m pytest -k '' test/test_tiny.py` *(fails: pytest not installed)*

Fix crossentropy link

---

test/unit/test_helpers.py
tinygrad/helpers.py

- fix getbits mask calculation without altering formatting
- move getbits unit tests into existing test_helpers suite
- `ruff check tinygrad/helpers.py test/unit/test_helpers.py`
- `PYTHONPATH=. python3 test/unit/test_helpers.py -v` *(fails: `ModuleNotFoundError: No module named 'numpy'`)*

Tests for getbits

---

tinygrad/runtime/graph/remote.py
tinygrad/runtime/ops_remote.py

Similar to how it's done with `UOp.unique_num`, looks a bit nicer

Use `itertools.count` instead of manual increment in remote

---

test/external/process_replay/process_replay.py

Exit is a much cleaner experience when running locally. Stacktrace isn't useful when we're printing the diff:
Compare
It'll still raise Exception for generic errors.

don't raise Exception in process replay [pr]

---

tinygrad/viz/serve.py

`VIZ=1 python3 -m pytest ./test/test_multitensor.py`
```
rewrote 2737 graphs and matched 315223 times, saved to /var/folders/vw/qw2gc7rs53jdykwhx85mcxf00000gn/T/rewrites.pkl.qazal
*** viz is starting
preparing profile: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9172/9172 [00:00<00:00, 1154957.76it/s]
*** started viz on http://127.0.0.1:8000
*** ready in 2433.36ms
```
master:
```
rewrote 2737 graphs and matched 315460 times, saved to /var/folders/vw/qw2gc7rs53jdykwhx85mcxf00000gn/T/rewrites.pkl.qazal
*** viz is starting
preparing profile: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ …
```

faster viz to_program [pr]

---

test/test_multitensor.py
test/test_subbuffer.py

This should fix remote cpu tests flakiness (segfaults were in `test_data_parallel_resnet_train_step` which is skipped on cpu but wasn't skipped on remote cpu)

Use REAL_DEV for test skips

---

test/external/external_model_benchmark.py

precision issue with different onnxruntime version

skip commavq in external_model_benchmark

---

tinygrad/runtime/ops_cuda.py
tinygrad/runtime/support/compiler_cuda.py

unify CUDA/NV/PTX disassemble pipeline
before, it was quite a mess how it worked; the `disassemble` function from `CUDACompiler` was not working for itself as `nvdisam` expects a `cubin` lib, but the `compile` outputs `ptx`. That `disassemble` function did work for `NVCompiler` that inherited it as the compile function from it does generate `cubin` lib.
`CUDA=1 PTX=0` and `CUDA=1 PTX=1` were disassembled by `cuda_disassemble` helper fun that introduced a step using ptxas for ptx into sass compilation.
Added disassemble to NVPTX that before was a noop.
Removed extra disassembling happening in `cuda_ops` as it was already triggered with `DEBUG >= 7` in realize.
https://github.com/tinygrad/tinygrad/blob/475a7583b38458e5addf74e15026f0888c1feaf9/tinygrad/engine/realize.py#L45
Now disassemble …

refactor `CUDA`, `NV` & `PTX` disassemble [pr]

---

test/test_mnist_dataset.py
tinygrad/engine/grouper.py

This was broken by #9845 the kernelize PR. It passes before that

its copying the dataset every time

---

test/test_schedule.py
tinygrad/engine/grouper.py

This changed to k.src https://github.com/tinygrad/tinygrad/pull/10494/files, ASSIGN/MSELECT do not define a Buffer directly, it should only be for BUFFER UOps.

proper error for device mismatch

---

tinygrad/viz/js/index.js

setting innerHTML doesn't escape `<` characters correctly:
setting innerText renders correctly as plain text

fix display of kernel args in viz [pr]

---

test/test_symbolic_ops.py
tinygrad/engine/grouper.py
tinygrad/uop/spec.py

COPY with a VIEW source should either make the VIEW contiguous or move the base and apply VIEW on the other device.
This is similar to how MSELECT(VIEW) will look like after https://github.com/tinygrad/tinygrad/pull/10496.
Also removed arg from the implementation. It is useless after MSELECT and clone fixes.

readable COPY(VIEW) reordering [pr]

---

test/test_linearizer.py
test/test_schedule.py
test/test_uops.py
tinygrad/engine/grouper.py

resolves #1461, there should be a way to get this value per backend without opening devices. 
Fixes running driver monitoring on METAL=1
```
PYTHONPATH="." METAL=1 IMAGE=0 NOLOCALS=0 python3 examples/openpilot/compile3.py https://github.com/commaai/openpilot/raw/v0.9.7/selfdrive/modeld/models/dmonitoring_model.onnx
```
and issues with backward pass in examples/minrf.py.
Python time:
```
~/code/tinygrad (32_buffer) > SCHEDULE_ONLY=1 PYTHONPATH=. python ./test/external/external_benchmark_schedule.py
***** model tensor in     23.16 ms
***** model schedule in   87.94 ms
all 111.15 ms
~/code/tinygrad (master) > SCHEDULE_ONLY=1 PYTHONPATH=. python ./test/external/external_benchmark_schedule.py
***** model tensor in     23.12 ms
***** model schedule in   81.22 ms
all 104.37 ms
```

do not create kernels with more inputs than the backend allows

---

tinygrad/engine/grouper.py

There should be a test for process replay in CI. Currently it's [silent](https://github.com/tinygrad/tinygrad/actions/runs/15280331322/job/42977465432#step:7:61) without `[pr]` -

fixup grouper process replay [pr]

---

test/helpers.py
tinygrad/codegen/kernel.py
tinygrad/codegen/lowerer.py
tinygrad/engine/grouper.py
tinygrad/uop/ops.py

This makes UOp.valid construction simpler in core tinygrad. It needed a graph_rewrite in the `ast_const` test helper to merge the views for manually constructed test ASTs.
Proper tinygrad merges all the views before putting the AST in a ScheduleItem.

UOp.valid and const_like work with just shapes [pr]

---

test/test_linearizer_dumb.py
test/test_linearizer_failures.py
test/test_linearizer_overflows.py
test/test_search.py

The IGNORE_OOB=0 check only works if the DEFINE_GLOBAL has a size.
TestTimeLinearizer.test_kernel_count can use kernelize, don't need to hardcode an AST for contiguous const.

fixup hardcoded asts ptr dtype and constants [pr]

---

test/external/process_replay/local.sh
test/external/process_replay/process_replay.py
test/external/process_replay/reset.py
tinygrad/codegen/kernel.py
tinygrad/engine/grouper.py
tinygrad/helpers.py
tinygrad/uop/ops.py

Process replay capturing shouldn't exist in the main loop of the process. It lives on the VIZ capturing decorator now.
The behavior and functionality for users stays exactly as it was before. It's just less lines and factored out.
Turns out if we capture linearize instead of to_program, it reveals test cases where the a Kernel is not reproducible from only its AST, opts and applied_opts. For example, test_float4_expanded calls`.upcast()`, changing self.upcasted, instead of appending an OptOp to applied_opts.

merge process replay and viz captures [pr]

---

test/external/process_replay/process_replay.py

Some PRs like #10609 change total number of scheduled kernels, it's useful to know by how many:
Things that just change structure of ASTs will look the same:

add kernel count to grouper process replay differ [pr]

---

.github/workflows/test.yml
setup.py
test/web/test_viz.js
tinygrad/viz/serve.py

Follow-up for the broken VIZ behavior #10624 fixed. Using Puppeteer to run an end-to-end test is more robust than a simple curl to prevent future regression.
Thanks to the work on webgpu there's already infrastructure in CI to write this test.
Running `node ./test/web/test_viz.js` locally will use the default tinygrad repo. The test in CI runs it in a virtual env.

viz browser tests

---

test/test_schedule.py

The linearizer seems to be fine without the CAST.
The real avg_pool2d kernel does not lower properly:
without CAST, this loop structure is fine, suggests there's a missing or_casted in the linearizer matchers?

linearizer failure from FUSE_ARANGE default diff

---

test/test_schedule.py
tinygrad/engine/grouper.py

The FUSE_ARANGE default diff revealed this bug, but it's a generic issue when pushing a reshape/permute before REDUCE_AXIS.
For example, in `python test/test_schedule.py TestSchedule.test_arange_sum`, we change the output dimensions from (6,1) to (3,2)
To fuse this reduce while keeping the output shape the same, the swizzler needs to change the reduce source's shape:
<br />
This gets at the heart of the swizzler, thought about this in porting DSP stuff to master too, when do we push MovementOps before ReduceOps and when do we decide to push it after?
Pushing it before will change the structure of ReduceOp ([10638](https://github.com/tinygrad/tinygrad/pull/10638)), pushing it after will change how it's stored in memory.
Currently we only change the reduceop if it's a non-contiguous / …

push permutes through fused reduces

---

docs/env_vars.md

- remove `METAL_XCODE` from env vars table
- `ruff check docs/env_vars.md` *(fails: SyntaxError in docs)*

Remove unused env var doc

---

.github/workflows/mlperf.yml

not to interfere with regular cache which is used by benchmark

mlperf ci uses its own cache

---

tinygrad/codegen/linearize.py

so block_reorder tests won't fail with flag set to 0

move BLOCK_REORDER to caller [pr]

---

test/test_symbolic_ops.py

- **feat: failing test for symbolic expand after pad**
- **feat: mark test as failing**

failing test for symbolic expand after pad

---

test/test_linearizer_failures.py

somehow only failed for AM and NV
`RuntimeError: UOp verification failed at 4 on Ops.LOAD dtypes.half 2 [<Ops.DEFINE_GLOBAL: 24>, <Ops.VIEW: 23>] None`

linearizer failure from wino fuse arange cifar

---

docs/ramp.py

This fixes the following error: 
```
ImportError: cannot import name 'UOp' from 'tinygrad.uop' (/tinygrad/tinygrad/uop/__init__.py). Did you mean: 'uop'?
```
in `ramp.py`.

ramp.py: correct UOp and Ops import path from tinygrad.uop to tinygrad.uop.ops

---

test/test_ops.py

testing negative parts double the effectiveness. keep the relu between two convs and the tests that explicitly test relu
also relax tol for large input convs as needed

remove .relu() call in several conv tests in test_ops

---

test/unit/test_uop_symbolic.py
tinygrad/uop/spec.py
tinygrad/uop/symbolic.py

relevant for keccak. Reduces scheduling time a bit (2900ms -> 2200ms on my machine).
example:
```python
from tinygrad import Tensor, dtypes
a = Tensor([ 1, 2 ], dtype=dtypes.int)
b = Tensor([ 1337 ], dtype=dtypes.int).pad((0, 1))
(a ^ b).realize()
```
before:
```c
void E_2(int* restrict data0, int* restrict data1, int* restrict data2) {
int val0 = *(data1+0);
int val1 = *(data2+0);
int val2 = *(data1+1);
*(data0+0) = (val0^val1);
*(data0+1) = (val2^0);
}
```
after:
```c
void E_2(int* restrict data0, int* restrict data1, int* restrict data2) {
int val0 = *(data1+0);
int val1 = *(data2+0);
int val2 = *(data1+1);
*(data0+1) = val2;
*(data0+0) = (val0^val1);
}
```

xor self folding

---

test/unit/test_uop_symbolic.py
tinygrad/uop/symbolic.py

For cdiv you can take out the sign for both the numerator and divisor but for cmod only the numerator

Remove incorrect rule for `x%-d -> (x%d)*-1`

---

test/unit/test_tqdm.py

I’m working on issue #7889.  I’ve verified locally that all unit tests pass under `TYPED=1`. Since these changes touch multiple files, I’m splitting them into several pull requests.
In `test_tqdm`, `typeguard` currently raises an error because `tinytqdm` requires the `rate` parameter to be an integer. To fix this, I replaced the float literal `1e9` with the integer expression `10**9`.

Change rate to int in test_tqdm

---

tinygrad/helpers.py
tinygrad/runtime/ops_metal.py

I’m working on issue #7889 and need to ensure the unit tests run with TYPED=1. To simplify the review process, I’m splitting the necessary changes into several PRs. See also #10848, #10859, #10864, #10866 and #10876.
Right now, `init_c_struct_t` gets called eight times, and we always pass it a type, never an instance. To stop Typeguard from throwing errors at runtime, I updated its type hint. I've modified the type hint in `to_struct` accordingly.

Change type hint for init_c_struct_t and to_struct [pr]

---

tinygrad/uop/ops.py

During shutdown, globals in the ops module cleanup before UOp `__del__` is called:
```
TRACK_MATCH_STATS=2 PRINT_MATCH_STATS=0 python test/test_tiny.py TestTiny.test_plus
```
in master prints a lot of spam:
```
Exception ignored in: <function UOp.__del__ at 0x10482d6c0>
File "/Users/qazal/code/tinygrad/tinygrad/uop/ops.py", line 77, in __del__
AttributeError: 'NoneType' object has no attribute 'BUFFER'
```

skip UOp del when python is shutting down [pr]

---

test/unit/test_helpers.py
tinygrad/helpers.py

I’m working on issue #7889 and need to ensure the unit tests run with TYPED=1. To simplify the review process, I’m splitting the necessary changes into several PRs. See also #10848, #10859, #10864 and #10866.
`to_mv` expects `ct` to be of type `int`. If you don’t cast it, `ct` is a `ctypes.Array` and causes a Typeguard error.

Cast ptr to int in test_from_mv_to_mv

---

test/test_ops.py
tinygrad/tensor.py

my attempt to fix the broken devectorize=0 which failed because of nan values. I propose a fix by applying the mask before the exponential rather than after, with mask value 1e4.

fix test logcumsumexp broken devectorize=0

---

tinygrad/viz/js/index.js

I think this makes the UI more consistent:
Same kernels on different GPUs have the same tint, but emphasis is on shape colors.

viz: color by kernel names in profiler

---

tinygrad/helpers.py
tinygrad/opt/heuristic.py

OptOps shouldn't rely on os.environ.

fix: getenv("NOLOCALS")/NOLOCALS context var

---

test/test_multitensor.py
test/test_schedule.py
test/unit/test_viz.py
tinygrad/uop/ops.py
tinygrad/viz/serve.py

The core idea is to track UOp fields, and lazily reconstruct UOp instances when the user opens a graph.
Benchmarks:
`VIZ=1 PYTHONPATH=. python3 examples/llama3.py --shard 4 --benchmark`
Master:  2.3 tok/s
Branch: 63.20 tok/s
VIZ = 0: 87.94 tok/s
This also naturally improves VIZ startup time, because it doesn't have UOp unpickling overhead on startup:
llama: 5800 ms → 3150 ms
beautiful_mnist: 440 ms → 215 ms
The fix for KERNEL UOp should be made generic, currently some UOps can have other UOps in the arg.

viz: non blocking UOp tracing

---

test/test_linearizer.py

Tests now notify when skipped
Before, they silently skipped if backend didn't had half precision and accumulation
Also cleaned up atol and rtol setup

minor cleanup on test_tensor_core_opts tests

---

.github/workflows/benchmark_search.yml
examples/hlb_cifar10.py

A deep dive: https://xl0.github.io/tinygrad-notes/bounty1.html
So the main issue here was the fact that `Tensor.masked_select()` is so slow that it's unusable. It's a natural choice for implementing `random_crop`, but not the only option.
Since `random_crop` picks a 32x32 rectangle from a 36x36 source image, there are only 16 possible crops. So I shuffle the dataset, split it 16-way, apply all possible crops using `.pad()` with negative padding, put it togeher and shuffle it again.
The result is not as straight-forward as `X.masked_select(mask)`, but it is actually fast - faster than the numpy implementation at least. Maybe we can use `.masked_select()` once it get good.
Another issue - indexing the dataset with a large 1-dim tensor to shuffle it is super slow, unless done with …

[bounty] Don't use numpy inside hlb_cifar10 training loop

---

tinygrad/viz/js/index.js
tinygrad/viz/js/worker.js
tinygrad/viz/serve.py

Caught this in llama kv cache assignment time VIZ. We don't put `(`s in the rendered code. The correct key is the function_name: `r_32_28start_pos2B129n1`

viz: convert to function_name in server [pr]

---

test/unit/test_uop_symbolic.py
tinygrad/uop/ops.py

The min/max of mod was not calculated correctly when the divisor is a negative variable. When it is negative vmin has the largest absolute value.
`Variable("x", 0, 10)%Variable("y", -10, -1)` was giving _min_max of `(0,0)`

fix mod `_min_max` with negative variable divisor

---

test/external/process_replay/process_replay.py
test/unit/test_linearizer_rewrite.py
tinygrad/engine/realize.py
tinygrad/opt/__init__.py
tinygrad/opt/kernel.py
tinygrad/uop/ops.py

Process replay and some other tests override OptOps with a custom sequence.
Currently, this is done through interfacing with the Kernel class. This diff moves this to the SINK UOp's argument.
Updating some of the tests to demonstrate use-case, I think this change enables removing kernel.py from the rest of the tests as well.
The get_optimized_ast stage moves opts_to_apply to applied_opts.
opts_to_apply=None. No optimizations specified by the sink. Use the default path (BEAM, NOOPT, heuristic.py)
opts_to_apply=() -> Equivalent to NOOPT=1.

add opts_to_apply option to AST KernelInfo

---

tinygrad/runtime/ops_remote.py

```
training bert
training on ['REMOTE:0', 'REMOTE:1', 'REMOTE:2', 'REMOTE:3', 'REMOTE:4', 'REMOTE:5']
File "/home/uuuvn/src/tinygrad/examples/mlperf/model_train.py", line 1300, in <module>
with Profiling(enabled=getenv("PYPROFILE")): globals()[nm]()
^^^^^^^^^^^^^^^
File "/home/uuuvn/src/tinygrad/examples/mlperf/model_train.py", line 975, in train_bert
for x in GPUS: Device[x]
~~~~~~^^^
File "/home/uuuvn/src/tinygrad/tinygrad/device.py", line 22, in __getitem__
def __getitem__(self, ix:str) -> Compiled: return self.__get_canonicalized_item(self.canonicalize(ix))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/uuuvn/src/tinygrad/tinygrad/device.py", line 28, in __get_canonicalized_item
ret = [cls for cname, cls in …
```

Weaker renderer validation in remote

---

test/external/speed_compare_cuda_ptx.py
test/test_linearizer.py
test/test_uops.py
test/test_winograd.py
test/unit/test_uop_spec.py

speed_compare_cuda_ptx
test_uop_spec
test_linearizer (some tests still call linearize here)
test_uops
test_winograd
I'll keep the pr's small

remove some linearize calls from tests [pr]

---

tinygrad/viz/js/index.js

The memory graph ends up taking [~10 lines of javascript](https://github.com/tinygrad/tinygrad/pull/10960/files#diff-9a76eaa27e7ac2e684e37ae3d8af0e64e34926b7945a5749f1a2d68d0d6d9a12R220-R236) to draw polygons instead of rectangles, everything is shared with the existing canvas.

viz: generic shape tooltip/click handlers + renames

---

tinygrad/viz/js/index.js
tinygrad/viz/js/worker.js

This diff fixes the rendering of KernelInfo in viz nodes:
Branch:
Master:
per the JSON spec: http://datatracker.ietf.org/doc/html/rfc8259#section-8 escape codes become string literals, so this needed an extra fixup to work properly.

viz: support axis colors in UOp nodes

---

tinygrad/viz/index.html
tinygrad/viz/js/index.js

- innerText to respect \n
- do not add id to divs, we don't need it and some DISK device names aren't valid DOM node ids
- tooltip always on top

viz: small fixups from memory graph

---

tinygrad/opt/kernel.py

For now, kernelinfo is kept as a property of kernel. This was done this way on order to keep the pr scoped. Using the kernelinfo directly from the ast breaks the copy semantics of kernel, as the state of the ast will change over time (search, heuristics, tests...).
In the future, kernelinfo could independently be refactored to dynamically get and update the one form from sink without needing to change again the api, (`kernel.info` will point towards the one in the ast, instead of being itself a property of kernel). This hasn't been done in this pr due to the reason stated above.

use kernel info

---

tinygrad/kernelize/kernelize.py

don't see why const 0 needs to be special and no test failure nor kernel diff

remove const 0 clause in "UOp with size 0 is zero" [pr]

---

test/test_profiler.py
tinygrad/device.py

This diff adds support for tracing cpu_profile events up to the point of error.
Currently in master if a function errors, we do not record any traces.
I think it'll be particularly useful for tracing graph_rewrite errors on the TINY device.

support capturing cpu_profile on error

---

tinygrad/viz/js/index.js
tinygrad/viz/js/worker.js
tinygrad/viz/serve.py

Some trace events (eg. codegen UOp rewrite) can relate to other trace events (eg. a Program run on the GPU) in VIZ.
This was scattered in python/javascript. This diff pushes the complexity to python.

viz: resolve all graph references in python

---

tinygrad/runtime/graph/hcq.py

Before this patch the code could issues redundant syncs because of the typing issue. Current tests should cover all correctness checks.

hcq: remove redundant syncs and fix typing

---

extra/amdpci/am_smi.py

10 retries are not sufficient to stop mp-processes. 64 should be enough to cover our systems and kill all child pids when they get stuck

am_smi: increase kill retries

---

test/unit/test_viz.py
tinygrad/engine/realize.py
tinygrad/uop/ops.py
tinygrad/viz/serve.py

This refactor revealed itself during the work on TINY device and #11048, it's fundamental to different traces (UOps, ProfileEvents, Buffers, call to get_program, ....) relating to each other.
Multiple features use this:
Clicking A node in the Kernel graph can take you to the kernel rewrite.
Opening a kernel rewrite shows the rendered code and colored name.
ProfilerEvents in the timeline link to the related UOp viz. (eg. TINY device's `get_program for E_32` -> `E_32` RewriteStep viz)
TracingKey implements this linking in a generic way. Old VIZ used to specifically check for ProgramSpec, this cannot extend to TINY device and Buffer tracing.

viz: switch to TracingKey

---

test/unit/test_viz.py
tinygrad/uop/ops.py
tinygrad/viz/js/index.js
tinygrad/viz/serve.py

no-op changes that would add noise to the core TracingKey diff:
s/kernel_code/fmt, can be anything the user specifies: `VIZ=1 python test/unit/test_viz.py TestViz.test_tracing_key`
Also aligning spacing in the structs.

viz: renames and spacing changes to tracing 

---

test/test_ops.py

The test divides by 0, crashes in llvm, cpu. A conditional move doesn't branch so the division by 0 is always performed even if the condition is false.

remove invalid int div test

---

extra/torch_backend/backend.py
test/test_ops.py

Torch's aten operators make no sense at all

clean svd tests, set full_matrices false in torch backend

---

tinygrad/runtime/support/nv/ip.py

the signature of ucode=0x9 is the last one. on ada there were 2 of them, so this should be more general

nv: use last signature

---

tinygrad/opt/heuristic.py
tinygrad/opt/kernel.py

idea is to make it behave the same regardless of axis order and with empty 1s in shape.
not quite fully remove all first_upcast yet because some conditions used already upcasted size which need a separate benchmark to remove.

update heuristic to use k.upcastable_dims and k.unrollable_dims [pr]

---

tinygrad/opt/kernel.py

all reference to global used axis_types, so we don't need number of global helper that was used to locate GLOBAL

remove Kernel.global_dims [pr]

---

.github/workflows/test.yml
test/test_image_dtype.py
tinygrad/tensor.py

broke openpilot benchmark
Reverts tinygrad/tinygrad#11007

Revert "image_dot of 2 half inputs returns half"

---

test/unit/test_helpers.py
tinygrad/device.py
tinygrad/runtime/ops_cuda.py
tinygrad/runtime/ops_dsp.py
tinygrad/runtime/ops_hip.py

In some old parts we use `from_mv` to get address of a memoryview. Switch to a lightweight `mv_address` in such cases

replace from_mv with lightweight mv_address

---

test/external/process_replay/process_replay.py

Currently CI always import errors if filenames in core tinygrad change: https://github.com/tinygrad/tinygrad/actions/runs/16402863306/job/46344733955#step:11:54
When [pr] isn't explicitly enabled, ImportErrors can just exit early.

process replay: optionally pass tinygrad import error

---

test/test_remote.py
tinygrad/device.py
tinygrad/engine/schedule.py
tinygrad/kernelize/multi.py
tinygrad/runtime/ops_remote.py

For multihost bert step to be 1300 ms instead of 13 s.
Toposort change is to have a bunch of big graphs instead of a couple thousand graphs with 1-2 kernels each
Multi change is to do topology-aware allreduce, otherwise allreduces would be really slow
The group id approach is the simplest one, devices with multiple idxes and consts instead of colon is a big refactor that i don't have neither time nor motivation to do

Remote scheduler changes

---

test/unit/test_helpers.py
tinygrad/helpers.py

This bug caused some labels in VIZ to be cut off early:
Branch:
Master:

fix word_wrap with newlines in input string [pr]

---

tinygrad/runtime/support/hcq.py

`HCQ._at_profile_finalize` expects the device to be synchronized, since it calls `q_t().timestamp(d.timeline_signal).signal(d.timeline_signal, d.next_timeline()).submit(d)` without any wait (for precision).
The race condition occurred only with SQTT: `self.allocator._copyout(sqtt_buf := memoryview(bytearray(wptr)), buf0))`, which may have a profiling wrapper that signals.
Synchronization is added in `_at_profile_finalize`, as it is required for the function to proceed correctly.

hcq: fix race in _at_profile_finalize

---

tinygrad/device.py
tinygrad/uop/ops.py
tinygrad/viz/js/index.js
tinygrad/viz/serve.py

This creates a place for showing stats about execution(s) of a kernel in the UOp VIZ sidebar.
Starting with `duration` and `device`, will expand to utilization/occupancy as we make progress on sampling GPU counters.

viz: add runtime stats

---

tinygrad/engine/realize.py
tinygrad/viz/js/index.js

The cyan ones right after get_program are the compiler:
Same click logic should work with the "compile E_xx" nodes.

viz: profile the compiler in TINY device

---

test/external/process_replay/process_replay.py

```
During handling of the above exception, another exception occurred:
File "/opt/homebrew/Cellar/python@3.12/3.12.11/Frameworks/Python.framework/Versions/3.12/lib/python3.12/logging/__init__.py", line 1160, in emit
msg = self.format(record)
^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/Cellar/python@3.12/3.12.11/Frameworks/Python.framework/Versions/3.12/lib/python3.12/logging/__init__.py", line 999, in format
return fmt.format(record)
^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/Cellar/python@3.12/3.12.11/Frameworks/Python.framework/Versions/3.12/lib/python3.12/logging/__init__.py", line 703, in format
record.message = record.getMessage()
^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/Cellar/python@3.12/3.12.11/Frameworks/Python.framework/Versions/3.12/lib/python3.12/logg …
```

[process replay] fix double exception + add name,loc in error msg

---

test/unit/test_viz.py
tinygrad/engine/realize.py
tinygrad/helpers.py
tinygrad/viz/serve.py

Moving it to the ProgramSpec metadata, since no other tracing format uses this.

viz: remove TracingKey.fmt

---

test/test_nn.py

makes adding Conv3d test only a few lines
dim parameter is awkward but I can't really think of a cleaner way to do it while keeping a structure that supports future Conv3d testing; tinygrad's Conv2d layer needs an indicator to determine 3d-ness

extract conv layer test logic

---

tinygrad/runtime/support/nv/nvdev.py

we going to match ops_nv closer here and leave smaller addresses for python.
gpus still require 40bits for some addresses, so can't go as high as amd

nv: move base address higher

---

tinygrad/viz/js/index.js

This value is slightly different from GlobalCounters.total_mem,
A Buffer can have multiple total memory values in its lifetime, based on all alive buffers at the hovered position.
eg in beautiful_mnist, total starts at 2.11GB and goes to 1.5GB as nearby bufs free:

viz: show total mem in tooltip

---

tinygrad/viz/js/index.js

It's actually pretty useful to see the name in tooltip when label is off screen:
Though in master it's not correctly formatted:
Sharing logic with the sidebar/diff view.

viz: add support for colored tooltip text

---

test/external/process_replay/process_replay.py
tinygrad/engine/realize.py

The primary tinygrad path uses opts_to_apply and does not open devices.
I think these only exist for the tests:
https://github.com/tinygrad/tinygrad/pull/11536/files#diff-adab0964d07f15c3087f305d525bb095cbb74929ee56c095833836f409042276R32-R34
Currently process replay does not function correctly on the tests with no renderer/custom opts args:

pass opts arg in get_program process replay [pr]

---

examples/mlperf/model_train.py

MP=8 GRADIENT_ACC_STEPS=3 BS=1 DEFAULT_FLOAT=bfloat16 OPTIM_DTYPE=bfloat16 LLAMA3_SIZE=70B SEQLEN=512 PYTHONPATH=. MODEL=llama3 python3 examples/mlperf/model_train.py

model parallel llama

---

tinygrad/tensor.py

`((idx.unsqueeze(dim) <= idx.unsqueeze(dim+1))` is just a lower triangular. not clear why rewrite did not figure it out, but this made `JITBEAM=2 PYTHONPATH=. python3 examples/olmoe.py` 5% faster.
more can be done in topk by only compute the idx for the topk and not the full sorted stuff

rewrite sort idx

---

examples/yolov3.py

List of fixes:
1) Old url link is broken. Replaced with working one
2) Add explicitly .astype(np.float32), otherwise it raises `TypeError: underlying buffer is not writable`

fix bugs at examples/yolov3.py

---

extra/torch_backend/backend.py
extra/torch_backend/test.py

should fix #10697. the torch.linalg.cross decomposition indexes with a tensor returned from arange. the decomp doesn't specify a dtype for arange so the current arange implementation returns a float tensor (torch.get_default_dtype()). changed the implementation to match torch's, returning torch.int64 if no dtype is specified.

add arange dtype inference to tiny backend

---

tinygrad/device.py
tinygrad/helpers.py
tinygrad/viz/serve.py

Generic profiling events exist in helpers so they can be imported from everywhere in tinygrad.

move ProfilePointEvent out of device.py [pr]

---

test/test_profiler.py
tinygrad/runtime/ops_metal.py

in `TestMultiTensor.test_shrink_on_shard_axis` there is a reproducible failure:
```
opened device METAL from pid:93942
*** METAL      1 r_16_16                                      arg  1 mem  0.00 GB tm      9.50us/     0.01ms (     0.54 GFLOPS    0.0|1.9     GB/s) ['arange']
opened device METAL:1 from pid:93942
opened device METAL:2 from pid:93942
*** METAL      2 E_2_4                                        arg  2 mem  0.00 GB tm      9.00us/     0.02ms (     0.00 GFLOPS    0.0|0.0     GB/s) 
*** METAL:1    3 xfer       32, METAL:1 <- METAL              arg  2 mem  0.00 GB tm    245.83us/     0.26ms (     0.00 GFLOPS    0.0|0.0     GB/s) 
*** METAL:2    4 xfer       32, METAL:2 <- METAL:1            arg  2 mem  0.00 GB tm    177.79us/     0.44ms (     0.00 GFLOPS    0.0|0.0     GB/s) …
```

metal: workaround for transfers sync issue

---

tinygrad/viz/js/index.js

I think it looks more solid this way:
master right aligns the last tick, which makes values move too much when scrolling through time.

viz: always left align timeline values

---

test/unit/test_viz.py
tinygrad/uop/ops.py

Thinking of showing the error with NOOP as a placeholder:

show rewrite errors in viz

---

tinygrad/uop/__init__.py
tinygrad/uop/ops.py
tinygrad/viz/serve.py

VIZ uses this to display rewrite exceptions:

add Ops.REWRITE_ERROR

---

test/test_softmax_fusion.py
tinygrad/codegen/opt/kernel.py

hits `assert all_same(tensor_core_opts)`
first found in #11648 by running `sam2_heiar2_tiny` model with `FUSE_ARANGE`.
Spent way too much time trying to write a `FUSE_ARANGE` repro, so I found a way to hit it with `.fuse()` instead.

add fuse and tc opt bug repro

---

test/unit/test_viz.py
tinygrad/viz/index.html
tinygrad/viz/js/index.js
tinygrad/viz/serve.py

Splitting memory/timeline to different track lines, entirely specified by the server.
First step toward offloading the entire layout to server: #11639
The implementation for expanding y axis is much cleaner here too, layout cost is: O(n) for shapes in the clicked track + offset shift for the tracks below it + canvas redraw.

viz: defines tracks in python

---

test/unit/test_dtype.py
tinygrad/tensor.py

memoryview does not support it, but casting works fine so cast is fine

support bf16 and fp8 in Tensor.tolist

---

test/test_symbolic_ops.py
test/test_tiny.py
tinygrad/schedule/rangeify.py
tinygrad/uop/ops.py

reshape should not be able to introduce symbolic variables, it doesn't make sense.

fix symbolic usage. use shrink, not reshape

---

test/unit/test_dtype_spec.py
tinygrad/dtype.py

truncate_fp16 cleanup

---

test/unit/test_attention.py
test/unit/test_llm_tokenizer.py
tinygrad/apps/llm.py

i worked on fixing the #Note/TODO comments to optimize RoPE so that JIT prunes rope cache outside the kernel. Jit can now optim and prune redundant rope comp by seing consistent tensor shape T + start_pos. I think now there is much better computation pattern and precision. Tried to make the math and code compact and in a few lines as possible.

rope cache optim for jit prune in llm.py

---

test/unit/test_viz.py
tinygrad/engine/realize.py
tinygrad/helpers.py
tinygrad/uop/ops.py
tinygrad/viz/js/index.js
tinygrad/viz/serve.py

Prereq for correctly coloring BEAM workers in the TINY device timeline:
Main process does schedule (green) -> get_program (blue)
[...TINY:pid] are the workers doing codegen. This is a UI no-op for single process profiles.

viz: color by name

---

tinygrad/viz/serve.py

Easier than os.path calls for traversing a directory in multi process tracing.

switch viz command line args to pathlib

---

test/unit/test_viz.py
tinygrad/viz/serve.py

These are all just packed trace event bytes.
The "shapes" and "buffers" names survived the viz/serve.py refactors.

viz: more consistent naming of events

---

test/unit/test_viz.py
tinygrad/helpers.py
tinygrad/viz/js/index.js
tinygrad/viz/serve.py

It's a helper that can insert marker lines in the timeline, eg:
```
(a+b).realize()
profile_marker("test 1")
(a*b).realize()
profile_marker("test 2")
```
renders:

viz: add python marker

---

tinygrad/uop/ops.py

broadcast is clearer than having to know that a UPat src means broadcast
relevant for #11611

broadcast for upat

---

test/unit/test_viz.py

Mainly the nested tree and Python location also work without `@track_rewrites`.

some viz tests don't need track_rewrites

---

test/test_dtype_alu.py

failures:
https://github.com/tinygrad/tinygrad/actions/runs/17490320000/job/49679581331?pr=12022#step:6:125
https://github.com/tinygrad/tinygrad/actions/runs/17490863451/job/49680153804?pr=12023#step:6:125
Can still be wrong if lhs outputs nan and stays float. Since it lhs gets casted to `dtypes.int32` later we don't fuzz that case.

exclude op2 nan lt in test_dtype_alu

---

tinygrad/viz/index.html
tinygrad/viz/js/index.js

- In master resizing happens even if the profiler page is hidden. The bug is easy to repro:
1. Resize the window in UOp VIZ
2. Navigate to Profiler, canvas collapses to 0px.
- min-width -> width to keep the layout in predictable, integer pixels. Longer names (like DISK paths) are scrollable:

viz: small profiler resizing improvements

---

.github/workflows/test.yml
test/test_ops.py

skip with SKIP_SLOW_TEST and decorators

clean up skip slow tests in PYTHON

---

tinygrad/codegen/opt/postrange.py

Currently codegen launches BEAM search even if the Opts are pre specified in the AST. This makes the process replay of anything that ran with BEAM=2 non deterministic.

do not launch BEAM when opts_to_apply exists [pr]

---

examples/sdxl.py

NULL backend passed validation before because both desired and actual went through NULL backend

don't validate output in sdxl with fakeweights

---

tinygrad/viz/index.html
tinygrad/viz/js/index.js
tinygrad/viz/serve.py

This isn't displayed at all in the default VIZ view, not planning to turn it on by default. The UOp rewrite page should focus on displaying rewrites, not profiler/timing data.

viz: remove unused runtime_stats feature

---

extra/models/inception.py

Part of #11304.
This diff enables the Inception model to load weights from an arbitrary path. This lets us load the official mlperf inception checkpoint, downloaded from mlcommons as part of #12170. This model is used in eval of Stable Diffusion v2 training.

Load weights from any path to inception model, for SD mlperf training eval

---

.github/workflows/benchmark.yml

account for compile cache, and it's annoying that job died due to timeout also messes the machine

increase benchmark timeout

---

tinygrad/schedule/rangeify.py

Basically resolve had the incorrect default argument 
`j != 1` would resolve to false implying that that the range doesnt end

fix map_expand for symbolic shapes

---

test/test_schedule.py
tinygrad/schedule/rangeify.py

Since symbolic can const fold the COPY parent, the COPY(CONST) simplifier should apply after it.
This removes a whole class of "IndexError: tuple index out of range" bugs in test_multitensor, these happen because a COPY(CONST) scheduled.
```
VIZ=1 RANGEIFY=1 PYTHONPATH=. python test/test_multitensor.py TestBatchNorm.test_batchnorm
```

rangeify: fix COPY simplifier

---

test/test_schedule.py
tinygrad/schedule/rangeify.py

a lot of these are failing
Because pm_cleanups removes the bufferizes of COPY's parent.
In the current design, REALIZE can be removed. But realize before a COPY (even if it's a system op), needs to always happen.
We need a way to express this. maybe even insert **contiguous** between COPY and its parents.
update: it's fine if you push the compute to the other device. But currently rangeify is either silently wrong or runtime asserts.

rangeify: fix copy size mismatch errs

---

test/unit/test_disk_tensor.py

Tested on tinyg3, 
```
~/code/tinygrad ((HEAD detached at 5e794be8a)) > DEBUG=1 CL=1 python test/unit/test_disk_tensor.py TestDiskTensor.test_bf16_disk_write_read
PYTHON: using PythonCompiler
opened device PYTHON from pid:25061
CLDevice: got 1 platforms and 6 devices
4141
CLDevice: opening NVIDIA GeForce RTX 4090 with version 570.133.20
CL: using CLCompiler
opened device CL from pid:25061
DISK:/tmp/dt_bf16_disk_write_read_f32: using Compiler
opened device DISK:/tmp/dt_bf16_disk_write_read_f32 from pid:25061
scheduled 2 kernels in 534.03 ms
DISK:/tmp/dt_bf16_disk_write_read_bf16: using Compiler
opened device DISK:/tmp/dt_bf16_disk_write_read_bf16 from pid:25061
scheduled 2 kernels in 1.67 ms
[17948. 49024. 50298. 50716. 16800.]
F
============================================================= …
```

skip test_bf16_disk_write_read on CL=1

---

tinygrad/viz/js/index.js

VIZ colors the flamegraph by call depth. The deeper the brighter.
Our normal traces usually don't go deeper than 4 layers, but if there are custom `cpu_profile` some deep calls lighten to white and label becomes unreadable:
This diff caps it to a reasonably dark color

viz: put a limit of brightness scale

---

tinygrad/viz/serve.py

Makes the rangeify multi graph more readable:
We can remove this once vars move to src.

srender UOp in movement op arg

---

tinygrad/uop/symbolic.py

fixes loop in `RANGEIFY=1 PYTHONPATH=. ASSERT_MIN_STEP_TIME=85 NULL=1 STEPS=10 python3 examples/hlb_cifar10.py`

filter vconst

---

.github/workflows/test.yml
tinygrad/schedule/rangeify.py

In master, RANGEIFY does not realize `t.shard(devices_4, 0).realize()`. This is because it only supports mapping Tensors to one BUFFERIZE. The sharded Tensor (tag 1) stacks 4 BUFFERIZEs:
```
RANGEIFY=1 PYTHONPATH=. VIZ=1 python test/test_multitensor.py TestHandleData.test_copied_to_device
```

rangeify: fix sharding

---

tinygrad/schedule/rangeify.py

eg `VIZ=1 CPU=1 RANGEIFY=1 python test/test_assign.py TestAssign.test_post_permuted_assignment` was creating extra tags

rangeify: fix empty tags in reshapes

---

tinygrad/tensor.py

This probably existed when there was a mutable .lazydata on the Tensor with a forced_realize attribute on it. It absolutely does nothing in the new Tensor with immutable UOp world.

remove no-op contiguous from rand

---

.github/workflows/test.yml
tinygrad/schedule/rangeify.py
tinygrad/uop/ops.py

The INDEX walks to the MSTACK:
And the realized assign matcher also checks MSTACK sources. This assign still gets removed:
with this, down to 2 failing multi tests:
`RANGEIFY=1 python3 -m pytest -n=auto ./test/test_multitensor.py`
```
FAILED test/test_multitensor.py::TestMultiTensor::test_multi_const_folding - AssertionError: 7 != 0
FAILED test/test_multitensor.py::TestMultiTransformer::test_transformer - AssertionError: UOp sources must have the same shape UOp(Ops.MUL, dtypes.float, arg=None, tag=(37,), src=(
======================================================================================= 2 failed, 90 passed, 19 skipped, 3 xfailed, 14 warnings in 6.24s =======================================================================================
```

rangeify: enable assign to mstack target

---

.github/workflows/test.yml
extra/remu/src/thread.rs
test/test_ops.py

test_masked_select is still very slow for the emulator...
`CI=1 FORWARD_ONLY=1 AMD_LLVM=0 PYTHONPATH=. AMD=1 RANGEIFY=1 python3 test/test_ops.py TestOps.test_masked_select`
The slowness also happens for the PYTHON backend.

remu: add new instructions introduced in RANGEIFY

---

tinygrad/codegen/__init__.py
tinygrad/uop/ops.py

why doesn't this work?
edit: two bugs
1. It was shaping INDEX(MSELECT) - MSELECT is MSTACK is BUFFER is BUFFERIZE in this context. None of them have shape.
2. Codegen cache wasn't accounting for RANGEIFY=1 context var (it doesn't need to in master)

rangeify: ban view pushing

---

tinygrad/viz/js/worker.js

It was giving the wrong text widths:
master:
branch:

viz: add font-weight to OffscreenCanvas config

---

test/test_multitensor.py
test/test_remote.py

It got lucky because Tensor.zeros is a CONST and no buffers asserted. We don't support assigning from a multi device to a single device (eg. without an MSELECT in between)

skip test_multihost_aware_schedule, assign devices mismatch 

---

.github/workflows/test.yml
tinygrad/schedule/rangeify.py

It was bufferizing an op with MSTACK sources to a single device Buffer.
easy to repro on non-webgpu with:
`METAL=1 MAX_KERNEL_BUFFERS=6 RANGEIFY=1 PYTHONPATH=. python test/test_multitensor.py TestBatchNorm.test_batchnorm`

fix limit_bufs with multi

---

tinygrad/schedule/rangeify.py

```
RANGEIFY=1 PYTHONPATH=. NULL=1 DEFAULT_FLOAT=HALF BENCHMARK=10 BS=8 GPUS=2 BERT_LAYERS=2 MODEL=bert python3 examples/mlperf/model_train.py
```
passes now.
MSTACK/MSELECT behave like BUFFER, they're global and jump to the outerworld.

don't tag MSTACK/MSELECT on global buffers

---

test/test_assign.py

I think only `a != b` is correct, sadly both behaviors exist.

add a test for untested Tensor.assign behavior

---

tinygrad/runtime/ops_remote.py
tinygrad/runtime/support/ib.py

RuntimeError, since this can happen with the link and should be handled. assert represents the wrong state and a potential bug.

remote: raise runtimeerror in checkz

---

test/test_schedule.py
tinygrad/schedule/rangeify.py

`RANGEIFY=1 MAX_BUFFER_SIZE=0 NULL=1 python examples/beautiful_mnist_multigpu.py` failure was pretty simple, it's an issue with CONST/COPY. The old multi stuff expected a direct edge to CONST:
https://github.com/tinygrad/tinygrad/blob/c1e85f699c1b3cf7db9e10a367a6feef69ecc6ec/tinygrad/schedule/multi.py#L120-L125
It doesn't work like this in rangeify (no view pushing).
It's easier to reason about these in rangeify earliest_rewrites though, I thought of modifying multi.py but that's gonna go away.

early copy fixup

---

test/unit/test_simplify_valid_idx.py
tinygrad/uop/symbolic.py

unsupported statements are handled in uop_given_valid already. the test failed because (100%x) somehow got simplified

remove skipping cast in simplify_valid [pr]

---

tinygrad/viz/serve.py

It's because in the old scheduler we still do CONST(VIEW) and that VIEW shouldn't dangle when const gets removed from the graph:
master vs branch:
In codegen it's already VIEW(CONST) so this isn't a problem

update viz to not use children [pr]

---

test/models/test_real_world.py

Asserts when running `python3 -m pytest -n=auto test/` on macbook. CI=1 uses a smaller gpt2 for speed.

update gpt2 kernel count tests in CI=0

---

examples/train_resnet.py

fix for #12513 
The `mode='L'` parameter in `Image.fromarray()` calls is deprecated in Pillow and triggers deprecation warnings. According to [PIL documentation](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.fromarray), the `mode` parameter is deprecated and Pillow now reliably auto-detects the appropriate mode from array data.
Remove the explicit `mode='L'` parameter since Pillow's auto-detection correctly identifies the mode as `'L'` (grayscale) for the input data.
- Verified that after removal, Pillow correctly auto-detects `'L'` mode for all input images
- Confirmed the model trains successfully without any behavior changes
- Elimination of deprecation warnings
```python
lambda x: [Image.fromarray(xx, mode='L').resize((64, 64)) for xx in x]
```
```python …
```

fix fromarray deprecation in example/train_resnet.py
